<?php /**@var \Application\Entity\NmtApplicationDocNumber $entity ;*/?>

<?php
if (count ( $errors ) > 0) {
	echo '<div class="alert alert-danger" role="alert" style="font-size: 10.5pt">';
	
	echo '<ul>';
	foreach ( $errors as $error ) :
		echo '<li>' . $error . '</li>';
	endforeach
	;
	echo '</ul>';
	echo '</div>';
}
?>

<div id="tabs" style="font-size: 9.5pt">
	<ul>
		<li><a href="#general"><small><i class="glyphicon glyphicon-pencil"></i></small>&nbsp;Document Number Range</a></li>
	</ul>

	<div id="general" style="font-size: 9pt">

		<form id="Create_Form" class="form-horizontal"
			action="/application/doc-number/edit" method="post" enctype="multipart/form-data">
			<input type="hidden" name="redirectUrl"
				value="<?php echo $redirectUrl ?>" />
<input type="hidden" name="entity_id" value="<?php echo (!$entity== null)? $entity->getId():"";?>" />
<input type="hidden" name="token" value="<?php echo (!$entity== null)? $entity->getToken():"";?>" />
				
				
			<fieldset>
				<legend style="font-size: 9.5pt; color: gray;">
					<small><span class="glyphicon glyphicon-triangle-right"></span></small>&nbsp;
					<a href="#invoice_header" class="" data-toggle="collapse">HEADER:</a>
				</legend>
				<div id="invoice_header" class="collapse in">
				
					<div class="form-group margin-bottom">
						<label class="control-label col-sm-2">Subject class:</label>
						<div class="col-sm-3">
							<input class="form-control input-sm" type="text" placeholder=""
								id="subjectClass" name="subjectClass" 
								value="<?php echo (!$entity == null)? $entity->getSubjectClass():"";?>">
						</div>
						
					</div>
					<div class="form-group margin-bottom required">
						<label class="control-label col-sm-2">Document Number Range:</label>
						<div class="col-sm-3">
							<input class="form-control input-sm" type="text" placeholder=""
								id="docNumberName" name="docNumberName" 
								value="<?php echo (!$entity == null)? $entity->getDocNumberName():"";?>">
						</div>
					
   			  			<div class="col-sm-3">
							<input
								<?php if(!$entity== null): echo ($entity->getIsActive()=="1")?"checked":""; else: echo "checked"; endif;?>
								type="checkbox" name="isActive" value="1">&nbsp;Is Active&nbsp;&nbsp;&nbsp;&nbsp;

						</div>
   					
   					</div>
   					
   					<div class="form-group margin-bottom">
						<label class="control-label col-sm-2">Prefix:</label>
						<div class="col-sm-3">
							<input class="form-control input-sm" type="text" placeholder=""
								id="prefix" name="prefix" 
								value="<?php echo (!$entity == null)? $entity->getPrefix():"";?>">
						</div>
						
					</div>
			
					<div class="form-group margin-bottom required">
						<label class="control-label col-sm-2">From Number:</label>
						<div class="col-sm-3">
							<input class="form-control input-sm" type="text" placeholder=""
								id="fromNumber" name="fromNumber" 
								value="<?php echo (!$entity == null)? $entity->getFromNumber():"";?>">
						</div>
						<label class="control-label col-sm-2">To Number:</label>
						<div class="col-sm-3">
							<input class="form-control input-sm" type="text" placeholder=""
								id="toNumber" name="toNumber" 
								value="<?php echo (!$entity == null)? $entity->getToNumber():"";?>">
						</div>
						
					</div>
					<div class="form-group margin-bottom">
						<label class="control-label col-sm-2">Suffix:</label>
						<div class="col-sm-3">
							<input class="form-control input-sm" type="text" placeholder=""
								id="suffix" name="suffix" 
								value="<?php echo (!$entity == null)? $entity->getSuffix():"";?>">
						</div>
						
					</div>
						<div class="form-group margin-bottom">
					<label class="control-label col-sm-2" >Remarks:</label>
            		<div class="col-sm-8">
            			<input class="form-control input-sm" type="text"  placeholder=""
            				name="remarks" value="<?php echo (!$entity == null)? $entity->getRemarks():"";?>">
            		</div>
				</div>
					
					
			</div>
					
				<hr>
				<div class="form-group margin-bottom">
						<label class="control-label col-sm-2" for="inputTag"></label>
						<div class="col-sm-3">
	   	<button onclick="submitForm('Create_Form');" class="btn btn-default btn-sm"><i class="glyphicon glyphicon-floppy-disk"> </i> Save</button>
							<a tabindex="11" class="btn btn-default btn-sm"
								href="<?php echo $this->baseUrl ?>/inventory/serial-number/list"><small><i
									class="glyphicon glyphicon-remove"></i></small>&nbsp;Cancel</a>
	
						</div>
					</div>
			</fieldset>
		</form>
	</div>
</div>



<script>
  
</script>

