<a class="btn btn-default" href="#"><small><i class="glyphicon glyphicon-upload"> </i></small>&nbsp;New Warning Letter</a>
<hr>
<table style="font-size: 10pt;" class="table table-bordered table-hover">
	<thead>
		<tr>
			<td><b>#</b></td>
			<td><b>Warning Date</b></td>
			<td><b>Warning Reason</b></td>
			<td><b>Issued By</b></td>
			<td><b>Action</b></td>
		</tr>
	</thead>
    	
	<tbody>
 	<tr>
    			<td>1</td>
    			<td>10-06-2017</td>
    			<td>Cut Fabric wrong</td>
    			<td>Thomas</td>
    			<td>see suporting Document</td>
    		</tr>
 </tbody>
</table>
 
