<?php 
/**@var \Application\Entity\NmtProcurePr $target ;
 * @var \Application\Entity\NmtProcurePrRow $entity ;
 */

?>
<?php
if (count ( $errors ) > 0) {
	echo '<div class="alert alert-danger" role="alert" style="font-size: 10.5pt">';
	
	echo '<ul>';
	foreach ( $errors as $error ) :
		echo '<li>' . $error . '</li>';
	endforeach
	;
	echo '</ul>';
	echo '</div>';
}
?>

<div id="tabs" style="font-size: 9.5pt">
	<ul>
		<li ><a href="#general"><small><i class="glyphicon glyphicon-plus"> </i></i></small>&nbsp;New Row</a></li>
     	<li ><a href="<?php echo $this->baseUrl ?>/procure/pr-row/list1?token=<?php echo (!$target == null)? $target->getToken():"";?>&target_id=<?php echo (!$target == null)? $target->getId():"";?>"><small><i class="glyphicon glyphicon-list"> </i></i></small>&nbsp;Current Rows</a></li>
 
			<li><a
			href="/procure/pr-attachment/get-pictures?token=<?php echo (!$target == null)? $target->getToken():"";?>&checksum=<?php echo (!$target == null)? $target->getChecksum():"";?>&target_id=<?php echo (!$target == null)? $target->getID():"";?>"><small></small><span class="glyphicon glyphicon-picture"></span></span>&nbsp;Picture</a></li>
			<li><a
			href="/procure/pr-attachment/list1?token=<?php echo (!$target == null)? $target->getToken():"";?>&checksum=<?php echo (!$target == null)? $target->getChecksum():"";?>&target_id=<?php echo (!$target == null)? $target->getID():"";?>">
			<small><span class="glyphicon glyphicon-paperclip"></span></small>&nbsp;Attachment</a></li>
	</ul>

	<div id="general" style="font-size: 9pt;">
		
		
		<form id="pr_header_form" class="form-horizontal"
			action="" method="post" enctype="multipart/form-data">
			<input type="hidden" name="redirectUrl"
				value="<?php echo $redirectUrl ?>" />

			<fieldset>
				<legend style="font-size: 9.5pt; color: gray;">
					<small><span class="glyphicon glyphicon-triangle-right"></span></small>&nbsp;
								<a href="#pr_header" class="" data-toggle="collapse">PR HEADER: <?php echo (!$target == null)? "(". $target->getPrAutoNumber() .")" :"";?></a>
	
				</legend>
				<div id="pr_header" class="collapse">

					<div class="form-group margin-bottom">
						<label class="control-label col-sm-2">PR Number:</label>
						<div class="col-sm-3">
							<input class="form-control input-sm" type="text" placeholder=""
								name="prNumber"
								value="<?php echo (!$target == null)? $target->getPrNumber():"";?>">
						</div>

						<label class="control-label col-sm-1" for="inputTag"></label>
						<div class="col-sm-4">
							<input
								<?php if(!$target == null): echo ($target->getIsActive()=="1")?"checked":""; else: echo "checked"; endif;?>
								type="checkbox" name="isActive" value="1">&nbsp;Active&nbsp;&nbsp;
							<input
								<?php if(!$target == null): echo ($target->getIsDraft()== "1")?"checked":""; else: echo "checked"; endif;?>
								type="checkbox" name="isDraft" value="1">&nbsp;Draft&nbsp;&nbsp;

						</div>

					</div>

					<div class="form-group margin-bottom">
						<label class="control-label col-sm-2">PR Name:</label>
						<div class="col-sm-3">
							<input class="form-control input-sm" type="text" placeholder=""
								id="prName" name="prName"
								value="<?php echo (!$target == null)? $target->getPrName():"";?>">
						</div>

						<label class="control-label col-sm-2">Keywords:</label>
						<div class="col-sm-3">
							<input class="form-control input-sm" type="text" placeholder=""
								id="keywords" name="keywords"
								value="<?php echo (!$target == null)? $target->getKeywords():"";?>">
						</div>
					</div>
					
						<div class="form-group margin-bottom">
		<label class="control-label col-sm-2" >Date:</label>
		<div class="col-sm-3">
<input class="form-control input-sm" type="text"  placeholder="" id = "submittedOn" name="submittedOn" 
value="<?php if(!$target == null): if ($target->getSubmittedOn() !== null): echo date_format($target->getSubmittedOn(),"Y-m-d"); endif; endif;?>" placeholder =" please select"/>
		</div>
	</div>

					<div class="form-group margin-bottom">
						<label class="control-label col-sm-2">Department</label>
						<div class="col-sm-3">
							<input disabled class="form-control input-sm" type="text"
								id="department_name" placeholder="Please select!"
								name="deparment_name"
								value="<?php if (!$target== null):if($target->getDepartment()!==null):echo $target->getDepartment()->getNodeName(); endif;endif;?>">

							<input type="hidden" class="form-control input-sm"
								id="department_name_selected" placeholder="Please select!"
								name="department_id"
								value="<?php if (!$target== null):if($target->getDepartment()!==null):echo $target->getDepartment()->getNodeId(); endif;endif;?>">
						</div>

						<a style="color: #0080ff;" href="javascript:;"
							onclick="showBootstrapDialog('Select Deparment','/application/department/list1','b_loaded_data');">Select&nbsp;&nbsp;<i
							class="glyphicon glyphicon-folder-open"></i>
						</a>
					</div>

					<div class="form-group margin-bottom">
                		<label class="control-label col-sm-2" >Remarks:</label>
                		<div class="col-sm-8">
                			<input class="form-control input-sm" type="text"  placeholder=""
                				name="itemDescription" value="<?php echo (!$target == null)? $target->getRemarks():"";?>">
                		</div>
					</div>

					<div class="form-group margin-bottom">
						<label class="control-label col-sm-2" for="inputTag"></label>
						<div class="col-sm-3">
							<a class="btn btn-default btn-sm"
								href="<?php echo $this->baseUrl ?>/procure/pr/edit?token=<?php echo (!$target == null)? $target->getToken():"";?>&entity_id=<?php echo (!$target == null)? $target->getId():"";?>&checksum=<?php echo (!$target == null)? $target->getChecksum():"";?>"><small><i
									class="glyphicon glyphicon-pencil"></i></small>&nbsp;Edit</a>

						</div>
					</div>

				</div>
			</fieldset>
			
		</form>
	
		

		<!-- TO UPDATE ACTION -->
		<form id="pr_row_form" class="form-horizontal"
			action="/procure/pr-row/add" method="post"
			enctype="multipart/form-data">
			<input type="hidden" name="target_id"
				value="<?php echo (!$target == null)? $target->getId():"";?>" /> <input
				type="hidden" name="token"
				value="<?php echo (!$target== null)? $target->getToken():"";?>" /> <input
				type="hidden" name="redirectUrl" value="<?php echo $redirectUrl ?>" />
				
				
				<fieldset>
				<legend style="font-size: 9pt; color: gray;">
					<small><span class="glyphicon glyphicon-triangle-right"></span></small>&nbsp;
					<a href="#transaction" class="" data-toggle="collapse">PR ROW:</a>
				</legend>
				<div id="transaction" class="collapse in">
				
				<div class="form-group margin-bottom">
		<label class="control-label col-sm-2">Row Number: </label>
		<div class="col-sm-1">
			<input tabindex="0" class="form-control input-sm" type="text" id="rowNumber" name="rowNumber" 
value="<?php if (!$entity== null):if($entity->getRowNumber()==null):echo $max_row_number + 1;else:echo $entity->getRowNumber();endif;else:echo $max_row_number + 1;endif;?>">
		</div>
	</div>
					<div class="form-group margin-bottom">
				<label class="control-label col-sm-2">Item: </label>
				<div class="col-sm-3">
					<input tabindex= "1" class="form-control input-sm" type="text" id="item_name"
						placeholder="Enter keyword to search item..." name="item_name"
						value="<?php if (!$entity== null): if($entity->getItem()!==null): echo $entity->getItem()->getItemName(); endif;endif;?>">


					<input type="hidden" id="item_id" placeholder="" name="item_id"
						value="<?php if (!$entity== null): if($entity->getItem()!==null): echo $entity->getItem()->getID(); endif;endif;?>">
				</div>
				<div class="col-sm-3">
				<a style="color: #0080ff;" href="javascript:;"
					onclick="showJqueryDialog('Select Item','1300',$(window).height()-80, '/inventory/item-search/do1?target_id=item_id&target_name=item_name','j_loaded_data', true);">Select&nbsp;&nbsp;<i
					class="glyphicon glyphicon-folder-open"></i>
				</a>
							
				</div>
				<div class="col-sm-3">
					<a target="_blank" style="font-size: 9pt;" href="/inventory/item/list">Item List&nbsp;&nbsp;</a><small><i class="glyphicon glyphicon-new-window"></i></small>
				</div>

			</div>

			<div class="form-group margin-bottom">
				<label class="control-label col-sm-2">Item Name:</label>
				<div class="col-sm-3">
					<input tabindex= "2" class="form-control input-sm" type="text" placeholder=""
						name="rowName" id="rowName"
					value="<?php echo (!$entity== null)? $entity->getRowName():"";?>">
				
				</div>
				 <div class="col-sm-3">
					<input  	<?php if(!$entity == null): echo ($entity->getIsActive()=="1")?"checked":""; else: echo "checked"; endif;?>
						type="checkbox" name="isActive" value="1" >&nbsp;Active&nbsp;&nbsp;
				</div>
			</div>

					<div class="form-group margin-bottom required">
						<label class="control-label col-sm-2">Quantity:</label>
						<div class="col-sm-3">
							<input tabindex= "3" class="form-control input-sm" type="text" placeholder=""
								name="quantity" id="quantity"
								value="<?php echo (!$entity== null)? $entity->getQuantity():"";?>">
						</div>
					</div>

					<div class="form-group margin-bottom required">
						<label class="control-label col-sm-2">Unit:</label>
						<div class="col-sm-3">
							<input  tabindex= "4" class="form-control input-sm" type="text" placeholder=""
								name="rowUnit" id="rowUnit"
								value="<?php echo (!$entity== null)? $entity->getRowUnit():"";?>">
						</div>

						<label class="control-label col-sm-2">Conversion Factor:</label>
						<div class="col-sm-3">
							<input tabindex= "5" class="form-control input-sm" type="text" placeholder=""
								name="conversionFactor" id="conversionFactor"
								value="<?php echo (!$entity== null)? $entity->getConversionFactor():"1";?>">
						</div>

					</div>

					<div class="form-group margin-bottom required">
						<label class="control-label col-sm-2">Expected Delivery:</label>
						<div class="col-sm-3">
							<input tabindex= "6" class="form-control input-sm" type="text" name="edt"
								value="<?php if(!$entity == null): echo ($entity->getEdt() !== null)? date_format($entity->getEdt(),"Y-m-d"):""; endif;?>"
								placeholder=" please select" id="edt" />
						</div>
					</div>
					
					<div class="form-group margin-bottom">
                		<label class="control-label col-sm-2" >Remarks:</label>
                		<div class="col-sm-8">
                			<input tabindex= "7" class="form-control input-sm" type="text"  placeholder=""
                				name="itemDescription" value="<?php echo (!$entity == null)? $entity->getRemarks():"";?>">
                		</div>
                	</div>

				</div>
			</fieldset>
				
				

			

			<fieldset>
				<legend style="font-size: 9pt; color: gray;">
					<small><span class="glyphicon glyphicon-triangle-right"></span></small>&nbsp;
					<a href="#reference" class="" data-toggle="collapse">REFERENCE:</a>
				</legend>

				<div id="reference" class="collapse in">
				<div class="form-group margin-bottom">
					<label class="control-label col-sm-2">For Project: </label>
					<div class="col-sm-3">
						<input disabled class="form-control input-sm" type="text" id="project_name"
							placeholder="Select Project if any" name="project_name"
							value="<?php if (!$entity== null): if($entity->getProject()!==null): echo $entity->getProject()->getProjectName(); endif;endif;?>">


						<input type="hidden" id="project_id" placeholder=""
							name="project_id"
							value="<?php if (!$entity== null): if($entity->getProject()!==null): echo $entity->getProject()->getID(); endif;endif;?>">
					</div>
					
					<div class="col-sm-3">
					<a style="color: #0080ff;" href="javascript:;"
						onclick="showJqueryDialog('Select Project','960',$(window).height()-100, '/pm/project-search/do1?target_id=project_id&target_name=project_name','j_loaded_data', true);">Select&nbsp;&nbsp;<i
						class="glyphicon glyphicon-folder-open"></i>
					</a>

							
					</div>
    				<div class="col-sm-3">
    					<a target="blank" style="font-size: 9pt;" href="/pm/project/list">Project List&nbsp;&nbsp;</a><small><i class="glyphicon glyphicon-new-window"></i></small>
    				</div>
				</div>
				</div>
			</fieldset>
			<hr>
			<div class="form-group margin-bottom">
				<label class="control-label col-sm-2" for="inputTag"></label>
				<div class="col-sm-3">

					<a tabindex="7" class="btn btn-default btn-sm" style="" href="javascript:;"
						onClick="submitForm('pr_row_form');"> <small><i
							class="glyphicon glyphicon-floppy-disk"> </i></small>&nbsp;Save
					</a>
					<a tabindex="8" class="btn btn-default btn-sm"
								href="<?php echo $this->baseUrl ?>/procure/pr/show?token=<?php echo (!$target == null)? $target->getToken():"";?>&entity_id=<?php echo (!$target == null)? $target->getId():"";?>&checksum=<?php echo (!$target == null)? $target->getChecksum():"";?>"><small><i
									class=""></i></small>&nbsp;Cancel</a>
				</div>
			</div>


		</form>
	</div>
</div>

<script type="text/javascript">

	$("#pr_header_form :input").attr("disabled", "disabled");

	$( "input[id='edt']").datepicker({ firstDay: 1, dateFormat: 'yy-mm-dd',closeText: 'X',changeMonth: true, changeYear: true});

    $( "#item_name" ).autocomplete({
     source: "/inventory/item-search/auto-complete",
     minLength: 2,
     select: function( event, ui ) {
   	  $( "#item_id" ).val(ui.item.id);
     
   	 	$('#global-notice').show();
   		$('#global-notice').html('"' + ui.item.value + '" selected');
   		$('#global-notice').fadeOut(5000);
   		//$("#jquery_dialog").dialog("close");
     }
    
   })
   .autocomplete( "instance" )._renderItem = function( ul, item ) {
	  var serial_no = "";
	  if(item.item_serial!=""){
		  serial_no = " : " + item.item_serial;
	  }
 	   
      return $( "<li>" )
        .append( "<div style='padding-bottom: 5px; border-bottom: thin solid gray;'><span style='font-size: 9.5pt;font-weight: bold;'>" + item.value + "</span><br><span style='color:gray;font-size: 9pt;'>" + item.item_sku + serial_no +"<span></div>" )
        .appendTo( ul );
    };
   ;
    

    $("#item_name").focus();
</script>

