
<div>
	<small><span class="glyphicon glyphicon-filter"></span></small>&nbsp;<a
		href="#transaction" class="" data-toggle="collapse">FILTER</a>
</div>
<div id="transaction" class="collapse">

	<div
		style="border: 1px; padding: 3px; font-size: 10pt; background: url(/images/bg1.png); background-repeat: repeat-x; background-color: #FFFFFF;">

		<form id="filter_form" class="form-horizontal"
			action="<?php echo $this->baseUrl ?>/procure/pr-row/all" method="get"
			enctype="multipart/form-data">

			<div class="form-group">
				<label class="control-label col-sm-2" for="inputTag">PR Year</label>
				<div class="col-sm-3">
					<select name="pr_year" class="form-control">
						<option value="0">All</option>
						<option <?php echo $pr_year=='2016'? "selected='selected'":"";?>
							value="2016">2016</option>
						<option <?php echo $pr_year=='2017'? "selected='selected'":"";?>
							value="2017">2017</option>
						<option <?php echo $pr_year=='2018'? "selected='selected'":"";?>
							value="2018">2018</option>
						<option <?php echo $pr_year=='2019'? "selected='selected'":"";?>
							value="2019">2019</option>
						<option <?php echo $pr_year=='2020'? "selected='selected'":"";?>
							value="2020">2020</option>
					</select>
				</div>
			</div>

			<div class="form-group">
				<label class="control-label col-sm-2" for="inputTag">PR Row Balance</label>
				<div class="col-sm-3">
					<select name="balance" class="form-control">
						<option value="2">All</option>
						<option <?php echo $balance=='0'? "selected='selected'":"";?>
							value="0">Balance=0 (Fulfilled Items)</option>
						<option <?php echo $balance=='1'? "selected='selected'":"";?>
							value="1">Balance>0 (Pending Items)</option>
						<option <?php echo $balance=='-1'? "selected='selected'":"";?>
							value="-1">Balance<0 (Some Free Items)</option>
					</select>
				</div>
			</div>

			<div class="form-group">
				<label class="control-label col-sm-2" for="inputTag">Active Items</label>
				<div class="col-sm-3">
					<select class="form-control" name="is_active">
						<option <?php echo $is_active ==''? "selected='selected'":"";?>
							value="">All</option>
						<option <?php echo $is_active=='1'? "selected='selected'":"";?>
							value="1">Active</option>
						<option <?php echo $is_active=='-1'? "selected='selected'":"";?>
							value="-1">Inactive</option>
					</select>
				</div>
			</div>

			<div class="form-group">
				<label class="control-label col-sm-2" for="inputTag">Sort by</label>
				<div class="col-sm-3">
					<select class="form-control" name="sort_by">
						<option value="">None</option>
						<option
							<?php echo $sort_by=='itemName'? "selected='selected'":"";?>
							value="itemName">Item Name</option>

						<option
							<?php echo $sort_by=='prNumber'? "selected='selected'":"";?>
							value="prNumber">Pr Number</option>
						<option
							<?php echo $sort_by=='vendorName'? "selected='selected'":"";?>
							value="vendorName">Vendor</option>
						<option
							<?php echo $sort_by=='currency'? "selected='selected'":"";?>
							value="currency">Currency</option>
						<option
							<?php echo $sort_by=='unitPrice'? "selected='selected'":"";?>
							value="unitPrice">Price</option>
						<option
							<?php echo $sort_by=='balance'? "selected='selected'":"";?>
							value="balance">Balance</option>
						<option
							<?php echo $sort_by=='prSubmitted'? "selected='selected'":"";?>
							value="prSubmitted">Pr Date</option>
					</select> <input
						<?php if(!$sort==null): echo ($sort=='ASC')? "checked":""; else: echo "checked"; endif;?>
						type="radio" name="sort" value="ASC">&nbsp;ASC&nbsp;&nbsp; <input
						<?php if(!$sort==null): echo ($sort=='DESC')? "checked":""; else: echo ""; endif;?>
						type="radio" name="sort" value="DESC">&nbsp;DESC&nbsp;&nbsp;

				</div>
			</div>

			<div class="form-group">
				<div class="col-sm-offset-2 col-sm-10">
					<button onclick="submitForm('Edit_PR_Form');"
						class="btn btn-default">
						<i class="glyphicon glyphicon-OK"> </i> OK
					</button>
				</div>
			</div>

		</form>

	</div>
</div>
<br>


<div id="pr_row_gird" style="margin: 1px;"></div>

<script>

   	 //to check whether any row is currently being edited.
    function isEditing($grid) {
        var rows = $grid.pqGrid("getRowsByClass", { cls: 'pq-row-edit' });
        if (rows.length > 0) {
            //focus on editor if any 
            $grid.find(".pq-editor-focus").focus();
            return true;
        }
        return false;
    }

     
	  //called by add button in toolbar.
    function addRow($grid) {
    	 if (isEditing($grid)) {
    	        return false;
    	    }
    	  
    	//append empty row in the first row.                            
        var rowData = { Item: "", Quantity: 0, Received: 0, Balance: 0}; //empty row template
        $grid.pqGrid("addRow", { rowIndxPage: 0, rowData: rowData });

        var $tr = $grid.pqGrid("getRow", { rowIndxPage: 0 });
        if ($tr) {
            //simulate click on edit button.
            $tr.find("button.edit_btn").click();
        }
    }

    var columns = [
    	{ title: "#", dataType: "string", dataIndx: "row_number", width: 7	,editable: false },
        { title: "PR Number", dataType: "string", dataIndx: "pr_number", width: 150,editable: false },
    	{ title: "SKU", dataType: "string", dataIndx: "item_sku", width:50,editable: false },
       	{ title: "Item", dataType: "string", dataIndx: "item_name", width: 280,editable: false },
        { title: "Quantity", dataType: "integer", dataIndx: "quantity", width: 70,align: 'right',hidden: false},
        { title: "Received", dataType: "string", dataIndx: "total_received", width:70, align: 'right',editable: false},
        { title: "Balance", dataType: "integer", dataIndx: "confirmed_balance", width: 70,align: 'right',editable: false},
        { title: "Vendor", dataType: "string", dataIndx: "vendor_name", width: 80,align: 'left',editable: false},
        { title: "Price", dataType: "float", dataIndx: "vendor_unit_price", width: 100,align: 'right', hidden: false},
        { title: "Curr", dataType: "string", dataIndx: "currency", width: 3,align: 'center', hidden: false},
        
        //{ title: "Remarks", dataType: "string", dataIndx: "remarks", align: 'left',minWidth: 150,editable: false},
        
        { title: "", editable: false, minWidth: 90, sortable: false,
            render: function (ui) {
                return "<button type='button' class='receive_btn'>Receive</button>";
	           }
        },
   ];

    var url = "/procure/pr-row/gird-all?pr_year=<?php echo $pr_year;?>&is_active=<?php echo $is_active; ?>&sort_by=<?php echo $sort_by ?>&sort=<?php echo $sort ?>&balance=<?php echo $balance ?>";
	//var url = "/procure/pr-row/gird-all";
	//var url = "/procure/pr-row/gird-all?pr_year=2017&balance=0&is_active=&sort_by=currency&sort=ASC";
	
	//alert(url);
	 var dataModel = {
    		  dataType: "JSON",
              location: "remote",
              method: "GET",
              recIndx: "row_id",
              url: url,
              getData: function (response) {
           	    return { data: response.data, curPage: response.curPage, totalRecords: response.totalRecords};
             },
            
       	
    };

    //var container_height = $('#main_container').height();
    //alert(container_height);
	var obj = { width: "100%", height: 680, showTitle : true,
			resizable:true,
			//draggable:true,
			sortable: true,
			hoverMode: 'cell',
			pageModel: { type: "remote", rPP:100, strRpp: "{0}" },
			columnBorders: true,
			dataModel: dataModel,
			colModel: columns,
			    numberCell: { resizable: true, width: 40, title: "#", minWidth: 25 },
	            resizable: true
       		
   	};

    var $grid = $("#pr_row_gird").pqGrid(obj);

    $grid.on('pqgridrefresh pqgridrefreshrow', function () {
        //debugger;
        var $grid = $(this);

        //receive button
        $grid.find("button.receive_btn").button({})
        .unbind("click")
        .bind("click", function (evt) {

            var $tr = $(this).closest("tr"),
            rowIndx = $grid.pqGrid("getRowIndx", { $tr: $tr }).rowIndx;

            rowData = $grid.pqGrid("getRowData", { rowIndx: rowIndx }),
            recIndx = $grid.pqGrid("option", "dataModel.recIndx");
    
            redirectUrl="/inventory/item-transaction/gr?token="+rowData['row_token']+"&pr_row_id="+rowData['row_id']+"&checksum="+rowData['row_checksum'];
          	//alert(rowData['item_name']);

          	window.open(redirectUrl,'_blank');
        });

      });
    
 
</script>



