 <form class="form-inline" action="<?php echo $this->baseUrl ?>/procure/pr-search/do"	method="get" enctype="multipart/form-data">
  <div class="form-group">
    	<input class="form-control" size="25" type="text" name = "q">
   </div>
  <div class="form-group">
     <button type="submit" class="btn btn-default"><small><i class="glyphicon glyphicon-search"> </i></small> Search</button>
  </div>
  
</form>
<hr>

<div><small><span class="glyphicon glyphicon-filter"></span></small>&nbsp;<a href="#transaction" class="" data-toggle="collapse">FILTER</a>
 </div>
 <div id ="transaction" class="collapse">
	
  <div style="border:1px; padding: 3px; font-size:10pt; background:url(/images/bg1.png); background-repeat: repeat-x; background-color: #FFFFFF;">
					    
 <form class="form-horizontal" action="<?php echo $this->baseUrl ?>/procure/pr-row/all" method="get" enctype="multipart/form-data">
	
	 <div class="form-group">
		<label class="control-label col-sm-2" for="inputTag">Item  Type</label>
		<div class="col-sm-3">
			<select class="form-control" name="item_type">
									<option value="">All</option>
									<option
										<?php echo $item_type=='ITEM'? "selected='selected'":"";?>
										value="ITEM">Item</option>
									<option
										<?php echo $item_type=='SERVICE'? "selected='selected'":"";?>
										value="SERVICE">Service</option>
									<option
										<?php echo $item_type=='SOFTWARE'? "selected='selected'":"";?>
										value="SOFTWARE">Software</option>
									</select>
		</div>
		<div class="col-sm-4">
	 	</div>
	</div>
	
	<div class="form-group">
		<label class="control-label col-sm-2" for="inputTag">Active Items</label>
		<div class="col-sm-3">
			<select class="form-control" name="is_active">
									<option
									<?php echo $is_active ==''? "selected='selected'":"";?>
										value="">All</option>
									<option
									<?php echo $is_active=='1'? "selected='selected'":"";?>
										value="1">Active</option>
									<option
									<?php echo $is_active=='-1'? "selected='selected'":"";?>
										value="-1">Inactive</option>
									</select>
		</div>
	</div>

	<div class="form-group">
		<label class="control-label col-sm-2" for="inputTag">Fixed Asset</label>
		<div class="col-sm-3">
			<select class="form-control" name="is_fixed_asset">
									<option
									<?php echo $is_fixed_asset==''? "selected='selected'":"";?>
										value="">All</option>
									<option
									<?php echo $is_fixed_asset=='1'? "selected='selected'":"";?>
										value="1">Fixed Asset</option>
									<option
									<?php echo $is_fixed_asset=='-1'? "selected='selected'":"";?>
										value="-1">None Fixed Asset</option>
									</select>
		</div>
	</div>

	<div class="form-group">
		<label class="control-label col-sm-2" for="inputTag">Sort by</label>
		<div class="col-sm-3">
			<select class="form-control" name="sort_by">
									<option value="">None</option>
									<option
										<?php echo $sort_by=='itemName'? "selected='selected'":"";?>
										value="itemName">Item Name</option>
						
									<option <?php echo $sort_by=='prNumber'? "selected='selected'":"";?>
										value="prNumber">Pr Number</option>
 			</select>
 			<input <?php if(!$sort==null): echo ($sort=='ASC')? "checked":""; else: echo "checked"; endif;?> type="radio" name="sort" value="ASC">&nbsp;ASC&nbsp;&nbsp;
 			<input <?php if(!$sort==null): echo ($sort=='DESC')? "checked":""; else: echo ""; endif;?> type="radio" name="sort" value="DESC">&nbsp;DESC&nbsp;&nbsp;
 							
		</div>
	</div>
	
	
	<div class="form-group">
		<label class="control-label col-sm-2" for="inputTag">Result per page</label>
		<div class="col-sm-3">
			<select class="form-control" name="perPage">
									<option value="">None</option>
									<option <?php echo $per_pape=='15'? "selected='selected'":"";?>
										value="15">15</option>

									<option <?php echo $per_pape=='20'? "selected='selected'":"";?>
										value="20">20</option>

									<option <?php echo $per_pape=='30'? "selected='selected'":"";?>
										value="30">30</option>

									<option <?php echo $per_pape=='50'? "selected='selected'":"";?>
										value="50">50</option>
									<option
										<?php echo $per_pape=='100'? "selected='selected'":"";?>
										value="100">100</option>
									<option
										<?php echo $per_pape=='200'? "selected='selected'":"";?>
										value="200">200</option>
								</select>
		</div>
	</div>
	
	<div class="form-group">
		<div class="col-sm-offset-2 col-sm-10">
			<button type="submit" class="btn btn-default">Show</button>
		</div>
	</div>     
	     
 </form>
 
    </div>
</div>
<br>

<?php




if ($total_records <= 0) {
	
	echo 'No record found!';
} else {
	
	if (! is_null ( $paginator )) {
		echo 'Record ' . $paginator->minInPage . ' to ' . $paginator->maxInPage . ' | ' . $total_records. ' records found!';
	} else {
		echo $total_records. ' records found!';
	}
	
	?>




<table style="font-size: 10pt;" class="table table-bordered table-hover">
	<thead>
		<tr>
			<td><b>#</b></td>
			<td><b>PR</b></td>
			<td><b>Item</b></td>
			<td><b>Quantity</b></td>
			<td><b>Received</b></td>
			<td><b>Action</b></td>
		</tr>
	</thead>

	<tbody>
 
	 <?php
	
	$count = 0;
	foreach ( $list as $a ) :
		$count ++;
		?>
	<tr>
		<td><?php echo ($paginator===null)? $count:$paginator->minInPage -1+ $count;?></td>
		<td>

<a style="color: #337ab7;" href="javascript:;"
	onclick="showJqueryDialog('Detail of PR: <?php echo $this->escapeJs($a['pr_number']) ?>','950','550', '/procure/pr-row/list1?token=<?php echo $a['pr_token'] ?>&checksum=<?php echo $a['pr_checksum'] ?>&target_id=<?php echo $a['pr_id'] ?>','j_loaded_data', true);"><?php echo $a['pr_number'] ?>
</a>

		
		</td>
		<td>
<a style="color: #337ab7;" href="javascript:;"
	onclick="showJqueryDialog('Detail of Item: <?php echo $this->escapeJs($a['item_name']) ?>','950','550', '/inventory/item/show1?token=<?php echo $a['item_token'] ?>&checksum=<?php echo $a['item_checksum'] ?>&entity_id=<?php echo $a['item_id'] ?>','j_loaded_data', true);"><?php echo $a['item_name'] ?>
</a>

		</td>
	
		<td><?php echo $a['quantity'] ?></td>
		<td><?php echo $a['total_received'] ?></td>
		<td>
<a href="<?php echo $this->baseUrl ?>/procure/pr-row/show?token=<?php echo $a['token'] ?>&entity_id=<?php echo $a['id'] ?>&checksum=<?php echo $a['checksum'] ?>">Show</a>
<a href="<?php echo $this->baseUrl ?>/procure/pr-row/edit?token=<?php echo $a['token'] ?>&entity_id=<?php echo $a['id'] ?>&checksum=<?php echo $a['checksum'] ?>">Edit</a>
		
		</td>
	</tr>
<?php endforeach; ?>

 </tbody>
</table>

<?php
	
	// ===============================
	if (! is_null ( $paginator )) :
		
		// change it only
	$base = $this->baseUrl . '/procure/pr-row/all?is_active='. $is_active.'&sort_by='.$sort_by.'&sort='.$sort;
	$_connector_symbol = '&';
		
		$last = $base . $_connector_symbol . 'page=' . $paginator->totalPages . '&perPage=' . $paginator->resultsPerPage;
		$first = $base . $_connector_symbol . 'page=1&perPage=' . $paginator->resultsPerPage;
		
		$p1 = ($paginator->page) - 1;
		$p2 = ($paginator->page) + 1;
		
		$prev = $base . $_connector_symbol . 'page=' . $p1 . '&perPage=' . $paginator->resultsPerPage;
		$next = $base . $_connector_symbol . 'page=' . $p2 . '&perPage=' . $paginator->resultsPerPage;
		
		echo '<ul class="pagination pagination-sm">';
		
		if ($paginator->page != 1 and $paginator->totalPages > 10) {
			echo '<li><a href="' . $first . '"> |< </a></li>';
			echo '<li><a href="' . $prev . '"> < </a></li>';
		}
		
		for($i = $paginator->minInPageSet; $i <= $paginator->maxInPageSet; $i ++) {
			
			$url = $base . $_connector_symbol . 'page=' . $i . '&perPage=' . $paginator->resultsPerPage;
			
			if ($i == $paginator->page) {
				echo '<li><a class="active" href="#">' . $i . '</a></li>';
			} else {
				echo '<li><a href="' . $url . '"> ' . $i . ' </a></li>';
			}
		}
		if ($paginator->page != $paginator->totalPages and $paginator->totalPages > 10) {
			echo '<li><a href="' . $next . '"> > </a></li>';
			echo '<li><a href="' . $last . '"> >| </a></li>';
		}
		echo '</ul>';
endif;
	
}
// ===============================
?>


