
<h4>
	 <?php
	 /** @var \Application\Entity\NmtProcurePr $target ; 
	  *  @var \Application\Entity\NmtProcurePrRow $entity ; 
	  */
	 
	 // target
	 echo (!$target== null)? 'PR: ' . $target->getPrNumber() . ' - ' . $target->getPrAutoNumber():"";?>
</h4>

<div id="tabs1" style="font-size: 9pt"> 
  <ul>
  <li ><a href="#general">PR Row</a></li>
  	<li ><a href="<?php echo $this->baseUrl ?>/procure/change-log/list1?object_token=<?php echo (!$entity == null)? $entity->getToken():"";?>&object_id=<?php echo (!$entity == null)? $entity->getId():"";?>&class_name=<?php echo (!$entity == null)? get_class($entity):"";?>"><span class="glyphicon glyphicon-list"></span>&nbsp;Log</a></li>
	
   </ul>

<div id="general"> 

<!-- TO UPDATE ACTION -->
<form id="pr_row_form" class="form-horizontal" action="" method="post" enctype="multipart/form-data">
<input type="hidden" name="target_id" value="<?php echo (!$target == null)? $target->getId():"";?>" />
<input type="hidden" name="token" value="<?php echo (!$target== null)? $target->getToken():"";?>" />
<input type="hidden" name="redirectUrl" value="<?php echo $redirectUrl ?>" />

<div class="form-group margin-bottom ">
		<label class="control-label col-sm-2" ><?php echo $this->translate('Row ID'); ?>:</label>
		<div class="col-sm-3">
		<input disabled class="form-control input-sm" type="text" value="<?php if(!$entity == null): echo $entity->getRowIdentifer(); endif;?>"/></div>
		<div class="col-sm-4">
		<?php echo (!$entity == null)? '<span style="color:gray;font-size: 9pt">Revision #: '. $entity->getRevisionNo().'</span>':'';?>
		<?php if (!$entity == null): if($entity->getLastChangeOn()!==null): echo '<span style="color:gray;font-size: 9pt">; Last Revision: '. $entity->getLastChangeOn()->format('d-m-Y h:i:s').'</span>'; endif; endif;?>
		
	  </div>
</div>

<div class="form-group margin-bottom">
		<label class="control-label col-sm-2" >Item: </label>
		<div class="col-sm-3">
			<input disabled class="form-control input-sm" type="text" id="item_name" placeholder="Select Item if any"
				name="item_name" 
value="<?php if (!$entity== null): if($entity->getItem()!==null): echo $entity->getItem()->getItemName(); endif;endif;?>">
	
	
			<input type="hidden" id="item_id" placeholder="" 
			name="item_id" 
value="<?php if (!$entity== null): if($entity->getItem()!==null): echo $entity->getItem()->getID(); endif;endif;?>">
		</div>
			<div class="col-sm-4">
			 <input <?php if(!$entity == null): echo ($entity->getIsActive()=="1")?"checked":""; else: echo "checked"; endif;?> type="checkbox" name="isActive" value="1">&nbsp;Active&nbsp;&nbsp;
		</div>
	</div>
	
	<div class="form-group margin-bottom">
		<label class="control-label col-sm-2" >Item Name</label>
		<div class="col-sm-3">
			<input class="form-control input-sm" type="text"  placeholder=""
				name="rowName" id="rowName" value="<?php echo (!$entity== null)? $entity->getRowName():"";?>">
	
		</div>
			
	</div>
	
<fieldset >
 <legend style="font-size: 9pt; color: gray;"><small><span class="glyphicon glyphicon-triangle-right"></span></small>&nbsp;
   <a href="#transaction" class="" data-toggle="collapse">PR ROW:</a>
 </legend>
	<div id ="transaction" class="collapse in">
	
	<div class="form-group margin-bottom required">
		<label class="control-label col-sm-2" >Quantity:</label>
		<div class="col-sm-3">
			<input class="form-control input-sm" type="text"  placeholder=""
				name="quantity" id="quantity" value="<?php echo (!$entity== null)? $entity->getQuantity():"";?>">
		</div>
	</div>
	
	<div class="form-group margin-bottom required">
		<label class="control-label col-sm-2" >Unit:</label>
		<div class="col-sm-3">
			<input class="form-control input-sm" type="text"  placeholder=""
				name="rowUnit" id="rowUnit" value="<?php echo (!$entity== null)? $entity->getRowUnit():"";?>">
		</div>
	
		<label class="control-label col-sm-2" >Conversion Factor:</label>
		<div class="col-sm-3">
			<input class="form-control input-sm" type="text"  placeholder=""
				name="conversionFactor" id="conversionFactor" value="<?php 
				if(!$entity== null):
				if($entity->getConversionFactor()!==null):
					echo number_format($entity->getConversionFactor(),2);
				endif;
				endif;
				?>">
		</div>
	
	</div>
</div>
</fieldset>
	
	<div class="form-group margin-bottom required">
		<label class="control-label col-sm-2" >Expected Delivery:</label>
		<div class="col-sm-3">
			<input class="form-control input-sm" type="text" name="edt" 
			value="<?php if(!$entity == null): echo ($entity->getEdt() !== null)? date_format($entity->getEdt(),"Y-m-d"):""; endif;?>" placeholder =" please select" id="edt" />
		</div>
	</div>
	
  <fieldset >
    <legend style="font-size: 9pt; color: gray;"><small><span class="glyphicon glyphicon-triangle-right"></span></small>&nbsp;
   <a href="#additional" class="" data-toggle="collapse">ADDITIONAL:</a>
 </legend>
	<div id ="additional" class="collapse in">
	
	<div class="form-group margin-bottom">
	<label class="control-label col-sm-2" >Remarks:</label>
		<div class="col-sm-3">
			<textarea  class="form-control input-sm" type="text" rows="3" placeholder=""
				name="remarks" style="font-size: 9pt;"><?php echo (!$entity == null)? $entity->getRemarks():"";?></textarea>
			</div>		
	</div>

</div>
</fieldset>
	
	<div class="form-group margin-bottom">
		<label class="control-label col-sm-2" for="inputTag"></label>
		<div class="col-sm-3">
	
<a class="btn btn-default" href="<?php echo $this->baseUrl ?>/procure/pr-row/edit?token=<?php echo (!$entity == null)? $entity->getToken():"";?>&entity_id=<?php echo (!$entity == null)? $entity->getId():"";?>&checksum=<?php echo (!$entity == null)? $entity->getChecksum():"";?>"><small><i class="glyphicon glyphicon-pencil"></i></small>&nbsp;Edit</a>
		</div>
	</div> 
		
	
</form>
</div>
</div>
<script type="text/javascript">
$("#pr_row_form :input").attr("disabled", "disabled");

$( "#tabs1" ).tabs({

	beforeLoad:function(e,ui){
		$( ui.panel ).html('<p>Loading...</p>');       
	    },
	   
});

</script>

