<?php
use Procure\Application\Reporting\PR\Output\PrRowStatusOutputStrategy;
?>
<div id="tabs" style="font-size: 9.5pt">
	<ul>
		<li><a href="#general"><i class="glyphicon glyphicon-shopping-cart"></i>&nbsp;PR
				Row</a></li>
	</ul>


	<div id="general" style="font-size: 9pt">





		<div>
			<small><span class="glyphicon glyphicon-filter"></span></small>&nbsp;<a
				style="font-size: 9.5pt" href="#transaction" class=""
				data-toggle="collapse">FILTER</a>
		</div>


		<div id="transaction" class="collapse">

			<div
				style="border: 1px; padding: 3px; font-size: 9pt; background: url(/images/bg1.png); background-repeat: repeat-x; background-color: #FFFFFF;">

				<form id="filter_form" class="form-horizontal"
					action="<?php echo $this->baseUrl ?>/procure/pr-row/status-report"
					method="get" enctype="multipart/form-data">
					<div class="form-group margin-bottom">
						<label class="control-label col-sm-2" for="inputTag">PR Year</label>
						<div class="col-sm-3">
							<select name="pr_year" class="form-control input-sm">
								<option value="0">All</option>
								<option <?php echo $pr_year=='2016'? "selected='selected'":"";?>
									value="2016">2016</option>
								<option <?php echo $pr_year=='2017'? "selected='selected'":"";?>
									value="2017">2017</option>
								<option <?php echo $pr_year=='2018'? "selected='selected'":"";?>
									value="2018">2018</option>
								<option <?php echo $pr_year=='2019'? "selected='selected'":"";?>
									value="2019">2019</option>
								<option <?php echo $pr_year=='2020'? "selected='selected'":"";?>
									value="2020">2020</option>
							</select>
						</div>
					</div>

					<div class="form-group margin-bottom">
						<label class="control-label col-sm-2" for="inputTag">PR Row
							Balance</label>
						<div class="col-sm-3">
							<select name="balance" class="form-control input-sm">
								<option value="2">All</option>
								<option <?php echo $balance=='0'? "selected='selected'":"";?>
									value="0">Balance=0 (Fulfilled Items)</option>
								<option <?php echo $balance=='1'? "selected='selected'":"";?>
									value="1">Balance>0 (Pending Items)</option>
								<option <?php echo $balance=='-1'? "selected='selected'":"";?>
									value="-1">Balance<0 (Some Free Items)</option>
							</select>
						</div>
					</div>

					<div class="form-group margin-bottom">
						<label class="control-label col-sm-2" for="inputTag">Active Items</label>
						<div class="col-sm-3">
							<select class="form-control input-sm" name="is_active">
								<option <?php echo $is_active ==''? "selected='selected'":"";?>
									value="">All</option>
								<option <?php echo $is_active=='1'? "selected='selected'":"";?>
									value="1">Active</option>
								<option <?php echo $is_active=='-1'? "selected='selected'":"";?>
									value="-1">Inactive</option>
							</select>
						</div>
					</div>

					<div class="form-group margin-bottom">
						<label class="control-label col-sm-2" for="inputTag">Sort by</label>
						<div class="col-sm-3">
							<select class="form-control input-sm" name="sort_by">
								<option value="">None</option>
								<option
									<?php echo $sort_by=='itemName'? "selected='selected'":"";?>
									value="itemName">Item Name</option>

								<option
									<?php echo $sort_by=='prNumber'? "selected='selected'":"";?>
									value="prNumber">Pr Number</option>
								<option
									<?php echo $sort_by=='vendorName'? "selected='selected'":"";?>
									value="vendorName">Vendor</option>
								<option
									<?php echo $sort_by=='currency'? "selected='selected'":"";?>
									value="currency">Currency</option>
								<option
									<?php echo $sort_by=='unitPrice'? "selected='selected'":"";?>
									value="unitPrice">Price</option>
								<option
									<?php echo $sort_by=='balance'? "selected='selected'":"";?>
									value="balance">Balance</option>
								<option
									<?php echo $sort_by=='prSubmitted'? "selected='selected'":"";?>
									value="prSubmitted">Pr Date</option>
							</select> <input
								<?php if(!$sort==null): echo ($sort=='ASC')? "checked":""; else: echo "checked"; endif;?>
								type="radio" name="sort" value="ASC">&nbsp;ASC&nbsp;&nbsp; <input
								<?php if(!$sort==null): echo ($sort=='DESC')? "checked":""; else: echo ""; endif;?>
								type="radio" name="sort" value="DESC">&nbsp;DESC&nbsp;&nbsp;

						</div>
					</div>
					<div class="form-group margin-bottom">
						<div class="col-sm-offset-2 col-sm-10">
							<a class="btn btn-default btn-sm" href="javascript:;"
								onClick="submitForm('filter_form');"><i class="fa fa-filter"
								aria-hidden="true"></i>&nbsp;&nbsp;Filter...</a>
						</div>
					</div>
				</form>
			</div>
		</div>

		<div style="position: relative; float: right; margin-bottom: 3px">
			<a class="btn btn-default btn-sm" href="javascript:;"
				onclick="showJqueryDialog('All Pr Row: <?php echo "Year= ".$pr_year;?>. <?php echo "Balance= ".$balance ?> ','1800',$(window).height()-50,'/procure/pr-row/all1?pr_year=<?php echo $pr_year;?>&is_active=<?php echo $is_active; ?>&sort_by=<?php echo $sort_by ?>&sort=<?php echo $sort ?>&balance=<?php echo $balance ?>','j_loaded_data',true);"><i
				class="fa fa-window-maximize" aria-hidden="true"></i> Full Screen</a>
			<a class="btn btn-default btn-sm"
				href="<?php echo $this->baseUrl ?>/procure/pr-row/status-report?output=<?php echo PrRowStatusOutputStrategy::OUTPUT_IN_EXCEL;?>&pr_year=<?php echo $pr_year;?>&is_active=<?php echo $is_active; ?>&sort_by=<?php echo $sort_by ?>&sort=<?php echo $sort ?>&balance=<?php echo $balance ?>"><i
				class="fa fa-file-excel-o" aria-hidden="true"></i>&nbsp;&nbsp;Excel</a>
		</div>

		<hr>
		<div style="color: gray; font-size: 9pt; margin-top: 8px"><?php echo "Sorted by = ".$sort_by;?>. <?php echo "Sort = ".$sort ?></div>

<?php
if ($output == PrRowStatusOutputStrategy::OUTPUT_IN_HMTL_TABLE) :
    echo $result;

    // ===============================
    if (! is_null($paginator)) :

        // change it only
        $link = "/procure/pr-row/status-report?pr_year=%s&balance=%s&is_active=%s&sort_by=%s&sort=%s&output=%s";
        $base = $this->baseUrl . sprintf($link, $pr_year, $balance, $is_active, $sort_by, $sort,$output);

        $_connector_symbol = '&';

        $last = $base . $_connector_symbol . 'page=' . $paginator->totalPages . '&perPage=' . $paginator->resultsPerPage;
        $first = $base . $_connector_symbol . 'page=1&perPage=' . $paginator->resultsPerPage;

        $p1 = ($paginator->page) - 1;
        $p2 = ($paginator->page) + 1;

        $prev = $base . $_connector_symbol . 'page=' . $p1 . '&perPage=' . $paginator->resultsPerPage;
        $next = $base . $_connector_symbol . 'page=' . $p2 . '&perPage=' . $paginator->resultsPerPage;

        echo '<ul class="pagination pagination-sm">';

        if ($paginator->page != 1 and $paginator->totalPages > 10) {
            echo '<li><a href="' . $first . '"> |< </a></li>';
            echo '<li><a href="' . $prev . '"> < </a></li>';
        }

        for ($i = $paginator->minInPageSet; $i <= $paginator->maxInPageSet; $i ++) {

            $url = $base . $_connector_symbol . 'page=' . $i . '&perPage=' . $paginator->resultsPerPage;

            if ($i == $paginator->page) {
                echo '<li><a class="active" href="#">' . $i . '</a></li>';
            } else {
                echo '<li><a href="' . $url . '"> ' . $i . ' </a></li>';
            }
        }
        if ($paginator->page != $paginator->totalPages and $paginator->totalPages > 10) {
            echo '<li><a href="' . $next . '"> > </a></li>';
            echo '<li><a href="' . $last . '"> >| </a></li>';
        }
        echo '</ul>';
    endif;
    

    
endif;


?>


<?php
if ($output == PrRowStatusOutputStrategy::OUTPUT_IN_ARRAY) :
?>

<div id="pr_row_gird" style="margin: 1px; font-size: 9pt"></div>

	</div>
</div>

<script>

   	 //to check whether any row is currently being edited.
    function isEditing($grid) {
        var rows = $grid.pqGrid("getRowsByClass", { cls: 'pq-row-edit' });
        if (rows.length > 0) {
            //focus on editor if any 
            $grid.find(".pq-editor-focus").focus();
            return true;
        }
        return false;
    }

     
	  //called by add button in toolbar.
    function addRow($grid) {
    	 if (isEditing($grid)) {
    	        return false;
    	    }
    	  
    	//append empty row in the first row.                            
        var rowData = { Item: "", Quantity: 0, Received: 0, Balance: 0}; //empty row template
        $grid.pqGrid("addRow", { rowIndxPage: 0, rowData: rowData });

        var $tr = $grid.pqGrid("getRow", { rowIndxPage: 0 });
        if ($tr) {
            //simulate click on edit button.
            $tr.find("button.edit_btn").click();
        }
    }

    var autoCompleteEditor = function (ui) {
        var $inp = ui.$cell.find("input");
        var rowData = ui.rowData;
      
        //initialize the editor
        $inp.autocomplete({
        	source: "/bp/vendor-search/auto-complete",
            minLength: 3,
            select: function( event, ui ) {
          	  //$( "#vendor_id" ).val(ui.item.id);
              //alert	( "Selected: " + ui.item.value + " aka " + ui.item.id );
          	  //alert($( "#vendor_id" ).val());
          	  //alert(ui.item.id);
          	  rowData.vendor_id = ui.item.id;

          	 	$('#global-notice').show();
          		$('#global-notice').html('"' + ui.item.value + '" selected');
          		$('#global-notice').fadeOut(5000);
          		//$("#jquery_dialog").dialog("close");
            }
            })
            .autocomplete( "instance" )._renderItem = function( ul, item ) {
            return $( "<li>" )
              .append( "<div style='padding-bottom: 5px; border-bottom: thin solid gray;'>" + item.value + "<br><span style='color:gray;font-size: 9pt;'>" + item.vendor_country + "<span></div>" )
              .appendTo( ul );
          };
    }

    var dateEditor = function (ui) {
        var $inp = ui.$cell.find("input"),
            $grid = $(this),
            validate = function (that) {
                var valid = $grid.pqGrid("isValid", { dataIndx: ui.dataIndx, value: $inp.val() }).valid;
                if (!valid) {
                    that.firstOpen = false;
                }
            };

        //initialize the editor
        $inp
        .on("input", function (evt) {
            validate(this);
        })
        .datepicker({
        	dateFormat: 'yy-mm-dd',closeText: 'X',
        	changeMonth: true,
            changeYear: true,
            showAnim: '',
            onSelect: function () {
                this.firstOpen = true;
                validate(this);
            },
            beforeShow: function (input, inst) {
                return !this.firstOpen;
            },
            onClose: function () {
                this.focus();
            }
        });
    }

    var columns = [
       	/* { title: "Receip Date", dataIndx: "receipt_date", width:100,editable: true,
          	editor: {
            type: 'textbox',
            init: dateEditor
        }, 

        render: function (ui) {
            //return "hello";
            var cellData = ui.cellData;
            if (cellData) {
                return $.datepicker.formatDate('yy-mm-dd', new Date(cellData));
            }
            else {
                return "";
            }
        },
        validations: [
           { type: 'regexp', value: '^[0-9]{4}-[0-9]{2}-[0-9]{2}$', msg: 'Not in mm/dd/yyyy format' }
        ] 
        }, */
        
    	 /*  { title: "vendor", dataType: "string", dataIndx: "vendor", align: 'left',minWidth: 100,editable: true,
              editor: {
              type: "textbox",
              init: autoCompleteEditor
              //type: function (ui) { return dropdowneditor(this, ui); }
          },},
          
        { title: "Vendor_id", dataType: "integer", dataIndx: "vendor_id", width: 7	,editable: true,hidden: true }, */
         
        //{ title: "#", dataType: "string", dataIndx: "row_number", width: 1,editable: false },
        { title: "FA Remarks", dataType: "string", dataIndx: "fa_remarks", align: 'left',minWidth: 150,editable: true},
        { title: "PR Number", dataType: "string", dataIndx: "pr_number", width: 130,editable: false },
        { title: "PR Date", dataType: "string", dataIndx: "pr_submitted_on", width: 70,editable: false },
    	{ title: "SKU", dataType: "string", dataIndx: "item_sku", width:50,editable: false },
       	{ title: "Item", dataType: "string", dataIndx: "item_name", width: 230,editable: false },
        { title: "Quantity", dataType: "integer", dataIndx: "quantity", width: 70,align: 'right',hidden: false,editable: false},
        { title: "Received", dataType: "string", dataIndx: "total_received", width:70, align: 'right',editable: false},
        { title: "Balance", dataType: "integer", dataIndx: "confirmed_balance", width: 70,align: 'right',editable: false},
        { title: "buying", dataType: "integer", dataIndx: "buying", width: 70,align: 'right',editable: false},
        
        { title: "Vendor", dataType: "string", dataIndx: "vendor_name", width: 80,align: 'left',editable: false},
        { title: "Price", dataType: "float", dataIndx: "vendor_unit_price", width: 100,align: 'right', hidden: false,editable: false},
        { title: "Curr", dataType: "string", dataIndx: "currency", width: 3,align: 'center', hidden: false,editable: false},
        { title: "Remarks", dataType: "string", dataIndx: "remarks", align: 'left',minWidth: 150,editable: false},
                  
        { title: "", editable: false, minWidth: 90, sortable: false,
            render: function (ui) {
                //return "<button type='button' class='receive_btn'>Receive</button><button type='button' class='receive1_btn'>Receive</button>";
            	return "<button type='button' class='receive1_btn'>Receive</button>";
	           }
        },
   ];

    var url = "/procure/pr-row/gird-all1?pr_year=<?php echo $pr_year;?>&is_active=<?php echo $is_active; ?>&sort_by=<?php echo $sort_by ?>&sort=<?php echo $sort ?>&balance=<?php echo $balance ?>";
	//var url = "/procure/pr-row/gird-all";
	//var url = "/procure/pr-row/gird-all?pr_year=2017&balance=0&is_active=&sort_by=currency&sort=ASC";
	
	//alert(url);
	 var dataModel = {
    		  dataType: "JSON",
              location: "remote",
              method: "GET",
              recIndx: "row_id",
              url: url,
              getData: function (response) {
           	    return { data: response.data, curPage: response.curPage, totalRecords: response.totalRecords};
             },
            
       	
    };

	

    //var container_height = $('#main_container').height();
    //alert(container_height);
	var obj = { width: "auto", height: $(window).height()-190, showTitle : true,
			resizable:true,
			//draggable:true,
			sortable: true,
			hoverMode: 'cell',
			pageModel: { type: "remote", rPP:100, strRpp: "{0}" },
			columnBorders: true,
			dataModel: dataModel,
			colModel: columns,
		    numberCell: {show:true, resizable: true, width: 40, title: "#", minWidth: 25 },
	        resizable: true,
	        editModel: {
                allowInvalid: true,
                saveKey: $.ui.keyCode.ENTER
            },
            editor: {
                select: true
            },
 			change: function (evt, ui) {                
                
                if (ui.source == 'commit' || ui.source == 'rollback') {
                    return;
                }
                console.log(ui);
                var $grid = $(this),
                    grid = $grid.pqGrid('getInstance').grid;
                var rowList = ui.rowList,
                    addList = [],
                    recIndx = grid.option('dataModel').recIndx,
                    deleteList = [],
                    updateList = [];
                
                for (var i = 0; i < rowList.length; i++) {
                    var obj = rowList[i],
                        rowIndx = obj.rowIndx,
                        newRow = obj.newRow,
                        type = obj.type,
                        rowData = obj.rowData;
                     if (type == 'add') {                        
                        var valid = grid.isValid({ rowData: newRow, allowInvalid: true }).valid;
                        if (valid) {
                            addList.push(newRow);
                        }
                    }
                    else if (type == 'update') {                        
                        var valid = grid.isValid({ rowData: rowData, allowInvalid: true }).valid;
                        if (valid) {
                            if (rowData[recIndx] == null) {
                                addList.push(rowData);
                            }
                            //else if (grid.isDirty({rowData: rowData})) {
                            else {
                                updateList.push(rowData);
                          		//alert(rowData[recIndx]  + "remarks: " + rowData.item_name);
                                 
                            }
                        }
                    }
                  }

                  if (addList.length || updateList.length || deleteList.length) {
					var sent_list = JSON.stringify({
                        updateList: updateList,
                        addList: addList,
                        deleteList: deleteList
                    });
                    //alert(sent_list);
                      
                      $.ajax({
                          url: '/procure/pr-row/update-row',
                          data: {
                              sent_list: sent_list
                          },
                          dataType: "json",
                          type: "POST",
                          async: true,
                          beforeSend: function (jqXHR, settings) {
                              //$(".saving", $grid).show();

							  	
                              //$("#global-notice").text("Updating...").show();
                              //alert(updateList[0].item_name  +  updateList[0].row_id);
                          },
                          success: function (changes) {
                              //commit the changes.
                              //alert(changes.updateList);
                               $("#global-notice").text("Updated...").show();
                		      //alert('it is ok');                
                              /* grid.commit({ type: 'add', rows: changes.addList });
                              grid.commit({ type: 'update', rows: changes.updateList });
                              grid.commit({ type: 'delete', rows: changes.deleteList }); */
                          },
                          complete: function () {
                              //$(".saving", $grid).hide();
                              $("#global-notice").delay(2200).fadeOut(500);
                              
                          }
                      });
                  }
                //alert(updateList.length);
               
            },     
	                
       		
   	};

    var $grid = $("#pr_row_gird").pqGrid(obj);

    $grid.on('pqgridrefresh pqgridrefreshrow', function () {
        //debugger;
        var $grid = $(this);

        //receive button
        $grid.find("button.receive_btn").button({})
        .unbind("click")
        .bind("click", function (evt) {

            var $tr = $(this).closest("tr"),
            rowIndx = $grid.pqGrid("getRowIndx", { $tr: $tr }).rowIndx;

            rowData = $grid.pqGrid("getRowData", { rowIndx: rowIndx }),
            recIndx = $grid.pqGrid("option", "dataModel.recIndx");
    
            redirectUrl="/inventory/item-transaction/gr?token="+rowData['row_token']+"&pr_row_id="+rowData['row_id']+"&checksum="+rowData['row_checksum'];
          	//alert(rowData['item_name']);

          	//window.open(redirectUrl,'_blank');
          	window.location.href = redirectUrl;
        });

        //receive button
        $grid.find("button.receive1_btn").button({})
        .unbind("click")
        .bind("click", function (evt) {

            var $tr = $(this).closest("tr"),
            rowIndx = $grid.pqGrid("getRowIndx", { $tr: $tr }).rowIndx;

            rowData = $grid.pqGrid("getRowData", { rowIndx: rowIndx }),
            recIndx = $grid.pqGrid("option", "dataModel.recIndx");
    
            redirectUrl="/inventory/item-transaction/gr1?token="+rowData['row_token']+"&pr_row_id="+rowData['row_id']+"&checksum="+rowData['row_checksum'];
          	//alert(rowData['item_name']);
          	
          	//showBootstrapDialog('Select Deparment',redirectUrl,'b_loaded_data');
          	showJqueryDialog('Item Receiving','1000',$(window).height()-100, redirectUrl,'j_loaded_data', true);
          	//window.open(redirectUrl,'_blank');
          	
        });

      });
    

    $("#main_container").height() = $(window).height()-190;
</script>

<?php
endif;
?>

