<?php
use Procure\Application\Reporting\PR\Output\PrRowStatusOutputStrategy;
?>

<?php

$output1 = PrRowStatusOutputStrategy::OUTPUT_IN_ARRAY;
$title1 = "Gird View";
$icon = 'fa fa-th';

if ($output == PrRowStatusOutputStrategy::OUTPUT_IN_ARRAY) :
    $output1 = PrRowStatusOutputStrategy::OUTPUT_IN_HMTL_TABLE;
    $title1 = "HTML View";
    $icon = 'fa fa-list';
    
endif;

$link = "/procure/pr-row/status-report?pr_year=%s&balance=%s&is_active=%s&sort_by=%s&sort=%s&output=%s";
$url = $this->baseUrl . sprintf($link, $pr_year, $balance, $is_active, $sort_by, $sort, $output1);

$link1 = "/procure/pr-row/status-report-gird?pr_year=%s&balance=%s&is_active=%s&sort_by=%s&sort=%s";
$url1 = $this->baseUrl . sprintf($link1, $pr_year, $balance, $is_active, $sort_by, $sort);

$filtered1 = "Year=%s, Balance=%s, Sorted By=%s %s, Display=%s";
$filtered = sprintf($filtered1, $pr_year, $balance, $sort_by, $sort, $output1);

?>


<div id="tabs" style="font-size: 9.5pt">
	<ul>
		<li><a href="#general"><i class="glyphicon glyphicon-shopping-cart"></i>&nbsp;PR
				Row</a></li>
	</ul>
	<div id="general" style="font-size: 9pt">
		<div>
			<small><span class="glyphicon glyphicon-filter"></span></small>&nbsp;<a
				style="font-size: 9.5pt" href="#transaction" class=""
				data-toggle="collapse">FILTER</a>
		</div>

		<div id="transaction" class="collapse">

			<div
				style="border: 1px; padding: 3px; font-size: 9pt; background: url(/images/bg1.png); background-repeat: repeat-x; background-color: #FFFFFF;">

				<form id="filter_form" class="form-horizontal"
					action="<?php echo $this->baseUrl ?>/procure/pr-row/status-report"
					method="get" enctype="multipart/form-data">
					<div class="form-group margin-bottom">
						<label class="control-label col-sm-2" for="inputTag">PR Year</label>
						<div class="col-sm-3">
							<select name="pr_year" class="form-control input-sm">
								<option value="0">All</option>
								<option <?php echo $pr_year=='2016'? "selected='selected'":"";?>
									value="2016">2016</option>
								<option <?php echo $pr_year=='2017'? "selected='selected'":"";?>
									value="2017">2017</option>
								<option <?php echo $pr_year=='2018'? "selected='selected'":"";?>
									value="2018">2018</option>
								<option <?php echo $pr_year=='2019'? "selected='selected'":"";?>
									value="2019">2019</option>
								<option <?php echo $pr_year=='2020'? "selected='selected'":"";?>
									value="2020">2020</option>
							</select>
						</div>
					</div>

					<div class="form-group margin-bottom">
						<label class="control-label col-sm-2" for="inputTag">PR Row
							Balance</label>
						<div class="col-sm-3">
							<select name="balance" class="form-control input-sm">
								<option value="2">All</option>
								<option <?php echo $balance=='0'? "selected='selected'":"";?>
									value="0">Balance=0 (Fulfilled Items)</option>
								<option <?php echo $balance=='1'? "selected='selected'":"";?>
									value="1">Balance>0 (Pending Items)</option>
								<option <?php echo $balance=='-1'? "selected='selected'":"";?>
									value="-1">Balance<0 (Some Free Items)</option>
							</select>
						</div>
					</div>

					<div class="form-group margin-bottom">
						<label class="control-label col-sm-2" for="inputTag">Active Items</label>
						<div class="col-sm-3">
							<select class="form-control input-sm" name="is_active">
								<option <?php echo $is_active ==''? "selected='selected'":"";?>
									value="">All</option>
								<option <?php echo $is_active=='1'? "selected='selected'":"";?>
									value="1">Active</option>
								<option <?php echo $is_active=='-1'? "selected='selected'":"";?>
									value="-1">Inactive</option>
							</select>
						</div>
					</div>

					<div class="form-group margin-bottom">
						<label class="control-label col-sm-2" for="inputTag">Sort by</label>
						<div class="col-sm-3">
							<select class="form-control input-sm" name="sort_by">
								<option value="">None</option>
								<option
									<?php echo $sort_by=='itemName'? "selected='selected'":"";?>
									value="itemName">Item Name</option>

								<option
									<?php echo $sort_by=='prNumber'? "selected='selected'":"";?>
									value="prNumber">Pr Number</option>
								<option
									<?php echo $sort_by=='vendorName'? "selected='selected'":"";?>
									value="vendorName">Vendor</option>
								<option
									<?php echo $sort_by=='currency'? "selected='selected'":"";?>
									value="currency">Currency</option>
								<option
									<?php echo $sort_by=='unitPrice'? "selected='selected'":"";?>
									value="unitPrice">Price</option>
								<option
									<?php echo $sort_by=='balance'? "selected='selected'":"";?>
									value="balance">Balance</option>
								<option
									<?php echo $sort_by=='prSubmitted'? "selected='selected'":"";?>
									value="prSubmitted">Pr Date</option>
							</select> <input
								<?php if(!$sort==null): echo ($sort=='ASC')? "checked":""; else: echo "checked"; endif;?>
								type="radio" name="sort" value="ASC">&nbsp;ASC&nbsp;&nbsp; <input
								<?php if(!$sort==null): echo ($sort=='DESC')? "checked":""; else: echo ""; endif;?>
								type="radio" name="sort" value="DESC">&nbsp;DESC&nbsp;&nbsp;

						</div>
					</div>

					<div class="form-group margin-bottom">
						<label class="control-label col-sm-2" for="inputTag">Display</label>
						<div class="col-sm-3">
							<select class="form-control input-sm" name="output">
								<option
									<?php echo $output == PrRowStatusOutputStrategy::OUTPUT_IN_ARRAY ? "selected='selected'":"";?>
									value="<?php echo PrRowStatusOutputStrategy::OUTPUT_IN_ARRAY; ?>">Gird</option>

								<option
									<?php echo $output==PrRowStatusOutputStrategy::OUTPUT_IN_HMTL_TABLE ? "selected='selected'":"";?>
									value="<?php echo PrRowStatusOutputStrategy::OUTPUT_IN_HMTL_TABLE; ?>">HTML</option>
							</select>
						</div>
					</div>
					<div class="form-group margin-bottom">
						<div class="col-sm-offset-2 col-sm-10">
							<a class="btn btn-default btn-sm" href="javascript:;"
								onClick="submitForm('filter_form');"><i class="fa fa-filter"
								aria-hidden="true"></i>&nbsp;&nbsp;Filter...</a>
						</div>
					</div>
				</form>
			</div>
		</div>

		<div style="color: gray; font-size: 9pt; margin-top: 8px"><?php echo $filtered; ?>
		</div>

		<hr style="font-size: 9.5pt; margin: 3pt 1pt 5pt 1pt;">


		<div id="transaction" class="collapse in">
			<div id="pr_rows">

				<div style="font-size: 9pt">

					<div class="dropdown">
						<button
							style="font-size: 9.5pt; margin-bottom: 2pt; padding: 3pt 5pt 3pt 5pt;"
							title="" class="btn btn-default dropdown-toggle btn-sm"
							type="button" id="dropdownMenu1" data-toggle="dropdown"
							aria-haspopup="true" aria-expanded="true">
							<i class="fa fa-download" aria-hidden="true"></i>&nbsp;Download
							&nbsp;<span class="caret"></span>
						</button>
						
						<?php

if ($output == PrRowStatusOutputStrategy::OUTPUT_IN_ARRAY) :

        ?>
						 
						<a
							style="font-size: 9.5pt; margin-bottom: 2pt; padding: 3pt 5pt 3pt 5pt;"
							title="<?php echo $this->translate("Refresh");?>"
							class="btn btn-default btn-sm" href="javascript:;"
							onclick="refreshGird();">&nbsp;<i class="fa fa-refresh"
							aria-hidden="true"></i>&nbsp;
						</a> 
						
						<?php endif;?>
						<a class="btn btn-default btn-sm"
							style="color: black; margin-bottom: 2pt; padding: 3pt 5pt 3pt 5pt;"
							title="<?php echo $title1; ?>" href="<?php echo $url;?>"> <i
							class="<?php echo $icon;?>" aria-hidden="true"></i>
						</a>

						<ul style="font-size: 9.5pt;" class="dropdown-menu"
							aria-labelledby="dropdownMenu1">

							<li><a class=""
								href="<?php echo $this->baseUrl ?>/procure/pr-row/status-report?output=<?php echo PrRowStatusOutputStrategy::OUTPUT_IN_EXCEL;?>&pr_year=<?php echo $pr_year;?>&is_active=<?php echo $is_active; ?>&sort_by=<?php echo $sort_by ?>&sort=<?php echo $sort ?>&balance=<?php echo $balance ?>"><i
									class="fa fa-file-excel-o" aria-hidden="true"></i>&nbsp;&nbsp;Excel
									(*.xlxs)</a></li>

							<li><a class=""
								href="<?php echo $this->baseUrl ?>/procure/pr-row/status-report?output=<?php echo PrRowStatusOutputStrategy::OUTPUT_IN_OPEN_OFFICE;?>&pr_year=<?php echo $pr_year;?>&is_active=<?php echo $is_active; ?>&sort_by=<?php echo $sort_by ?>&sort=<?php echo $sort ?>&balance=<?php echo $balance ?>"><i
									class="fa fa-file-excel-o" aria-hidden="true"></i>&nbsp;&nbsp;OpenOffice
									(*.ods)</a></li>

						</ul>
					</div>

				</div>

			</div>
		</div>

<?php
if ($output == PrRowStatusOutputStrategy::OUTPUT_IN_HMTL_TABLE) :
    echo $result;

    // ===============================
    if (! is_null($paginator)) :

        // change it only
        $link = "/procure/pr-row/status-report?pr_year=%s&balance=%s&is_active=%s&sort_by=%s&sort=%s&output=%s";
        $base = $this->baseUrl . sprintf($link, $pr_year, $balance, $is_active, $sort_by, $sort, $output);

        $_connector_symbol = '&';

        $last = $base . $_connector_symbol . 'page=' . $paginator->totalPages . '&perPage=' . $paginator->resultsPerPage;
        $first = $base . $_connector_symbol . 'page=1&perPage=' . $paginator->resultsPerPage;

        $p1 = ($paginator->page) - 1;
        $p2 = ($paginator->page) + 1;

        $prev = $base . $_connector_symbol . 'page=' . $p1 . '&perPage=' . $paginator->resultsPerPage;
        $next = $base . $_connector_symbol . 'page=' . $p2 . '&perPage=' . $paginator->resultsPerPage;

        echo '<ul class="pagination pagination-sm">';

        if ($paginator->page != 1 and $paginator->totalPages > 10) {
            echo '<li><a href="' . $first . '"> |< </a></li>';
            echo '<li><a href="' . $prev . '"> < </a></li>';
        }

        for ($i = $paginator->minInPageSet; $i <= $paginator->maxInPageSet; $i ++) {

            $url = $base . $_connector_symbol . 'page=' . $i . '&perPage=' . $paginator->resultsPerPage;

            if ($i == $paginator->page) {
                echo '<li><a class="active" href="#">' . $i . '</a></li>';
            } else {
                echo '<li><a href="' . $url . '"> ' . $i . ' </a></li>';
            }
        }
        if ($paginator->page != $paginator->totalPages and $paginator->totalPages > 10) {
            echo '<li><a href="' . $next . '"> > </a></li>';
            echo '<li><a href="' . $last . '"> >| </a></li>';
        }
        echo '</ul>';
    endif;
    

    
endif;


?>


<?php
if ($output == PrRowStatusOutputStrategy::OUTPUT_IN_ARRAY) :
    ?>

<div id="pr_row_gird" style="margin: 1px; font-size: 9pt"></div>

	</div>
</div>

<script>

    var columns = [
      
        { title: "FA Remarks", dataType: "string", dataIndx: "faRemarks", align: 'left',minWidth: 150,editable: true},
        { title: "PR Number", dataType: "string", dataIndx: "prNumber", width: 130,editable: false },
        { title: "PR Date", dataType: "string", dataIndx: "prSubmittedOn", width: 60,editable: false },
    	{ title: "SKU", dataType: "string", dataIndx: "itemSKU", width:50,editable: false },
       	{ title: "Item", dataType: "string", dataIndx: "itemName", width: 250,editable: false },
      	{ title: "Row name", dataType: "string", dataIndx: "rowName", width: 100,editable: false },
     	{ title: "Row name", dataType: "string", dataIndx: "rowCode", width: 100,editable: false },
            
        { title: "Quantity", dataType: "integer", dataIndx: "quantity", width: 70,align: 'right',hidden: false,editable: false},
        { title: "PO", dataType: "string", dataIndx: "poQuantity", width:70, align: 'right',editable: false},
        { title: "Posted PO", dataType: "string", dataIndx: "postedPoQuantity", width:70, align: 'right',editable: false},

        { title: "GR", dataType: "string", dataIndx: "grQuantity", width:70, align: 'right',editable: false},
        { title: "Posted GR", dataType: "string", dataIndx: "postedGrQuantity", width:70, align: 'right',editable: false},

        { title: "GR", dataType: "string", dataIndx: "stockGrQuantity", width:70, align: 'right',editable: false},
        { title: "Posted GR", dataType: "string", dataIndx: "postedStockGrQuantity", width:70, align: 'right',editable: false},

        { title: "AP", dataType: "string", dataIndx: "apQuantity", width:70, align: 'right',editable: false},
        { title: "Posted AP", dataType: "string", dataIndx: "postedApQuantity", width:70, align: 'right',editable: false},
    
        
        { title: "Vendor", dataType: "string", dataIndx: "lastVendor", width: 150,align: 'left',editable: false},
        { title: "Unit Price", dataType: "float", dataIndx: "lastUP", width: 80,align: 'right', hidden: false,editable: false},
        { title: "Curr", dataType: "string", dataIndx: "lastCurrency", width: 3,align: 'center', hidden: false,editable: false},
        { title: "Remarks", dataType: "string", dataIndx: "remarks", align: 'left',minWidth: 150,editable: false},
   ];

    <?php
    $link = "/procure/pr-row/status-report-gird?pr_year=%s&balance=%s&is_active=%s&sort_by=%s&sort=%s&output=%s";
    $url = $this->baseUrl . sprintf($link, $pr_year, $balance, $is_active, $sort_by, $sort, $output);

    ?>
    var url = "<?php echo $url;?>";
    var dataModel = {
    		  dataType: "JSON",
              location: "remote",
              method: "GET",
              recIndx: "row_id",
              url: url,
              getData: function (response) {
           	    return { data: response.data, curPage: response.curPage, totalRecords: response.totalRecords};
             },
    };

	var obj = { width: "auto", height: $(window).height()-300, showTitle : true,
			resizable:true,
			//draggable:true,
			sortable: true,
			hoverMode: 'cell',
			pageModel: { type: "remote", rPP:100, strRpp: "{0}" },
			columnBorders: true,
			dataModel: dataModel,
			colModel: columns,
		    numberCell: {show:true, resizable: true, width: 40, title: "#", minWidth: 25 },
	        resizable: true,
	        editModel: {
                allowInvalid: true,
                saveKey: $.ui.keyCode.ENTER
            },
            editor: {
                select: true
            },
 			change: function (evt, ui) {                
                
                if (ui.source == 'commit' || ui.source == 'rollback') {
                    return;
                }
                console.log(ui);
                var $grid = $(this),
                    grid = $grid.pqGrid('getInstance').grid;
                var rowList = ui.rowList,
                    addList = [],
                    recIndx = grid.option('dataModel').recIndx,
                    deleteList = [],
                    updateList = [];
                
                for (var i = 0; i < rowList.length; i++) {
                    var obj = rowList[i],
                        rowIndx = obj.rowIndx,
                        newRow = obj.newRow,
                        type = obj.type,
                        rowData = obj.rowData;
                     if (type == 'add') {                        
                        var valid = grid.isValid({ rowData: newRow, allowInvalid: true }).valid;
                        if (valid) {
                            addList.push(newRow);
                        }
                    }
                    else if (type == 'update') {                        
                        var valid = grid.isValid({ rowData: rowData, allowInvalid: true }).valid;
                        if (valid) {
                            if (rowData[recIndx] == null) {
                                addList.push(rowData);
                            }
                            //else if (grid.isDirty({rowData: rowData})) {
                            else {
                                updateList.push(rowData);
                          		//alert(rowData[recIndx]  + "remarks: " + rowData.item_name);
                                 
                            }
                        }
                    }
                  }

                  if (addList.length || updateList.length || deleteList.length) {
					var sent_list = JSON.stringify({
                        updateList: updateList,
                        addList: addList,
                        deleteList: deleteList
                    });
                    //alert(sent_list);
                      
                      $.ajax({
                          url: '/procure/pr-row/update-row',
                          data: {
                              sent_list: sent_list
                          },
                          dataType: "json",
                          type: "POST",
                          async: true,
                          beforeSend: function (jqXHR, settings) {
                              //$(".saving", $grid).show();

							  	
                              //$("#global-notice").text("Updating...").show();
                              //alert(updateList[0].item_name  +  updateList[0].row_id);
                          },
                          success: function (changes) {
                              //commit the changes.
                              //alert(changes.updateList);
                               $("#global-notice").text("Updated...").show();
                		      //alert('it is ok');                
                              /* grid.commit({ type: 'add', rows: changes.addList });
                              grid.commit({ type: 'update', rows: changes.updateList });
                              grid.commit({ type: 'delete', rows: changes.deleteList }); */
                          },
                          complete: function () {
                              //$(".saving", $grid).hide();
                              $("#global-notice").delay(2200).fadeOut(500);
                              
                          }
                      });
                  }
                //alert(updateList.length);
               
            },     
	                
       		
   	};

    var $grid = $("#pr_row_gird").pqGrid(obj);

    $("#main_container").height() = $(window).height()-190;

    function refreshGird(){
    	$( "#pr_row_gird" ).pqGrid( "refreshDataAndView" )
	} 
    
</script>

<?php
endif;

?>

