<div id="tabs" style="font-size: 9.5pt">

	<ul>
		<li><a href="#general">Transition</a></li>
	</ul>
	<div id="general">


<?php

if (count($total_records) <= 0) {
	
	echo 'No record found!';
} else {
    echo count($total_records);
	?>


<form action="<?php echo $this->baseUrl ?>/workflow/transition/add-agent" method="post" enctype="multipart/form-data" id="">
<input type="hidden" name="target_id" value="<?php echo (int) $target->getId(); ?>" />
<input type="hidden" name="token" value="<?php echo  $target->getToken(); ?>" />


<table style="font-size: 9.5pt;" class="table table-bordered table-hover">
			<thead>
				<tr>
					<td><input type="checkbox" id="select_ALL" name="SelectAll" value="YES"/> <b>All</b> </td>
 					<td><b>#</b></td>
					<td><b>First Name</b></td>
					<td><b>Last Name</b></td>
					<td><b>Email</b></td>
					</tr>
			</thead>

			<tbody>
 
	 <?php
	
	$count = 0;
	foreach ( $agents as $a ) :
		$count ++;
		?>
	<tr>
					<td><input class="checkbox1" type="checkbox" name="agents[]" value="<?php echo $a['id'];?>" class="checkbox"/></td>
					<td><?php echo $count;?></td>
					<td><?php echo $a['firstname'];?></td>
					<td><?php echo $a['lastname'];?></td>
					<td><?php echo $a['email'];?></td>
				</tr>
<?php endforeach; ?>

 </tbody>
		</table>
		
		<input class="btn btn-primary" type="submit" name="grant" value="Add Agent" />
		
</form>

	</div>
</div>

<?php } ?>
