<?php
/**
 * @var \Application\Entity\NmtProcurePrRow $target ;
 * @var \Application\Entity\NmtApplicationAttachment $entity ;
 */
$form_action = '';
$form_title = '';

$attachment_url =  $this->baseUrl . '/procure/pr-row-attachment' ;


switch ($action) {

    case \Application\Model\Constants::FORM_ACTION_ADD:
        $form_action = '/procure/pr-row-attachment/upload';
        $form_title = $this->translate("Upload");

        break;
    case \Application\Model\Constants::FORM_ACTION_EDIT:
        $form_action = '/procure/pr-row-attachment/edit';
        $form_title = $this->translate("Edit Header");
        break;
}
?>

<h4>
	 <?php 
	 /**@todo: UPDATE TARGET */
	 if (!$target== null):
 	  echo  'PR Line: ' . $target->getId();
        if($target->getItem()!=null): echo '<br>'.$target->getItem()->getItemName();endif;
     endif; 	
 	;?>
 	
</h4>


<?php
if (count ( $errors ) > 0) {
	echo '<div class="alert alert-danger" role="alert" style="font-size: 10.5pt">';
	
	echo '<ul>';
	foreach ( $errors as $error ) :
		echo '<li>' . $error . '</li>';
	endforeach
	;
	echo '</ul>';
	echo '</div>';
}
?>

<div id="tabs" style="font-size: 9.5pt"> 
  <ul>
  <li ><a href="#general"><?php echo $form_title;?>:</a></li>

				<?php if($action == \Application\Model\Constants::FORM_ACTION_EDIT):?>

  		<li ><a title="<?php echo $this->translate("Change Logs");?>" href="<?php echo $this->baseUrl ?>/procure/change-log/list1?object_token=<?php echo (!$entity == null)? $entity->getToken():"";?>&object_id=<?php echo (!$entity == null)? $entity->getId():"";?>&class_name=<?php echo (!$entity == null)? get_class($entity):"";?>"><span class="glyphicon glyphicon-list"></span>&nbsp;Log</a></li>
          			<?php endif;?>



   </ul>

<div id="general" style="font-size: 9pt; padding-top: 0px"> 


<h5 style="color: gray">
</h5>

<hr>

<!-- TO UPDATE ACTION -->
<form id="attachment_upload_form" class="form-horizontal" action="<?php echo $form_action; ?>" method="post" enctype="multipart/form-data">
<input type="hidden" name="target_id" value="<?php echo (!$target == null)? $target->getId():"";?>" />
<input type="hidden" name="token" value="<?php echo (!$target== null)? $target->getToken():"";?>" />

<input type="hidden" name="entity_token" value="<?php echo (!$entity== null)? $entity->getToken():"";?>" />
<input type="hidden" name="entity_id" value="<?php echo (!$entity== null)? $entity->getId():"";?>" />


<input type="hidden" name="redirectUrl" value="<?php echo $redirectUrl ?>" />

 			<?php if($action == \Application\Model\Constants::FORM_ACTION_EDIT):?>
           				<input type="hidden" name="n" value="<?php echo $n;?>" />
        	<?php endif;?>
        

	<div class="form-group margin-bottom required">
		<label class="control-label col-sm-2 " >Document Subject:</label>
		<div class="col-sm-3">
			<input class="form-control input-sm" type="text"  placeholder=""
				name="documentSubject" id="documentSubject" value="<?php echo (!$entity== null)? $entity->getDocumentSubject():"";?>">
		</div>
		<label class="control-label col-sm-1" for="inputTag"></label>
		<div class="col-sm-4">
					  	     <input <?php if(!$entity == null): echo ($entity->getIsActive()=="1")?"checked":""; else: echo "checked"; endif;?> type="checkbox" name="isActive" value="1">&nbsp;Active&nbsp;&nbsp;
		</div>		
	</div>
		
	<div class="form-group margin-bottom">
		<label class="control-label col-sm-2" for="inputTag">Attachment:</label>
		<div class="col-sm-3">
							<?php if($action == \Application\Model\Constants::FORM_ACTION_ADD):?>
  
			<input style=";" type="file" id= "attachments" name="attachments" />
			        			<?php endif;?>
	
						<?php if($action == \Application\Model\Constants::FORM_ACTION_EDIT):?>
  	   <i class="glyphicon glyphicon-download-alt"></i>&nbsp;&nbsp;<a href="<?php echo $attachment_url ?>/download?token=<?php echo (!$entity == null)? $entity->getToken():"";?>&entity_id=<?php echo (!$entity == null)? $entity->getId():"";?>&checksum=<?php echo (!$entity == null)? $entity->getChecksum():"";?>"><?php echo (!$entity == null)? $entity->getFilenameOriginal():"";?></a>
	        			<?php endif;?>
			
			
		</div>		
	</div>
	
	<div class="form-group margin-bottom">
		<label class="control-label col-sm-2" >Valid From:</label>
		<div class="col-sm-3">
			<input class="form-control input-sm" type="text" name="validFrom" 
			value="<?php if(!$entity == null): echo ($entity->getValidFrom() !== null)? date_format($entity->getValidFrom(),"Y-m-d"):""; endif;?>" placeholder =" please select" id="valid_from" />
		</div>
		
		<label class="control-label col-sm-2" >Valid To:</label>
		<div class="col-sm-3">
			<input class="form-control input-sm" type="text" name="validTo" 
			value="<?php if(!$entity == null): echo ($entity->getValidTo() !== null)? date_format($entity->getValidTo(),"Y-m-d"):""; endif;?>" placeholder =" please select" id="valid_to" />
		</div>		
	</div>
	<div class="form-group margin-bottom">
					<label class="control-label col-sm-2" >Remark:</label>
            		<div class="col-sm-8">
            			<input tabindex="9" class="form-control input-sm" type="text"  placeholder=""
            				name="remarks" value="<?php echo (!$entity == null)? $entity->getRemarks():"";?>">
            		</div>
				</div>
	<hr>
	<div class="form-group margin-bottom">
		<label class="control-label col-sm-2" for="inputTag"></label>
		<div class="col-sm-3">

         			<?php if($action == \Application\Model\Constants::FORM_ACTION_ADD):?>
            			
	
 <a class="btn btn-default" style="" href="javascript:;"
	onClick="doUploadAttachment('attachment_upload_form','attachments','<?php echo $attachment_url; ?>/upload-pictures','<?php echo $target!==null ? $target->getId():""?>','<?php echo $redirectUrl ?>','','<?php echo $target!==null ? $target->getToken():""?>');">
	<small><i class="fa fa-upload" aria-hidden="true"></i>&nbsp; Upload
</a>
					<a tabindex="11" class="btn btn-default"
								href="<?php echo $this->baseUrl ?>/procure/pr-row/edit?token=<?php echo (!$target == null)? $target->getToken():"";?>&entity_id=<?php echo (!$target == null)? $target->getId():"";?>"><small><i
									class="glyphicon glyphicon-ok"></i></small>&nbsp;Cancel</a>
   		</div>
	</div> 

           			<?php endif;?>

         			<?php if($action == \Application\Model\Constants::FORM_ACTION_EDIT):?>
         			
  			<a tabindex="11" class="btn btn-default btn-sm"
						onclick="submitForm('attachment_upload_form');" href="javascript:;"><small><i
							class="glyphicon glyphicon-floppy-disk"></i></small>&nbsp;<?php echo $this->translate("Save");?></a>
						<a tabindex="11" class="btn btn-default"
								href="<?php echo $this->baseUrl ?>/procure/pr-row/edit?token=<?php echo (!$target == null)? $target->getToken():"";?>&entity_id=<?php echo (!$target == null)? $target->getId():"";?>"><small><i
									class="glyphicon glyphicon-ok"></i></small>&nbsp;Cancel</a>
        			
          			<?php endif;?>
           			
		
	
</form>
</div>
</div>

<script type="text/javascript">
$('#attachments').bind('change', function() {
	var file_size;
	file_size = this.files[0].size
	if (file_size > 10485760){
		//alert('This file size is too large : ' + file_size + "MB. Please select new file");
		
		$('#b_loaded_data').text('This file size is too large : ' + file_size + "MB. Please select new file");
		$('#modal1').modal();

		 $("#attachments").val("");
		 	
	}else{
		//alert('This file size is: ' + file_size + "MB, OKE");
		 //$('#save').removeAttr('disabled');
	}

});

$( "input[id='valid_from']").datepicker({ firstDay: 1, dateFormat: 'yy-mm-dd',closeText: 'X',changeMonth: true, changeYear: true});
$( "input[id='valid_to']").datepicker({ firstDay: 1, dateFormat: 'yy-mm-dd',closeText: 'X',changeMonth: true, changeYear: true});


</script>

