<h5>Change Password:</h5>
<hr>

<?php

if (! $messages == null) {
	
	if ($status == 1){
		echo '<div class="alert alert-success">';
	}else{
		echo '<div class="alert alert-error">';
	}
	
	echo '<ul>';
	foreach ( $messages as $m ) :
		echo '<li>' . $m . '</li>';
	endforeach;
	
	echo '</ul>';
	echo '</div>';
}
?>


<form class="form-horizontal"
	action="<?php echo $this->baseUrl ?>/user/profile/change-password"
	method="post" enctype="multipart/form-data" id="change-password-form">

	<div class="control-group">
		<label class="control-label" for="inputTag">Old Password</label>
		<div class="controls">
			<input type="password" id="inputTag" placeholder="enter old password"
				name="old_password">
		</div>
	</div>

	<div class="control-group">
		<label class="control-label" for="inputTag">New Password</label>
		<div class="controls">
			<input type="password" id="inputTag" placeholder="enter new password"
				name="new_password">
		</div>
	</div>

	<div class="control-group">
		<label class="control-label" for="inputTag">New Password (re-type)</label>
		<div class="controls">
			<input type="password" id="inputTag"
				placeholder="re-enter new password" name="new_password1">
		</div>
	</div>

	<div class="control-group">
		<div class="controls">
			<button type="submit" class="btn">Change Password</button>
		</div>
	</div>
</form>
