<?php
/**@var \Application\Entity\NmtFinPostingPeriod $entity*/
/**@var \Application\Model\Constants $const ; */
$const = new \Application\Model\Constants;


if (count ( $errors ) > 0) {
	echo '<div class="alert alert-danger" role="alert" style="font-size: 10.5pt">';
	
	echo '<ul>';
	foreach ( $errors as $error ) :
		echo '<li>' . $error . '</li>';
	endforeach
	;
	echo '</ul>';
	echo '</div>';
}
?>

<div id="tabs" style="font-size: 9.5pt"> 
  <ul>
  <li ><a href="#general">New Posting Period</a></li>
   </ul>

<div id="general"> 

<form id="Create_Form" class="form-horizontal" action="/finance/posting-period/add" method="post" enctype="multipart/form-data">
<input type="hidden" name="redirectUrl" value="<?php echo $redirectUrl ?>" />

	<div class="form-group">
		<label class="control-label col-sm-2" >Period Code:</label>
		<div class="col-sm-3">
			<input class="form-control" type="text"  placeholder=""
				name="periodCode" value="<?php echo (!$entity == null)? $entity->getPeriodCode():"";?>">
		</div>
		
		<label class="control-label col-sm-2" >Period Name:</label>
		<div class="col-sm-3">
			<input class="form-control" type="text"  placeholder=""
				id = "periodName" name="periodName" value="<?php echo (!$entity == null)? $entity->getPeriodName():"";?>">
		</div>
		
	</div>
	
	<div class="form-group">
		<label class="control-label col-sm-2" >Period Start:</label>
		<div class="col-sm-3">
<input placeholder="Please select" class="form-control" type="text"  placeholder="" id = "postingFromDate" name="postingFromDate" 
value="<?php if(!$entity == null): if ($entity->getPostingFromDate() !== null): echo date_format($entity->getPostingFromDate(),"Y-m-d"); endif; endif;?>" placeholder =" please select"/>
		</div>
		
		<label class="control-label col-sm-2" >Period End:</label>
		<div class="col-sm-3">
<input placeholder="Please select" class="form-control" type="text"  placeholder="" id = "postingToDate" name="postingToDate" 
value="<?php if(!$entity == null): if ($entity->getPostingToDate() !== null): echo date_format($entity->getPostingToDate(),"Y-m-d"); endif; endif;?>" placeholder =" please select"/>
		</div>
		
	</div>
	
	<div class="form-group">
		<label class="control-label col-sm-2" >Remarks:</label>
		<div class="col-sm-3">
			<textarea  class="form-control" type="text" rows="4" placeholder=""
				name="remarks" style="font-size: 9pt;"></textarea>
		</div>
	</div>
	
	<div class="form-group">
		<label class="control-label col-sm-2" for="inputTag"></label>
		<div class="col-sm-3">
	   	<button onclick="submitForm('Create_Form');" class="btn btn-default"><i class="glyphicon glyphicon-floppy-disk"> </i> Save</button>
  		</div>
	</div> 
		
	
</form>
</div>
</div>

<script>
   $( "input[id='postingFromDate']").datepicker({ firstDay: 1, dateFormat: 'yy-mm-dd',closeText: 'X', changeMonth: true, changeYear: true});
   $( "input[id='postingToDate']").datepicker({ firstDay: 1, dateFormat: 'yy-mm-dd',closeText: 'X', changeMonth: true, changeYear: true});

   </script>

