<div id="tabs" style="font-size: 9.5pt">

	<ul>
		<li><a href="#general">Posting Period</a></li>
	</ul>
<div id="general">

<?php
if ($total_records <= 0) {
	echo 'No record found!';
} else {
	
	if (! is_null ( $paginator )) {
		echo 'Record ' . $paginator->minInPage . ' to ' . $paginator->maxInPage . ' | ' . $total_records . ' records found!';
	} else {
		echo $total_records . ' records found!';
	}
	
	?>


<table style="font-size: 10pt;" class="table table-bordered table-hover">
	<thead>
		<tr>
			<td><b>#</b></td>
			<td><b>Period Name</b></td>
			<td><b>Period<br>Start</b></td>
			<td><b>Period<br>End</b></td>
			<td><b>Status</b></td>
			<td><b>Action</b></td>
		</tr>
	</thead>

	<tbody>
 
	 <?php
	
	$count = 0;
	foreach ( $list as $a ) :
	
	    /**@var \Application\Entity\NmtFinPostingPeriod $a*/
		$count ++;
		?>
	<tr>
			<td><?php echo ($paginator===null)? $count:$paginator->minInPage -1+ $count;?></td>
			<td>
			<?php echo $a->getPeriodName();?>
			</td>

			<td><?php echo date_format($a->getPostingFromDate(),"Y-m-d") ?></td>
			<td><?php echo date_format($a->getPostingToDate(),"Y-m-d") ?></td>
			<td><?php echo $a->getPeriodStatus();?></td>
			<td>
			
			</td>
		</tr>
<?php endforeach; ?>

 </tbody>
</table>

<?php
	
	// ===============================
	if (! is_null ( $paginator )) :
		
		// change it only
	$base = $this->baseUrl . '/procure/pr/all/row_number='.$row_number.'/status='.$status.'?is_active=' . $is_active . '&sort_by=' . $sort_by . '&sort=' . $sort. '&balance=' . $balance;
		$_connector_symbol = '&';
		
		$last = $base . $_connector_symbol . 'page=' . $paginator->totalPages . '&perPage=' . $paginator->resultsPerPage;
		$first = $base . $_connector_symbol . 'page=1&perPage=' . $paginator->resultsPerPage;
		
		$p1 = ($paginator->page) - 1;
		$p2 = ($paginator->page) + 1;
		
		$prev = $base . $_connector_symbol . 'page=' . $p1 . '&perPage=' . $paginator->resultsPerPage;
		$next = $base . $_connector_symbol . 'page=' . $p2 . '&perPage=' . $paginator->resultsPerPage;
		
		echo '<ul class="pagination pagination-sm">';
		
		if ($paginator->page != 1 and $paginator->totalPages > 10) {
			echo '<li><a href="' . $first . '"> |< </a></li>';
			echo '<li><a href="' . $prev . '"> < </a></li>';
		}
		
		for($i = $paginator->minInPageSet; $i <= $paginator->maxInPageSet; $i ++) {
			
			$url = $base . $_connector_symbol . 'page=' . $i . '&perPage=' . $paginator->resultsPerPage;
			
			if ($i == $paginator->page) {
				echo '<li><a class="active" href="#">' . $i . '</a></li>';
			} else {
				echo '<li><a href="' . $url . '"> ' . $i . ' </a></li>';
			}
		}
		if ($paginator->page != $paginator->totalPages and $paginator->totalPages > 10) {
			echo '<li><a href="' . $next . '"> > </a></li>';
			echo '<li><a href="' . $last . '"> >| </a></li>';
		}
		echo '</ul>';
endif;
	
}
// ===============================
?>
</div>
</div>

