<?php

/**
 *
 * @author Nguyen Mau Tri - ngmautri@gmail.com
 *         ===================================
 */
// ===========================================================
?>

<div class="modal" id="confirm_remove_row_modal_sm" role="dialog">
	<div class="modal-dialog modal-md">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal">&times;</button>
			</div>
			<div class="modal-body" id="b_modal_sm_body">
				<h5>#<?php
    echo $this->translate('Data will be removed!');
    ?></h5>
				<div class="alert alert-warning">
					<strong>[Info]</strong> <?php

    echo $this->translate('Remove can not be recalled!');
    ?>
      		</div>
				<p><?php
    echo $this->translate('Do you want to continue?');
    ?></p>
			</div>
			<div class="modal-footer">
				<button onclick="doRemoving();" type="button"
					class="btn btn-primary btn-sm">YES</button>
				<button type="button" class="btn btn-default btn-sm"
					data-dismiss="modal">Cancel</button>
			</div>
		</div>
	</div>
</div>

<script>

    $("#checkAll").click(function () {
        $('input:checkbox').not(this).prop('checked', this.checked);
        showDeleteButton();
    });

    $(".checkbox1").change(function() {   
        showDeleteButton();            
    });

    function showDeleteButton(){
        var checkedNum = $('input[name="ids[]"]:checked').length;
        

        $('#deleteBtn').show();
        if(!checkedNum){
            $('#deleteBtn').hide();
        }     
 
    }

    function countCheckedBox() {
        var checkedNum = $('input[name="ids[]"]:checked').length;
        alert(checkedNum);       
    }

    function confirmRemove() {
      $('#confirm_remove_row_modal_sm').modal();
     
    }

    function doRemoving() {

        $('#confirm_remove_row_modal_sm').modal('hide');
        $('#overlay').fadeIn(300);
        var checkedBox = $('input[name="ids[]"]:checked');
        var ids=[];
        console.log(checkedBox);
        
        
        for (let i = 0; i < checkedBox.length; i++) {
            ids[i] = checkedBox[i].value;
        }
        console.log(ids);

        $.ajax({
            type: 'POST',
            url: '/inventory/item-serial/remove',
            dataType: 'json',
            data: {
                  ids: ids
            },
            success: function(msg) {
                // /alert(msg.data);
                //need to refresh;
                //alert(previous_url);
                doPaginatorV1(previous_url,'item_serial_div');
                
            },
            fail: function(msg) {
                alert('failed');
            },
            done: function() {
                $('#overlay').fadeOut(300);
            }
         });
        
    }


</script>


