<?php
/**
 * @var \Application\Entity\NmtApplicationIncoterms $entity ;
 * 
 */
$form_action = '';
$form_title = '';

switch ($action) {

    case \Application\Model\Constants::FORM_ACTION_ADD:
        $form_action = '/application/incoterm/add';
        $form_title = $this->translate("Add Incoterm:");

        break;
    case \Application\Model\Constants::FORM_ACTION_EDIT:
        $form_action = '/application/incoterm/edit';
        $form_title = $this->translate("Edit Incoterm:");
        break;
}
?>




<div id="tabs" style="font-size: 10pt">
	<ul>
		<li><a href="#general"><?php echo $form_title;?></a></li>
					
		<?php if($action == \Application\Model\Constants::FORM_ACTION_EDIT):?>
        <?php endif;?>			
				</ul>

	<div id="general" style="font-size: 9pt">
		<!-- Tab1 -->
    	
 	<?php
if (count($errors) > 0) {
    echo '<div class="alert alert-danger alert-dismissible"" role="alert" style="font-size: 9.5pt"><a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>[ERROR]';

    echo '<ul>';
    foreach ($errors as $error) :
        echo '<li>' . $error . '</li>';
    endforeach
    ;
    echo '</ul>';
    echo '</div>';
}
?>
    
					<form id="New_Invoice_Row" class="form-horizontal"
			action="<?php echo $form_action;?>" method="post"
			enctype="multipart/form-data">

			<input type="hidden" name="redirectUrl"
				value="<?php echo $redirectUrl ?>" /> <input type="hidden"
				id="entity_id" name="entity_id"
				value="<?php if (!$entity == null): echo $entity->getId();endif;?>" />
					
							
            			<?php if($action == \Application\Model\Constants::FORM_ACTION_EDIT):?>
            				<input type="hidden" name="n" value="<?php echo $n;?>" />
            			<?php endif;?>
            			
            			
			<div class="form-group margin-bottom">
				<label class="control-label col-sm-2">Incoterm: </label>
				<div class="col-sm-3">
					<input tabindex="1" class="form-control input-sm" type="text"
						id="incoterm" placeholder="" name="incoterm"
						value="<?php if (!$entity== null): if($entity->getIncoterm()!==null): echo $entity->getIncoterm();endif;endif;?>">
				</div>
			</div>
			
			<div class="form-group margin-bottom">
				<label class="control-label col-sm-2">Incoterm1: </label>
				<div class="col-sm-3">
					<input tabindex="1" class="form-control input-sm" type="text"
						id="incoterm1" placeholder="" name="incoterm1"
						value="<?php if (!$entity== null): if($entity->getIncoterm1()!==null): echo $entity->getIncoterm1();endif;endif;?>">
				</div>
				
				<div class="col-sm-3">
										<input
											<?php if(!$entity== null): echo ($entity->getLocationRequired()=="1")?"checked":""; else: echo "checked"; endif;?>
											type="checkbox" name="locationRequired" value="1"><?php echo $this->translate("Location required");?> &nbsp;&nbsp;&nbsp;

									</div>
			</div>
			
			<div class="form-group margin-bottom">
									
								</div>
			

			<div class="form-group margin-bottom">
				<label class="control-label col-sm-2">Incoterm Description: </label>
				<div class="col-sm-8">
					<textarea class="form-control input-sm" type="text" rows="6"
						placeholder="" name="incotermDescription" style="font-size: 9pt;"><?php echo (!$entity == null)? $entity->getIncotermDescription():"";?></textarea>

				</div>
			</div>

			<hr style="margin: 5pt 1pt 5pt 1pt;">

			<div class="form-group margin-bottom" style="margin-top: 10pt">
				<label class="control-label col-sm-2" for="inputTag"></label>
				<div class="col-sm-3">
					<a tabindex="11" class="btn btn-default btn-sm"
						onclick="submitForm('New_Invoice_Row');" href="javascript:;"><small><i
							class="glyphicon glyphicon-floppy-disk"></i></small>&nbsp;<?php echo $this->translate("Save");?></a>
					<a tabindex="12" class="btn btn-default btn-sm"
						href="<?php echo $this->baseUrl ?>/procure/po/review?token=<?php echo (!$target == null)? $target->getToken():"";?>&entity_id=<?php echo (!$target == null)? $target->getId():"";?>"><small><i
							class="glyphicon glyphicon-remove"></i></small>&nbsp;<?php echo $this->translate("Cancel");?></a>

				</div>


			</div>
		</form>


	</div>

	<!-- end tab -->
</div>

