<div id="tabs" style="font-size: 9.5pt">
	<ul>
		<li><a href="#general"><?php echo $this->translate("Payment Terms");?>:</a></li>
	</ul>

	<div id="general">

		<ul class="nav nav-pills">
			<li><a style="color: #0080ff;"
				href="<?php echo $this->baseUrl ?>/application/payment-term/add"><?php echo $this->translate("Add New Payment Term");?>
	</a></li>
			</a>
			</li>

		</ul>


		<hr>
<?php

if ($total_records <= 0) {

    echo 'No Resources found!';
} else {

    if (! is_null($paginator)) {
        echo 'Result ' . $paginator->getMinInPage() . ' to ' . $paginator->getMaxInPage() . ' | ' . $total_records . ' Resources found!';
    } else {
        echo $total_records . ' Resources found!';
    }

    ?>

<table class="table table-bordered table-striped">
			<thead>
				<tr>
					<td><b>Incoterm</b></td>
					<td><b>Incoterm1</b></td>

					<td><b>Detail</b></td>
					<td><b>Prepayment</b></td>
					<td><b>Active</b></td>

					<td><b>Date</b></td>
					<td><b>Action</b></td>

				</tr>
			</thead>

			<tbody>
 
	 <?php

    $count = 0;
    foreach ($list as $a) :
        $count ++;

        /**@var \Application\Entity\NmtApplicationPmtTerm $a ;*/

        ?>
	 <tr>
					<td><?php echo $this->escapeHtml($a->getPmtTermCode());?></td>
					<td><?php echo $this->escapeHtml($a->getPmtTermName());?></td>

					<td><?php echo $this->escapeHtml($a->getDescription());?></td>
					<td><?php echo $this->escapeHtml($a->getIsPrepayment());?></td>
					<td><?php echo $this->escapeHtml($a->getIsActive());?></td>

					<td><?php echo date_format ( $a->getCreatedOn(), "d/m/Y  h:m");?> </td>

					<td><a
						href="<?php echo $this->baseUrl ?>/application/payment-term/edit?token=213214314dfds&entity_id=<?php echo $a->getID();?>&checksum=dfdfdfeedfds"><?php echo $this->translate("Edit");?>
</a></td>
				</tr>
<?php endforeach; ?>

 </tbody>
		</table>

<?php

    // ===============================
    if (! is_null($paginator)) :

        // change it only
        $base = $this->baseUrl . '/application/country/list';
        $_connector_symbol = '?';

        $last = $base . $_connector_symbol . 'page=' . $paginator->getTotalPages() . '&perPage=' . $paginator->getResultsPerPage();;
        $first = $base . $_connector_symbol . 'page=1&perPage=' . $paginator->getResultsPerPage();;

        $p1 = ($paginator->getPage()) - 1;
        $p2 = ($paginator->getPage()) + 1;

        $prev = $base . $_connector_symbol . 'page=' . $p1 . '&perPage=' . $paginator->getResultsPerPage();;
        $next = $base . $_connector_symbol . 'page=' . $p2 . '&perPage=' . $paginator->getResultsPerPage();;

        echo '<ul class="pagination pagination-sm">';

        if ($paginator->getPage() != 1 and $paginator->getTotalPages() > 10) {
            echo '<li><a href="' . $first . '"> |< </a></li>';
            echo '<li><a href="' . $prev . '"> < </a></li>';
        }

        for ($i = $paginator->getMinInPageSet(); $i <= $paginator->getMaxInPageSet(); $i ++) {

            $url = $base . $_connector_symbol . 'page=' . $i . '&perPage=' . $paginator->getResultsPerPage();;

            if ($i == $paginator->getPage()) {
                echo '<li><a class="active" href="#">' . $i . '</a></li>';
            } else {
                echo '<li><a href="' . $url . '"> ' . $i . ' </a></li>';
            }
        }
        if ($paginator->getPage() != $paginator->getTotalPages() and $paginator->getTotalPages() > 10) {
            echo '<li><a href="' . $next . '"> > </a></li>';
            echo '<li><a href="' . $last . '"> >| </a></li>';
        }
        echo '</ul>';
endif;

}
// ===============================
?>

</div>
</div>