<?php

/**
 *
 * @var \Application\Entity\NmtInventoryMv $target ;
 * @var \Application\Entity\NmtInventoryTrx $entity ;
 */
$form_action = '';
$form_title = '';

switch ($action) {

    case \Application\Model\Constants::FORM_ACTION_ADD:
        $form_action = '/inventory/gi-row/add';
        $form_title = $this->translate("Add Good Issue Row:");

        break;
    case \Application\Model\Constants::FORM_ACTION_EDIT:
        $form_action = '/inventory/gi-row/edit';
        $form_title = $this->translate("Edit Good Issue Row:");
        break;
}

?>

<div id="wrapper" class="toggled">

	<!-- Sidebar -->
	<div id="sidebar-wrapper" style="font-size: 9.5pt;">
	<?php
$current_step = "STEP2";
include (ROOT . '/module/Inventory/view/inventory/gi-create-wizard.php');
?>


	</div>
	<!-- /#sidebar-wrapper -->

	<!-- Page Content -->
	<div id="page-content-wrapper"
		style="font-size: 9.5pt; padding: 0px; margin: 0px;">
		<div class="container-fluid" id="main_container"
			style="font-size: 9.5pt; padding: 1px; margin: 0px;";>
			<a style="font-size: 9pt; margin: 2px; padding: 3px;"
				href="#menu-toggle" class="btn btn-primary btn-sm" id="menu-toggle"><span
				title="Hide Menu"><i class="fa fa-chevron-left" aria-hidden="true"></i>
					Menu <span></a>


			<div id="tabs" style="font-size: 10pt">
				<ul>
					<li><a href="#general"><small><i class="glyphicon glyphicon-plus">
							</i></i></small>&nbsp;<?php echo $form_title;?></a></li>
					<li><a
						href="<?php echo $this->baseUrl ?>/procure/gr-row/list?token=<?php echo (!$target == null)? $target->getToken():"";?>&target_id=<?php echo (!$target == null)? $target->getId():"";?>"><small><i
								class="glyphicon glyphicon-list"> </i></i></small>&nbsp;Current
							Rows</a></li>

					<li><a title="<?php echo $this->translate("Change Logs");?>"
						href="<?php echo $this->baseUrl ?>/inventory/change-log/list1?object_token=<?php echo (!$entity == null)? $entity->getToken():"";?>&object_id=<?php echo (!$entity == null)? $entity->getId():"";?>&class_name=<?php echo (!$entity == null)? get_class($entity):"";?>"><span
							class="glyphicon glyphicon-list"></span>&nbsp;Log</a></li>

				</ul>

				<div id="general" style="font-size: 9pt">
					<!-- Tab1 -->
					
						<?php

    echo "GI100-";
    echo (! $target == null) ? $target->getSysNumber() : "";

    if (count($errors) > 0) {
        echo '<div class="alert alert-danger alert-dismissible"" role="alert" style="font-size: 9.5pt"><a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>[ERROR]';

        echo '<ul>';
        foreach ($errors as $error) :
            echo '<li>' . $error . '</li>';
        endforeach
        ;
        echo '</ul>';
        echo '</div>';
    }
    ?>

					<!-- for all case: -->
					<form id="New_Invoice_Row" class="form-horizontal"
						action="<?php echo $form_action;?>" method="post"
						enctype="multipart/form-data">

						<input type="hidden" name="redirectUrl"
							value="<?php echo $redirectUrl ?>" /> <input type="hidden"
							id="target_id" name="target_id"
							value="<?php if (!$target == null): echo $target->getId();endif;?>" />
						<input type="hidden" id="target_token" name="target_token"
							value="<?php if (!$target == null): echo $target->getToken();endif;?>" />

						<input type="hidden" id="entity_id" name="entity_id"
							value="<?php if (!$entity == null): echo $entity->getId();endif;?>" />
						<input type="hidden" id="token" name="token"
							value="<?php if (!$entity == null): echo $entity->getToken();endif;?>" />

            			<?php if($action == \Application\Model\Constants::FORM_ACTION_EDIT):?>
            			<input type="hidden" name="n" value="<?php echo $n;?>" />
            			<?php endif;?>
            			
			<!-- for all case: -->

						<div id="new_row" class="collapse in">
							<div class="form-group margin-bottom">
								<label class="control-label col-sm-2"></label>
								<div class="col-sm-3">
									<input
										<?php if(!$entity== null): echo ($entity->getIsActive()=="1")?"checked":""; else: echo "checked"; endif;?>
										type="checkbox" name="isActive" value="1">&nbsp;Is
									Active&nbsp;&nbsp;&nbsp;&nbsp;
								</div>
							</div>
							<div class="form-group margin-bottom  required">

								<label class="control-label col-sm-2">Item: </label>
								<div class="col-sm-3">
									<input tabindex="2" class="form-control" type="text"
										id="item_name" placeholder="Enter keyword to search item..."
										name="item_name"
										value="<?php if (!$entity== null): if($entity->getItem()!==null): echo $entity->getItem()->getItemName(); endif;endif;?>">


									<input type="hidden" id="item_id" placeholder="" name="item_id"
										value="<?php if (!$entity== null): if($entity->getItem()!==null): echo $entity->getItem()->getID(); endif;endif;?>">

									<div id="item_url" style="display: none;"></div>


								</div>


								<div class="col-sm-1" style="margin: 0px">
									<span title="<?php echo $this->translate("Item Detail");?>"
										id="item_detail" style="display: none;"> &nbsp;&nbsp;<a
										style="color: #0080ff;" href="javascript:;"
										onclick="showSelectedItem();"><i style="color: navy"
											class="fa fa-info-circle fa-lg" aria-hidden="true"></i> </a>
										<br>
									</span>
								</div>
								<div class="col-sm-2" style="margin: 0px">
									<a style="color: #0080ff;" href="javascript:;"
										onclick="showJqueryDialog('Select Item','1350',$(window).height()-50, '/inventory/item-search/do1?target_id=item_id&target_name=item_name','j_loaded_data', true);">Select&nbsp;&nbsp;<i
										class="glyphicon glyphicon-folder-open"></i>
									</a>

								</div>
								<div class="col-sm-3">
									<a target="_blank" style="font-size: 9pt;"
										href="/inventory/item/list">Item List&nbsp;&nbsp;</a><small><i
										class="glyphicon glyphicon-new-window"></i></small>
								</div>
							</div>

							<div class="form-group margin-bottom required">
								<label class="control-label col-sm-2" for="inputTag">Quantity:</label>
								<div class="col-sm-3">
									<input tabindex="6" class="form-control input-sm" type="text"
										id="quantity" name="quantity"
										value="<?php echo (!$entity == null)? $entity->getQuantity():"";?>">
								</div>
							</div>

							<div class="form-group margin-bottom required">
								<label class="control-label col-sm-2">Issue for: </label>
								<div class="col-sm-3">
									<input disabled class="form-control input-sm" type="text"
										id="issue_for_name" placeholder="Select Item if any"
										name="issue_for_name"
										value="<?php if(!$entity== null): if($entity->getIssueFor()!==null):echo $entity->getIssueFor()->getItemName(); endif;endif;?>">
									<input type="hidden" id="issue_for_id" placeholder=""
										name="issue_for_id"
										value="<?php if(!$entity== null): if($entity->getIssueFor()!==null):echo $entity->getIssueFor()->getId(); endif;endif;?>">
								</div>


								<a style="color: #0080ff;" href="javascript:;"
									onclick="showJqueryDialog('Select Item','950','500', '/inventory/item-search/do1?target_id=issue_for_id&target_name=issue_for_name','j_loaded_data', true);">Select&nbsp;&nbsp;<i
									class="glyphicon glyphicon-folder-open"></i>
								</a>

							</div>

							<div class="form-group margin-bottom required">
								<label class="control-label col-sm-2" for="inputTag"><?php echo $this->translate("Cost Center");?>:</label>


								<div class="col-sm-3">
									<select name="cost_center_id" class="form-control input-sm">
										<option value=""><?php echo $this->translate("Select Cost Center");?></option>
   	    							<?php
            if ($cost_center_list !== null) :
                foreach ($cost_center_list as $cc) :

                    /**@var \Application\Entity\FinCostCenter $cc ; */

                    if ($entity !== null) :
                        if ($entity->getCostCenter() !== null) :
                            if ($entity->getCostCenter()->getId() == $cc->getId()) :
                                echo '<option selected value="' . $cc->getId() . '">' . $cc->getCostCenterName() . '</option>';
                            else :
                                echo '<option value="' . $cc->getId() . '">' . $cc->getCostCenterName() . ' - ' . $cc->getDescription() . '</option>';
                            endif;
                        else :
                            echo '<option value="' . $cc->getId() . '">' . $cc->getCostCenterName() . ' - ' . $cc->getDescription() . '</option>';
                        endif;
                    else :
                        echo '<option value="' . $cc->getId() . '">' . $cc->getCostCenterName() . ' - ' . $cc->getCostCenterName() . '</option>';
                    endif;
                endforeach
                ;
   	    							endif;

            ?>
   					</select>
								</div>


							</div>


							<div class="form-group margin-bottom">
								<label class="control-label col-sm-2">Remark:</label>
								<div class="col-sm-8">
									<input tabindex="9" class="form-control input-sm" type="text"
										placeholder="" name="remarks"
										value="<?php echo (!$entity == null)? $entity->getRemarks():"";?>">
								</div>
							</div>

							<div class="form-group margin-bottom">
								<label class="control-label col-sm-2" for="inputTag"></label>
								<div class="col-sm-3">
									<a tabindex="10" class="btn btn-default btn-sm"
										onclick="submitForm('New_Invoice_Row');" href="javascript:;"><small><i
											class="glyphicon glyphicon-floppy-disk"></i></small>&nbsp;Save</a>
									<a tabindex="11" class="btn btn-default btn-sm"
										href="<?php echo $this->baseUrl ?>/inventory/gi/review?token=<?php echo (!$target == null)? $target->getToken():"";?>&entity_id=<?php echo (!$target == null)? $target->getId():"";?>"><small><i
											class="glyphicon glyphicon-remove"></i></small>&nbsp;Cancel</a>

								</div>
							</div>

						</div>
					</form>


					<!-- end tab -->
				</div>
			</div>
		</div>
		<!-- /#page-content-wrapper -->

	</div>
	<!-- /#wrapper -->



	<script type="text/javascript">
 	$( "#item_name" ).focus();
 	 

    $( "#item_name" ).autocomplete({
        source: "/inventory/item-search/auto-complete",
        minLength: 2,
        select: function( event, ui ) {
        	 $( "#item_id" ).val(ui.item.id);
        	    
             $('#item_url').text('/inventory/item/show1?tab_idx=0&entity_id='+ui.item.id+'&token='+ui.item.token);
             
           
         	 	$('#global-notice').show();
         		$('#global-notice').html('"' + ui.item.value + '" selected');
         		$('#global-notice').fadeOut(5000);
         		//$("#jquery_dialog").dialog("close");
   
          	$('#item_detail').show();
           	$( "#quantity" ).focus();
       
        }
       
      })
      .autocomplete( "instance" )._renderItem = function( ul, item ) {
    	  var serial_no = "";
    	  if(item.item_serial!=""){
    		  serial_no = " : " + item.item_serial;
    	  }
    	   
         return $( "<li>" )
           .append( "<div style='padding-bottom: 5px; border-bottom: thin solid gray;'><span style='font-size: 9.5pt;font-weight: bold;'>" + item.value + "</span><br><span style='color:gray;font-size: 9pt;'>" + item.item_sku + serial_no +"<span></div>" )
           .appendTo( ul );
       };

    $('#quantity').bind('change', function() {
         });

    function showSelectedItem(){
    	//var url= '/inventory/item/show1?tab_idx=7&entity_id=<?php echo $target->getId();?>&token=<?php echo $target->getToken();?>';
    	var url=  $('#item_url').text();
      	showJqueryDialog('Item Detail','1450',$(window).height()-40, url,'j_loaded_data', true);
    }

    <?php
    if ($entity !== null) :
        if ($entity->getItem() !== null) :
            ?>

    	    		  $("#item_id" ).val(<?php echo +$entity->getItem()->getId();?>);      	  
    	    	      $('#item_url').text('/inventory/item/show1?tab_idx=0&entity_id=<?php echo +$entity->getItem()->getId();?>&token=<?php echo $entity->getItem()->getToken();?>');
    	    		  $('#item_detail').show();
    	    		    

    	    		<?php
    	    		endif;
    	    		endif;


    ?>

 </script>