<?php

/**@var \Application\Entity\NmtInventoryGi $target ;
 @var \Application\Entity\NmtInventoryTrx $entity ; */

$current_step = "STEP2";

?>

<?php
if (count($errors) > 0) {
    echo '<div class="alert alert-danger" role="alert" style="font-size: 10.5pt">';

    echo '<ul>';
    foreach ($errors as $error) :
        echo '<li>' . $error . '</li>';
    endforeach
    ;
    echo '</ul>';
    echo '</div>';
}
?>
<div id="tabs" style="font-size: 9.5pt">
	<ul>
		<li><a href="#general"><small><i class="glyphicon glyphicon-plus"> </i></i></small>&nbsp;New
				Row</a></li>
		<li><a
			href="<?php echo $this->baseUrl ?>/procure/gr-row/list?token=<?php echo (!$target == null)? $target->getToken():"";?>&target_id=<?php echo (!$target == null)? $target->getId():"";?>"><small><i
					class="glyphicon glyphicon-list"> </i></i></small>&nbsp;Current
				Rows</a></li>
	</ul>

	<div id="general" style="font-size: 9pt;">
		<!-- Tab1 -->

		<h4>
			<strong>Goods Issue:</strong>
		</h4>

		<form id="Create_Inv_Form" class="form-horizontal" action=""
			method="post" enctype="multipart/form-data">
			<input type="hidden" name="redirectUrl"
				value="<?php echo $redirectUrl ?>" />
			<fieldset>
				<legend style="font-size: 9pt; color: gray;">
					<small><span class="glyphicon glyphicon-triangle-right"></span></small>&nbsp;
					<a style="font-size: 9pt; color: gray;" href="#invoice_header"
						class="" data-toggle="collapse">HEADER (<?php echo (!$target == null)? $target->getSysNumber():"";?>)</a>
				</legend>

				<div id="invoice_header" class="collapse">


					<div class="form-group margin-bottom required">
						<div class="col-sm-3">

							<input
								<?php if(!$target== null): echo ($target->getIsActive()=="1")?"checked":""; else: echo "checked"; endif;?>
								type="checkbox" name="isActive" value="1">&nbsp;Is
							Active&nbsp;&nbsp;&nbsp;&nbsp;

						</div>
						
					</div>



					<div class="form-group margin-bottom">
						<label class="control-label col-sm-2">Description</label>
						<div class="col-sm-8">
							<input class="form-control input-sm" type="text" placeholder=""
								name="remarks"
								value="<?php echo (!$target == null)? $target->getRemarks():"";?>">
						</div>
					</div>
					<br>
					<div class="form-group margin-bottom">
						<label class="control-label col-sm-2" for="inputTag"></label>
						<div class="col-sm-3">
							<a class="btn btn-default"
								href="<?php echo $this->baseUrl ?>/procure/po/edit?token=<?php echo (!$target == null)? $target->getToken():"";?>&entity_id=<?php echo (!$target == null)? $target->getId():"";?>"><small><i
									class="glyphicon glyphicon-pencil"></i></small>&nbsp;Edit</a>
						</div>
					</div>
				</div>
			</fieldset>

		</form>

		<form id="New_Invoice_Row" class="form-horizontal"
			action="<?php echo $this->baseUrl ?>/inventory/gr-row/add"
			method="post" enctype="multipart/form-data">
			<input type="hidden" name="redirectUrl"
				value="<?php echo $redirectUrl ?>" /> <input type="hidden"
				id="gr_id" name="gr_id"
				value="<?php if (!$target == null): echo $target->getId();endif;?>" />
			<input type="hidden" id="gr_token" name="gr_token"
				value="<?php if (!$target == null): echo $target->getToken();endif;?>" />


			<fieldset>
				<legend style="font-size: 9pt; color: gray;">
					<small><span class="glyphicon glyphicon-triangle-right"></span></small>&nbsp;
					<a style="font-size: 9pt; color: gray;" href="#new_row" class=""
						data-toggle="collapse">NEW ROW:</a>
				</legend>
				<div id="new_row" class="collapse in">
					<div class="form-group margin-bottom">
						<label class="control-label col-sm-2"></label>
						<div class="col-sm-3">
							<input
								<?php if(!$entity== null): echo ($entity->getIsActive()=="1")?"checked":""; else: echo "checked"; endif;?>
								type="checkbox" name="isActive" value="1">&nbsp;Is
							Active&nbsp;&nbsp;&nbsp;&nbsp;
						</div>
					</div>
					<div class="form-group margin-bottom  required">
						<label class="control-label col-sm-2">Item: </label>
						<div class="col-sm-3">
							<input tabindex="2" class="form-control" type="text"
								id="item_name" placeholder="Enter keyword to search item..."
								name="item_name"
								value="<?php if (!$entity== null): if($entity->getItem()!==null): echo $entity->getItem()->getItemName(); endif;endif;?>">


							<input type="hidden" id="item_id" placeholder="" name="item_id"
								value="<?php if (!$entity== null): if($entity->getItem()!==null): echo $entity->getItem()->getID(); endif;endif;?>">
						</div>
						<div class="col-sm-3">
							<a style="color: #0080ff;" href="javascript:;"
								onclick="showJqueryDialog('Select Item','1000',$(window).height()-100, '/inventory/item-search/do1?target_id=item_id&target_name=item_name','j_loaded_data', true);">Select&nbsp;&nbsp;<i
								class="glyphicon glyphicon-folder-open"></i>
							</a>

						</div>
						<div class="col-sm-3">
							<a target="_blank" style="font-size: 9pt;"
								href="/inventory/item/list">Item List&nbsp;&nbsp;</a><small><i
								class="glyphicon glyphicon-new-window"></i></small>
						</div>
					</div>
					<div class="form-group margin-bottom required">
						<label class="control-label col-sm-2" for="inputTag">Quantity:</label>
						<div class="col-sm-3">
							<input tabindex="6" class="form-control input-sm" type="text"
								id="quantity" name="quantity"
								value="<?php echo (!$entity == null)? $entity->getQuantity():"";?>">
						</div>
					</div>
					<div class="form-group margin-bottom">
						<label class="control-label col-sm-2">Remark:</label>
						<div class="col-sm-8">
							<input tabindex="9" class="form-control input-sm" type="text"
								placeholder="" name="remarks"
								value="<?php echo (!$entity == null)? $entity->getRemarks():"";?>">
						</div>
					</div>

					<div class="form-group margin-bottom">
						<label class="control-label col-sm-2" for="inputTag"></label>
						<div class="col-sm-3">
							<a tabindex="10" class="btn btn-default btn-sm"
								onclick="submitForm('New_Invoice_Row');" href="javascript:;"><small><i
									class="glyphicon glyphicon-floppy-disk"></i></small>&nbsp;Save</a>
							<a tabindex="11" class="btn btn-default btn-sm"
								href="<?php echo $this->baseUrl ?>/procure/po/add1?token=<?php echo (!$target == null)? $target->getToken():"";?>&entity_id=<?php echo (!$target == null)? $target->getId():"";?>"><small><i
									class="glyphicon glyphicon-remove"></i></small>&nbsp;Cancel</a>

						</div>
					</div>

				</div>
			</fieldset>
		</form>



		<!-- Tab1 -->
	</div>
</div>



<script type="text/javascript">
	$("#Create_Inv_Form :input").attr("disabled", "disabled");
    $( "#pr_item_name" ).autocomplete({
        source: "/procure/pr-search/auto-complete",
        minLength: 2,
        select: function( event, ui ) {
            $( "#pr_row_id" ).val(ui.item.pr_row_id);
            $( "#quantity" ).val(ui.item.row_quantity);
            $( "#item_id" ).val(ui.item.item_id);
            $( "#item_name" ).val(ui.item.item_name);
                        
             //alert(ui.item.item_id);
            $('#global-notice').show();
            $('#global-notice').html('"' + ui.item.item_name + '" selected');
            $('#global-notice').fadeOut(5000);
        }
        })
        .autocomplete( "instance" )._renderItem = function( ul, item ) {
        return $( "<li>" )
          .append( "<div style='padding-bottom: 15px; border-bottom: thin solid gray;'><span style='font-size: 9.5pt;font-weight: bold;'>" + item.item_sku_key  +  " | " + item.item_name + " | Q'ty: " + item.row_quantity + 
                  "</span><br><span style='padding-top: 7px;color:gray;font-size: 9pt;'>" + item.pr_number + " | " + item.row_name +"<span></div>" )
 
 
 
 //         .append( "<div style='padding-bottom: 5px; border-bottom: thin solid gray;color:gray;font-size: 9.5pt;'>" + item.pr_number + "<br><span style='color:black;font-size: 9.5pt;'>" + item.item_sku_key  +  " | " + item.item_name + " | Q'ty: " + item.row_quantity + "<span></div>" )
          .appendTo( ul );
        };	

        $( "#pr_item_name" ).focus();   

    $( "#item_name" ).autocomplete({
        source: "/inventory/item-search/auto-complete",
        minLength: 2,
        select: function( event, ui ) {
      	  $( "#item_id" ).val(ui.item.id);
        
      	 	$('#global-notice').show();
      		$('#global-notice').html('"' + ui.item.value + '" selected');
      		$('#global-notice').fadeOut(5000);
      		//$("#jquery_dialog").dialog("close");
        }
       
      })
      .autocomplete( "instance" )._renderItem = function( ul, item ) {
    	  var serial_no = "";
    	  if(item.item_serial!=""){
    		  serial_no = " : " + item.item_serial;
    	  }
    	   
         return $( "<li>" )
           .append( "<div style='padding-bottom: 5px; border-bottom: thin solid gray;'><span style='font-size: 9.5pt;font-weight: bold;'>" + item.value + "</span><br><span style='color:gray;font-size: 9pt;'>" + item.item_sku + serial_no +"<span></div>" )
           .appendTo( ul );
       };

    $('#quantity').bind('change', function() {
       	$('#net_amount').val($('#unit_price').val() * $('#quantity').val());
       	$('#gross_amount').val($('#net_amount').val()*1 + $('#tax_amount').val()*1);

    });

    $('#unit_price').bind('change', function() {
    	$('#net_amount').val($('#unit_price').val() * $('#quantity').val());
    	$('#gross_amount').val($('#net_amount').val()*1 + $('#tax_amount').val()*1);	
    });

    $('#tax_rate').bind('change', function() {
    	$('#tax_amount').val($('#net_amount').val() * $('#tax_rate').val()/100);
    	$('#gross_amount').val($('#net_amount').val()*1 + $('#tax_amount').val()*1);
    });

	$( "input[id='trx_date']").datepicker({ firstDay: 1, dateFormat: 'yy-mm-dd',closeText: 'X',changeMonth: true, changeYear: true});

    $( function() {
         $( "#vendor_name" ).autocomplete({
          source: "/bp/vendor-search/auto-complete",
          minLength: 3,
          select: function( event, ui ) {
        	  $( "#vendor_id" ).val(ui.item.id);
            //alert	( "Selected: " + ui.item.value + " aka " + ui.item.id );
        	  //alert($( "#vendor_id" ).val());
    
        	 	$('#global-notice').show();
        		$('#global-notice').html('"' + ui.item.value + '" selected');
        		$('#global-notice').fadeOut(5000);
        		//$("#jquery_dialog").dialog("close");
          }
          })
          .autocomplete( "instance" )._renderItem = function( ul, item ) {
          return $( "<li>" )
            .append( "<div style='padding-bottom: 5px; border-bottom: thin solid gray;'>" + item.value + "<br><span style='color:gray;font-size: 9pt;'>" + item.vendor_country + "<span></div>" )
            .appendTo( ul );
        };
          ;
     } );

 </script>