
<ul class="nav nav-pills">
 <li class="active"><a href="#">Add department member:</a></li>


</ul>


<form action="<?php echo $this->baseUrl ?>/application/department/add-member"	method="post" enctype="multipart/form-data" id="New Sparepart">
	
<input type="hidden" name="id" value="<?php echo (int) $department->id; ?>" />
<input type="hidden" name="redirectUrl" value="<?php echo $redirectUrl ?>" />

<table class="pure-table pure-table-bordered">
<thead>
	<tr>
		<td></td>
		<td>First Name</td>
		<td>Last Name</td>
		<td>Email</td>		
	</tr>
</thead>
<tbody>

 <?php 
	 
	 $count = 0;
	foreach ($users as $user) :
	 	 $count++;
	 echo  ($count % 2 == 1) ? "<tr>" : "<tr class=\"pure-table-odd\">";
	 	 
	 ?>	
 	

    	<td><input type="checkbox" name="users[]" value="<?php echo $this->escapeHtml($user['id']);?>" class="checkbox"/></td>
    	<td><?php echo $this->escapeHtml($user['firstname']);?></td>
    	<td><?php echo $this->escapeHtml($user['lastname']);?></td>
    	<td><?php echo $this->escapeHtml($user['email']);?></td>
 
     	</tr>
<?php endforeach; ?>

<tr>
	<td></td> 
	<td><input type="submit" name="add" value="Add" />	</td>
</tr>
</tbody>	
</table>
