
<h5>Edit Purchasing Item:</h5>

<?php

if (count ( $errors ) > 0) {
	echo '<div class="alert alert-error">';
	
	echo '<ul>';
	foreach ( $errors as $error ) :
		echo '<li>' . $error . '</li>';
	endforeach
	;
	echo '</ul>';
	echo '</div>';
}
?>

<form class="form-horizontal" 	action="<?php echo $this->baseUrl ?>/procurement/po/edit-item"
	method="post" enctype="multipart/form-data" id="NewSP">
	<input type="hidden" name="redirectUrl"
		value="<?php echo $redirectUrl ?>" /><input
		type="hidden" name="pr_item_id" value="<?php echo $pr_item->id ?>" />
	<input type="hidden" name="vendor_id" id="vendor_id" value="<?php echo $po_item !=null?$po_item->vendor_id:"";?>" />
	<input type="hidden" name="id" id="id" value="<?php echo $po_item->id ?>" />
	
	<div class="control-group">
		<label class="control-label" for="inputTag">Vendor:</label>
		<div class="controls">

 		
			<input readonly type="text" id="vendor" placeholder="" name="vendor"
				value="<?php echo $po_item !=null?$po_item->vendor_name:"";?>"> 
			
		
		<a href="javascript:;" onclick="loadVendorList();"
				class="helper"> Select Vendor <i class=" icon-folder-open"></i></a>

		<?php 
			if ($pr_item->article_id > 0) :
			echo '<div style="color: gray;">Last vendor:' . $pr_item->article_vendor_name .'</div>';
		endif;
		
		if ($pr_item->sparepart_id > 0) : 
     		echo '<div style="color: gray;">Last vendor:' .$pr_item->sp_vendor_name.'</div>';
		endif; ?>
		</div>
	</div>
	<hr>

	<div class="control-group">
		<label class="control-label" for="inputTag">Items:</label>
		<div class="controls">
			<input type="text" placeholder="" name="name"
				value="<?php echo $po_item !=null?$po_item->name:"";?>">
		</div>
	</div>
	<div class="control-group">
		<label class="control-label" for="inputTag">Item Code (if any):</label>
		<div class="controls">
			<input type="text" placeholder="" name="code"
				value="<?php echo $po_item !=null?$po_item->code:"";?>">
		</div>
	</div>

	<div class="control-group">
		<label class="control-label" for="inputTag">Item Unit:</label>
		<div class="controls">
			<input type="text" placeholder="" name="code"
				value="<?php echo $po_item !=null?$po_item->unit:"";?>">
		</div>
	</div>

	<div class="control-group">
		<label class="control-label" for="inputTag">Ordered Quantity:</label>
		<div class="controls">
			<input readonly type="text" id="inputTag" placeholder=""
				name="delivered_quantity" value="<?php echo $pr_item->quantity ?>">
         </div>
	</div>

	<div class="control-group">
		<label class="control-label" for="inputTag">Price:</label>
		<div class="controls">
			<input  type="text" id="inputTag" placeholder="" name="price" value="<?php echo $po_item !=null?$po_item->price:"";?>">
			<?php 
			if ($pr_item->article_id > 0) :
			echo '<span style="color: gray;">Last price:' . $pr_item->article_price.'</span>';
		endif;
		
		if ($pr_item->sparepart_id > 0) : 
     		echo '<span style="color: gray;">Last price:' .$pr_item->sp_price.'</span>';
		endif; ?>
		</div>
	</div>

	<div class="control-group">
		<label class="control-label" for="inputTag">Currency:</label>
		<div class="controls">
			<select style="wight: 10px" name="curreny" id="curreny">

				<option value="">---Please select---</option>
				<option <?php echo $po_item->currency =="USD"? "selected='selected'":"";?> value="USD">USD</option>
				<option <?php echo $po_item->currency =="LAK"? "selected='selected'":"";?> value="LAK">LAK</option>
				<option <?php echo $po_item->currency =="THB"? "selected='selected'":"";?> value="THB">THB</option>

			</select>
			
			<?php 
			if ($pr_item->article_id > 0) :
			echo '<span style="color: gray;">Last price:' . $pr_item->article_currency.'</span>';
		endif;
		
		if ($pr_item->sparepart_id > 0) : 
     		echo '<span style="color: gray;">Last currency:' .$pr_item->sp_currency.'</span>';
		endif; ?>
		</div>
	</div>

	<div class="control-group">
		<label class="control-label" for="inputTag">Payment Method:</label>
		<div class="controls">
			<select name="payment_method" id="payment_method">

				<option selected="selected" value="">---Please select---</option>
				<option <?php echo $po_item->payment_method=='By Cash'? "selected='selected'":"";?> value="By Cash">By Cash</option>
				<option <?php echo $po_item->payment_method=='Bank Transfer'? "selected='selected'":"";?> value="Bank Transfer">Bank Transfer</option>
				<option <?php echo $po_item->payment_method=='Other'? "selected='selected'":"";?> value="Other">Other Method</option>
			</select>
		</div>
	</div>



	<div class="control-group">
		<label class="control-label" for="inputDescription">Remarks:</label>
		<div class="controls">
			<textarea id="inputDescription" placeholder="" rows="2" cols="5"
				name="remarks"></textarea>
		</div>
	</div>

	<div class="control-group">
		<div class="controls">
			<button type="submit" class="btn">
				<i class="icon-plus"> </i> Add
			</button>
		</div>
	</div>
</form>



<div id="dialog" style="display: none;">Check code...</div>

<!-- Modal -->
	<div id="myModal" class="modal hide" role="dialog">
	  <div class="modal-dialog">
	  	 <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h5 class="modal-title">Add To Cart</h5>
      </div>
	      <div class="modal-body">
	  <div>
	  <span id="_status"></span>
	  </div>

<form class="form-horizontal" action="<?php echo $this->baseUrl ?>/procurement/pr/select-item-2"	method="post" enctype="multipart/form-data" id="NewSP" >
<input type="hidden" name="redirectUrl" value="<?php echo $redirectUrl ?>" />
<input type="hidden" name="article_id" id ="item_id" value="" />
 	
	 	 <div class="control-group">
	        <label class="control-label" for="inputNameLocal">Priority:</label>
        <div class="controls">
        	<select name="priority" id ="item_priority">
        		<option value="Low">Low</option>
        		<option value="Medium" selected>Medium</option>
        		<option value="High">High</option>
        		<option value="Urgent">Urgent</option>
 			</select>
	     </div>
      </div>
      	
      <div class="control-group">
        <label class="control-label" for="inputTag">Name:</label>
        <div class="controls">
          <input type="text" id="item_name" placeholder="" name="name" value="article">
        </div>
      </div>
      
      <div class="control-group">
        <label class="control-label" for="inputTag">Unit</label>
        <div class="controls">
          <input type="text" id="item_unit" placeholder="" name="unit" value="">
        </div>
      </div>
      
       <div class="control-group">
        <label class="control-label" for="inputTag">Quantity:</label>
        <div class="controls">
          <input type="text" id="item_quantity" placeholder="" name="quantity" value="">
        </div>
      </div>
      
     
      
      <div class="control-group">
        <label class="control-label" for="inputNameLocal">Requested Delivery Date:</label>
        <div class="controls">
          <input type="text" id="end_date" placeholder="click to select" name="EDT" value="">
        </div>
      </div>
      
       <div class="control-group">
        <label class="control-label" for="inputDescription">Reason /Note:</label>
        <div class="controls">
          <textarea id="item_remarks" placeholder="" rows="2" cols="5" name="remarks"></textarea>
        </div>
      </div>
    </form>
	      </div>
	      
		  <div class="modal-footer">
	        <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
	        <button onclick="addItemToCart('ARTICLE');" type="button" class="btn btn-primary">Add To Cart</button>
	      </div>
	   </div>
	</div>
	
	<!-- Modal -->
	<div id="myModal1" class="modal hide" role="dialog">
	  <div class="modal-dialog">
	      <div class="modal-body">
	        <p>Working on it........Please Wait!</p>
	      </div>
	   </div>
	</div>		



