<?php include (ROOT.'\module\Procurement\view\procurement\menu.php'); ?>
<script language="javascript">
			var id_array = [];
</script>


<?php

if ($department_id == 0 or $department_id == null):
	$department_selected = "Department = All";
endif;

if ($vendor_id <= 0 or $vendor_id == null):
$vendor_selected = "Vendor = All";
endif;

if ($balance== 2 or $balance == null):
$balance_selected = "Balance = All";
endif;

if ($balance== 0 ):
$balance_selected = "Balance = 0 (Fulfilled Items)";
endif;

if ($balance== 1 ):
$balance_selected = "Balance >0 (Pending Items)";
endif;

if ($balance== -1 ):
$balance_selected = "Balance <0 (Some free items)";
endif;


if ($currency == "" or $currency == null):
$currency_selected = "Currency = all";
	else:
$currency_selected = "Currency = ".$currency;
endif;

if ($payment_method == "" or $payment_method == null):
	$payment_method_selected = "Payment method = All";
else:
	$payment_method_selected = "Payment method = ".$payment_method;
endif;

?>


<h4> Purchase Order Items:</h4>
<div class="panel-group">
	<div class="panel panel-default">
		<div class="panel-heading">
			<h5 class="panel-title">
				<a data-toggle="collapse" href="#collapse1"><i class="icon-filter">
				</i> FILTER</a>
				
			</h5>
		</div>
		<div id="collapse1"
			class="panel-collapse collapse">
			<div class="panel-body">
			<div style="padding:3px;background: url(/images/bg1.png); background-repeat:repeat-x; background-color: #FFFFFF;">
				<form class="form-horizontal"
					action="<?php echo $this->baseUrl ?>/procurement/po/list"
					method="get" enctype="multipart/form-data" id="ReportForm">
					<div class="control-group">
						<label class="control-label" for="inputNameLocal">PR by
							Department: </label>
						<div class="controls">
							<select name="department_id">
								<option value="">All departments</option>
   	    	<?php
									
									foreach ( $departments as $dept ) :
										if ($dept->id === $department_id) :
											$department_selected = "Department = ".  $dept->name;
										
											echo '<option selected="selected" value="' . $dept->id . '">' . $dept->name . '</option>';
										 else :
											echo '<option value="' . $dept->id . '">' . $dept->name . '</option>';
										endif;
									endforeach
									;
									?>
   	
   					</select>
						</div>
					</div>

					
					
					<div class="control-group">
						<label class="control-label" for="inputNameLocal">Balance: </label>
						<div class="controls">
							<select name="balance">
								<option value="2">All</option>
								<option <?php echo $balance=='0'? "selected='selected'":"";?>
									value="0">Balance=0 (Fulfilled Items)</option>
								<option <?php echo $balance=='1'? "selected='selected'":"";?>
									value="1">Balance>0 (Pending Items)</option>
								<option <?php echo $balance=='-1'? "selected='selected'":"";?>
									value="-1">Balance<0 (Some Free Items)</option>

							</select>
						</div>
					</div>
						<div class="control-group">
						<label class="control-label" for="inputTag">Currency:</label>
						<div class="controls">
							<select style="wight: 10px" name="currency" id="currency">
				
								<option selected="selected" value="">All</option>
								<option <?php echo $currency=='USD'? "selected='selected'":"";?> value="USD">USD</option>
								<option <?php echo $currency=='LAK'? "selected='selected'":"";?> value="LAK">LAK</option>
								<option <?php echo $currency=='THB'? "selected='selected'":"";?> value="THB">THB</option>
				
							</select>
							</div>
					</div>
					
					<div class="control-group">
					<label class="control-label" for="inputTag">Payment Method:</label>
						<div class="controls">
							<select name="payment_method" id="payment_method">
				
								<option selected="selected" value="">All</option>
								<option <?php echo $payment_method=='By Cash'? "selected='selected'":"";?> value="By Cash">By Cash</option>
								<option <?php echo $payment_method=='Bank Transfer'? "selected='selected'":"";?> value="Bank Transfer">Bank Transfer</option>
								<option <?php echo $payment_method=='Other'? "selected='selected'":"";?> alue="Other">Other Method</option>
							</select>
						</div>
					</div>
					
					<div class="control-group">
						<label class="control-label" for="inputNameLocal">Vendor: </label>
						<div class="controls">
							<select name="vendor_id">
								<option value="-1">All</option>
								<?php
									
									foreach ( $vendors as $a ) :
										if ($a->vendor_id === $vendor_id) :
												$vendor_selected = "Vendor = All" . $a->vendor_name;;
											echo '<option selected="selected" value="' . $a->vendor_id . '">' . $a->vendor_name .'</option>';
										else :
											echo '<option value="' . $a->vendor_id . '">' . $a->vendor_name . '</option>';
										endif;
									endforeach
									;
									?>

							</select>
						</div>
					</div>

					<div class="control-group">
						<div class="controls">
							<button type="submit" class="btn">
								<i class="icon-search"> </i> show
							</button>
						</div>
					</div>
				</form>
				<hr>
			</div>
			</div>
		</div>
	</div>
</div>
<hr>

<?php  	

	if (! is_null ( $paginator )) :
		echo '<h5>'. $paginator->minInPage . ' to ' . $paginator->maxInPage . ' of ' . $total_items . 
		' Item(s) found | ' . $department_selected . ' | ' . 
	 $vendor_selected . ' | ' .
	 $balance_selected . ' | ' .
	 $currency_selected . ' | ' .
	 $payment_method_selected. ' | ' .
	 '</h5>';	
	 else :
	 echo '<h5>' . $total_items .
	 ' Item(s)found | <span class="label label-info">' . $department_selected . ' | ' . 
	 $vendor_selected . ' | ' .
	 $balance_selected . ' | ' .
	 $currency_selected . ' | ' .
	 $payment_method_selected. ' | ' .
	 '</h5>';		
	 endif;
	 ?>

<?php  	if (count($po_items) >0): ?>
<ul class="nav nav-pills">
 <li><a href="<?php echo $this->baseUrl.'/procurement/po/list?output=csv&department_id='.$department_id.
 '&vendor_id='.$vendor_id.'&balance='.$balance.'&currency='.$currency.'&payment_method='.$payment_method;?>"><i class="icon-download-alt">  </i> Download (csv)</a> 
</li>
 <?php if($payment_method=='By Cash'):?>
 	<li><a href="<?php echo $this->baseUrl ?>/procurement/cash/request" target=>Cash Request</a>
 <?php endif;?> 
</li>
</ul>
<?php endif;?> 

	

<?php  	if (count($po_items) >0): ?>


<table class="table table-striped table-bordered">
	<thead>
		<tr>
			<td><input type="checkbox" id="select_ALL" name="SelectAll"
				value="YES" /> <b>All</b></td>

		<td><b>Requester</b></td>
		<td><b>Item Name</b></td>
		<td ><b data-toggle="tooltip" title = "Ordered Quantity">Ordered <br> Quantity</b></td>
		
		<td ><b data-toggle="tooltip" title = "Purchasing Quantity">Purchasing<br>Quantity</b></td>
		<td ><b data-toggle="tooltip" title = "Purchasing Quantity">Received<br>Quantity</b></td>
		<td ><b data-toggle="tooltip" title = "Purchasing Quantity">Notified<br>Quantity</b></td>
		<td ><b data-toggle="tooltip" title = "Purchasing Quantity">Confirmed<br>Quantity</b></td>
		<td ><b data-toggle="tooltip" title = "Purchasing Quantity">Rejected<br>Quantity</b></td>
		<td><b data-toggle="tooltip" title="Balance">Balance</b></td>
		<td><b>Unit <br>Price</b></td>
		<td><b>Total</b></td>
			<td><b data-toggle="tooltip" title="Currency">Curr.</b></td>
	<td><b>Vendor</b></td>
		</tr>
	</thead>
	<tbody>	
 
  <?php
	
	$count = 0;
	foreach ( $po_items as $item ) :
		$count ++;
		//echo ($count % 2 == 1) ? "<tr>" : "<tr class=\"pure-table-odd\">";
		
		?>
		<tr>
		<td><?php echo ($paginator===null)? $count:$paginator->minInPage -1+ $count;?></td>
		
	 	<td><input class="checkbox1" type="checkbox" name="po_items[]"
		value="<?php echo $item->id ;?>" /></td>

		<td><?php echo $item->pr_requester_name;?>
		
		<div style="color: gray; font-size: 8pt;">
			Dept.:<?php echo $item->pr_of_department;?><br>
					<a style="color: black; font-size: 8pt;" href="<?php echo $this->baseUrl ?>/procurement/pr/process?pr_id=<?php echo $item->pr_id;?>"
				target="_blank">#<?php echo $item->auto_pr_number;?></a>
	
			</div>
		</td>
		<td>
			<div class="dropdown">
					<a class="dropdown-toggle" type="button" data-toggle="dropdown"
						href="#"><span style="color: black;"><b><?php echo $item->name;?></b></span>
					<span class="caret"></span></a>
					<ul class="dropdown-menu">
	    	     	
    
    	<?php if ($item->confirmed_balance > 0) : ?>
 <li>  			
 <a href="<?php echo $this->baseUrl ?>/procurement/gr/receive?pr_item_id=<?php echo $this->escapeHtml($item->pr_item_id);?>&po_item_id=<?php echo $this->escapeHtml($item->id)?>">
 <i class="icon-check"></i> Receive</a></li>
   	<li class="divider"></li>
 <li>
 <a href="<?php echo $this->baseUrl ?>/procurement/po/edit-item?id=<?php echo $this->escapeHtml($item->id)?>&pr_item_id=<?php echo $this->escapeHtml($item->pr_item_id);?>">
 <i class="icon-pencil">  </i> Edit</a></li>  	
    	<?php endif; ?>
	

		
		
		</td>
		<td><?php echo $item->ordered_quantity;?></td>
		
		<td><?php echo $item->ordered_quantity;?></td>
		<td>
		<a href="<?php echo $this->baseUrl ?>/procurement/gr/receive-list?po_item_id=<?php echo $item->id;?>" target="_blank"><?php echo $item->total_received_quantity;?></a>
		</td>
		<td><?php echo $item->unconfirmed_quantity;?></td>
		<td><?php echo $item->confirmed_quantity;?></td>
		<td><?php echo $item->rejected_quantity;?></td>
	<td><?php echo $item->confirmed_balance;?></td>
		
		
		<td><?php echo $item->price;?></td>
		<td><?php echo ($item->price*$item->total_received_quantity);?></td>
		<td><?php echo $item->currency;?></td>
		
		
		<td>
		<a href="<?php echo $this->baseUrl ?>/procurement/vendor/show?id=<?php echo $item->vendor_id;?>" target="_blank"><?php echo $item->vendor_name;?></a>
<div style="color: gray; font-size: 8pt;">
			<?php echo $item->payment_method;?><br>
			</div>
</td>
	
<?php endforeach; ?>

 			

</tbody>
</table>
<?php else: echo 'Please change filter! <hr>'?>


<?php endif; ?>




<?php
	
	if (! is_null ( $paginator )) {
		
		// change it only
		$base = $this->baseUrl . '/procurement/po/list?department_id='.$department_id.'&vendor_id='.$vendor_id.'&balance='.$balance.'&currency='.$currency.'&payment_method='.$payment_method;
		
		$_connector_symbol = '&';
		
		$last = $base . $_connector_symbol . 'page=' . $paginator->totalPages . '&perPage=' . $paginator->resultsPerPage;
		$first = $base . $_connector_symbol . 'page=1&perPage=' . $paginator->resultsPerPage;
		
		$p1 = ($paginator->page) - 1;
		$p2 = ($paginator->page) + 1;
		
		$prev = $base . $_connector_symbol . 'page=' . $p1 . '&perPage=' . $paginator->resultsPerPage;
		$next = $base . $_connector_symbol . 'page=' . $p2 . '&perPage=' . $paginator->resultsPerPage;
		
		echo '<ul class="pagination">';
		
		if ($paginator->page != 1 and $paginator->totalPages > 10) {
			echo '<li><a href="' . $first . '"> |< </a></li>';
			echo '<li><a href="' . $prev . '"> < </a></li>';
		}
		
		for($i = $paginator->minInPageSet; $i <= $paginator->maxInPageSet; $i ++) {
			
			$url = $base . $_connector_symbol . 'page=' . $i . '&perPage=' . $paginator->resultsPerPage;
			
			if ($i == $paginator->page) {
				echo '<li><a class="active" href="#">' . $i . '</a></li>';
			} else {
				echo '<li><a href="' . $url . '"> ' . $i . ' </a></li>';
			}
		}
		if ($paginator->page != $paginator->totalPages and $paginator->totalPages > 10) {
			echo '<li><a href="' . $next . '"> > </a></li>';
			echo '<li><a href="' . $last . '"> >| </a></li>';
		}
		echo '</ul>';
	}
	
	?>
	
	
	<!-- Modal -->
	<div id="myModal" class="modal hide" role="dialog">
	  <div class="modal-dialog">
	  	 <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h5 class="modal-title">Mascot International (Laos)</h5>
      </div>
	      <div class="modal-body">
	        <p>Do you want to Notify this delivery?</p>
	      </div>
	      
		  <div class="modal-footer">
	        <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
	        <button onclick="submitDNCartItems();" type="button" class="btn btn-primary">OK</button>
	      </div>
	   </div>
	</div>
	
	
	<!-- Modal -->
	<div id="myModal1" class="modal hide" role="dialog">
	  <div class="modal-dialog">
	      <div class="modal-body">
	        <span id="modad_body_text">Working on it........Please Wait!</span>
	      </div>
	   </div>
	</div>
	
	<div id="myModal2" class="modal hide" role="dialog">
	  <div class="modal-dialog">
	  	 <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h5 class="modal-title">Mascot International (Laos)</h5>
      </div>
	      <div class="modal-body">
	      	<span id="cart_item_to_delete"></span>
	        <p>Do you want to delete this Item?</p>
	      </div>
	      
		  <div class="modal-footer">
	        <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
	        <button onclick="deleteDNCartItem();" type="button" class="btn btn-primary">DELETE</button>
	      </div>
	   </div>
	</div>			
