<?php include (ROOT.'\module\Procurement\view\procurement\menu.php'); ?>

<script language="javascript">
			var id_array = [];
</script>

 

<?php  	if (count($pr_items) >0): ?>




<ul class="nav nav-pills">
	<li><a href="/application/pdf/po?pr_id=<?php echo $pr->id ?>"  target="_blank"><i class="icon-print">  </i> Print PO (PDF)</a> </li>
 	<li><a href="/procurement/pr/process?output=csv&pr_id=<?php echo $pr->id ?>"><i class="icon-download-alt">  </i> Download PO(CSV)</a> </li>
</ul>



<table id="pr_item_tbl" class="table table-striped table-bordered">
	<thead>
		<tr style="font-size: 10pt;">
			<td><span>#</span></td>
			<td>Status</td>
			<td><b>Item Name</b></td>
			<td><b>Unit</b></td>
			<td><b data-toggle="tooltip" title="Ordred Quantity">Ordered <br>Quantity</b></td>
			<td><b data-toggle="tooltip" title="Bought Quantity">Received<br>Quantity</b></td>
			<td><b data-toggle="tooltip" title="Notified Quantity">Notified<br>Quantity</b></td>
			<td><b data-toggle="tooltip" title="Notified Quantity">Confirmed<br>Quantity</b></td>
			<td><b data-toggle="tooltip" title="Rejected Quantity">Rejected <br>Quantity</b></td>
			<td><b data-toggle="tooltip" title="Balance">Balance</b></td>
			<td><b data-toggle="tooltip" title="Free">Free</b></td>
			<td><b>EDT</b></td>
			<td><b>Last Purchase</b></td>
			<td><b>This PO</b></td>
			</tr>
	</thead>
	<tbody>	
  <?php
	$count = 0;
	foreach ( $pr_items as $item ) :
		$count ++;
		// echo ($count % 2 == 1) ? "<tr>" : "<tr class=\"pure-table-odd\">";
		?>
		<tr id="3">
			<td contenteditable='true'><?php echo $count;?></td>
			<td>
			<div style="font-size: 8pt;">
			<?php if ($item->confirmed_balance > 0) : ?>
   				<?php if ($item->po_item_id > 0) : ?>
   					<span style="font-size: 7pt;" class="label label-info">Buying</span>
   				<?php else: ?>
   					<span style="color:red;"><b>Pending</b></span>
   				<?php endif; ?>
   				
   				  				<?php else: ?>
   				<span style="font-size: 7pt;" class="label label-success">Fulfilled</span>
   				
   				<?php endif; ?>
   			</div>
   			</td>
			<td>
				<div class="dropdown">
					<a class="dropdown-toggle" type="button" data-toggle="dropdown"
						href="#"><span style="color:black;"><b><?php echo $item->name;?></b></span>
	
	
						
    <span class="caret"></span></a>
    
    	
		<ul class="dropdown-menu">
	 	
    	<?php if ($item->confirmed_balance > 0) : ?>
   			
   		<?php if ($item->po_item_id > 0) : ?>
   			<li><a href="/procurement/gr/receive?pr_item_id=<?php echo $item->id;?>&po_item_id=<?php echo $item->po_item_id;?>"><i
								class="icon-check"> </i> Receive </a></li>	
   				<li class="divider"></li>
   			<li><a href="/procurement/po/edit-item?pr_item_id=<?php echo $item->id;?>&id=<?php echo $item->po_item_id;?>"><i
								class="icon-pencil"> </i> Edit PO Item </a></li>	
			<li class="divider"></li>
    	<?php else: ?>
    		<li><a
							href="/procurement/po/add-to-cart?pr_item_id=<?php echo $item->id?>"><i
								class="icon-check"> </i> Purchase</a></li>
   	
    						<li class="divider"></li>
    	<?php endif; ?>
   				
    	<?php endif; ?>
	
     	
      	
        
        <?php
		if ($item->article_id > 0) :
			?>
        <li><a
							href="/inventory/article/show?id=<?php echo $item->article_id;?>" target="_blank"><i
								class="icon-list"> </i> Detail</a></li>
		<?php endif; ?>
		
		 <?php if ($item->sparepart_id > 0) : ?>
     	<li><a
							href="/inventory/spareparts/show?id=<?php echo $item->sparepart_id;?>" targey="_blank"><i
								class="icon-list"> </i> Detail</a></li>
		<?php endif; ?>
	
		
		     
  <li><a href="/procurement/pr/history?sparepart_id=<?php echo $item->sparepart_id;?>&article_id=<?php echo $item->article_id;?>"><i class="icon-signal"></i> Order History</a></li>
									<li><a href="#"><i class="icon-film"></i> Picture</a></li>
					</ul>
				</div>
			
			<div style="color: gray;">
				Code: <?php echo $this->escapeHtml($item->code);?><br>
			</div>
		
		

			</td>
			<td><?php echo $item->unit;?></td>
		<td><?php echo $item->quantity;?></td>
			<td>
			<?php if ($item->total_received_quantity>0): ?>
		<a href="<?php echo $this->baseUrl ?>/procurement/gr/receive-list?po_item_id=<?php echo $item->po_item_id;?>" target="_blank"><?php echo $item->total_received_quantity;?></a>
			<?php else: 
				echo $item->total_received_quantity;
			endif; ?>
			</td>
			
			
			
			<td><?php echo $item->unconfirmed_quantity;?></td>
			<td><?php echo $item->confirmed_quantity;?></td>
			<td><?php echo $item->rejected_quantity;?></td>
			<td><?php echo $item->confirmed_balance;?></td>
			<td><?php echo $item->confirmed_free_balance;?></td>
		
		<?php if($item->confirmed_balance == 0): ?>
			<td><?php echo date_format(date_create($item->EDT),"Y-m-d");?>
			<div>
			<span style="font-size: 7pt;" class="label label-success">Fulfilled</span>
			</div>
			</td>
		<?php else: ?>		
			<td><span id="<?php echo $item->id;?>_EDT"><?php echo date_format(date_create($item->EDT),"Y-m-d");?></span>
			<div>
			<span style="color: gray; font-size: 8pt; font-style: italic; vertical-align: center " id="<?php echo $item->id;?>_timer"></span>
			</div></td>
		<?php endif; ?>	

			<td>
			<?php if($item->article_id>0): ?>			
<a
				href="<?php echo $this->baseUrl ?>/procurement/vendor/show?id=<?php echo $item->article_vendor_id;?>"
				target="_blank"><?php echo $item->article_vendor_name;?></a>
			<?php endif;?>
			<?php if($item->sparepart_id>0): ?>			
<a
				href="<?php echo $this->baseUrl ?>/procurement/vendor/show?id=<?php echo $item->sp_vendor_id;?>"
				target="_blank"><?php echo $item->sp_vendor_name;?></a>
			<?php endif;?>
			
			<br> <span style="font-size: 9pt; font-style: italic;">
			<?php
		if ($item->article_id > 0) :
			if ($item->article_price > 0) :
				echo 'Unit price:' . $item->article_price . ' ' . $item->article_currency;
				;
				endif;
		endif;
		
		if ($item->sparepart_id > 0) :
			if ($item->sp_price > 0) :
				echo 'Unit price:' . $item->sp_price . ' ' . $item->sp_currency;
			
			endif;
		
		endif;
		?>
			</span>	
			</td>
			
			<td>
					
<a href="<?php echo $this->baseUrl ?>/procurement/vendor/show?id=<?php echo $item->po_vendor_id;?>"
				target="_blank"><?php echo $item->po_vendor_name;?></a>
		
			<br> <span style="font-size: 8pt; font-style: italic;">
			<?php
				echo 'Unit price:' . $item->po_price . ' ' . $item->po_currency;
			?>
			</span>
			<br> <span style="font-size: 8pt; font-style: italic;">
			<?php echo  $item->po_payment_method;?>
			</span>	
			</td>
			
			
			<script language="javascript">
				id_array.push(<?php echo $item->id;?>);
			</script>
		</tr>

	<?php endforeach; ?>
</tbody>
</table>
<br>


 <?php
else :
	echo 'No Items found ...';


endif;
 ?>
 

<!-- Modal -->
	<div id="myModal" class="modal hide" role="dialog">
	  <div class="modal-dialog">
	  	 <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h5 class="modal-title">Mascot International (Laos)</h5>
      </div>
	      <div class="modal-body">
	        <p>Do you want to approve this Purchase Request?</p>
	      </div>
	      
		  <div class="modal-footer">
	        <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
	        <button onclick="approvePR('<?php echo $pr->id?>');" type="button" class="btn btn-primary">OK</button>
	      </div>
	   </div>
	</div>	
	
	<!-- Modal -->
	<div id="myModal1" class="modal hide" role="dialog">
	  <div class="modal-dialog">
	      <div class="modal-body">
	        <p>Sending data........Please Wait!</p>
	      </div>
	   </div>
	</div>
