
<ul class="nav nav-pills">
	<li><a href="<?php echo $this->baseUrl ?>/procure/pr-row/list">PR Row
			List</a></li>
</ul>

<form class="form-inline"
	action="<?php echo $this->baseUrl ?>/procure/pr-search/do" method="get"
	enctype="multipart/form-data">
	<div class="form-group">
		<input class="form-control" size="28" type="text" name="q" class="">
	</div>
	<div class="form-group">
		<button type="submit" class="btn btn-default">
			<small><i class="glyphicon glyphicon-search"> </i></small> Search
		</button>
	</div>

</form>


<?php
echo '<hr>';
echo '<span>';
echo $message;
echo '</span>';

if (! $hits == null) :
	
	?>
<table style="font-size: 10pt;" class="table table-hover table-bordered">
	<thead>
		<tr>
			<td><b>#</b></td>
			<td><b>PR</b></td>
			<td><b>Item</b></td>
			<td><b>Code</b></td>
			<td><b>quantity</b></td>
			<td><b>PR<br>Unit
			</b></td>
			<td><b>Conversion<br>Factor
			</b></td>
			<td><b>Action</b></td>
		</tr>
	</thead>
	<tbody>

	 <?php
	
	$count = 0;
	foreach ( $hits as $hit ) :
		$count ++;
		// echo ($count % 2 == 1) ? "<tr>" : "<tr class=\"pure-table-odd\">";
		
		?>
	 <tr>

			<td> <?php echo $count;?></td>
			<td><span id=""><?php echo $this->escapeHtml($hit->pr_number);?></span></td>
			<td><span id=""><?php echo $this->escapeHtml($hit->item_name);?></span></td>
			<td><span id=""><?php echo $this->escapeHtml($hit->manufacturer_code);?></span></td>
			<td><span id=""><?php echo $this->escapeHtml($hit->row_quantity);?></span></td>
			<td><span id=""><?php echo $this->escapeHtml($hit->row_unit);?></span></td>
			<td><span id=""><?php echo $this->escapeHtml($hit->row_conversion_factor);?></span></td>
		<!--  <td><span id=""><?php echo round($hit->score* 100,0). '%';?></span></td>-->
			<td><a
<a href="<?php echo $this->baseUrl ?>/procure/pr-row/show?token=<?php echo $hit->token;?>&entity_id=<?php echo $hit->pr_row_id;?>&checksum=<?php echo $hit->checksum;?>">Show</a>
<a href="<?php echo $this->baseUrl ?>/procure/pr-row/edit?token=<?php echo $hit->token;?>&entity_id=<?php echo $hit->pr_row_id;?>&checksum=<?php echo $hit->checksum;?>">Edit</a>
<a href="<?php echo $this->baseUrl ?>/inventory/item-transaction/gr?token=<?php echo $hit->token;?>&pr_row_id=<?php echo $hit->pr_row_id;?>&checksum=<?php echo $hit->checksum;?>">Receive</a>

			</td>
		</tr>
<?php endforeach; ?>
</tbody>
</table>


<?php endif; ?>
