
	
	<ul id="menu" >
	 <li> <a href="<?php echo $this->baseUrl ?>/inventory/asset/category">Asset Management</a> </li>
	 <li> <a href="<?php echo $this->baseUrl ?>/inventory/spareparts/category">Spare-Part Management</a> </li>
	 <li> <a href="<?php echo $this->baseUrl ?>/inventory/article/list">Items Management</a> </li>
	 <li> <a href="<?php echo $this->baseUrl ?>/procurement/pr/list">Procurement Management</a> </li>
	</ul>
	
	 

    