	<?php 
{
echo '<div class="alert alert-warning">';
	
	 echo '<ul>';
	 echo '<li>Beta Version: Access Control List (ACL) has not been implemented yet.... Please edit only in area you have authority</li>';
 
	 echo '</ul>';
	 echo '</div>';
} 
?>
	
	<ul id="menu" >
	 <li> <a href="<?php echo $this->baseUrl ?>/inventory/asset/category">Asset Management</a> </li>
	 <li> <a href="<?php echo $this->baseUrl ?>/inventory/spareparts/category">Spare-Part Management</a> </li>
	 <li> <a href="<?php echo $this->baseUrl ?>/inventory/article/list">Items Management</a> </li>
	 <li> <a href="<?php echo $this->baseUrl ?>/procurement/">Procurement Management</a> </li>

	</ul>
	
    