
<div class="row">
    <div class="span5" id="html"  style="background-color:lavender;">

	<ul>
		<?php echo $jsTree?>
	</ul>

	</div>
    <div id="content" class="span8" style="background-color:lavenderblush;">
 	</div>
  </div>








<script type="text/javascript">	
// html demo
	$('#html').jstree({
		"core" : {
		       // so that create works
		       "check_callback" : true
		     },
		    "plugins" : [ "contextmenu" ],

		    "contextmenu":{         
		        "items": function($node) {
		            var tree = $("#html").jstree(true);
		            return {
		                "Create": {
		                    "separator_before": false,
		                    "separator_after": false,
		                    "label": "Create",
		                    "action": function (obj) { 
		                    	var ref = $.jstree.reference(obj.reference);
                                sel = ref.get_selected();
        	                    $node = tree.create_node($node);
			                    tree.edit($node);
		                    }
		                },
		                "Rename": {
		                    "separator_before": false,
		                    "separator_after": false,
		                    "label": "Rename",
		                    "action": function (obj) { 
		                        tree.edit($node);
		                    }
		                },                         
		                "Remove": {
		                    "separator_before": false,
		                    "separator_after": false,
		                    "label": "Remove",
		                    "action": function (obj) { 
		                        tree.delete_node($node);
		                    }
		                },
		                "Add Member": {
		                    "separator_before": false,
		                    "separator_after": false,
		                    "label": "Add Member",
		                    "action": function (obj) { 
		                   }
		                }
		            };
		        }
		    }
		    
    });

	// When the jsTree is ready, add two more records.
	$('#html').on('create_node.jstree', function (e, data) {
		//alert(data.node.parent +  data.node.id);
	});
	
	$('#html').on('rename_node.jstree', function (e, data) {
		//alert(data.node.parent +  data.node.id);
		createArticleCat(data.node.parent,data.node.id,data.node.text);
    });

	$('#html').on('delete_node.jstree', function (e, data) {
		//alert(data.node.id);
		deleteArticleCat(data.node.id);
   });

	$("#html").on("click", ".jstree-anchor", function(e) {
		   var id = $("#html").jstree(true).get_node($(this)).id;
		   var cat_name = $("#html").jstree(true).get_node($(this)).text;
		   //alert(cat_name);
		   //$("#content").text(cat_name);
		   loadArticles(id,cat_name);
	});
	
</script>

<!-- Modal -->
<div id="myModal1" class="modal hide" role="dialog">
	<div class="modal-dialog">
		<div class="modal-body">
			<p>Working on it........Please Wait!</p>
		</div>
	</div>
</div>

<!-- Modal -->
<div id="myModal" class="modal hide" role="dialog">
	<div class="modal-dialog">
		<div class="modal-header">
			<button type="button" class="close" data-dismiss="modal">&times;</button>
			<h5 class="modal-title">Message:</h5>
		</div>
		<div class="modal-body">
			<div>
				<span id="_status"></span>
			</div>
		</div>
		<div class="modal-footer">
			<button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
		</div>
	</div>
</div>
