
<ul class="nav nav-pills">
	<li><a href="<?php echo $this->baseUrl ?>/inventory/article/add">Add
			New Item</a></li>
	<!-- <li><a href="<?php echo $this->baseUrl ?>/inventory/article/category">Item category</a></li> -->
</ul>



<form class="form-search"
	action="<?php echo $this->baseUrl ?>/inventory/search/article"
	method="get" enctype="multipart/form-data">
	<input type="text" name="query" class="">
	<button type="submit" class="btn">
		<i class="icon-search"></i>Search
	</button>
</form>



<?php

if ($total_articles <= 0) {

    echo 'No items found!';
} else {

    if (! is_null($paginator)) {
        echo 'Result ' . $paginator->getMinInPage() . ' to ' . $paginator->getMaxInPage() . ' | ' . $total_articles . ' items found!';
    } else {
        echo $total_articles . ' items found!';
    }

    ?>

<table class="pure-table pure-table-bordered">
	<thead>
		<tr>
			<td><b>Name</b></td>
			<!-- td><b>Name-LA</b></td> -->
			<td><b data-toggle="tooltip" title="Balance">Bal.</b></td>
			<td><b>Code</b></td>
			<td><b>Unit</b></td>
			<td><b>Remark</b></td>
			<td><b>Action</b></td>
		</tr>
	</thead>

	<tbody>
 
	 <?php

    $count = 0;
    foreach ($articles as $a) :
        $count ++;
        echo ($count % 2 == 1) ? "<tr>" : "<tr class=\"pure-table-odd\">";
        // $instock = $a['totalINFLOW']-$a['totalOUTFLOW'];

        ?>
	 
	 
		<td><span id="<?php echo $this->escapeHtml($a->id);?>_name"><?php echo $this->escapeHtml($a->name);?></span>
		</td>

		<td><a
			href="<?php echo $this->baseUrl ?>/inventory/article/movements?article_id=<?php echo $this->escapeHtml($a->id);?>"><?php echo $this->escapeHtml($a->article_balance);?></a>
		</td>


		<!-- <td><?php echo$this->escapeHtml($a->name_local);?> -->
		<td><span id="<?php echo $this->escapeHtml($a->id);?>_code"><?php echo $this->escapeHtml($a->code);?></span></td>
		<td><span id="<?php echo $this->escapeHtml($a->id);?>_unit"><?php echo $this->escapeHtml($a->unit);?></span></td>
		<td><?php echo $this->escapeHtml($a->remarks);?> </td>

		<td><a href="#" onclick="openPRCart('<?php echo $a->id?>');"><i
				class="icon-shopping-cart"></i>Order</a> <a
			href="<?php echo $this->baseUrl ?>/inventory/article/receive?article_id=<?php echo $this->escapeHtml($a->id);?>">Receive</a>
			<a
			href="<?php echo $this->baseUrl ?>/inventory/article/issue?article_id=<?php echo $this->escapeHtml($a->id);?>">Issue</a>

			<a
			href="<?php echo $this->baseUrl ?>/inventory/article/edit?id=<?php echo $this->escapeHtml($a->id);?>">Edit</a>
			<a
			href="<?php echo $this->baseUrl ?>/inventory/article/show?id=<?php echo $this->escapeHtml($a->id);?>">Detail</a>

		</td>
		</tr>
<?php endforeach; ?>

 </tbody>
</table>


<br>

<?php

    // ===============================
    if (! is_null($paginator)) :

        // change it only
        $base = $this->baseUrl . '/inventory/article/list';
        $_connector_symbol = '?';

        $last = $base . $_connector_symbol . 'page=' . $paginator->getTotalPages() . '&perPage=' . $paginator->getResultsPerPage();;
        $first = $base . $_connector_symbol . 'page=1&perPage=' . $paginator->getResultsPerPage();;

        $p1 = ($paginator->getPage()) - 1;
        $p2 = ($paginator->getPage()) + 1;

        $prev = $base . $_connector_symbol . 'page=' . $p1 . '&perPage=' . $paginator->getResultsPerPage();;
        $next = $base . $_connector_symbol . 'page=' . $p2 . '&perPage=' . $paginator->getResultsPerPage();;

        echo '<ul class="pagination">';

        if ($paginator->getPage() != 1 and $paginator->getTotalPages() > 10) {
            echo '<li><a href="' . $first . '"> |< </a></li>';
            echo '<li><a href="' . $prev . '"> < </a></li>';
        }

        for ($i = $paginator->getMinInPageSet(); $i <= $paginator->getMaxInPageSet(); $i ++) {

            $url = $base . $_connector_symbol . 'page=' . $i . '&perPage=' . $paginator->getResultsPerPage();;

            if ($i == $paginator->getPage()) {
                echo '<li><a class="active" href="#">' . $i . '</a></li>';
            } else {
                echo '<li><a href="' . $url . '"> ' . $i . ' </a></li>';
            }
        }
        if ($paginator->getPage() != $paginator->getTotalPages() and $paginator->getTotalPages() > 10) {
            echo '<li><a href="' . $next . '"> > </a></li>';
            echo '<li><a href="' . $last . '"> >| </a></li>';
        }
        echo '</ul>';
endif;

}
// ===============================
?>


<!-- Modal -->
<div id="myModal" class="modal hide" role="dialog">
	<div class="modal-dialog">
		<div class="modal-header">
			<button type="button" class="close" data-dismiss="modal">&times;</button>
			<h5 class="modal-title">Mascot International (Laos)</h5>
		</div>
		<div class="modal-body">
			<span id="_status"></span>

			<form class="form-horizontal"
				action="<?php echo $this->baseUrl ?>/procurement/pr/select-item-2"
				method="post" enctype="multipart/form-data" id="NewSP">
				<input type="hidden" name="redirectUrl"
					value="<?php echo $redirectUrl ?>" /> <input type="hidden"
					name="article_id" id="item_id" value="" />

				<div class="control-group">
					<label class="control-label" for="inputNameLocal">Priority:</label>
					<div class="controls">
						<select name="priority" id="item_priority">
							<option value="Low">Low</option>
							<option value="Medium" selected>Medium</option>
							<option value="High">High</option>
							<option value="Urgent">Urgent</option>
						</select>
					</div>
				</div>

				<div class="control-group">
					<label class="control-label" for="inputTag">Name:</label>
					<div class="controls">
						<input type="text" id="item_name" placeholder="" name="name"
							value="article">
					</div>
				</div>

				<div class="control-group">
					<label class="control-label" for="inputTag">Code:</label>
					<div class="controls">
						<input type="text" id="item_code" placeholder="" name="code"
							value="">
					</div>
				</div>

				<div class="control-group">
					<label class="control-label" for="inputTag">Unit:</label>
					<div class="controls">
						<input type="text" id="item_unit" placeholder="" name="unit"
							value="">
					</div>
				</div>


				<div class="control-group">
					<label class="control-label" for="inputTag">Quantity:</label>
					<div class="controls">
						<input type="text" id="item_quantity" placeholder=""
							name="quantity" value="">
					</div>
				</div>

				<div class="control-group">
					<label class="control-label" for="inputNameLocal">Requested
						Delivery Date:</label>
					<div class="controls">
						<input type="text" id="end_date" placeholder="click to select"
							name="EDT" value="">
					</div>
				</div>

				<div class="control-group">
					<label class="control-label" for="inputDescription">Reason /Note:</label>
					<div class="controls">
						<textarea id="item_remarks" placeholder="" rows="2" cols="5"
							name="remarks"></textarea>
					</div>
				</div>
			</form>
		</div>

		<div class="modal-footer">
			<button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
			<button onclick="addItemToCart('ARTICLE');" type="button"
				class="btn btn-primary">Add To Cart</button>
		</div>
	</div>
</div>

<!-- Modal -->
<div id="myModal1" class="modal hide" role="dialog">
	<div class="modal-dialog">
		<div class="modal-body">
			<p>Working on it........Please Wait!</p>
		</div>
	</div>
</div>
