<ul class="nav nav-pills">
	<li><a href="<?php echo $this->baseUrl ?>/inventory/article/add">Add
			New Item</a></li>
	<li><a
		href="<?php echo $this->baseUrl ?>/inventory/article/my-dept-articles">My
			Department Items</a></li>

	<li class="dropdown"><a class="dropdown-toggle" data-toggle="dropdown"
		href="#">Show Items <span class="caret"></span></a>
		<ul class="dropdown-menu">
			<li><a href="<?php echo $this->baseUrl ?>/inventory/article/list">All
					Items</a></li>
			<li class="divider"></li>

			<li><a
				href="<?php echo $this->baseUrl ?>/inventory/article/list-with-last-do">All
					Items Details</a></li>
		</ul></li>

</ul>
