
<ul class="nav nav-pills">
 <li><a href="<?php echo $this->baseUrl ?>/inventory/article/add"><i class="icon-plus">  </i> Add New Item</a></li>
 <li><a href="<?php echo $this->baseUrl ?>/inventory/article/list?output=csv"><i class="icon-download-alt">  </i> Download (csv)</a> 
 <li><a href="<?php echo $this->baseUrl ?>/inventory/article/list?output=order_template"><i class="icon-download-alt">  </i> Order Template(csv)</a> 

</li>
</ul>

 	 

  <form class="form-search" action="<?php echo $this->baseUrl ?>/inventory/search/article"	method="get" enctype="multipart/form-data">
      <input type="text" name = "query" class="">
      <button type="submit" class="btn"><i class="icon-search"></i>Search</button>
   </form>
 
<div class="panel-group">
	<div class="panel panel-default">
		<div class="panel-heading">
			<h5 class="panel-title">
				<a data-toggle="collapse" href="#collapse1"><i class="icon-filter">
				</i> FILTER</a>
			</h5>
		</div>

		<div id="collapse1"
			class="panel-collapse collapse <?php echo count($articles)>0?"":"in"?>">
			<div class="panel-body">
				<div
					style="padding: 3px; background: url(/images/bg1.png); background-repeat: repeat-x; background-color: #FFFFFF;">
					<form class="form-horizontal"
						action="<?php echo $this->baseUrl ?>/inventory/article/list"
						method="get" enctype="multipart/form-data" id="ReportForm">
						
						<div class="control-group">
							<label class="control-label" for="inputNameLocal">Item Type: </label>
							<div class="controls">
								<select name="item_type">
									<option value="">All</option>
									<option
										<?php echo $item_type=='Stocked Product'? "selected='selected'":"";?>
										value="Stocked Product">Stocked Products</option>
									<option
										<?php echo $item_type=='Unstocked Product'? "selected='selected'":"";?>
										value="Unstocked Product">Unstocked Products</option>
									<option
										<?php echo $item_type=='Service'? "selected='selected'":"";?>
										value="Service">Service</option>
									</select>
							</div>
						</div>
						

						<div class="control-group">
							<label class="control-label" for="inputNameLocal">Item Status: </label>
							<div class="controls">
								<select name="item_status">
									<option value="">All</option>
									<option
										<?php echo $item_status=='Activated'? "selected='selected'":"";?>
										value="Activated">Activated</option>
									<option
										<?php echo $item_status=='Deactivated'? "selected='selected'":"";?>
										value="Deactivated">Deactivated</option>
									</select>
							</div>
						</div>

						
						<div class="control-group">
							<label class="control-label" for="inputNameLocal">Sort by: </label>
							<div class="controls">
								<select name="sort_by">
									<option value="">None</option>
									<option
										<?php echo $sort_by=='item_name'? "selected='selected'":"";?>
										value="item_name">Item Name</option>
						
									<option <?php echo $sort_by=='created_date'? "selected='selected'":"";?>
										value="created_date">Created Date</option>
								</select>

							</div>
						</div>

						<div class="control-group">
							<label class="control-label" for="inputNameLocal">Result per
								page: </label>
							<div class="controls">
								<select name="perPage">
									<option value="">None</option>
									<option <?php echo $per_pape=='10'? "selected='selected'":"";?>
										value="10">10</option>

									<option <?php echo $per_pape=='15'? "selected='selected'":"";?>
										value="15">15</option>

									<option <?php echo $per_pape=='20'? "selected='selected'":"";?>
										value="20">20</option>

									<option <?php echo $per_pape=='50'? "selected='selected'":"";?>
										value="50">50</option>
									<option
										<?php echo $per_pape=='100'? "selected='selected'":"";?>
										value="100">100</option>
								</select>

							</div>
						</div>

						<div class="control-group">
							<div class="controls">
								<button type="submit" class="btn">
									<i class="icon-search"> </i> show
								</button>
							</div>
						</div>
					</form>
				<hr>
				</div>

			</div>
		</div>
	</div>
</div>

<?php

if ($total_articles <= 0) {
	
	echo 'No items found!';
} else {

	if (! is_null ( $paginator )) {
		echo 'Result '. $paginator->minInPage. ' to '.$paginator->maxInPage. ' | ' .$total_articles . ' items found!';
	}else{	
		echo $total_articles . ' items found!';
	}
	
?>

<table class="table table-striped table-bordered">
<thead>
	<tr>
		<td><b>#</b></td>
		<td><b>Picture</b></td>
		<td><b>Name</b></td>
		<!-- td><b>Name-LA</b></td> -->
		<td><b>Item Type</b></td>
		<td><b>Created Date</b></td>
		
		<td ><b data-toggle="tooltip" title = "Balance">Current <br> Balance</b></td>	
		<td><b>Remark</b></td>
		<td><b>Action</b></td>
	</tr>
</thead>

 <tbody>
 
	 <?php 
	 
	 $count = 0;
	 foreach ($articles as $a) : 
	 	 $count++;
 ?>
	 
	 <tr>
	 <td><?php echo ($paginator===null)? $count:$paginator->minInPage -1+ $count;?></td>
	 	<td>
			<?php 
			if($a->article_pic_id!==null):
			?>
			<a href="<?php echo $this->baseUrl ?>/inventory/article/show?id=<?php echo $this->escapeHtml($a['id']);?>">
			<img class= "img-rounded" width="80" height="80" src="/inventory/image/articlethumbnail200?id=<?php echo $a->article_pic_id;?>"/>
		</a>			
			<?php 
			else:
			?>
			<img class= "img-rounded" width="70" height="70" src="/images/no-pic.jpg"/>
				
			<?php 
			endif;
			?>
			
			</td>
	 
	 
		<td>
		
		<div class="dropdown">
					<a style="" class="dropdown-toggle" type="button" data-toggle="dropdown"
						href="#"><span style="color:black;" id="<?php echo $this->escapeHtml($a['id']);?>_name"><b><?php echo $this->escapeHtml($a['name']);?></b></span>
						<span class="caret"></span></a>
					<ul class="dropdown-menu">
						<li><a href="<?php echo $this->baseUrl ?>/inventory/article/edit?id=<?php echo $this->escapeHtml($a->id);?>"><i class="icon-pencil"></i> Edit</a>

						</li>
						<li>	<a href="<?php echo $this->baseUrl ?>/inventory/article/show?id=<?php echo $this->escapeHtml($a->id);?>"><i class="icon-list"></i> Detail</a>
	
						</li>
 						<li class="divider"></li>
 						<li><a
							href="<?php echo $this->baseUrl ?>/inventory/article/upload-picture1?id=<?php echo $this->escapeHtml($a['id']);?>">Upload Picture</a>
						</li>
 	
 							<li class="divider"></li>
 						<li><a
				href="<?php echo $this->baseUrl ?>/inventory/article/movements?article_id=<?php echo $this->escapeHtml($a['id']);?>">Stock movement</a>
						</li>
						</ul>
				</div>
		<div style="color: gray;">
				Code: <span id="<?php echo $this->escapeHtml($a->id);?>_code"><?php echo $this->escapeHtml($a->code);?></span><br>
				Unit: <span id="<?php echo $this->escapeHtml($a->id);?>_unit"><?php echo $this->escapeHtml($a->unit);?></span>
				</div>
		
		</td>
		<td><?php echo $this->escapeHtml($a->type);?> </td>
		<td><?php echo $this->escapeHtml($a->created_on);?> </td>
		
		<td>
		
		<a href="<?php echo $this->baseUrl ?>/inventory/article/movements?article_id=<?php echo $this->escapeHtml($a->id);?>"><?php echo $this->escapeHtml($a->article_balance);?></a>
		</td>
		
		
		<!-- <td><?php echo$this->escapeHtml($a->name_local);?> -->
		<td><?php echo $this->escapeHtml($a->remarks);?> </td>
		 
		<td>
		<a href="#" onclick="openPRCart('<?php echo $a->id?>');"><i class="icon-shopping-cart"></i>Order</a>
		<a href="<?php echo $this->baseUrl ?>/inventory/article/receive?article_id=<?php echo $this->escapeHtml($a->id);?>">Receive</a>
		<a href="<?php echo $this->baseUrl ?>/inventory/article/issue?article_id=<?php echo $this->escapeHtml($a->id);?>">Issue</a>
	
		
		</td>
	</tr>
<?php endforeach; ?>

 </tbody>
</table>


<br>

<?php

//===============================
if (! is_null ( $paginator )):
		
	
	//change it only
	$base=$this->baseUrl . '/inventory/article/list';
	$_connector_symbol = '?';

	$last 	= $base . $_connector_symbol.'page=' . $paginator->totalPages . '&perPage=' . $paginator->resultsPerPage;
	$first 	= $base . $_connector_symbol.'page=1&perPage=' . $paginator->resultsPerPage;

	$p1 = ($paginator->page)-1;
	$p2 = ($paginator->page)+1;

	$prev = $base . $_connector_symbol.'page=' . $p1 . '&perPage=' . $paginator->resultsPerPage;
	$next = $base . $_connector_symbol.'page=' . $p2 . '&perPage=' . $paginator->resultsPerPage;


	echo '<ul class="pagination">';

	if($paginator->page != 1 AND $paginator->totalPages > 10){
		echo '<li><a href="'.  $first.'"> |< </a></li>';
		echo '<li><a href="'.  $prev .'"> < </a></li>';
	}

	for($i = $paginator->minInPageSet; $i <= $paginator->maxInPageSet; $i ++) {
			
		$url = $base. $_connector_symbol.'page=' . $i . '&perPage=' . $paginator->resultsPerPage;

			
		if ($i == $paginator->page) {
			echo   '<li><a class="active" href="#">'.$i.'</a></li>';
		} else {
			echo '<li><a href="'. $url. '"> '. $i. ' </a></li>';
		}
	}
	if($paginator->page != $paginator->totalPages AND $paginator->totalPages > 10){
		echo '<li><a href="'.  $next.'"> > </a></li>';
		echo '<li><a href="'.  $last .'"> >| </a></li>';
	}
	echo '</ul>';
endif;

}
//===============================
?>


<?php include (ROOT.'\module\Inventory\view\inventory\article_order_form.php'); ?>