<h3>Stock Movement</h3>

<h4> <?php echo $this->escapeHtml($article->name);?> </h4>

<hr>
<table class="pure-table pure-table-bordered">
<thead>
	<tr>
		<td><b>id</b></td>
		<td><b>Movement</b></td>
		<td><b>Flow</b></td>
		<td><b>Quantity</b></td>
		<td><b>Comment</b></td>
		
	</tr>
</thead>
<tbody>

<?php 
	 
	 $count = 0;
	foreach ($movements as $a) :
	 	 $count++;
	 echo  ($count % 2 == 1) ? "<tr>" : "<tr class=\"pure-table-odd\">";
	 	 
	 ?>

		<td><?php echo $a->id;?></td>
		<td><?php echo date_format(date_create($a->movement_date),"Y-m-d");?></td>
		<td><?php echo $a->flow;?></td>
		<td><?php echo $a->quantity;?></td>
		<td><?php echo $a->comment;?></td>
		
	</tr>
<?php endforeach; ?>
</tbody>
</table>

