
<h5><?php  echo $this->escapeHtml($article->name);?> - Pictures</h5>

<a href="<?php echo $this->baseUrl ?>/inventory/article/upload-picture?id=<?php echo $article->id?>">  <i class="icon-upload">  </i> UPLOAD</a>


<table class="pure-table pure-table-bordered">
<thead>
	<tr>
		<td>File name</td>
		<td>File Type</td>
		<td>Checksum</td>
		<td>Size</td>
		<td>Visibility</td>
		<td>Uploaded on</td>		
		<td>Thumbnail</td>		
		<td>Action</td>
	</tr>
</thead>
<tbody>

 <?php 
	 
	 $count = 0;
	foreach ($pictures as $pic) : 
	 	 $count++;
	 echo  ($count % 2 == 1) ? "<tr>" : "<tr class=\"pure-table-odd\">";
	 	 
	 ?>
	 	<td><?php  echo $this->escapeHtml($pic->filename);?></td>
 		<td><?php  echo $this->escapeHtml($pic->filetype);?></td>
 		<td><?php  echo $this->escapeHtml($pic->checksum);?></td>
 		
 		<td><?php  echo $this->escapeHtml($pic->size);?></td>
  		<td><?php  echo $this->escapeHtml($pic->visibility);?></td>
  		<td><?php  echo $this->escapeHtml($pic->uploaded_on);?></td>
  		<td>
  		<img class= "img-rounded" width="80" hight="80" src="/inventory/image/article-thumbnail150?id=<?php  echo $this->escapeHtml($pic->id);?>"/>
  		</td>
  		
	
		<td><a
			href="<?php echo $this->baseUrl ?>/inventory/image/delete-article-picture?id=<?php  echo $this->escapeHtml($pic->id);?>">
				delete</td>
	</tr>
	 
<?php endforeach; ?>
</tbody>
</table>