
<form class="form-search"
	action="<?php echo $this->baseUrl ?>/inventory/article/list"
	method="get" enctype="multipart/form-data">
	<button type="submit" class="btn">
		<i class="icon-arrow-left"> </i> Back
	</button>
</form>

<h4>
	Receiving: <span class="label label-success"></span> <?php echo $article->name; ?> </h4>

<hr>

<?php

if (count($errors) > 0) {
    echo '<div class="alert alert-error">';

    echo '<ul>';
    foreach ($errors as $error) :
        echo '<li>' . $error . '</li>';
    endforeach
    ;
    echo '</ul>';
    echo '</div>';
}
?>

<form class="form-horizontal"
	action="<?php echo $this->baseUrl ?>/inventory/article/receive"
	method="post" enctype="multipart/form-data" id="NewSP">
	<input type="hidden" name="article_id"
		value="<?php echo (int) $article->id; ?>" /> <input type="hidden"
		name="redirectUrl" value="<?php echo $redirectUrl ?>" />

	<div class="control-group">
		<label class="control-label" for="inputName">Receipt date:</label>
		<div class="controls">
			<input type="text" name="movement_date" value=""
				placeholder=" please select" id="movement_date" />
		</div>
	</div>

	<div class="control-group">
		<label class="control-label" for="inputNameLocal">Quantity:</label>
		<div class="controls">
			<input type="text" name="quantity"
				value="<?php echo $movement!==null ? ($movement->quantity) :""?>" />
			<span class="label label-info">
			(In stock: <?php echo (int) $article->article_balance . ' pcs.'; ?>)</span>
		</div>
	</div>

	<div class="control-group">
		<label class="control-label" for="inputNameLocal">Requester:</label>
		<div class="controls">
			<input type="text" name="requester"
				value="<?php echo $movement!==null ? ($movement->requester) :""?>" />
		</div>
	</div>

	<div class="control-group">
		<label class="control-label" for="inputDescription">Reason:</label>
		<div class="controls">
			<textarea class="form-control" id="inputDescription" placeholder=""
				rows="3" name="reason"><?php echo $movement!==null ? ($movement->reason) :""?></textarea>
		</div>
	</div>


	<div class="control-group">
		<label class="control-label" for="inputDescription">Comment:</label>
		<div class="controls">
			<textarea class="form-control" id="inputDescription" placeholder=""
				rows="2" name="comment"><?php echo $movement!==null ? ($movement->comment) :""?></textarea>
		</div>
	</div>

	<div class="control-group">
		<div class="controls">
			<button type="submit" class="btn">
				<i class="icon-plus"> </i> Receive
			</button>
		</div>
	</div>
</form>

<div id="dialog" style="display: none;">No asset found...</div>

<hr>
<h5>
	<a
		href="/inventory/spareparts/pictures?sparepart_id=<?php echo (int) $article->id; ?>">Items
		pictures</a>
</h5>

<div class="container">
	<div id="lightgallery">

 
 <?php foreach ($pictures as $pic) : ?>
  	
    <a
			href="/inventory/image/article?id=<?php  echo $this->escapeHtml($pic->id);?>">
			<img class="img-rounded" width="80" height="80"
			src="/inventory/image/article-thumbnail150?id=<?php  echo $this->escapeHtml($pic->id);?>" />
		</a>
	
<?php endforeach; ?>
</div>
</div>