 <form class="form-search" action="<?php echo $this->baseUrl ?>/inventory/article/list"	method="get" enctype="multipart/form-data">
      <button type="submit" class="btn"><i class="icon-arrow-left">  </i> Back</button>
</form>

<h4> <?php echo $this->escapeHtml($article->name);?></h4>
 <hr>
<h5>
	<a
		href="<?php echo $this->baseUrl ?>/inventory/article/movements?article_id=<?php echo $this->escapeHtml($article->id);?>">Show
		Stock Movements </a>
</h5>
<hr>
<table>

	<tr>
		<td><label for="tag">Type:</label></td>
		<td><?php echo $this->escapeHtml($article->type);?></td>
	</tr>

	<tr>
		<td><label for="name_local">Description:</label>
		
		<td><?php echo $article->description;?></td>
	</tr>
	<tr>
		<td><label for="description">Tag: </label></td>
		<td><?php echo $article->name_local;?></td>
	</tr>

	<tr>
		<td><label for="code">Supplier Code /Serial:</label></td>
		<td><?php echo $this->escapeHtml($article->status);?></td>
	</tr>


	<tr>
		<td><label for="location">Location:</label></td>
		<td><?php echo $this->escapeHtml($article->visibility);?></td>
	</tr>
	<tr>
		<td><label for="comment">Comment:</label></td>
		<td><?php echo $this->escapeHtml($article->remarks);?></td>
	</tr>

</table>

<hr>

<h5>    <a href="/inventory/article/pictures?article_id=<?php echo $this->escapeHtml($article->id);?>">Item pictures:</a></h5>


<div id="lightgallery">

 
 <?php foreach ($pictures as $pic) : ?>
  	
    <a href="/inventory/image/article?id=<?php  echo $this->escapeHtml($pic->id);?>">
    <img class= "img-rounded" width="150" height="150" src="/inventory/image/articlethumbnail200?id=<?php  echo $this->escapeHtml($pic->id);?>"/>
    </a>
	
<?php endforeach; ?>
</div>
