
<?php

/**@var \Application\Entity\NmtHrEmployee $target ; 
 @var \Application\Entity\NmtHrContract $entity ;
 */
?>

<h4><?php

if (! $target == null) :

    echo sprintf('<a href="/hr/employee/show?token=%s&entity_id=%s&checksum=%s" >%s</a>', $target->getToken(), $target->getId(), $target->getChecksum(), strtoupper($target->getEmployeeName()) . ' #' . $target->getEmployeeCode());
endif;

?></h4>

<?php
if (count($errors) > 0) {
    echo '<div class="alert alert-danger" role="alert" style="font-size: 10.5pt">';

    echo '<ul>';
    foreach ($errors as $error) :
        echo '<li>' . $error . '</li>';
    endforeach
    ;
    echo '</ul>';
    echo '</div>';
}
?>

<div id="tabs" style="font-size: 9.5pt">
	<ul>
		<li><a href="#general"><?php echo $this->translate('Contract'); ?></a></li>
		<li><a
			href="/hr/contract-log/list1?object_token=<?php echo (!$entity == null)? $entity->getToken():"";?>&object_id=<?php echo (!$entity == null)? $entity->getID():"";?>&class_name=<?php echo (!$entity == null)? get_class($entity):"";?>"><span
				class="glyphicon glyphicon-list"></span>&nbsp;Change Log</a></li>
		<li><a
			href="/hr/salary/simulate?token=<?php echo (!$entity == null)? $entity->getToken():"";?>&target_id=<?php echo (!$entity == null)? $entity->getID():"";?>"><span><?php echo $this->translate('Posting'); ?></a></li>

	</ul>

	<div id="general" style="font-size: 9pt">

		<div style="position: relative; float: right;">
			<a class="btn btn-default btn-sm"
				href="<?php echo $this->baseUrl ?>/hr/employee-contract/amend?token=<?php echo $this->escapeHtml($entity->getToken());?>&entity_id=<?php echo $this->escapeHtml($entity->getID());?>">
				<i class="fa fa-pencil-square-o" aria-hidden="true"></i> <?php echo $this->translate("Edit")?></a>

			<a tabindex="11" class="btn btn-default btn-sm"
				href="<?php echo $redirectUrl; ?>"><small><i class=""></i></small>&nbsp;<?php echo $this->translate('Cancel'); ?></a>
			<a style="color: red;" class="btn btn-default btn-sm"
				href="<?php echo $this->baseUrl ?>/hr/employee-contract/terminate?token=<?php echo $this->escapeHtml($entity->getToken());?>&entity_id=<?php echo $this->escapeHtml($entity->getID());?>"><i
				class="fa fa-times" aria-hidden="true"></i>&nbsp;<?php echo $this->translate("Terminate")?></a>

		</div>
		<hr>
		<form id="create_form" class="form-horizontal"
			action="/hr/employee-contract/add" method="post"
			enctype="multipart/form-data">
			<input type="hidden" name="redirectUrl"
				value="<?php echo $redirectUrl ?>" /> <input type="hidden"
				name="target_id"
				value="<?php echo (!$target == null)? $target->getId():"";?>" /> <input
				type="hidden" name="target_token"
				value="<?php echo (!$target == null)? $target->getToken():"";?>" />

			<fieldset>
				<legend style="font-size: 9pt; color: gray;">
					<small><span class="glyphicon glyphicon-triangle-right"></span></small>&nbsp;
					<a style="font-size: 9pt; color: gray;" href="#contract_header"
						class="" data-toggle="collapse">CONTRACT HEADER:</a>
				</legend>
				<div id="contract_header" class="collapse in">
					<!-- -- -->

					<div class="form-group margin-bottom required">
						<label class="control-label col-sm-2"><?php echo $this->translate('Contract Number'); ?>:</label>
						<div class="col-sm-3">
							<input class="form-control input-sm" type="text"
								name="contractNumber"
								value="<?php if(!$entity == null): echo $entity->getContractNumber(); endif;?>"
								placeholder="<?php echo $this->translate('please enter contract number'); ?>"
								id="" />
						</div>
						<div class="col-sm-4">
							<input
								<?php if(!$entity == null): echo ($entity->getIsActive()=="1")?"checked":""; else: echo "checked"; endif;?>
								type="checkbox" name="isActive" value="1">&nbsp;<?php echo $this->translate('Active'); ?>&nbsp;&nbsp;
		</div>
		<?php echo (!$entity == null)? '<span style="color:gray;font-size: 9pt">Revision #: '. $entity->getRevisionNo().'</span>':'';?>
		<br>
		<?php if (!$entity == null): if($entity->getLastChangeOn()!==null): echo '<span style="color:gray;font-size: 9pt">Last Revision: '. $entity->getLastChangeOn()->format('d-m-Y h:i:s').'</span>'; endif; endif;?>
		
	</div>

					<div class="form-group margin-bottom required">
						<label class="control-label col-sm-2"><?php echo $this->translate('Contract Date'); ?>:</label>
						<div class="col-sm-3">
							<input class="form-control input-sm" type="text"
								name="contractDate" id="contractDate"
								value="<?php if(!$entity == null): if ($entity->getContractDate() !== null): echo date_format($entity->getContractDate(),"Y-m-d"); endif; endif;?>"
								placeholder="<?php echo $this->translate('Select contract date!'); ?>"
								id="" />
						</div>
						<div class="col-sm-4"></div>

					</div>

					<div class="form-group margin-bottom">
						<label class="control-label col-sm-2"><?php echo $this->translate('Vadid From'); ?>:</label>
						<div class="col-sm-3">
							<input class="form-control input-sm" type="text" placeholder=""
								name="effectiveFrom" id="validFrom"
								value="<?php if(!$entity == null): if ($entity->getEffectiveFrom() !== null): echo date_format($entity->getEffectiveFrom(),"Y-m-d"); endif; endif;?>">
						</div>
						<label class="control-label col-sm-2"><?php echo $this->translate('Vadid To'); ?>:</label>
						<div class="col-sm-3">
							<input class="form-control input-sm" type="text" placeholder=""
								name="effectiveTo" id="validTo"
								value="<?php if(!$entity == null): if ($entity->getEffectiveTo() !== null): echo date_format($entity->getEffectiveTo(),"Y-m-d"); endif; endif;?>">
						</div>
					</div>


				</div>
			</fieldset>

			<fieldset>
				<legend style="font-size: 9pt; color: gray;">
					<small><span class="glyphicon glyphicon-triangle-right"></span></small>&nbsp;
					<a style="font-size: 9pt; color: gray;" href="#contract_job"
						class="" data-toggle="collapse">POSITION, WORKING TIME, etc.:</a>
				</legend>
				<div id="contract_job" class="collapse in">
					<!-- detail -->

					<div class="form-group margin-bottom required">
						<label class="control-label col-sm-2"><?php echo $this->translate('Postion'); ?>:</label>
						<div class="col-sm-3">
							<select name="position_id" class="form-control input-sm">
								<option value=""><?php echo $this->translate('Select Position'); ?></option>
		<?php
if ($position_list !== null) :
    foreach ($position_list as $pos) :
        if ($entity !== null) :
            if ($entity->getPosition() !== null) :
                if ($entity->getPosition()->getPositionName() == $pos->getPositionName()) :
                    echo '<option selected value="' . $pos->getId() . '">' . $pos->getPositionName() . '</option>';
                else :
                    echo '<option value="' . $pos->getId() . '">' . $pos->getPositionName() . '</option>';
                endif;
            else :
                echo '<option value="' . $pos->getId() . '">' . $pos->getPositionName() . '</option>';
            endif;
        else :
            echo '<option value="' . $pos->getId() . '">' . $pos->getPositionName() . '</option>';
        endif;
    endforeach
    ;
		endif;

?>
	</select>
						</div>
						<label class="control-label col-sm-2"><?php echo $this->translate('Contract Status'); ?>:</label>
						<div class="col-sm-3">
							<input class="form-control input-sm" type="text" placeholder=""
								name="status" id=""
								value="<?php echo (!$entity == null)? $entity->getContractStatus():"";?>">
						</div>

					</div>

					<div class="form-group margin-bottom required">
						<label class="control-label col-sm-2"><?php echo $this->translate('Working Time From'); ?>:</label>
						<div class="col-sm-3">
							<input class="form-control input-sm" type="text" placeholder=""
								name="workingTimeFrom" id=""
								value="<?php echo (!$entity == null)? $entity->getWorkingTimeFrom():"";?>">
						</div>
						<label class="control-label col-sm-2"><?php echo $this->translate('Working Time To'); ?>:</label>
						<div class="col-sm-3">
							<input class="form-control input-sm" type="text" placeholder=""
								name="workingTimeTo" id=""
								value="<?php echo (!$entity == null)? $entity->getWorkingTimeTo():"";?>">
						</div>
					</div>

				</div>
			</fieldset>
			<fieldset>
				<legend style="font-size: 9pt; color: gray;">
					<small><span class="glyphicon glyphicon-triangle-right"></span></small>&nbsp;
					<a style="font-size: 9pt; color: gray;" href="#contract_salary"
						class="" data-toggle="collapse">REMUNERATION:</a>
				</legend>
				<div id="contract_salary" class="collapse">
					<!-- -- -->
					<div class="form-group margin-bottom required">
						<label class="control-label col-sm-2"><?php echo $this->translate('Basic Salary'); ?>:</label>
						<div class="col-sm-3">
							<input class="form-control input-sm" type="text" placeholder=""
								name="basicSalary" id=""
								value="<?php echo (!$entity == null)? $entity->getBasicSalary():"";?>">
						</div>
						<div class="col-sm-4">
							<input
								<?php if(!$entity == null): echo ($entity->getIsActive()=="1")?"checked":""; else: echo "checked"; endif;?>
								type="checkbox" name="isActive" value="1">&nbsp;<?php echo $this->translate('Is Gross'); ?>&nbsp;&nbsp;
		</div>

					</div>

					<div class="form-group margin-bottom required">

						<label class="control-label col-sm-2"><?php echo $this->translate('Currency'); ?>:</label>
						<div class="col-sm-3">
							<select name="currency_id" class="form-control input-sm">
								<option value="">Select Currency</option>
		<?php
if ($currency_list !== null) :
    foreach ($currency_list as $curr) :
        if ($entity !== null) :
            if ($entity->getCurrency() !== null) :
                if ($entity->getCurrency()->getCurrency() == $curr->getCurrency()) :
                    echo '<option selected value="' . $curr->getId() . '">' . $curr->getCurrency() . '</option>';
                else :
                    echo '<option value="' . $curr->getId() . '">' . $curr->getCurrency() . '</option>';
                endif;
            else :
                echo '<option value="' . $curr->getId() . '">' . $curr->getCurrency() . '</option>';
            endif;
        else :
            echo '<option value="' . $curr->getId() . '">' . $curr->getCurrency() . '</option>';
			 endif;
			endforeach;
		endif;
		?>
	</select>
						</div>
			
			</fieldset>

			<div id="other_income"></div>



		</form>
	</div>
</div>




<script>
$("#create_form :input").attr("disabled", "disabled");
ajaxloadData('<?php echo $this->baseUrl ?>/hr/salary/list1?token=<?php echo $this->escapeHtml($entity->getToken());?>&target_id=<?php echo $this->escapeHtml($entity->getID());?>','#other_income');
</script>

