
<?php
if ($total_records <= 0) {

    echo 'No records found!';
} else {

    if (! is_null($paginator)) {
        echo 'Record ' . $paginator->getMinInPage() . ' to ' . $paginator->getMaxInPage() . ' | ' . $total_records . ' recor found!';
    } else {
        echo $total_records . ' records found!';
    }

    ?>

<table style="font-size: 10pt" class="table table-bordered table-hover">
	<thead>
		<tr>
			<td><b>Select</b></td>
			<td><b>Country Name</b></td>
			<td><b>Code 2</b></td>
		</tr>
	</thead>

	<tbody>

		<tr>
			<td><a href="javascript:;"
				onclick="selectId('','country_id','','country_name');"><small><i
						class="glyphicon glyphicon-triangle-right"></i></small>&nbsp;Select
			</a></td>
			<td>NONE</td>
			<td>NONE</td>
		</tr>
 
	 <?php

    $count = 0;
    foreach ($list as $a) :
        $count ++;
        ?>
	 <tr>
			<td><a href="javascript:;"
				onclick="selectId('<?php echo $this->escapeHtml($a->getId());?>','country_id','<?php echo $this->escapeHtml($a->getCountryName());?>','country_name');"><small><i
						class="glyphicon glyphicon-triangle-right"></i></small>&nbsp;Select
			</a></td>
			<td><?php echo $this->escapeHtml($a->getCountryName());?></td>
			<td><?php echo $this->escapeHtml($a->getCountryCode2());?></td>
		</tr>
<?php endforeach; ?>

 </tbody>
</table>

<?php

    // ===============================
    if (! is_null($paginator)) :

        // change it only
        $base = $this->baseUrl . '/application/country/list';
        $_connector_symbol = '?';

        $last = $base . $_connector_symbol . 'page=' . $paginator->getTotalPages() . '&perPage=' . $paginator->getResultsPerPage();;
        $first = $base . $_connector_symbol . 'page=1&perPage=' . $paginator->getResultsPerPage();;

        $p1 = ($paginator->getPage()) - 1;
        $p2 = ($paginator->getPage()) + 1;

        $prev = $base . $_connector_symbol . 'page=' . $p1 . '&perPage=' . $paginator->getResultsPerPage();;
        $next = $base . $_connector_symbol . 'page=' . $p2 . '&perPage=' . $paginator->getResultsPerPage();;

        echo '<ul class="pagination pagination-sm">';

        if ($paginator->getPage() != 1 and $paginator->getTotalPages() > 10) {
            echo '<li><a href="' . $first . '"> |< </a></li>';
            echo '<li><a href="' . $prev . '"> < </a></li>';
        }

        for ($i = $paginator->getMinInPageSet(); $i <= $paginator->getMaxInPageSet(); $i ++) {

            $url = $base . $_connector_symbol . 'page=' . $i . '&perPage=' . $paginator->getResultsPerPage();;

            if ($i == $paginator->getPage()) {
                echo '<li><a class="active" href="#">' . $i . '</a></li>';
            } else {
                echo '<li><a href="' . $url . '"> ' . $i . ' </a></li>';
            }
        }
        if ($paginator->getPage() != $paginator->getTotalPages() and $paginator->getTotalPages() > 10) {
            echo '<li><a href="' . $next . '"> > </a></li>';
            echo '<li><a href="' . $last . '"> >| </a></li>';
        }
        echo '</ul>';
endif;

}
// ===============================
?>

