;<?php
use Application\Domain\Util\Pagination\Paginator;
use Procure\Application\Helper\FormHelper;
use Procure\Application\Service\Output\Contract\HeadersSaveAsSupportedType;
use Procure\Domain\PurchaseRequest\PRSnapshot;

/**
 *
 * @author Nguyen Mau Tri - ngmautri@gmail.com
 *         ===================================
 */

/**@var PRSnapshot $rootSnapshot ;*/
/**@var Paginator $paginator ;*/
/**@var \Application\Controller\Plugin\NmtPlugin $nmtPlugin ;*/

// echo $total_records;
$table_body = "";
$count = 0;
$n = 0;

$main_tab = $this->translate("INVOICE LIST");

$createUrl = $this->baseUrl . "/procure/ap/create";
$baseUrl = "/procure/ap-report/header-status";

$filterUrl = $baseUrl;

$result_msg = sprintf('<span style="color: graytext">%s</span>', 'No record found!');
$base = sprintf('%s?is_active=%s&currentState=%s&docStatus=%s&sort_by=%s&sort=%s', $baseUrl, $is_active, $currentState, $docStatus, $sort_by, $sort);

$save_as_excel = sprintf('%s?is_active=%s&currentState=%s&docStatus=%s&sort_by=%s&sort=%s&file_type=%s', $baseUrl, $is_active, $currentState, $docStatus, $sort_by, $sort, HeadersSaveAsSupportedType::OUTPUT_IN_EXCEL);
$save_as_openoffice = sprintf('%s?is_active=%s&currentState=%s&docStatus=%s&sort_by=%s&sort=%s&file_type=%s', $baseUrl, $is_active, $currentState, $docStatus, $sort_by, $sort, HeadersSaveAsSupportedType::OUTPUT_IN_OPEN_OFFICE);

if (count($list) > 0) {

    $result_msg = sprintf("%s records found!", $total_records);

    if ($paginator !== null) {
        $tmp = sprintf('Recored %s to %s of %s found!', $paginator->getMinInPage(), $paginator->getMaxInPage(), $total_records);
        $result_msg = sprintf('<span style="color:graytext;">%s</span>', $tmp);
    }

    foreach ($list as $rootSnapshot) {

        $n ++;

        if ($paginator !== null) {
            $count = $paginator->getMinInPage() - 1 + $n;
        } else {
            $count = $n;
        }

        $url = sprintf($this->baseUrl . "/procure/ap/view?entity_id=%s&entity_token=%s", $rootSnapshot->getId(), $rootSnapshot->getToken());
        $title = "Show PO";
        $icon = null;
        $viewBtn = FormHelper::createButton($this->translate("View"), $title, $url, $icon);

        $url = sprintf($this->baseUrl . "/procure/ap/update?entity_id=%s&entity_token=%s", $rootSnapshot->getId(), $rootSnapshot->getToken());
        $title = "Edit PO";
        $icon = 'glyphicon glyphicon-pencil';
        $editBtn = FormHelper::createButton($this->translate("Edit"), $title, $url, $icon);

        $table_body = $table_body . "<tr>";
        $table_body = $table_body . sprintf("<td>%s</td>", $count);
        $table_body = $table_body . sprintf("<td>%s</td>", $rootSnapshot->getDocStatus());
        $table_body = $table_body . sprintf("<td>%s</td>", $rootSnapshot->getSysNumber());
        $table_body = $table_body . sprintf("<td>%s</td>", $rootSnapshot->getVendorName());
        $table_body = $table_body . sprintf("<td>%s</td>", $rootSnapshot->getDocNumber());
        $table_body = $table_body . sprintf("<td>%s</td>", $rootSnapshot->getDocDate());
        $table_body = $table_body . sprintf("<td>%s</td>", $rootSnapshot->getTotalRows());
        $table_body = $table_body . sprintf("<td>%s</td>", $rootSnapshot->getGrossAmount());
        $table_body = $table_body . sprintf("<td>%s</td>", $rootSnapshot->getCurrencyIso3());
        $table_body = $table_body . sprintf("<td>%s</td>", $viewBtn . ' ' . $editBtn);

        $table_body = $table_body . "</tr>";
    }
}
$filter_msg = sprintf("Status=%s | Active=%s | Sorted by = %s - %s.", $docStatus, $is_active, $sort_by, $sort);

// ===================================
?>