<h3>New Asset (category = <?php echo $category?> )</h3>


<form action="<?php echo $this->baseUrl ?>/inventory/asset/add"	method="post" enctype="multipart/form-data" id="NewAsset">
<input type="hidden" name="category_id" value="<?php echo (int) $category_id; ?>" />
<input type="hidden" name="redirectUrl" value="<?php echo $redirectUrl ?>" />

<table>

<tr>
	<td><label for="category">Name</label> </td>
	<td><input type="text"	name="name" value="" /></td>
</tr>
<tr>
	<td><label for="category">Description</label> 
	<td><textarea cols="45" name="description" id="description" style="background:#FFFFFF" rows="3"></textarea></td>
</tr>
<tr>
	<td><label for="group_id">Asset Group</label> </td>
	<td><input type="text"	name="group_id" value="" /></td>
</tr>
<tr>
	<td><label for="tag">Tag</label> </td>
	<td><input type="text"	name="tag" value="" /></td>
</tr>

<tr>
	<td><label for="brand">Brand</label> </td>
	<td><input type="text"	name="brand" value="" /></td>
</tr>

<tr>
	<td><label for="model">Model</label> </td>
	<td><input type="text"	name="model" value="" /></td>
</tr>
<tr>
	<td><label for="serial">Serial</label> </td>
	<td><input type="text"	name="serial" value="" /></td>
</tr>
<tr>
	<td><label for="origin">Origin</label></td>
	<td><input type="text"	name="origin" value="" /></td>
</tr>


<tr>
	<td><label for="origin">Location</label></td>
	<td><input type="text"	name="location" value="MLA" /></td>
</tr>


<tr>
	<td><label for="comment">Note: </label> 
	<td><textarea cols="60" name="comment" id="comment" style="background:#FFFFFF" rows="5"></textarea></td>
</tr>

<tr>
	<td></td> 
	<td><input type="submit" name="add" value="Add" />	</td>
</tr>

</table>

<p>Pictures:</p>
<input type="file" name="pictures[]" /><br>
<input type="file" name="pictures[]" /><br>
<input type="file" name="pictures[]" /><br>

 
</form>