<h3><?php echo $this->escapeHtml($category)?></h3>

 <P><a href="<?php echo $this->baseUrl ?>/inventory/asset/add?category_id=<?php echo $this->escapeHtml($category_id)?>&category=<?php echo $this->escapeHtml($category)?>">Add new asset</a></P>

<form action="<?php echo $this->baseUrl ?>/inventory/search/asset"	method="get" enctype="multipart/form-data" id="search">
<table>
	<tr><td><input type="text"	name="query" value="" /><td>
	<td><input type="submit" name="seach" value="search" /></td>
	</tr>
</table>
</form>


 <?php if ($total_asset <= 0){
 	
 	echo 'No asset found!';
 }else { 	
 	
 	echo $total_asset. ' assets found!';
 	
  	if (! is_null ( $paginator )) {
 		?>
 			
 		<hr>
 	<?php	
 		echo 'Result '. $paginator->minInPage. ' to '.$paginator->maxInPage;
 		}
 	
 ?>
 
<table border="1" cellpadding="3"> 
<tr>
		<td><b>Asset Name</b></td>
		<td><b>Model</b></td>
		<td><b>Serial</b></td>
		<td><b>Brand </b></td>
		<td><b>Tag </b></td>
		<td><b>Action</b></td>
	</tr>
 <?php foreach ($assets as $asset) : ?>
  	
    <tr>
		<td><?php echo $this->escapeHtml($asset['name']);?></td>
		<td><?php echo $this->escapeHtml($asset['model']);?></td>
		<td><?php echo $this->escapeHtml($asset['serial']);?></td>
		<td><?php echo $this->escapeHtml($asset['brand']);?></td>
		<td><?php echo $this->escapeHtml($asset['tag']);?></td>
		<td>
         <a href="<?php echo $this->baseUrl ?>/inventory/asset/edit?id=<?php echo $this->escapeHtml($asset['id']);?>">  Edit </a>
      	 | <a href="<?php echo $this->baseUrl ?>/inventory/asset/show?id=<?php echo $this->escapeHtml($asset['id']);?>">  Detail</a>
     	
     	</td>
	</tr>
<?php endforeach; ?>
</table>

<br>
<?php 

		
 if (!is_null($paginator)) { 
 	
 	$last = $this->baseUrl.'/inventory/asset/categorydetail?category_id='.$category_id.'&category='.$category.
 	'&page='.$paginator->totalPages.'&perPage='.$paginator->resultsPerPage;
 	
 	$first = $this->baseUrl.'/inventory/asset/categorydetail?category_id='.$category_id.'&category='.$category.
 	'&page=1&perPage='.$paginator->resultsPerPage;
 	
 	
 	for($i=$paginator->minInPageSet; $i<=$paginator->maxInPageSet; $i++) {
	
	$url = $this->baseUrl.'/inventory/asset/categorydetail?category_id='.$category_id.'&category='.$category.
	'&page='.$i.'&perPage='.$paginator->resultsPerPage;
	
	$last = $this->baseUrl.'/inventory/asset/categorydetail?category_id='.$category_id.'&category='.$category.
	'&page='.$paginator->totalPages.'&perPage='.$paginator->resultsPerPage;
	
?>

<?php if ($i == $paginator->page){
	echo $i. '&nbsp';
}else {
?>
	<a href="<?php echo $url; ?>"> <?php echo $i ?> &nbsp</a>

<?php }
}
?>
<a href="<?php echo $last; ?>">| Last</a>
<?php
}
}?>