
<h5><?php  echo $this->escapeHtml($asset->name);?> - Pictures</h5>

<table class="pure-table pure-table-bordered">
<thead>
	<tr>
		<td>File name</td>
		<td>File Type</td>
		<td>Size</td>
		<td>Visibility</td>
		<td>Uploaded on</td>		
		<td>Thumbnail</td>		
		<td>Action</td>
	</tr>
</thead>
<tbody>

 <?php 
	 
	 $count = 0;
	foreach ($pictures as $pic) : 
	 	 $count++;
	 echo  ($count % 2 == 1) ? "<tr>" : "<tr class=\"pure-table-odd\">";
	 	 
	 ?>
	 	<td><?php  echo $this->escapeHtml($pic->filename);?></td>
 		<td><?php  echo $this->escapeHtml($pic->filetype);?></td>
 		<td><?php  echo $this->escapeHtml($pic->size);?></td>
  		<td><?php  echo $this->escapeHtml($pic->visibility);?></td>
  		<td><?php  echo $this->escapeHtml($pic->uploaded_on);?></td>
  		<td> 
   		<img alt="" class= "img-rounded" width="50" hight="50" src="/inventory/image/assetthumbnail150?id=<?php  echo $this->escapeHtml($pic->id);?>"/>
   		
  		</td>
  		
	
		<td><a
			href="<?php echo $this->baseUrl ?>/inventory/image/delete-asset_picture?id=<?php  echo $this->escapeHtml($pic->id);?>">
				delete</td>
	</tr>
	 
<?php endforeach; ?>
</tbody>
</table>