<h5> Edit | Add Repair Request | Dispone Request | Show Repair History </h5>

<hr>

<h4> Asset Barcode: <img alt="" src="/inventory/asset/barcode?id=<?php echo $this->escapeHtml($asset->id);?>">
</h4> 
<hr>

<table>

<tr>
	<td><label for="category">Asset Name:</label> </td>
	<td><?php echo $this->escapeHtml($asset->name);?></td>
</tr>
<tr>
	<td><label for="category">Description:</label> 
	<td><?php echo $this->escapeHtml($asset->description);?></td>
</tr>
<tr>
	<td><label for="tag">Tag: </label> </td>
	<td><?php echo $this->escapeHtml($asset->tag);?></td>
</tr>



<tr>
	<td><label for="model">Model:</label> </td>
	<td><?php echo $this->escapeHtml($asset->model);?></td>
</tr>
<tr>
	<td><label for="serial">Serial:</label> </td>
	<td><?php echo $this->escapeHtml($asset->serial);?></td>
</tr>
<tr>
	<td><label for="origin">Origin:</label></td>
	<td><?php echo $this->escapeHtml($asset->origin);?></td>
</tr>


<tr>
	<td><label for="location">Location:</label></td>
	<td><?php echo $this->escapeHtml($asset->location);?></td>

</tr>

</table>



<h5> Asset Picture:</h5>
<table border="1">

 <?php foreach ($pictures as $pic) : ?>
  	
    <tr>
		<td>
			<img alt="" src="/inventory/image/index?id=<?php  echo $this->escapeHtml($pic->id);?>">
     	</td>
	</tr>
<?php endforeach; ?>
</table>