<div id="wrapper1" class="toggled1">

	<!-- Sidebar -->
	<div id="sidebar-wrapper1" style="font-size: 9.5pt;">
	
	 <form class="form-inline" action="<?php echo $this->baseUrl ?>/inventory/search/item"	method="get" enctype="multipart/form-data">
  <div class="form-group" style="padding-left: 8px;">
    	<input placeholder ="<?php echo $this->translate("enter search term ...")?>" class="form-control" size="15" type="text" name = "q">
 
 
  </div>
  
  <div class="form-group">
     <button type="submit" class="btn btn-default"><small><i class="glyphicon glyphicon-search"> </i></small></button>
  </div>
	
	
		<h5 style="padding-left: 10px;">
			<strong><?php echo $this->translate("ITEM CATEGORY")?></strong>
		</h5>
		<hr>
		
		

		<a style="color: #0080ff;padding-left: 10px; " href="javascript:;"
			onclick="$('#html').jstree('open_all');">Expand all </a>

		&nbsp;|&nbsp; <a style="color: #0080ff;" href="javascript:;"
			onclick="$('#html').jstree('close_all');">Collapse all </a>


		<div id="html" class="demo">
			<ul>
	<?php echo $jsTree ?>
		    </ul>
		</div>


	</div>
	<!-- /#sidebar-wrapper -->

	<!-- Page Content -->
	<div id="page-content-wrapper1"
		style="font-size: 9.5pt; padding: 0px; margin: 0px;">
		<div class="container-fluid" id="main_container"
			style="font-size: 9.5pt; padding: 1px; margin: 0px;";>
			<div>
			<a style="font-size: 9pt; margin: 2px; padding: 3px;"
				href="#menu-toggle" class="btn btn-primary btn-sm" id="menu-toggle"><i
				class="fa fa-chevron-left" aria-hidden="true"></i> Menu </a>
			</div>

				<a class="btn btn-default btn-sm"
				style="color: black; padding: 1pt 5pt 2pt 5pt;" title="List View"
				href="http://localhost:81/inventory/item-category/update-list"> <i class="fa fa-list" aria-hidden="true"></i></a>

			<div style="" id="category_list">
			</div>




		</div>
	</div>
	<!-- /#page-content-wrapper -->
	<hr>
	<footer>
		<span
			style="font-size: 9pt; font-weight: bold; padding-top: 20px; color: graytext;">&copy;
			2016-2018 Nguyen Mau Tri</span>
	</footer>

</div>
<!-- /#wrapper -->





<script>

  

// html demo
	$('#html').jstree({
		"core" : {
		       // so that create works
		       "check_callback" : true
		     },
		    "plugins" : [ "contextmenu" ],

		    "contextmenu":{         
		        "items": function($node) {
		            var tree = $("#html").jstree(true);
		            return {
		                "Create": {
		                    "separator_before": false,
		                    "separator_after": false,
		                    "label": "Create New Category",
		                    "action": function (obj) { 
		                    	var ref = $.jstree.reference(obj.reference);
                                sel = ref.get_selected();
        	                    $node = tree.create_node($node);
			                    tree.edit($node);
		                    }
		                },
		                "Rename": {
		                    "separator_before": false,
		                    "separator_after": false,
		                    "label": "Rename Category",
		                    "action": function (obj) { 
		                        tree.edit($node);
		                    }
		                },                         
		                "Remove": {
		                    "separator_before": false,
		                    "separator_after": false,
		                    "label": "Remove Category",
		                    "action": function (obj) { 
		                        tree.delete_node($node);
		                    }
		                },
		                "Add Member": {
		                    "separator_before": false,
		                    "separator_after": false,
		                    "label": "Add Member",
		                    "action": function (obj) {
		                    	var redirectUrl = "/application/item-category/add-member?category="+$node.text; 
		                    	window.location = redirectUrl;
		                   }
		                },
		                
		            };
		        }
		    }
		    
    });

	// When the jsTree is ready, add two more records.
	$('#html').on('create_node.jstree', function (e, data) {
		//alert(data.node.parent +  data.node.id);
	});
	
	$('#html').on('rename_node.jstree', function (e, data) {
		//alert(data.node.parent +  data.node.id);
		//createRole(data.node.parent,data.node.id,data.node.text);
    });

	$('#html').on('delete_node.jstree', function (e, data) {
		//alert(data.node.parent +  data.node.id);
		//createRole(data.node.parent,data.node.id,data.node.text);
    });

	$("#html").on("click", ".jstree-anchor", function(e) {

		   var node = $("#html").jstree(true).get_node($(this));
		   var id = $("#html").jstree(true).get_node($(this)).id;
		   var cat_name = $("#html").jstree(true).get_node($(this)).text;
		   //var node = $("#html").jstree(true).get_node($(this)).data.ic.hasMember;
			if (node.state.disabled)
    		{
        		//alert('disabled');
    		}else{        		
    			loadCategory(id,cat_name);
        	}
	});
</script>



