<?php
use Inventory\Domain\Item\ItemType;
use Inventory\Domain\Item\ItemSnapshot;

$nid = \Application\Model\Constants::INVENTORY_HASH_ID;

/**
 *
 * @var \Application\Controller\Plugin\NmtPlugin $nmtPlugin ;
 */
?>


<div id="tabs1" style="font-size: 9.5pt">

	<ul>
		<li><a href="#general">Items</a></li>
	</ul>
	<div id="general">


<?php

if ($total_records <= 0) {

    echo 'No record found!';
} else {

    if (! is_null($paginator)) {
        echo 'Record ' . $paginator->minInPage . ' to ' . $paginator->maxInPage . ' | ' . $total_records . ' records found!';
    } else {
        echo $total_records . ' records found!';
    }

    // $url = sprintf($this->baseUrl . '/inventory/item/list2?layout=list&is_active=%s&item_type=%s&sort_by=%s&sort=%s&is_fixed_asset=%s&perPage=%s&page=%s', $is_active, $item_type, $sort_by, $sort, $is_fixed_asset, $per_pape, $page);

    ?>


	&nbsp;&nbsp;&nbsp;<a class="btn btn-default btn-sm"
			style="color: black; padding: 1pt 5pt 2pt 5pt;" title="List View"
			href="<?php echo $url;?>"> <i class="fa fa-list" aria-hidden="true"></i></a>

		<hr style="margin: 5pt 1pt 5pt 1pt;">
		<div class="container-fluid">

 <?php

    $lineBreak = 4;
    $count = 0;

    foreach ($list as $a) :

     /**
      * @var ItemSnapshot $a ;
      */
        $url = $nmtPlugin->getItemPic($a->getId());

        if ($count == 0 || $count % $lineBreak == 0) {
            echo '<div class="row" style="height-min:130px; border:1px;">';
        }

        ?>
		    <div class="col-xs-6 col-md-3	">


				<table style="">
					<tr style="padding: 1pt 2pt 10pt 1pt;">
						<td>


							<div style="position: relative; float: right;">
								<!-- <span class="badge badge-primary"><?php echo ($paginator===null)? $count:$paginator->minInPage -1+ $count+1;?></span> -->

								<!--  <img id="item_<?php echo $this->escapeHtml($a->getId());?>"
									style="cursor: pointer;" title="click for more detail!"
									onclick="" class="img-rounded" width="120" height="120"
									src="/inventory/item/get-picture1?&item_id=<?php echo $a->getId();?>" />-->


								<a target="_blank" style="color: black;"
									href="<?php echo $this->baseUrl ?>/inventory/item/show?token=<?php echo $a->getToken() ;?>&entity_id=<?php echo  $a->getId();?>&checksum=<?php echo $a->getChecksum();?>">
									<img id="item_<?php echo $this->escapeHtml($a->getId());?>"
									style="cursor: pointer;" title="click for more detail!"
									onclick="" class="img-rounded" width="150" height="150"
									src="<?php echo $url; ?>" />
								</a>

							</div>
						</td>

						<td style="padding: 1pt 1pt 1pt 10pt;"><span
							style="padding: 1pt 1pt 1pt 2pt; font-weight: bold;"> <a
								target="_blank" style="color: black;"
								href="<?php echo $this->baseUrl ?>/inventory/item/show?token=<?php echo $a->getToken() ;?>&entity_id=<?php echo $a->getId();?>&checksum=<?php echo $a->getChecksum();?>">
						<?php echo ucwords(substr($this->escapeHtml($a->getItemName()),0,100));?></a>	
							<?php if($a->getItemType()=="SERVICE"):?>			
							<span style="font-size: 8pt;" class="badge">S</span>
							<?php endif; ?>
							
								<?php if($a->getIsFixedAsset()=="1"):?>			
							<span style="font-size: 6pt;" class="badge">A</span>
							<?php endif; ?>
							
								</span> <span
							style="padding: 1pt 1pt 1pt 1pt; color: graytext; font-size: 8pt;">
								<br><?php echo $this->escapeHtml(($a->getItemSku()));?>
						
			<br><?php echo $this->escapeHtml($a->getSysNumber());?>
				<br><?php echo $this->escapeHtml($a->getSerialNumber());?>
						<br><?php echo substr($this->escapeHtml($a->getManufacturerModel()),0,30);?>
						
						<div style="margin: 2px; font-size: 9pt">

									<div class="dropdown">
										<button
											style="color: black; padding: 2pt 2pt 2pt 2pt; color: navy; font-size: 8.5pt"
											class="btn btn-default dropdown-toggle btn-sm" type="button"
											id="dropdownMenu1" data-toggle="dropdown"
											aria-haspopup="true" aria-expanded="true">
											<i class="fa fa-bars" aria-hidden="true"></i>&nbsp;Action&nbsp;<span
												class="caret"></span>
										</button>
										
									</div>
						
	
		<?php ?>
	
					
					
					
					<tr>
				
				</table>


			</div>

		<?php
        $count ++;

        if ($count % $lineBreak == 0) {

            echo '</div><hr style="margin: 5pt 1pt 5pt 1pt;">';
        }
        ?>
        
    	
<?php endforeach; ?>
</div>





<?php

    // ===============================
    if (! is_null($paginator)) :

        // change it only
        $base = $this->baseUrl . '/inventory/item/list2?is_active=' . $is_active . '&layout=' . $layout . '&item_type=' . $item_type . '&sort_by=' . $sort_by . '&sort=' . $sort . '&is_fixed_asset=' . $is_fixed_asset;
        $_connector_symbol = '&';

        $last = $base . $_connector_symbol . 'page=' . $paginator->totalPages . '&perPage=' . $paginator->resultsPerPage;
        $first = $base . $_connector_symbol . 'page=1&perPage=' . $paginator->resultsPerPage;

        $p1 = ($paginator->page) - 1;
        $p2 = ($paginator->page) + 1;

        $prev = $base . $_connector_symbol . 'page=' . $p1 . '&perPage=' . $paginator->resultsPerPage;
        $next = $base . $_connector_symbol . 'page=' . $p2 . '&perPage=' . $paginator->resultsPerPage;

        echo '<ul class="pagination pagination-sm">';

        if ($paginator->page != 1 and $paginator->totalPages > 10) {
            echo '<li><a href="' . $first . '"> |< </a></li>';
            echo '<li><a href="' . $prev . '"> < </a></li>';
        }

        for ($i = $paginator->minInPageSet; $i <= $paginator->maxInPageSet; $i ++) {

            $url = $base . $_connector_symbol . 'page=' . $i . '&perPage=' . $paginator->resultsPerPage;

            if ($i == $paginator->page) {
                echo '<li><a class="active" href="#">' . $i . '</a></li>';
            } else {
                echo '<li><a href="' . $url . '"> ' . $i . ' </a></li>';
            }
        }
        if ($paginator->page != $paginator->totalPages and $paginator->totalPages > 10) {
            echo '<li><a href="' . $next . '"> > </a></li>';
            echo '<li><a href="' . $last . '"> >| </a></li>';
        }
        echo '</ul>';
endif;

}
// ===============================
?>

</div>
</div>


<script type="text/javascript">

$( "#tabs1" ).tabs({

	beforeLoad:function(e,ui){
		$( ui.panel ).html('<p>Loading...</p>');       
	    },
	   
});
</script>

