	<!-- 
	<ul id="menu" >
		 <li> <a href="<?php echo $this->baseUrl ?>/procurement/pr/create-step1">Create PR</a> </li>
	 	<li> <a href="<?php echo $this->baseUrl ?>/procurement/pr/my-pr">My Purchase Requests</a> </li>
	 	<li> <a href="<?php echo $this->baseUrl ?>/procurement/pr/my-submitted_items">My Submitted PR Items</a> </li>
		 <li> <a href="<?php echo $this->baseUrl ?>/procurement/pr/all-pr">Show all PR</a> </li>
	  	 <li> <a href="<?php echo $this->baseUrl ?>/procurement/pr/pr-items">Show all PR Items</a> </li>
	 	 <li> <a href="<?php echo $this->baseUrl ?>/procurement/delivery/create-step1">Create Delivery</a> </li>
	 	 <li> <a href="<?php echo $this->baseUrl ?>/procurement/delivery/my-delivery">My Deliveries</a> </li>
	 	 <li> <a href="<?php echo $this->baseUrl ?>/procurement/vendor/add">Create Vendor</a> </li>
	 	 <li> <a href="<?php echo $this->baseUrl ?>/procurement/vendor/list">Show All Vendors</a> </li>

	</ul>
	
	 -->
 <div class="btn-group">
   <div class="btn-group">
    <button type="button" class="btn btn-defaultdropdown-toggle" data-toggle="dropdown">
    Purchase Request (PR) <span class="caret"></span></button>
    <ul class="dropdown-menu" role="menu">
 		<li> <a href="<?php echo $this->baseUrl ?>/procurement/pr/all-pr">Show all PR</a> </li>
	  	<li> <a href="<?php echo $this->baseUrl ?>/procurement/pr/pr-items">Show all PR Items</a> </li>
	
    </ul>
  </div>
  
    <div class="btn-group">
    <button type="button" class="btn btn-defaultdropdown-toggle" data-toggle="dropdown">
    Quotation <span class="caret"></span></button>
    <ul class="dropdown-menu" role="menu">
      <li> <a href="<?php echo $this->baseUrl ?>/procurement/delivery/create-step1">Create Quotation</a> </li>
	 	  <li class="divider"></li>
	 	 
	 	 <li> <a href="<?php echo $this->baseUrl ?>/procurement/delivery/my-delivery">All Quotation</a> </li>
	    </ul>
    </ul>
  </div>
  
  <div class="btn-group">
    <button type="button" class="btn btn-info dropdown-toggle" data-toggle="dropdown">
    Delivery (DO) <span class="caret"></span></button>
    <ul class="dropdown-menu" role="menu">
 	 	<li> <a href="<?php echo $this->baseUrl ?>/procurement/do/receive"></a> </li>
    	 <li class="divider"></li>
	 	 <li> <a href="<?php echo $this->baseUrl ?>/procurement/po/list">PO Items</a> </li>
 		 <li> <a href="<?php echo $this->baseUrl ?>/procurement/delivery/item-to-deliver">Items to Delivery</a> </li>
	    </ul>
  </div>
  
   <div class="btn-group">
    <button type="button" class="btn btn-defaultdropdown-toggle" data-toggle="dropdown">
    Vendor <span class="caret"></span></button>
    <ul class="dropdown-menu" role="menu">
	 	 <li> <a href="<?php echo $this->baseUrl ?>/procurement/vendor/add">Create Vendor</a> </li>
	 	  <li class="divider"></li>
	 	 
	 	 <li> <a href="<?php echo $this->baseUrl ?>/procurement/vendor/list">Show All Vendors</a> </li>
   </ul>
  </div>
</div>