	<ul id="menu" >
	 <li> <a href="<?php echo $this->baseUrl ?>/procurement/pr/create-step1">Create PR</a> </li>
	 <li> <a href="<?php echo $this->baseUrl ?>/procurement/pr/my-pr">My Purchase Requests</a> </li>
	 	 <li> <a href="<?php echo $this->baseUrl ?>/procurement/delivery/create-step1">Create Delivery</a> </li>
	 	 <li> <a href="<?php echo $this->baseUrl ?>/procurement/delivery/my-delivery">My Deliveries</a> </li>

	</ul>
	
    

