<h4>
	<a href="/hr/setting/index"><i class="fa fa-cog" aria-hidden="true"></i> <?php echo $this->translate('HR SETTING'); ?></a>
</h4>
<div id="tabs" style="font-size: 9.5pt">

	<ul>
		<li><a href="#general"><?php echo $this->translate('Income Setup'); ?></a></li>
	</ul>
	<div id="general" style="font-size: 9.5pt">
		<h4><?php echo $n . $this->translate(' components updated.'); ?></h4>
	</div>
</div>