<?php /**@var \Application\Entity\NmtHrLeaveReason $entity ; */ ?>

<?php
if (count($errors) > 0) {
    echo '<div class="alert alert-danger" role="alert" style="font-size: 10.5pt">';

    echo '<ul>';
    foreach ($errors as $error) :
        echo '<li>' . $error . '</li>';
    endforeach
    ;
    echo '</ul>';
    echo '</div>';
}
?>

<div id="tabs" style="font-size: 9.5pt">
	<ul>
		<li><a href="#general"><?php echo $this->translate('New Leave Reason'); ?></a></li>
	</ul>

	<div id="general">

		<form id="create_employee_form" class="form-horizontal"
			action="/hr/leave-reason/add" method="post"
			enctype="multipart/form-data">
			<input type="hidden" name="redirectUrl"
				value="<?php echo $redirectUrl ?>" />
			<div class="form-group margin-bottom required">
				<label class="control-label col-sm-2"><?php echo $this->translate('Leave Reason'); ?>:</label>
				<div class="col-sm-3">
					<input class="form-control input-sm" type="text" name="leaveReason"
						value="<?php if(!$entity == null): echo $entity->getLeaveReason(); endif;?>"
						placeholder="Please enter leave reason!" id="" />
				</div>

				<div class="col-sm-4">
					<input
						<?php if(!$entity == null): echo ($entity->getIsActive()=="1")?"checked":""; else: echo "checked"; endif;?>
						type="checkbox" name="isActive" value="1">&nbsp;<?php echo $this->translate('Active'); ?>&nbsp;&nbsp;
		</div>
			</div>

			<div class="form-group margin-bottom required">
				<label class="control-label col-sm-2"><?php echo $this->translate('Leave Reason'); ?> (local):</label>
				<div class="col-sm-3">
					<input class="form-control input-sm" type="text"
						name="leaveReasonLocal"
						value="<?php if(!$entity == null): echo $entity->getLeaveReasonLocal(); endif;?>"
						placeholder="" />
				</div>
			</div>

			<div class="form-group margin-bottom required">
				<label class="control-label col-sm-2"><?php echo $this->translate('Reference'); ?>:</label>
				<div class="col-sm-3">
					<input class="form-control input-sm" type="text"
						name="legalReference"
						value="<?php if(!$entity == null): echo $entity->getLegalReference(); endif;?>"
						placeholder="" id="" />
				</div>
			</div>
			<div class="form-group margin-bottom">
				<label class="control-label col-sm-2"><?php echo $this->translate('Vadid From'); ?>:</label>
				<div class="col-sm-3">
					<input class="form-control input-sm" type="text" placeholder=""
						name="description"
						value="<?php echo (!$entity == null)? $entity->getDescription():"";?>">
				</div>
			</div>
			<div class="form-group margin-bottom">
				<label class="control-label col-sm-2"><?php echo $this->translate('Vadid To'); ?>:</label>
				<div class="col-sm-3">
					<input class="form-control input-sm" type="text" placeholder=""
						name="description"
						value="<?php echo (!$entity == null)? $entity->getDescription():"";?>">
				</div>
			</div>
			<div class="form-group margin-bottom">
				<label class="control-label col-sm-2"><?php echo $this->translate('Description'); ?>:</label>
				<div class="col-sm-8">
					<input class="form-control input-sm" type="text" placeholder=""
						name="description"
						value="<?php echo (!$entity == null)? $entity->getDescription():"";?>">
				</div>
			</div>
			<hr>


			<div class="form-group margin-bottom">
				<label class="control-label col-sm-2" for="inputTag"></label>
				<div class="col-sm-3">
					<a tabindex="10" class="btn btn-default btn-sm"
						onclick="submitForm('create_employee_form');" href="javascript:;"><small><i
							class="glyphicon glyphicon-floppy-disk"></i></small>&nbsp;<?php echo $this->translate('Save'); ?></a>
					<a tabindex="11" class="btn btn-default btn-sm"
						href="<?php echo $this->baseUrl ?>/hr/leave-reason/list"><small><i
							class=""></i></small>&nbsp;<?php echo $this->translate('Cancel'); ?></a>
				</div>
			</div>


		</form>
	</div>
</div>


