<h4>
	<a href="/hr/setting/index"><i class="fa fa-cog" aria-hidden="true"></i> <?php echo $this->translate('HR SETTING'); ?></a>
</h4>
<div id="tabs" style="font-size: 9.5pt">

	<ul>
		<li><a href="#general"><?php echo $this->translate('Leave Reason'); ?></a></li>
	</ul>
	<div id="general" style="font-size: 9pt">
		<a class="btn btn-default btn-sm"
			href="<?php echo $this->baseUrl ?>/hr/leave-reason/add"><small><i
				class="glyphicon glyphicon-plus"> </i></small>&nbsp;<?php echo $this->translate('New Leave Reason'); ?></a>
		<hr>


<?php

if ($total_records <= 0) {

    echo 'No record found!';
} else {

    if (! is_null($paginator)) {
        echo 'Record ' . $paginator->getMinInPage() . ' to ' . $paginator->getMaxInPage() . ' | ' . $total_records . ' records found!';
    } else {
        echo $total_records . ' ' . $this->translate('records');
    }

    ?>

<table style="font-size: 10pt;" class="table table-bordered table-hover">
			<thead>
				<tr>
					<td><b>#</b></td>
					<td><b><?php echo $this->translate('Leave Reason'); ?></a></b></td>
					<td><b><?php echo $this->translate('Reference'); ?></a></b></td>
					<td><b><?php echo $this->translate('Vadid From'); ?></a></b></td>
					<td><b><?php echo $this->translate('Vadid To'); ?></a></b></td>
					<td><b><?php echo $this->translate('Status'); ?></b></td>
					<td><b><?php echo $this->translate('Created Date'); ?></a></b></td>
					<td><b><?php echo $this->translate('Action'); ?></a></b></td>
				</tr>
			</thead>

			<tbody>
 
	 <?php

    $count = 0;
    foreach ($list as $a) :
        $count ++;
        /**@var \Application\Entity\NmtHrLeaveReason $a ; */
        ?>
	 <tr>
					<td><?php echo ($paginator===null)? $count:$paginator->getMinInPage() -1+ $count;?></td>
					<td><?php echo $this->escapeHtml($a->getLeaveReason());?></td>
					<td><?php echo $this->escapeHtml($a->getLegalReference());?></td>
					<td>1/1/2014</td>
					<td>1/1/9999</td>
					<td><?php echo $this->escapeHtml($a->getIsActive());?></td>
					<td><?php echo ($a->getCreatedOn()!==null )? date_format ( $a->getCreatedOn(), "d-m-y"):"";?> </td>
					<td><a
						href="<?php echo $this->baseUrl ?>/hr/leave-reason/show?token=<?php echo $this->escapeHtml($a->getToken());?>&entity_id=<?php echo $this->escapeHtml($a->getID());?>"><?php echo $this->translate('Show'); ?></a>
						<a
						href="<?php echo $this->baseUrl ?>/hr/leave-reason/edit?token=<?php echo $this->escapeHtml($a->getToken());?>&entity_id=<?php echo $this->escapeHtml($a->getID());?>"><?php echo $this->translate('Edit'); ?></a>
					</td>

				</tr>
<?php endforeach; ?>

 </tbody>
		</table>

<?php

    // ===============================
    if (! is_null($paginator)) :

        // change it only
        $base = $this->baseUrl . '/inventory/item/list?is_active=' . $is_active . '&item_type=' . $item_type . '&sort_by=' . $sort_by . '&sort=' . $sort . '&is_fixed_asset=' . $is_fixed_asset;
        $_connector_symbol = '&';

        $last = $base . $_connector_symbol . 'page=' . $paginator->getTotalPages() . '&perPage=' . $paginator->getResultsPerPage();;
        $first = $base . $_connector_symbol . 'page=1&perPage=' . $paginator->getResultsPerPage();;

        $p1 = ($paginator->getPage()) - 1;
        $p2 = ($paginator->getPage()) + 1;

        $prev = $base . $_connector_symbol . 'page=' . $p1 . '&perPage=' . $paginator->getResultsPerPage();;
        $next = $base . $_connector_symbol . 'page=' . $p2 . '&perPage=' . $paginator->getResultsPerPage();;

        echo '<ul class="pagination pagination-sm">';

        if ($paginator->getPage() != 1 and $paginator->getTotalPages() > 10) {
            echo '<li><a href="' . $first . '"> |< </a></li>';
            echo '<li><a href="' . $prev . '"> < </a></li>';
        }

        for ($i = $paginator->getMinInPageSet(); $i <= $paginator->getMaxInPageSet(); $i ++) {

            $url = $base . $_connector_symbol . 'page=' . $i . '&perPage=' . $paginator->getResultsPerPage();;

            if ($i == $paginator->getPage()) {
                echo '<li><a class="active" href="#">' . $i . '</a></li>';
            } else {
                echo '<li><a href="' . $url . '"> ' . $i . ' </a></li>';
            }
        }
        if ($paginator->getPage() != $paginator->getTotalPages() and $paginator->getTotalPages() > 10) {
            echo '<li><a href="' . $next . '"> > </a></li>';
            echo '<li><a href="' . $last . '"> >| </a></li>';
        }
        echo '</ul>';
endif;
	
}
// ===============================
?>
</div>
</div>