<?php
/**
 * @var \Application\Entity\NmtInventoryItemGroup $entity ;
 * @var \Application\Controller\Plugin\NmtPlugin $nmtPlugin ;
 * 
 * */
$form_action = '';
$form_title = '';

switch ($action) {

    case \Application\Model\Constants::FORM_ACTION_ADD:
        $form_action = '/inventory/item-group/add';
        $form_title = $this->translate("Add Item Group:");

        break;
    case \Application\Model\Constants::FORM_ACTION_EDIT:
        $form_action = '/inventory/item-group/edit';
        $form_title = $this->translate("Edit Item Group:");
        break;
}
?>




<div id="tabs" style="font-size: 10pt">
	<ul>
		<li><a href="#general"><?php echo $form_title;?></a></li>
					
		<?php if($action == \Application\Model\Constants::FORM_ACTION_EDIT):?>
        <?php endif;?>			
				</ul>

	<div id="general" style="font-size: 9pt">
		<!-- Tab1 -->
    	
 	<?php
if (count($errors) > 0) {
    echo '<div class="alert alert-danger alert-dismissible"" role="alert" style="font-size: 9.5pt"><a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>[ERROR]';

    echo '<ul>';
    foreach ($errors as $error) :
        echo '<li>' . $error . '</li>';
    endforeach
    ;
    echo '</ul>';
    echo '</div>';
}
?>
    
					<form id="New_Invoice_Row" class="form-horizontal"
			action="<?php echo $form_action;?>" method="post"
			enctype="multipart/form-data">

			<input type="hidden" name="redirectUrl"
				value="<?php echo $redirectUrl ?>" /> <input type="hidden"
				id="entity_id" name="entity_id"
				value="<?php if (!$entity == null): echo $entity->getId();endif;?>" />
					
							
            			<?php if($action == \Application\Model\Constants::FORM_ACTION_EDIT):?>
            				<input type="hidden" name="n" value="<?php echo $n;?>" />
            			<?php endif;?>
            			
            			
			<div class="form-group margin-bottom required">
				<label class="control-label col-sm-2"><?php echo $this->translate("Item Group");?>:</label>
				<div class="col-sm-3">
					<input class="form-control input-sm" type="text" placeholder=""
						id="groupName" name="groupName"
						value="<?php echo (!$entity == null)? $entity->getGroupName():"";?>">
				</div>

				<div class="col-sm-3">
					<input
						<?php if(!$entity== null): echo ($entity->getIsActive()=="1")?"checked":""; else: echo "checked"; endif;?>
						type="checkbox" name="isActive" value="1">&nbsp;IsActive&nbsp;&nbsp;&nbsp;&nbsp;

				</div>

			</div>
			<div class="form-group margin-bottom required">

				<label class="control-label col-sm-2"><?php echo $this->translate("Revenue Account");?>:</label>
				<div class="col-sm-3">
					<select name="revenue_account_id" class="form-control input-sm">
						<option value=""><?php echo $this->translate("Select GL Account");?></option>
   	    							<?php
            $gl_list = $nmtPlugin->glAccountList();

            if ($gl_list !== null) :
                foreach ($gl_list as $gl) :

                    /**@var \Application\Entity\FinAccount $gl ; */

                    if ($entity !== null) :
                        if ($entity->getRevenueAccount() !== null) :
                            if ($entity->getRevenueAccount()->getId() == $gl->getId()) :
                                echo '<option selected value="' . $gl->getId() . '">' . $gl->getAccountNumber() . '</option>';
                            else :
                                echo '<option value="' . $gl->getId() . '">' . $gl->getAccountNumber() . ' - ' . $gl->getDescription() . '</option>';
                            endif;
                        else :
                            echo '<option value="' . $gl->getId() . '">' . $gl->getAccountNumber() . ' - ' . $gl->getDescription() . '</option>';
                        endif;
                    else :
                        echo '<option value="' . $gl->getId() . '">' . $gl->getAccountNumber() . ' - ' . $gl->getDescription() . '</option>';
                    endif;
                endforeach
                ;
   	    							endif;

            ?>
   					</select>
				</div>

				<label class="control-label col-sm-2" for="inputTag"><?php echo $this->translate("Inventory Account (asset)");?>:</label>
				<div class="col-sm-3">
					<select name="inventory_account_id" class="form-control input-sm">
						<option value=""><?php echo $this->translate("Select GL Account");?></option>
   	    							<?php
            $gl_list = $nmtPlugin->glAccountList();

            if ($gl_list !== null) :
                foreach ($gl_list as $gl) :

                    /**@var \Application\Entity\FinAccount $gl ; */

                    if ($entity !== null) :
                        if ($entity->getInventoryAccount() !== null) :
                            if ($entity->getInventoryAccount()->getId() == $gl->getId()) :
                                echo '<option selected value="' . $gl->getId() . '">' . $gl->getAccountNumber() . '</option>';
                            else :
                                echo '<option value="' . $gl->getId() . '">' . $gl->getAccountNumber() . ' - ' . $gl->getDescription() . '</option>';
                            endif;
                        else :
                            echo '<option value="' . $gl->getId() . '">' . $gl->getAccountNumber() . ' - ' . $gl->getDescription() . '</option>';
                        endif;
                    else :
                        echo '<option value="' . $gl->getId() . '">' . $gl->getAccountNumber() . ' - ' . $gl->getDescription() . '</option>';
                    endif;
                endforeach
                ;
   	    							endif;

            ?>
   					</select>
				</div>

			</div>

			<div class="form-group margin-bottom required">

				<label class="control-label col-sm-2"><?php echo $this->translate("Expense Account");?>:</label>
				<div class="col-sm-3">
					<select name="expense_account_id" class="form-control input-sm">
						<option value=""><?php echo $this->translate("Select GL Account");?></option>
   	    							<?php
            $gl_list = $nmtPlugin->glAccountList();

            if ($gl_list !== null) :
                foreach ($gl_list as $gl) :

                    /**@var \Application\Entity\FinAccount $gl ; */

                    if ($entity !== null) :
                        if ($entity->getExpenseAccount() !== null) :
                            if ($entity->getExpenseAccount()->getId() == $gl->getId()) :
                                echo '<option selected value="' . $gl->getId() . '">' . $gl->getAccountNumber() . '</option>';
                            else :
                                echo '<option value="' . $gl->getId() . '">' . $gl->getAccountNumber() . ' - ' . $gl->getDescription() . '</option>';
                            endif;
                        else :
                            echo '<option value="' . $gl->getId() . '">' . $gl->getAccountNumber() . ' - ' . $gl->getDescription() . '</option>';
                        endif;
                    else :
                        echo '<option value="' . $gl->getId() . '">' . $gl->getAccountNumber() . ' - ' . $gl->getDescription() . '</option>';
                    endif;
                endforeach
                ;
   	    							endif;

            ?>
   					</select>
				</div>

				<label class="control-label col-sm-2" for="inputTag"><?php echo $this->translate("COGS Account");?>:</label>
				<div class="col-sm-3">
					<select name="cogs_account_id" class="form-control input-sm">
						<option value=""><?php echo $this->translate("Select GL Account");?></option>
   	    							<?php
            $gl_list = $nmtPlugin->glAccountList();

            if ($gl_list !== null) :
                foreach ($gl_list as $gl) :

                    /**@var \Application\Entity\FinAccount $gl ; */

                    if ($entity !== null) :
                        if ($entity->getCogsAccount() !== null) :
                            if ($entity->getCogsAccount()->getId() == $gl->getId()) :
                                echo '<option selected value="' . $gl->getId() . '">' . $gl->getAccountNumber() . '</option>';
                            else :
                                echo '<option value="' . $gl->getId() . '">' . $gl->getAccountNumber() . ' - ' . $gl->getDescription() . '</option>';
                            endif;
                        else :
                            echo '<option value="' . $gl->getId() . '">' . $gl->getAccountNumber() . ' - ' . $gl->getDescription() . '</option>';
                        endif;
                    else :
                        echo '<option value="' . $gl->getId() . '">' . $gl->getAccountNumber() . ' - ' . $gl->getDescription() . '</option>';
                    endif;
                endforeach
                ;
   	    							endif;

            ?>
   					</select>
				</div>

			</div>

			<div class="form-group margin-bottom">

				<label class="control-label col-sm-2" for="inputTag"><?php echo $this->translate("Cost Center");?>:</label>
				<div class="col-sm-3">
					<select name="cost_center_id" class="form-control input-sm">
						<option value=""><?php echo $this->translate("Select Cost Center");?></option>
   	    							<?php

            $cost_center_list = $nmtPlugin->costCenterList();
            if ($cost_center_list !== null) :
                foreach ($cost_center_list as $cc) :

                    /**@var \Application\Entity\FinCostCenter $cc ; */

                    if ($entity !== null) :
                        if ($entity->getCostCenter() !== null) :
                            if ($entity->getCostCenter()->getId() == $cc->getId()) :
                                echo '<option selected value="' . $cc->getId() . '">' . $cc->getCostCenterName() . '</option>';
                            else :
                                echo '<option value="' . $cc->getId() . '">' . $cc->getCostCenterName() . ' - ' . $cc->getDescription() . '</option>';
                            endif;
                        else :
                            echo '<option value="' . $cc->getId() . '">' . $cc->getCostCenterName() . ' - ' . $cc->getDescription() . '</option>';
                        endif;
                    else :
                        echo '<option value="' . $cc->getId() . '">' . $cc->getCostCenterName() . ' - ' . $cc->getCostCenterName() . '</option>';
                    endif;
                endforeach
                ;
   	    							endif;

            ?>
   					</select>
				</div>
			</div>

			<div class="form-group margin-bottom">

				<label class="control-label col-sm-2" for="inputTag"><?php echo $this->translate("Default Warehouse");?>:</label>
				<div class="col-sm-3">
					<select name="default_warehouse_id" class="form-control input-sm">
						<option value=""><?php echo $this->translate("---");?></option>
   	    							<?php
            $wh_list = $nmtPlugin->warehouseList();
            if ($wh_list !== null) :
                foreach ($wh_list as $cc) :

                    /**@var \Application\Entity\NmtInventoryWarehouse $cc ; */

                    if ($entity !== null) :
                        if ($entity->getDefaultWarehouse() !== null) :
                            if ($entity->getDefaultWarehouse()->getId() == $cc->getId()) :
                                echo '<option selected value="' . $cc->getId() . '">' . $cc->getWhCode() . ' - ' . $cc->getWhName() . '</option>';
                            else :
                                echo '<option value="' . $cc->getId() . '">' . $cc->getWhCode() . ' - ' . $cc->getWhName() . '</option>';
                            endif;
                        else :
                            echo '<option value="' . $cc->getId() . '">' . $cc->getWhCode() . ' - ' . $cc->getWhName() . '</option>';
                        endif;
                    else :
                        echo '<option value="' . $cc->getId() . '">' . $cc->getWhCode() . ' - ' . $cc->getWhName() . '</option>';
                    endif;
                endforeach
                ;
   	    							endif;

            ?>
   					</select>
				</div>
			</div>
			<div class="form-group margin-bottom">
				<label class="control-label col-sm-2">Remarks:</label>
				<div class="col-sm-8">
					<input class="form-control input-sm" type="text" placeholder=""
						name="description"
						value="<?php echo (!$entity == null)? $entity->getDescription():"";?>">
				</div>
			</div>
			<hr>
			<div class="form-group margin-bottom">
				<label class="control-label col-sm-2" for="inputTag"></label>
				<div class="col-sm-3">
					<button onclick="submitForm('Create_Inv_Form');"
						class="btn btn-default btn-sm">
						<i class="glyphicon glyphicon-floppy-disk"> </i> Save
					</button>
					<a class="btn btn-default btn-sm"
						href="<?php echo $this->baseUrl ?>/inventory/item-group/list"><small><i
							class="glyphicon glyphicon-remove"></i></small>&nbsp;Cancel</a>

				</div>
			</div>

		</form>


	</div>

	<!-- end tab -->
</div>

