<?php if (count($rows)==0): 

?>

<h5>no thing found!</h5>

<?php else: 

//$nid = "0ff0ae71fd193493409a6434844b72d621011fd814b9c882c51fd448adc789e4";
$nid = "06a19815c7af6d8df4cfe6ab657ec477fe284cda72fbf12cce02dabdd4ce51a8";

?>
<div style="color: gray;font-size: 9pt;" id="total_ordered"></div>
<div style="color: gray;font-size: 9pt;" id="total_received"></div>
<div style="color: gray;font-size: 9pt;" id="total_balance"></div>

<table style="font-size: 9pt;" class="table table-bordered table-hover">
	<thead>
		<tr>
			<td><b>#</b></td>
			<td><b>PR No.</b></td>
			<td><b>PO No.</b></td>
			<td><b>AP Invoice</b></td>			
			<td><b>Vendor</b></td>				
			<td><b>Pr Date</b></td>
			<td><b>Unit</b></td>
			<td><b>Quantity <br> Q'ty</b></td>
			<td><b>U/P<br>Doc.</b></td>
			<td><b>Total<br>Doc.</b></td>
			<td><b>Doc.<br>Curr</b></td>
			<td><b>U/P.<br>Loc.</b></td>
			<td><b>Total.<br>Loc.</b></td>
	
			<td><b>Status</b></td>
			<td><b>Action</b></td>
		</tr>
	</thead>
	<tbody>
 
	 <?php
	
	$count = 0;
	//$total_ordered = 0;
	//$total_received = 0;
	//$total_balance = 0;
	foreach ( $rows as $r ) :
		$count ++;
		/**@var \Application\Entity\FinVendorInvoiceRow $a ;*/		
		$a = $r[0];
		
		?>
	 <tr>
	 <td><?php echo $count;?></td>
			<?php if($a->getPrRow()!==null):?>			
			<td><a href="/procure/pr/show?nid=<?php echo $nid;?>&entity_id=<?php echo $a->getPrRow()->getPr()->getId();?>&token=<?php echo $a->getPrRow()->getPr()->getToken();?>" target="_blank"><?php echo $a->getPrRow()->getPr()->getPrAutoNumber();?></a></td>
			<?php else:?>
			<td>N/A</td>
			<?php endif; ?>
			
			<?php if($a->getPoRow()!==null):?>			
			<td><a href="/procure/po/add1?nid=<?php echo $nid;?>&entity_id=<?php echo $a->getPoRow()->getPo()->getId();?>&token=<?php echo $a->getPoRow()->getPo()->getToken();?>" target="_blank"><?php echo $a->getPoRow()->getPo()->getSysNumber();?></a></td>
			<?php else:?>
			<td>N/A</td>
			<?php endif; ?>
			
	 		<td><a href="/finance/v-invoice/show?nid=<?php echo $nid;?>&entity_id=<?php echo $a->getInvoice()->getId();?>&token=<?php echo $a->getInvoice()->getToken();?>" target="_blank"><?php if($a->getInvoice()->getSysNumber()==null):echo "N/A";else: echo $a->getInvoice()->getSysNumber();endif;?></a></td>
			
			<td><?php if(!$a->getInvoice()->getVendor()==null): echo $a->getInvoice()->getVendor()->getVendorName();endif;?> </td>
	
			<td><?php if(!$a->getInvoice()->getInvoiceDate()==null): echo date_format ( $a->getInvoice()->getInvoiceDate(), "d/m/y");endif;?> </td>
			<td><?php echo $a->getItem()->getStandardUom()->getUomCode();?></td>
		
			<td><?php echo $a->getQuantity();?></td>
			<td><?php echo number_format($a->getUnitPrice(),$a->getInvoice()->getCurrency()->getDecimalPlaces());?></td>
			<td><?php echo number_format($a->getUnitPrice()*$a->getQuantity(),$a->getInvoice()->getCurrency()->getDecimalPlaces());?></td>
			<td><?php echo $a->getInvoice()->getCurrency()->getCurrency();?></td>
			<td><?php echo number_format($a->getUnitPrice()*$a->getInvoice()->getExchangeRate(),0);?></td>
			<td><?php echo number_format($a->getUnitPrice()*$a->getInvoice()->getExchangeRate()*$a->getQuantity(),0);?></td>
		
			<td><?php echo $a->getCurrentState();?></td>
			<td>
			</td>
			
		</tr>
<?php endforeach; ?>

 </tbody>
</table>

<script type="text/javascript">
</script>

<?php endif; ?>
	
