<?php

/**@var \Application\Entity\FinVendorInvoice $target ;
 @var \Application\Entity\FinVendorInvoiceRow $entity ;
 */
$form_action = '';
$form_title = '';

switch ($action) {

    case \Application\Model\Constants::FORM_ACTION_ADD:
        $form_action = '/finance/v-invoice-row/add';
        $form_title = $this->translate("Add AP Row:");

        break;
    case \Application\Model\Constants::FORM_ACTION_EDIT:
        $form_action = '/finance/v-invoice-row/edit';
        $form_title = $this->translate("Edit AP Row:");
        break;
}
?>


<div id="wrapper" class="toggled">

	<!-- Sidebar -->
	<div id="sidebar-wrapper" style="font-size: 9.5pt;">
	
					<?php
    $current_step = "STEP2";
    include (ROOT . '/module/Finance/view/finance/ap-create-wizard.php');
    ?>
  				<div class="alert alert-info" role="alert"
			style="padding: 1px; font-size: 9.5pt; margin: 5pt 2pt 5pt 5pt">
			<ul style="font-size: 9pt; padding-left: 18pt;">
				<li><span style="color: gray;"> Vendor: <?php if (!$target == null): if (!$target->getVendor() == null):echo $target->getVendor()->getVendorName();endif;endif;?></li>
				<li><span style="color: gray;">Invoice No.: <?php echo (!$target == null)? $target->getInvoiceNo():"";?> // <?php echo (!$target == null)? $target->getSapDoc():"";?></span></li>
				<li><span style="color: gray;">Invoice Date: <?php if(!$target == null): if ($target->getInvoiceDate() !== null): echo date_format($target->getInvoiceDate(),"Y-m-d"); endif; endif;?></span>
				</li>
				<li><span style="color: gray;">A/P #<?php echo (!$target == null)? $target->getSysNumber():"";?></span></li>
				<li><span style="color: gray;">Status: <?php echo (!$target == null)? $target->getCurrentState():"";?></span></li>

				<li>-----</li>

				<li><span style="color: gray;">Total Line: <?php echo ($total_row);?></span></li>
				<li><span style="color: gray;">Net: <?php echo number_format($net_amount,2) . " " . $target->getCurrency()->getCurrency() ;?></span></li>
				<li><span style="color: gray;">Tax: <?php echo number_format($tax_amount,2);?></span></li>
				<li><span style="color: gray;">Gross: <?php echo number_format($gross_amount,2) . " " .$target->getCurrency()->getCurrency();?></span></li>
			</ul>
		</div>


	</div>
	<!-- /#sidebar-wrapper -->

	<!-- Page Content -->
	<div id="page-content-wrapper"
		style="font-size: 9.5pt; padding: 0px; margin: 0px;">
		<div class="container-fluid" id="main_container"
			style="font-size: 9.5pt; padding: 1px; margin: 0px;";>
			<a style="font-size: 9pt; margin: 2px; padding: 3px;"
				href="#menu-toggle" class="btn btn-primary btn-sm" id="menu-toggle"><span
				title="Hide Menu"><i class="fa fa-chevron-left" aria-hidden="true"></i>
					Menu <span></a>


			<div id="tabs" style="font-size: 10pt">
				<ul>
					<li><a href="#general"><?php echo $form_title;?></a></li>
					
				<?php if($action == \Application\Model\Constants::FORM_ACTION_EDIT):?>
            		<li ><a title="<?php echo $this->translate("Change Logs");?>" href="<?php echo $this->baseUrl ?>/procure/change-log/list1?object_token=<?php echo (!$entity == null)? $entity->getToken():"";?>&object_id=<?php echo (!$entity == null)? $entity->getId():"";?>&class_name=<?php echo (!$entity == null)? get_class($entity):"";?>"><span class="glyphicon glyphicon-list"></span>&nbsp;Log</a></li>
				<?php endif;?>
            			
				</ul>

				<div id="general" style="font-size: 9pt">
					<!-- Tab1 -->
	
	<?php
if (count($errors) > 0) {
    echo '<div class="alert alert-danger alert-dismissible" role="alert" style="font-size: 9.5pt"> <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>[ERROR]';

    echo '<ul>';
    foreach ($errors as $error) :
        echo '<li>' . $error . '</li>';
    endforeach
    ;
    echo '</ul>';
    echo '</div>';
}
?>
	
					<form id="New_Invoice_Row" class="form-horizontal"
						action="<?php echo $form_action;?>"
						method="post" enctype="multipart/form-data">
						
						<input type="hidden" name="redirectUrl"
							value="<?php echo $redirectUrl ?>" /> <input type="hidden"
							id="target_id" name="target_id"
							value="<?php if (!$target == null): echo $target->getId();endif;?>" />
						<input type="hidden" id="target_token" name="target_token"
							value="<?php if (!$target == null): echo $target->getToken();endif;?>" />

						<input type="hidden" id="entity_id" name="entity_id"
							value="<?php if (!$entity == null): echo $entity->getId();endif;?>" />
						<input type="hidden" id="token" name="token"
							value="<?php if (!$entity == null): echo $entity->getToken();endif;?>" />

							
            			<?php if($action == \Application\Model\Constants::FORM_ACTION_EDIT):?>
            				<input type="hidden" name="n" value="<?php echo $n;?>" />
            			<?php endif;?>
            		
							
						<div class="form-group margin-bottom">
							<label class="control-label col-sm-2">Row Number: </label>
							<div class="col-sm-1">
								<input tabindex="0" class="form-control input-sm" type="text"
									id="rowNumber" name="rowNumber"
									value="<?php if($entity->getRowNumber()==null): echo ($max_row_number+1); else: echo $entity->getRowNumber(); endif;?>">
							</div>

							<label class="control-label col-sm-2"></label>
							<div class="col-sm-3">
								<input <?php if(!$entity== null): echo ($entity->getIsActive()=="1")?"checked":""; else: echo "checked"; endif;?>
									type="checkbox" name="isActive" value="1">&nbsp;Is
								Active&nbsp;&nbsp;&nbsp;&nbsp;
							</div>
						</div>

						<div class="form-group margin-bottom">	
							<label class="control-label col-sm-2">PR Item: </label>
							<div class="col-sm-3">
								<input tabindex="1" class="form-control input-sm" type="text"
									id="pr_item_name" placeholder="Select PR item"
									name="pr_item_name"
									value="<?php if (!$entity== null): if($entity->getPrRow()!==null): echo $entity->getPrRow()->getRowIdentifer(); endif;endif;?>">
								<input type="hidden" id="pr_row_id" placeholder=""
									name="pr_row_id"
									value="<?php if (!$entity== null): if($entity->getPrRow()!==null): echo $entity->getPrRow()->getId(); endif;endif;?>">

								<div id="pr_row_url" style="display: none;"></div>


							</div>

							<div class="col-sm-1">

								<span title="<?php echo $this->translate("Line Detail");?>"
									id="pr_row_detail" style="display: none;"> &nbsp;&nbsp;<a
									style="color: #0080ff;" href="javascript:;"
									onclick="showSelectedPrRow();"><i style="color: navy"
										class="fa fa-info-circle fa-lg" aria-hidden="true"></i></a>
								</span>
							</div>

							<div class="col-sm-2">
								<a tabindex="100" style="color: #0080ff;" href="javascript:;"
									onclick="showJqueryDialog('Select PR Row','1000',$(window).height()-100, '/procure/pr-search/do1?target_id=pr_row_id&target_name=pr_item_name','j_loaded_data', true);">Select&nbsp;&nbsp;<i
									class="glyphicon glyphicon-folder-open"></i>
								</a>
							</div>

							<div class="col-sm-3">
								<a tabindex="101" target="_blank" style="font-size: 9pt;"
									href="/procure/pr/all/row_number=2/status=all">PR List&nbsp;&nbsp;</a><small><i
									class="glyphicon glyphicon-new-window"></i></small>
							</div>
						</div>
						
						<div class="form-group margin-bottom">
							<label class="control-label col-sm-2">PO Item: </label>
							<div class="col-sm-3">
								<input tabindex="1" class="form-control input-sm" type="text"
									id="po_item_name" placeholder="Select PO item"
									name="po_item_name"
									value="<?php if (!$entity== null): if($entity->getPoRow()!==null): echo $entity->getPoRow()->getRowIdentifer(); endif;endif;?>">
								<input type="hidden" id="po_row_id" placeholder=""
									name="po_row_id"
									value="<?php if (!$entity== null): if($entity->getPoRow()!==null): echo $entity->getPoRow()->getId(); endif;endif;?>">

								<div id="po_row_url" style="display: none;"></div>


							</div>

							<div class="col-sm-1">

								<span title="<?php echo $this->translate("Line Detail");?>"
									id="pr_row_detail" style="display: none;"> &nbsp;&nbsp;<a
									style="color: #0080ff;" href="javascript:;"
									onclick="showSelectedPoRow();"><i style="color: navy"
										class="fa fa-info-circle fa-lg" aria-hidden="true"></i></a>
								</span>
							</div>

							<div class="col-sm-2">
								<a tabindex="100" style="color: #0080ff;" href="javascript:;"
									onclick="showJqueryDialog('Select PO Row','1000',$(window).height()-100, '/procure/po-search/do1?target_id=po_row_id&target_name=po_item_name','j_loaded_data', true);">Select&nbsp;&nbsp;<i
									class="glyphicon glyphicon-folder-open"></i>
								</a>
							</div>

							<div class="col-sm-3">
								<a tabindex="101" target="_blank" style="font-size: 9pt;"
									href="/procure/pr-row/all">PR Item List&nbsp;&nbsp;</a><small><i
									class="glyphicon glyphicon-new-window"></i></small>
							</div>
						</div>
						

						<div class="form-group margin-bottom  required">
							<label class="control-label col-sm-2">Item: </label>
							<div class="col-sm-3">
								<input tabindex="2" class="form-control" type="text"
									id="item_name" placeholder="Enter keyword to search item..."
									name="item_name"
									value="<?php if (!$entity== null): if($entity->getItem()!==null): echo $entity->getItem()->getItemName(); endif;endif;?>">


								<input type="hidden" id="item_id" placeholder="" name="item_id"
									value="<?php if (!$entity== null): if($entity->getItem()!==null): echo $entity->getItem()->getID(); endif;endif;?>">

								<div id="item_url" style="display: none;"></div>


							</div>

							<div class="col-sm-1" style="margin: 0px">
								<span title="<?php echo $this->translate("Item Detail");?>"
									id="item_detail" style="display: none;"> &nbsp;&nbsp;<a
									style="color: #0080ff;" href="javascript:;"
									onclick="showSelectedItem();"><i style="color: navy"
										class="fa fa-info-circle fa-lg" aria-hidden="true"></i> </a> <br>
								</span>
							</div>

							<div class="col-sm-2">
								<a style="color: #0080ff;" href="javascript:;"
									onclick="showJqueryDialog('Select Item','1000',$(window).height()-100, '/inventory/item-search/do1?target_id=item_id&target_name=item_name','j_loaded_data', true);">Select&nbsp;&nbsp;<i
									class="glyphicon glyphicon-folder-open"></i>
								</a>

							</div>
							<div class="col-sm-3">
								<a target="_blank" style="font-size: 9pt;"
									href="/inventory/item/list">Item List&nbsp;&nbsp;</a><small><i
									class="glyphicon glyphicon-new-window"></i></small>
							</div>
						</div>
						<div class="form-group margin-bottom">
							<label class="control-label col-sm-2" for="inputTag">Vendor Item
								Code:</label>
							<div class="col-sm-3">
								<input tabindex="3" class="form-control input-sm" type="text"
									id="vendorItemName" name="vendorItemName"
									value="<?php echo (!$entity == null)? $entity->getVendorItemName():"";?>">
							</div>
							
							<label class="control-label col-sm-2" for="inputTag">Vendor Item
								Code:</label>
							<div class="col-sm-3">
								<input tabindex="3" class="form-control input-sm" type="text"
									id="vendor_item_code" name="vendorItemCode"
									value="<?php echo (!$entity == null)? $entity->getVendorItemCode():"";?>">
							</div>
						</div>
						<hr style="margin: 5pt 1pt 5pt 1pt;">
						<div class="form-group margin-bottom required">

							<label class="control-label col-sm-2"><?php echo $this->translate("Target Warehouse");?>:</label>
							<div class="col-sm-3">
								<select tabindex="4" name="target_wh_id" id="target_wh_id"
									class="form-control input-sm">
									<option value=""><?php echo $this->translate("...");?></option>
   	    							<?php
   	    	 if ($wh_list !== null) :
   	    	 foreach ($wh_list as $gl) :

                    /**@var \Application\Entity\NmtInventoryWarehouse $gl ; */

                    if ($entity !== null) :
                        if ($entity->getWarehouse() !== null) :
                        if ($entity->getWarehouse()->getId() == $gl->getId()) :
                            echo '<option selected value="' . $gl->getId() . '">' . $gl->getWhName() . '</option>';
                            else :
                            echo '<option value="' . $gl->getId() . '">' . $gl->getWhName() . '</option>';
                            endif;
                        else :
                        echo '<option value="' . $gl->getId() . '">' . $gl->getWhName() . '</option>';
                        endif;
                    else :
                    echo '<option value="' . $gl->getId() . '">' . $gl->getWhName()  . '</option>';
                    endif;
                endforeach
                ;
   	    							endif;

            ?>
   					</select>
							</div>	
							</div>


						<div class="form-group margin-bottom required">
							<label class="control-label col-sm-2" for="inputTag">Quantity:</label>
							<div class="col-sm-3">
								<input tabindex="4" class="form-control input-sm" type="text"
									id="quantity" name="docQuantity"
									value="<?php echo (!$entity == null)? $entity->getDocQuantity():"";?>">
							</div>
						</div>

						<div class="form-group margin-bottom required">
							<label class="control-label col-sm-2" for="inputTag">Unit:</label>
							<div class="col-sm-3">
								<input tabindex="5" class="form-control input-sm" type="text"
									name="docUnit" id="rowUnit"
									value="<?php echo (!$entity == null)? $entity->getDocUnit():"each";?>">

								<div
									style="color: graytext; padding-bottom: 5px; margin: 0 0 0 20pt; font-size: 8.5pt"
									id="pr_row_uom"></div>

							</div>
							<label class="control-label col-sm-2" for="inputTag"><?php echo $this->translate("Convert Factor");?>:</label>
							<div class="col-sm-3">
								<input tabindex="6" class="form-control input-sm" type="text"
									name="conversionFactor"
									value="<?php echo (!$entity == null)? $entity->getConversionFactor():"1";?>">
								<div
									style="color: graytext; padding-bottom: 5px; margin: 0 0 0 10pt; font-size: 8.5pt"
									id="">Converstion to order unit (see PR).</div>

							</div>

						</div>

						<div class="form-group margin-bottom required">
							<label class="control-label col-sm-2" for="inputTag">Unit Price:</label>
							<div class="col-sm-3">
								<input tabindex="7" class="form-control input-sm" type="text"
									id="docUnitPrice" name="docUnitPrice"
									value="<?php echo (!$entity == null)? $entity->getDocUnitPrice():"";?>">

							</div>
							<div class="col-sm-3">
         	        		<?php if (!$target == null): echo $target->getCurrency()->getCurrency(); endif;?>
          </div>
						</div>
						<div class="form-group margin-bottom required">
							<label class="control-label col-sm-2" for="inputTag">Net Amount:</label>
							<div class="col-sm-3">
								<input readonly class="form-control input-sm" type="text"
									id="net_amount" name="netAmount"
									value="<?php echo (!$entity == null)? $entity->getNetAmount():"";?>">

							</div>
							<div class="col-sm-3">
         	        		<?php if (!$target == null): echo $target->getCurrency()->getCurrency(); endif;?>
          </div>
						</div>
						<div class="form-group margin-bottom required">
							<label class="control-label col-sm-2" for="inputTag">Tax Rate:</label>
							<div class="col-sm-3">
								<input tabindex="8" class="form-control input-sm" type="text"
									id="tax_rate" name="taxRate"
									value="<?php echo (!$entity == null)? $entity->getTaxRate():"";?>">
							</div>
							<label class="control-label col-sm-2" for="inputTag">Tax Amount:</label>
							<div class="col-sm-3">
								<input readonly class="form-control input-sm" type="text"
									id="tax_amount" name="taxAmount"
									value="<?php echo (!$entity == null)? $entity->getTaxAmount():"";?>">
							</div>
						</div>

						<div class="form-group margin-bottom required">
							<label class="control-label col-sm-2" for="inputTag">Gross
								Amount:</label>
							<div class="col-sm-3">
								<input readonly class="form-control input-sm" type="text"
									id="gross_amount" name="grossAmount"
									value="<?php echo (!$entity == null)? $entity->getGrossAmount():"";?>">

							</div>
							<div class="col-sm-3">
         	        		<?php if (!$target == null): echo $target->getCurrency()->getCurrency(); endif;?>
          </div>
						</div>

						<div class="form-group margin-bottom required">

							<label class="control-label col-sm-2"><?php echo $this->translate("GL Account");?>:</label>
							<div class="col-sm-3">
								<select tabindex="9" name="gl_account_id" id="gl_account_id"
									class="form-control input-sm">
									<option value=""><?php echo $this->translate("Select GL Account");?></option>
   	    							<?php
            if ($gl_list !== null) :
                foreach ($gl_list as $gl) :

                    /**@var \Application\Entity\FinAccount $gl ; */

                    if ($entity !== null) :
                        if ($entity->getGlAccount() !== null) :
                            if ($entity->getGlAccount()->getId() == $gl->getId()) :
                            echo '<option selected value="' . $gl->getId() . '">' . $gl->getAccountNumber() . ' - ' . $gl->getDescription() . '</option>';
                            else :
                                echo '<option value="' . $gl->getId() . '">' . $gl->getAccountNumber() . ' - ' . $gl->getDescription() . '</option>';
                            endif;
                        else :
                            echo '<option value="' . $gl->getId() . '">' . $gl->getAccountNumber() . ' - ' . $gl->getDescription() . '</option>';
                        endif;
                    else :
                        echo '<option value="' . $gl->getId() . '">' . $gl->getAccountNumber() . ' - ' . $gl->getDescription() . '</option>';
                    endif;
                endforeach
                ;
   	    							endif;

            ?>
   					</select>
							</div>

							

						</div>
						
						<div class="form-group margin-bottom">
				<label class="control-label col-sm-2" for="inputTag"><?php echo $this->translate("Cost Center");?>:</label>
							<div class="col-sm-3">
								<select tabindex="10" name="cost_center_id" id="cost_center_id"
									class="form-control input-sm">
									<option value=""><?php echo $this->translate("Select Cost Center");?></option>
   	    							<?php
            if ($cost_center_list !== null) :
                foreach ($cost_center_list as $cc) :

                    /**@var \Application\Entity\FinCostCenter $cc ; */

                    if ($entity !== null) :
                        if ($entity->getCostCenter() !== null) :
                            if ($entity->getCostCenter()->getId() == $cc->getId()) :
                                echo '<option selected value="' . $cc->getId() . '">' . $cc->getCostCenterName() . '</option>';
                            else :
                                echo '<option value="' . $cc->getId() . '">' . $cc->getCostCenterName() . ' - ' . $cc->getDescription() . '</option>';
                            endif;
                        else :
                            echo '<option value="' . $cc->getId() . '">' . $cc->getCostCenterName() . ' - ' . $cc->getDescription() . '</option>';
                        endif;
                    else :
                        echo '<option value="' . $cc->getId() . '">' . $cc->getCostCenterName() . ' - ' . $cc->getCostCenterName() . '</option>';
                    endif;
                endforeach
                ;
   	    							endif;

            ?>
   					</select>
								</div>
						</div>
						
						

						<div class="form-group margin-bottom">
							<label class="control-label col-sm-2">Remark:</label>
							<div class="col-sm-3">
								<input tabindex="11" class="form-control input-sm" type="text"
									placeholder="" name="remarks"
									value="<?php echo (!$entity == null)? $entity->getRemarks():"";?>">
							</div>
						</div>

				
										<div class="form-group margin-bottom">
			<label class="control-label col-sm-2">Description:</label>
				<div class="col-sm-4">
					<textarea class="form-control input-sm" type="text" rows="5"
						placeholder="" name="descriptionText" style="font-size: 9pt;"><?php echo (!$entity == null)? $entity->getDescriptionText():"";?></textarea>
				</div>
			</div>
			<hr style="margin: 5pt 1pt 5pt 1pt">
		

						<div class="form-group margin-bottom" style="margin-top: 5pt">
							<label class="control-label col-sm-2" for="inputTag"></label>
							<div class="col-sm-3">
								<a tabindex="10" class="btn btn-default btn-sm"
									onclick="submitForm('New_Invoice_Row');" href="javascript:;"><small><i
										class="glyphicon glyphicon-floppy-disk"></i></small>&nbsp;Save</a>
								<a tabindex="11" class="btn btn-default btn-sm"
									href="<?php echo $this->baseUrl ?>/finance/v-invoice/show?token=<?php echo (!$target == null)? $target->getToken():"";?>&entity_id=<?php echo (!$target == null)? $target->getId():"";?>"><small><i
										class="glyphicon glyphicon-remove"></i></small>&nbsp;Cancel</a>
							</div>
							<div class="col-sm-3">					
	
					<?php if($active_row>0):?>
					<a style="color: white;" class="btn btn-primary btn-sm"
									href="<?php echo $this->baseUrl ?>/finance/v-invoice/review?token=<?php echo (!$target == null)? $target->getToken():"";?>&entity_id=<?php echo (!$target == null)? $target->getId():"";?>"><?php echo $this->translate("Review & Post");?>&nbsp;<i
									class="fa fa-chevron-right" aria-hidden="true"></i> </a>
					<?php endif;?>				
									</div>


						</div>
					</form>

				</div>

				<!-- end tab -->
			</div>
		</div>
	</div>
	<!-- /#page-content-wrapper -->

</div>
<!-- /#wrapper -->



<script type="text/javascript">

	$("#Create_Inv_Form :input").attr("disabled", "disabled");

	// focus on 
    $( "#pr_item_name" ).focus();  
	
	// search pr item
    $( "#pr_item_name" ).autocomplete({
        source: "/procure/pr-search/auto-complete",
        minLength: 2,
        select: function( event, ui ) {

      	   	$( "#gl_account_id" ).val("");
      	   	$( "#cost_center_id").val("");
             
            $( "#pr_row_id" ).val(ui.item.pr_row_id);
            $( "#quantity" ).val(ui.item.row_quantity);
            $( "#item_id" ).val(ui.item.item_id);
            $( "#item_name" ).val(ui.item.item_name);

            $('#item_url').text('/inventory/item/show1?tab_idx=11&entity_id='+ui.item.item_id+'&token='+ui.item.item_token);
            $('#pr_row_url').text('/procure/pr-row/show1?entity_id='+ui.item.pr_row_id+'&token='+ui.item.token);

            $('#rowUnit').val(ui.item.row_unit);
            $('#pr_row_uom').text(ui.item.row_unit +' = ' + ui.item.row_conversion_factor);
             	 
            
             //alert(ui.item.item_id);
            $('#global-notice').show();
            $('#global-notice').html('"' + ui.item.item_name + '" selected');
            $('#global-notice').fadeOut(5000);
        	$('#item_detail').show();
         	$('#pr_row_detail').show();
            
         	$( "#quantity" ).focus();

         	// update GL account and cost center
         	if(ui.item.inventory_account_id !==null){
             	// update GL account and cost center
         	   	$( "#gl_account_id" ).val(ui.item.inventory_account_id);
          	}

         // update GL account and cost center
         	if(ui.item.cost_center_id !==null){
             	// update GL account and cost center
         	   	$( "#cost_center_id").val(ui.item.cost_center_id);
          	}		

         	
        }
        })
        .autocomplete( "instance" )._renderItem = function( ul, item ) {
        return $( "<li>" )
    .append( "<div style='padding-bottom: 15px; border-bottom: thin solid gray;'><span style='font-size: 9.5pt;font-weight: bold;'>" + item.item_sku_key  +  " | " + item.item_name + " | Q'ty: " + item.row_quantity + 
                  "</span><br><span style='padding-top: 7px;color:gray;font-size: 9pt;'>" + item.pr_number + " | " + item.row_name +"<span></div>" )
  
 //         .append( "<div style='padding-bottom: 5px; border-bottom: thin solid gray;color:gray;font-size: 9.5pt;'>" + item.pr_number + "<br><span style='color:black;font-size: 9.5pt;'>" + item.item_sku_key  +  " | " + item.item_name + " | Q'ty: " + item.row_quantity + "<span></div>" )
          .appendTo( ul );
        };	


    	// search po item
        $( "#po_item_name" ).autocomplete({
            source: "/procure/po-search/auto-complete?vendor_id=<?php echo $target->getVendor()->getId();?>",
            minLength: 2,
            select: function( event, ui ) {

        	   	$( "#gl_account_id" ).val("");
          	   	$( "#cost_center_id").val("");
          	 	$( "#docUnitPrice").val("");
                
         
                
                $( "#po_row_id" ).val(ui.item.po_row_id);
                $( "#quantity" ).val(ui.item.row_quantity);
                $( "#docUnitPrice" ).val(ui.item.row_unit_price);
                
                $( "#item_id" ).val(ui.item.item_id);
                $( "#item_name" ).val(ui.item.item_name);

                

                $('#item_url').text('/inventory/item/show1?tab_idx=11&entity_id='+ui.item.item_id+'&token='+ui.item.item_token);
                $('#po_row_url').text('/procure/po-row/show1?entity_id='+ui.item.po_row_id+'&token='+ui.item.token);

                $('#rowUnit').val(ui.item.row_unit);
                $('#po_row_uom').text(ui.item.row_unit +' = ' + ui.item.row_conversion_factor);
                 	 
                
                 //alert(ui.item.item_id);
                $('#global-notice').show();
                $('#global-notice').html('"' + ui.item.item_name + '" selected');
                $('#global-notice').fadeOut(5000);
            	$('#item_detail').show();
             	$('#pr_row_detail').show();
                
             	$( "#quantity" ).focus();


             	// update GL account and cost center
             	if(ui.item.inventory_account_id !==null){
                 	// update GL account and cost center
             	   	$( "#gl_account_id" ).val(ui.item.inventory_account_id);
              	}

             // update GL account and cost center
             	if(ui.item.cost_center_id !==null){
                 	// update GL account and cost center
             	   	$( "#cost_center_id").val(ui.item.cost_center_id);
              	}		
            }
            })
            .autocomplete( "instance" )._renderItem = function( ul, item ) {
            return $( "<li>" )
        .append( "<div style='padding-bottom: 15px; border-bottom: thin solid gray;'><span style='font-size: 9.5pt;font-weight: bold;'>"  + item.item_sku_key  +  " | " + item.item_name + " | Q'ty: " + item.row_quantity + 
                      "</span><br><span style='padding-top: 7px;color:gray;font-size: 9pt;'>"+ item.vendor_name +'<br>' + item.po_number + " | " + item.row_identifer_keyword  + " | " + item.manufacturer_code_key +"<span></div>" )
      
     //         .append( "<div style='padding-bottom: 5px; border-bottom: thin solid gray;color:gray;font-size: 9.5pt;'>" + item.pr_number + "<br><span style='color:black;font-size: 9.5pt;'>" + item.item_sku_key  +  " | " + item.item_name + " | Q'ty: " + item.row_quantity + "<span></div>" )
              .appendTo( ul );
            };	
            

    // search item
    $( "#item_name" ).autocomplete({
        source: "/inventory/item-search/auto-complete",
        minLength: 2,
        select: function( event, ui ) {
      	  $( "#item_id" ).val(ui.item.id);      	  
          $('#item_url').text('/inventory/item/show1?tab_idx=11&entity_id='+ui.item.id+'&token='+ui.item.token);
          
      	 	$('#global-notice').show();
      		$('#global-notice').html('"' + ui.item.value + '" selected');
      		$('#global-notice').fadeOut(5000);
      		//$("#jquery_dialog").dialog("close");

      	  	$('#item_detail').show();
      	    $( "#quantity" ).focus();

      	// update GL account and cost center
       	if(ui.item.inventory_account_id !==null){
           	// update GL account and cost center
       	   	$( "#gl_account_id" ).val(ui.item.inventory_account_id);
        	}

       // update GL account and cost center
       	if(ui.item.cost_center_id !==null){
           	// update GL account and cost center
       	   	$( "#cost_center_id").val(ui.item.cost_center_id);
        	}		
      	  
        }
       
      })
      .autocomplete( "instance" )._renderItem = function( ul, item ) {
    	  var serial_no = "";
    	  if(item.item_serial!=""){
    		  serial_no = " : " + item.item_serial;
    	  }
    	   
         return $( "<li>" )
           .append( "<div style='padding-bottom: 5px; border-bottom: thin solid gray;'><span style='font-size: 9.5pt;font-weight: bold;'>" + item.value + "</span><br><span style='color:gray;font-size: 9pt;'>" + item.item_sku + serial_no +"<span></div>" )
           .appendTo( ul );
       };

    $('#quantity').bind('change', function() {
       	$('#net_amount').val($('#docUnitPrice').val() * $('#quantity').val());
       	$('#gross_amount').val($('#net_amount').val()*1 + $('#tax_amount').val()*1);

    });

    $('#docUnitPrice').bind('change', function() {
    	$('#net_amount').val($('#docUnitPrice').val() * $('#quantity').val());
    	$('#gross_amount').val($('#net_amount').val()*1 + $('#tax_amount').val()*1);	
    });

    $('#tax_rate').bind('change', function() {
    	$('#tax_amount').val($('#net_amount').val() * $('#tax_rate').val()/100);
    	$('#gross_amount').val($('#net_amount').val()*1 + $('#tax_amount').val()*1);
    });

	$( "input[id='trx_date']").datepicker({ firstDay: 1, dateFormat: 'yy-mm-dd',closeText: 'X',changeMonth: true, changeYear: true});

    $( function() {
         $( "#vendor_name" ).autocomplete({
          source: "/bp/vendor-search/auto-complete",
          minLength: 3,
          select: function( event, ui ) {
        	  $( "#vendor_id" ).val(ui.item.id);
            //alert	( "Selected: " + ui.item.value + " aka " + ui.item.id );
        	  //alert($( "#vendor_id" ).val());
    
        	 	$('#global-notice').show();
        		$('#global-notice').html('"' + ui.item.value + '" selected');
        		$('#global-notice').fadeOut(5000);
        		//$("#jquery_dialog").dialog("close");
          }
          })
          .autocomplete( "instance" )._renderItem = function( ul, item ) {
          return $( "<li>" )
            .append( "<div style='padding-bottom: 5px; border-bottom: thin solid gray;'>" + item.value + "<br><span style='color:gray;font-size: 9pt;'>" + item.vendor_country + "<span></div>" )
            .appendTo( ul );
        };
          ;
     } );

    function showSelectedItem(){
		var url= $('#item_url').text(); 
	   	showJqueryDialog('Item Detail','1550',$(window).height()-40, url,'j_loaded_data', true);
	}

    function showSelectedPrRow(){
		var url= $('#pr_row_url').text();
	   	showJqueryDialog('PR Row Detail','1550',$(window).height()-40, url,'j_loaded_data', true);
	}

	<?php
    if ($entity != null) :
    if ($entity->getItem() != null) :
        ?>

	  $("#item_id" ).val(<?php echo +$entity->getItem()->getId();?>);      	  
      $('#item_url').text('/inventory/item/show1?tab_idx=11&entity_id=<?php echo +$entity->getItem()->getId();?>&token=<?php echo $entity->getItem()->getToken();?>');
	  $('#item_detail').show();
	    

	<?php
	endif;
	endif;


?>

 </script>