<?php

/**@var \Application\Entity\FinVendorInvoice $target ;
 @var \Application\Entity\FinVendorInvoiceRow $entity ;
 */
?>


<div id="wrapper" class="toggled">

	<!-- Sidebar -->
	<div id="sidebar-wrapper" style="font-size: 9.5pt;">
	
					<?php
    $current_step = "STEP2";
    include (ROOT . '/module/Finance/view/finance/ap-create-wizard.php');
    ?>
  		

	</div>
	<!-- /#sidebar-wrapper -->

	<!-- Page Content -->
	<div id="page-content-wrapper"
		style="font-size: 9.5pt; padding: 0px; margin: 0px;">
		<div class="container-fluid" id="main_container"
			style="font-size: 9.5pt; padding: 1px; margin: 0px;";>
			<a style="font-size: 9pt; margin: 2px; padding: 3px;"
				href="#menu-toggle" class="btn btn-primary btn-sm" id="menu-toggle"><span
				title="Hide Menu"><i class="fa fa-chevron-left" aria-hidden="true"></i>
					Menu <span></a>


			<div id="tabs" style="font-size: 10pt">
				<ul>
					<li><a href="#general"><?php echo $this->translate("New AP Invoice");?></a></li>
				</ul>

				<div id="general" style="font-size: 9pt">
					<!-- Tab1 -->
	
	<?php
if (count($errors) > 0) {
    echo '<div class="alert alert-danger alert-dismissible" role="alert" style="font-size: 9.5pt"> <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>[ERROR]';

    echo '<ul>';
    foreach ($errors as $error) :
        echo '<li>' . $error . '</li>';
    endforeach
    ;
    echo '</ul>';
    echo '</div>';
}
?>
	
				<form id="Create_Inv_Form" class="form-horizontal"
						action="/finance/v-invoice/add" method="post"
						enctype="multipart/form-data">
						<input type="hidden" name="redirectUrl"
							value="<?php echo $redirectUrl ?>" />

						<fieldset>
							<legend style="font-size: 9pt; color: gray;">
								<small><span class="glyphicon glyphicon-triangle-right"></span></small>&nbsp;
								<a href="#invoice_header" class="" data-toggle="collapse">INVOICE
									HEADER:</a>
							</legend>

							<div id="invoice_header" class="collapse">


								<div class="form-group margin-bottom required">
									<label class="control-label col-sm-2 ">Vendor:</label>
									<div class="col-sm-3">
										<input class="form-control input-sm input-sm" type="text"
											id="vendor_name_1" placeholder="Enter term to search vendor"
											name="vendor_name"
											value="<?php if (!$target == null): if (!$target->getVendor() == null):echo $target->getVendor()->getVendorName();endif;endif;?>">

										<input type="hidden" id="vendor_id" placeholder=""
											name="vendor_id"
											value="<?php if (!$target == null): if (!$target->getVendor() == null):echo $target->getVendor()->getId();endif;endif;?>">
									</div>
									<div class="col-sm-3">

										<input
											<?php if(!$target== null): echo ($target->getIsActive()=="1")?"checked":""; else: echo "checked"; endif;?>
											type="checkbox" name="isActive" value="1">&nbsp;Is
										Active&nbsp;&nbsp;&nbsp;&nbsp;

									</div>
									<div class="col-sm-3">

										<a target="blank" style="font-size: 9pt;"
											href="/bp/vendor/list">Vendor List&nbsp;&nbsp;</a><small><i
											class="glyphicon glyphicon-new-window"></i></small>
									</div>
								</div>

								<div class="form-group margin-bottom required">
									<label class="control-label col-sm-2">Invoice number:</label>
									<div class="col-sm-3">
										<input class="form-control input-sm" type="text"
											placeholder="Please enter invoice number!" id="invoiceNo"
											name="invoiceNo"
											value="<?php echo (!$target == null)? $target->getInvoiceNo():"";?>">
									</div>
									<label class="control-label col-sm-2">SAP Document No.:</label>
									<div class="col-sm-3">
										<input class="form-control input-sm" type="text"
											placeholder="" id="sapDoc" name="sapDoc"
											value="<?php echo (!$target == null)? $target->getSapDoc():"";?>">
									</div>
								</div>
								<div class="form-group margin-bottom required">

									<label class="control-label col-sm-2 required">Invoice Date:</label>
									<div class="col-sm-3">
										<input class="form-control input-sm input-sm" type="text"
											id="invoiceDate" name="invoiceDate"
											value="<?php if(!$target == null): if ($target->getInvoiceDate() !== null): echo date_format($target->getInvoiceDate(),"Y-m-d"); endif; endif;?>"
											placeholder=" please select" />
									</div>
								</div>
								<div class="form-group margin-bottom required">

									<label class="control-label col-sm-2">Currency:</label>
									<div class="col-sm-3">
										<select name="currency_id" class="form-control">
											<option value="">Select Currency</option>
   	    							<?php
            if ($currency_list !== null) :
                foreach ($currency_list as $curr) :
                    if ($target !== null) :
                        if ($target->getCurrency() !== null) :
                            if ($target->getCurrency()->getCurrency() == $curr->getCurrency()) :
                                echo '<option selected value="' . $curr->getId() . '">' . $curr->getCurrency() . '</option>';
                            else :
                                echo '<option value="' . $curr->getId() . '">' . $curr->getCurrency() . '</option>';
                            endif;
                        else :
                            echo '<option value="' . $curr->getId() . '">' . $curr->getCurrency() . '</option>';
                        endif;
                    else :
                        echo '<option value="' . $curr->getId() . '">' . $curr->getCurrency() . '</option>';
                    endif;
                endforeach
                ;
   	    							endif;

            ?>
   					</select>
									</div>



									<div class="form-group margin-bottom required">

										<label class="control-label col-sm-2">Good Receipt Date:</label>
										<div class="col-sm-3">
											<input class="form-control input-sm input-sm" type="text"
												id="grDate" name="grDate"
												value="<?php if(!$target == null): if ($target->getGrDate() !== null): echo date_format($target->getGrDate(),"Y-m-d"); endif; endif;?>"
												placeholder=" please select" />
										</div>
										<label class="control-label col-sm-2" for="inputTag">Target
											Warehouse:</label>
										<div class="col-sm-3">
											<input class="form-control" readonly type="text"
												id="target_wh_name" placeholder="Please select!"
												name="target_wh"
												value="<?php if (!$target == null): if (!$target->getWarehouse() == null):echo $target->getWarehouse()->getWhName();endif;endif;?>">
											<input type="hidden" id="target_wh_id" name="target_wh_id"
												value="<?php if (!$target == null): if (!$target->getWarehouse() == null):echo $target->getWarehouse()->getId();endif;endif;?>" />
										</div>
									</div>

									<div class="form-group margin-bottom">
										<label class="control-label col-sm-2">Description</label>
										<div class="col-sm-8">
											<input class="form-control input-sm" type="text"
												placeholder="" name="remarks"
												value="<?php echo (!$target == null)? $target->getRemarks():"";?>">
										</div>
									</div>
									<br>
									<div class="form-group margin-bottom">
										<label class="control-label col-sm-2" for="inputTag"></label>
										<div class="col-sm-3">
											<a class="btn btn-default"
												href="<?php echo $this->baseUrl ?>/finance/v-invoice/edit?token=<?php echo (!$target == null)? $target->getToken():"";?>&entity_id=<?php echo (!$target == null)? $target->getId():"";?>"><small><i
													class="glyphicon glyphicon-pencil"></i></small>&nbsp;Edit</a>
										</div>
									</div>
								</div>
						
						</fieldset>

					</form>

					<form id="New_Invoice_Row" class="form-horizontal"
						action="<?php echo $this->baseUrl ?>/finance/v-invoice-row/edit"
						method="post" enctype="multipart/form-data">
						<input type="hidden" name="redirectUrl"
							value="<?php echo $redirectUrl ?>" /> <input type="hidden"
							id="entity_id" name="entity_id"
							value="<?php if (!$entity == null): echo $entity->getId();endif;?>" />
						<input type="hidden" id="token" name="token"
							value="<?php if (!$entity == null): echo $entity->getToken();endif;?>" />
						<input type="hidden" name="n" value="<?php echo $n;?>" />


						<fieldset>
							<legend style="font-size: 9pt; color: gray;">
								<small><span class="glyphicon glyphicon-triangle-right"></span></small>&nbsp;
								<a href="#new_row" class="" data-toggle="collapse">NEW INVOICE
									ROW:</a>
							</legend>
							<div id="new_row" class="collapse in">
								<div class="form-group margin-bottom">
									<label class="control-label col-sm-2"></label>
									<div class="col-sm-3">
										<input id="is_active"
											<?php if(!$entity== null): echo ($entity->getIsActive()=="1")?"checked":""; else: echo "checked"; endif;?>
											type="checkbox" name="isActive" value="1">&nbsp;Is
										Active&nbsp;&nbsp;&nbsp;&nbsp;
									</div>
								</div>
								<div class="form-group margin-bottom">
									<label class="control-label col-sm-2">Row Number: </label>
									<div class="col-sm-1">
										<input tabindex="0" class="form-control input-sm" type="text"
											id="rowNumber" name="rowNumber"
											value="<?php if (!$entity== null): echo $entity->getRowNumber(); endif;?>">
									</div>
									<div class="col-sm-3" style="color: gray">
				<?php echo 'Current State:'. strtoupper($entity->getCurrentState());?>
		</div>
								</div>

								<div class="form-group margin-bottom">
									<label class="control-label col-sm-2">PR Item: </label>
									<div class="col-sm-3">
										<input tabindex="1" class="form-control input-sm" type="text"
											id="pr_item_name" placeholder="Select PR item"
											name="pr_item_name"
											value="<?php if (!$entity== null): if($entity->getPrRow()!==null): echo $entity->getPrRow()->getId(); endif;endif;?>">
										<input type="hidden" id="pr_row_id" placeholder=""
											name="pr_row_id"
											value="<?php if (!$entity== null): if($entity->getPrRow()!==null): echo $entity->getPrRow()->getId(); endif;endif;?>">

										<div id="pr_row_url" style="display: none;"></div>


									</div>

									<div class="col-sm-1">

										<span title="<?php echo $this->translate("Line Detail");?>"
											id="pr_row_detail" style="display: none;"> &nbsp;&nbsp;<a
											style="color: #0080ff;" href="javascript:;"
											onclick="showSelectedPrRow();"><i style="color: navy"
												class="fa fa-info-circle fa-lg" aria-hidden="true"></i></a>
										</span>
									</div>

									<div class="col-sm-2">
										<a tabindex="100" style="color: #0080ff;" href="javascript:;"
											onclick="showJqueryDialog('Select PR Row','1000',$(window).height()-100, '/procure/pr-search/do1?target_id=pr_row_id&target_name=pr_item_name','j_loaded_data', true);">Select&nbsp;&nbsp;<i
											class="glyphicon glyphicon-folder-open"></i>
										</a>
									</div>

									<div class="col-sm-3">
										<a tabindex="101" target="_blank" style="font-size: 9pt;"
											href="/procure/pr-row/all">PR Item List&nbsp;&nbsp;</a><small><i
											class="glyphicon glyphicon-new-window"></i></small>
									</div>
								</div>

								<div class="form-group margin-bottom  required">
									<label class="control-label col-sm-2">Item: </label>
									<div class="col-sm-3">
										<input tabindex="2" class="form-control" type="text"
											id="item_name" placeholder="Enter keyword to search item..."
											name="item_name"
											value="<?php if (!$entity== null): if($entity->getItem()!==null): echo $entity->getItem()->getItemName(); endif;endif;?>">


										<input type="hidden" id="item_id" placeholder=""
											name="item_id"
											value="<?php if (!$entity== null): if($entity->getItem()!==null): echo $entity->getItem()->getID(); endif;endif;?>">

										<div id="item_url" style="display: none;"></div>


									</div>

									<div class="col-sm-1" style="margin: 0px">
										<span title="<?php echo $this->translate("Item Detail");?>"
											id="item_detail" style="display: none;"> &nbsp;&nbsp;<a
											style="color: #0080ff;" href="javascript:;"
											onclick="showSelectedItem();"><i style="color: navy"
												class="fa fa-info-circle fa-lg" aria-hidden="true"></i> </a>
											<br>
										</span>
									</div>

									<div class="col-sm-2">
										<a style="color: #0080ff;" href="javascript:;"
											onclick="showJqueryDialog('Select Item','1000',$(window).height()-100, '/inventory/item-search/do1?target_id=item_id&target_name=item_name','j_loaded_data', true);">Select&nbsp;&nbsp;<i
											class="glyphicon glyphicon-folder-open"></i>
										</a>

									</div>
									<div class="col-sm-3">
										<a target="_blank" style="font-size: 9pt;"
											href="/inventory/item/list">Item List&nbsp;&nbsp;</a><small><i
											class="glyphicon glyphicon-new-window"></i></small>
									</div>
								</div>
								<div class="form-group margin-bottom">
									<label class="control-label col-sm-2" for="inputTag">Vendor
										Item Code:</label>
									<div class="col-sm-3">
										<input tabindex="3" class="form-control input-sm" type="text"
											id="vendor_item_code" name="vendorItemCode"
											value="<?php echo (!$entity == null)? $entity->getVendorItemCode():"";?>">
									</div>
								</div>


								<div class="form-group margin-bottom required">

									<label class="control-label col-sm-2"><?php echo $this->translate("GL Account");?>:</label>
									<div class="col-sm-3">
										<select name="gl_account_id" class="form-control input-sm">
											<option value=""><?php echo $this->translate("Select GL Account");?></option>
   	    							<?php
            if ($gl_list !== null) :
                foreach ($gl_list as $gl) :

                    /**@var \Application\Entity\FinAccount $gl ; */

                    if ($entity !== null) :
                        if ($entity->getGlAccount() !== null) :
                            if ($entity->getGlAccount()->getId() == $gl->getId()) :
                                echo '<option selected value="' . $gl->getId() . '">' . $gl->getAccountNumber() . '</option>';
                            else :
                                echo '<option value="' . $gl->getId() . '">' . $gl->getAccountNumber() . '-' . $gl->getDescription() . '</option>';
                            endif;
                        else :
                            echo '<option value="' . $gl->getId() . '">' . $gl->getAccountNumber() . '-' . $gl->getDescription() . '</option>';
                        endif;
                    else :
                        echo '<option value="' . $gl->getId() . '">' . $gl->getAccountNumber() . '-' . $gl->getDescription() . '</option>';
                    endif;
                endforeach
                ;
   	    							endif;

            ?>
   					</select>
									</div>


									<label class="control-label col-sm-2" for="inputTag"><?php echo $this->translate("Cost Center");?>:</label>
									<div class="col-sm-3">
										<select name="cost_center_id" class="form-control input-sm">
											<option value=""><?php echo $this->translate("Select Cost Center");?></option>
   	    							<?php
            if ($cost_center_list !== null) :
                foreach ($cost_center_list as $cc) :

                    /**@var \Application\Entity\FinCostCenter $cc ; */

                    if ($entity !== null) :
                        if ($entity->getCostCenter() !== null) :
                            if ($entity->getCostCenter()->getId() == $cc->getId()) :
                                echo '<option selected value="' . $cc->getId() . '">' . $cc->getCostCenterName() . '</option>';
                            else :
                                echo '<option value="' . $cc->getId() . '">' . $cc->getCostCenterName() . ' - ' . $cc->getDescription() . '</option>';
                            endif;
                        else :
                            echo '<option value="' . $cc->getId() . '">' . $cc->getCostCenterName() . ' - ' . $cc->getDescription() . '</option>';
                        endif;
                    else :
                        echo '<option value="' . $cc->getId() . '">' . $cc->getCostCenterName() . ' - ' . $cc->getCostCenterName() . '</option>';
                    endif;
                endforeach
                ;
   	    							endif;

            ?>
   					</select>
									</div>

								</div>

								<div class="form-group margin-bottom required">
									<label class="control-label col-sm-2" for="inputTag">Unit:</label>
									<div class="col-sm-3">
										<input tabindex="4" class="form-control input-sm" type="text"
											name="unit"
											value="<?php echo (!$entity == null)? $entity->getUnit():"";?>">
									</div>
									<label class="control-label col-sm-2" for="inputTag">Converstion
										Factor:</label>
									<div class="col-sm-3">
										<input tabindex="5" class="form-control input-sm" type="text"
											name="conversionFactor"
											value="<?php echo (!$entity == null)? $entity->getConversionFactor():"";?>">
									</div>

								</div>
								<div class="form-group margin-bottom required">
									<label class="control-label col-sm-2" for="inputTag">Quantity:</label>
									<div class="col-sm-3">
										<input tabindex="6" class="form-control input-sm" type="text"
											id="quantity" name="quantity"
											value="<?php echo (!$entity == null)? $entity->getQuantity():"";?>">
									</div>
									<label class="control-label col-sm-2" for="inputTag"></label>

									<div class="col-sm-4">
               		<?php
                $sn_url = "";
                if ($entity->getItem() !== null) :
                    $sn_url = sprintf('/inventory/serial-number/assign?token=%s&target_id=%s&n=%s', $entity->getItem()->getToken(), $entity->getItem()->getId(), $entity->getQuantity());
               		endif;

                ?>	
               
 					<a style="color: white;" tabindex=""
											class="btn btn-primary btn-sm" href="<?php echo $sn_url;?>">Assign
											Serial No.</a>
									</div>

								</div>

								<div class="form-group margin-bottom required">
									<label class="control-label col-sm-2" for="inputTag">Unit
										Price:</label>
									<div class="col-sm-3">
										<input tabindex="7" class="form-control input-sm" type="text"
											id="unit_price" name="unitPrice"
											value="<?php echo (!$entity == null)? $entity->getUnitPrice():"";?>">

									</div>
									<div class="col-sm-3">
         	        		<?php if (!$target == null): echo $target->getCurrency()->getCurrency(); endif;?>
          </div>
								</div>
								<div class="form-group margin-bottom required">
									<label class="control-label col-sm-2" for="inputTag">Net
										Amount:</label>
									<div class="col-sm-3">
										<input readonly class="form-control input-sm" type="text"
											id="net_amount" name="netAmount"
											value="<?php echo (!$entity == null)? $entity->getNetAmount():"";?>">

									</div>
									<div class="col-sm-3">
         	        		<?php if (!$target == null): echo $target->getCurrency()->getCurrency(); endif;?>
          </div>
								</div>
								<div class="form-group margin-bottom required">
									<label class="control-label col-sm-2" for="inputTag">Tax Rate:</label>
									<div class="col-sm-3">
										<input tabindex="8" class="form-control input-sm" type="text"
											id="tax_rate" name="taxRate"
											value="<?php echo (!$entity == null)? $entity->getTaxRate():"";?>">
									</div>
									<label class="control-label col-sm-2" for="inputTag">Tax
										Amount:</label>
									<div class="col-sm-3">
										<input readonly class="form-control input-sm" type="text"
											id="tax_amount" name="taxAmount"
											value="<?php echo (!$entity == null)? $entity->getTaxAmount():"";?>">
									</div>
								</div>

								<div class="form-group margin-bottom required">
									<label class="control-label col-sm-2" for="inputTag">Gross
										Amount:</label>
									<div class="col-sm-3">
										<input readonly class="form-control input-sm" type="text"
											id="gross_amount" name="grossAmount"
											value="<?php echo (!$entity == null)? $entity->getGrossAmount():"";?>">

									</div>
									<div class="col-sm-3">
         	        		<?php if (!$target == null): echo $target->getCurrency()->getCurrency(); endif;?>
          </div>
								</div>
								<div class="form-group margin-bottom">
									<label class="control-label col-sm-2">Remarks:</label>
									<div class="col-sm-8">
										<input tabindex="9" class="form-control input-sm" type="text"
											placeholder="" name="remarks" id="remarks"
											value="<?php echo (!$entity == null)? $entity->getRemarks():"";?>">
									</div>
								</div>

								<hr>
								<div class="form-group margin-bottom">
									<label class="control-label col-sm-2" for="inputTag"></label>
									<div class="col-sm-3">
										<a tabindex="10" class="btn btn-default btn-sm"
											onclick="submitForm('New_Invoice_Row');" href="javascript:;"><small><i
												class="glyphicon glyphicon-floppy-disk"></i></small>&nbsp;Save</a>
										<a tabindex="11" class="btn btn-default btn-sm"
											href="<?php echo $this->baseUrl ?>/finance/v-invoice/review?token=<?php echo (!$target == null)? $target->getToken():"";?>&entity_id=<?php echo (!$target == null)? $target->getId():"";?>"><small><i
												class="glyphicon glyphicon-remove"></i></small>&nbsp;Cancel</a>

									</div>
								</div>

							</div>
						</fieldset>
					</form>


				</div>

				<!-- end tab -->
			</div>
		</div>
	</div>
	<!-- /#page-content-wrapper -->

</div>
<!-- /#wrapper -->



<script type="text/javascript">
	
    
    
$( "#pr_item_name" ).autocomplete({
    source: "/procure/pr-search/auto-complete",
    minLength: 2,
    select: function( event, ui ) {
        $( "#pr_row_id" ).val(ui.item.pr_row_id);
        $( "#quantity" ).val(ui.item.row_quantity);
        $( "#item_id" ).val(ui.item.item_id);
        $( "#item_name" ).val(ui.item.item_name);

        $('#item_url').text('/inventory/item/show1?tab_idx=7&entity_id='+ui.item.item_id+'&token='+ui.item.item_token);
        $('#pr_row_url').text('/procure/pr-row/show1?entity_id='+ui.item.pr_row_id+'&token='+ui.item.token);
     	 
        
         //alert(ui.item.item_id);
        $('#global-notice').show();
        $('#global-notice').html('"' + ui.item.item_name + '" selected');
        $('#global-notice').fadeOut(5000);
    	$('#item_detail').show();
     	$('#pr_row_detail').show();
        
     	$( "#quantity" ).focus();
    }
    })
    .autocomplete( "instance" )._renderItem = function( ul, item ) {
    return $( "<li>" )
.append( "<div style='padding-bottom: 15px; border-bottom: thin solid gray;'><span style='font-size: 9.5pt;font-weight: bold;'>" + item.item_sku_key  +  " | " + item.item_name + " | Q'ty: " + item.row_quantity + 
              "</span><br><span style='padding-top: 7px;color:gray;font-size: 9pt;'>" + item.pr_number + " | " + item.row_name +"<span></div>" )

//         .append( "<div style='padding-bottom: 5px; border-bottom: thin solid gray;color:gray;font-size: 9.5pt;'>" + item.pr_number + "<br><span style='color:black;font-size: 9.5pt;'>" + item.item_sku_key  +  " | " + item.item_name + " | Q'ty: " + item.row_quantity + "<span></div>" )
      .appendTo( ul );
    };	

    $( "#pr_item_name" ).focus();  
     

$( "#item_name" ).autocomplete({
    source: "/inventory/item-search/auto-complete",
    minLength: 2,
    select: function( event, ui ) {
  	  $( "#item_id" ).val(ui.item.id);      	  
      $('#item_url').text('/inventory/item/show1?tab_idx=7&entity_id='+ui.item.id+'&token='+ui.item.token);
      
  	 	$('#global-notice').show();
  		$('#global-notice').html('"' + ui.item.value + '" selected');
  		$('#global-notice').fadeOut(5000);
  		//$("#jquery_dialog").dialog("close");

  	  	$('#item_detail').show();
  	  $( "#quantity" ).focus();
    }
   
  })
  .autocomplete( "instance" )._renderItem = function( ul, item ) {
	  var serial_no = "";
	  if(item.item_serial!=""){
		  serial_no = " : " + item.item_serial;
	  }
	   
     return $( "<li>" )
       .append( "<div style='padding-bottom: 5px; border-bottom: thin solid gray;'><span style='font-size: 9.5pt;font-weight: bold;'>" + item.value + "</span><br><span style='color:gray;font-size: 9pt;'>" + item.item_sku + serial_no +"<span></div>" )
       .appendTo( ul );
   };



       $('#quantity').bind('change', function() {
          	$('#net_amount').val($('#unit_price').val() * $('#quantity').val());
          	$('#gross_amount').val($('#net_amount').val()*1 + $('#tax_amount').val()*1);

       });

       $('#unit_price').bind('change', function() {
       	$('#net_amount').val($('#unit_price').val() * $('#quantity').val());
       	$('#gross_amount').val($('#net_amount').val()*1 + $('#tax_amount').val()*1);	
       });

       $('#tax_rate').bind('change', function() {
       	$('#tax_amount').val($('#net_amount').val() * $('#tax_rate').val()/100);
       	$('#gross_amount').val($('#net_amount').val()*1 + $('#tax_amount').val()*1);
       });
       
	$( "input[id='trx_date']").datepicker({ firstDay: 1, dateFormat: 'yy-mm-dd',closeText: 'X',changeMonth: true, changeYear: true});

    $( function() {
         $( "#vendor_name" ).autocomplete({
          source: "/bp/vendor-search/auto-complete",
          minLength: 3,
          select: function( event, ui ) {
        	  $( "#vendor_id" ).val(ui.item.id);
            //alert	( "Selected: " + ui.item.value + " aka " + ui.item.id );
        	  //alert($( "#vendor_id" ).val());
    
        	 	$('#global-notice').show();
        		$('#global-notice').html('"' + ui.item.value + '" selected');
        		$('#global-notice').fadeOut(5000);
        		//$("#jquery_dialog").dialog("close");
          }
          })
          .autocomplete( "instance" )._renderItem = function( ul, item ) {
          return $( "<li>" )
            .append( "<div style='padding-bottom: 5px; border-bottom: thin solid gray;'>" + item.value + "<br><span style='color:gray;font-size: 9pt;'>" + item.vendor_country + "<span></div>" )
            .appendTo( ul );
        };
          ;
     } );

    function showSelectedItem(){
		var url= $('#item_url').text(); 
	   	showJqueryDialog('Item Detail','1350',$(window).height()-40, url,'j_loaded_data', true);
	}

    function showSelectedPrRow(){
		var url= $('#pr_row_url').text();
	   	showJqueryDialog('PR Row Detail','1350',$(window).height()-40, url,'j_loaded_data', true);
	}

    <?php
    if ($entity !== null) :
        if ($entity->getItem()!==null):
    		?>

    		  $("#item_id" ).val(<?php echo +$entity->getItem()->getId();?>);      	  
    	      $('#item_url').text('/inventory/item/show1?tab_idx=0&entity_id=<?php echo +$entity->getItem()->getId();?>&token=<?php echo $entity->getItem()->getToken();?>');
    		  $('#item_detail').show();
    		    

    		<?php
    		endif;
    		endif;
    		?>


    		<?php 
    	    		if($entity!==null):
    	    		if($entity->getPrRow()!==null):

    	    		?>

    	    	      $( "#pr_row_id" ).val(<?php echo +$entity->getPrRow()->getId();?>);
    	    	      $('#pr_row_url').text('/procure/pr-row/show1?tab_idx=0&entity_id=<?php echo +$entity->getPrRow()->getId();?>&token=<?php echo $entity->getPrRow()->getToken();?>');
    	    		  $('#pr_row_detail').show();   	    		    

    	    		<?php
    	    		endif;
    	    		endif;
    	    		?>
 </script>