
<form class="form-search"
	action="<?php echo $this->baseUrl ?>/inventory/article/list"
	method="get" enctype="multipart/form-data">
	<button type="submit" class="btn">
		<i class="icon-arrow-left"> </i> Back
	</button>
</form>
<hr>

<h4>Issuing: <?php echo $article->name; ?> </h4>
<hr>

<?php

if (count($errors) > 0) {
    echo '<div class="alert alert-error">';

    echo '<ul>';
    foreach ($errors as $error) :
        echo '<li>' . $error . '</li>';
    endforeach
    ;
    echo '</ul>';
    echo '</div>';
}
?>
	



<?php if ($instock > 0):?>


<form class="form-horizontal"
	action="<?php echo $this->baseUrl ?>/inventory/transaction/gi"
	method="post" enctype="multipart/form-data" id="Issusing">
	<input type="hidden" name="article_id"
		value="<?php echo (int) $article->id; ?>" /> <input type="hidden"
		name="instock" value="<?php echo (int) $instock ?>" /> <input
		type="hidden" name="redirectUrl" value="<?php echo $redirectUrl ?>" />

	<div class="control-group">
		<label class="control-label" for="inputNameLocal">Movement Type: </label>
		<div class="controls">
			<select name="movement_type">
      	    <?php

foreach ($movement_types as $key => $a) :
        echo '<option value="' . $a . '">' . $a . '</option>';
    endforeach
    ;
    ?>   		
   			</select>
		</div>
	</div>

	<div class="control-group">
		<label class="control-label" for="inputName">Issue date:</label>
		<div class="controls">
			<input type="text" name="movement_date" value=""
				placeholder=" please select" id="movement_date" />
		</div>
	</div>

	<div class="control-group">
		<label class="control-label" for="inputNameLocal">Quantity:</label>
		<div class="controls">
			<input type="text" name="quantity"
				value="<?php echo $movement!==null ? ($movement->quantity) :""?>" />
			<span class="label label-info">
			(In stock: <?php echo (int) $instock . ' pcs.'; ?>)</span> <a
				href="javascript:;"
				onclick="showBalance('<?php echo $article->id?>','<?php echo $article->name?>');"
				class="helper">Check Balance <i class=" icon-folder-open"></i></a>

		</div>
	</div>

	<div class="control-group">
		<label class="control-label" for="inputNameLocal">Requester:</label>
		<div class="controls">
			<input type="text" name="requester"
				value="<?php echo $movement!==null ? ($movement->requester) :""?>" />
		</div>
	</div>

	<div class="control-group">
		<label class="control-label" for="inputDescription">Comment:</label>
		<div class="controls">
			<textarea class="form-control" id="inputDescription" placeholder=""
				rows="2" name="comment"><?php echo $movement!==null ? ($movement->comment) :""?></textarea>
		</div>
	</div>

	<div class="control-group">
		<div class="controls">
			<button type="submit" class="btn">
				<i class="icon-minus"> </i> Issue
			</button>
		</div>
	</div>
</form>

<div id="dialog" style="display: none;">No asset found...</div>


<?php

else :

    echo 'Please make order!';
endif;
?>
<div id="dialog1" style="display: none; padding-top: 4pt"></div>
