
 
 <?php echo $this->doctype(); ?>

<html lang="en">
<head>
<meta charset="utf-8">
<?= $this->headTitle('Mascot International Laos')->setSeparator(' - ')->setAutoEscape(false) ?>
<?=$this->headMeta ()->appendName ( 'viewport', 'width=device-width, initial-scale=1.0' )->appendHttpEquiv ( 'X-UA-Compatible', 'IE=edge' )?>

<!-- Le styles -->
<link href="/img/favicon.ico" rel="shortcut icon"
	type="image/vnd.microsoft.icon">

<link href="/bootstrap3/css/bootstrap.min.css" media="screen"
	rel="stylesheet" type="text/css">
<link href="/bootstrap3/css/bootstrap-theme.min.css" media="screen"
	rel="stylesheet" type="text/css">
<link href="/bootstrap3/css/style.css" media="screen" rel="stylesheet"
	type="text/css">


<link href="/css/lightgallery.css" rel="stylesheet" type="text/css">
<link href="/css/lg-transitions.min.css" rel="stylesheet"
	type="text/css">
<link href="/css/jstree/style.css" rel="stylesheet" type="text/css">
<link href="/css/bootstrap-editable.css" rel="stylesheet"
	type="text/css">
<link href="/css/calendar.css" media="screen" rel="stylesheet"
	type="text/css">
<!-- <link href="/css/tables.css" rel="stylesheet"  type="text/css">  -->

<link href="/jquery/jquery-ui.min.css" rel="stylesheet" type="text/css">
<link href="/jquery/jquery-ui.theme.min.css" rel="stylesheet"
	type="text/css">
<link href="/jquery/jquery-ui.structure.min.css" rel="stylesheet"
	type="text/css">


<!--PQ Grid files-->
<link rel="stylesheet" href="/pqgird/css/pqgrid.min.css" />
<link rel="stylesheet" href="/pqselect/pqselect.min.css" />


<!--PQ Grid Office theme-->
<link rel="stylesheet" href="/pqgird/themes/office/pqgrid.css" />
<link rel="stylesheet" href="/awesome-4.7.0/css/font-awesome.min.css">

<style>
.map {
	width: 220px;
	height: 220px;
}

.ui-tooltip {
	max-width: 250px;
}
</style>






<script type="text/javascript" src="/js/jquery.js"></script>
<script type="text/javascript" src="/bootstrap3/js/bootstrap.min.js"></script>


<script type="text/javascript" src="/jquery/jquery-ui.min.js"></script>
<script type="text/javascript" src="/js/exif.js"></script>
<script type="text/javascript" src="/js/lightgallery-all.min.js"></script>
<script type="text/javascript" src="/js/lg-thumbnail.js"></script>
<script type="text/javascript" src="/js/lg-fullscreen.min.js"></script>
<script type="text/javascript" src="/js/Observer.js"></script>

<script type="text/javascript" src="/js/jstree.min.js"></script>
<script type="text/javascript" src="/js/jquery.tabledit.min.js"></script>
<script type="text/javascript" src="/js/bootstrap-editable.min.js"></script>
<script type="text/javascript" src="/js/mla.js"></script>
<script type="text/javascript" src="/js/NMT.js"></script>
<script type="text/javascript" src="/js/mla-hr.js"></script>
<script type="text/javascript" src="/js/mla-proc.js"></script>
<script type="text/javascript" src="/js/nmt-inventory.js"></script>

<script src="/pqgird/js/pqgrid.min.js"></script>
<script src="/pqselect/pqselect.min.js"></script>

<script>


  var timerSubject = new Subject();

  $(function() {
	    $( "input[id='movement_date']").datepicker({ firstDay: 1, dateFormat: 'yy-mm-dd',closeText: 'X'});
   });


  $(function() {
	    $( "input[id='start_date']").datepicker({ firstDay: 1, dateFormat: 'yy-mm-dd',closeText: 'X'});
 });

  $(function() {
	    $( "input[id='end_date']").datepicker({ firstDay: 1, dateFormat: 'yy-mm-dd',closeText: 'X'});
});

  $(function() {
	   // $( "input[type=submit], button" ).button();
  });

  $(function() {
	    $( "#tabs" ).tabs({

	    	beforeLoad:function(e,ui){
	    		$( ui.panel ).html('<p>Loading...</p>');       
	    	    },
	    	   
	    });
	  });
  
  $(function() {
	    $( "#menu" ).menu();
	  });


  $( function() {
	    $( document ).tooltip({
	      items: "img, [item-pic], [title]",
	      content: function() {
	        var element = $( this );
	        if ( element.is( "[item-pic]" ) ) {
	          var text = element.text();
	          var item_id = element.attr("id");
	          var item_name = element.attr("item_name");

	          return "<div style='font-size: 10pt'>"+ item_name +"</div><img class='map' alt='"+ item_id +"' src='/inventory/item/get-picture?item_id=" + item_id +"'><div style='font-size: 10pt'>Click for more detail!</div>";
	        }
	        if ( element.is( "[title]" ) ) {
	          return element.attr( "title" );
	        }
	        if ( element.is( "img" ) ) {
	          return element.attr( "alt" );
	        }
	      }
	    });
	  } );

 

   startTime();
  </script>


</head>
<body>

	<div style="display: none" id="global-notice"></div>

	<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
		<div class="container" style="padding-right: 0px; padding-left: 0px">
			<div class="navbar-header"
				style="padding-right: 0px; padding-left: 0px">
				<button type="button" class="navbar-toggle" data-toggle="collapse"
					data-target=".navbar-collapse">
					<span class="icon-bar"></span> <span class="icon-bar"></span> <span
						class="icon-bar"></span>
				</button>
				<a style="color: #adadad; font-weight: bold;"
					href="<?= $this->url('home') ?>"> <img src="/img/logo.gif"
					height="50" alt="" /></a>
			</div>
			<div class="collapse navbar-collapse">
				<ul class="nav navbar-nav">	
				 
				<?php
    $current_module = "HR";
    include (ROOT . '/module/Application/view/navbar.php');
    ?>
					</ul>

			</div>
		</div>
	</nav>




	<div class="container-fluid" id="main_container">


		<div class="row row-offcanvas row-offcanvas-right">
			<div class="col-xs-12 col-sm-10 col-sm-push-2 ">
				<p class="pull-right visible-xs">
					<button type="button" class="btn btn-primary"
						data-toggle="offcanvas" title="Toggle sidebar">
						<i class="fa fa-chevron-right"></i>
					</button>
				</p>
				<div class="row" style="padding-right: 5px">
      	      <?= $this->content ?>
        	 </div>
				<!--/row-->
			</div>
			<!--/.col-xs-12.col-sm-9-->

			<div class="col-xs-6 col-sm-2 col-sm-pull-10 sidebar-offcanvas"
				id="sidebar" style="font-size: 9.5pt;">
				<h5>
					<strong><?php echo $this->translate('HR MANAGEMENT'); ?></strong>
				</h5>

				<form class="form-inline"
					action="<?php echo $this->baseUrl ?>/hr/employee-search/do"
					method="get" enctype="multipart/form-data">
					<div class="form-group">
						<input
							placeholder="<?php echo $this->translate('search term...'); ?>"
							class="form-control" size="10" type="text" name="q">


					</div>
					<div class="form-group">
						<button type="submit" class="btn btn-default">
							<small><i class="glyphicon glyphicon-search"> </i></small>
						</button>
					</div>

				</form>
			    <?php 
// <-- Update this !!
    echo $this->navigation('hr_navi')
        ->menu()
        ->setMinDepth(0)
        ->setMaxDepth(0)
        ->setUlClass('nav nav-pills nav-stacked')
        ->setPartial('navigation.phtml');
    ?>
        </div>
			<!--/.sidebar-offcanvas-->
		</div>
		<!--/row-->

		<hr>

		<footer> &copy; 2016-2017 Nguyen Mau Tri </footer>

	</div>
	<!--/.container-->

	<div id="flash_messages" class="global-notice" style="display: none;"><?php
if ($this->flashMessenger() !== null) {
    echo $this->flashMessenger()->render();
}
?></div>

	<script>
		var flash_message = $( "#flash_messages" ).text();
		if(flash_message!=''){
			$( "#flash_messages" ).show();
			$( "#flash_messages" ).delay(2200).fadeOut(1000);
		}

		 $('[data-toggle="offcanvas"]').click(function () {
			    $('.row-offcanvas').toggleClass('active')
			  });
		
</script>

	<!-- Modal -->
	<div class="modal" id="modal1" role="dialog">
		<div class="modal-dialog">
			<div class="modal-content">
				<div class="modal-header">
					<button type="button" class="close" data-dismiss="modal">&times;</button>
					<span class="modal-title" id="modal_title"
						style="font-weight: bold;">Mascot International Laos</span>
				</div>
				<div class="modal-body">
					<div id="b_loaded_data">loading</div>
				</div>
				<div class="modal-footer">
					<span id="node_selected"></span>&nbsp;&nbsp;
					<button type="button" class="btn btn-default" data-dismiss="modal">Confirm</button>
				</div>
			</div>
		</div>
	</div>



	<div id="jquery_dialog" style="display: none; padding-top: 10pt">
		<div id="j_loaded_data"></div>
	</div>


	<!-- Modal -->
	<div id="b_modal_no_header" class="modal" role="dialog">
		<div class="modal-dialog">
			<div class="modal-content">
				<div class="modal-body">
					<p>Processing........Please Wait!</p>
				</div>
			</div>
		</div>
	</div>

	<!-- Modal -->
	<div class="modal fade" id="b_modal_sm" role="dialog">
		<div class="modal-dialog modal-sm">
			<div class="modal-content">
				<div class="modal-header">
					<button type="button" class="close" data-dismiss="modal">&times;</button>
					<h5 class="modal-title" id="b_modal_sm_title">Mascot International
						Laos</h5>
				</div>
				<div class="modal-body" id="b_modal_sm_body">
					<p>No attachment selected!</p>
				</div>
				<div class="modal-footer">
					<button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
				</div>
			</div>
		</div>
	</div>


</body>
</html>
