       
	
<h3>Login <i class="fa fa-lock" aria-hidden="true"></i>
</h3>
<?php

if (! $messages == null) {
	echo '<div class="alert alert-danger">';
	
	echo '<ul>';
	foreach ( $messages as $m ) :
		echo '<li>' . $m . '</li>';
	endforeach
	;
	echo '</ul>';
	echo '</div>';
}
?>


<div style="border-color:gray ; border-style:solid; border: 1px; padding-top: 30px; height:300pt; font-size: 10pt; background: url(/images/bg1.png); background-repeat: repeat-x; background-color: #FFFFFF;">      
<form class="form-horizontal"
	action="<?php echo $this->baseUrl ?>/user/auth/authenticate"
	method="post" enctype="multipart/form-data" id="authentication">
   <input type="hidden" name="redirect" value="<?php echo $redirect;?>" />


	<div class="form-group margin-bottom">
		<label class="control-label col-sm-2 sm" for="inputEmail">Email:</label>
		<div class="col-sm-3">
			<input type="text" class="form-control input-sm" id="inputEmail"
				placeholder="Email" name="email">
		</div>
	</div>

	<div class="form-group margin-bottom">
		<label class="control-label col-sm-2 sm" for="inputPassword">Password:</label>
		<div class="col-sm-3">
			<input type="password" class="form-control input-sm" id="inputPassword"
				placeholder="Password" name="password">
		</div>
	</div>
	<div class="form-group margin-bottom">
		<div class="col-sm-offset-2 col-sm-10">
			<button type="submit" class="btn btn-default">Login</button>
		</div>
	</div>
</form>


<!-- 
<hr>
<div class="alert alert-warning">
	<Strong>Info: </Strong>If you're new user, please <a
		href="<?php echo $this->baseUrl ?>/user/index/register">click here</a>
	to register.
</div>
 -->
 </div>
