
<h3>Login</h3>
<?php if (!$messages== null)
{
	echo '<ul style="color:#FF0000">';
	 foreach ($messages as $m) :
	 echo '<li>'.$m . '</li>';
	 
	 endforeach;
	 echo '</ul>';
} 

?>

<form action="<?php echo $this->baseUrl ?>/user/auth/authenticate"	method="post" enctype="multipart/form-data" id="authentication">

<table>

<tr>
	<td><label for="email">Email: </label> </td>
	<td><input type="text"	name="email" value="" /></td>
</tr>


<tr>
	<td><label for="tag">Password: </label> </td>
	<td><input type="password"	name="password" value="" /></td>
</tr>

<tr>
	<td></td> 
	<td><input type="submit" name="login" value="login" />	</td>
</tr>

</table>
 
</form>

<br>
<b>If you're new user, please <a href="<?php echo $this->baseUrl ?>/user/index/register">click here</a> to register.</b>
