<?php
use Application\Application\Helper\OptionHelper;
use Procure\Application\Helper\ErrorMessage;
use Procure\Application\Helper\OptionList;

/**
 *
 * @author Nguyen Mau Tri - ngmautri@gmail.com
 *         ===========================================
 */
/**@var \Procure\Application\DTO\Qr\QrDTO $headerDTO ;*/
/**@var \Procure\Application\DTO\Qr\QrRowDTO $dto ;*/
/**@var \Application\Controller\Plugin\NmtPlugin $nmtPlugin ;*/

// var_dump($headerDTO);

// echo memory_get_usage();
$message_url = null;
$review_url = null;
$rowNumber = null;
$doc_wh_id = null;
$pr_item_name = null;
$docUomName = 'each';
$remove_url = null;
$removeBtn = null;
// var_dump($headerDTO);
if ($headerDTO !== null) {
    $target_id = $headerDTO->getId();
    $target_token = $headerDTO->getToken();

    $message_url = sprintf($this->baseUrl . "/application/message-store/list1?entity_token=%s&entity_id=%s", $target_token, $target_id);
    $review_url = sprintf($this->baseUrl . "/procure/qr/review?entity_id=%s&entity_token=%s", $target_id, $target_token);

    // $add_url = sprintf($this->baseUrl . "/procure/po/add-row?target_id=%s&token=%s", $target_id, $target_token);
    $log_url = sprintf($this->baseUrl . "/application/message-store/list1?entity_id=%s&entity_token=%s", $headerDTO->getId(), $headerDTO->getToken());

    $rowNumber = $headerDTO->getTotalRows() + 1;
    $doc_wh_id = $headerDTO->getWarehouse();
}

$wh_id = null;
$gl_account = null;
$cost_center = null;
if ($dto !== null) {
    $rowNumber = $dto->getRowNumber();
    $wh_id = $dto->getWarehouse();
    $gl_account = $dto->getGlAccount();
    $cost_center = $dto->getCostCenter();
    $pr_item_name = $dto->itemName . ' || ' . $dto->getPrNumber();

    $docUomName = $dto->getDocUnit();
    $remove_url = sprintf($this->baseUrl . "/procure/qr/remove-row?ver=%s&entity_id=%s&entity_token=%s&target_id=%s&target_token=%s", $docRevisionNo, $dto->getId(), $dto->getToken(), $target_id, $target_token);
    $removeBtn = sprintf(' <a class="btn btn-danger btn-sm" style="color: white" onclick="confirmRemoveRow();" href="javascript:;">
     <i class="fa fa-remove" aria-hidden="true"></i> &nbsp;%s</a>', $this->translate("Remove"));
}

if ($wh_id == null) {
    $wh_id = $doc_wh_id;
}

$wh_option = OptionList::createWarehouseOption($nmtPlugin->warehouseList(), $wh_id);
$gl_option = OptionList::createGLAccountOption($nmtPlugin->glAccountList(), $gl_account);
$cost_center_option = OptionList::createCostCenterOption($nmtPlugin->costCenterList(), $cost_center);

$uomList = $sharedCollection->getUomCollection();
$uom_option = OptionHelper::createUomNameOption($uomList, $docUomName);

$error_msg = ErrorMessage::showErrorMessage($errors);

// echo memory_get_usage();
// =====================================================
?>
<div id="wrapper" class="toggled">
   <!-- Sidebar -->
   <div id="sidebar-wrapper" style="font-size: 9.5pt;">

    	<?php
    $current_step = "STEP2";
    include (ROOT . '/module/Procure/view/procure/quote-create-wizard.php');
    include (ROOT . '/module/Procure/view/procure/qr_summary.php');
    ?>


   </div>
   <!-- /#sidebar-wrapper -->
   <!-- Page Content -->
   <div id="page-content-wrapper" style="font-size: 9.5pt; padding: 0px; margin: 0px;">
      <div class="container-fluid" id="main_container" style="font-size: 9.5pt; padding: 1px; margin: 0px;";>
         <a style="font-size: 9pt; margin: 2px; padding: 3px;" href="#menu-toggle" class="btn btn-primary btn-sm" id="menu-toggle">
            <span title="Hide Menu">
               <i class="fa fa-chevron-left" aria-hidden="true"></i>
               Menu
               <span>

         </a>
         <div id="tabs" style="font-size: 10pt">
            <ul>
               <li>
                  <a href="#general"><?php

                echo $form_title;
                ?></a>
               </li>
               <li>
                  <a href="<?php

                echo $log_url;
                ?>">
                     <span class="glyphicon glyphicon-list"></span>
                     &nbsp;Log
                  </a>
               </li>
            </ul>
            <div id="general" style="font-size: 9pt">
               <!-- Tab1 -->

<?php
// ================================
echo $error_msg;
// ===============================
?>

					<form id="New_Invoice_Row" class="form-horizontal" action="<?php

    echo $form_action;
    ?>" method="post" enctype="multipart/form-data">
                  <input type="hidden" name="redirectUrl" value="<?php

                echo $redirectUrl?>" />
                  <input type="hidden" id="target_id" name="target_id" value="<?php

                echo $target_id;
                ?>" />
                  <input type="hidden" id="target_token" name="target_token" value="<?php

                echo $target_token;
                ?>" />
                  <input type="hidden" name="docRevisionNo" value="<?php

                echo $docRevisionNo;
                ?>" />
                  <input type="hidden" id="entity_id" name="entity_id" value="<?php

                echo $entity_id;
                ?>" />
                  <input type="hidden" id="entity_token" name="entity_token" value="<?php

                echo $entity_token;
                ?>" />
                  <div class="form-group margin-bottom">
                     <label class="control-label col-sm-2">Row Number: </label>
                     <div class="col-sm-1">
                        <input tabindex="0" class="form-control input-sm" type="text" id="rowNumber" name="rowNumber" value="<?php

                        echo $rowNumber;
                        ?>">
                     </div>
                     <div class="col-sm-2">
                        <input
                           <?php

                        if (! $dto == null) :
                            echo ($dto->getIsActive() == "1") ? "checked" : "";
                        else :
                            echo "checked";
                        endif;
                        ?>
                           type="checkbox" name="isActive" value="1">
                        &nbsp;Is Active&nbsp;&nbsp;&nbsp;&nbsp;
                     </div>
                  </div>
                  <div class="form-group margin-bottom">
                     <label class="control-label col-sm-2">PR Item: </label>
                     <div class="col-sm-3">
                        <input tabindex="1" class="form-control input-sm" type="text" id="pr_item_name" placeholder="Select PR item" name="pr_item_name" value="<?php
                        echo $pr_item_name;
                        ?>
                        ">
                        <input type="hidden" id="pr_row_id" placeholder="" name="prRow" value="">
                        <div id="pr_row_url" style="display: none;"></div>
                     </div>
                     <div class="col-sm-1">
                        <span title="<?php

                        echo $this->translate("Line Detail");
                        ?>" id="pr_row_detail" style="display: none;">
                           &nbsp;&nbsp;
                           <a style="color: #0080ff;" href="javascript:;" onclick="showSelectedPrRow();">
                              <i style="color: navy" class="fa fa-info-circle fa-lg" aria-hidden="true"></i>
                           </a>
                        </span>
                     </div>
                     <div class="col-sm-1">
                        <a tabindex="100" style="color: #0080ff;" href="javascript:;" onclick="showJqueryDialog('Select PR Row','1000',$(window).height()-100, '/procure/pr-search/do1?target_id=pr_row_id&target_name=pr_item_name','j_loaded_data', true);">
                           Select&nbsp;&nbsp;
                           <i class="glyphicon glyphicon-folder-open"></i>
                        </a>
                     </div>
                     <div class="col-sm-1">
                        <a tabindex="" target="_blank" style="font-size: 9pt;" href="/procure/pr-row/all">PR Item List&nbsp;&nbsp;</a>
                        <small>
                           <i class="glyphicon glyphicon-new-window"></i>
                        </small>
                     </div>
                  </div>
                  <div class="form-group margin-bottom  required">
                     <label class="control-label col-sm-2">Item: </label>
                     <div class="col-sm-3">
                        <input tabindex="2" class="form-control" type="text" id="item_name" placeholder="Enter keyword to search item..." name="itemName"
                           value="<?php

                        if (! $dto == null) :
                            echo $dto->getItemName();endif;

                        ?>">
                        <input type="hidden" id="item" placeholder="" name="item" value="<?php

                        if (! $dto == null) :
                            echo $dto->getItem(); endif;

                        ?>">
                        <div id="item_url" style="display: none;"></div>
                     </div>
                     <div class="col-sm-1" style="margin: 0px">
                        <span title="<?php

                        echo $this->translate("Item Detail");
                        ?>" id="item_detail" style="display: none;">
                           &nbsp;&nbsp;
                           <a style="color: #0080ff;" href="javascript:;" onclick="showSelectedItem();">
                              <i style="color: navy" class="fa fa-info-circle fa-lg" aria-hidden="true"></i>
                           </a>
                           <br>
                        </span>
                     </div>
                     <div class="col-sm-1" style="margin: 0px">
                        <a style="color: #0080ff;" href="javascript:;" onclick="showJqueryDialog('Select Item','1350',$(window).height()-50, '/inventory/item-search/do1?target_id=item_id&target_name=item_name','j_loaded_data', true);">
                           Select&nbsp;&nbsp;
                           <i class="glyphicon glyphicon-folder-open"></i>
                        </a>
                     </div>
                     <div class="col-sm-1">
                        <a target="_blank" style="font-size: 9pt;" href="/inventory/item/list">Item List&nbsp;&nbsp;</a>
                        <small>
                           <i class="glyphicon glyphicon-new-window"></i>
                        </small>
                     </div>
                  </div>
                  <div class="form-group margin-bottom">
                     <label class="control-label col-sm-2" for="inputTag">Vendor Item Name:</label>
                     <div class="col-sm-3">
                        <input tabindex="3" class="form-control input-sm" type="text" id="vendorItemName" name="vendorItemName" value="<?php

                        echo (! $dto == null) ? $dto->getVendorItemName() : "";
                        ?>">
                     </div>
                     <label class="control-label col-sm-2" for="inputTag">Vendor Item Code:</label>
                     <div class="col-sm-3">
                        <input tabindex="3" class="form-control input-sm" type="text" id="vendor_item_code" name="vendorItemCode" value="<?php

                        echo (! $dto == null) ? $dto->getVendorItemCode() : "";
                        ?>">
                     </div>
                  </div>
                  <hr style="margin: 5pt 1pt 5pt 1pt;">
                  <div class="form-group margin-bottom required">
                     <label class="control-label col-sm-2" for="inputTag">Quantity:</label>
                     <div class="col-sm-3">
                        <input tabindex="4" class="form-control input-sm" type="text" id="quantity" name="docQuantity" value="<?php

                        echo (! $dto == null) ? $dto->getDocQuantity() : "";
                        ?>">
                     </div>
                     <div class="col-sm-3">
                        <div style="color: graytext; padding-bottom: 5px;" id="purchase_uom_convert_factor"></div>
                     </div>
                  </div>
                  <hr style="margin: 5pt 1pt 5pt 1pt;">
                  <div class="form-group margin-bottom required">
                     <label class="control-label col-sm-2"><?php

                    echo $this->translate("Document Unit");
                    ?></label>
                     <div class="col-sm-3">
                        <select tabindex="5" name="docUnit" id="docUnit" class="form-control input-sm chosen-select">
                           <option value=""><?php

                        echo $this->translate("Select doc unit");
                        ?></option>
                    <?php
                    echo $uom_option;
                    ?>
               </select>
                     </div>
                     <label class="control-label col-sm-2" for="inputTag">Converstion Factor:</label>
                     <div class="col-sm-1">
                        <input tabindex="6" class="form-control input-sm" type="text" name="standardConvertFactor" id="standardConvertFactor" value="<?php

                        echo (! $dto == null) ? $dto->getStandardConvertFactor() : "1";
                        ?>">
                     </div>
                     <div class="col-sm-3">
                        <span style="color: graytext; padding-bottom: 5px; margin: 0 0 0 10pt; font-size: 8.5pt" id="">Converstion to item standard unit.</span>
                     </div>
                  </div>
                  <hr style="margin: 5pt 1pt 5pt 1pt;">
                  <hr style="margin: 5pt 1pt 5pt 1pt;">
                  <div class="form-group margin-bottom required">
                     <label class="control-label col-sm-2" for="inputTag">Unit Price:</label>
                     <div class="col-sm-3">
                        <input tabindex="7" class="form-control input-sm" type="text" id="unit_price" name="docUnitPrice" value="<?php

                        echo (! $dto == null) ? $dto->getDocUnitPrice() : "";
                        ?>">
                     </div>
                     <div class="col-sm-1" style="margin-left: 0px">
                        <strong><?php

                        if (! $headerDTO == null) :
                            echo $headerDTO->getCurrencyIso3(); endif;

                        ?></strong>
                     </div>
                     <label class="control-label col-sm-1" for="inputTag">Exw Price (info):</label>
                     <div class="col-sm-3">
                        <input tabindex="8" class="form-control input-sm" type="text" id="exw_unit_price" name="exwUnitPrice" value="<?php

                        echo (! $dto == null) ? $dto->getExwUnitPrice() : "";
                        ?>">
                     </div>
                  </div>
                  <div class="form-group margin-bottom required">
                     <label class="control-label col-sm-2" for="inputTag">Discount Rate (%):</label>
                     <div class="col-sm-3">
                        <input class="form-control input-sm" type="text" id="discountRate" name="discountRate" value="<?php

                        echo (! $dto == null) ? $dto->getDiscountRate() : "";
                        ?>">
                     </div>
                  </div>
                  <div class="form-group margin-bottom required">
                     <label class="control-label col-sm-2" for="inputTag">Discount Amount:</label>
                     <div class="col-sm-3">
                        <input readonly="readonly" class="form-control input-sm" type="text" id="discountAmount" name="" discountAmount"" value="<?php

                        echo (! $dto == null) ? $dto->getDiscountAmount() : "";
                        ?>">
                     </div>
                     <div class="col-sm-1">
                        <strong><?php

                        if (! $headerDTO == null) :
                            echo $headerDTO->getCurrencyIso3(); endif;

                        ?></strong>
                     </div>
                  </div>
                  <div class="form-group margin-bottom required">
                     <label class="control-label col-sm-2" for="inputTag">Net Amount:</label>
                     <div class="col-sm-3">
                        <input readonly class="form-control input-sm" type="text" id="net_amount" name="netAmount" value="<?php

                        echo (! $dto == null) ? $dto->getNetAmount() : "";
                        ?>">
                     </div>
                     <div class="col-sm-3">
                        <strong><?php

                        if (! $headerDTO == null) :
                            echo $headerDTO->getCurrencyIso3(); endif;

                        ?></strong>
                     </div>
                  </div>
                  <div class="form-group margin-bottom required">
                     <label class="control-label col-sm-2" for="inputTag">Tax Rate:</label>
                     <div class="col-sm-3">
                        <input tabindex="9" class="form-control input-sm" type="text" id="tax_rate" name="taxRate" value="<?php

                        echo (! $dto == null) ? $dto->getTaxRate() : "0";
                        ?>">
                     </div>
                     <label class="control-label col-sm-2" for="inputTag">Tax Amount:</label>
                     <div class="col-sm-3">
                        <input readonly class="form-control input-sm" type="text" id="tax_amount" name="taxAmount" value="<?php

                        echo (! $dto == null) ? $dto->getTaxAmount() : "";
                        ?>">
                     </div>
                  </div>
                  <div class="form-group margin-bottom required">
                     <label class="control-label col-sm-2" for="inputTag">Gross Amount:</label>
                     <div class="col-sm-3">
                        <input readonly class="form-control input-sm" type="text" id="gross_amount" name="grossAmount" value="<?php

                        echo (! $dto == null) ? $dto->getGrossAmount() : "";
                        ?>">
                     </div>
                     <div class="col-sm-1">
                        <strong><?php

                        if (! $headerDTO == null) :
                            echo $headerDTO->getCurrencyIso3(); endif;

                        ?></strong>
                     </div>
                     <label class="control-label col-sm-1" for="inputTag">Total Exw (info):</label>
                     <div class="col-sm-3">
                        <input readonly tabindex="10" class="form-control input-sm" type="text" id="total_exw_price" name="totalExwPrice" value="<?php

                        echo (! $dto == null) ? $dto->getTotalExwPrice() : "";
                        ?>">
                     </div>
                  </div>
                  <div class="form-group margin-bottom required">
                     <label class="control-label col-sm-2"><?php
                    echo $this->translate("GL Account");
                    ?>:</label>
                     <div class="col-sm-3">
                        <select tabindex="9" name="glAccount" id="glAccount" class="form-control input-sm chosen-select">
                           <option value=""><?php
                        echo $this->translate("Select GL Account");
                        ?></option><?php
                        echo $this->translate("...");
                        ?></option>
<?php
// ================
echo $gl_option;
// ================
?>
                                        </select>
                     </div>
                  </div>
                  <div class="form-group margin-bottom required">
                     <label class="control-label col-sm-2"><?php
                    echo $this->translate("Cost Center");
                    ?>:</label>
                     <div class="col-sm-3">
                        <select tabindex="9" name="costCenter" id="costCenter" class="form-control input-sm chosen-select  ">
                           <option value=""><?php
                        echo $this->translate("Select Cost Center");
                        ?></option>
<?php
// ================
echo $cost_center_option;
// ================
?>
                                        </select>
                     </div>
                  </div>
                  <hr style="margin: 5pt 1pt 5pt 1pt;">
                  <div class="form-group margin-bottom">
                     <label class="control-label col-sm-2">Remark:</label>
                     <div class="col-sm-3">
                        <input tabindex="11" class="form-control input-sm" type="text" placeholder="" name="remarks" value="<?php

                        echo (! $dto == null) ? $dto->getRemarks() : "";
                        ?>">
                     </div>
                  </div>
                  <div class="form-group margin-bottom">
                     <label class="control-label col-sm-2">Description:</label>
                     <div class="col-sm-4">
                        <textarea class="form-control input-sm" type="text" rows="6" placeholder="" name="descriptionText" style="font-size: 9pt;"><?php

                        echo (! $dto == null) ? $dto->getDescriptionText() : "";
                        ?></textarea>
                     </div>
                  </div>
                  <hr style="margin: 5pt 1pt 5pt 1pt">
                  <div class="form-group margin-bottom" style="margin-top: 10pt">
                     <label class="control-label col-sm-2" for="inputTag"></label>
                     <div class="col-sm-3">
                        <a tabindex="11" class="btn btn-default btn-sm" onclick="submitForm('New_Invoice_Row');" href="javascript:;">
                           <small>
                              <i class="glyphicon glyphicon-floppy-disk"></i>
                           </small>&nbsp;<?php

                        echo $this->translate("Save");
                        ?></a>
                        <a tabindex="12" class="btn btn-default btn-sm" href="<?php

                        echo $review_url;
                        ?>">
                           <small>
                              <i class="glyphicon glyphicon-remove"></i>
                           </small>&nbsp;<?php

                        echo $this->translate("Cancel");
                        ?></a>
                        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                        <?php

                        echo $removeBtn;
                        ?>
                     </div>
                     <div class="col-sm-3"></div>
                  </div>
               </form>
            </div>
            <!-- end tab -->
         </div>
      </div>
   </div>
   <!-- /#page-content-wrapper -->
</div>
<!-- /#wrapper -->
<div class="modal" id="confirm_remove_row_modal_sm" role="dialog">
   <div class="modal-dialog modal-md">
      <div class="modal-content">
         <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal">&times;</button>
         </div>
         <div class="modal-body" id="b_modal_sm_body">
            <h5>#<?php

            echo $this->translate('Row will be removed!');
            ?></h5>
            <div class="alert alert-warning">
               <strong>[Info]</strong> <?php

            echo $this->translate('Remove can not be recalled!');
            ?>
               <!-- Journal Entry will be created. <br>- Warehouse Journal will be
               created.
                -->
            </div>
            <p><?php

            echo $this->translate('Do you want to continue?');
            ?></p>
         </div>
         <div class="modal-footer">
            <button onclick="doRemovingRow();" type="button" class="btn btn-primary btn-sm">YES</button>
            <button type="button" class="btn btn-default btn-sm" data-dismiss="modal">Cancel</button>
         </div>
      </div>
   </div>
</div>
<script type="text/javascript">

function confirmRemoveRow() {
    $('#confirm_remove_row_modal_sm').modal();
 }

 function doRemovingRow() {
 $('#confirm_remove_row_modal_sm').modal('hide');
 $('#b_modal_no_header').modal();
 var url="<?php

echo $remove_url;
?>";

var review_url="<?php

echo $review_url;
?>";
 $.get(url,function( data ) {
     window.location.href= review_url;
   });
}


    $('#unit_price').bind('change', function() {
    	$('#exw_unit_price').val($('#unit_price').val());
    });

	$("#Create_Inv_Form :input").attr("disabled", "disabled");

    $( "#pr_item_name" ).focus();

    $('#quantity').bind('change', function() {
       	$('#net_amount').val($('#unit_price').val() * $('#quantity').val());
       	$('#gross_amount').val($('#net_amount').val()*1 + $('#tax_amount').val()*1);

    });

    $('#unit_price').bind('change', function() {
    	$('#net_amount').val($('#unit_price').val() * $('#quantity').val());
    	$('#gross_amount').val($('#net_amount').val()*1 + $('#tax_amount').val()*1);
    });

    $('#tax_rate').bind('change', function() {
    	$('#tax_amount').val($('#net_amount').val() * $('#tax_rate').val()/100);
    	$('#gross_amount').val($('#net_amount').val()*1 + $('#tax_amount').val()*1);
    });

	$( "input[id='trx_date']").datepicker({ firstDay: 1, dateFormat: 'yy-mm-dd',closeText: 'X',changeMonth: true, changeYear: true});

</script>
<?php
include (ROOT . '/module/Procure/view/procure/pr_auto_complete.php');
include (ROOT . '/module/Inventory/view/inventory/item_auto_complete.php');
?>