<a style="color: #0080ff;" href="javascript:;"
	onclick="showBootstrapDialog('Warehouse List','/inventory/warehouse/list1','loaded_data');"> <i class="icon-list"> </i> Test Ajax List
</a>
<hr>
 
<?php

if ($total_records <= 0) {
	
	echo 'No record found!';
} else {
	
	if (! is_null ( $paginator )) {
		echo 'Record ' . $paginator->minInPage . ' to ' . $paginator->maxInPage . ' | ' . $total_records. ' records found!';
	} else {
		echo $total_records. ' records found!';
	}
	
	?>

<table class="table table-bordered table-hover">
	<thead>
		<tr>
			<td><b>#</b></td>
			<td><b>Company Code</b></td>
			<td><b>Company Name	</b></td>
			<td><b>Status</b></td>
			<td><b>Default</b></td>
			<td><b>Locked</b></td>
			<td><b>Date</b></td>
			<td><b>Action</b></td>
		</tr>
	</thead>

	<tbody>
 
	 <?php
	
	$count = 0;
	foreach ( $list as $a ) :
		$count ++;
		?>
	 <tr>
			<td><?php echo $count;?></td> 	
			<td><?php echo $this->escapeHtml($a->getWhCode());?></td>
			<td><?php echo $this->escapeHtml($a->GetWhName());?></td>
			<td><?php echo $this->escapeHtml($a->getWhStatus());?></td>
			<td><?php echo $this->escapeHtml($a->getIsDefault());?></td>
			<td><?php echo $this->escapeHtml($a->getIsLocked());?></td>
			<td><?php echo date_format ( $a->getCreatedOn(), "d/m/y");?> </td>
			<td></td>
		
		</tr>
<?php endforeach; ?>

 </tbody>
</table>

<?php
	
	// ===============================
	if (! is_null ( $paginator )) :
		
		// change it only
		$base = $this->baseUrl . '/inventory/warehouse/list';
		$_connector_symbol = '?';
		
		$last = $base . $_connector_symbol . 'page=' . $paginator->totalPages . '&perPage=' . $paginator->resultsPerPage;
		$first = $base . $_connector_symbol . 'page=1&perPage=' . $paginator->resultsPerPage;
		
		$p1 = ($paginator->page) - 1;
		$p2 = ($paginator->page) + 1;
		
		$prev = $base . $_connector_symbol . 'page=' . $p1 . '&perPage=' . $paginator->resultsPerPage;
		$next = $base . $_connector_symbol . 'page=' . $p2 . '&perPage=' . $paginator->resultsPerPage;
		
		echo '<ul class="pagination pagination-sm">';
		
		if ($paginator->page != 1 and $paginator->totalPages > 10) {
			echo '<li><a href="' . $first . '"> |< </a></li>';
			echo '<li><a href="' . $prev . '"> < </a></li>';
		}
		
		for($i = $paginator->minInPageSet; $i <= $paginator->maxInPageSet; $i ++) {
			
			$url = $base . $_connector_symbol . 'page=' . $i . '&perPage=' . $paginator->resultsPerPage;
			
			if ($i == $paginator->page) {
				echo '<li><a class="active" href="#">' . $i . '</a></li>';
			} else {
				echo '<li><a href="' . $url . '"> ' . $i . ' </a></li>';
			}
		}
		if ($paginator->page != $paginator->totalPages and $paginator->totalPages > 10) {
			echo '<li><a href="' . $next . '"> > </a></li>';
			echo '<li><a href="' . $last . '"> >| </a></li>';
		}
		echo '</ul>';
endif;
	
}
// ===============================
?>



<!-- Modal -->
<div class="modal" id="modal1" role="dialog">
	<div class="modal-dialog">
		<div class="modal-content">
			<div   class="modal-header">
				<button type="button" class="close" data-dismiss="modal">&times;</button>
				<b><h5 style="font-weight: bold;" class="modal-title" id = "modal_title" >Mascot International Laos</h5></b>
			</div>
			<div class="modal-body">
				<div id="loaded_data">loading</div>
			</div>
			<div class="modal-footer">
				<button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
			</div>
		</div>
	</div>
</div>
<div id="dialog1" style="display: none; padding-top: 4pt">
	<div id="search_result1">loading</div>
</div>
