


<a class="btn btn-default btn-sm"
	href="<?php echo $this->baseUrl ?>/inventory/item-transaction/gr?token=<?php echo (!$target== null)? $target->getToken():"";?>&target_id=<?php echo (!$target== null)? $target->getID():"";?>&checksum=<?php echo (!$target== null)? $target->getChecksum():"";?>"><small><i
		class="glyphicon glyphicon-plus"> </i></small>&nbsp;Receive</a>
<a class="btn btn-default btn-sm"
	href="<?php echo $this->baseUrl ?>/inventory/item-transaction/gi?token=<?php echo (!$target== null)? $target->getToken():"";?>&target_id=<?php echo (!$target== null)? $target->getID():"";?>&checksum=<?php echo (!$target== null)? $target->getChecksum():"";?>"><small><i
		class="glyphicon glyphicon-minus"> </i></small>&nbsp;Issue</a>
<a class="btn btn-default btn-sm"
	href="<?php echo $this->baseUrl ?>/inventory/item-transaction/transfer?token=<?php echo (!$target== null)? $target->getToken():"";?>&target_id=<?php echo (!$target== null)? $target->getID():"";?>&checksum=<?php echo (!$target== null)? $target->getChecksum():"";?>"><small><i
		class="glyphicon glyphicon-refresh"> </i></small>&nbsp;Transfer</a>

<hr>
<?php

if ($total_records <= 0) {

    echo 'No record found!';
} else {

    if (! is_null($paginator)) {
        echo 'Record ' . $paginator->minInPage . ' to ' . $paginator->maxInPage . ' | ' . $total_records . ' records found!';
    } else {
        echo $total_records . ' records found!';
    }

    ?>

<table id="mytable26" style="font-size: 9pt; color: graytext;" class="table table-bordered table-hover">
	<thead>
		<tr>
			<td><b>#</b></td>
			<td><b>Ref</b></td>
	
			<td><b>BarCode</b></td>
			<td><b>BarCode1</b></td>

			<td><b>Flow</b></td>
			<td><b>Unit Price</b></td>
			<td><b>Currency</b></td>

			<td><b>Mfg </b></td>
			<td><b>Mfg Serial</b></td>
			<td><b>Mfg Warranty</b></td>
			<td><b>Mfg Warranty End</b></td>
			<td><b>Remarks</b></td>
			<td><b>Action</b></td>
		</tr>
	</thead>

	<tbody>
 
	 <?php

    $count = 0;
    foreach ($list as $a) :

        /**@var \Application\Entity\NmtInventoryItemSerial $a ; */
        $count ++;
        ?>
	 <tr>
			<td><?php echo ($paginator===null)? $count:$paginator->minInPage -1+ $count;?></td>
			
			<td><?php  if($a->getApRow()!==null): echo $a->getApRow()->getInvoice()->getSysNumber(); endif;?></td>
		
			<td><!-- <img alt="" height=""
				src="/inventory/item/barcode?barcode=<?php echo (!$a == null)? $a->getSysNumber():"";?>"> -->
			</td>
			<td>	<?php echo $a->getSerialNumber();?></td>
			<td></td>
			<td><?php  if($a->getApRow()!==null): echo number_format($a->getApRow()->getUnitPrice(),2); endif;?></td>
			<td></td>

			<td>
			<?php echo $a->getMfgName();?>
			</td>


			<td><?php echo $this->escapeHtml($a->getMfgSerialNumber());?></td>

			<td>
	 	<?php if(!$a == null): if ($a->getMfgDate() !== null): echo date_format($a->getMfgDate(),"Y-m-d"); endif; endif;?></td>

			</td>
			<td>
		 	<?php if(!$a == null): if ($a->getMfgWarrantyEnd() !== null): echo date_format($a->getMfgWarrantyEnd(),"Y-m-d"); endif; endif;?></td>

			</td>
			<td>
			<?php echo $a->getRemarks();?>
			</td>
			<td><a class="" style="color:black;padding:1pt 2pt 2pt 2pt;"
				href="<?php echo $this->baseUrl ?>/inventory/item-serial/edit?token=<?php echo $a->getToken();?>&entity_id=<?php echo $a->getId();?>"><?php echo $this->translate('Edit');?></a>

<a class="" style="color:black;padding:1pt 2pt 1pt 2pt;"
				href="<?php echo $this->baseUrl ?>/inventory/item-serial-attachment/upload-pictures?token=<?php echo $a->getToken();?>&target_id=<?php echo $a->getId();?>"><?php echo $this->translate('Upload');?></a>
		
			
		
		</td>
		</tr>
<?php endforeach; ?>

 </tbody>
</table>

<?php

    // ===============================
    if (! is_null($paginator)) :

        // change it only
        $base = $this->baseUrl . '/inventory/item/list?is_active=' . $is_active . '&item_type=' . $item_type . '&sort_by=' . $sort_by . '&sort=' . $sort . '&is_fixed_asset=' . $is_fixed_asset;
        $_connector_symbol = '&';

        $last = $base . $_connector_symbol . 'page=' . $paginator->totalPages . '&perPage=' . $paginator->resultsPerPage;
        $first = $base . $_connector_symbol . 'page=1&perPage=' . $paginator->resultsPerPage;

        $p1 = ($paginator->page) - 1;
        $p2 = ($paginator->page) + 1;

        $prev = $base . $_connector_symbol . 'page=' . $p1 . '&perPage=' . $paginator->resultsPerPage;
        $next = $base . $_connector_symbol . 'page=' . $p2 . '&perPage=' . $paginator->resultsPerPage;

        echo '<ul class="pagination pagination-sm">';

        if ($paginator->page != 1 and $paginator->totalPages > 10) {
            echo '<li><a href="' . $first . '"> |< </a></li>';
            echo '<li><a href="' . $prev . '"> < </a></li>';
        }

        for ($i = $paginator->minInPageSet; $i <= $paginator->maxInPageSet; $i ++) {

            $url = $base . $_connector_symbol . 'page=' . $i . '&perPage=' . $paginator->resultsPerPage;

            if ($i == $paginator->page) {
                echo '<li><a class="active" href="#">' . $i . '</a></li>';
            } else {
                echo '<li><a href="' . $url . '"> ' . $i . ' </a></li>';
            }
        }
        if ($paginator->page != $paginator->totalPages and $paginator->totalPages > 10) {
            echo '<li><a href="' . $next . '"> > </a></li>';
            echo '<li><a href="' . $last . '"> >| </a></li>';
        }
        echo '</ul>';
endif;

}
// ===============================
?>



