<?php
use Application\Domain\Util\Collection\Render\AbstractCollectionRender;

/**
 *
 * @author Nguyen Mau Tri - ngmautri@gmail.com
 *        
 */

/**
 *
 * @var AbstractCollectionRender $collectionRender
 */

?>
  
    <div id="item_serial_div">
	  <h5>Item Serial Documents</h5>

        <?php
        echo $collectionRender->execute();
        echo $collectionRender->printAjaxPaginator();
        ?>
    </div>