<a class="btn btn-default"
	href="<?php echo $this->baseUrl ?>/inventory/item-transaction/gr?token=<?php echo (!$target== null)? $target->getToken():"";?>&target_id=<?php echo (!$target== null)? $target->getID():"";?>&checksum=<?php echo (!$target== null)? $target->getChecksum():"";?>"><small><i
		class="glyphicon glyphicon-plus"> </i></small>&nbsp;Receive</a>
<a class="btn btn-default"
	href="<?php echo $this->baseUrl ?>/inventory/item-transaction/gi?token=<?php echo (!$target== null)? $target->getToken():"";?>&target_id=<?php echo (!$target== null)? $target->getID():"";?>&checksum=<?php echo (!$target== null)? $target->getChecksum():"";?>"><small><i
		class="glyphicon glyphicon-minus"> </i></small>&nbsp;Issue</a>
<a class="btn btn-default"
	href="<?php echo $this->baseUrl ?>/inventory/item-transaction/transfer?token=<?php echo (!$target== null)? $target->getToken():"";?>&target_id=<?php echo (!$target== null)? $target->getID():"";?>&checksum=<?php echo (!$target== null)? $target->getChecksum():"";?>"><small><i
		class="glyphicon glyphicon-refresh"> </i></small>&nbsp;Transfer</a>

<hr>
<?php

if ($total_records <= 0) {

    echo 'No record found!';
} else {

    if (! is_null($paginator)) {
        echo 'Record ' . $paginator->getMinInPage() . ' to ' . $paginator->getMaxInPage() . ' | ' . $total_records . ' records found!';
    } else {
        echo $total_records . ' records found!';
    }

    ?>

<table style="font-size: 9pt;" class="table table-bordered table-hover">
	<thead>
		<tr>
			<td><b>#</b></td>
			<td><b>PR Number</b></td>
			<td><b>Vendor</b></td>
			<td><b>Flow</b></td>
			<td><b>Q'ty</b></td>
			<td><b>Price</b></td>
			<td><b>Total <br>Value
			</b></td>
			<td><b>Curr.</b></td>
			<td><b>Payment<br>Method
			</b></td>
			<td><b>Unit</b></td>
			<td><b>Conversion</b></td>
			<td><b>Transaction<br>Date
			</b></td>
			<td><b>Created Date</b></td>
			<td><b>Attachment</b></td>
		</tr>
	</thead>

	<tbody>
 
	 <?php

    $count = 0;
    foreach ($list as $a) :
        $count ++;
        ?>
	 <tr>
			<td><?php echo ($paginator===null)? $count:$paginator->getMinInPage() -1+ $count;?></td>
			<td><?php if($a->getPrRow()!==null): echo $a->getPrRow()->getPr()->getPrNumber(); endif;?></td>

			<td><?php if($a->getVendor()!==null): echo $a->getVendor()->getVendorName(); endif;?></td>
			<td><?php echo $this->escapeHtml($a->getFlow());?></td>

			<td><?php echo $this->escapeHtml($a->getQuantity());?></td>

			<td><?php echo number_format( $this->escapeHtml($a->getVendorUnitPrice()), 2, ",", ".");?></td>
			<td><?php echo $a->getQuantity()*$a->getVendorUnitPrice();?></td>

			<td><?php if($a->getCurrency()!==null): echo $a->getCurrency()->getCurrency(); endif;?></td>
			<td><?php echo ($a->getPmtMethod() !==null)? $this->escapeHtml($a->getPmtMethod()->getMethodCode()):"N/A";?></td>
			<td><?php echo $this->escapeHtml($a->getVendorItemUnit());?></td>
			<td><?php echo $this->escapeHtml($a->getConversionText());?></td>
			<td><?php echo ($a->getTrxdate()!==null )? date_format ( $a->getTrxdate(), "d/m/y"):"N/A";?> </td>
			<td><?php echo ($a->getCreatedOn()!==null )? date_format ( $a->getCreatedOn(), "d/m/y"):"N/A";?> </td>
			<td><a
				href="<?php echo $this->baseUrl ?>/inventory/item-transaction/show?token=<?php echo $a->getToken();?>&entity_id=<?php echo $a->getID();?>&checksum=<?php echo $a->getChecksum();?>">Show</a>
				<a
				href="<?php echo $this->baseUrl ?>/inventory/item-transaction/edit?token=<?php echo $a->getToken();?>&entity_id=<?php echo $a->getID();?>&checksum=<?php echo $a->getChecksum();?>">Edit</a>
			</td>

		</tr>
<?php endforeach; ?>

 </tbody>
</table>

<?php

    // ===============================
    if (! is_null($paginator)) :

        // change it only
        $base = $this->baseUrl . '/inventory/item/list?is_active=' . $is_active . '&item_type=' . $item_type . '&sort_by=' . $sort_by . '&sort=' . $sort . '&is_fixed_asset=' . $is_fixed_asset;
        $_connector_symbol = '&';

        $last = $base . $_connector_symbol . 'page=' . $paginator->getTotalPages() . '&perPage=' . $paginator->getResultsPerPage();;
        $first = $base . $_connector_symbol . 'page=1&perPage=' . $paginator->getResultsPerPage();;

        $p1 = ($paginator->getPage()) - 1;
        $p2 = ($paginator->getPage()) + 1;

        $prev = $base . $_connector_symbol . 'page=' . $p1 . '&perPage=' . $paginator->getResultsPerPage();;
        $next = $base . $_connector_symbol . 'page=' . $p2 . '&perPage=' . $paginator->getResultsPerPage();;

        echo '<ul class="pagination pagination-sm">';

        if ($paginator->getPage() != 1 and $paginator->getTotalPages() > 10) {
            echo '<li><a href="' . $first . '"> |< </a></li>';
            echo '<li><a href="' . $prev . '"> < </a></li>';
        }

        for ($i = $paginator->getMinInPageSet(); $i <= $paginator->getMaxInPageSet(); $i ++) {

            $url = $base . $_connector_symbol . 'page=' . $i . '&perPage=' . $paginator->getResultsPerPage();;

            if ($i == $paginator->getPage()) {
                echo '<li><a class="active" href="#">' . $i . '</a></li>';
            } else {
                echo '<li><a href="' . $url . '"> ' . $i . ' </a></li>';
            }
        }
        if ($paginator->getPage() != $paginator->getTotalPages() and $paginator->getTotalPages() > 10) {
            echo '<li><a href="' . $next . '"> > </a></li>';
            echo '<li><a href="' . $last . '"> >| </a></li>';
        }
        echo '</ul>';
endif;

}
// ===============================
?>



