<?php

/**
 *
 * @author Nguyen Mau Tri - ngmautri@gmail.com
 *
 */
use Inventory\Application\Service\ItemVariant\Export\ExportAsHtmlTable;

$url = sprintf('/inventory/item-variant/create?item_id=%s', $item_id);
?>
<a class="btn btn-default btn-sm" href="<?php
echo $url;
?>">
         <small>

   <i class="glyphicon glyphicon-plus"> </i>
   </small>&nbsp;<?php

echo $this->translate('Create New');
?></a>

<?php
$export = new ExportAsHtmlTable();
echo $export->execute($variantCollection);
?>