<?php
$nid = \Application\Model\Constants::INVENTORY_HASH_ID;
?>

<div id="tabs" style="font-size: 9.5pt">

	<ul>
		<li><a href="#general">Item Serial</a></li>
	</ul>
	<div id="general">

		<hr>
<?php

if ($total_records <= 0) {
    
    echo 'No record found!';
} else {
    
    if (! is_null($paginator)) {
        echo 'Record ' . $paginator->minInPage . ' to ' . $paginator->maxInPage . ' | ' . $total_records . ' records found!';
    } else {
        echo $total_records . ' records found!';
    }
    
    ?>

<table style="font-size: 9pt;" class="table table-bordered table-hover">
			<thead>
				<tr>
					<td><b>#</b></td>
						<td><b>Reversed</b></td>
				
					<td><b>BarCode</b></td>
					<td><b>SN</b></td>
					<td><b>Item</b></td>
					<td><b>Flow</b></td>
					<td><b>Unit Price</b></td>
					<td><b>Currency</b></td>

					<td><b>Mfg </b></td>
					<td><b>Mfg Model</b></td>
					<td><b>Mfg Serial</b></td>
					<td><b>Mfg Warranty</b></td>
					<td><b>Mfg Warranty End</b></td>
					<td><b>Attachment</b></td>
					<td><b>Action</b></td>
				</tr>
			</thead>

			<tbody>
 
	 <?php
    
    $count = 0;
    foreach ($list as $a) :
        
        /**@var \Application\Entity\NmtInventoryItemSerial $a ; */
        $count ++;
        ?>
	 <tr>
					<td><?php echo ($paginator===null)? $count:$paginator->minInPage -1+ $count;?></td>
							<td><?php echo $this->escapeHtml($a->getIsReversed());?></td>
			
					<td>
			
			<?php echo $a->getSysNumber(); ?>
			</td>
			
							<td>
			
			<?php echo $a->getSerialNumber(); ?>
			</td>
			

					<td>
			<?php if($a->getItem()!==null): echo $a->getItem()->getItemName(); endif;?>
			</td>

				
					<td><?php if($a->getInventoryTrx()!==null):echo $this->escapeHtml($a->getInventoryTrx()->getFlow());endif;?></td>
					<td><?php  if($a->getInventoryTrx()!==null):if($a->getInventoryTrx()->getVendorUnitPrice()!==null): echo number_format($a->getInventoryTrx()->getVendorUnitPrice(),2); endif;endif;?></td>
					<td><?php  if($a->getInventoryTrx()!==null):if($a->getInventoryTrx()->getCurrency()!==null): echo $a->getInventoryTrx()->getCurrency()->getCurrency(); endif;endif;?></td>

					<td>
			<?php echo $a->getMfgName();?>
			</td>

					<td><?php echo $this->escapeHtml($a->getMfgModel());?></td>

					<td><?php echo $this->escapeHtml($a->getMfgSerialNumber());?></td>

					<td>
	 	<?php if(!$a == null): if ($a->getMfgDate() !== null): echo date_format($a->getMfgDate(),"Y-m-d"); endif; endif;?></td>

					</td>
					<td>
		 	<?php if(!$a == null): if ($a->getMfgWarrantyEnd() !== null): echo date_format($a->getMfgWarrantyEnd(),"Y-m-d"); endif; endif;?></td>

					</td>
					<td>
			<?php echo $a->getRemarks();?>
			</td>
					<td><a
						href="<?php echo $this->baseUrl ?>/inventory/item-serial/edit?nid=<?php echo $nid;?>&token=<?php echo $a->getToken();?>&entity_id=<?php echo $a->getId();?>"><?php echo $this->translate('Show');?></a>
						<a
							href="<?php echo $this->baseUrl ?>/inventory/item-serial/edit?nid=<?php echo $nid;?>&token=<?php echo $a->getToken();?>&entity_id=<?php echo $a->getId();?>"><?php echo $this->translate('Edit');?></a></td>
				</tr>
<?php endforeach; ?>

 </tbody>
		</table>
	</div>
</div>


<?php
   
    // ===============================
    if (! is_null($paginator)) :
        
        // change it only
        $base = $this->baseUrl . '/inventory/item-serial/list?is_active=' . $is_active . '&sort_by=' . $sort_by . '&sort=' . $sort;
        $_connector_symbol = '&';
        
        $last = $base . $_connector_symbol . 'page=' . $paginator->totalPages . '&perPage=' . $paginator->resultsPerPage;
        $first = $base . $_connector_symbol . 'page=1&perPage=' . $paginator->resultsPerPage;
        
        $p1 = ($paginator->page) - 1;
        $p2 = ($paginator->page) + 1;
        
        $prev = $base . $_connector_symbol . 'page=' . $p1 . '&perPage=' . $paginator->resultsPerPage;
        $next = $base . $_connector_symbol . 'page=' . $p2 . '&perPage=' . $paginator->resultsPerPage;
        
        echo '<ul class="pagination pagination-sm">';
        
        if ($paginator->page != 1 and $paginator->totalPages > 10) {
            echo '<li><a href="' . $first . '"> |< </a></li>';
            echo '<li><a href="' . $prev . '"> < </a></li>';
        }
        
        for ($i = $paginator->minInPageSet; $i <= $paginator->maxInPageSet; $i ++) {
            
            $url = $base . $_connector_symbol . 'page=' . $i . '&perPage=' . $paginator->resultsPerPage;
            
            if ($i == $paginator->page) {
                echo '<li><a class="active" href="#">' . $i . '</a></li>';
            } else {
                echo '<li><a href="' . $url . '"> ' . $i . ' </a></li>';
            }
        }
        if ($paginator->page != $paginator->totalPages and $paginator->totalPages > 10) {
            echo '<li><a href="' . $next . '"> > </a></li>';
            echo '<li><a href="' . $last . '"> >| </a></li>';
        }
        echo '</ul>';
endif;
    
}
// ===============================
?>



