<h4>Add Wahrehouse for company: <?php echo $company->getCompanyName();?></h4>

<hr>

<?php
if (count ( $errors ) > 0) {
	echo '<div class="alert alert-danger" role="alert">';
	
	echo '<ul>';
	foreach ( $errors as $error ) :
		echo '<li>' . $error . '</li>';
	endforeach
	;
	echo '</ul>';
	echo '</div>';
}
?>


<form class="form-horizontal"
	action="<?php echo $this->baseUrl ?>/inventory/warehouse/add"
	method="post" enctype="multipart/form-data">
	<input type="hidden" name="company_id" value="<?php echo $company!==null ? ($company->getId()) :""?>" />
 	<input type="hidden" name="redirectUrl"
	value="<?php echo $redirectUrl ?>" />	

	<div class="form-group">
		<label class="control-label col-sm-2" for="inputTag">Warehouse Code</label>
		<div class="col-sm-3">
				<input class="form-control"  type="text" placeholder="" name="wh_code" ">
		</div>
	</div>
	<div class="form-group">
		<label class="control-label col-sm-2" for="inputTag"></label>
		<div class="col-sm-3">
			 <input type="checkbox" name="is_locked" value="1"> Locked 
			 <input type="checkbox" name="is_default" value="1"> Default Warehouse<br>
	
		</div>
	</div>
	
	<div class="form-group">
		<label class="control-label col-sm-2" for="inputTag">Warehouse Name</label>
		<div class="col-sm-3">
			<input class="form-control" type="text" id="inputTag" placeholder=""
				name="wh_name" value="">
		</div>
	</div>
	
	<div class="form-group">
		<label class="control-label col-sm-2" for="inputTag">Warehouse Address</label>
		<div class="col-sm-3">
			<input class="form-control" type="text" id="inputTag" placeholder=""
				name="wh_address" value="">
		</div>
	</div>
	
	<div class="form-group">
		<label class="control-label col-sm-2" for="inputTag">Country</label>
		<div class="col-sm-3">
			<select class="form-control"  name="country_id" >
				        		<option value="">-----</option>
				    	    <?php foreach ($countries as $r) :
				    	    echo '<option value="' . $r->getId(). '">' .  $r->getCountryName(). '</option>';
				  					endforeach; 
							?>   		
			</select>
		</div>
	</div>
	
	<div class="form-group">
		<label class="control-label col-sm-2" for="inputTag">Contact person</label>
		<div class="col-sm-3">
			<input class="form-control" type="text" id="inputTag" placeholder=""
				name="wh_contact_person" value="">
		</div>
	</div>
	<div class="form-group">
		<label class="control-label col-sm-2" for="inputTag">Default</label>
		<div class="col-sm-3">
			<select class="form-control" name="wh_status">
				<option selected="selected" value="Activated">Activated</option>
				<option value="Deactivated">Deactivated</option>
			</select>
		</div>
	</div>
	
	<div class="form-group">
		<div class="col-sm-offset-2 col-sm-10">
			<button type="submit" class="btn btn-default">Submit</button>
		</div>
	</div>
</form>



<div id="dialog" style="display: none;">Check code...</div>