<?php
/**
 * @var \Application\Entity\NmtInventoryWarehouse $entity ;
 * 
 */
$form_action = '';
$form_title = '';

switch ($action) {

    case \Application\Model\Constants::FORM_ACTION_ADD:
        $form_action = '/inventory/warehouse/add';
        $form_title = $this->translate("Add Warehouse:");

        break;
    case \Application\Model\Constants::FORM_ACTION_EDIT:
        $form_action = '/inventory/warehouse/edit';
        $form_title = $this->translate("Edit Warehouse:");
        break;
}
?>




<div id="tabs" style="font-size: 10pt">
	<ul>
		<li><a href="#general"><?php echo $form_title;?></a></li>
					
		<?php if($action == \Application\Model\Constants::FORM_ACTION_EDIT):?>
        <?php endif;?>			
				</ul>

	<div id="general" style="font-size: 9pt">
		<!-- Tab1 -->
    	
 	<?php
if (count($errors) > 0) {
    echo '<div class="alert alert-danger alert-dismissible"" role="alert" style="font-size: 9.5pt"><a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>[ERROR]';

    echo '<ul>';
    foreach ($errors as $error) :
        echo '<li>' . $error . '</li>';
    endforeach
    ;
    echo '</ul>';
    echo '</div>';
}
?>
    
					<form id="New_Invoice_Row" class="form-horizontal"
			action="<?php echo $form_action;?>" method="post"
			enctype="multipart/form-data">

			<input type="hidden" name="redirectUrl"
				value="<?php echo $redirectUrl ?>" /> <input type="hidden"
				id="entity_id" name="entity_id"
				value="<?php if (!$entity == null): echo $entity->getId();endif;?>" />
					
							
            			<?php if($action == \Application\Model\Constants::FORM_ACTION_EDIT):?>
            				<input type="hidden" name="n" value="<?php echo $n;?>" />
            			<?php endif;?>
            			
            			
			<div class="form-group margin-bottom">
				<label class="control-label col-sm-2"><?php echo $this->translate("Warehouse Code");?>: </label>
				<div class="col-sm-3">
					<input tabindex="1" class="form-control input-sm" type="text"
						id="whCode" placeholder="" name="whCode"
						value="<?php if (!$entity== null): if($entity->getWhCode()!==null): echo $entity->getWhCode();endif;endif;?>">
				</div>
			</div>

			<div class="form-group margin-bottom">
				<label class="control-label col-sm-2"><?php echo $this->translate("Warehouse Name");?>: </label>
				<div class="col-sm-3">
					<input tabindex="1" class="form-control input-sm" type="text"
						id="whName" placeholder="" name="whName"
						value="<?php if (!$entity== null): if($entity->getWhName()!==null): echo $entity->getWhName();endif;endif;?>">
				</div>

				<div class="col-sm-3">
					<input
						<?php if(!$entity== null): echo ($entity->getWhStatus()=="1")?"checked":""; else: echo "checked"; endif;?>
						type="checkbox" name="whStatus" value="1"><?php echo $this->translate("Location required");?> &nbsp;&nbsp;&nbsp;

									</div>
			</div>
			
			<div class="form-group margin-bottom">
				<label class="control-label col-sm-2"><?php echo $this->translate("Address");?>: </label>
				<div class="col-sm-3">
					<input tabindex="1" class="form-control input-sm" type="text"
						id="whAddress" placeholder="" name="whAddress"
						value="<?php if (!$entity== null): if($entity->getWhAddress()!==null): echo $entity->getWhAddress();endif;endif;?>">
				</div>
			</div>

					<div class="form-group margin-bottom required">

							<label class="control-label col-sm-2"><?php echo $this->translate("Country");?>:</label>
							<div class="col-sm-3">
								<select tabindex="9" name="country_id" id="country_id"
									class="form-control input-sm">
									<option value=""><?php echo $this->translate("Select Country");?></option>
   	    							<?php
   	    	 if ($country_list !== null) :
   	    	 foreach ($country_list as $gl) :

                    /**@var \Application\Entity\NmtApplicationCountry $gl ; */

                    if ($entity !== null) :
                        if ($entity->getWhCountry() !== null) :
                        if ($entity->getWhCountry()->getId() == $gl->getId()) :
                            echo '<option selected value="' . $gl->getId() . '">' . $gl->getCountryName() . '</option>';
                            else :
                            echo '<option value="' . $gl->getId() . '">' . $gl->getCountryName() . '</option>';
                            endif;
                        else :
                            echo '<option value="' . $gl->getId() . '">' . $gl->getCountryName() . '</option>';
                        endif;
                    else :
                    echo '<option value="' . $gl->getId() . '">' . $gl->getCountryName()  . '</option>';
                    endif;
                endforeach
                ;
   	    							endif;

            ?>
   					</select>
							</div>

							

			</div>
						
						
			<div class="form-group margin-bottom">
				<label class="control-label col-sm-2"><?php echo $this->translate("Contract Person");?>: </label>
				<div class="col-sm-3">
					<input tabindex="1" class="form-control input-sm" type="text"
						id="whContactPerson" placeholder="" name="whContactPerson"
						value="<?php if (!$entity== null): if($entity->getWhContactPerson()!==null): echo $entity->getWhContactPerson();endif;endif;?>">
				</div>
			</div>
			
			
			<div class="form-group margin-bottom">
				<label class="control-label col-sm-2"><?php echo $this->translate("Contract Person Email");?>: </label>
				<div class="col-sm-3">
					<input tabindex="1" class="form-control input-sm" type="text"
						id="whEmail" placeholder="" name="whEmail"
						value="<?php if (!$entity== null): if($entity->getWhEmail()!==null): echo $entity->getWhEmail();endif;endif;?>">
				</div>
			</div>
			
				<div class="form-group margin-bottom">
				<label class="control-label col-sm-2"><?php echo $this->translate("Remarks");?>: </label>
				<div class="col-sm-5">
					<textarea class="form-control input-sm" type="text" rows="6"
						placeholder="" name="remarks" style="font-size: 9pt;"><?php echo (!$entity == null)? $entity->getRemarks():"";?></textarea>

				</div>
			</div>

			<div class="form-group margin-bottom"></div>



			<hr style="margin: 5pt 1pt 5pt 1pt;">

			<div class="form-group margin-bottom" style="margin-top: 10pt">
				<label class="control-label col-sm-2" for="inputTag"></label>
				<div class="col-sm-3">
					<a tabindex="11" class="btn btn-default btn-sm"
						onclick="submitForm('New_Invoice_Row');" href="javascript:;"><small><i
							class="glyphicon glyphicon-floppy-disk"></i></small>&nbsp;<?php echo $this->translate("Save");?></a>
					<a tabindex="12" class="btn btn-default btn-sm"
						href="<?php echo $this->baseUrl ?>/inventory/warehouse/list"><small><i
							class="glyphicon glyphicon-remove"></i></small>&nbsp;<?php echo $this->translate("Cancel");?></a>

				</div>


			</div>
		</form>


	</div>

	<!-- end tab -->
</div>

