<div id="tabs" style="font-size: 9.5pt"> 
  <ul>
  <li ><a href="#general">Currency List</a></li>
   </ul>

<div id="general"> 

<ul class="nav nav-pills">
	<li><a style="color: #0080ff;" href="<?php echo $this->baseUrl ?>/inventory/warehouse/create"><?php echo $this->translate("Add New Warehouse");?>
	</a></li>
</a></li>

</ul>


<hr>
<?php

if ($total_records <= 0) {
	
	echo 'No Resources found!';
} else {
	
	if (! is_null ( $paginator )) {
		echo 'Result ' . $paginator->getMinInPage() . ' to ' . $paginator->getMaxInPage() . ' | ' . $total_records. ' Resources found!';
	} else {
		echo $total_records. ' Resources found!';
	}
	
	?>

<table class="table table-bordered table-striped">
	<thead>
		<tr>
			<td><b><?php echo $this->translate("WH Code");?></b></td>
			<td><b><?php echo $this->translate("WH Name");?></b></td>
			<td><b><?php echo $this->translate("WH Address");?></b></td>
			<td><b><?php echo $this->translate("Country");?></b></td>
			<td><b><?php echo $this->translate("Default");?></b></td>
			<td><b><?php echo $this->translate("Created Date");?></b></td>
		
			<td><b><?php echo $this->translate("Action");?></b></td>
			
		</tr>
	</thead>

	<tbody>
 
	 <?php
	
	$count = 0;
	foreach ( $list as $a ) :
		$count ++;
			
		/**@var \Application\Entity\NmtInventoryWarehouse $a ;*/
		
		?>
	 <tr>
			<td><?php echo $this->escapeHtml($a->getWhCode());?></td>
			<td><?php echo $this->escapeHtml($a->getWhName());?></td>
			<td><?php echo $this->escapeHtml($a->getWhAddress());?></td>
	
			<td><?php if($a->getWhCountry()!=null):echo $a->getWhCountry()->getCountryName(); endif;?></td>
			<td><?php if ($this->escapeHtml($a->getIsDefault()!=1)):
			?>
<a class = "btn-default sm" href="<?php echo $this->baseUrl ?>/inventory/warehouse/set-default?token=213214314dfds&entity_id=<?php echo $a->getID();?>&checksum=dfdfdfeedfds"><?php echo $this->translate("Set Default");?>
</a>

<?php
			else:
			?>
			1
			<?php
			endif;
			?></td>
			
					
			<td><?php echo date_format ( $a->getCreatedOn(), "d/m/Y  h:m");?> </td>

			<td>
<a href="<?php echo $this->baseUrl ?>/inventory/warehouse/update?token=<?php echo $a->getToken();?>&entity_id=<?php echo $a->getID();?>"><?php echo $this->translate("Edit");?>
</a>
			
			</td>
		</tr>
<?php endforeach; ?>

 </tbody>
</table>

<?php
	
	// ===============================
	if (! is_null ( $paginator )) :
		
		// change it only
		$base = $this->baseUrl . '/inventory/warehouse/list';
		$_connector_symbol = '?';
		
		$last = $base . $_connector_symbol . 'page=' . $paginator->getTotalPages() . '&perPage=' . $paginator->getResultsPerPage();;
		$first = $base . $_connector_symbol . 'page=1&perPage=' . $paginator->getResultsPerPage();;
		
		$p1 = ($paginator->getPage()) - 1;
		$p2 = ($paginator->getPage()) + 1;
		
		$prev = $base . $_connector_symbol . 'page=' . $p1 . '&perPage=' . $paginator->getResultsPerPage();;
		$next = $base . $_connector_symbol . 'page=' . $p2 . '&perPage=' . $paginator->getResultsPerPage();;
		
		echo '<ul class="pagination pagination-sm">';
		
		if ($paginator->getPage() != 1 and $paginator->getTotalPages() > 10) {
			echo '<li><a href="' . $first . '"> |< </a></li>';
			echo '<li><a href="' . $prev . '"> < </a></li>';
		}
		
		for($i = $paginator->getMinInPageSet(); $i <= $paginator->getMaxInPageSet(); $i ++) {
			
			$url = $base . $_connector_symbol . 'page=' . $i . '&perPage=' . $paginator->getResultsPerPage();;
			
			if ($i == $paginator->getPage()) {
				echo '<li><a class="active" href="#">' . $i . '</a></li>';
			} else {
				echo '<li><a href="' . $url . '"> ' . $i . ' </a></li>';
			}
		}
		if ($paginator->getPage() != $paginator->getTotalPages() and $paginator->getTotalPages() > 10) {
			echo '<li><a href="' . $next . '"> > </a></li>';
			echo '<li><a href="' . $last . '"> >| </a></li>';
		}
		echo '</ul>';
endif;
	
}
// ===============================
?>

</div></div>