
<ul class="nav nav-pills">
 <li><a href="/inventory/warehouse/add"><i class="icon-plus">  </i> Add Warehouse</a></li>
</ul>  
 
	
<table class="table table-striped table-bordered">
<thead>
<tr>	
  		<td><b>Warehouse Code</b></td>
		<td><b>Warehouse Name</b></td>
		<td><b>Address</b></td>
	
		</tr>
</thead>
<tbody>	
 
  <?php 
   	
	 $count = 0;
	 foreach ($warehouses as $item) : 
	 	 $count++;
	// echo  ($count % 2 == 1) ? "<tr>" : "<tr class=\"pure-table-odd\">";
	 
	 	 
	 ?>
	 <tr>
		<td><?php echo $item->wh_code?></td>
		<td><?php echo $item->wh_name?></td>
		<td><?php echo $item->wh_address?></td>
		</tr>
	
<?php endforeach; ?>

</tbody>
</table>
<hr>
