<table class="table table-striped table-bordered">
<thead>
<tr>	
		<td><b>Select</b></td>
  		<td><b>Warehouse Code</b></td>
		<td><b>Warehouse Name</b></td>
		<td><b>Address</b></td>
		<td><b>Contact Person</b></td>
		</tr>
</thead>
<tbody>	
		<tr>
	 	<td><a style="color: blue;" onclick="selectWH('<?php echo $wh ?>','DEFAULT WAREHOUSE','')" href="javascript:;">	<i class="icon-chevron-right"></i> Select  </a></td>
		<td>999999</td>
		<td>DEFAULT WAREHOUSE</td>
		<td>N/A<td>
		</tr>
 
  <?php 
   	
	 $count = 0;
	 foreach ($warehouses as $item) : 
	 	 $count++;
	// echo  ($count % 2 == 1) ? "<tr>" : "<tr class=\"pure-table-odd\">";
	 
	 	 
	 ?>
	 <tr>
	 	<td><a style="color: blue;" onclick="selectWH('<?php echo $wh ?>','<?php echo $item->wh_name?>','<?php echo $item->id?>')" href="javascript:;">	<i class="icon-chevron-right"></i> Select  </a></td>
		<td><?php echo $item->wh_code?></td>
		<td><?php echo $item->wh_name?></td>
		<td><?php echo $item->wh_address?></td>
		<td><?php echo $item->wh_contact_person?></td>
		</tr>
	
<?php endforeach; ?>

</tbody>
</table>
<hr>
