<h4>Item: <?php echo $item->getItemName();?></h4>

<?php if (count($errors)>0)
{
echo '<div class="alert alert-error">';
	
	echo '<ul>';
	 foreach ($errors as $error) :
	 echo '<li>'.$error . '</li>';
	 
	 endforeach;
	 echo '</ul>';
	 echo '</div>';
} 
?>

<div id="tabs" style="font-size: 10pt"> 
  <ul>
  <li ><a href="#general">Transfer</a></li>
   </ul>
   
 <div id="general">

<form class="form-horizontal" action="<?php echo $this->baseUrl ?>/inventory/warehouse/transfer"	method="post" enctype="multipart/form-data">
	<input type="hidden" name="redirectUrl" value="<?php echo $redirectUrl ?>" />
	<input type="hidden" id="item_id" name="item_id" value="<?php echo $item->getId()?>" />
	<input type="hidden" id="source_wh_id" name="source_wh_id" value="" />
	<input type="hidden" id="target_wh_id" name="target_wh_id" value="" />
	
 	 <div class="form-group">
		<label class="control-label col-sm-2" for="inputTag">Transfer Date</label>
		<div class="col-sm-3">
  			<input class="form-control" type="text" name="movement_date" value="" placeholder =" please select" id="movement_date" />
         </div>
      </div>
      
    <div class="form-group">
		<label class="control-label col-sm-2" for="inputTag">Source WH</label>
		<div class="col-sm-3">
  			<input class="form-control" readonly type="text" id="source_wh_name" placeholder="Please select!" name="source_wh"
				value=""> 
			</div>
<a style="color: #0080ff;" href="javascript:;"
onclick="showBootstrapDialog('Source Warehouse','/inventory/warehouse/list1?target_id=source_wh_id&target_name=source_wh_name','loaded_data');">Select&nbsp;&nbsp;<i class="glyphicon glyphicon-folder-open"></i>
</a>
		
	</div>
	
	<div class="form-group">
		<label class="control-label col-sm-2" for="inputTag">Target WH</label>
		<div class="col-sm-3">
  			<input class="form-control" readonly type="text" id="target_wh_name" placeholder="Please select!" name="target_wh"
				value=""> 
		</div>
<a style="color: #0080ff;" href="javascript:;"
	onclick="showBootstrapDialog('Target Warehouse','/inventory/warehouse/list1?target_id=target_wh_id&target_name=target_wh_name','loaded_data');">Select&nbsp;&nbsp;<i class="glyphicon glyphicon-folder-open"></i>
</a>		
	</div>
      

  <div class="form-group">
		<label class="control-label col-sm-2" for="inputTag">Transer Quantity</label>
		<div class="col-sm-3">
  				<input class="form-control" type="text" name="quantity" value="">
		</div>
		<a href="javascript:;" onclick="showBalance('<?php echo $item->getId();?>','<?php echo $article->name?>');"
				class="helper">Check Balance <i class=" icon-folder-open"></i></a>
      </div>
      
  <div class="form-group">
		<label class="control-label col-sm-2" for="inputTag">Remarks</label>
		<div class="col-sm-4">
  	        <textarea class="form-control" id="inputDescription" placeholder="" rows="2" name="remarks">
          </textarea>
        </div>
      </div>
      
 	  
    <div class="form-group">
		<label class="control-label col-sm-2" for="inputTag"></label>
		<div class="col-sm-3">
  	         <button type="submit" class="btn btn-default">Transfer</button>
        </div>
      </div>
    </form>
    
 </div>
 </div>

  <!-- Modal -->
<div class="modal" id="modal1" role="dialog">
	<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal">&times;</button>
				<b><h5 style = "font-weight: bold" class="modal-title" id = "modal_title" >Mascot International Laos</h5></b>
			</div>
			<div class="modal-body">
				<div id="loaded_data">loading</div>
			</div>
			<div class="modal-footer">
				<span id="node_selected">No thing selected</span>&nbsp;&nbsp;
				<button type="button" class="btn btn-default" data-dismiss="modal">Confirm</button>
			</div>
		</div>
	</div>
</div>

    
<div id="dialog1" style="display: none; padding-top: 4pt">
</div>    