
<div id="tabs" style="font-size: 9.5pt">

	<ul>
		<li><a href="#general"><?php echo $this->translate('Salary calculation'); ?></a></li>
	</ul>
<div id="general" style="font-size: 9pt">

<div class="row">
  <div class="col-xs-6 col-md-3">
  <div class="list-group" style="">
  	<a class="list-group-item" href="/hr/position/list"><?php echo $this->translate('Period Closing'); ?></a>
  	<a class="list-group-item" href="/hr/leave-reason/list"><?php echo $this->translate('Payroll Input Consolidation'); ?></a>
	<a class="list-group-item" href="/hr/minimum-wage/index"><?php echo $this->translate('Input Checking'); ?></a>
	<a class="list-group-item" href="/hr/sso/index"><?php echo $this->translate('Draft Caculation'); ?></a>
	<a class="list-group-item" href="/hr/income-setup/index"><?php echo $this->translate('Adjustment'); ?></a>
	<a class="list-group-item" href="/hr/income-decorator/index"><?php echo $this->translate('Final Caculation'); ?></a>
	<a class="list-group-item" href="/hr/income-decorator/index"><?php echo $this->translate('Submision for Approval'); ?></a>
	</div>
  </div>
    <div class="col-xs-12 col-sm-6 col-md-9" style=""><h3><?php echo $this->translate('Running'); ?></h3></div>
  
</div>	

</div>
</div>
