<?php /**@var \Application\Entity\NmtProcureQo $target ;*/ ?>
<?php $attachment_url =  $this->baseUrl . '/procure/quote-attachment' ;?>


<a class="btn btn-default" href="<?php echo $attachment_url ?>/upload?token=<?php echo (!$target== null)? $target->getToken():"";?>&target_id=<?php echo (!$target== null)? $target->getID():"";?>"><small><i class="fa fa-upload" aria-hidden="true"></i>&nbsp;</small>&nbsp;New Attachment</a>
  
<hr>

 

<?php

if ($total_records <= 0) {
	
	echo 'No record found!';
} else {
	
	if (! is_null ( $paginator )) {
		echo 'Record ' . $paginator->getMinInPage() . ' to ' . $paginator->getMaxInPage() . ' | ' . $total_records. ' records found!';
	} else {
		echo $total_records. ' records found!';
	}
	
	?>

<table style="font-size: 10pt;" class="table table-bordered table-hover">
	<thead>
		<tr>
			<td><b>#</b></td>
			<td><b>Vendor</b></td>
			<td><b>Doc. Subject</b></td>
			<td><b>Doc. Name</b></td>
			<td><b>Doc. Size</b></td>
			<td><b>A</b></td>
			<td><b>D</b></td>
			<td><b>P</b></td>
			<td><b>Date</b></td>
			<td><b>Action</b></td>
		</tr>
	</thead>

	<tbody>
 
	 <?php
	
	$count = 0;
	foreach ( $list as $a ) :
	   
      /**@var \Application\Entity\NmtApplicationAttachment $a ;*/

		$count ++;
		?>
	 <tr>
	 <td><?php echo ($paginator===null)? $count:$paginator->getMinInPage() -1+ $count;?></td>
	 
	 		<td>
<?php if ($a->getVendor()!==null):?>
<a target="_blank" style="color:navy;" href="<?php echo $this->baseUrl ?>/bp/vendor/show?token=<?php echo $a->getVendor()->getToken();?>&entity_id=<?php echo $a->getVendor()->getId();?>&checksum=<?php echo $a->getVendor()->getChecksum();?>"><?php echo $a->getVendor()->getVendorName();?></a>
<?php endif;?>
	 		</td>
	 		<td><?php echo $this->escapeHtml($a->getDocumentSubject());?></td>
			<td><?php echo $this->escapeHtml($a->getFileNameOriginal());?></td>
			<td><?php echo $this->escapeHtml($a->getSize());?></td>
			<td><?php echo ($a->getIsActive()=='1')?'<small><i class="glyphicon glyphicon-ok"></i></small>':'';?></td>
			<td><?php echo ($a->getMarkedForDeletion()=='1')?'<small><i class="glyphicon glyphicon-remove"></i></small>':'';?></td>
			<td><?php echo ($a->getisPicture()=='1')?'<small><i class="glyphicon glyphicon-ok"></i></small>':'';?></td>
	
			<td><?php echo date_format ( $a->getCreatedOn(), "d/m/y");?> </td>
			<td>
<small><i class="glyphicon glyphicon-download-alt"></i></small>&nbsp;<a href="<?php echo $attachment_url ?>/download?token=<?php echo $this->escapeHtml($a->getToken());?>&entity_id=<?php echo $this->escapeHtml($a->getID());?>&checksum=<?php echo $this->escapeHtml($a->getChecksum());?>">download</a>
<a href="<?php echo $attachment_url ?>/show?token=<?php echo $this->escapeHtml($a->getToken());?>&entity_id=<?php echo $this->escapeHtml($a->getID());?>&checksum=<?php echo $this->escapeHtml($a->getChecksum());?>">Show</a>
<a href="<?php echo $attachment_url ?>/edit?token=<?php echo $this->escapeHtml($a->getToken());?>&entity_id=<?php echo $this->escapeHtml($a->getID());?>&checksum=<?php echo $this->escapeHtml($a->getChecksum());?>">Edit</a>

			</td>
			
		</tr>
<?php endforeach; ?>

 </tbody>
</table>

<?php
	
	// ===============================
	if (! is_null ( $paginator )) :
		
		// change it only
	$base = $this->baseUrl . '/inventory/item/list?is_active='. $is_active.'&item_type='. $item_type.'&sort_by='.$sort_by.'&sort='.$sort.'&is_fixed_asset='.$is_fixed_asset;
		$_connector_symbol = '&';
		
		$last = $base . $_connector_symbol . 'page=' . $paginator->getTotalPages() . '&perPage=' . $paginator->getResultsPerPage();;
		$first = $base . $_connector_symbol . 'page=1&perPage=' . $paginator->getResultsPerPage();;
		
		$p1 = ($paginator->getPage()) - 1;
		$p2 = ($paginator->getPage()) + 1;
		
		$prev = $base . $_connector_symbol . 'page=' . $p1 . '&perPage=' . $paginator->getResultsPerPage();;
		$next = $base . $_connector_symbol . 'page=' . $p2 . '&perPage=' . $paginator->getResultsPerPage();;
		
		echo '<ul class="pagination pagination-sm">';
		
		if ($paginator->getPage() != 1 and $paginator->getTotalPages() > 10) {
			echo '<li><a href="' . $first . '"> |< </a></li>';
			echo '<li><a href="' . $prev . '"> < </a></li>';
		}
		
		for($i = $paginator->getMinInPageSet(); $i <= $paginator->getMaxInPageSet(); $i ++) {
			
			$url = $base . $_connector_symbol . 'page=' . $i . '&perPage=' . $paginator->getResultsPerPage();;
			
			if ($i == $paginator->getPage()) {
				echo '<li><a class="active" href="#">' . $i . '</a></li>';
			} else {
				echo '<li><a href="' . $url . '"> ' . $i . ' </a></li>';
			}
		}
		if ($paginator->getPage() != $paginator->getTotalPages() and $paginator->getTotalPages() > 10) {
			echo '<li><a href="' . $next . '"> > </a></li>';
			echo '<li><a href="' . $last . '"> >| </a></li>';
		}
		echo '</ul>';
endif;
	
}
// ===============================
?>


