<?php 
/**@var \Application\Entity\NmtInventoryItemSerial $target ;*/

$attachment_url =  $this->baseUrl . '/inventory/item-serial-attachment';
$nid = \Application\Model\Constants::INVENTORY_HASH_ID;
if(!$target== null){
    $redirectUrl=sprintf("/inventory/item/show?tab_idx=5&entity_id=%s&token=%s",$target->getItem()->getId(), $target->getItem()->getToken());
}
?>

<h4>
	 <?php 
	 /**@todo: UPDATE TARGET */
 	echo (!$target== null)? 'Serial: ' . $target->getSysNumber():"";?>
</h4>


<?php
if (count ( $errors ) > 0) {
	echo '<div class="alert alert-danger" role="alert" style="font-size: 10.5pt">';
	
	echo '<ul>';
	foreach ( $errors as $error ) :
		echo '<li>' . $error . '</li>';
	endforeach
	;
	echo '</ul>';
	echo '</div>';
}
?>

<div id="tabs" style="font-size: 9.5pt"> 
  <ul>
  <li ><a href="#general">Picture Upload</a></li>
   </ul>

<div id="general">

<h5 style="color: gray">
	 <?php echo (!$target== null)? 'Item: ' . $target->getItem()->getItemName()."<br>":"";?>
</h5>

<hr>
 

<!-- TO UPDATE ACTION -->
<form id="sp_upload_pic_form" class="form-horizontal" action="" method="post" enctype="multipart/form-data">
	
	
	<div class="form-group">
		<label class="control-label col-sm-2" for="inputTag">Picture</label>
		<div class="col-sm-3">
			<input type="file" name="pictures[]" />
			<input type="file" name="pictures[]" />
			<input type="file" name="pictures[]" />
			<input type="file" name="pictures[]" />
			<input type="file" name="pictures[]" />
		</div>
	</div>
	
	
	
	<div class="form-group">
		<label class="control-label col-sm-2" for="inputTag"></label>
		<div class="col-sm-3">
			<button type="button"  onclick="uploadImages('<?php echo $attachment_url; ?>/upload-pictures','<?php echo $target!==null ? $target->getId():""?>','<?php echo $redirectUrl ?>','','<?php echo $target!==null ? $target->getToken():""?>')" class="btn btn-primary btn-sm" id="upload">
				<i class="fa fa-upload" aria-hidden="true"></i>&nbsp;Upload
			</button>
			</div>
	</div>
	
</form>
</div>
</div>


