<h4>Create New Country:</h4>
<hr>

<?php
if (count ( $errors ) > 0) {
	echo '<div class="alert alert-danger" role="alert">';
	
	echo '<ul>';
	foreach ( $errors as $error ) :
		echo '<li>' . $error . '</li>';
	endforeach
	;
	echo '</ul>';
	echo '</div>';
}
?>


<form class="form-horizontal"
	action="<?php echo $this->baseUrl ?>/application/country/add"
	method="post" enctype="multipart/form-data">
	<input type="hidden" name="redirectUrl"
		value="<?php echo $redirectUrl ?>" />


	<div class="form-group">
		<label class="control-label col-sm-2" for="inputTag">Country Name</label>
		<div class="col-sm-3">
			<input class="form-control" type="text" id="inputTag" placeholder=""
				name="country_name" value="">
		</div>
	</div>
	
	<div class="form-group">
		<label class="control-label col-sm-2" for="inputTag">Country Code Alpha2</label>
		<div class="col-sm-3">
			<input class="form-control" type="text" id="inputTag" placeholder=""
				name="country_code_2" value="">
		</div>
	</div>
	
	<div class="form-group">
		<label class="control-label col-sm-2" for="inputTag">Country Code Alpha3</label>
		<div class="col-sm-3">
			<input class="form-control" type="text" id="inputTag" placeholder=""
				name="country_code_3" value="">
		</div>
	</div>
	
	<div class="form-group">
		<label class="control-label col-sm-2" for="inputTag">Country Numeric Code</label>
		<div class="col-sm-3">
			<input class="form-control" type="text" id="inputTag" placeholder=""
				name="country_numeric_code" value="">
		</div>
	</div>
	
	<div class="form-group">
		<label class="control-label col-sm-2" for="inputDescription">remarks</label>
		<div class="col-sm-3">
			<textarea class="form-control" id="inputDescription" placeholder=""
				rows="2" name="remarks"></textarea>
		</div>
	</div>

	<div class="form-group">
		<label class="control-label col-sm-2" for="inputTag">Status</label>
		<div class="col-sm-3">
			<select class="form-control" name="status">
				<option selected="selected" value="1">Activated</option>
				<option value="0">Deactivated</option>
			</select>
		</div>
	</div>

	<div class="form-group">
		<div class="col-sm-offset-2 col-sm-10">
			<button type="submit" class="btn btn-default">Submit</button>
		</div>
	</div>
</form>



<div id="dialog" style="display: none;">Check code...</div>