
<?php  //var_dump( $hits) ?>
<ul class="nav nav-pills">
	<li><a href="<?php echo $this->baseUrl ?>/application/search">Item
			List</a></li>
</ul>

 <form class="form-inline" action="<?php echo $this->baseUrl ?>/application/search/resource"	method="get" enctype="multipart/form-data">
  <div class="form-group">
    	<input class="form-control" size="28" type="text" name = "q" class="">
  </div>
  <div class="form-group">
     <button type="submit" class="btn btn-default"><small><i class="glyphicon glyphicon-search"> </i></small> Search</button>
  </div>
  
</form>

<hr>

<div class="alert alert-info">
	You can search wildcard*. e.g enter <em>cof*</em> to search for Coffee
</div>

<?php

echo '<span>';
echo $message;
echo '</span><hr>';

if (! $hits == null) :
	
	?>
<table class="table table-striped table-bordered">
	<thead>
		<tr>
			<td><b>#</b></td>
			<td><b>Module</b></td>
			<td><b>Controller</b></td>
			<td><b>Action</b></td>
			<td><b>Resource</b></td>
		</tr>
	</thead>
	<tbody>

	 <?php
	
	$count = 0;
	foreach ( $hits as $hit ) :
		$count ++;
		// echo ($count % 2 == 1) ? "<tr>" : "<tr class=\"pure-table-odd\">";
		
		?>
	 <tr>
			<td> <?php echo $count;?></td>
			<td><span id="<?php echo $hit->module_1?>_name"><?php echo $this->escapeHtml($hit->module_1	);?></span></td>
				<td><span id="<?php echo $hit->controller_1?>_name"><?php echo $this->escapeHtml($hit->controller_1);?></span></td>
					<td><span id="<?php echo $hit->action_1?>_name"><?php echo $this->escapeHtml($hit->action_1);?></span></td>
					<td><span id="<?php echo $hit->resource_1?>_name"><?php echo $this->escapeHtml($hit->resource_1);?></span></td>
	
		</tr>
<?php endforeach; ?>
</tbody>
</table>


<?php endif; ?>
