<h1><?php echo $this->escapeHtml($category->name);?></h1>

<?php echo $this->escapeHtml($category->id);?>

<?php //var_dump($spareparts); ?>

<form
	action="<?php echo $this->baseUrl ?>/inventory/admin/add-sparepart-category-member"
	method="post" enctype="multipart/form-data" id="New Sparepart">

	<input type="hidden" name="id"
		value="<?php echo (int) $category->id; ?>" /> <input type="hidden"
		name="redirectUrl" value="<?php echo $redirectUrl ?>" />

	<table class="pure-table pure-table-bordered">
		<thead>
			<tr>
				<td></td>
				<td>Tag</td>
				<td>Spare Parts</td>
			</tr>
		</thead>
		<tbody>

 <?php

$count = 0;
foreach ($spareparts as $sparepart) :
    $count ++;
    echo ($count % 2 == 1) ? "<tr>" : "<tr class=\"pure-table-odd\">";

    ?>	
 	

    	<td><input type="checkbox" name="sparepart[]"
				value="<?php echo $this->escapeHtml($sparepart['id']);?>"
				class="checkbox" /></td>
			<td><?php echo $this->escapeHtml($sparepart['tag']);?></td>
			<td><?php echo $this->escapeHtml($sparepart['name']);?></td>
			</tr>
<?php endforeach; ?>

<tr>
				<td></td>
				<td><input type="submit" name="add" value="Add" /></td>
			</tr>
		</tbody>
	</table>