<h1><?php echo $this->escapeHtml($category->name);?></h1>
	
<?php echo $this->escapeHtml($category->id);?>

<?php //var_dump($spareparts); ?>

<form action="<?php echo $this->baseUrl ?>/inventory/admin/add-sparepart-category-member"	method="post" enctype="multipart/form-data" id="New Sparepart">
	
<input type="hidden" name="id" value="<?php echo (int) $category->id; ?>" />

<table border="1" cellpadding="3">
<tr>
		<td><b></b></td>

		<td><b>Spare Parts</b></td>
		
	</tr>	
	<?php foreach ($spareparts as $sparepart) : ?>
 	
    <tr>
    	<td><input type="checkbox" name="sparepart[]" value="<?php echo $this->escapeHtml($sparepart['id']);?>" class="checkbox"/></td>
    	<td><?php echo $this->escapeHtml($sparepart['tag']);?></td>
    	<td><?php echo $this->escapeHtml($sparepart['name']);?></td>
     	</tr>
<?php endforeach; ?>

<tr>
	<td></td> 
	<td><input type="submit" name="add" value="Add" />	</td>
</tr>
</table>
