
<h4>Adding Member for Compay: <?php echo $company->getCompanyName(); ?></h4>


<form
	action="<?php echo $this->baseUrl ?>/application/company/add-member"
	method="post" enctype="multipart/form-data">

	<input type="hidden" name="company_id"
		value="<?php echo $company->getId(); ?>" /> <input type="hidden"
		name="redirectUrl" value="<?php echo $redirectUrl ?>" />



	<table class="table table-bordered table-striped">
		<thead>
			<tr>
				<td>Select</td>
				<td>First Name</td>
				<td>Last Name</td>
				<td>Email</td>
			</tr>
		</thead>
		<tbody>

 <?php

$count = 0;
foreach ($users as $user) :
    $count ++;

    ?>	
 		<tr>
				<td><input type="checkbox" name="users[]"
					value="<?php echo $this->escapeHtml($user['id']);?>"
					class="checkbox" /></td>
				<td><?php echo $this->escapeHtml($user['firstname']);?></td>
				<td><?php echo $this->escapeHtml($user['lastname']);?></td>
				<td><?php echo $this->escapeHtml($user['email']);?></td>

			</tr>
<?php endforeach; ?>

<tr>
				<td></td>
				<td><input type="submit" name="add" value="Add" /></td>
			</tr>



		</tbody>
	</table>