 	
<?php
if ($total_resources <= 0) {

    echo 'No Resources found!';
} else {

    if (! is_null($paginator)) {
        echo 'Result ' . $paginator->minInPage . ' to ' . $paginator->maxInPage . ' | ' . $total_resources . ' Resources found!';
    } else {
        echo $total_resources . ' Resources found!';
    }

    ?>

<form
	action="<?php echo $this->baseUrl ?>/application/role/grant-access"
	method="post" enctype="multipart/form-data" id="">

	<input type="hidden" name="role_id"
		value="<?php echo (int) $role_id; ?>" />

	<table class="table table-bordered table-striped">
		<thead>
			<tr>
				<td><b>Select</b></td>
				<td><b>Module</b></td>
				<td><b>Action</b></td>
				<td><b>Resource</b></td>
				<td><b>Type</b></td>
				<td><b>isWhiteList</b></td>
				<td><b>Remarks</b></td>
				<td><b>Updated on</b></td>
				<td><b>Action</b></td>
			</tr>
		</thead>

		<tbody>
 
	 <?php

    $count = 0;
    foreach ($resources as $a) :
        $count ++;
        // echo ($count % 2 == 1) ? "<tr>" : "<tr class=\"pure-table-odd\">";
        // $instock = $a['totalINFLOW']-$a['totalOUTFLOW'];

        ?>
	 <tr>
				<td><input type="checkbox" name="resources[]"
					value="<?php echo $a->id;?>" class="checkbox" /></td>
				<td><?php echo $this->escapeHtml($a->module);?></td>
				<td><?php echo $this->escapeHtml($a->action);?></td>
				<td><?php echo $this->escapeHtml($a->resource);?></td>
				<td><?php echo $this->escapeHtml($a->type);?></td>
				<td>-</td>
				<td><?php echo $this->escapeHtml($a->remarks);?> </td>
				<td><?php echo date_format (date_create($a->created_on), "d/m/Y  h:m");?> </td>

				<td></td>
			</tr>
<?php endforeach; ?>

 </tbody>
	</table>
	<input class="btn btn-primary" type="submit" name="grant"
		value="Grant Access" />
	<hr>



	<br>

<?php

    // ===============================
    if (! is_null($paginator)) :

        // change it only
        $base = $this->baseUrl . '/application/role/grant-access?id=' . $role_id;
        $_connector_symbol = '&';

        $last = $base . $_connector_symbol . 'page=' . $paginator->totalPages . '&perPage=' . $paginator->resultsPerPage;
        $first = $base . $_connector_symbol . 'page=1&perPage=' . $paginator->resultsPerPage;

        $p1 = ($paginator->page) - 1;
        $p2 = ($paginator->page) + 1;

        $prev = $base . $_connector_symbol . 'page=' . $p1 . '&perPage=' . $paginator->resultsPerPage;
        $next = $base . $_connector_symbol . 'page=' . $p2 . '&perPage=' . $paginator->resultsPerPage;

        echo '<ul class="pagination">';

        if ($paginator->page != 1 and $paginator->totalPages > 10) {
            echo '<li><a href="' . $first . '"> |< </a></li>';
            echo '<li><a href="' . $prev . '"> < </a></li>';
        }

        for ($i = $paginator->minInPageSet; $i <= $paginator->maxInPageSet; $i ++) {

            $url = $base . $_connector_symbol . 'page=' . $i . '&perPage=' . $paginator->resultsPerPage;

            if ($i == $paginator->page) {
                echo '<li><a class="active" href="#">' . $i . '</a></li>';
            } else {
                echo '<li><a href="' . $url . '"> ' . $i . ' </a></li>';
            }
        }
        if ($paginator->page != $paginator->totalPages and $paginator->totalPages > 10) {
            echo '<li><a href="' . $next . '"> > </a></li>';
            echo '<li><a href="' . $last . '"> >| </a></li>';
        }
        echo '</ul>';
endif;

}
//===============================
?>

