<div id="tabs" style="font-size: 9.5pt"> 
  <ul>
  <li ><a href="#general">Country List</a></li>
   </ul>

<div id="general"> 

<?php

if ($total_records <= 0) {
	
	echo 'No Resources found!';
} else {
	
	if (! is_null ( $paginator )) {
		echo 'Result ' . $paginator->minInPage . ' to ' . $paginator->maxInPage . ' | ' . $total_records. ' Resources found!';
	} else {
		echo $total_records. ' Resources found!';
	}
	
	?>

<table class="table table-bordered table-striped">
	<thead>
		<tr>
			<td><b>Company Code</b></td>
			<td><b>Company Name	</b></td>
			<td><b>Currency	</b></td>
	
			<td><b>Status</b></td>
			<td><b>Date</b></td>
			<td><b>Action</b></td>
		</tr>
	</thead>

	<tbody>
 
	 <?php
	
	$count = 0;
	foreach ( $list as $a ) :
		$count ++;
		/**@var \Application\Entity\NmtApplicationCompany $a ;*/
		$edit_url = sprintf('/application/company/edit?token=%s&entity_id=%s', $a->getToken(), $a->getId());
		
		?>
	 <tr>
			<td><?php echo $this->escapeHtml($a->getCompanyCode());?></td>
			<td><?php echo $this->escapeHtml($a->getCompanyName());?></td>
			<td><?php if ($a->getDefaultCurrency()!==null): echo $a->getDefaultCurrency()->getCurrency();endif;?></td>
	
			<td><?php echo $this->escapeHtml($a->getStatus());?></td>
			<td><?php echo date_format ( $a->getCreatedOn(), "d/m/Y  h:m");?> </td>
			<td>
			<a href="<?php echo $edit_url; ?>"><?php echo $this->translate("Edit");?></a>
			<a href="<?php echo $this->baseUrl ?>/application/company/add-member?company_id=<?php echo $this->escapeHtml($a->getID());?>">Add member</a>
			<a href="<?php echo $this->baseUrl ?>/application/company/upload-logo?target_id=<?php echo $this->escapeHtml($a->getID());?>">upload logo</a>
			<a href="<?php echo $this->baseUrl ?>/inventory/warehouse/add?company_id=<?php echo $this->escapeHtml($a->getID());?>">Add Warehouse</a>
			<a href="<?php echo $this->baseUrl ?>/inventory/warehouse/list?company_id=<?php echo $this->escapeHtml($a->getID());?>">Warehouses</a>
		
		</tr>
<?php endforeach; ?>

 </tbody>
</table>

<?php
	
	// ===============================
	if (! is_null ( $paginator )) :
		
		// change it only
		$base = $this->baseUrl . '/application/uom/list';
		$_connector_symbol = '?';
		
		$last = $base . $_connector_symbol . 'page=' . $paginator->totalPages . '&perPage=' . $paginator->resultsPerPage;
		$first = $base . $_connector_symbol . 'page=1&perPage=' . $paginator->resultsPerPage;
		
		$p1 = ($paginator->page) - 1;
		$p2 = ($paginator->page) + 1;
		
		$prev = $base . $_connector_symbol . 'page=' . $p1 . '&perPage=' . $paginator->resultsPerPage;
		$next = $base . $_connector_symbol . 'page=' . $p2 . '&perPage=' . $paginator->resultsPerPage;
		
		echo '<ul class="pagination pagination-sm">';
		
		if ($paginator->page != 1 and $paginator->totalPages > 10) {
			echo '<li><a href="' . $first . '"> |< </a></li>';
			echo '<li><a href="' . $prev . '"> < </a></li>';
		}
		
		for($i = $paginator->minInPageSet; $i <= $paginator->maxInPageSet; $i ++) {
			
			$url = $base . $_connector_symbol . 'page=' . $i . '&perPage=' . $paginator->resultsPerPage;
			
			if ($i == $paginator->page) {
				echo '<li><a class="active" href="#">' . $i . '</a></li>';
			} else {
				echo '<li><a href="' . $url . '"> ' . $i . ' </a></li>';
			}
		}
		if ($paginator->page != $paginator->totalPages and $paginator->totalPages > 10) {
			echo '<li><a href="' . $next . '"> > </a></li>';
			echo '<li><a href="' . $last . '"> >| </a></li>';
		}
		echo '</ul>';
endif;
	
}
// ===============================
?>

</div></div>