<?php

/**@var \Application\Entity\NmtApplicationCompany $entity ;*/
$url = sprintf('/application/company/show?token=%s&entity_id=%s', $entity->getToken(), $entity->getId());

?>


<?php
if (count($errors) > 0) {
    echo '<div class="alert alert-danger" role="alert" style="font-size: 10.5pt">';

    echo '<ul>';
    foreach ($errors as $error) :
        echo '<li>' . $error . '</li>';
    endforeach
    ;
    echo '</ul>';
    echo '</div>';
}
?>

<div>
	<h4>
		<a href="<?php echo $url; ?>"><?php echo (!$entity == null)?$entity->getCompanyName():"";?></a>
	</h4>
</div>


<div id="tabs" style="font-size: 9.5pt">
	<ul>
		<li><a href="#general"><?php echo $this->translate("Edit Company");?></a></li>
	</ul>

	<div id="general" style="font-size: 9pt">

		<!-- UPDATE -->
		<form id="Edit_PR_Form" class="form-horizontal"
			action="/application/company/edit" method="post"
			enctype="multipart/form-data">
			<input type="hidden" name="redirectUrl"
				value="<?php echo $redirectUrl ?>" /> <input type="hidden"
				name="entity_id"
				value="<?php echo (!$entity== null)? $entity->getId():"";?>" /> <input
				type="hidden" name="token"
				value="<?php echo (!$entity== null)? $entity->getToken():"";?>" /> <input
				type="hidden" name="n" value="<?php echo $n;?>" />

			<div class="form-group margin-bottom required">
				<label class="control-label col-sm-2"><?php echo $this->translate('Company Code'); ?>:</label>
				<div class="col-sm-3">
					<input disabled class="form-control input-sm" type="text"
						value="<?php if(!$entity == null): echo $entity->getCompanyCode(); endif;?>" />
				</div>
				<div class="col-sm-4"></div>
			</div>

			<div class="form-group margin-bottom required">
				<label class="control-label col-sm-2"><?php echo $this->translate('Company Name'); ?>:</label>
				<div class="col-sm-3">
					<input disabled class="form-control input-sm" type="text"
						value="<?php if(!$entity == null): echo $entity->getCompanyName(); endif;?>" />
				</div>
				<div class="col-sm-4">
					<input
						<?php if(!$entity == null): echo ($entity->getStatus()=="1")?"checked":""; else: echo "checked"; endif;?>
						type="checkbox" name="isActive" value="1">&nbsp;Active&nbsp;&nbsp;
				</div>

			</div>

			<div class="form-group margin-bottom required">

				<label class="control-label col-sm-2"><?php echo $this->translate("Default Currency");?></label>
				<div class="col-sm-3">
					<select name="currency_id" class="form-control input-sm">
						<option value="">Select Currency</option>
   	    							<?php
            if ($currency_list !== null) :
                foreach ($currency_list as $curr) :
                    if ($entity !== null) :
                        if ($entity->getDefaultCurrency() !== null) :
                            if ($entity->getDefaultCurrency()->getCurrency() == $curr->getCurrency()) :
                                echo '<option selected value="' . $curr->getId() . '">' . $curr->getCurrency() . '</option>';
                            else :
                                echo '<option value="' . $curr->getId() . '">' . $curr->getCurrency() . '</option>';
                            endif;
                        else :
                            echo '<option value="' . $curr->getId() . '">' . $curr->getCurrency() . '</option>';
                        endif;
                    else :
                        echo '<option value="' . $curr->getId() . '">' . $curr->getCurrency() . '</option>';
                    endif;
                endforeach
                ;
   	    							endif;

            ?>
   					</select>
				</div>
			</div>
			<div class="form-group margin-bottom">
				<label class="control-label col-sm-2" for="inputTag"></label>
				<div class="col-sm-3">
					<button onclick="submitForm('Edit_PR_Form');"
						class="btn btn-default">
						<i class="glyphicon glyphicon-floppy-disk"> </i> Save
					</button>
				</div>
			</div>


		</form>
	</div>
</div>

