<?php
namespace Application\Form\Collection;

use Application\Domain\Util\Translator;
use Application\Form\Contracts\GenericForm;
use Application\Form\Helper\DefaultOptions;
use Zend\Form\Element\Select;

/**
 *
 * @author Nguyen Mau Tri - ngmautri@gmail.com
 *        
 */
class DefaultCollectionFilterForm extends GenericForm
{

    private $accountOptions;

    public function __construct($id = null)
    {
        parent::__construct($id);
        $this->id = $id;
        $this->setAttribute('method', 'get');
        $this->setAttribute('class', 'form-horizontal');
    }

    public function setAction($url)
    {
        $this->setAttribute('action', $url);
        return $this;
    }

    /*
     * |=============================
     * |Autogenerate Element
     * |
     * |=============================
     */

    /**
     *
     * {@inheritdoc}
     * @see \Application\Form\Contracts\GenericForm::addElements()
     */
    protected function addElements()
    {
        // left empty
    }

    /*
     * |=============================
     * | Manual Element
     * |
     * |=============================
     */

    /**
     *
     * {@inheritdoc}
     * @see \Application\Form\Contracts\GenericForm::addManualElements()
     */
    protected function addManualElements()
    {

        // ======================================
        // Form Element for {resultPerPage}
        // ======================================

        // select
        $select = new Select();
        $select->setName("resultPerPage");
        $select->setAttributes([
            'id' => 'resultPerPage',
            'class' => "form-control input-sm chosen-select",
            'required' => true
        ]);

        $select->setOptions([
            'label' => Translator::translate('Result Per Page'),
            'label_attributes' => [
                'class' => 'control-label col-sm-2'
            ]
        ]);
        // $select->setEmptyOption(Translator::translate('Parent Account Number'));

        $select->setValueOptions(DefaultOptions::createResultPerPageOption());
        // $select->setDisableInArrayValidator(false);
        $this->add($select);
    }

    /*
     * |=============================
     * | Function to get Form Elements
     * | Autogenerated
     * |
     * |=============================
     */
    public function getItemId()
    {
        return $this->get("itemId");
    }

    public function getVendorId()
    {
        return $this->get("vendorId");
    }

    public function getInvoiceId()
    {
        return $this->get("invoiceId");
    }

    public function getDocYear()
    {
        return $this->get("docYear");
    }

    public function getDocMonth()
    {
        return $this->get("docMonth");
    }

    public function getIsActive()
    {
        return $this->get("isActive");
    }

    public function getResultPerPage()
    {
        return $this->get("resultPerPage");
    }

    public function getRenderType()
    {
        return $this->get("renderType");
    }
}
