<script language="javascript">
			var id_array = [];
</script>

        
 <?php 
echo '<div class="alert alert-info">';
	
	 echo '<ul>';
	 echo '<li>All Purchase Request View for Procurement</li>';
	 echo '</ul>';
	 echo '</div>';

?>

 <form class="form-search" action="<?php echo $this->baseUrl ?>/procurement/"	method="get" enctype="multipart/form-data">
      <button type="submit" class="btn"><i class="icon-arrow-left">  </i> Back</button>
</form>
 
<h4>All Purchase Requests:</h4>

<?php echo count($all_pr) . ' PRs found'?>
<table class="pure-table pure-table-bordered"">
<thead>
<tr>	
		<td><b>Name</b></td>
		<td><b>Description</b></td>
		<td><b>Requester</b></td>		
		<td><b>Created on</b></td>
		<td><b>Latest Status</b></td>
		<td><b>Updated on</b></td>
		
		<td><b>Action</b></td>
	</tr>
</thead>
<tbody>	
 
  <?php 
	 
	 $count = 0;
	 foreach ($all_pr as $item) : 
	 	 $count++;
	 echo  ($count % 2 == 1) ? "<tr>" : "<tr class=\"pure-table-odd\">";
	 ?>
		<td><?php echo $item->pr_number;?> <span class="label label-info"><?php echo $item->tItems;?></span></td> 	
		<td><?php echo $item->description;?></td>
		<td><?php echo $item->requester;?></td>
		
		<td><?php echo date_format(date_create($item->requested_on),"Y-m-d");?></td>
		<td><?php echo $item->status ===null?'Started':$item->status;?></td>
		<td><?php echo $item->last_change;?></td>
		<td>
		<a
		href="<?php echo $this->baseUrl ?>/procurement/pr/approve-step-1?pr_id=<?php echo $item->id;?>"><?php echo $item->status ==='Approved'?'show':'approve';?>
		</a>
		
		
	</td>
<?php endforeach; ?>
</tbody>
</table>

