<script language="javascript">
			var id_array = [];
</script>

<div class="panel-group">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h5 class="panel-title">
          <a data-toggle="collapse" href="#collapse1"><?php echo $pr!==null ? '<h5>Purchase Request (PR): '. $pr->pr_number.'</h5>':"" ?></a>
        </h5>
      </div>
      <div id="collapse1" class="panel-collapse collapse <?php echo $pr->status === null?'':'in';?>">
        <div class="panel-body">
        
     <?php if ($pr!==null)
{
echo '<div class="alert alert-info">';
	
	 echo '<ul>';
	 echo '<li>Description	: <strong>' .$pr->description	 . '</strong></li>';
	 echo '<li>Created on		: <strong>' .$pr->requested_on . '</strong> by <strong>' . $pr->requester . '</strong></li>';
	 echo '<li>Updated on		: <strong>' .$pr->last_change . '</strong></li>';
	 echo '<li>Latest Status		: <strong>' .$pr->status .  '</strong> by <strong>' .$pr->changed_by . '</strong></li>';
	 
	 echo '</ul>';
	 echo '</div>';
} 
?>
        </div>
     </div>
    </div>
  </div>        

 

<?php  	if (count($pr_items) >0): ?>

<?php  	if ($pr->status!=='Approved'): ?>
<button title="Submit PR to Procurment" class="btn btn-default" onclick="openConfirmation('<?php echo $pr->id?>');" type="button"><i class="icon-ok">  </i> Approve</button>
<?php  	endif; ?>
 <hr>
<a href="/application/pdf/pr?id=<?php echo $pr->id ?>"  target="_blank"><i class="icon-download-alt">  </i> PDF</a>    	


<table class="pure-table pure-table-bordered">
<thead>
<tr>	
		<td><b>Item</b></td>
		<td><b>Priority</b></td>
		<td><b>Name</b></td>
		<td><b>Description</b></td>
		<td><b>Unit</b></td>
		<td><b>Quantity</b></td>
		<td><b>Delivered</b></td>
		<td><b>Balance</b></td>		
		<td><b>EDT</b></td>
		<td><b>Count Down</b></td>
		<td><b>Action</b></td>
		
	</tr>
</thead>
<tbody>	
 
  <?php 
   	
	 $count = 0;
	 foreach ($pr_items as $item) : 
	 	 $count++;
	 echo  ($count % 2 == 1) ? "<tr>" : "<tr class=\"pure-table-odd\">";
	 
	 $to_delivery = $item->quantity - $item->delivered_quantity;
	 
	 	 
	 ?>
		<td><?php echo $count;?></td>
		<td><?php echo $item->priority=='Urgent'? '<span class="label label-warning">'. $item->priority .'</span>':$item->priority;?></td> 	
		<td><?php echo $item->name;?></td>
		<td><?php echo $item->description;?></td>
		<td><?php echo $item->unit;?></td>
		<td><?php echo $item->quantity;?></td>
		<td><?php echo $item->delivered_quantity;?></td>
		<td><?php echo $to_delivery==0?'<span class="label label-success">0</span>':$to_delivery;?></td>
		
		
		<td><span id="<?php echo $item->id;?>_EDT"><?php echo date_format(date_create($item->EDT),"Y-m-d");?></span></td>
		<td><span id="<?php echo $item->id;?>_timer"></span></td>
		<td>  </i> <b>Action</b></td>
		
		</tr>
		
		<script language="javascript">
			id_array.push(<?php echo $item->id;?>);
		</script>
		

<?php endforeach; ?>

 			

</tbody>
</table>
<hr>

<?php endif; ?>
 <form class="form-search" action="<?php echo $this->baseUrl ?>/procurement/pr/all-pr"	method="get" enctype="multipart/form-data">
      <button type="submit" class="btn"><i class="icon-arrow-left">  </i> Back</button>
</form>


<!-- Modal -->
	<div id="myModal" class="modal hide" role="dialog">
	  <div class="modal-dialog">
	  	 <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h5 class="modal-title">Mascot International (Laos)</h5>
      </div>
	      <div class="modal-body">
	        <p>Do you want to approve this Purchase Request?</p>
	      </div>
	      
		  <div class="modal-footer">
	        <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
	        <button onclick="approvePR('<?php echo $pr->id?>');" type="button" class="btn btn-primary">OK</button>
	      </div>
	   </div>
	</div>	
	
	<!-- Modal -->
	<div id="myModal1" class="modal hide" role="dialog">
	  <div class="modal-dialog">
	      <div class="modal-body">
	        <p>Sending data........Please Wait!</p>
	      </div>
	   </div>
	</div>	