<script language="javascript">
			var id_array = [];
</script>

<div class="panel-group">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h5 class="panel-title">
          <a data-toggle="collapse" href="#collapse1"><?php echo $pr!==null ? '<h5>Purchase Request (PR): '. $pr->pr_number.'</h5>':"" ?></a>
        </h5>
      </div>
      <div id="collapse1" class="panel-collapse collapse <?php echo $pr->status === null?'':'in';?>">
        <div class="panel-body">
        
     <?php if ($pr!==null)
{
echo '<div class="alert alert-info">';
	
	 echo '<ul>';
	 echo '<li>Description	: <strong>' .$pr->description	 . '</strong></li>';
	 echo '<li>Created on		: <strong>' .$pr->requested_on . '</strong> by <strong>' . $pr->requester . '</strong></li>';
	 echo '<li>Updated on		: <strong>' .$pr->last_change . '</strong></li>';
	 echo '<li>Latest Status		: <strong>' .$pr->status .  '</strong> by <strong>' .$pr->changed_by . '</strong></li>';
	 
	 echo '</ul>';
	 echo '</div>';
} 
?>
        </div>
     </div>
    </div>
  </div>        

 

<?php  	if (count($pr_items) >0): ?>



<?php  	if ($pr->status!=='Approved'): ?>
<button title="Submit PR to Procurment" class="btn btn-default" onclick="openConfirmation('<?php echo $pr->id?>');" type="button"><i class="icon-ok">  </i> Approve</button>
<?php  	endif; ?>
 <hr>
<a href="/application/pdf/pr?id=<?php echo $pr->id ?>"  target="_blank"><i class="icon-download-alt">  </i> PDF</a>    	




<table class="table table-striped table-bordered">
	<thead>
		<tr>
			<td><b>No.</b></td>
			<td><b>Item Name</b></td>
			<td><b>Unit</b></td>
			<td><b data-toggle="tooltip" title="Ordred Quantity">Requested <br>Quantity</b></td>
			<td><b data-toggle="tooltip" title="Delivered Quantity">Delivered<br>Quantity</b></td>
			<td><b data-toggle="tooltip" title="Rejected Quantity">Rejected <br>Quantity</b></td>
			<td><b data-toggle="tooltip" title="Balance">Balance</b></td>
			<td><b data-toggle="tooltip" title="Free">Free</b></td>
			<td><b data-toggle="tooltip" title="Unconfirmed Quantity">Notified<br> Quantity</b></td>
			<td><b>EDT</b></td>
			<td><b>Last Vendor</b></td>
			<td><b>Last Price</b></td>
		</tr>
	</thead>
	<tbody>	
  <?php
	$count = 0;
	foreach ( $pr_items as $item ) :
		$count ++;
		// echo ($count % 2 == 1) ? "<tr>" : "<tr class=\"pure-table-odd\">";
		?>
		<tr>
			<td><?php echo ($paginator===null)? $count:$paginator->minInPage -1+ $count;?></td>

			<td>
				<div class="dropdown">
					<a class="dropdown-toggle" type="button" data-toggle="dropdown"
						href="#"><span style="color:black;"><b><?php echo $item->name;?></b></span>
						
    <span class="caret"></span></a>
					<ul class="dropdown-menu">
						<li><a href="#"><i class="icon-tag"> </i> Process</a></li>
     	
    	<?php if ($item->confirmed_balance > 0) : ?>
   			
   		<?php if ($item->total_saved_delivered_quantity > 0) : ?>
   			<li><a href="/procurement/delivery/review-cart"><i class="icon-check"> </i> Review Delivery	</a></li>	
    	<?php else: ?>
    		<li><a href="/procurement/delivery/add-to-cart?pr_item_id=<?php echo $item->id?>"><i class="icon-check"> </i> Delivery</a></li>
   	
    	<?php endif; ?>
   				
    	<?php endif; ?>
	
     	
      	<li class="divider"></li>
        
        <?php
		if ($item->article_id > 0) :
			?>
        <li><a
							href="/inventory/article/show?id=<?php echo $item->article_id;?>"><i
								class="icon-list"> </i> Detail</a></li>
		<?php endif; ?>
		
		 <?php if ($item->sparepart_id > 0) : ?>
     	<li><a
							href="/inventory/spareparts/show?id=<?php echo $item->sparepart_id;?>"><i
								class="icon-list"> </i> Detail</a></li>
		<?php endif; ?>
	
		
		     
         <li><a href="#"><i class="icon-signal"></i> Order History</a></li>
						<li><a href="#"><i class="icon-film"></i> Picture</a></li>
					</ul>
				</div>
			
			<div style="color: gray;">
				Code: <?php echo $this->escapeHtml($item->code);?><br>
				</div>
		


			</td>
			<td><?php echo $item->unit;?></td>
			<td><?php echo $item->quantity;?></td>
			<td><?php echo $item->confirmed_quantity;?></td>
			<td><?php echo $item->rejected_quantity;?></td>
			<td><?php echo $item->confirmed_balance;?></td>
			<td><?php echo $item->confirmed_free_balance;?></td>
			<td><?php echo $item->unconfirmed_quantity;?></td>
		
		<?php if($item->confirmed_balance == 0): ?>
			<td><?php echo date_format(date_create($item->EDT),"Y-m-d");?>
			<div>
			<span class="label label-success">Fulfilled</span>
			</div>
			</td>
		<?php else: ?>		
			<td><span id="<?php echo $item->id;?>_EDT"><?php echo date_format(date_create($item->EDT),"Y-m-d");?></span>
			<div>
			<span style="color: gray; font-size: 8pt; font-style: italic; " id="<?php echo $item->id;?>_timer"></span>
			</div></td>
		<?php endif; ?>	

			<td>
			<?php if($item->article_id>0): ?>			
<a
				href="<?php echo $this->baseUrl ?>/procurement/vendor/show?id=<?php echo $item->article_vendor_id;?>"
				target="_blank"><?php echo $item->article_vendor_name;?></a>
			<?php endif;?>
			<?php if($item->sparepart_id>0): ?>			
<a
				href="<?php echo $this->baseUrl ?>/procurement/vendor/show?id=<?php echo $item->sp_vendor_id;?>"
				target="_blank"><?php echo $item->sp_vendor_name;?></a>
			<?php endif;?>
			</td>
			<td>
		<?php
		if ($item->article_id > 0) :
			echo $item->article_price . ' '. $item->article_currency;;
		
		endif;
		
		if ($item->sparepart_id > 0) :
			echo $item->sp_price . ' '. $item->sp_currency;
		
		endif;
		?>
			</td>

	
			<script language="javascript">
			id_array.push(<?php echo $item->id;?>);
		</script>
		</tr>

	<?php endforeach; ?>
</tbody>
</table>
<br>

<?php
	
	if (! is_null ( $paginator )) {
		
		// change it only
		$base = $this->baseUrl . '/procurement/pr/pr-items?department_id=' . $department_id . '&last_status=' . $last_status
		. '&balance=' . $balance . '&unconfirmed_quantity=' . $unconfirmed_quantity.'&added_delivery_list=' . $added_delivery_list;
		
		$_connector_symbol = '&';
		
		$last = $base . $_connector_symbol . 'page=' . $paginator->totalPages . '&perPage=' . $paginator->resultsPerPage;
		$first = $base . $_connector_symbol . 'page=1&perPage=' . $paginator->resultsPerPage;
		
		$p1 = ($paginator->page) - 1;
		$p2 = ($paginator->page) + 1;
		
		$prev = $base . $_connector_symbol . 'page=' . $p1 . '&perPage=' . $paginator->resultsPerPage;
		$next = $base . $_connector_symbol . 'page=' . $p2 . '&perPage=' . $paginator->resultsPerPage;
		
		echo '<ul class="pagination">';
		
		if ($paginator->page != 1 and $paginator->totalPages > 10) {
			echo '<li><a href="' . $first . '"> |< </a></li>';
			echo '<li><a href="' . $prev . '"> < </a></li>';
		}
		
		for($i = $paginator->minInPageSet; $i <= $paginator->maxInPageSet; $i ++) {
			
			$url = $base . $_connector_symbol . 'page=' . $i . '&perPage=' . $paginator->resultsPerPage;
			
			if ($i == $paginator->page) {
				echo '<li><a class="active" href="#">' . $i . '</a></li>';
			} else {
				echo '<li><a href="' . $url . '"> ' . $i . ' </a></li>';
			}
		}
		if ($paginator->page != $paginator->totalPages and $paginator->totalPages > 10) {
			echo '<li><a href="' . $next . '"> > </a></li>';
			echo '<li><a href="' . $last . '"> >| </a></li>';
		}
		echo '</ul>';
	}
	
	?>




	

 
 
 <?php
else :
	echo 'No Items found ...';


endif;
 ?>
 

<!-- Modal -->
	<div id="myModal" class="modal hide" role="dialog">
	  <div class="modal-dialog">
	  	 <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h5 class="modal-title">Mascot International (Laos)</h5>
      </div>
	      <div class="modal-body">
	        <p>Do you want to approve this Purchase Request?</p>
	      </div>
	      
		  <div class="modal-footer">
	        <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
	        <button onclick="approvePR('<?php echo $pr->id?>');" type="button" class="btn btn-primary">OK</button>
	      </div>
	   </div>
	</div>	
	
	<!-- Modal -->
	<div id="myModal1" class="modal hide" role="dialog">
	  <div class="modal-dialog">
	      <div class="modal-body">
	        <p>Sending data........Please Wait!</p>
	      </div>
	   </div>
	</div>	
 