<script language="javascript">
			var id_array = [];
</script>

<!--  
<span class="label label-info"><?php echo count($pr_items) . ' PR - Items'?></span>

-->
 
<?php  	if (count($cart_items) >0): ?>
 
 <div class="control-group">
        <label class="control-label" for="inputTag"><b>PR Number:</b></label>
        <div class="controls">
          <input type="text" id="pr_number" placeholder="Please enter PR Number" name="pr_number" value="">
        </div>
      </div> 	
  	
	
<table class="pure-table pure-table-bordered">
<thead>
<tr>	
  		<td><input type="checkbox" id="select_ALL" name="SelectAll" value="YES"/> <b>All</b> </td>
 
		<td><b>Item</b></td>
		<td><b>Priority</b></td>
		<td><b>Name</b></td>
		<td><b>Unit</b></td>
		<td><b>Code</b></td>
		<td><b>Quantity</b></td>
		<td><b>EDT</b></td>
		<td><b>Count Down</b></td>
		<td><b>Asset Name</b></td>
		<td><b>Remarks</b></td>
		<td><b>Action</b></td>
		
	</tr>
</thead>
<tbody>	
 
  <?php 
   	
	 $count = 0;
	 foreach ($cart_items as $item) : 
	 	 $count++;
	 echo  ($count % 2 == 1) ? "<tr>" : "<tr class=\"pure-table-odd\">";
	 
	 	 
	 ?>
	 	<td><input class="checkbox1" type="checkbox" name="cart_items[]" value="<?php echo $item->id ;?>"/></td>
 
		<td><?php echo $count;?></td>
		<td><?php echo $item->priority=='Urgent'? '<span class="label label-warning">'. $item->priority .'</span>':$item->priority;?></td> 	
		<td><?php echo $item->name;?></td>
		<td><?php echo $item->code;?></td>
		<td><?php echo $item->unit;?></td>
		<td><?php echo $item->quantity;?></td>
		<td><span id="<?php echo $item->id;?>_EDT"><?php echo date_format(date_create($item->EDT),"Y-m-d");?></span></td>
		<td><span id="<?php echo $item->id;?>_timer"></span></td>
		<td><?php echo $item->asset_name;?></td>
		<td><?php echo $item->remarks;?></td>
		<td>
		<a href="<?php echo $this->baseUrl ?>/procurement/pr/edit-cart-item?id=<?php echo $this->escapeHtml($item->id);?>">Edit</a>
		<a href="#" onclick="deleteCartItemDialog('<?php echo $this->escapeHtml($item->id)?>');">Delete</a>
		</td>		
		
		</tr>
		
		<script language="javascript">
			id_array.push(<?php echo $item->id;?>);
		</script>
		

<?php endforeach; ?>

 			

</tbody>
</table>
<hr>

 <form class="form-search" action="<?php echo $this->baseUrl ?>/inventory"	method="get" enctype="multipart/form-data">
      <button type="submit" class="btn"><i class="icon-arrow-left">  </i> Back</button>
      <button title="Submit PR to Procurment" class="btn btn-default" onclick="openSubmitCartConfirmation(1);" type="button"><i class="icon-ok">  </i> Submit</button>
</form>
<?php else: echo '<div class="alert alert-warning">
  Order List is currently empty!</div>' ?>


 <form class="form-search" action="<?php echo $this->baseUrl ?>/inventory"	method="get" enctype="multipart/form-data">
      <button type="submit" class="btn"><i class="icon-arrow-left">  </i> Back</button>
 </form>

<?php endif; ?>


<!-- Modal -->
	<div id="myModal" class="modal hide" role="dialog">
	  <div class="modal-dialog">
	  	 <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h5 class="modal-title">Mascot International (Laos)</h5>
      </div>
	      <div class="modal-body">
	        <p>Do you want to complete and submit Purchase Request <span id="submitted_id"></span>?</p>
	      </div>
		  <div class="modal-footer">
	        <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
	        <button onclick="submitCartItems();" type="button" class="btn btn-primary">OK</button>
	      </div>
	   </div>
	</div>
	
	
	<!-- Modal -->
	<div id="myModal1" class="modal hide" role="dialog">
	  <div class="modal-dialog">
	      <div class="modal-body">
	        <span id="modad_body_text">Working on it........Please Wait!</span>
	      </div>
	   </div>
	</div>
	
	<div id="message_modal" class="modal hide" role="dialog">
	  <div class="modal-dialog">
	  		  	 <div class="modal-header">
        		<button type="button" class="close" data-dismiss="modal">&times;</button>
        <h5 class="modal-title">Mascot International (Laos)</h5>
      </div>
	  	
	      <div class="modal-body">
	        <span id="message_modal_content">Working on it........Please Wait!</span>
	      </div>
	       <div class="modal-footer">
	        <button type="button" class="btn btn-primary" data-dismiss="modal">OK</button>
	        </div>
	   </div>
	</div>
	
	<div id="myModal2" class="modal hide" role="dialog">
	  <div class="modal-dialog">
	  	 <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h5 class="modal-title">Mascot International (Laos)</h5>
      </div>
	      <div class="modal-body">
	      	<span id="cart_item_to_delete"></span>
	        <p>Do you want to delete Order Item <span id="cart_item_to_delete_id"></span>?</p>
	      </div>
	      
		  <div class="modal-footer">
	        <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
	        <button onclick="deleteCartItem();" type="button" class="btn btn-primary">OK</button>
	      </div>
	   </div>
	</div>			