<script language="javascript">
			var id_array = [];
</script>

<!--  
<span class="label label-info"><?php echo count($pr_items) . ' PR - Items'?></span>

-->
 <div class="control-group">
        <label class="control-label" for="inputTag">PR Number:</label>
        <div class="controls">
          <input type="text" id="pr_number" placeholder="" name="pr_number" value="PR-FA-2016-0001">
        </div>
      </div>
<?php  	if (count($cart_items) >0): ?>
  	
<table class="pure-table pure-table-bordered"">
<thead>
<tr>	
		<td><b>Item</b></td>
		<td><b>Priority</b></td>
		<td><b>Name</b></td>
		<td><b>Unit</b></td>
		<td><b>Quantity</b></td>
	<td><b>EDT</b></td>
		<td><b>Count Down</b></td>
		<td><b>Action</b></td>
		
	</tr>
</thead>
<tbody>	
 
  <?php 
   	
	 $count = 0;
	 foreach ($cart_items as $item) : 
	 	 $count++;
	 echo  ($count % 2 == 1) ? "<tr>" : "<tr class=\"pure-table-odd\">";
	 
	 	 
	 ?>
		<td><?php echo $count;?></td>
		<td><?php echo $item->priority=='Urgent'? '<span class="label label-warning">'. $item->priority .'</span>':$item->priority;?></td> 	
		<td><?php echo $item->name;?></td>
			<td><?php echo $item->unit;?></td>
		<td><?php echo $item->quantity;?></td>
			<td><span id="<?php echo $item->id;?>_EDT"><?php echo date_format(date_create($item->EDT),"Y-m-d");?></span></td>
			<td><span id="<?php echo $item->id;?>_timer"></span></td>
			<td><b><?php echo $item->id;?></b></td>
		
		</tr>
		
		<script language="javascript">
			id_array.push(<?php echo $item->id;?>);
		</script>
		

<?php endforeach; ?>

 			

</tbody>
</table>
<hr>
<?php else: echo 'please add items!' ?>


<?php endif; ?>
 <form class="form-search" action="<?php echo $this->baseUrl ?>/inventory"	method="get" enctype="multipart/form-data">
      <button type="submit" class="btn"><i class="icon-arrow-left">  </i> Back</button>
            <button title="Submit PR to Procurment" class="btn btn-default" onclick="openConfirmation(1);" type="button"><i class="icon-ok">  </i> Submit</button>
 
</form>

<!-- Modal -->
	<div id="myModal" class="modal hide" role="dialog">
	  <div class="modal-dialog">
	  	 <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h5 class="modal-title">Mascot International (Laos)</h5>
      </div>
	      <div class="modal-body">
	        <p>Do you want to complete and submit this Purchase Request?</p>
	      </div>
	      
		  <div class="modal-footer">
	        <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
	        <button onclick="submitCartItems();" type="button" class="btn btn-primary">OK</button>
	      </div>
	   </div>
	</div>	
	
	<!-- Modal -->
	<div id="myModal1" class="modal hide" role="dialog">
	  <div class="modal-dialog">
	      <div class="modal-body">
	        <p>Working on it........Please Wait!</p>
	      </div>
	   </div>
	</div>	