
<?php 
if($layout!="ajax"):
	include (ROOT.'\module\Procurement\view\procurement\menu.php'); 
endif;
?>

<script language="javascript">
			var id_array = [];
</script>

<h4>Order History:</h4>


<?php if(count($pr_items)>0):?>
<?php echo count($pr_items). " Order Found!"?>
<table class="table table-striped table-bordered">
	<thead>

		<tr>
			<td><b>#</b></td>
			<td><b>PR#</b></td>
			<td><b>PR Number</b></td>
		
			<td><b>Item Name</b></td>
			<td><b data-toggle="tooltip" title="Ordred Quantity">Requested <br>Quantity</b></td>
			<td><b data-toggle="tooltip" title="Ordred Quantity">Balance</b></td>
			<td><b data-toggle="tooltip" title="Ordred Quantity">Order Date</b></td>
			<td><b data-toggle="tooltip" title="Ordred Quantity">Status</b></td>
		
		</tr>
	</thead>
	<tbody>	
  <?php
	$count = 0;
	foreach ( $pr_items as $item ) :
		$count ++;
		// echo ($count % 2 == 1) ? "<tr>" : "<tr class=\"pure-table-odd\">";
		?>
		<tr>
			<td><?php echo $count;?></td>
			<td>		
			<a data-toggle="tooltip" title="Detail of PR#<?php echo $item->pr_id;?>" style="font-size: 8pt;"
						href="<?php echo $this->baseUrl ?>/procurement/pr/show?pr_id=<?php echo $item->pr_id;?>"
						target="_blank">PR#<?php echo $item->pr_id;?></a>
	</td>
			<td><?php echo $item->pr_number;?></td>
			<td><?php echo $item->name;?></td>
			<td><?php echo $item->quantity;?></td>
			<td><?php echo $item->balance;?></td>
			<td><?php echo $item->created_on;?></td>
			<td>N/A</td>
	
	
		</tr>
	<?php endforeach; ?>
</tbody>
</table>
<br>

 
 <?php

else :
	echo 'No Items found ...';

endif;
?>
 
 