 <form class="form-search" action="<?php echo $this->baseUrl ?>/procurement/"	method="get" enctype="multipart/form-data">
      <button type="submit" class="btn"><i class="icon-arrow-left">  </i> Back</button>
</form>
<hr>

<h4>My Purchase Requests:</h4>

<ul class="nav nav-pills">
 <li><a href="<?php echo $this->baseUrl ?>/procurement/pr/create-step1">Create New PR</a></li>
 </ul>


<?php if(count($my_pr) >0): 
	echo count($my_pr) . ' PRs found'?>
<table class="pure-table pure-table-bordered">
<thead>
<tr>	
		<td><b>Name</b></td>
		<td><b>Name</b></td>
		<td><b>Description</b></td>
		<td><b>Requester</b></td>
		<td><b>Created on</b></td>
		<td><b>Latest Status</b></td>
		<td><b>Last change by</b></td>
		<td><b>Updated on</b></td>
		
		<td><b>Action</b></td>
	</tr>
</thead>
<tbody>	
 
  <?php 
	 
	 $count = 0;
	 foreach ($my_pr as $item) : 
	 	 $count++;
	 echo  ($count % 2 == 1) ? "<tr>" : "<tr class=\"pure-table-odd\">";
	 ?>
	 	<td><?php echo $item->auto_pr_number;?> <span class="label label-info"><?php echo $item->tItems;?></span></td> 	
	
		<td><?php echo $item->pr_number;?></td> 	
		<td><?php echo $item->description;?></td>
		<td><?php echo $item->requester;?></td>
		
		<td><?php echo date_format(date_create($item->requested_on),"Y-m-d");?></td>
		<td><?php echo $item->status ===null?'Started':$item->status;?></td>
		<td><?php echo $item->changed_by;?></td>
		<td><?php echo $item->last_change;?></td>
		<td>
		<a
			href="<?php echo $this->baseUrl ?>/procurement/pr/create-step2?pr_id=<?php echo $item->id;?>"><?php echo $item->status ===null?'Edit':'Show';?>
		</a>
		
		
	</td>
<?php endforeach; ?>
</tbody>
</table>
<?php else:
echo 'No PRs found ...';

endif;
 ?>
