
<?php 
if($layout!="ajax"):
	include (ROOT.'\module\Procurement\view\procurement\menu.php'); 
endif;
?>

<script language="javascript">
			var id_array = [];
</script>

<h4>Order History:</h4>


<?php if(count($pendings)>0):?>
<?php echo count($pendings). " Items Found!"?>
<table class="table table-striped table-bordered">
	<thead>

		<tr>
			<td><b>#</b></td>
			<td><b>PR#</b></td>
			<td><b>PR Number</b></td>
			<td><b data-toggle="tooltip" title="Ordred Quantity">Order Date</b></td>
		
			<td><b data-toggle="tooltip" title="Ordred Quantity">Requested <br>Quantity</b></td>
			<td><b data-toggle="tooltip" title="Ordred Quantity">Balance</b></td>
			<td><b data-toggle="tooltip" title="Ordred Quantity">Status</b></td>
		
		</tr>
	</thead>
	<tbody>	
  <?php
	$count = 0;
	foreach ( $pendings as $item ) :
		$count ++;
		// echo ($count % 2 == 1) ? "<tr>" : "<tr class=\"pure-table-odd\">";
		?>
		<tr>
			<td><?php echo $count;?></td>
			<td><?php echo $item->purchase_request_id;?></td>	
			<td><?php echo $item->pr_number;?></td>		
			<td><?php echo $item->created_on;?></td>
			<td><?php echo $item->quantity;?></td>
			<td><?php echo $item->confirmed_balance;?></td>
			<td>N/A</td>
	
	
		</tr>
	<?php endforeach; ?>
</tbody>
</table>
<br>

 
 <?php

else :
	echo 'No Items found ...';

endif;
?>
 
 