
<?php include (ROOT.'\module\Procurement\view\procurement\menu.php'); ?>
<script language="javascript">
			var id_array = [];
</script>

<h4>All PR Items:</h4>

<?php

if ($pr_year == 0 or $balance == $pr_year) :
	$pr_year_selected = "PR Year = All";
else:
	$pr_year_selected = "PR Year =" . $pr_year;
endif;



if ($department_id == 0 or $department_id == null) :
	$department_selected = "Department = All";
endif;

if ($balance == 2 or $balance == null) :
	$balance_selected = "Balance = All";
endif;

if ($balance == 0) :
	$balance_selected = "Balance = 0 (Fulfilled Items)";
endif;

if ($balance == 1) :
	$balance_selected = 'Balance >0 <span style="color:red;">(Pending Items)</span>';
endif;

if ($balance == - 1) :
	$balance_selected = "Balance <0 (Some free items)";
endif;

if ($processing == "2") :
	$processing_selected = "Processing Status = All";
 else :
	$processing_selected = "Processing = " . $processing;
endif;

if ($sort_by == "" or $sort_by == null) :
	$sort_by_selected = "Sort = None";
 else :
	$sort_by_selected = "Sort by = " . $sort_by;
endif;

?>


<div class="panel-group">
	<div class="panel panel-default">
		<div class="panel-heading">
			<h5 class="panel-title">
				<a data-toggle="collapse" href="#collapse1"><i class="icon-filter">
				</i> FILTER</a>
			</h5>
		</div>

		<div id="collapse1"
			class="panel-collapse collapse <?php echo count($pr_items)>0?"":"in"?>">
			<div class="panel-body">
				<div
					style="padding: 3px; background: url(/images/bg1.png); background-repeat: repeat-x; background-color: #FFFFFF;">
					<form class="form-horizontal"
						action="<?php echo $this->baseUrl ?>/procurement/pr/pr-items"
						method="get" enctype="multipart/form-data" id="ReportForm">
						
		<div class="control-group">
        <label class="control-label" for="inputNameLocal">PR by Year: </label>
        <div class="controls">
        	<select name="pr_year" >
        		<option value="0">All</option>
   	    		<option <?php echo $pr_year=='2016'? "selected='selected'":"";?> value="2016">2016</option>
   	    		<option <?php echo $pr_year=='2017'? "selected='selected'":"";?> value="2017">2017</option>
   	    		<option <?php echo $pr_year=='2018'? "selected='selected'":"";?> value="2018">2018</option>
   	 			<option <?php echo $pr_year=='2019'? "selected='selected'":"";?> value="2019">2019</option>
   	 			<option <?php echo $pr_year=='2020'? "selected='selected'":"";?> value="2020">2020</option>
   			</select>
	     </div>
      </div>
						
						<div class="control-group">
							<label class="control-label" for="inputNameLocal">PR by
								Department: </label>
							<div class="controls">
								<select name="department_id">
									<option value="">All departments</option>
   	    	<?php
									
									foreach ( $departments as $dept ) :
										if ($dept->id === $department_id) :
											$department_selected = "Department = " . $dept->name;
											echo '<option selected="selected" value="' . $dept->id . '">' . $dept->name . '</option>';
										 else :
											echo '<option value="' . $dept->id . '">' . $dept->name . '</option>';
										endif;
									endforeach
									;
									?>
   	
   			</select>
							</div>
						</div>

						<div class="control-group">
							<label class="control-label" for="inputNameLocal">Balance: </label>
							<div class="controls">
								<select name="balance">
									<option value="2">All</option>
									<option <?php echo $balance=='0'? "selected='selected'":"";?>
										value="0">Balance=0 (Fulfilled Items)</option>
									<option <?php echo $balance=='1'? "selected='selected'":"";?>
										value="1">Balance>0 (Pending Items)</option>
									<option <?php echo $balance=='-1'? "selected='selected'":"";?>
										value="-1">Balance<0 (Some Free Items)</option>

								</select>
							</div>
						</div>


						<div class="control-group">
							<label class="control-label" for="inputNameLocal">In processing:
							</label>
							<div class="controls">
								<select name="processing">
									<option value="2">All</option>
									<option
										<?php echo $processing=='0'? "selected='selected'":"";?>
										value="0">NO</option>
									<option
										<?php echo $processing=='1'? "selected='selected'":"";?>
										value="1">YES</option>
								</select>
							</div>
						</div>

						<div class="control-group">
							<label class="control-label" for="inputNameLocal">Sort by: </label>
							<div class="controls">
								<select name="sort_by">
									<option value="">None</option>
									<option
										<?php echo $sort_by=='pr_number'? "selected='selected'":"";?>
										value="pr_number">PR Number</option>

									<option
										<?php echo $sort_by=='requester_name'? "selected='selected'":"";?>
										value="requester_name">Requester Name</option>

									<option
										<?php echo $sort_by=='item_name'? "selected='selected'":"";?>
										value="item_name">Item Name</option>

									<option <?php echo $sort_by=='EDT'? "selected='selected'":"";?>
										value="EDT">Expected Delivery Date</option>
								</select>

							</div>
						</div>

						<div class="control-group">
							<label class="control-label" for="inputNameLocal">Result per
								page: </label>
							<div class="controls">
								<select name="perPage">
									<option value="">None</option>
									<option <?php echo $per_pape=='10'? "selected='selected'":"";?>
										value="10">10</option>

									<option <?php echo $per_pape=='15'? "selected='selected'":"";?>
										value="15">15</option>

									<option <?php echo $per_pape=='20'? "selected='selected'":"";?>
										value="20">20</option>

									<option <?php echo $per_pape=='50'? "selected='selected'":"";?>
										value="50">50</option>
									<option
										<?php echo $per_pape=='100'? "selected='selected'":"";?>
										value="100">100</option>
								</select>

							</div>
						</div>

						<div class="control-group">
							<div class="controls">
								<button type="submit" class="btn">
									<i class="icon-search"> </i> show
								</button>
							</div>
						</div>
					</form>

				</div>

			</div>
		</div>
	</div>
</div>
<hr>

<?php
if (! is_null ( $paginator )) :
	echo '<h5>' . $paginator->getMinInPage() . ' to ' . $paginator->getMaxInPage() . ' of ' . $total_items . ' Item(s) found | ' . 
	$pr_year_selected. ' | '. $department_selected . ' | ' . $balance_selected . ' | ' . $processing_selected . ' | ' . $sort_by_selected . ' | ' . '</h5>';
 else :
	echo '<h5>' . $total_items . ' Item(s) found | ' . 
	$pr_year_selected. ' | ' . $department_selected . ' | ' . $balance_selected . ' | ' . $processing_selected . ' | ' . $sort_by_selected . ' | ' . '</h5>';
endif;
?>
<?php if (count ( $pr_items ) > 0) : ?>

<ul class="nav nav-pills">
<?php
	echo '<li><a href="/procurement/pr/pr-items?output=csv&department_id=' . $department_id . '&last_status=' . $last_status . '&balance=' . $balance . '&unconfirmed_quantity=' . $unconfirmed_quantity . '&processing=' . $processing . '&sort_by=' . $sort_by . '"><i class="icon-download-alt"> </i> Download (CSV)</a> </li>';
	?>
</ul>



<table class="table table-striped table-bordered">
	<thead>

		<tr>
			<td><b>#</b></td>
			<td><b>Status</b></td>
			<td><b>Item Name</b></td>
			<td><b>PR Number</b></td>
			<td><b>Unit</b></td>
			<td><b data-toggle="tooltip" title="Ordred Quantity">Ordered <br>Quantity
			</b></td>
			<td><b data-toggle="tooltip" title="Bought Quantity">Received<br>Quantity
			</b></td>
			<td><b data-toggle="tooltip" title="Notified Quantity">Notified<br>Quantity
			</b></td>
			<td><b data-toggle="tooltip" title="Notified Quantity">Confirmed<br>Quantity
			</b></td>
			<td><b data-toggle="tooltip" title="Rejected Quantity">Rejected <br>Quantity
			</b></td>
			<td><b data-toggle="tooltip" title="Balance">Balance</b></td>
			<td><b data-toggle="tooltip" title="Free">Free</b></td>
			<td><b>EDT</b></td>
			<td><b>Last Purchase</b></td>
		</tr>
	</thead>
	<tbody>	
  <?php
	$count = 0;
	foreach ( $pr_items as $item ) :
		$count ++;
		// echo ($count % 2 == 1) ? "<tr>" : "<tr class=\"pure-table-odd\">";
		?>
		<tr>
			<td><?php echo ($paginator===null)? $count:$paginator->getMinInPage() -1+ $count;?></td>
			<td>
				<div style="font-size: 8pt;">
			    <?php if ($item->confirmed_balance > 0) : ?>
   				<?php if ($item->po_item_id > 0) : ?>
   					<span style="font-size: 7pt;" class="label label-info">Buying</span>
   				<?php else: ?>
   					<span style="color: red;"><b>Pending</b></span>
   				<?php endif; ?>
   				
   				  				<?php else: ?>
   				<span style="font-size: 7pt;" class="label label-success">Fulfilled</span>
   				
   				<?php endif; ?>
   				
   					<div style="color: gray; font-size: 8pt;">
						<span data-toggle="tooltip" title="Priotiry"><?php echo $item->priority=='Urgent'? '<span class="label label-warning" >'. $item->priority .'</span>':$item->priority;?></span><br>
					</div>
				</div>
			</td>
			<td>
				<div class="dropdown">
					<a class="dropdown-toggle" type="button" data-toggle="dropdown"
						href="#"><span style="color: black;"><b><?php echo $item->name;?></b></span>
						<span class="caret"></span></a>
					<ul class="dropdown-menu">
	    	
    	<?php if ($item->confirmed_balance > 0) : ?>
   			
   		<?php if ($item->po_item_id > 0) : ?>
   			<li><a href="/procurement/do/receive?pr_item_id=<?php echo $item->id;?>&po_item_id=<?php echo $item->po_item_id;?>"><iclass="icon-check"> </i> Receive </a></li>
			<li class="divider"></li>
			<li><a href="<?php echo $this->baseUrl ?>/procurement/po/edit-item?id=<?php echo $this->escapeHtml($item->po_item_id)?>&pr_item_id=<?php echo $this->escapeHtml($item->id);?>"><i class="icon-pencil"></i> Edit PO Item</a></li>  	
    	
    	<?php else: ?>
    		<li><a href="/procurement/po/add-to-cart?pr_item_id=<?php echo $item->id?>"><i class="icon-check"> </i> Purchase</a></li>
   	
    	<?php endif; ?>
   				
    	<?php endif; ?>
	  
	  	<li class="divider"></li>
        
        <?php
		if ($item->article_id > 0) :
			?>
        <li><a
							href="/inventory/article/show?id=<?php echo $item->article_id;?>"
							target="_blank"><i class="icon-list"> </i> Detail</a></li>
		<?php endif; ?>
		
		 <?php if ($item->sparepart_id > 0) : ?>
     	<li><a
							href="/inventory/spareparts/show?id=<?php echo $item->sparepart_id;?>"
							target="_blank"><i class="icon-list"> </i> Detail</a></li>
		<?php endif; ?>
	
		
		     
        	 <li><a
							href="/procurement/pr/history?sparepart_id=<?php echo $item->sparepart_id;?>&article_id=<?php echo $item->article_id;?>"><i
								class="icon-signal"></i> Order History</a></li>
					</ul>
				</div>

				<div style="color: gray; font-size: 8pt;">
				Code: <?php echo $this->escapeHtml($item->code);?><br>
				</div>
			</td>
			<td><span data-toggle="tooltip"
				title="<?php echo $item->pr_requester_name;?>"><?php echo $item->pr_number;?></span>
				<div style="color: gray; font-size: 8pt;">
					<a data-toggle="tooltip"
						title="Detail of PR#<?php echo $item->purchase_request_id;?> by <?php echo $item->pr_requester_name;?> - <?php echo $item->pr_of_department;?>"
						style="font-size: 8pt;"
						href="<?php echo $this->baseUrl ?>/procurement/pr/process?pr_id=<?php echo $item->purchase_request_id;?>"
						target="_blank">PR#<?php echo $item->purchase_request_id;?></a>
				</div></td>
			<td><?php echo $item->unit;?></td>
			<td><?php echo $item->quantity;?></td>
			<td><?php echo $item->total_received_quantity;?></td>
			<td><?php echo $item->unconfirmed_quantity;?></td>
			<td><?php echo $item->confirmed_quantity;?></td>
			<td><?php echo $item->rejected_quantity;?></td>
			<td><?php echo $item->confirmed_balance;?></td>
			<td><?php echo $item->confirmed_free_balance;?></td>
		
		<?php if($item->confirmed_balance == 0): ?>
			<td><?php echo date_format(date_create($item->EDT),"Y-m-d");?>
			<div>
					<span style="font-size: 7pt;" class="label label-success">Fulfilled</span>
				</div></td>
		<?php else: ?>		
			<td><span id="<?php echo $item->id;?>_EDT"><?php echo date_format(date_create($item->EDT),"Y-m-d");?></span>
				<div>
					<span style="color: gray; font-size: 8pt; font-style: italic;"
						id="<?php echo $item->id;?>_timer"></span>
				</div></td>
		<?php endif; ?>	

			<td>
				<?php if($item->article_id>0): ?>			
<a
				href="<?php echo $this->baseUrl ?>/procurement/vendor/show?id=<?php echo $item->article_vendor_id;?>"
				target="_blank"><?php echo $item->article_vendor_name;?></a>
			<?php endif;?>
			
			<?php if($item->sparepart_id>0): ?>			
<a
				href="<?php echo $this->baseUrl ?>/procurement/vendor/show?id=<?php echo $item->sp_vendor_id;?>"
				target="_blank"><?php echo $item->sp_vendor_name;?></a>
			<?php endif;?>
			
			<br> <span style="font-size: 9pt; font-style: italic;">
			<?php
		if ($item->article_id > 0) :
			if ($item->article_price > 0) :
				echo 'Unit price:' . $item->article_price . ' ' . $item->article_currency;
				;
			
			
			
			
				endif;
		
		
		
		
		endif;
		
		if ($item->sparepart_id > 0) :
			if ($item->sp_price > 0) :
				echo 'Unit price:' . $item->sp_price . ' ' . $item->sp_currency;
			
			
			
			
			
			endif;
		
		
		
		
		
		endif;
		?>
			</span>
			</td>

			<script language="javascript">
			id_array.push(<?php echo $item->id;?>);
		</script>
		</tr>

	<?php endforeach; ?>
</tbody>
</table>
<br>

<?php
	
	if (! is_null ( $paginator )) {
		
		// change it only
		$base = $this->baseUrl . '/procurement/pr/pr-items?department_id=' . $department_id . '&last_status=' . $last_status . '&balance=' . $balance . '&unconfirmed_quantity=' . $unconfirmed_quantity . '&processing=' . $processing . '&sort_by=' . $sort_by;
		
		$_connector_symbol = '&';
		
		$last = $base . $_connector_symbol . 'page=' . $paginator->getTotalPages() . '&perPage=' . $paginator->getResultsPerPage();;
		$first = $base . $_connector_symbol . 'page=1&perPage=' . $paginator->getResultsPerPage();;
		
		$p1 = ($paginator->getPage()) - 1;
		$p2 = ($paginator->getPage()) + 1;
		
		$prev = $base . $_connector_symbol . 'page=' . $p1 . '&perPage=' . $paginator->getResultsPerPage();;
		$next = $base . $_connector_symbol . 'page=' . $p2 . '&perPage=' . $paginator->getResultsPerPage();;
		
		echo '<ul class="pagination">';
		
		if ($paginator->getPage() != 1 and $paginator->getTotalPages() > 10) {
			echo '<li><a href="' . $first . '"> |< </a></li>';
			echo '<li><a href="' . $prev . '"> < </a></li>';
		}
		
		for($i = $paginator->getMinInPageSet(); $i <= $paginator->getMaxInPageSet(); $i ++) {
			
			$url = $base . $_connector_symbol . 'page=' . $i . '&perPage=' . $paginator->getResultsPerPage();;
			
			if ($i == $paginator->getPage()) {
				echo '<li><a class="active" href="#">' . $i . '</a></li>';
			} else {
				echo '<li><a href="' . $url . '"> ' . $i . ' </a></li>';
			}
		}
		if ($paginator->getPage() != $paginator->getTotalPages() and $paginator->getTotalPages() > 10) {
			echo '<li><a href="' . $next . '"> > </a></li>';
			echo '<li><a href="' . $last . '"> >| </a></li>';
		}
		echo '</ul>';
	}
	
	?>




	

 
 
 
 
 
 
 <?php

else :
	echo 'No Items found ...';


endif;
?>
 
 