<script language="javascript">
			var id_array = [];
</script>

<h5>All PR Items:</h5>

<?php
$department_name = "All";
$status_name = $last_status;

if ($status_name == '') :
	$status_name = ' | PR status = All';
 else :
	$status_name = ' | PR status = ' . $last_status;
endif;

?>

<div class="panel-group">
	<div class="panel panel-default">
		<div class="panel-heading">
			<h5 class="panel-title">
				<a data-toggle="collapse" href="#collapse1"><i class="icon-filter">
				</i> FILTER</a>
			</h5>
		</div>

		<div id="collapse1"
			class="panel-collapse collapse <?php echo count($pr_items)>0?"":"in"?>">
			<div class="panel-body">
				<hr>
				<form class="form-horizontal"
					action="<?php echo $this->baseUrl ?>/procurement/pr/pr-items"
					method="get" enctype="multipart/form-data" id="ReportForm">
					<div class="control-group">
						<label class="control-label" for="inputNameLocal">PR by
							Department: </label>
						<div class="controls">
							<select name="department_id">
								<option value="">All departments</option>
   	    	<?php
									
									foreach ( $departments as $dept ) :
										if ($dept->id === $department_id) :
											$department_name = $dept->name;
											echo '<option selected="selected" value="' . $dept->id . '">' . $dept->name . '</option>';
										 else :
											echo '<option value="' . $dept->id . '">' . $dept->name . '</option>';
										endif;
									endforeach
									;
									?>
   	
   			</select>
						</div>
					</div>

					<div class="control-group">
						<label class="control-label" for="inputNameLocal">PR by Status: </label>
						<div class="controls">
							<select name="last_status">
								<option value="">All</option>
								<option
									<?php echo $last_status=='Submitted'? "selected='selected'":"";?>
									value="Submitted">Submitted</option>
								<option
									<?php echo $last_status=='Approved'? "selected='selected'":"";?>
									value="Approved">Approved</option>
								<option
									<?php echo $last_status=='Fulfilled'? "selected='selected'":"";?>
									value="Fulfilled">Fulfilled</option>

							</select>
						</div>
					</div>

					<div class="control-group">
						<label class="control-label" for="inputNameLocal">Balance: </label>
						<div class="controls">
							<select name="balance">
								<option value="2">All</option>
								<option <?php echo $balance=='0'? "selected='selected'":"";?>
									value="0">Balance=0</option>
								<option <?php echo $balance=='1'? "selected='selected'":"";?>
									value="1">Balance>0</option>
								<option <?php echo $balance=='-1'? "selected='selected'":"";?>
									value="-1">Balance<0 (Some Free)</option>

							</select>
						</div>
					</div>

					<div class="control-group">
						<label class="control-label" for="inputNameLocal">Delivery
							Notification: </label>
						<div class="controls">
							<select name="unconfirmed_quantity">
								<option value="2">All</option>
								<option
									<?php echo $unconfirmed_quantity=='0'? "selected='selected'":"";?>
									value="0">sent and confirmed</option>
								<option
									<?php echo $unconfirmed_quantity=='1'? "selected='selected'":"";?>
									value="1">sent but unconfirmed</option>


							</select>
						</div>
					</div>

					<div class="control-group">
						<label class="control-label" for="inputNameLocal">Processing:
							</label>
						<div class="controls">
							<select name="processing">
								<option value="2">All</option>
								<option
									<?php echo $processing=='0'? "selected='selected'":"";?>
									value="0">NO</option>
								<option
									<?php echo $processing=='1'? "selected='selected'":"";?>
									value="1">YES</option>
							</select>
						</div>
					</div>

					<div class="control-group">
						<div class="controls">
							<button type="submit" class="btn">
								<i class="icon-search"> </i> show
							</button>
						</div>
					</div>
				</form>



			</div>
		</div>
	</div>
</div>
<hr>

<form class="form-search"
	action="<?php echo $this->baseUrl ?>/procurement/" method="get"
	enctype="multipart/form-data">
	<button type="submit" class="btn">
		<i class="icon-arrow-left"> </i> Back
	</button>
</form>


<?php

if (count ( $pr_items ) > 0) :
	
	if (! is_null ( $paginator )) :
		echo '<h5>Result ' . $paginator->minInPage . ' to ' . $paginator->maxInPage . ' | ' . $total_items . ' Items found | Deparment = ' . $department_name . '' . $status_name . ' | ' . $balance . ' | ' . $unconfirmed_quantity . '</h5>';
	 else :
		echo '<h5>' . $total_items . ' Items found | Deparment = ' . $department_name . '' . $status_name . ' | ' . $balance . ' | ' . $unconfirmed_quantity . '</h5>';
	endif;
	?>

<table class="table table-striped table-bordered">
	<thead>
		<tr>
			<td><b>No.</b></td>
			<td><b>Item Name</b></td>
			<td><b>PR Number</b></td>
			<td><b>Unit</b></td>
			<td><b data-toggle="tooltip" title="Ordred Quantity">Requested <br>Quantity</b></td>
			<td><b data-toggle="tooltip" title="Bought Quantity">Received<br>Quantity
			<td><b data-toggle="tooltip" title="Notified Quantity">Notified<br>Quantity</b></td>
			<td><b data-toggle="tooltip" title="Notified Quantity">Confirmed<br>Quantity</b></td>
			<td><b data-toggle="tooltip" title="Rejected Quantity">Rejected <br>Quantity</b></td>
			<td><b data-toggle="tooltip" title="Balance">Balance</b></td>
			<td><b data-toggle="tooltip" title="Free">Free</b></td>
			
			</b></td>
			<td><b>EDT</b></td>
			<td><b>Last Purchase</b></td>
		</tr>
	</thead>
	<tbody>	
  <?php
	$count = 0;
	foreach ( $pr_items as $item ) :
		$count ++;
		// echo ($count % 2 == 1) ? "<tr>" : "<tr class=\"pure-table-odd\">";
		?>
		<tr>
			<td><?php echo ($paginator===null)? $count:$paginator->minInPage -1+ $count;?></td>

			<td>
				<div class="dropdown">
					<a class="dropdown-toggle" type="button" data-toggle="dropdown"
						href="#"><span style="color: black;"><b><?php echo $item->name;?></b></span>
					<span class="caret"></span></a>
					<ul class="dropdown-menu">
	    	
    	<?php if ($item->confirmed_balance > 0) : ?>
   			
   		<?php if ($item->po_item_id > 0) : ?>
   			<li><a href="/procurement/do/receive?pr_item_id=<?php echo $item->id;?>&po_item_id=<?php echo $item->po_item_id;?>"><i
								class="icon-check"> </i> Receive </a></li>	
    	<?php else: ?>
    		<li><a
							href="/procurement/po/add-to-cart?pr_item_id=<?php echo $item->id?>"><i
								class="icon-check"> </i> Purchase</a></li>
   	
    	<?php endif; ?>
   				
    	<?php endif; ?>
	
     	
      	<li class="divider"></li>
        
        <?php
		if ($item->article_id > 0) :
			?>
        <li><a
							href="/inventory/article/show?id=<?php echo $item->article_id;?>" target="_blank"><i
								class="icon-list" > </i> Detail</a></li>
		<?php endif; ?>
		
		 <?php if ($item->sparepart_id > 0) : ?>
     	<li><a
							href="/inventory/spareparts/show?id=<?php echo $item->sparepart_id;?>" target="_blank"><i
								class="icon-list"> </i> Detail</a></li>
		<?php endif; ?>
	
		
		     
         <li><a href="#"><i class="icon-signal"></i> Order History</a></li>
					</ul>
				</div>

				<div style="color: gray;">
				Code: <?php echo $this->escapeHtml($item->code);?><br>
				<?php if ($item->confirmed_balance > 0) : ?>
   				<?php if ($item->po_item_id > 0) : ?>
   				Status: <span class="label label-info">Processing...</span>
   				<?php else: ?>
   				Status: <span class="	">Pending</span>
   				<?php endif; ?>
   				<?php else: ?>
   				Status: <span class="label label-success">Fulfilled</span>
   				<?php endif; ?>
				</div>
			
			<td><?php echo $item->pr_number;?>
			<div style="color: gray; font-size: 8pt;">
			Dept.:<?php echo $item->pr_of_department;?><br>
			Priority:<?php echo $item->priority=='Urgent'? '<span class="label label-warning" >'. $item->priority .'</span>':$item->priority;?><br>
			<a style="color: black; font-size: 8pt;" href="<?php echo $this->baseUrl ?>/procurement/pr/approve-step-1?pr_id=<?php echo $item->purchase_request_id;?>"
				target="_blank">#<?php echo $item->pr_auto_number;?></a>
						
			</div></td>


			</td>
			<td><?php echo $item->unit;?></td>
			<td><?php echo $item->quantity;?></td>
			<td><?php echo $item->total_received_quantity;?></td>
			<td><?php echo $item->unconfirmed_quantity;?></td>
			<td><?php echo $item->confirmed_quantity;?></td>
			<td><?php echo $item->rejected_quantity;?></td>
			<td><?php echo $item->confirmed_balance;?></td>
			<td><?php echo $item->confirmed_free_balance;?></td>
		
		<?php if($item->confirmed_balance == 0): ?>
			<td><?php echo date_format(date_create($item->EDT),"Y-m-d");?>
			<div>
					<span class="label label-success">Fulfilled</span>
				</div></td>
		<?php else: ?>		
			<td><span id="<?php echo $item->id;?>_EDT"><?php echo date_format(date_create($item->EDT),"Y-m-d");?></span>
				<div>
					<span style="color: gray; font-size: 8pt; font-style: italic;"
						id="<?php echo $item->id;?>_timer"></span>
				</div></td>
		<?php endif; ?>	

			<td>
				<?php if($item->article_id>0): ?>			
<a
				href="<?php echo $this->baseUrl ?>/procurement/vendor/show?id=<?php echo $item->article_vendor_id;?>"
				target="_blank"><?php echo $item->article_vendor_name;?></a>
			<?php endif;?>
			
			<?php if($item->sparepart_id>0): ?>			
<a
				href="<?php echo $this->baseUrl ?>/procurement/vendor/show?id=<?php echo $item->sp_vendor_id;?>"
				target="_blank"><?php echo $item->sp_vendor_name;?></a>
			<?php endif;?>
			
			<br> <span style="font-size: 9pt; font-style: italic;">
			<?php
		if ($item->article_id > 0) :
			if ($item->article_price > 0) :
				echo 'Unit price:' . $item->article_price . ' ' . $item->article_currency;
				;
				endif;
		endif;
		
		if ($item->sparepart_id > 0) :
			if ($item->sp_price > 0) :
				echo 'Unit price:' . $item->sp_price . ' ' . $item->sp_currency;
			
			endif;
		
		endif;
		?>
			</span>
			</td>

			<script language="javascript">
			id_array.push(<?php echo $item->id;?>);
		</script>
		</tr>

	<?php endforeach; ?>
</tbody>
</table>
<br>

<?php
	
	if (! is_null ( $paginator )) {
		
		// change it only
		$base = $this->baseUrl . '/procurement/pr/pr-items?department_id=' . $department_id . '&last_status=' . $last_status . '&balance=' . $balance . '&unconfirmed_quantity=' . $unconfirmed_quantity . '&processing=' . $processing;
		
		$_connector_symbol = '&';
		
		$last = $base . $_connector_symbol . 'page=' . $paginator->totalPages . '&perPage=' . $paginator->resultsPerPage;
		$first = $base . $_connector_symbol . 'page=1&perPage=' . $paginator->resultsPerPage;
		
		$p1 = ($paginator->page) - 1;
		$p2 = ($paginator->page) + 1;
		
		$prev = $base . $_connector_symbol . 'page=' . $p1 . '&perPage=' . $paginator->resultsPerPage;
		$next = $base . $_connector_symbol . 'page=' . $p2 . '&perPage=' . $paginator->resultsPerPage;
		
		echo '<ul class="pagination">';
		
		if ($paginator->page != 1 and $paginator->totalPages > 10) {
			echo '<li><a href="' . $first . '"> |< </a></li>';
			echo '<li><a href="' . $prev . '"> < </a></li>';
		}
		
		for($i = $paginator->minInPageSet; $i <= $paginator->maxInPageSet; $i ++) {
			
			$url = $base . $_connector_symbol . 'page=' . $i . '&perPage=' . $paginator->resultsPerPage;
			
			if ($i == $paginator->page) {
				echo '<li><a class="active" href="#">' . $i . '</a></li>';
			} else {
				echo '<li><a href="' . $url . '"> ' . $i . ' </a></li>';
			}
		}
		if ($paginator->page != $paginator->totalPages and $paginator->totalPages > 10) {
			echo '<li><a href="' . $next . '"> > </a></li>';
			echo '<li><a href="' . $last . '"> >| </a></li>';
		}
		echo '</ul>';
	}
	
	?>




	

 
 
 
 <?php
 
 else :
	echo 'No Items found ...';

endif;
?>
 
 