<?php
if (count ( $message ) > 0) {
	echo '<div id="flash_message" class="global-notice">';
	foreach ( $message as $m ) :
	echo   $m. '<br>';
	endforeach;
	echo '</div>';
}
?>

<h3>Item Management</h3>

<hr>
<ul id="menu">
	<li><a href="<?php echo $this->baseUrl ?>/inventory/item/add">Create new item</a></li>
		<li><a href="<?php echo $this->baseUrl ?>/inventory/item/list">All items</a></li>
</ul>

<script>
$( "#flash_message" ).fadeOut(4500);
</script>

