<?php
/**
 *
 * @author Nguyen Mau Tri - ngmautri@gmail.com
 *         ===================================
 */
use Application\Application\Helper\ErrorMessage;
use Application\Application\Helper\OptionList;
use Application\Domain\Shared\Constants;
use Inventory\Application\DTO\Transaction\TrxDTO;
use Inventory\Application\DTO\Transaction\TrxRowDTO;
use Inventory\Application\Export\Transaction\Contracts\SaveAsSupportedType;
use Inventory\Application\Helper\Toolbar;
use Procure\Domain\Shared\ProcureDocStatus;

/**@var TrxDTO $headerDTO ;*/
/**@var TrxRowDTO $rowDTO ;*/
/**@var \Application\Controller\Plugin\NmtPlugin $nmtPlugin ;*/

// var_dump($headerDTO);
// echo memory_get_usage();

$add_row_url = null;
$picture_url = null;
$attachment_url = null;
$status_url = null;
$log_url = null;
$view_url = null;
$rowGirdUrl = null;
$hoverMode = "row";
$dropDownMenu = null;
$fullscrean = null;
$isViewing = false;
$refresh_btn = '';
$upload_btn = '';
if ($action == Constants::FORM_ACTION_SHOW) {
    $isViewing = true;
}

$canPost = false;

$transactionStatus = "";
$alert = "info";

$wh_id = null;
$pmtTermId = null;
$currencyId = null;
$incotermId = null;
$transactionTypeArray = [];
$summary_txt = null;

$rows_upload_url = "/inventory/item-opening-balance/upload-rows";

if (! $headerDTO == null) {

    $f = 'Net amount: %s %s  | Tax amount: %s  | Gross amount: %s %s  | Total rows: %s';
    $summary_tmp = sprintf($f, $headerDTO->getNetAmount(), $headerDTO->getCurrencyIso3(), $headerDTO->getTaxAmount(), $headerDTO->getGrossAmount(), $headerDTO->getCurrencyIso3(), $headerDTO->getTotalRows());

    $f = '&nbsp;&nbsp;<span><strong>Ref no. #%s // </strong></span><span class="" style="padding: 3px; margin-bottom: 2px; font-size: 10pt; color: gray">%s</span>';
    $summary_txt = sprintf($f, $headerDTO->getSysNumber(), $summary_tmp);

    $transactionStatus = sprintf('<span style="color:red;">%s</span>', $headerDTO->getTransactionStatus());

    if ($headerDTO->getTransactionStatus() == "completed") {
        $transactionStatus = sprintf('<span style="color:green;">%s</span>', $headerDTO->getTransactionStatus());
        $alert = "success";
    }
    $transactionTypeArray = $transactionType[$headerDTO->getMovementType()];

    $base_url = "/inventory/item-opening-balance/";

    $format = $base_url . 'row-gird?entity_id=%s&entity_token=%s';
    $rowGirdUrl = sprintf($format, $headerDTO->getId(), $headerDTO->getToken());

    $picture_url = sprintf($this->baseUrl . "/procure/po-attachment/get-pictures?target_id=%s&token=%s", $headerDTO->getId(), $headerDTO->getToken());
    $attachment_url = sprintf($this->baseUrl . "/procure/v-invoice-attachment/list1?target_id=%s&token=%s", $headerDTO->getId(), $headerDTO->getToken());
    $status_url = sprintf($this->baseUrl . "/procure/po/status?entity_id=%s&token=%s", $headerDTO->getId(), $headerDTO->getToken());
    $review_url = sprintf($this->baseUrl . $base_url . "review?entity_id=%s&entity_token=%s", $headerDTO->getId(), $headerDTO->getToken());
    $view_url = sprintf($this->baseUrl . $base_url . "view?entity_id=%s&entity_token=%s", $headerDTO->getId(), $headerDTO->getToken());

    $log_url = sprintf($this->baseUrl . "/application/message-store/list1?entity_id=%s&entity_token=%s", $headerDTO->getId(), $headerDTO->getToken());
    $update_header_url = sprintf($this->baseUrl . $base_url . "update?entity_id=%s&entity_token=%s", $headerDTO->getId(), $headerDTO->getToken());

    $add_row_url = sprintf($this->baseUrl . $base_url . "add-row?target_id=%s&target_token=%s", $headerDTO->getId(), $headerDTO->getToken());

    $save_as_pdf = sprintf($this->baseUrl . $base_url . "save-as?file_type=%s&entity_id=%s&entity_token=%s", SaveAsSupportedType::OUTPUT_IN_PDF, $headerDTO->getId(), $headerDTO->getToken());
    $save_as_excel = sprintf($this->baseUrl . $base_url . "save-as?file_type=%s&entity_id=%s&entity_token=%s", SaveAsSupportedType::OUTPUT_IN_EXCEL, $headerDTO->getId(), $headerDTO->getToken());
    $save_as_openoffice = sprintf($this->baseUrl . $base_url . "save-as?file_type=%s&entity_id=%s&entity_token=%s", SaveAsSupportedType::OUTPUT_IN_OPEN_OFFICE, $headerDTO->getId(), $headerDTO->getToken());

    if ($headerDTO->getDocStatus() == Constants::DOC_STATUS_DRAFT && $action == Constants::FORM_ACTION_REVIEW) :
        $hoverMode = "cell";
        $canPost = true;
    endif;

    switch ($headerDTO->getDocStatus()) {
        case ProcureDocStatus::DOC_STATUS_DRAFT:
            $isDraft = true;
            $canPost = true;
            break;
        case ProcureDocStatus::DOC_STATUS_POSTED:
            $isPosted = true;
            break;
    }

    $wh_id = $headerDTO->getWarehouse();
    $pmtTermId = $headerDTO->getPmtTerm();
    $currencyId = $headerDTO->getDocCurrency();
    $incotermId = $headerDTO->getIncoterm();

    $fullscreen_url = 'nmt';

    $format = "showJqueryDialog(\'%s\',\'1850\',$(window).height()-50,\'%s\',\'j_loaded_data\',true);";
    $fullscreen_onclick = sprintf($format, $headerDTO->getSysNumber(), $fullscreen_url);

    $format = '<a style="font-size: 9.5pt; margin-bottom: 2pt; padding: 3pt 5pt 3pt 5pt;" class="btn btn-default btn-sm" href="javascript:;" onclick="%s">
  &nbsp;<i class="fa fa-window-maximize" aria-hidden="true"></i>&nbsp;</a>&nbsp;';
    $fullscreen = sprintf($format, $fullscreen_onclick);

    $format = '<a style="font-size: 9.5pt; margin-bottom: 2pt; padding: 3pt 5pt 3pt 5pt;" class="btn btn-default btn-sm" href="javascript:;" onclick="%s">
  &nbsp;<i class="fa fa-refresh" aria-hidden="true"></i>&nbsp;</a>&nbsp;';
    $refresh_btn = sprintf($format, "refreshGird();");

    $upload_url = sprintf('/inventory/item-opening-balance/upload-rows?target_id=%s&target_token=%s', $headerDTO->getId(), $headerDTO->getToken());
    $format = '<a style="font-size: 9.5pt; margin-bottom: 2pt; padding: 3pt 5pt 3pt 5pt;" class="btn btn-default btn-sm" href="%s">
  &nbsp;Upload <i class="fa fa-upload" aria-hidden="true"></i>&nbsp;</a>&nbsp;';
    $upload_btn = sprintf($format, $upload_url);

    $dropDownList = [
        sprintf('<a target="_blank" class="" href="%s"><i class="fa fa-file-pdf-o fa-lg" aria-hidden="true"></i>&nbsp;Pdf (*.pdf)</a>', $save_as_pdf),
        'divider',
        sprintf('<a target="_blank" class="" href="%s"><i class="fa fa-file-excel-o fa-lg" aria-hidden="true"></i> &nbsp;Excel (*.xlxs)</a>', $save_as_excel),
        sprintf('<a target="_blank" class="" href="%s"><i class="fa fa-file-excel-o fa-lg" aria-hidden="true"></i> Open Office (*.ods)</a>', $save_as_openoffice)
    ];

    $dropDownMenu = \Application\Application\Helper\FormHelper::createCustomDropDownMenu($dropDownList, 'dropdownMenu1');

    $format = '/inventory/change-log/list1?object_token=%s&object_id=%s';
    $url1 = sprintf($format, $headerDTO->getToken(), $headerDTO->getId());
    $logTab = sprintf('<a title="Change Log" href="%s"><span class="glyphicon glyphicon-list"></span>&nbsp;Log</a></li></a>', $url1);

    $tabsList = [
        // $logisticTab,
        $logTab
    ];

    $tabs = \Application\Application\Helper\FormHelper::createTabs($tabsList);
}

$wh_option = OptionList::createWarehouseOption($nmtPlugin->warehouseList(), $wh_id);
$paymentTerm_option = OptionList::createPmtTermOption($nmtPlugin->getPaymentTerms(), $pmtTermId);
$incoterm_option = OptionList::createIncotermOption($nmtPlugin->incotermList(), $incotermId);
$currency_option = OptionList::createCurrencyOption($nmtPlugin->currencyList(), $currencyId);
$error_msg = ErrorMessage::showErrorMessage($errors);

// ============================
?>
<div id="wrapper" class="toggled">
   <!-- Sidebar -->
   <div id="sidebar-wrapper" style="font-size: 9.5pt;">

<?php
if ($action == Constants::FORM_ACTION_REVIEW) :
    $current_step = "STEP3";
    include (ROOT . '/module/Inventory/view/inventory/opening-balance-create-wizard.php');
endif;

include (ROOT . '/module/Inventory/view/inventory/trx_summary.php');
?>

	<?php
if ($action == Constants::FORM_ACTION_REVIEW) :
    ?>
		<div class="alert alert-warning" role="alert" style="padding: 5px 2px 2px 5px; margin: 5pt 2pt 2pt 8pt; font-size: 9.2pt; color: graytext;">
         <i class="fa fa-info-circle" aria-hidden="true"></i>&nbsp;
			<?php

    echo $this->translate('Document can\'t be changed anymore when posted! <br> ');
    ?>
		</div>
	<?php endif;

?>
	</div>
   <!-- /#sidebar-wrapper -->
   <!-- Page Content -->
   <div id="page-content-wrapper" style="font-size: 9.5pt; padding: 0px; margin: 0px;">
      <div class="container-fluid" id="main_container" style="font-size: 9.5pt; padding: 1px; margin: 0px;";>
         <a style="font-size: 9pt; margin: 2px; padding: 3px;" href="#menu-toggle" class="btn btn-primary btn-sm" id="menu-toggle">
            <span title="Hide Menu">
               <i class="fa fa-chevron-left" aria-hidden="true"></i>
               Menu
               <span>
         
         </a>
         <div></div>
         <div id="tabs" style="font-size: 9.5pt">
            <ul>
               <li>
                  <a href="#general">
                     <small>
                        <i class="fa fa-calculator" aria-hidden="true"></i>
                     </small>&nbsp;<?php

                    echo $form_title;
                    ?></a>
               </li>
                 <?php
                echo $tabs;
                ?>
            </ul>
            <div id="general" style="font-size: 9pt; padding: 10px 10px 1px 5px">
               <!-- Tab1 -->


<?php
// ================================
echo $error_msg;
// ===============================

if ($action == Constants::FORM_ACTION_UPLOAD) :
    include (ROOT . '/module/Inventory/view/inventory/trx_rows_upload.php');
endif;

if ($action == Constants::FORM_ACTION_REVERSE) :
    ?>
    <form id="REVERSAL_FORM" class="form-horizontal" action="<?php

    echo $form_action;
    ?>" method="post" enctype="multipart/form-data">
                  <input type="hidden" name="entity_id" value="<?php

    echo (! $headerDTO == null) ? $headerDTO->getId() : "";
    ?>" />
                  <input type="hidden" name="entity_token" value="<?php
    echo (! $headerDTO == null) ? $headerDTO->getToken() : "";
    ?>" />
                  <input type="hidden" name="version" value="<?php
    echo $version;
    ?>" />
                  <fieldset>
                     <legend style="font-size: 9.5pt; color: gray;">
                        <small>
                           <span class="glyphicon glyphicon-triangle-right"></span>
                        </small>
                        &nbsp;
                        <a href="#reserval_header" class="" data-toggle="collapse"><?php
    echo $this->translate("Reserval Header");
    ?>:</a>
                     </legend>
                     <div id="reserval_header" class="collapse in">
                        <div class="form-group margin-bottom required">
                           <label class="control-label col-sm-2 required"><?php

    echo $this->translate("Reversal Date");
    ?> :</label>
                           <div class="col-sm-3">
                              <input class="form-control input-sm" type="text" id="reversalDate" name="reversalDate" value="" placeholder=" please select" />
                           </div>
                        </div>
                        <div class="form-group margin-bottom">
                           <label class="control-label col-sm-2">Description</label>
                           <div class="col-sm-8">
                              <input class="form-control input-sm" type="text" placeholder="" name="reversalReason" value="<?php

    echo (! $headerDTO == null) ? '[Reversal] ' . $headerDTO->getRemarks() : "";
    ?>">
                           </div>
                        </div>
                        <div class="form-group margin-bottom">
                           <label class="control-label col-sm-2" for="inputTag"></label>
                           <div class="col-sm-3">
                              <a class="btn btn-primary btn-sm" style="color: white" onclick="confirmReserval();" href="javascript:;">
                                 <i class="fa fa-floppy-o" aria-hidden="true"></i> &nbsp;<?php

    echo $this->translate('Post');
    ?></a>
                              <a tabindex="11" class="btn btn-default btn-sm" href="<?php
    echo $view_url;
    ?>">
                                 <small>
                                    <i class="glyphicon glyphicon-remove"></i>
                                 </small>
                                 &nbsp;Cancel
                              </a>
                           </div>
                           <div class="col-sm-3"></div>
                        </div>
                     </div>
                  </fieldset>
               </form>
               <hr style="margin: 20pt 1pt 5pt 1pt;">
<?php endif;

?>


                <!-- ================ TOOL BAR ======================-->
               <div style="position: relative; float: right;">
               <?php
            echo Toolbar::showToolbarOpeningBalance($headerDTO, $action, $this);
            ?>
               </div>
               <!-- ================== TOOL BAR ===================-->
               <FORM id="HEADER_FORM" class="form-horizontal" action="<?php
            echo $form_action;
            ?>" method="post" enctype="multipart/form-data">
                  <input type="hidden" name="redirectUrl" value="<?php
                echo $redirectUrl?>" />
                  <input type="hidden" id="entity_id" name="entity_id" value="<?php
                echo $entity_id;
                ?>" />
                  <input type="hidden" id="entity_token" name="entity_token" value="<?php
                echo $entity_token;
                ?>" />
                  <input type="hidden" name="version" value="<?php
                echo $version;
                ?>" />
                  <fieldset>
                     <legend style="font-size: 9.5pt; color: gray;">
                        <small>
                           <span class="glyphicon glyphicon-triangle-right"></span>
                        </small>
                        &nbsp;
                        <a href="#invoice_header" class="" data-toggle="collapse">HEADER (<?php
                        echo "Version " . $version;
                        ?>):</a>
                     </legend>
                     <div id="invoice_header" class="collapse">
                        <div class="form-group margin-bottom required">
                           <label class="control-label col-sm-2">Movement Type:</label>
                           <div class="col-sm-3">
                              <select name="movementType" class="form-control input-sm">
                                 <option value="">Select Movement</option>
                              <?php
                            if ($transactionType !== null) :
                                foreach ($transactionType as $k => $v) :
                                    if ($headerDTO !== null) :
                                        if ($headerDTO->movementType == $k) :
                                            echo '<option selected value="' . $k . '">' . $k . ' - ' . $this->translate($v['type_name']) . '</option>';
                                        else :
                                            echo '<option value="' . $k . '">' . $k . ' - ' . $this->translate($v['type_name']) . '</option>';
                                        endif;
                                    else :
                                        echo '<option value="' . $k . '">' . $k . ' - ' . $this->translate($v['type_name']) . '</option>';
                                    endif;
                                endforeach
                                ;
                              endif;

                            ?>
                  </select>
                           </div>
                           <div class="col-sm-3">
                              <input
                                 <?php

                                if (! $headerDTO == null) :
                                    echo ($headerDTO->isActive == "1") ? "checked" : "";
                                else :
                                    echo "checked";
                                endif;
                                ?>
                                 type="checkbox" name="isActive" value="1">
                              &nbsp;Is Active&nbsp;&nbsp;&nbsp;&nbsp;
                           </div>
                        </div>
                        <div class="form-group margin-bottom required">
                           <label class="control-label col-sm-2">Movement Date:</label>
                           <div class="col-sm-3">
                              <input class="form-control input-sm" type="text" id="movementDate" name="movementDate" value="<?php

                            if (! $headerDTO == null) :
                                echo $headerDTO->movementDate; endif;

                            ?>"
                                 placeholder=" please select" />
                           </div>
                           <label class="control-label col-sm-2"><?php

                        echo $this->translate("Source Warehouse");
                        ?></label>
                           <div class="col-sm-3">
                              <select name="warehouse" id="standardUom_id" class="form-control input-sm">
                                 <option value=""><?php

                                echo $this->translate("Select Warehouse");
                                ?></option>
            <?php
            echo $wh_option;
            ?>
                  </select>
                           </div>
                        </div>
                        <div class="form-group margin-bottom">
                           <label class="control-label col-sm-2">Description</label>
                           <div class="col-sm-8">
                              <input class="form-control input-sm" type="text" placeholder="" name="remarks" value="<?php

                            echo (! $headerDTO == null) ? $headerDTO->remarks : "";
                            ?>">
                           </div>
                        </div>
                        <hr>
                     </div>
                  </fieldset>
               </form>
               <!-- HEADER END -->
               <!-- ROW -->
               <form action="">
                  <fieldset>
                     <legend style="font-size: 9pt; color: gray;">
                        <small>
                           <span class="glyphicon glyphicon-triangle-right"></span>
                        </small>
                        &nbsp;
                        <a href="#rows" class="" data-toggle="collapse">ROWS:</a>
                     </legend>
                     <div id="rows" class="collapse in">
                        <!-- button -->
                        <div style="font-size: 9pt">
                           <div class="dropdown">
                              <!-- button -->
                              <button style="font-size: 9.5pt; margin-bottom: 2pt; padding: 3pt 5pt 3pt 5pt;" title="" class="btn btn-default dropdown-toggle btn-sm" type="button" id="dropdownMenu1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
                                 <i class="fa fa-download" aria-hidden="true"></i>
                                 <span class="caret"></span>
                              </button>
                             
                            <?php
                            echo $refresh_btn;
                            echo $fullscreen;
                            echo $upload_btn;
                            echo $summary_txt;
                            echo $dropDownMenu;
                            ?>
                           </div>
                        </div>
                        <!-- button -->
                        <div id="pr_row_gird" style="font-size: 8pt;"></div>
                  
                  </fieldset>
               </form>
            </div>
            <!-- end tab -->
         </div>
      </div>
   </div>
   <!-- /#page-content-wrapper -->
</div>
<!-- /#wrapper -->
<!-- Modal -->
<div class="modal" id="confirm_modal_sm" role="dialog">
   <div class="modal-dialog modal-md">
      <div class="modal-content">
         <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal">&times;</button>
         </div>
         <div class="modal-body" id="b_modal_sm_body">
            <h5>#<?php

            echo $this->translate('PO will be posted!');
            ?></h5>
            <div class="alert alert-warning">
               <strong>[Info]</strong> <?php

            echo $this->translate('Document can\'t be changed anymore when posted!');
            ?>
					<!-- Journal Entry will be created. <br>- Warehouse Journal will be
					created.
					 -->
            </div>
            <p><?php

            echo $this->translate('Do you want to continue?');
            ?></p>
         </div>
         <div class="modal-footer">
            <button onclick="doPosting();" type="button" class="btn btn-primary btn-sm">YES</button>
            <button type="button" class="btn btn-default btn-sm" data-dismiss="modal">Cancel</button>
         </div>
      </div>
   </div>
</div>
<!-- RESERVAL MODAL -->
<div class="modal" id="reversal_confirm_modal_sm" role="dialog">
   <div class="modal-dialog modal-md">
      <div class="modal-content">
         <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal">&times;</button>
         </div>
         <div class="modal-body" id="b_modal_sm_body">
            <h5>#<?php

            echo $this->translate('Invoice will be reversed!');
            ?></h5>
            <div class="alert alert-warning">
               <strong>[Info]</strong> <?php

            echo $this->translate('Document can\'t be changed anymore when posted!');
            ?>
					<!-- Journal Entry will be created. <br>- Warehouse Journal will be
					created.
					 -->
            </div>
            <p><?php

            echo $this->translate('Do you want to continue?');
            ?></p>
         </div>
         <div class="modal-footer">
            <button onclick="doReserval();" type="button" class="btn btn-primary btn-sm">YES</button>
            <button type="button" class="btn btn-default btn-sm" data-dismiss="modal">Cancel</button>
         </div>
      </div>
   </div>
</div>
<!-- Modal -->
<div class="modal" id="update_header_confirm_modal_sm" role="dialog">
   <div class="modal-dialog modal-md">
      <div class="modal-content">
         <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal">&times;</button>
         </div>
         <div class="modal-body" id="b_modal_sm_body">
            <h5>#<?php

            echo $this->translate('Document header amendment will be posted!');
            ?></h5>
            <div class="alert alert-warning">
               <strong>[Info]</strong> <?php

            echo $this->translate('Document can\'t be changed anymore when posted!');
            ?>
				</div>
            <p><?php

            echo $this->translate('Do you want to continue?');
            ?></p>
         </div>
         <div class="modal-footer">
            <button onclick="doPostAmendment();" type="button" class="btn btn-primary btn-sm">YES</button>
            <button type="button" class="btn btn-default btn-sm" data-dismiss="modal">Cancel</button>
         </div>
      </div>
   </div>
</div>
<script>



$( "input[id='contractDate']").datepicker({ firstDay: 1, dateFormat: 'yy-mm-dd',closeText: 'X',changeMonth: true, changeYear: true});
$( "input[id='reversalDate']").datepicker({ firstDay: 1, dateFormat: 'yy-mm-dd',closeText: 'X',changeMonth: true, changeYear: true});

<?php

if (! $canPost) :
    ?>
$("#HEADER_FORM :input").attr("disabled", "disabled");
<?php endif;

?>

function confirmPost() {
 	$('#confirm_modal_sm').modal();
}

function doPosting() {
   $('#confirm_modal_sm').modal('hide');
   $('#b_modal_no_header').modal();
   submitForm('HEADER_FORM');

   
}


	var obj = { width: "auto", height: $(window).height()-300, showTitle : false,
			resizable:true,
			sortable: true,
			freezeCols:1,
			hoverMode: 'row',
		   	pageModel: { type: "remote", rPP: 100, strRpp: "{0}" },
		  	editModel: {
                allowInvalid: true,
                saveKey: $.ui.keyCode.ENTER
            },
            editor: {
                select: true
            },
		 columnBorders: true,
	  	  toolbar: {
            items: [
              { type: 'button', icon: 'ui-icon-plus', label: 'Add New Row', listeners: [
                    { "click": function (evt, ui) {
                            var $grid = $(this).closest('.pq-grid');
                            redirectUrl="<?php
                            echo $add_row_url;
                            ?>";
                            window.location.href= redirectUrl;
                         }
                    }
                 ]
              }
            ]
        },
       change: function (evt, ui) {

            if (ui.source == 'commit' || ui.source == 'rollback') {
                return;
            }
            console.log(ui);
            var $grid = $(this),
                grid = $grid.pqGrid('getInstance').grid;
            var rowList = ui.rowList,
                addList = [],
                recIndx = grid.option('dataModel').recIndx,
                deleteList = [],
                updateList = [];

            for (var i = 0; i < rowList.length; i++) {
                var obj = rowList[i],
                    rowIndx = obj.rowIndx,
                    newRow = obj.newRow,
                    type = obj.type,
                    rowData = obj.rowData;
                 if (type == 'add') {
                    var valid = grid.isValid({ rowData: newRow, allowInvalid: true }).valid;
                    if (valid) {
                        addList.push(newRow);
                    }
                }
                else if (type == 'update') {
                    var valid = grid.isValid({ rowData: rowData, allowInvalid: true }).valid;
                    if (valid) {
                        if (rowData[recIndx] == null) {
                            addList.push(rowData);
                        }
                        //else if (grid.isDirty({rowData: rowData})) {
                        else {
                            updateList.push(rowData);
                      		//alert(rowData[recIndx]  + "remarks: " + rowData.item_name);

                        }
                    }
                }
              }

              if (addList.length || updateList.length || deleteList.length) {
				var sent_list = JSON.stringify({
                    updateList: updateList,
                    addList: addList,
                    deleteList: deleteList
                });
                //alert(sent_list);

                  $.ajax({
                      url: '/procure/po/update-row',
                      data: {
                          sent_list: sent_list
                      },
                      dataType: "json",
                      type: "POST",
                      async: true,
                      beforeSend: function (jqXHR, settings) {
                          //$(".saving", $grid).show();


                          //$("#global-notice").text("Updating...").show();
                          //alert(updateList[0].item_name  +  updateList[0].row_id);
                      },
                      success: function (changes) {
                          //commit the changes.

                      	  if(changes.status == <?php

                        echo Constants::AJAX_FAILED;
                        ?>){
                      		$("#global-notice").text(changes.message).show();
                      	  }else{
                      		$("#global-notice").text("[OK] Updated...").show();
                      	  }
                        },
                      complete: function () {
                          $("#global-notice").delay(2200).fadeOut(500);
                     	  refreshGird();
                      }
                  });
              }
          },

	};

    obj.dataModel = {
	     dataType: "JSON",
            location: "remote",
            method: "GET",
            recIndx: "id",
            url: "<?php
            echo $rowGirdUrl;
            ?>",
            getData: function (response) {
         	    return { data: response.data, curPage: response.curPage, totalRecords: response.totalRecords};
           }
    };

    obj.colModel = [
       { title: "", editable: false, minWidth: 55, sortable: false,
           render: function (ui) {
               //return "<button type='button' class='edit_btn' ><small><i style='font-style: normal;' class=''>Edit&nbsp;</i></small></button><button type='button' class='receive_btn'><span class='glyphicon glyphicon-plus'>&nbsp;</span><button type='button' class='receive_inline_btn'><span class='glyphicon glyphicon-plus'>&nbsp;</span></button>";
        		return '<button type="button" class="edit_btn">Edit </button>';
           }
       },

        { title: "FA Remarks", dataType: "string", dataIndx: "faRemarks", align: 'left',minWidth: 150,editable: true},
        { title: "GL", dataType: "string", dataIndx: "glAccountNumber", width:50,editable: false },
        { title: "CC", dataType: "string", dataIndx: "costCenterName", width:85,editable: false },
        { title: "Ref", dataType: "string", dataIndx: "sysNumber", width:120,editable: false},
        { title: "#", dataType: "integer", dataIndx: "rowNumber", width:10,editable: true },
        { title: "SKU", dataType: "string", dataIndx: "itemSKU", width:50,editable: false },
        { title: "Item", dataType: "string", dataIndx: "itemName", width:220,editable: false },
        { title: "Vendor Item Name", dataType: "string", dataIndx: "vendorItemName", width:180,editable: false },
        { title: "Code", dataType: "string", dataIndx: "vendorItemCode", width:100,editable: false },
        { title: "Doc Qty", dataType: "string", dataIndx: "docQuantity", width: 70,align: 'right',editable: false},
        { title: "Unit Price", dataType: "decimal", dataIndx: "docUnitPrice", width:90, align: 'right',editable: false},
        { title: "Unit", dataType: "string", dataIndx: "rowUnit", width: 50,align: 'right',editable: false},
        { title: "Net", dataType: "decimal", dataIndx: "netAmount", width:90, align: 'right',editable: false},
        { title: "Tax", dataType: "integer", dataIndx: "taxAmount", width:80, align: 'right',editable: false},
        { title: "Gross", dataType: "decimal", dataIndx: "grossAmount", width: 90,align: 'right',editable: false},
        { title: "Receiving", dataType: "decimal", dataIndx: "draftGrQuantity",align: 'right', width:80,editable: false },
        { title: "Received", dataType: "decimal", dataIndx: "postedGrQuantity", align: 'right',width:70,editable: false },
        { title: "Billed qty", dataType: "decimal", dataIndx: "postedAPQuantity", align: 'right',width:70,editable: false },
        { title: "Billed Amt", dataType: "decimal", dataIndx: "billedAmount",align: 'right', width:70,editable: false },
        { title: "Open Amt", dataType: "decimal", dataIndx: "openAPAmount",align: 'right', width:90,editable: false },
        { title: "Standard Qty", dataType: "integer", dataIndx: "convertedStandardQuantity", width: 70,align: 'right',editable: false},
        { title: "Standard Unit", dataType: "integer", dataIndx: "convertedStandardUnitPrice", width: 70,align: 'right',editable: false},
        { title: "Target WH", dataType: "string", dataIndx: "warehouseCode", width:120,editable: false },
        { title: "PR", dataType: "string", dataIndx: "prNumber", width:120,editable: false },
        { title: "Remarks", dataType: "string", dataIndx: "remarks", align: 'left',minWidth: 150,editable: false},
     ];

    var $grid = $("#pr_row_gird").pqGrid(obj);
    $grid.on('pqgridrefresh pqgridrefreshrow', function () {
        //debugger;
        var $grid = $(this);

        $grid.find("button.edit_btn").button({})
        .unbind("click")
        .bind("click", function (evt) {
            var $tr = $(this).closest("tr"),
            rowIndx = $grid.pqGrid("getRowIndx", { $tr: $tr }).rowIndx;
            rowData = $grid.pqGrid("getRowData", { rowIndx: rowIndx }),
            recIndx = $grid.pqGrid("option", "dataModel.recIndx");
            redirectUrl="/inventory/item-opening-balance/update-row?entity_token="+rowData['token']+"&entity_id="+rowData['id']+"&target_id="+rowData['docId']+"&target_token="+rowData['docToken'];
  			window.location.href = redirectUrl;
        });

     });

	// important for datamodel: local.
    $( "#pr_row_gird" ).pqGrid( "refreshDataAndView" );

    function refreshGird(){
    	$( "#pr_row_gird" ).pqGrid( "refreshDataAndView" )
    }
    
</script>
