<?php
/**@var \Application\Entity\NmtProcurePo $entity ;*/

$form_action = '';
$form_title = '';

switch ($action) {

    case \Application\Model\Constants::FORM_ACTION_ADD:
        $form_action = '/procure/po/add';
        $form_title = $this->translate("Add PO");

        break;
    case \Application\Model\Constants::FORM_ACTION_EDIT:
        $form_action = '/procure/po/edit';
        $form_title = $this->translate("Edit PO");
        break;
        
    case \Application\Model\Constants::FORM_ACTION_PO_FROM_QO:
        /**@var \Application\Entity\NmtProcureQo $target */
        
        $form_action = '/procure/po/copy-from-qo';
        $form_title = $this->translate("Create PO from QO");
        break;
}

?>


<div id="wrapper" class="toggled">

	<!-- Sidebar -->
	<div id="sidebar-wrapper" style="font-size: 9.5pt;">
					<?php
    $current_step = "STEP1";
    include (ROOT . '/module/Procure/view/procure/create-wizard.php');
    ?>


	</div>
	<!-- /#sidebar-wrapper -->

	<!-- Page Content -->
	<div id="page-content-wrapper"
		style="font-size: 9.5pt; padding: 0px; margin: 0px;">
		<div class="container-fluid" id="main_container"
			style="font-size: 9.5pt; padding: 1px; margin: 0px;";>
			<a style="font-size: 9pt; margin: 2px; padding: 3px;"
				href="#menu-toggle" class="btn btn-primary btn-sm" id="menu-toggle"><span
				title="Hide Menu"><i class="fa fa-chevron-left" aria-hidden="true"></i>
					Menu <span></a>


			<div id="tabs" style="font-size: 10pt">
				<ul>
					<li><a href="#general"><?php echo $form_title;?>:</a></li>
		<?php if($action == \Application\Model\Constants::FORM_ACTION_EDIT):?>
 	 	<li><a
						href="<?php echo $this->baseUrl ?>/procure/change-log/list1?object_token=<?php echo (!$entity == null)? $entity->getToken():"";?>&object_id=<?php echo (!$entity == null)? $entity->getId():"";?>&class_name=<?php echo (!$entity == null)? get_class($entity):"";?>"><span
							class="glyphicon glyphicon-list"></span>&nbsp;Log</a></li>
		<?php endif;?>			
	
				</ul>

				<div id="general" style="font-size: 9pt">
					<!-- Tab1 -->
		
	<?php
if (count($errors) > 0) {
    echo '<div class="alert alert-danger alert-dismissible"" role="alert" style="font-size: 9.5pt"><a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>[ERROR]';

    echo '<ul>';
    foreach ($errors as $error) :
        echo '<li>' . $error . '</li>';
    endforeach
    ;
    echo '</ul>';
    echo '</div>';
}
?>
	<form id="Creating_Form" class="form-horizontal"
						action="<?php echo $form_action;?>" method="post"
						enctype="multipart/form-data">
						<input type="hidden" name="redirectUrl"
							value="<?php echo $redirectUrl ?>" /> <input type="hidden"
							id="entity_id" name="entity_id"
							value="<?php if (!$entity == null): echo $entity->getId();endif;?>" />
						<input type="hidden" id="entity_token" name="entity_token"
							value="<?php if (!$entity == null): echo $entity->getToken();endif;?>" />

							
            			<?php if($action == \Application\Model\Constants::FORM_ACTION_EDIT):?>
            				<input type="hidden" name="n" value="<?php echo $n;?>" />
            			<?php endif;?>
            			
           			<?php if($action == \Application\Model\Constants::FORM_ACTION_PO_FROM_QO):
           			?>
             			<input type="hidden" name="target_id" value="<?php echo (!$target== null)? $target->getId():"";?>" />
						<input type="hidden" name="target_token" value="<?php echo (!$target== null)? $target->getToken():"";?>" />
          			<?php endif;?>
            			
            			
            			
            			<fieldset>
							<legend style="font-size: 9.5pt; color: gray;">
								<small><span class="glyphicon glyphicon-triangle-right"></span></small>&nbsp;
								<a href="#invoice_header" class="" data-toggle="collapse">HEADER:</a>
							</legend>
							<div id="invoice_header" class="collapse in">
								<div class="form-group margin-bottom required">
									<label class="control-label col-sm-2">Current State:</label>
									<div class="col-sm-3">
										<select name="currentState" class="form-control input-sm">
											<option value="">Please Select</option>
											<option
												<?php if($entity->getCurrentState()=="draftPo"): echo "selected"; endif ?>
												value="draftPo">Draft</option>
											<option
												<?php if($entity->getCurrentState()=="finalPo"): echo "selected"; endif ?>
												value="finalPo">Final</option>
										</select>
									</div>

									<div class="col-sm-3">
										<input
											<?php if(!$entity== null): echo ($entity->getIsActive()=="1")?"checked":""; else: echo "checked"; endif;?>
											type="checkbox" name="isActive" value="1">&nbsp;Is
										Active&nbsp;&nbsp;&nbsp;&nbsp;

									</div>

								</div>

								<div class="form-group margin-bottom required">
									<label class="control-label col-sm-2 ">Vendor:</label>
									<div class="col-sm-3">
										<input class="form-control input-sm" type="text"
											id="vendor_name_1" placeholder="Enter term to search vendor"
											name="vendor_name"
											value="<?php if (!$entity == null): if (!$entity->getVendor() == null):echo $entity->getVendor()->getVendorName();endif;endif;?>">

										<input type="hidden" id="vendor_id" placeholder=""
											name="vendor_id"
											value="<?php if (!$entity == null): if (!$entity->getVendor() == null):echo $entity->getVendor()->getId();endif;endif;?>">
									</div>
									<div class="col-sm-3">

										<a target="blank" style="font-size: 9pt;"
											href="/bp/vendor/list">Vendor List&nbsp;&nbsp;</a><small><i
											class="glyphicon glyphicon-new-window"></i></small>
									</div>
								</div>

								<div class="form-group margin-bottom">
									<label class="control-label col-sm-2">Contract /PO No.:</label>
									<div class="col-sm-3">
										<input class="form-control input-sm" type="text"
											placeholder="" id="contractNo" name="contractNo"
											value="<?php echo (!$entity == null)? $entity->getContractNo():"";?>">
									</div>
									<label class="control-label col-sm-2">Contract /PO Date:</label>
									<div class="col-sm-3">
										<input class="form-control input-sm" type="text"
											placeholder="" id="contractDate" name="contractDate"
											value="<?php if(!$entity == null): if ($entity->getContractDate() !== null): echo date_format($entity->getContractDate(),"Y-m-d"); endif; endif;?>">
									</div>
								</div>

								<div class="form-group margin-bottom required">

									<label class="control-label col-sm-2">Currency:</label>
									<div class="col-sm-3">
										<select name="currency_id" class="form-control input-sm">
											<option value="">Select Currency</option>
   	    							<?php
            if ($currency_list !== null) :
                foreach ($currency_list as $curr) :
                    if ($entity !== null) :
                        if ($entity->getCurrency() !== null) :
                            if ($entity->getCurrency()->getCurrency() == $curr->getCurrency()) :
                                echo '<option selected value="' . $curr->getId() . '">' . $curr->getCurrency() . '</option>';
                            else :
                                echo '<option value="' . $curr->getId() . '">' . $curr->getCurrency() . '</option>';
                            endif;
                        else :
                            echo '<option value="' . $curr->getId() . '">' . $curr->getCurrency() . '</option>';
                        endif;
                    else :
                        echo '<option value="' . $curr->getId() . '">' . $curr->getCurrency() . '</option>';
                    endif;
                endforeach
                ;
   	    							endif;

            ?>
   					</select>
									</div>

									<label class="control-label col-sm-2">Exchange Rate:</label>
									<div class="col-sm-3">
										<input class="form-control input-sm" type="text"
											placeholder="" id="exchangeRate" name="exchangeRate"
											value="<?php echo (!$entity == null)? $entity->getExchangeRate():"";?>">
									</div>
								</div>


		
    									<div class="form-group margin-bottom required">
    
    									<label class="control-label col-sm-2"><?php echo $this->translate("Incoterm");?>:</label>
    									<div class="col-sm-3">
    										<select name="incoterm_id" class="form-control input-sm">
    											<option value="">Select Incoterm</option>
       	    							<?php
                if ($incoterm_list !== null) :
                foreach ($incoterm_list as $l) :
                        if ($entity !== null) :
                        if ($entity->getIncoterm2() !== null) :
                            if ($entity->getIncoterm2()->getIncoterm() == $l->getIncoterm()) :
                            echo '<option selected value="' . $l->getId() . '">' . $l->getIncoterm() . '-' .  $l->getIncoterm1(). '</option>';
                                else :
                                echo '<option value="' . $l->getId() . '">' . $l->getIncoterm()  . '-' .  $l->getIncoterm1(). '</option>';
                                endif;
                            else :
                            echo '<option value="' . $l->getId() . '">' . $l->getIncoterm() . '-' .  $l->getIncoterm1(). '</option>';
                            endif;
                        else :
                        echo '<option value="' . $l->getId() . '">' . $l->getIncoterm()  . '-' .  $l->getIncoterm1(). '</option>';
                        endif;
                    endforeach
                    ;
       	    							endif;
    
                ?>
       					</select>
    									</div>
    									
    									<label class="control-label col-sm-2"><?php echo $this->translate("Incoterm Place");?>:</label>
    									<div class="col-sm-3">
    										<input class="form-control input-sm" type="text"
    											placeholder="" id="incotermPlace" name="incotermPlace"
    											value="<?php echo (!$entity == null)? $entity->getIncotermPlace():"";?>">
    									</div>
    									
    								</div>

						<div class="form-group margin-bottom">
									<label class="control-label col-sm-2"><?php echo $this->translate("Payment Term");?>:</label>
									<div class="col-sm-5">
										<input class="form-control input-sm" type="text"
											placeholder="" id="paymentTerm" name="paymentTerm"
											value="<?php echo (!$entity == null)? $entity->getPaymentTerm():"";?>">
									</div>
									</div>


								<div class="form-group margin-bottom">
									<label class="control-label col-sm-2">Description</label>
									<div class="col-sm-8">
										<input class="form-control input-sm" type="text" id="remarks"
											placeholder="" name="remarks"
											value="<?php echo (!$entity == null)? $entity->getRemarks():"";?>">
									</div>
								</div>


							</div>

							<hr>
							<div class="form-group margin-bottom">
								<label class="control-label col-sm-2" for="inputTag"></label>
								<div class="col-sm-3">
									<button id="submit" onclick="submitForm('Creating_Form');"
										class="btn btn-default btn-sm">
										<i class="glyphicon glyphicon-floppy-disk"> </i> Save
									</button>
									<a class="btn btn-default btn-sm"
										href="<?php echo $redirectUrl; ?>"><small><i
											class="glyphicon glyphicon-remove"></i></small>&nbsp;Cancel</a>

								</div>
							</div>
						</fieldset>
					</form>

				</div>

				<!-- end tab -->
			</div>
		</div>
	</div>
	<!-- /#page-content-wrapper -->

</div>
<!-- /#wrapper -->

<script>

$( "input[id='contractDate']").datepicker({ firstDay: 1, dateFormat: 'yy-mm-dd',closeText: 'X',changeMonth: true, changeYear: true});


$( "#vendor_name_1" ).autocomplete({
    source: "/bp/vendor-search/auto-complete",
    minLength: 3,
    select: function( event, ui ) {
  	  $( "#vendor_id" ).val(ui.item.id);
      //alert	( "Selected: " + ui.item.value + " aka " + ui.item.id );
  	  //alert($( "#vendor_id" ).val());

  	 	$('#global-notice').show();
  		$('#global-notice').html('"' + ui.item.value + '" selected');
  		$('#global-notice').fadeOut(5000);
  		//$("#jquery_dialog").dialog("close");
    }
    })
    .autocomplete( "instance" )._renderItem = function( ul, item ) {
    return $( "<li>" )
      .append( "<div style='padding-bottom: 5px; border-bottom: thin solid gray;'><b>" + item.value + "</b><br><span style='color:gray;font-size: 9pt;'>" + item.vendor_country + "<span></div>" )
      .appendTo( ul );
    };

$( "#vendor_name_1" ).focus();

<?php if($entity->getDocStatus() == \Application\Model\Constants::DOC_STATUS_POSTED):?>
$("#Creating_Form :input").attr("disabled", "disabled");
$("#remarks").attr("disabled", false);
$("#entity_id").attr("disabled", false);
$("#entity_token").attr("disabled", false);
$("#submit").attr("disabled", false);
 <?php endif;?>

  
</script>