<?php

/**
 *
 * @author Nguyen Mau Tri - ngmautri@gmail.com
 *        
 */

/**
 *
 * @var DocMapRenderAsHtmlTable $collectionRender
 */
use Procure\Application\Service\PO\Render\DocMapRenderAsHtmlTable;
?>
  
    <div id="doc_map_div">
	  <h5>Releated Documents</h5>

        <?php
        echo $collectionRender->execute();
        echo $collectionRender->printAjaxPaginator();
        ?>
    </div>