<?php

/**
 *
 * @author Nguyen Mau Tri - ngmautri@gmail.com
 *        
 */

/**
 *
 * @var DocMapRenderAsHtmlTable $collectionRender
 */
use Application\Application\Helper\Form\FormHelper;
use Procure\Application\Service\PO\Render\DocMapRenderAsHtmlTable;
?>
  
    <div id="doc_map_div">
	  <h5>Releated Documents</h5>

        <?php
        if ($collectionRender != null) :
            echo $collectionRender->execute();
            echo $collectionRender->printAjaxPaginator();
        else :
            FormHelper::echoMessage("Nothing found !");
        endif;
        ?>
    </div>