<?php

/**
 *
 * @author Nguyen Mau Tri - ngmautri@gmail.com
 *        
 */

/**
 *
 * @var DocMapRenderAsHtmlTable $collectionRender
 */
use Application\Application\Helper\Form\FormHelper;
use Fhaculty\Graph\Graph;
use Procure\Application\Service\PO\Render\DocMapRenderAsHtmlTable;
?>
  
    <div id="doc_map_div">
	  <h5>Releated Documents</h5>

        <?php
        if ($collectionRender != null) :
            echo $collectionRender->execute();
            echo $collectionRender->printAjaxPaginator();
        else :
            FormHelper::echoMessage("Nothing found !");
        endif;
        ?>
    </div>
    
<?php
$graph = new Graph();

$blue = $graph->createVertex("blue");
$blue->setAttribute('label', 'blue');
$blue->setAttribute('graphviz.color', 'blue');

$red = $graph->createVertex("red");
$red->setAttribute('label', 'red');
$red->setAttribute('graphviz.color', 'red');

$e = $blue->createEdgeTo($red);
$graph->addEdge($e);

$graphviz = new Graphp\GraphViz\GraphViz();
// $graphviz->setFormat('png');
echo $graphviz->createImageHtml($graph);
?>
