<?php

/**@var \Application\Entity\NmtProcurePo $a ; */
?>

<div id="tabs1" style="font-size: 9.5pt">

<div id="general">

<div>
	<small><span class="glyphicon glyphicon-filter"></span></small>&nbsp;<a
		href="#list_filter" class="" data-toggle="collapse">FILTER</a>
</div>
<div id="list_filter" class="collapse">

	<div
		style="border: 1px; padding: 3px; font-size: 9pt; background: url(/images/bg1.png); background-repeat: repeat-x; background-color: #FFFFFF;">

		<form class="form-horizontal"
			action="<?php

echo $this->baseUrl?>/finance/v-invoice/list" method="get"
			enctype="multipart/form-data">

			<div class="form-group margin-bottom">
				<label class="control-label col-sm-2" for="inputTag">Current State:</label>
				<div class="col-sm-3">
					<select name="currentState"  class="form-control input-sm">
						<option value="">All</option>
						<option <?php

echo $currentState == 'contract' ? "selected='selected'" : "";
    ?>
							value="contract">Contract /PO</option>
						<option <?php

echo $currentState == 'draftInvoice' ? "selected='selected'" : "";
    ?>
							value="draftInvoice">Draft Invoice</option>
						<option <?php

echo $currentState == 'finalInvoice' ? "selected='selected'" : "";
    ?>
							value="finalInvoice">Final Invoice</option>
					</select>
				</div>
			</div>

			<div class="form-group margin-bottom">
				<label class="control-label col-sm-2" for="inputTag">Active Items</label>
				<div class="col-sm-3">
					<select class="form-control input-sm" name="is_active">
						<option <?php

echo $is_active == '2' ? "selected='selected'" : "";
    ?>
							value="2">All</option>
						<option <?php

echo $is_active == '1' ? "selected='selected'" : "";
    ?>
							value="1">Active</option>
						<option <?php

echo $is_active == '-1' ? "selected='selected'" : "";
    ?>
							value="-1">Inactive</option>
					</select>
				</div>
			</div>

			<div class="form-group margin-bottom">
				<label class="control-label col-sm-2" for="inputTag">Sort by</label>
				<div class="col-sm-3">
					<select class="form-control input-sm" name="sort_by">
						<option value="">None</option>
						<option
							<?php

echo $sort_by == 'invoiceDate' ? "selected='selected'" : "";
    ?>
							value="invoiceDate">Invoice Date</option>
						<option
							<?php

echo $sort_by == 'vendorName' ? "selected='selected'" : "";
    ?>
							value="vendorName">Vendor Name</option>
						<option
							<?php

echo $sort_by == 'currencyCode' ? "selected='selected'" : "";
    ?>
							value="currencyCode">Currency</option>
						<option
							<?php

echo $sort_by == 'createdOn' ? "selected='selected'" : "";
    ?>
							value="createdOn">Created Date</option>
					</select> <input
						<?php

if (! $sort == null) :
        echo ($sort == 'ASC') ? "checked" : "";
    else :
        echo "checked";
    endif;
    ?>
						type="radio" name="sort" value="ASC">&nbsp;ASC&nbsp;&nbsp; <input
						<?php

if (! $sort == null) :
        echo ($sort == 'DESC') ? "checked" : "";
    else :
        echo "";
    endif;
    ?>
						type="radio" name="sort" value="DESC">&nbsp;DESC&nbsp;&nbsp;

				</div>
			</div>


			<div class="form-group margin-bottom">
				<label class="control-label col-sm-2" for="inputTag">Result per page</label>
				<div class="col-sm-3">
					<select class="form-control input-sm" name="perPage">
						<option value="">None</option>
						<option <?php

echo $per_pape == '15' ? "selected='selected'" : "";
    ?>
							value="15">15</option>

						<option <?php

echo $per_pape == '20' ? "selected='selected'" : "";
    ?>
							value="20">20</option>

						<option <?php

echo $per_pape == '30' ? "selected='selected'" : "";
    ?>
							value="30">30</option>

						<option <?php

echo $per_pape == '50' ? "selected='selected'" : "";
    ?>
							value="50">50</option>
						<option <?php

echo $per_pape == '100' ? "selected='selected'" : "";
    ?>
							value="100">100</option>
						<option <?php

echo $per_pape == '200' ? "selected='selected'" : "";
    ?>
							value="200">200</option>
					</select>
				</div>
			</div>

			<div class="form-group margin-bottom">
				<div class="col-sm-offset-2 col-sm-10">
					<button type="submit" class="btn btn-default">Show</button>
				</div>
			</div>

		</form>
	</div>
</div>

	<hr>



<?php
if ($total_records <= 0) :
    echo 'No record found!';
else :

    if (! is_null($paginator)) :
        echo 'Record ' . $paginator->getMinInPage() . ' to ' . $paginator->getMaxInPage() . ' | ' . $total_records . ' records found!';
    else :
        echo $total_records . ' records found!';
    endif;

    ?>

<table style="font-size: 9.3pt;" class="table table-bordered table-hover">
	<thead>
		<tr>
			<td><b>#</b></td>
			<td><b>Vendor</b></td>
			<td><b>Curr</b></td>
			<td><b>Gross <br>amount</b></td>
			<td><?php

echo $this->translate("Status");
    ?></td>
			<td><?php

echo $this->translate("Status");
    ?></td>

			<td><b>Action</b></td>
		</tr>
	</thead>

	<tbody>

	 <?php

    $count = 0;
    foreach ($list as $l) :
        $count ++;

        /**@var \Application\Entity\FinVendorInvoice $a ; */
        $a = $l[0];
        ?>

	<tr>
			<td>
<a style="color:navy;" href="<?php

echo $this->baseUrl?>/procure/po/show?token=<?php

echo $a->getToken();
        ?>&entity_id=<?php

echo $a->getId();
        ?>"><?php

echo ($paginator == null) ? $count : $paginator->getMinInPage() - 1 + $count;
        ?></a>

			</td>
			<td><?php

echo $a->getVendor()->getVendorName()?></td>
			<td><?php

echo $a->getCurrency()->getCurrency()?></td>
			<td><?php

if ($l['gross_amount'] != null) :
            echo number_format($l['gross_amount'], 2);endif;

        ?></td>
			<td><?php

echo $a->getDocStatus();
        ?></td>
		<td><?php

echo $a->getTransactionStatus();
        ?></td>

			<td>
<a href="<?php

echo $this->baseUrl?>/procure/po/show?token=<?php

echo $a->getToken();
        ?>&entity_id=<?php

echo $a->getId();
        ?>">
<?php

echo $this->translate("Show");
        ?>
</a>
			</td>
	<?php

endforeach
    ;
    ?>
 </tbody>
</table>


<?php
    // =============================== navigation.
    ?>

</div>
<?php

endif;
?>


