<?= $this->doctype() ?>
<html lang="en">
<head>
<meta charset="utf-8">
        <?= $this->headTitle('Mascot Innternational Laos')->setSeparator(' - ')->setAutoEscape(false) ?>

        <?=$this->headMeta ()->appendName ( 'viewport', 'width=device-width, initial-scale=1.0' )->appendHttpEquiv ( 'X-UA-Compatible', 'IE=edge' )?>

        <!-- Le styles -->
        <?=$this->headLink ( [ 'rel' => 'shortcut icon','type' => 'image/vnd.microsoft.icon','href' => $this->basePath () . '/img/favicon.ico' ] )->prependStylesheet ( $this->basePath ( 'css/style.css' ) )->prependStylesheet ( $this->basePath ( 'css/bootstrap-theme.min.css' ) )->prependStylesheet ( $this->basePath ( 'css/bootstrap.min.css' ) )?>

        <!-- Scripts -->
        <?=$this->headScript ()->prependFile ( $this->basePath ( 'js/bootstrap.min.js' ) )->prependFile ( $this->basePath ( 'js/jquery-3.1.0.min.js' ) )?>
        
 <link href="/css/bootstrap-responsive.min.css" media="screen"
	rel="stylesheet" type="text/css">

<link rel="stylesheet" href="/css/jstree/style.css" type="text/css">
<link rel="stylesheet" href="/css/bootstrap-editable.css"
	type="text/css">

<link rel="stylesheet" href="/jquery/jquery-ui.min.css" type="text/css">
<link rel="stylesheet" href="/jquery/jquery-ui.theme.min.css"
	type="text/css">
<link rel="stylesheet" href="/jquery/jquery-ui.structure.min.css"
	type="text/css">
<link href="/css/style.css" media="screen" rel="stylesheet"
	type="text/css">
<link href="/css/calendar.css" media="screen" rel="stylesheet"
	type="text/css">

<link rel="stylesheet" href="/css/tables.css" type="text/css">

<script src="/js/NMT.js"></script>
<script src="/jquery/jquery-ui.min.js"></script>

</head>
<body>

	<div style="display: none" id="global-notice"></div>

	<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
		<div class="container">
			<div class="navbar-header">
				<button type="button" class="navbar-toggle" data-toggle="collapse"
					data-target=".navbar-collapse">
					<span class="icon-bar"></span> <span class="icon-bar"></span> <span
						class="icon-bar"></span>
				</button>
				<a style="color:#adadad; font-weight: bold;" href="<?= $this->url('home') ?>"> <img
					src="<?= $this->basePath('img/logo.gif') ?>" height="50"
					alt="Mascot
					International Laos <?= \Application\Module::VERSION ?>" />&nbsp;Mascot
					International Laos
				</a>
			</div>
			<div class="collapse navbar-collapse">
				<ul class="nav navbar-nav">
				</ul>
					
			</div>
		</div>
	</nav>
	<div class="container">
		
	        <?= $this->content ?>
            <hr>
		<footer>

			<p>Email: nmt@mascot.dk</p>
		</footer>
	</div>
        <?= $this->inlineScript() ?>
    </body>
</html>
