<?php echo $this->doctype(); ?>

<html lang="en">
<head>
<meta charset="utf-8">
<?= $this->headTitle('Mascot International Laos')->setSeparator(' - ')->setAutoEscape(false) ?>
<?=$this->headMeta ()->appendName ( 'viewport', 'width=device-width, initial-scale=1.0' )->appendHttpEquiv ( 'X-UA-Compatible', 'IE=edge' )?>

<!-- Le styles -->
<link href="/img/favicon.ico" rel="shortcut icon" type="image/vnd.microsoft.icon">

<link href="/bootstrap3/css/bootstrap.min.css" media="screen" rel="stylesheet" type="text/css">
<link href="/bootstrap3/css/bootstrap-theme.min.css" media="screen" rel="stylesheet" type="text/css">
<link href="/bootstrap3/css/style.css" media="screen" rel="stylesheet" type="text/css">
	           

<link href="/css/lightgallery.css" rel="stylesheet"  type="text/css">
<link href="/css/lg-transitions.min.css" rel="stylesheet"   type="text/css">
<link href="/css/jstree/style.css" rel="stylesheet"  type="text/css">
<link href="/css/bootstrap-editable.css" rel="stylesheet" type="text/css">
<link href="/css/calendar.css" media="screen" rel="stylesheet"  type="text/css">
<link href="/css/tables.css" rel="stylesheet"  type="text/css">

<link href="/jquery/jquery-ui.min.css" rel="stylesheet"  type="text/css">
<link href="/jquery/jquery-ui.theme.min.css" rel="stylesheet"  type="text/css">
<link href="/jquery/jquery-ui.structure.min.css" rel="stylesheet"  type="text/css">

<script type="text/javascript" src="/js/jquery.js"></script>
<script type="text/javascript" src="/bootstrap3/js/bootstrap.min.js"></script>


<script type="text/javascript" src="/jquery/jquery-ui.min.js"></script>
<script type="text/javascript" src="/js/exif.js"></script>								
<script type="text/javascript" src="/js/lightgallery-all.min.js"></script>
<script type="text/javascript" src="/js/lg-thumbnail.js"></script>
<script type="text/javascript" src="/js/lg-fullscreen.min.js"></script>
<script type="text/javascript" src="/js/Observer.js"></script>

<script type="text/javascript" src="/js/jstree.min.js"></script>
<script type="text/javascript" src="/js/jquery.tabledit.min.js"></script>
<script type="text/javascript" src="/js/bootstrap-editable.min.js"></script>		
<script type="text/javascript" src="/js/mla.js"></script>
<script type="text/javascript" src="/js/NMT.js"></script>
<script type="text/javascript" src="/js/mla-hr.js"></script>
<script type="text/javascript" src="/js/mla-proc.js"></script>
<script type="text/javascript" src="/js/nmt-inventory.js"></script>

<script>


  var timerSubject = new Subject();

  $(function() {
	    $( "input[id='movement_date']").datepicker({ firstDay: 1, dateFormat: 'yy-mm-dd',closeText: 'X'});
   });


  $(function() {
	    $( "input[id='start_date']").datepicker({ firstDay: 1, dateFormat: 'yy-mm-dd',closeText: 'X'});
 });

  $(function() {
	    $( "input[id='end_date']").datepicker({ firstDay: 1, dateFormat: 'yy-mm-dd',closeText: 'X'});
});

  $(function() {
	   // $( "input[type=submit], button" ).button();
  });

  $(function() {
	    $( "#tabs" ).tabs({
	     
	    });
	  });
  
  $(function() {
	    $( "#menu" ).menu();
	  });

  startTime();
  </script>


</head>
<body>

	<div style="display: none" id="global-notice"></div>

	<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
		<div class="container">
			<div class="navbar-header">
				<button type="button" class="navbar-toggle" data-toggle="collapse"
					data-target=".navbar-collapse">
					<span class="icon-bar"></span> <span class="icon-bar"></span> <span
						class="icon-bar"></span>
				</button>
				<a style="color:#adadad; font-weight: bold;" href="#"> <img
					src="/img/logo.gif" height="50"
					alt=""/>&nbsp;Mascot
					International Laos
				</a>
			</div>
			<div class="collapse navbar-collapse">
				<ul class="nav navbar-nav">
						<li><a href="<?= $this->url('home') ?>"><i class="glyphicon glyphicon-home"></i></a></li>
				 <?php if ($this->user !== null): ?>
				
				 		<li class="dropdown"><a class="dropdown-toggle"
						data-toggle="dropdown" href="#">My Inbox <span class="caret"></span></a>
						<ul class="dropdown-menu">
							<li><a href="/procurement/do/get-notification">Delivery
									Notification</a></li>
						</ul></li>

						<li class="dropdown"><a class="dropdown-toggle"
						data-toggle="dropdown" href="#">Inventory <span class="caret"></span></a>
						<ul class="dropdown-menu">
						<li><a href="/inventory/item"><small><i class="glyphicon glyphicon-triangle-right"></i></small>&nbsp;Items management</a></li>
						<li><a href="/inventory/warehouse"><small><span class="glyphicon glyphicon-triangle-right"></span></small>&nbsp;Warehouse management</a></li>
					
						</ul>
						</li>
						  
						  <?php if ($this->cart_items !== null): ?>
						  
						  <li class="dropdown"><a class="dropdown-toggle"
						data-toggle="dropdown" href="#"> <span class="label"><i
								class="icon-shopping-cart"> </i></span>
						    
						   
						    <?php if ($this->cart_items >0): ?>
						    <span id="cart_items" class="badge">
						    <?php								
								echo $this->cart_items;
							else :
								?>
	  					    <span id="cart_items" class="">
						    <?php endif;?>						    
						    </span>&nbsp;ORDER LIST <span class="caret"></span></a>
						<ul class="dropdown-menu">
							<li><a href="/procurement/pr/cart"> <i class="icon-shopping-cart">
								</i> Review Cart
							</a></li>
							<li class="divider"></li>
							<li><a href="/procurement/pr/mine">My PR</a></li>
							<li><a href="/procurement/pr/my-items">My PR Items</a></li>
						</ul></li>
						  <?php endif;?>
						  
						   	<?php if ($this->isAdmin==true): ?>
						   	
						   		  <li class="dropdown"><a class="dropdown-toggle"
						data-toggle="dropdown" href="#"><span class="label label-success">
								<small><span class="glyphicon glyphicon-wrench"> </span></small>
						</span>&nbsp;&nbsp;Settings
						<span class="caret"></span></a>
						<ul class="dropdown-menu">
							<li><a href="<?php echo $this->baseUrl ?>/user/index/index">User
									Manager</a></li>
							<li><a
								href="<?php echo $this->baseUrl ?>/application/department/list">Department</a>
							</li>
							<li><a
								href="<?php echo $this->baseUrl ?>/application/acl/list-resources">ACL
									Management</a></li>
							<li class="divider"></li>
							<li><a href="<?php echo $this->baseUrl ?>/workflow/wf">Workflow
									Management</a></li>
							<li class="divider"></li>
							<li><a
								href="<?php echo $this->baseUrl ?>/inventory/article/admin-add"><i
									class="icon-plus"> </i> Add New Item</a></li>
							<li><a href="<?php echo $this->baseUrl ?>/inventory/article/all"><i
									class="icon-list-alt"></i> Show all articles</a></li>
							<li class="divider"></li>
							<li><a href="<?php echo $this->baseUrl ?>/user/admin/asset-index">Update
									Asset Index</a></li>
							<li><a
								href="<?php echo $this->baseUrl ?>/user/admin/sparepart-index">Update
									Sparepart Index</a></li>

							<li><a
								href="<?php echo $this->baseUrl ?>/user/admin/article-index">Update
									Item Index</a></li>
							<li><a
								href="<?php echo $this->baseUrl ?>/user/admin/vendor-index">Update
									Vendor Index</a></li>
							<li class="divider"></li>
							<li><a
								href="<?php echo $this->baseUrl ?>/hr/employee/create-index">Update
									Employee Index</a></li>
							</ul></li>
						  <?php endif;?>
						  
						  	<?php if ($this->isProcurement==true): ?>
							<li class="dropdown"><a class="dropdown-toggle"
						data-toggle="dropdown" href="#"><span class="label label-default"></span>
							PROCUREMENT <span class="caret"></span></a>
						<ul class="dropdown-menu">
							<li><a href="<?php echo $this->baseUrl ?>/procurement/pr/all-pr">All
									PR</a></li>
							<li><a
								href="<?php echo $this->baseUrl ?>/procurement/pr/pr-items">All
									PR Items</a></li>
							<li class="divider"></li>

							<li><a href="<?php echo $this->baseUrl ?>/inventory/article/all">Show
									all items</a></li>

							<li class="divider"></li>

							<li><a
								href="<?php echo $this->baseUrl ?>/procurement/vendor/list">Show
									all vendors </a></li>

						</ul></li>
						  <?php endif;?>
						
				
						  <li class="dropdown"><a class="dropdown-toggle"
						data-toggle="dropdown" href="#"><span class="label label-primary">
								<small><span class="glyphicon glyphicon-user"> </span></small>
						</span>&nbsp;&nbsp;<?php echo $this->user?>
						    <span class="caret"></span></a>
						<ul class="dropdown-menu">
							<li><a href="/user/profile"><small><i class="glyphicon glyphicon-user">
								</i></small>&nbsp;My Profile</a></li>
							<li class="divider"></li>
							<li><a href="/user/auth/logout"><small><i
									class="glyphicon glyphicon-log-out"></i></small>&nbsp;Logout</a></li>
						</ul></li>
						
						
						  <?php endif;?>
				<li id="clock1" style="color: #FFFFCC; padding: 6px 4px 2px 15px; font-size:10pt;"></li>
					
					</ul>
					
			</div>
		</div>
	</nav>
	<div class="container">
		
	
		
            <?= $this->content ?>
            <hr>
		<footer>

			<p>Email: nmt@mascot.dk</p>
		</footer>
	</div>
        <?= $this->inlineScript() ?>
    </body>
</html>
