 <h4>Create Item:</h4>
<?php
if (count ( $errors ) > 0) {
	echo '<div class="alert alert-danger" role="alert">';
	
	echo '<ul>';
	foreach ( $errors as $error ) :
		echo '<li>' . $error . '</li>';
	endforeach
	;
	echo '</ul>';
	echo '</div>';
}
?>

<form class="form-horizontal" action="<?php echo $this->baseUrl ?>/inventory/item/add" method="post" enctype="multipart/form-data">
<input type="hidden" name="redirectUrl"
		value="<?php echo $redirectUrl ?>" />

<div id="tabs" style="font-size: 9.5pt"> 
  <ul>
  <li ><a href="#general">Item</a></li>
   </ul>

<div id="general"> 
	
	<div class="form-group">
		<label class="control-label col-sm-2" >Item ID</label>
		<div class="col-sm-3">
			<input class="form-control" type="text"  placeholder=""
				name="item_sku" value="<?php echo (!$entity == null)? $entity->getItemSku():"";?>">
		</div>		
		<div class="col-sm-4">
	  	     <input <?php if(!$entity == null): echo ($entity->getIsActive()==="1")?"checked":""; else: echo "checked"; endif;?> type="checkbox" name="is_active" value="1">&nbsp;Active&nbsp;&nbsp;
			 <input <?php if(!$entity == null): echo ($entity->getIsStocked()==="1")?"checked":""; else: echo "checked"; endif;?> type="checkbox" name="is_stocked" value="1">&nbsp;Stocked &nbsp;&nbsp;
			 <input <?php if(!$entity == null): echo ($entity->getIsPurchased()==="1")?"checked":""; else: echo "checked"; endif;?> type="checkbox" name="is_purchased" value="1">&nbsp;Purchased &nbsp;&nbsp;<br>
	 		 <input <?php if(!$entity == null): echo ($entity->getIsSaleItem()==="1")?"checked":""; else: echo ""; endif;?> type="checkbox" name="is_sale_item" value="1">&nbsp;For Sale &nbsp;&nbsp;
			 <input <?php if(!$entity == null): echo ($entity->getIsFixedAsset()==="1")?"checked":""; else: echo ""; endif;?> type="checkbox" name="is_fixed_asset" value="1">&nbsp;Fixed Asset
		
		</div>
		
		<div class="col-sm-3">
			<img alt="" height="" src="/inventory/item/barcode?barcode=22011979">
		</div>
	</div>
	
	<div class="form-group">
		<label class="control-label col-sm-2" >Item  Name</label>
		<div class="col-sm-3">
			<input class="form-control" type="text"  placeholder=""
				name="item_name" value="<?php echo (!$entity == null)? $entity->getItemName():"";?>">
		</div>
		
		<label class="control-label col-sm-2" >Item Foreign Name</label>
		<div class="col-sm-3">
			<input class="form-control" type="text"  placeholder=""
				name="item_name_foreign" value="<?php echo (!$entity == null)? $entity->getItemNameForeign():"";?>">
		</div>
	</div>
		<div class="form-group">
		<label class="control-label col-sm-2" >Item  Description</label>
		<div class="col-sm-8">
			<input class="form-control" type="text"  placeholder=""
				name="item_description" value="<?php echo (!$entity == null)? $entity->getItemDescription():"";?>">
		</div>
	</div>
	<div class="form-group">
		<label class="control-label col-sm-2" >Bar Code</label>
		<div class="col-sm-3">
			<input class="form-control" type="text"  placeholder=""
				name="item_barcode" value="<?php echo (!$entity == null)? $entity->getBarcode():"";?>">
			
		</div>		
		<label class="control-label col-sm-2" >Keyworks</label>
		<div class="col-sm-3">
			<input class="form-control" type="text"  placeholder=""
				name="keywords" value="<?php echo (!$entity == null)? $entity->getKeywords():"";?>">
		</div>
	</div>
	
	<div class="form-group">
		<label class="control-label col-sm-2" >Item Type</label>
		<div class="col-sm-3">
			<select class="form-control"  name="item_type" >
        		<option <?php if(!$entity == null): echo ($entity->getItemType()=="ITEM")?"selected":""; endif;?> value="ITEM">Item</option>
   	     		<option <?php if(!$entity == null): echo ($entity->getItemType()=="SERVICE")?"selected":""; endif;?> value="SERVICE">Service</option>
   	     		<option <?php if(!$entity == null): echo ($entity->getItemType()=="SOFTWARE")?"selected":""; endif;?> value="SOFTWARE">Software</option>
    		</select>
		</div>
		
		<label class="control-label col-sm-2" >Measurement</label>
		<div class="col-sm-3">
			<input disabled class="form-control" type="text" id="standard_uom_name" placeholder="Please select standard unit"
				name="item_uom_name" value="<?php echo (!$uom == null)? $uom->getUomCode():"";?>">
			<input type="hidden" id="standard_uom_id" placeholder="" 
			name="standard_uom_id" value="<?php echo (!$uom == null)? $uom->getId():"";?>">	
			
		</div>
		
<a style="color: #0080ff;" href="javascript:;"
	onclick="showBootstrapDialog('Select Unit of Measurement','/application/uom/list1','loaded_data');">Select&nbsp;&nbsp;<i class="glyphicon glyphicon-folder-open"></i>
</a>
		
	</div>
	
	<div class="form-group">
		<label class="control-label col-sm-2" >Item Category</label>
		<div class="col-sm-3">
			<input disabled class="form-control" type="text" id="item_category_name" placeholder="Please select item category"
				name="country_code_2" value="<?php echo (!$category == null)? $category->getNodeName():"";?>">
			<input type="hidden" id="item_category_name_selected" placeholder="" 
			name="item_category_id" value="<?php echo (!$category == null)? $category->getNodeId():"";?>">	
		</div>
		
<a style="color: #0080ff;" href="javascript:;"
	onclick="showBootstrapDialog('Select Item Category','/application/item-category/list1','loaded_data');">Select&nbsp;&nbsp;<i class="glyphicon glyphicon-folder-open"></i>
</a>

	</div>
	
	<div class="form-group">
		<label class="control-label col-sm-2" >Department</label>
		<div class="col-sm-3">
			<input disabled class="form-control" type="text" id="department_name" placeholder="Please select!"
				name="deparment_name" value="<?php echo (!$department == null)? $department->getNodeName():"";?>">
			<input type="hidden" id="department_name_selected" placeholder="" 
			name="department_id" value="<?php echo (!$department == null)? $department->getNodeId():"";?>">	
		</div>
		
<a style="color: #0080ff;" href="javascript:;"
	onclick="showBootstrapDialog('Select Deparment','/application/department/list1','loaded_data');">Select&nbsp;&nbsp;<i class="glyphicon glyphicon-folder-open"></i>
</a>

</div>
	
	<div class="form-group">
		<label class="control-label col-sm-2">Location</label>
		<div class="col-sm-3">
			<input class="form-control" type="text"  placeholder=""
				name="location" value="<?php echo (!$entity == null)? $entity->getLocation():"";?>">
		</div>
		
	</div>
	
	
	
	<div class="form-group">
		<label class="control-label col-sm-2" >Manufacturer</label>
		<div class="col-sm-3">
			<input class="form-control" type="text"  placeholder=""
				name="manufacturer" value="<?php echo (!$entity == null)? $entity->getManufacturer():"";?>">
		</div>
		<label class="control-label col-sm-2" >Manufacturer Model</label>
		<div class="col-sm-3">
			<input class="form-control" type="text"  placeholder=""
				name="manufacturer_code" value="<?php echo (!$entity == null)? $entity->getManufacturerModel():"";?>">
		</div>
	</div>
	
	<div class="form-group">
		<label class="control-label col-sm-2" >Manufacturer's Item Code</label>
		<div class="col-sm-3">
			<input class="form-control" type="text"  placeholder=""
				name="manufacturer_code" value="<?php echo (!$entity == null)? $entity->getManufacturerCode():"";?>">
		</div>
		
		
		<label class="control-label col-sm-2" >Manufacturer Serial</label>
		<div class="col-sm-3">
			<input class="form-control" type="text" placeholder=""
				name="manufacturer_serial" value="<?php echo (!$entity == null)? $entity->getManufacturerSerial():"";?>">
		</div>
		
	</div>
	
	
	<div class="form-group">
		<label class="control-label col-sm-2" >Lead time</label>
		<div class="col-sm-3">
			<input  class="form-control" type="text" placeholder=""
				name="lead_time" value="<?php echo (!$entity == null)? $entity->getLeadTime():"";?>">
				 <input <?php if(!$entity == null): echo ($entity->getLocalAvailabiliy()==="1")?"checked":""; else: echo ""; endif;?> type="checkbox" name="local_availability" value="1">&nbsp;Local Availability
		
		</div>
		<label class="control-label col-sm-2" >Remarks</label>
		<div class="col-sm-3">
			<textarea  class="form-control" type="text" rows="5" placeholder=""
				name="remarks" style="font-size: 9pt;"><?php echo (!$entity == null)? $entity->getRemarks():"";?></textarea>
		</div>
	</div>
	
	<div class="form-group">
		<div class="col-sm-offset-2 col-sm-10">
			<button type="submit" class="btn btn-default">Save</button>
		</div>
	</div>
</div>
	
</div>	
	

</form>

<!-- Modal -->
<div class="modal" id="modal1" role="dialog">
	<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal">&times;</button>
				<span class="modal-title" id="modal_title" style="font-weight: bold;">Mascot International Laos</span>
			</div>
			<div class="modal-body">
				<div id="loaded_data">loading</div>
			</div>
			<div class="modal-footer">
				<span id="node_selected">No thing selected</span>&nbsp;&nbsp;
				<button type="button" class="btn btn-default" data-dismiss="modal">Confirm</button>
			</div>
		</div>
	</div>
</div>


<div id="dialog" style="display: none;">Check code...</div>

