<h4>
	 <?php 
	 // target:EMPLOYEE
	 echo (!$target== null)? 'Employee: ' . $target->getEmployeeName():"";?>
</h4>

<?php
if (count ( $errors ) > 0) {
	echo '<div class="alert alert-danger" role="alert" style="font-size: 10.5pt">';
	
	echo '<ul>';
	foreach ( $errors as $error ) :
		echo '<li>' . $error . '</li>';
	endforeach
	;
	echo '</ul>';
	echo '</div>';
}
?>

<div id="tabs" style="font-size: 10pt"> 
  <ul>
  <li ><a href="#general">Picture Upload</a></li>
   </ul>

<div id="general"> 

<!-- TO UPDATE ACTION -->
<form id="attachment_upload_form" class="form-horizontal" action="/hr/employee-attachment/upload-picture" method="post" enctype="multipart/form-data">
<input type="hidden" name="target_id" value="<?php echo (!$target == null)? $target->getId():"";?>" />
<input type="hidden" name="token" value="<?php echo (!$target== null)? $target->getToken():"";?>" />
<input type="hidden" name="redirectUrl" value="<?php echo $redirectUrl ?>" />


		
	<div class="form-group">
		<label class="control-label col-sm-2" for="inputTag">Piture:</label>
		<div class="col-sm-3">
			<input style=";" type="file" id= "attachments" name="attachments" />
		</div>		
	</div>
	
	<div class="form-group">
		<label class="control-label col-sm-2" >Valid From:</label>
		<div class="col-sm-3">
			<input class="form-control" type="text" name="validFrom" 
			value="<?php if(!$entity == null): echo ($entity->getValidFrom() !== null)? date_format($entity->getValidFrom(),"Y-m-d"):""; endif;?>" placeholder =" please select" id="valid_from" />
		</div>
		
		<label class="control-label col-sm-2" >Valid To:</label>
		<div class="col-sm-3">
			<input class="form-control" type="text" name="validTo" 
			value="<?php if(!$entity == null): echo ($entity->getValidTo() !== null)? date_format($entity->getValidTo(),"Y-m-d"):""; endif;?>" placeholder =" please select" id="valid_to" />
		</div>		
	</div>
	<div class="form-group">
	<label class="control-label col-sm-2" >Remarks:</label>
		<div class="col-sm-3">
			<textarea  class="form-control" type="text" rows="4" placeholder=""
				name="remarks" style="font-size: 9pt;"><?php echo (!$entity == null)? $entity->getRemarks():"";?></textarea>
		</div>		
	</div>
	
	<div class="form-group">
		<label class="control-label col-sm-2" for="inputTag"></label>
		<div class="col-sm-3">
	   	<button type="submit" class="btn btn-default"><i class="glyphicon glyphicon-upload"> </i> Upload</button>
  		</div>
	</div> 
		
	
</form>
</div>
</div>

<script type="text/javascript">
$('#attachments').bind('change', function() {
	var file_size;
	file_size = this.files[0].size
	if (file_size > 2097152){
		//alert('This file size is too large : ' + file_size + "MB. Please select new file");
		
		$('#b_loaded_data').text('This file size is too large : ' + file_size + "MB. Please select new file");
		$('#modal1').modal();

		 $("#attachments").val("");
		 	
	}else{
		//alert('This file size is: ' + file_size + "MB, OKE");
		 //$('#save').removeAttr('disabled');
	}

});

$( "input[id='valid_from']").datepicker({ firstDay: 1, dateFormat: 'yy-mm-dd',closeText: 'X',changeMonth: true, changeYear: true});
$( "input[id='valid_to']").datepicker({ firstDay: 1, dateFormat: 'yy-mm-dd',closeText: 'X',changeMonth: true, changeYear: true});


</script>

<!-- Modal -->
<div class="modal" id="modal1" role="dialog">
	<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal">&times;</button>
				<span class="modal-title" id="modal_title" style="font-weight: bold;">Mascot International Laos</span>
			</div>
			<div class="modal-body">
				<div id="b_loaded_data">loading</div>
			</div>
			<div class="modal-footer">
				<span id="node_selected"></span>&nbsp;&nbsp;
				<button type="button" class="btn btn-default" data-dismiss="modal">Confirm</button>
			</div>
		</div>
	</div>
</div>




<div id="jquery_dialog" style="display: none; padding-top: 10pt">
	<div id="j_loaded_data"></div>
</div>



