
<ul class="nav nav-pills">
	<li><a href="<?php echo $this->baseUrl ?>/application/role/list1">Role</a></li>
	<li><a
		href="<?php echo $this->baseUrl ?>/application/acl/update-resources">Update
			ALC Resource</a></li>
	<li><a
		href="<?php echo $this->baseUrl ?>/application/acl/list-resources">List
			ALC Resources</a></li>
</ul>
<hr>
<?php echo $counter . ' resource have been updated' ?>
