
<div id="tabs" style="font-size: 10pt">
	<ul>
		<li><a href="#general">ACL Recources</a></li>
	</ul>

	<div id="general">

		<ul class="nav nav-pills">
			<li><a href="<?php echo $this->baseUrl ?>/application/role/list1">Role</a></li>
			<li><a
				href="<?php echo $this->baseUrl ?>/application/acl/update-sys-resources">Update
					ACL Resources</a></li>
			<li><a
				href="<?php echo $this->baseUrl ?>/application/acl/list-resources">List
					ACL Resources</a></li>
		</ul>
		<hr>
		<h5><?php echo $new_counter . ' Resources have been added' ?></h5>
		<h5><?php echo $updated_counter . ' Resources have been updated' ?></h5>

	</div>
</div>