<?php

namespace UserTest\Model;

use PHPUnit_Framework_TestCase;
use Zend\Db\TableGateway;
use Zend\Db\Adapter\Adapter;
use Zend\Db\ResultSet\ResultSet;
use Zend\EventManager\EventManager;
use Zend\EventManager\Event;
use User\Model\UserTable;
use UserTest\Bootstrap;


use Zend\Mail\Message;
use Zend\Mail\Transport\File;
use Zend\Mime\Part as MimePart;
use Zend\Mime\Message as MimeMessage;
use Zend\Mime\Mime;

use Zend\Mail\Header\ContentType;

class UserTest extends PHPUnit_Framework_TestCase {
	
	/*
	public function testUserTable() {
		$resultSet = new ResultSet ();
		$userTable = Bootstrap::getServiceManager ()->get ( 'User\Model\UserTable' );
		// var_dump($userTable->getUserByID(1));
		$u =  $userTable->getUserByEmail ("ngmautri@outlook.com1");
		var_dump ( count($u) );
		
	}
	*/
	
	/*
	public function testDI() {
		$callback = function ($event) {
			echo "An event has happend \n";
			var_dump ( $event->getName () );
			var_dump ( $event->getParams () );
		};
		
		$eventManager = new EventManager ();
		$eventManager->attach ( 'eventName', $callback );
		echo "\nRaise an event\n";
		$eventManager->trigger ( 'eventName', null, array (
				'one' => 1,
				'two' => 2 
		) );
	}
	*/
	
	
	public function testSendingMail() {
		
$emailText = <<<EOT
	
<p>Welcome Mascot Laos Plattform!</p>
		
Your account is created.<br/>
click on below link to activate your account:
<p>
Regards<br/>
MLA Team
</p>
<p>(<em>This Email is generated by the system.</em>)</p>
EOT;

		$html = new MimePart($emailText);
		//$html->type = Mime::TYPE_HTML;
		
		$body = new MimeMessage();
		$body->setParts(array($html));
		
		// build message
		$message = new Message ();
		$message->addFrom ( 'mib-team@web.de' );
		$message->addTo ('ngmautri@outlook.com');
		$message->setSubject ( 'Mascot Laos Plattform Register' );
		
		$type = new ContentType();
		$type->setType('text/html');
		
		$message->getHeaders()->addHeader($type);
		$message->setBody ($emailText);
		
		$mailTransport = Bootstrap::getServiceManager ()->get ( 'SmtpTransportService' );
		
		// send message
		$mailTransport->send ( $message );
		echo $emailText;
	
	}
}

