<div id="tabs" style="font-size: 9.5pt"> 
  <ul>
  <li ><a href="#general">Currency List</a></li>
   </ul>

<div id="general"> 

<ul class="nav nav-pills">
	<li><a style="color: #0080ff;" href="<?php echo $this->baseUrl ?>/application/incoterm/add"><?php echo $this->translate("Add New Incoterm");?>
	</a></li>
</a></li>

</ul>


<hr>
<?php

if ($total_records <= 0) {
	
	echo 'No Resources found!';
} else {
	
	if (! is_null ( $paginator )) {
		echo 'Result ' . $paginator->minInPage . ' to ' . $paginator->maxInPage . ' | ' . $total_records. ' Resources found!';
	} else {
		echo $total_records. ' Resources found!';
	}
	
	?>

<table class="table table-bordered table-striped">
	<thead>
		<tr>
			<td><b>Incoterm</b></td>
		
			<td><b>Incoterm</b></td>
			<td><b>Incoterm1</b></td>
			<td><b>Incoterm1</b></td>
	 	   <td><b>Incoterm1</b></td>
	       <td><b>Incoterm1</b></td>
	
			<td><b>Date</b></td>
			<td><b>Action</b></td>
			
		</tr>
	</thead>

	<tbody>
 
	 <?php
	
	$count = 0;
	foreach ( $list as $a ) :
		$count ++;
			
		/**@var \Application\Entity\PmtOutgoing $a ;*/
		
		?>
	 <tr>
			<td><?php echo $this->escapeHtml($a->getSysNumber());?></td>
		
			<td><?php echo $this->escapeHtml($a->getVendorName());?></td>
			<td><?php echo $this->escapeHtml($a->getDocAmount());?></td>
			<td><?php echo $this->escapeHtml($a->getIsReversed());?></td>
		    <td><?php echo $this->escapeHtml($a->getPostingKey());?></td>
		   <td><?php echo $this->escapeHtml($a->getDocStatus());?></td>
		
			<td><?php if($a->getCreatedOn()!==null): echo date_format ( $a->getCreatedOn(), "d/m/Y  h:m"); endif;?> </td>

			<td>
<a href="<?php echo $this->baseUrl ?>/payment/outgoing/show?token=213214314dfds&entity_id=<?php echo $a->getID();?>&checksum=dfdfdfeedfds"><?php echo $this->translate("show");?>
</a>
			
			</td>
		</tr>
<?php endforeach; ?>

 </tbody>
</table>

<?php
	
	// ===============================
	if (! is_null ( $paginator )) :
		
		// change it only
		$base = $this->baseUrl . '/application/country/list';
		$_connector_symbol = '?';
		
		$last = $base . $_connector_symbol . 'page=' . $paginator->totalPages . '&perPage=' . $paginator->resultsPerPage;
		$first = $base . $_connector_symbol . 'page=1&perPage=' . $paginator->resultsPerPage;
		
		$p1 = ($paginator->page) - 1;
		$p2 = ($paginator->page) + 1;
		
		$prev = $base . $_connector_symbol . 'page=' . $p1 . '&perPage=' . $paginator->resultsPerPage;
		$next = $base . $_connector_symbol . 'page=' . $p2 . '&perPage=' . $paginator->resultsPerPage;
		
		echo '<ul class="pagination pagination-sm">';
		
		if ($paginator->page != 1 and $paginator->totalPages > 10) {
			echo '<li><a href="' . $first . '"> |< </a></li>';
			echo '<li><a href="' . $prev . '"> < </a></li>';
		}
		
		for($i = $paginator->minInPageSet; $i <= $paginator->maxInPageSet; $i ++) {
			
			$url = $base . $_connector_symbol . 'page=' . $i . '&perPage=' . $paginator->resultsPerPage;
			
			if ($i == $paginator->page) {
				echo '<li><a class="active" href="#">' . $i . '</a></li>';
			} else {
				echo '<li><a href="' . $url . '"> ' . $i . ' </a></li>';
			}
		}
		if ($paginator->page != $paginator->totalPages and $paginator->totalPages > 10) {
			echo '<li><a href="' . $next . '"> > </a></li>';
			echo '<li><a href="' . $last . '"> >| </a></li>';
		}
		echo '</ul>';
endif;
	
}
// ===============================
?>

</div></div>