<?php
namespace Inventory\Form\ItemComponent;

use Application\Form\Contracts\GenericForm;
use Zend\Form\Element\Hidden;

/**
 *
 * @author Nguyen Mau Tri - ngmautri@gmail.com
 *
 */
class ItemComponentForm extends GenericForm
{

    private $accountOptions;

    public function __construct($id = null)
    {
        parent::__construct($id);
        $this->id = $id;
        $this->setAttribute('method', 'post');
        $this->setAttribute('class', 'form-horizontal');
        $this->addRootElement();
        $this->addMemberElement();
    }

    public function setAction($url)
    {
        $this->setAttribute('action', $url);
        return $this;
    }

    /*
     * |=============================
     * |Autogenerate Element
     * |
     * |=============================
     */

    /**
     *
     * {@inheritdoc}
     * @see \Application\Form\Contracts\GenericForm::addElements()
     */
    protected function addElements()
    {}

    /*
     * |=============================
     * | Manual Element
     * |
     * |=============================
     */

    /**
     *
     * {@inheritdoc}
     * @see \Application\Form\Contracts\GenericForm::addManualElements()
     */
    protected function addManualElements()
    {
        $this->add([
            'type' => Hidden::class,
            'name' => 'parent'
        ]);

        $this->add([
            'type' => Hidden::class,
            'name' => 'id'
        ]);
    }

    /*
     * |=============================
     * | Function to get Form Elements
     * | Autogenerated
     * |
     * |=============================
     */
    public function getRootId()
    {
        return $this->get("group");
    }

    public function getMemberId()
    {
        return $this->get("id");
    }

    public function getAttributeCode()
    {
        return $this->get("attributeCode");
    }

    public function getAttributeName()
    {
        return $this->get("attributeName");
    }

    public function getAttributeName1()
    {
        return $this->get("attributeName1");
    }

    public function getAttributeName2()
    {
        return $this->get("attributeName2");
    }

    public function getCombinedName()
    {
        return $this->get("combinedName");
    }

    public function getRemarks()
    {
        return $this->get("remarks");
    }

    public function getGroup()
    {
        return $this->get("group");
    }
}
