
<?php // var_dump( $hits) ?>


  <form class="form-search" action="<?php echo $this->baseUrl ?>/inventory/search/asset"	method="get" enctype="multipart/form-data">
      <input type="text" name = "query" class="">
      <button type="submit" class="btn"><i class="icon-search">  </i>Search</button>
   </form>

<?php if (!$hits==null): 
echo '<span class="label label-info">';
echo count($hits).' result(s) found for query: "' . $query;
echo '</span><hr>';
?>
<table class="pure-table pure-table-bordered">
<thead>
	<tr>
		<td><b>Tag</b></td>
		<td><b>Asset Name</b></td>
		<td><b>Action</b></td>
	</tr>
</thead>
<tbody>

	 <?php 
	 
	 $count = 0;
	foreach ($hits as $hit) :
	 	 $count++;
	 echo  ($count % 2 == 1) ? "<tr>" : "<tr class=\"pure-table-odd\">";
	 	 
	 ?>
	 
     	<td><?php echo $this->escapeHtml($hit->tag);?></td>
		<td><?php echo $this->escapeHtml($hit->name);?></td>
		<td>
		<a href="<?php echo $this->baseUrl ?>/inventory/asset/edit?id=<?php echo $hit->asset_id?>">  Edit</a>
				<a href="<?php echo $this->baseUrl ?>/inventory/asset/upload-picture1?id=<?php echo $hit->asset_id?>">  Picture</a>
		
		<a href="<?php echo $this->baseUrl ?>/inventory/asset/show?id=<?php echo $hit->asset_id?>">  Detail</a>
		</td>
	</tr>
<?php endforeach; ?>
</tbody>
</table>


<?php endif; ?>
