<h3>Item</h3>

<ul style="font-size: 10pt" id="menu">
	<li><a href="<?php echo $this->baseUrl ?>/inventory/search/create-index">Create index</a></li>
	<li><a href="<?php echo $this->baseUrl ?>/inventory/search/item?q=">Search all item</a></li>
	<li><a href="<?php echo $this->baseUrl ?>/inventory/search/asset-item?q=">Search fixed asset</a></li>
	<li><a href="<?php echo $this->baseUrl ?>/inventory/search/sparepart-item?q=">Search sparepart</a></li>
	
</ul>


