<!-- 
 <ul class="nav nav-pills">
	<li><a href="<?php echo $this->baseUrl ?>/inventory/item/list">Item List</a></li>
</ul>
 
 <form class="form-inline" action="<?php echo $this->baseUrl ?>/inventory/search/item"	method="get" enctype="multipart/form-data">
  <div class="form-group">
    	<input class="form-control" size="28" type="text" name = "q" class="">
  </div>
  <div class="form-group">
     <button type="submit" class="btn btn-default"><small><i class="glyphicon glyphicon-search"> </i></small> Search</button>
  </div>
  
</form>
 -->
 
 <div id="tabs" style="font-size: 9.5pt">

	<ul>
		<li><a href="#general">Search Result</a></li>
	</ul>
<div id="general">

<?php
echo '<span>';
echo $message;
echo '</span>';

?>
	<a class="btn btn-default btn-sm" style="color:black;padding:1pt 5pt 1pt 5pt; margin:1pt 1pt 3pt 15pt;" title="Grid View" href="<?php echo $this->baseUrl ?>/inventory/search/item?layout=grid&q=<?php echo $q;?>">
	<i class="fa fa-th" aria-hidden="true"></i></a>


<?php 
if (! $hits == null) :
	
	?>
	
<table id="mytable26" style="font-size: 9.2pt; color: graytext;" class="table table-hover table-bordered">
	<thead>
		<tr style = "">
			<td><b>#</b></td>
			<td><b>ID</b></td>
			<td><b>Name</b></td>
			<td><b>SKU</b></td>
			<td><b>SKU1</b></td>
			<td><b>SKU1</b></td>
			<td><b>Manufacturer Code</b></td>
			<td><b>Manufacturer Serial</b></td>
			<td><b>Manufacturer Model</b></td>
			<td><b>Matched</b></td>
			<td><b>Action</b></td>
		</tr>
	</thead>
	<tbody>

	 <?php
	
	$count = 0;
	foreach ( $hits as $hit ) :
	$url = $nmtPlugin->getItemPic($hit->item_id);
	
		$count ++;
		// echo ($count % 2 == 1) ? "<tr>" : "<tr class=\"pure-table-odd\">";
		
		?>
	 <tr>
	
			<td> <?php echo $count;?></td>
					<td><span id="">
						<img id="item_<?php echo $this->escapeHtml($hit->item_id);?>"
								style="cursor: pointer;" title="click for more detail!"
								onclick="" class="img-rounded" width="100" height="100"
								src="<?php echo $url; ?>" />
					</span></td>
		
	
				<td>
	<span id="">
	<a style="cursor:pointer;" title="picture" item-pic="" id="<?php echo $this->escapeHtml($hit->item_id);?>" item_name="<?php echo $this->escapeHtml($hit->item_name);?>" target="blank" href="<?php echo $this->baseUrl ?>/inventory/item/show?token=<?php echo $hit->token;?>&entity_id=<?php echo $hit->item_id;?>&checksum=<?php echo $hit->checksum;?>">
	<?php echo $this->escapeHtml($hit->item_name);?></a>
	
				
				</span>
				<br><?php echo $this->escapeHtml($hit->item_sys_number);?>
				</td>
				<td><span id=""><?php echo $this->escapeHtml($hit->item_sku);?></span></td>
				<td><span id="">	</span></td>
				<td><span id=""><?php echo $this->escapeHtml($hit->serial_number_key);?></span></td>
				<td><span id=""><?php echo $this->escapeHtml($hit->manufacturer_code);?></span></td>
				<td><span id=""><?php echo  $this->escapeHtml($hit->manufacturer_serial);?></span></td>
				<td><span id=""><?php echo  $this->escapeHtml($hit->manufacturer_model);?></span></td>
    
			<td><span id=""><?php echo round($hit->score* 100,0). '%';?></span></td>
	<td>
	<a class="btn btn-default btn-sm" style="color:black;padding:1pt 5pt 2pt 5pt;" title="picture" item-pic="" id="<?php echo $this->escapeHtml($hit->item_id);?>" item_name="<?php echo $this->escapeHtml($hit->item_name);?>" target="blank" href="<?php echo $this->baseUrl ?>/inventory/item/show?token=<?php echo $hit->token;?>&entity_id=<?php echo $hit->item_id;?>&checksum=<?php echo $hit->checksum;?>">
	<i class="fa fa-eye" aria-hidden="true"></i></a>
	<a class="btn btn-default btn-sm" style="color:black;padding:1pt 5pt 2pt 5pt;" title="edit" href="<?php echo $this->baseUrl ?>/inventory/item/update?token=<?php echo $hit->token;?>&entity_id=<?php echo $hit->item_id;?>&checksum=<?php echo $hit->checksum;?>"><i class="fa fa-pencil" aria-hidden="true"></i></a>
	<a class="btn btn-default btn-sm" style="color:black;padding:1pt 5pt 2pt 5pt;" title="add attachment" href="<?php echo $this->baseUrl ?>/inventory/item-attachment/upload?token=<?php echo $hit->token;?>&target_id=<?php echo $hit->item_id;?>&checksum=<?php echo $hit->checksum;?>"><i class="fa fa-paperclip" aria-hidden="true"></i></a>

	<a class="btn btn-default btn-sm" style="color:black;padding:1pt 2pt 2pt 2pt;" href="<?php echo $this->baseUrl ?>/inventory/item/upload-picture?token=<?php echo $hit->token;?>&target_id=<?php echo $hit->item_id;?>&checksum=<?php echo $hit->checksum;?>">Upload picture</a>
</a>
		
	</td>	
		</tr>
<?php endforeach; ?>
</tbody>
</table>


<?php endif; ?>
</div></div>

