
<?php // var_dump( $hits) ?>

<ul class="nav nav-pills">
 <li><a href="<?php echo $this->baseUrl ?>/inventory/spareparts/category">Spare-part Category</a></li>
 </ul>

  <form class="form-search" action="<?php echo $this->baseUrl ?>/inventory/search/sparepart"	method="get" enctype="multipart/form-data">
      <input type="text" name = "query" class="">
      <button type="submit" class="btn"><i class="icon-search">  </i>Search</button>
   </form>

 
<?php if (!$hits==null): 
echo '<span class="label label-info">';
echo count($hits).' result(s) found for query: "' . $query;
echo '</span><br>';
?>

<table class="pure-table pure-table-bordered">
<thead>
	<tr>
		<td><b>Tag</b></td>
		<td><b>Name</b></td>
		<td><b>Code</b></td>
		<td><b>Action</b></td>
	</tr>
</thead>
<tbody>

	 <?php 
	 
	 $count = 0;
	foreach ($hits as $hit) :
	 	 $count++;
	 echo  ($count % 2 == 1) ? "<tr>" : "<tr class=\"pure-table-odd\">";
	 	 
	 ?>

    	<td><?php echo $this->escapeHtml($hit->tag);?></td>
		<td><span id="<?php echo $hit->sparepart_id?>_name"><?php echo $this->escapeHtml($hit->name);?></span></td>
		<td><?php echo $this->escapeHtml($hit->code);?></td>
		<td>
		<a href="#" onclick="openPRCart('<?php echo $hit->sparepart_id?>');"><i class="icon-shopping-cart"></i>Order</a>
		
		<a href="<?php echo $this->baseUrl ?>/inventory/spareparts/edit?id=<?php echo $hit->sparepart_id?>">  Edit</a>
		<a href="<?php echo $this->baseUrl ?>/inventory/spareparts/upload-picture?id=<?php echo $hit->sparepart_id?>">  Picture</a>
					
		<a href="<?php echo $this->baseUrl ?>/inventory/spareparts/receive?sparepart_id=<?php echo $hit->sparepart_id?>">  Receive</a>			
		<a href="<?php echo $this->baseUrl ?>/inventory/spareparts/issue?sparepart_id=<?php echo $hit->sparepart_id?>">  Issue</a>
		<a href="<?php echo $this->baseUrl ?>/inventory/spareparts/show?id=<?php echo $hit->sparepart_id?>">  Detail</a>
		</td>
	</tr>
<?php endforeach; ?>
</tbody>
</table>


<?php endif; ?>

<!-- Modal -->
	<div id="myModal" class="modal hide" role="dialog">
	  <div class="modal-dialog">
	  	 <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h5 class="modal-title">Add To Cart</h5>
      </div>
	      <div class="modal-body">
	  <div>
	  <span id="_status"></span>
	  </div>

<form class="form-horizontal" action="<?php echo $this->baseUrl ?>/procurement/pr/select-item-2"	method="post" enctype="multipart/form-data" id="NewSP" >
<input type="hidden" name="redirectUrl" value="<?php echo $redirectUrl ?>" />
<input type="hidden" name="article_id" id ="item_id" value="" />
 	
	 	 <div class="control-group">
	        <label class="control-label" for="inputNameLocal">Priority:</label>
        <div class="controls">
        	<select name="priority" id ="item_priority">
        		<option value="Low">Low</option>
        		<option value="Medium" selected>Medium</option>
        		<option value="High">High</option>
        		<option value="Urgent">Urgent</option>
 			</select>
	     </div>
      </div>
      	
      <div class="control-group">
        <label class="control-label" for="inputTag">Name:</label>
        <div class="controls">
          <input type="text" id="item_name" placeholder="" name="name" value="article">
        </div>
      </div>
      
      <div class="control-group">
        <label class="control-label" for="inputTag">Unit</label>
        <div class="controls">
          <input type="text" id="item_unit" placeholder="" name="quantity" value="">
        </div>
      </div>
      
       <div class="control-group">
        <label class="control-label" for="inputTag">Quantity:</label>
        <div class="controls">
          <input type="text" id="item_quantity" placeholder="" name="quantity" value="">
        </div>
      </div>
      
     
      
      <div class="control-group">
        <label class="control-label" for="inputNameLocal">Requested Delivery Date:</label>
        <div class="controls">
          <input type="text" id="end_date" placeholder="click to select" name="EDT" value="">
        </div>
      </div>
      
       <div class="control-group">
        <label class="control-label" for="inputDescription">Reason /Note:</label>
        <div class="controls">
          <textarea id="item_remarks" placeholder="" rows="2" cols="5" name="remarks"></textarea>
        </div>
      </div>
    </form>
	      </div>
	      
		  <div class="modal-footer">
	        <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
	        <button onclick="addItemToCart('SPARE_PART');" type="button" class="btn btn-primary">Add To Cart</button>
	      </div>
	   </div>
	</div>
	
	<!-- Modal -->
	<div id="myModal1" class="modal hide" role="dialog">
	  <div class="modal-dialog">
	      <div class="modal-body">
	        <p>Working on it........Please Wait!</p>
	      </div>
	   </div>
	</div>		

