 <ul class="nav nav-pills">
	<li><a href="<?php echo $this->baseUrl ?>/hr/employee/list">Employee List</a></li>
</ul>
 
 <form class="form-inline" action="<?php echo $this->baseUrl ?>/hr/employee-search/do"	method="get" enctype="multipart/form-data">
  <div class="form-group">
    	<input class="form-control" size="28" type="text" name = "q" class="">
  </div>
  <div class="form-group">
     <button type="submit" class="btn btn-default"><small><i class="glyphicon glyphicon-search"> </i></small> Search</button>
  </div>
  
</form>


<?php
echo '<hr>';
echo '<span>';
echo $message;
echo '</span>';

if (! $hits == null) :
	
	?>
<table style = "font-size: 10pt;" class="table table-hover table-bordered">
	<thead>
		<tr style = "">
			<td><b>#</b></td>
			<td><b>Code</b></td>
			<td><b>Name</b></td>
			<td><b>Birthday</b></td>
			<td><b>Matched</b></td>
			<td><b>Action</b></td>
		</tr>
	</thead>
	<tbody>

	 <?php
	
	$count = 0;
	foreach ( $hits as $hit ) :
		$count ++;
		// echo ($count % 2 == 1) ? "<tr>" : "<tr class=\"pure-table-odd\">";
		
		?>
	 <tr>
	
			<td> <?php echo $count;?></td>
	
				<td><span id=""><?php echo $this->escapeHtml($hit->employee_code);?></span></td>
				<td><span id=""><?php echo $this->escapeHtml($hit->employee_name);?></span></td>
				<td><span id=""></span></td>
				<td><span id=""><?php echo round($hit->score* 100,0). '%';?></span></td>
	<td>
	<a href="<?php echo $this->baseUrl ?>/hr/employee/show?token=<?php echo $hit->token;?>&checksum=<?php echo $hit->checksum;?>&target_id=<?php echo $this->escapeHtml($hit->employee_id);?>">show</a>
	</td>	
		</tr>
<?php endforeach; ?>
</tbody>
</table>


<?php endif; ?>
