<form class="form-inline" action=""	method="get" enctype="multipart/form-data">
  <div class="form-group">
    	<input class="form-control" size="25" type="text" id ="search_term_<?php echo $context;?>" name = "q">
   </div>
  <div class="form-group">
     <button type="submit" class="btn btn-default" onclick="searchEntity('/hr/employee-search/do1','<?php echo $context;?>');"><small><i class="glyphicon glyphicon-search"> </i></small> Search</button>
  </div>
  
</form>

<div>
<ul class="nav nav-pills">
		<li><a style="color: #0080ff;" href="/procurement/vendor/add"><i
				class="glyphicon glyphicon-plus"> </i>&nbsp;New Employee </a>
		
		<li><a style="color: #0080ff;" href="javascript:;"
		onclick="loadData1('/hr/employee/select','<?php echo $context;?>');"><i class="glyphicon glyphicon-list"> </i>&nbsp;All Employees
			</a>
		</ul>
</div>

<?php
echo '<span style = "color: gray; font-size: 9pt;">';
echo $message;
echo '</span>';

if (! $hits == null) :
	?>
<table style = "font-size: 10pt;" class="table table-hover table-bordered">
	<thead>
		<tr>
			<td><b>#</b></td>
			<td><b>Select</b></td>
			<td><b>Code</b></td>
			<td><b>Employee</b></td>
			<!--  <td><b>Birthday</b></td>-->
		</tr>
	</thead>
	<tbody>

	 <?php
	
	$count = 0;
	foreach ( $hits as $hit ) :
		$count ++;
		// echo ($count % 2 == 1) ? "<tr>" : "<tr class=\"pure-table-odd\">";
		
		?>
	 <tr>
	
			<td> <?php echo $count;?></td>
	 		<td>		
<a href="javascript:;"
	onclick="selectId('<?php echo $this->escapeHtml($hit->employee_id);?>','employee_id','<?php echo $this->escapeHtml($hit->employee_name);?>','employee_name');"><small><i class="glyphicon glyphicon-triangle-right"></i></small>&nbsp;Select
</a></td>
			<td><?php echo $this->escapeHtml($hit->employee_code);?></td>
	 		<td><?php echo $this->escapeHtml($hit->employee_name);?></td>
		<td>
<a target="blank" href="<?php echo $this->baseUrl ?>/hr/employee/show?token=<?php echo $hit->token;?>&checksum=<?php echo $hit->checksum;?>&target_id=<?php echo $hit->employee_id;?>">Show</a> <small><i class="glyphicon glyphicon-new-window"> </i></small>
	</td>	
		</tr>
<?php endforeach; ?>
</tbody>
</table>


<?php endif; ?>
