<h4>Create Payment Method:</h4>
<?php
if (count ( $errors ) > 0) {
	echo '<div class="alert alert-danger" role="alert">';
	
	echo '<ul>';
	foreach ( $errors as $error ) :
		echo '<li>' . $error . '</li>';
	endforeach
	;
	echo '</ul>';
	echo '</div>';
}
?>

<div id="tabs"> 
  <ul>
  <li ><a href="#general">Method</a></li>
   </ul>

<div id="general">
<form class="form-horizontal"
	action="<?php echo $this->baseUrl ?>/application/pmt-method/add"
	method="post" enctype="multipart/form-data">
	<input type="hidden" name="redirectUrl"
		value="<?php echo $redirectUrl ?>" />	

	<div class="form-group">
		<label class="control-label col-sm-2" for="inputTag">Method Code</label>
		<div class="col-sm-3">
			<input class="form-control" type="text" id="inputTag" placeholder=""
				name="pmt_method_code" value="">
		</div>
	</div>
	
	<div class="form-group">
		<label class="control-label col-sm-2" for="inputTag">Method Name</label>
		<div class="col-sm-3">
			<input class="form-control" type="text" id="inputTag" placeholder=""
				name="pmt_method_name" value="">
		</div>
	</div>

	

	<div class="form-group">
		<label class="control-label col-sm-2" for="inputDescription">Description</label>
		<div class="col-sm-3">
			<textarea class="form-control" id="inputDescription" placeholder=""
				rows="2" name="description"></textarea>
		</div>
	</div>

	
	<div class="form-group">
		<label class="control-label col-sm-2" for="inputTag">Status</label>
		<div class="col-sm-3">
			<select class="form-control" name="parent">
				<option selected="selected" value="Activated">Activated</option>
				<option value="Deactivated">Deactivated</option>
			</select>
		</div>
	</div>

	<div class="form-group">
		<div class="col-sm-offset-2 col-sm-10">
			<button type="submit" class="btn btn-default">Submit</button>
		</div>
	</div>
</form>
</div>
</div>



<div id="dialog" style="display: none;">Check code...</div>