<a class="btn btn-default" href="<?php echo $this->baseUrl ?>/hr/employee-leave/add?token=<?php echo (!$target== null)? $target->getToken():"";?>&target_id=<?php echo (!$target== null)? $target->getID():"";?>"><small><i class="glyphicon glyphicon-plus"> </i></small>&nbsp;Apply New Leave</a>
<hr>

<table style="font-size: 10pt;" class="table table-bordered table-hover">
	<thead>
		<tr>
			<td><b>#</b></td>
			<td><b>Start Date</b></td>
			<td><b>End Date</b></td>
			<td><b>Total Days</b></td>
			<td><b>Leave Reason</b></td>
			<td><b>Supporing<br>Document</b></td>
			<td><b>Status</b></td>
			<td><b>Comment</b></td>
			<td><b>Action</b></td>
		</tr>
	</thead>
    	<tr>
    			<td>#</td>
    			<td>10-06-2017</td>
    			<td>10-06-2017</td>
    			<td>0,5</td>
    			<td>Sick Leave</td>
    			<td>Yes</td>
    			<td>Approved</td>
    			<td>Doctor check</td>
    			<td>see suporting Document</td>
    		</tr>
			<tr>
    			<td>#</td>
    			<td>10-07-2017</td>
    			<td>10-07-2017</td>
    			<td>1</td>
    			<td>Approved Leave</td>
    			<td>Yes</td>
    			<td>Approved</td>
    			<td>Go to bank</td>
    			<td>attach document</td>
    		</tr>
    		<tr>
    			<td>#</td>
    			<td>15-07-2017</td>
    			<td>18-07-2017</td>
    			<td>3</td>
    			<td>Approved Leave</td>
    			<td>Yes</td>
    			<td>Pending</td>
    			<td>N/A</td>
    			<td>see suporting Document</td>
    		</tr>
	<tbody>
 	 <tr>
  	 </tr>
 </tbody>
</table>
