
<table class="table table-striped table-bordered">
	<thead>
		<tr>
			<td><b>Warehouse Code</b></td>
			<td><b>Warehouse Name</b></td>
			<td><b>In Stock</b></td>

		</tr>
	</thead>
	<tbody>	
 
  <?php
$count = 0;
foreach ($balances as $item) :
    $count ++;
    // echo ($count % 2 == 1) ? "<tr>" : "<tr class=\"pure-table-odd\">";

    ?>
	 <tr>
			<td><?php echo $item->wh_code?></td>
			<td><?php echo $item->wh_name?></td>
			<td><?php echo $item->current_balance?></td>
		</tr>
	
<?php endforeach; ?>

</tbody>
</table>
<hr>
