
<div id="tabs" style="font-size: 9.5pt">

	<ul>
		<li><a href="#general"><?php echo $this->translate('Applicant List'); ?></a></li>
	</ul>
	<div id="general">

		<a class="btn btn-default btn-sm"
			href="<?php echo $this->baseUrl ?>/hr/employee/add"><i
			class="fa fa-user-plus" aria-hidden="true"></i>&nbsp;<?php echo $this->translate('New Applicant'); ?></a>
		<a class="btn btn-default btn-sm" href="javascript:;"
			onclick="showJqueryDialog('<?php echo $this->translate('Search Applicant'); ?>','750','520', '/hr/employee/select','j_loaded_data', true);"><i
			class="fa fa-search" aria-hidden="true"></i>&nbsp;<?php echo $this->translate('Search Applicant'); ?></a>
		<hr>

		<div>
			<small><span class="glyphicon glyphicon-filter"></span></small>&nbsp;<a
				href="#transaction" class="" data-toggle="collapse"><?php echo $this->translate('Filter'); ?></a>
		</div>
		<div id="transaction" class="collapse">

			<!-- <div style="border: 1px; padding: 3px; font-size: 9pt; background: url(/images/bg1.png); background-repeat: repeat-x; background-color: #FFFFFF;"> -->
			<div style="border: 1px; padding: 3px; font-size: 9pt;">
				<form class="form-horizontal"
					action="<?php echo $this->baseUrl ?>/procure/pr/all<?php echo "/row_number=".$row_number?><?php echo $status!==null? "/status=".$status:"";?>"
					method="get" enctype="multipart/form-data">

					<div class="form-group margin-bottom">
						<label class="control-label col-sm-2" for="inputTag"><?php echo $this->translate('Applicant Status'); ?></label>
						<div class="col-sm-3">
							<select class="form-control input-sm" name="is_active">
								<option <?php echo $is_active =='2'? "selected='selected'":"";?>
									value="2">All</option>
								<option <?php echo $is_active=='1'? "selected='selected'":"";?>
									value="1">Active</option>
								<option <?php echo $is_active=='-1'? "selected='selected'":"";?>
									value="-1">Inactive</option>
							</select>
						</div>
					</div>

					<div class="form-group margin-bottom">
						<label class="control-label col-sm-2" for="inputTag"><?php echo $this->translate('Sort by'); ?></label>
						<div class="col-sm-3">
							<select class="form-control input-sm" name="sort_by">
								<option value="">None</option>
								<option
									<?php echo $sort_by=='prNumber'? "selected='selected'":"";?>
									value="prNumber"><?php echo $this->translate('Employee Code'); ?></option>
								<option
									<?php echo $sort_by=='createdOn'? "selected='selected'":"";?>
									value="createdOn"><?php echo $this->translate('Created Date'); ?></option>
							</select> <input
								<?php if(!$sort==null): echo ($sort=='ASC')? "checked":""; else: echo "checked"; endif;?>
								type="radio" name="sort" value="ASC">&nbsp;<?php echo $this->translate('ASC'); ?>&nbsp;&nbsp; <input
								<?php if(!$sort==null): echo ($sort=='DESC')? "checked":""; else: echo ""; endif;?>
								type="radio" name="sort" value="DESC">&nbsp;<?php echo $this->translate('DESC'); ?>&nbsp;&nbsp;

				</div>
					</div>


					<div class="form-group margin-bottom">
						<label class="control-label col-sm-2" for="inputTag"><?php echo $this->translate('Result per page'); ?></label>
						<div class="col-sm-3">
							<select class="form-control input-sm" name="perPage">
								<option value="">None</option>
								<option <?php echo $per_pape=='15'? "selected='selected'":"";?>
									value="15">15</option>

								<option <?php echo $per_pape=='20'? "selected='selected'":"";?>
									value="20">20</option>

								<option <?php echo $per_pape=='30'? "selected='selected'":"";?>
									value="30">30</option>

								<option <?php echo $per_pape=='50'? "selected='selected'":"";?>
									value="50">50</option>
								<option <?php echo $per_pape=='100'? "selected='selected'":"";?>
									value="100">100</option>
								<option <?php echo $per_pape=='200'? "selected='selected'":"";?>
									value="200">200</option>
							</select>
						</div>
					</div>

					<div class="form-group margin-bottom">
						<div class="col-sm-offset-2 col-sm-10">
							<button type="submit" class="btn btn-default"><?php echo $this->translate('Filter'); ?></button>
						</div>
					</div>

				</form>

			</div>
			<hr>
		</div>


		<div style="color: gray; font-size: 9pt; margin-top: 8px"><?php echo $this->translate('Employee Status')." = ".$is_active;?>&nbsp;|&nbsp;<?php echo $this->translate('Sort by'). " = ".$sort_by;?>&nbsp;|&nbsp;<?php echo $this->translate('Sort'). " = ".$sort ?></div>
		<br>

<?php

if ($total_records <= 0) {

    echo 'No record found!';
} else {

    if (! is_null($paginator)) {
        echo $paginator->minInPage . ' - ' . $paginator->maxInPage . ' | ' . $total_records . ' ' . $this->translate('records');
    } else {
        echo $total_records . ' ' . $this->translate('records');
    }

    ?>

<table style="font-size: 10pt;" class="table table-bordered table-hover">
			<thead>
				<tr>
					<td><b>#</b></td>
					<td><b><?php echo $this->translate('Employee Code'); ?></b></td>
					<td><b><?php echo $this->translate('Name'); ?></b></td>
					<td><b><?php echo $this->translate('Name'); ?> (local)</b></td>
					<td><b><?php echo $this->translate('Birthday'); ?></b></td>
					<td><b><?php echo $this->translate('Gender'); ?></b></td>
					<td><b><?php echo $this->translate('Employee Status'); ?></b></td>
					<td><b><?php echo $this->translate('Action'); ?></b></td>
				</tr>
			</thead>

			<tbody>
 
	 <?php

    $count = 0;
    foreach ($list as $a) :
        /**@var \Application\Entity\NmtHrEmployee $a ;*/

        $count ++;

        ?>
	 <tr>
					<td><?php echo ($paginator===null)? $count:$paginator->minInPage -1+ $count;?></td>
					<td>N/A</td>
					<td><?php echo $this->escapeHtml($a->getEmployeeName());?></td>
					<td><?php echo $this->escapeHtml($a->getEmployeeNameLocal());?></td>
					<td><?php echo ($a->getBirthday()!==null )? date_format ( $a->getBirthday(), "d-m-y"):"";?> </td>
					<td><?php echo $this->escapeHtml($a->getGender());?></td>
					<td>1</td>

					<td><a
						href="<?php echo $this->baseUrl ?>/hr/employee/show?token=<?php echo $this->escapeHtml($a->getToken());?>&checksum=<?php echo $a->getChecksum();?>&entity_id=<?php echo $this->escapeHtml($a->getID());?>"><?php echo $this->translate('Show'); ?></a>
						<a
						href="<?php echo $this->baseUrl ?>/hr/employee/edit?token=<?php echo $this->escapeHtml($a->getToken());?>&checksum=<?php echo $a->getChecksum();?>&entity_id=<?php echo $this->escapeHtml($a->getID());?>"><?php echo $this->translate('Edit'); ?></a>
					</td>

				</tr>
<?php endforeach; ?>

 </tbody>
		</table>

<?php

    // ===============================
    if (! is_null($paginator)) :

        // change it only
        $base = $this->baseUrl . '/hr/employee/applicant-list?is_active=' . $is_active . '&sort_by=' . $sort_by . '&sort=' . $sort;
        $_connector_symbol = '&';

        $last = $base . $_connector_symbol . 'page=' . $paginator->totalPages . '&perPage=' . $paginator->resultsPerPage;
        $first = $base . $_connector_symbol . 'page=1&perPage=' . $paginator->resultsPerPage;

        $p1 = ($paginator->page) - 1;
        $p2 = ($paginator->page) + 1;

        $prev = $base . $_connector_symbol . 'page=' . $p1 . '&perPage=' . $paginator->resultsPerPage;
        $next = $base . $_connector_symbol . 'page=' . $p2 . '&perPage=' . $paginator->resultsPerPage;

        echo '<ul class="pagination pagination-sm">';

        if ($paginator->page != 1 and $paginator->totalPages > 10) {
            echo '<li><a href="' . $first . '"> |< </a></li>';
            echo '<li><a href="' . $prev . '"> < </a></li>';
        }

        for ($i = $paginator->minInPageSet; $i <= $paginator->maxInPageSet; $i ++) {

            $url = $base . $_connector_symbol . 'page=' . $i . '&perPage=' . $paginator->resultsPerPage;

            if ($i == $paginator->page) {
                echo '<li><a class="active" href="#">' . $i . '</a></li>';
            } else {
                echo '<li><a href="' . $url . '"> ' . $i . ' </a></li>';
            }
        }
        if ($paginator->page != $paginator->totalPages and $paginator->totalPages > 10) {
			echo '<li><a href="' . $next . '"> > </a></li>';
			echo '<li><a href="' . $last . '"> >| </a></li>';
		}
		echo '</ul>';
endif;
	
}
// ===============================
?>
</div>
</div>