
  
<ul class="nav nav-pills">
	<li><a
		href="<?php echo $this->baseUrl ?>/hr/employee/add"><i class="icon-plus">  </i> Add
			New Employee</a></li>
			
			<li><a href="<?php echo $this->baseUrl ?>/hr/employee/list?output=csv"><i class="icon-download-alt">  </i> Download (csv)</a> 
</li>
</ul>

<form class="form-search" action="/hr/employee/search"	method="get" enctype="multipart/form-data">
      <input type="text" name = "query" class="">
      <button type="submit" class="btn"><i class="icon-search">  </i>Search</button>
   </form>

<?php

if ($total_employees<= 0) {
	
	echo 'No spare part found!';
} else {
	
	if (! is_null ( $paginator )) {
		echo '<h5>Result ' . $paginator->minInPage . ' to ' . $paginator->maxInPage . ' | ' . $total_employees. ' members found! </h5>';
		;
	} else {
		echo '<h5>' . $total_employees. ' spare parts found! </h5>';
	}
	?>


<table class="table table-striped table-bordered">
	<thead>
		<tr>
			<td><b>#</b></td>
			<td><b>Photo</b></td>
			<td><b>Code</b></td>
			<td><b>name</b></td>
			<td><b>Gender</b></td>
			<td><b data-toggle="tooltip" title="Current Balance">Birthday</b></td>
			<td><b data-toggle="tooltip" title="Minimum Balance">Remarks</b></td>
			<td><b>ACTION</b></td>
		</tr>
	</thead>
	<tbody>
	  <?php
	
	$count = 0;
	foreach ( $employees as $a ) :
		 $count++;
		// echo ($count % 2 == 1) ? "<tr>" : "<tr class=\"pure-table-odd\">";
		
		?>
	<tr>
		<td><?php echo ($paginator===null)? $count:$paginator->minInPage -1+ $count;?></td>
			<td>
			<?php 
			if($a->sp_pic_id!==null):
			?>
			<a href="<?php echo $this->baseUrl ?>/inventory/spareparts/show?id=<?php echo $this->escapeHtml($a['id']);?>">
			<img class= "img-rounded" width="90" height="100" src="/hr/image/employee-thumbnail-200?id=<?php echo $a->sp_pic_id;?>"/>
		</a>			
			<?php 
			else:
			?>
			<img class= "img-rounded" width="70" height="80" src="/images/no-pic.jpg"/>
				
			<?php 
			endif;
			?>
			
			</td>
			
			<td><?php echo $a['employee_code'];?></td>
			<td>

				<div class="dropdown">
					<a style="" class="dropdown-toggle" type="button" data-toggle="dropdown"
						href="#"><span style="color:black;" id="<?php echo $this->escapeHtml($a['id']);?>_name"><b><?php echo $this->escapeHtml($a['employee_name']);?></b></span>
						<span class="caret"></span></a>
				</div>
			</td>
			<td><?php echo $a['employee_gender'];?></td>
			<td><?php echo date_format(date_create($a['employee_dob']),"d-m-Y");?></td>
			<td><?php echo $a['remarks'];?></td>
			<td><a href="<?php echo $this->baseUrl ?>/hr/employee/upload-picture1?id=<?php echo $this->escapeHtml($a['id']);?>">upload picture</a>
	</td>	
		</tr>
<?php endforeach; ?>

</tbody>
</table>

<br>

<?php
	
	if (! is_null ( $paginator )) {
		
		// change it only
		$base = $this->baseUrl . '/hr/employee/list';
		
		$_connector_symbol = '?';
		
		$last = $base . $_connector_symbol . 'page=' . $paginator->totalPages . '&perPage=' . $paginator->resultsPerPage;
		$first = $base . $_connector_symbol . 'page=1&perPage=' . $paginator->resultsPerPage;
		
		$p1 = ($paginator->page) - 1;
		$p2 = ($paginator->page) + 1;
		
		$prev = $base . $_connector_symbol . 'page=' . $p1 . '&perPage=' . $paginator->resultsPerPage;
		$next = $base . $_connector_symbol . 'page=' . $p2 . '&perPage=' . $paginator->resultsPerPage;
		
		echo '<ul class="pagination">';
		
		if ($paginator->page != 1 and $paginator->totalPages > 10) {
			echo '<li><a href="' . $first . '"> |< </a></li>';
			echo '<li><a href="' . $prev . '"> < </a></li>';
		}
		
		for($i = $paginator->minInPageSet; $i <= $paginator->maxInPageSet; $i ++) {
			
			$url = $base . $_connector_symbol . 'page=' . $i . '&perPage=' . $paginator->resultsPerPage;
			
			if ($i == $paginator->page) {
				echo '<li><a class="active" href="#">' . $i . '</a></li>';
			} else {
				echo '<li><a href="' . $url . '"> ' . $i . ' </a></li>';
			}
		}
		if ($paginator->page != $paginator->totalPages and $paginator->totalPages > 10) {
			echo '<li><a href="' . $next . '"> > </a></li>';
			echo '<li><a href="' . $last . '"> >| </a></li>';
		}
		echo '</ul>';
	}
}
?>


<?php include (ROOT.'\module\Inventory\view\inventory\sp_order_form.php'); ?>