
<?php // var_dump( $hits) ?>
<ul class="nav nav-pills">
 <li><a href="<?php echo $this->baseUrl ?>/hr/employee/list">All Employee</a></li>
</ul>

  <form class="form-search" action="<?php echo $this->baseUrl ?>/hr/employee/search"	method="get" enctype="multipart/form-data">
      <input type="text" name = "query" class="">
      <button type="submit" class="btn"><i class="icon-search">  </i>Search</button>
   </form>

<?php if ($error!==null)
{
	echo '<div class="alert alert-error">';
	echo $error;
	echo '</div>';
} 
?>


<?php if (!$hits==null): 
echo '<span class="label label-info">';
echo count($hits).' result(s) found for query: "' . $query;
echo '</span><br>';
?>
<table class="table table-striped table-bordered">
	<thead>
		<tr>
			<td><b>#</b></td>
			<td><b>Photo</b></td>
			<td><b>Code</b></td>
			<td><b>name</b></td>
			<td><b>Gender</b></td>
			<td><b data-toggle="tooltip" title="Current Balance">Birthday</b></td>
			<td><b>ACTION</b></td>
		</tr>
	</thead>
	<tbody>

	 <?php 
	 
	 $count = 0;
	foreach ($hits as $hit) :
	 	 $count++;
	 ?>
	 <tr>
	 	<td><?php echo $count;?></td>
	 	
	 	<td>
			<?php 
			if($hit->sp_pic_id!==""):
			?>
			<img class= "img-rounded" width="90" height="100" src="/hr/image/employee-thumbnail-200?id=<?php echo $hit->sp_pic_id;?>"/>
			<?php 
			else:
			?>
			<img class= "img-rounded" width="70" height="80" src="/images/no-pic.jpg"/>
			<?php 
			endif;
			?>
			
			</td>
	 	
		<td><span id="<?php echo $hit->employee_code?>_code"><?php echo $this->escapeHtml($hit->employee_code);?></span></td>

		<td><span id="<?php echo $hit->employee_name?>_name"><?php echo $this->escapeHtml($hit->employee_name);?></span></td>
		<td><span id="<?php echo $hit->employee_name?>_gender"><?php echo $this->escapeHtml($hit->employee_gender);?></span></td>
		<td><span id="<?php echo $hit->employee_name?>_dob"><?php echo date_format(date_create($hit->employee_dob),"d-m-Y"); ?></span></td>
	
		<td>
<a href="<?php echo $this->baseUrl ?>/hr/employee/upload-picture1?id=<?php echo $this->escapeHtml($hit->employee_id);?>">upload picture</a>
		</td>
	</tr>
<?php endforeach; ?>
</tbody>
</table>


<?php endif; ?>


<!-- Modal -->
<div id="myModal" class="modal hide" role="dialog">
	<div class="modal-dialog">
		<div class="modal-header">
			<button type="button" class="close" data-dismiss="modal">&times;</button>
			<h5 class="modal-title">Mascot International (Laos)</h5>
		</div>
		<div class="modal-body">
			<span id="_status"></span>

			<form class="form-horizontal"
				action="<?php echo $this->baseUrl ?>/procurement/pr/select-item-2"
				method="post" enctype="multipart/form-data" id="NewSP">
				<input type="hidden" name="redirectUrl"
					value="<?php echo $redirectUrl ?>" /> <input type="hidden"
					name="vendor_id" id="item_id" value="" />

				<div class="control-group">
					<label class="control-label" for="inputNameLocal">Priority:</label>
					<div class="controls">
						<select name="priority" id="item_priority">
							<option value="Low">Low</option>
							<option value="Medium" selected>Medium</option>
							<option value="High">High</option>
							<option value="Urgent">Urgent</option>
						</select>
					</div>
				</div>

				<div class="control-group">
					<label class="control-label" for="inputTag">Name:</label>
					<div class="controls">
						<input type="text" id="item_name" placeholder="" name="name"
							value="article">
					</div>
				</div>
	
				<div class="control-group">
					<label class="control-label" for="inputTag">Code:</label>
					<div class="controls">
						<input type="text" id="item_code" placeholder="" name="code"
							value="">
					</div>
				</div>
				
				<div class="control-group">
					<label class="control-label" for="inputTag">Unit:</label>
					<div class="controls">
						<input type="text" id="item_unit" placeholder="" name="unit"
							value="">
					</div>
				</div>
				

				<div class="control-group">
					<label class="control-label" for="inputTag">Quantity:</label>
					<div class="controls">
						<input type="text" id="item_quantity" placeholder=""
							name="quantity" value="">
					</div>
				</div>

				<div class="control-group">
					<label class="control-label" for="inputNameLocal">Requested
						Delivery Date:</label>
					<div class="controls">
						<input type="text" id="end_date" placeholder="click to select"
							name="EDT" value="">
					</div>
				</div>

				<div class="control-group">
					<label class="control-label" for="inputDescription">Reason /Note:</label>
					<div class="controls">
						<textarea id="item_remarks" placeholder="" rows="2" cols="5"
							name="remarks"></textarea>
					</div>
				</div>
			</form>
		</div>

		<div class="modal-footer">
			<button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
			<button onclick="addItemToCart('ARTICLE');" type="button"
				class="btn btn-primary">Add To Cart</button>
		</div>
	</div>
</div>

<!-- Modal -->
<div id="myModal1" class="modal hide" role="dialog">
	<div class="modal-dialog">
		<div class="modal-body">
			<p>Working on it........Please Wait!</p>
		</div>
	</div>
</div>
