 <form class="form-inline" action=""	method="get" enctype="multipart/form-data">
  <div class="form-group">
    	<input class="form-control" size="25" type="text" id ="search_term_<?php echo $context;?>" name = "query">
   </div>
  <div class="form-group">
     <button type="submit" class="btn btn-default" onclick="searchEntity('/hr/employee-search/do1','<?php echo $context;?>');"><small><i class="glyphicon glyphicon-search"> </i></small> Search</button>
  </div>
  
</form>
<div>
<ul class="nav nav-pills">
		<li><a style="color: #0080ff;" href="/procurement/vendor/add"><i
				class="glyphicon glyphicon-plus"> </i>&nbsp;New Employee </a>
		
		<li><a style="color: #0080ff;" href="javascript:;"
			onclick="loadData1('/hr/employee/select','<?php echo $context;?>');"><i class="glyphicon glyphicon-list"> </i>&nbsp;All Employees
		</a>
		</ul>
</div>
<?php

if ($total_records <= 0) {
	
	echo 'No Resources found!';
} else {
	
	if (! is_null ( $paginator )) {
		echo 'Result ' . $paginator->minInPage . ' to ' . $paginator->maxInPage . ' | ' . $total_records. ' Resources found!';
	} else {
		echo $total_records. ' record found!';
	}
	
	?>

<div id="search_result"></div>
<table style="font-size: 10pt" class="table table-bordered table-hover">
	<thead>
		<tr>
			<td><b>#</b></td>
			<td><b>Select</b></td>
			<td><b>Code</b></td>
			<td><b>Employee</b></td>
			<!--  <td><b>Birthday</b></td>-->
			<td></td>
			
		</tr>
	</thead>

	<tbody>
	
	 <tr>
	 	 	<td></td>		
	 
	 		<td>		
<a href="javascript:;"
	onclick="selectId('0','employee_id','','employee_name');"><small><i class="glyphicon glyphicon-triangle-right"></i></small>&nbsp;Select
</a></td>
			<td>NONE</td>
	 		<td>NONE</td>
	 		<td></td>
	 	</tr>
 
	 <?php
	
	$count = 0;
	foreach ( $list as $a ) :
		$count ++;
	?>
	 <tr>
	 	 	<td><?php echo $count; ?></td>		
	 
	 		<td>		
<a href="javascript:;"
	onclick="selectId('<?php echo $a->getId();?>','employee_id','<?php echo $a->getEmployeeCode()." - ".$a->getEmployeeName();?>','employee_name');"><small><i class="glyphicon glyphicon-triangle-right"></i></small>&nbsp;Select
</a></td>
			<td><?php echo $a->getEmployeeCode();?></td>
	 		<td><?php echo $a->getEmployeeName();?></td>
	 		<!-- <td>
<?php // echo  ($a->getBirthday()!== null)? date_format($a->getBirthday(),"d-m-Y"):""?>
	 		</td>
	 		 -->
	 		 <td>
<a target="blank" href="<?php echo $this->baseUrl ?>/hr/employee/show?token=<?php echo $this->escapeHtml($a->getToken());?>&checksum=<?php echo $a->getChecksum();?>&entity_id=<?php echo $this->escapeHtml($a->getID());?>">Show</a>&nbsp;
<small><i class="glyphicon glyphicon-new-window"> </i></small>
	 		</td>
		</tr>
<?php endforeach; ?>

 </tbody>
</table>

<?php
	
	// ===============================
	if (! is_null ( $paginator )) :
		
		// change it only
		$base = $this->baseUrl . '/application/uom/list';
		$_connector_symbol = '?';
		
		$last = $base . $_connector_symbol . 'page=' . $paginator->totalPages . '&perPage=' . $paginator->resultsPerPage;
		$first = $base . $_connector_symbol . 'page=1&perPage=' . $paginator->resultsPerPage;
		
		$p1 = ($paginator->page) - 1;
		$p2 = ($paginator->page) + 1;
		
		$prev = $base . $_connector_symbol . 'page=' . $p1 . '&perPage=' . $paginator->resultsPerPage;
		$next = $base . $_connector_symbol . 'page=' . $p2 . '&perPage=' . $paginator->resultsPerPage;
		
		echo '<ul class="pagination pagination-sm">';
		
		if ($paginator->page != 1 and $paginator->totalPages > 10) {
			echo '<li><a href="' . $first . '"> |< </a></li>';
			echo '<li><a href="' . $prev . '"> < </a></li>';
		}
		
		for($i = $paginator->minInPageSet; $i <= $paginator->maxInPageSet; $i ++) {
			
			$url = $base . $_connector_symbol . 'page=' . $i . '&perPage=' . $paginator->resultsPerPage;
			
			if ($i == $paginator->page) {
				echo '<li><a class="active" href="#">' . $i . '</a></li>';
			} else {
				echo '<li><a href="' . $url . '"> ' . $i . ' </a></li>';
			}
		}
		if ($paginator->page != $paginator->totalPages and $paginator->totalPages > 10) {
			echo '<li><a href="' . $next . '"> > </a></li>';
			echo '<li><a href="' . $last . '"> >| </a></li>';
		}
		echo '</ul>';
endif;
}
// ===============================
?>


