<h4><?php echo (!$entity == null)? "Employee: " . $entity->getEmployeeName() ." - ". $entity->getEmployeeCode():"";?></h4>

<div id="tabs" style="font-size: 9.5pt">
	<ul>
		<li><a href="#general">Personal</a></li>
		<li><a href="#cv">CV</a></li>
		<li><a href="#application">Application</a></li>
		<li><a
			href="/hr/employee-contract/list1?token=<?php echo (!$entity == null)? $entity->getToken():"";?>&target_id=<?php echo (!$entity == null)? $entity->getID():"";?>">Contract</a></li>
		<!-- <li><a href="#employment">Employment</a></li> -->
		<!-- <li><a href="#remuneration">Remuneration <small><iclass="glyphicon glyphicon-lock"> </i></small></a></li> -->
		<li><a
			href="/hr/employee-evaluation/list1?token=<?php echo (!$entity == null)? $entity->getToken():"";?>&target_id=<?php echo (!$entity == null)? $entity->getID():"";?>"><span
				class=""></span>&nbsp;Evaluation</a></li>
		</li>
		<li><a
			href="/hr/employee-leave/list1?token=<?php echo (!$entity == null)? $entity->getToken():"";?>&target_id=<?php echo (!$entity == null)? $entity->getID():"";?>"><span
				class=""></span>&nbsp;Leave</a></li>
		</li>
		<li><a
			href="/hr/employee-ot/list1?token=<?php echo (!$entity == null)? $entity->getToken():"";?>&target_id=<?php echo (!$entity == null)? $entity->getID():"";?>"><span
				class=""></span>&nbsp;Overtime</a></li>
		</li>
		<li><a
			href="/hr/employee-warning/list1?token=<?php echo (!$entity == null)? $entity->getToken():"";?>&target_id=<?php echo (!$entity == null)? $entity->getID():"";?>"><span
				class=""></span>&nbsp;<?php echo $this->translate('Disciplinary'); ?></a></li>
		</li>
		<!-- 
		<li><a
			href="/hr/employee-attachment/get-pictures?token=<?php echo (!$entity == null)? $entity->getToken():"";?>&checksum=<?php echo (!$entity == null)? $entity->getChecksum():"";?>&target_id=<?php echo (!$entity == null)? $entity->getID():"";?>"><span
				class="glyphicon glyphicon-picture"></span>&nbsp;Picture</a></li>
		 -->
		<li><a
			href="/hr/employee-attachment/list1?token=<?php echo (!$entity == null)? $entity->getToken():"";?>&checksum=<?php echo (!$entity == null)? $entity->getChecksum():"";?>&target_id=<?php echo (!$entity == null)? $entity->getID():"";?>"><span
				class="glyphicon glyphicon-paperclip"></span>&nbsp;Attachment</a></li>
		<li><a
			href="/inventory/item-assignment/to-employee?token=<?php echo (!$entity == null)? $entity->getToken():"";?>&target_id=<?php echo (!$entity == null)? $entity->getID():"";?>"><span
				class="glyphicon glyphicon-paperclip"></span>&nbsp;Asset</a></li>
		<li><a
			href="/hr/payroll-input/list1?period_id=2&token=<?php echo (!$entity == null)? $entity->getToken():"";?>&target_id=<?php echo (!$entity == null)? $entity->getID():"";?>">
				<i class="fa fa-calculator" aria-hidden="true"></i>&nbsp;Caculation
		</a></li>
		<li><a
			href="/hr/entity-change-log/list1?object_token=<?php echo (!$entity == null)? $entity->getToken():"";?>&object_id=<?php echo (!$entity == null)? $entity->getID():"";?>&class_name=<?php echo (!$entity == null)? get_class($entity):"";?>"><span
				class="glyphicon glyphicon-list"></span>&nbsp;Log</a></li>

	</ul>

	<div id="application" style="font-size: 9pt">
		<form id="application_form" class="form-horizontal" action=""
			method="post" enctype="multipart/form-data">
			<input type="hidden" name="redirectUrl"
				value="<?php echo $redirectUrl ?>" />

			<fieldset>
				<legend style="font-size: 9pt; color: gray;">
					<small><span class="glyphicon glyphicon-triangle-right"></span></small>&nbsp;
					<a href="#application_for" class="" data-toggle="collapse">APPLICATION:</a>
				</legend>
				<div id="application_for" class="collapse in">
					<div class="form-group margin-bottom">
						<label class="control-label col-sm-2">Application For</label>
						<div class="col-sm-3">
							<input class="form-control input-sm" type="text" placeholder=""
								name="employeeCode" value="Finance Manager">
						</div>
						<label class="control-label col-sm-2">Application submited on:</label>
						<div class="col-sm-3">
							<input class="form-control input-sm" type="text" placeholder=""
								name="employeeCode" value="01-06-2017">
						</div>
					</div>

				</div>
			</fieldset>
			<fieldset>
				<legend style="font-size: 9pt; color: gray;">
					<small><span class="glyphicon glyphicon-triangle-right"></span></small>&nbsp;
					<a href="#application_ref" class="" data-toggle="collapse">REFFERENCE:</a>
				</legend>
				<div id="application_ref" class="collapse in">
					<div class="form-group margin-bottom">
						<label class="control-label col-sm-2">Reference: </label>
						<div class="col-sm-3">
							<input class="form-control input-sm" type="text" placeholder=""
								name="employeeCode" value="New Paper /Facebook">
						</div>
						<label class="control-label col-sm-2">Recuirment Campain:</label>
						<div class="col-sm-3">
							<input class="form-control input-sm" type="text" placeholder=""
								name="employeeCode" value="Radio 03/2017">
						</div>
					</div>
					<div class="form-group margin-bottom">
						<label class="control-label col-sm-2">Bring-In Friend</label>
						<div class="col-sm-3">
							<input class="form-control input-sm" type="text" placeholder=""
								name="employeeCode" value="YES">
						</div>

					</div>



				</div>
			</fieldset>

		</form>
	</div>

	<!-- GENERRA -->
	<div id="general" style="font-size: 9pt">

		<form id="employee_show_form" class="form-horizontal" action=""
			method="post" enctype="multipart/form-data">
			<input type="hidden" name="redirectUrl"
				value="<?php echo $redirectUrl ?>" />

			<fieldset>

				<legend style="font-size: 9pt; color: gray;">
					<small><span class="glyphicon glyphicon-triangle-right"></span></small>&nbsp;
					<a href="#general_info" class="" data-toggle="collapse">GENERAL:</a>
				</legend>
				<div id="general_info" class="collapse in"
					style="padding: 0px; margin: 0">


					<div class="form-group margin-bottom">
						<label class="control-label col-sm-2">First Name - Local</label>
						<div class="col-sm-3">
							<input class="form-control input-sm" type="text" placeholder=""
								id="employeeName" name="employeeName"
								value="<?php echo (!$entity == null)? $entity->getEmployeeName():"";?>">
						</div>

						<label class="control-label col-sm-2">Last Name - Local:</label>
						<div class="col-sm-3">
							<input class="form-control input-sm" type="text" placeholder=""
								id="employeeName" name="employeeNameLocal"
								value="<?php echo (!$entity == null)? $entity->getEmployeeNameLocal():"";?>">
						</div>
					</div>

					<div class="form-group margin-bottom">
						<label class="control-label col-sm-2">First Name - EN</label>
						<div class="col-sm-3">
							<input class="form-control input-sm" type="text" placeholder=""
								id="employeeName" name="employeeName"
								value="<?php echo (!$entity == null)? $entity->getEmployeeName():"";?>">
						</div>

						<label class="control-label col-sm-2">Last Name - EN:</label>
						<div class="col-sm-3">
							<input class="form-control input-sm" type="text" placeholder=""
								id="employeeName" name="employeeNameLocal"
								value="<?php echo (!$entity == null)? $entity->getEmployeeNameLocal():"";?>">
						</div>
					</div>


					<div class="form-group margin-bottom">
						<label class="control-label col-sm-2">Birthday</label>
						<div class="col-sm-3">
							<input class="form-control input-sm" type="text" name="birthday"
								value="<?php if(!$entity == null): echo ($entity->getBirthday() !== null)? date_format($entity->getBirthday(),"Y-m-d"):""; endif;?>"
								placeholder=" please select" id="birthday" />
						</div>

						<label class="control-label col-sm-2" for="inputTag">Gender</label>
						<div class="col-sm-3">
							<select class="form-control input-sm" name="gender">
								<option value="">Please select</option>
								<option
									<?php if(!$entity == null):	echo ($entity->getGender()=='M')?'selected="selected"':''; endif;?>
									value="M">Male</option>
								<option
									<?php if(!$entity == null):	echo ($entity->getGender()=='F')?'selected="selected"':''; endif;?>
									value="F">Female</option>
							</select>
						</div>
					</div>

					<div class="form-group margin-bottom">
						<label class="control-label col-sm-2">Birth Country</label>
						<div class="col-sm-3">
							<input class="form-control input-sm" type="text" placeholder=""
								id="employeeName" name="employeeName" value="Vietnam">
						</div>

						<label class="control-label col-sm-2">Nationality:</label>
						<div class="col-sm-3">
							<input class="form-control input-sm" type="text" placeholder=""
								id="employeeName" name="employeeNameLocal" value="Vietnamese">
						</div>
					</div>

					<div class="form-group margin-bottom">
						<label class="control-label col-sm-2">Minority</label>
						<div class="col-sm-3">
							<input class="form-control input-sm" type="text" placeholder=""
								id="employeeName" name="employeeName" value="Mong">
						</div>

						<label class="control-label col-sm-2">Marital Status:</label>
						<div class="col-sm-3">
							<input class="form-control input-sm" type="text" placeholder=""
								id="employeeName" name="employeeNameLocal" value="married">
						</div>
					</div>


				</div>
			</fieldset>

			<fieldset>
				<legend style="font-size: 9pt; color: gray;">
					<small><span class="glyphicon glyphicon-triangle-right"></span></small>&nbsp;
					<a href="#address" class="" data-toggle="collapse">ADDRESS:</a>
				</legend>
				<div id="address" class="collapse">
					<div class="form-group margin-bottom">
						<label class="control-label col-sm-2">Address</label>
						<div class="col-sm-3">
							<input class="form-control input-sm" type="text" placeholder=""
								id="employeeName" name="employeeName" value="Donpalan">
						</div>
						<label class="control-label col-sm-2">Distance to Factory:</label>
						<div class="col-sm-3">
							<input class="form-control input-sm" type="text" placeholder=""
								id="employeeName" name="employeeName" value="10km">
						</div>

					</div>

					<div class="form-group margin-bottom">
						<label class="control-label col-sm-2">Country:</label>
						<div class="col-sm-3">
							<input class="form-control input-sm" type="text" placeholder=""
								id="employeeName" name="employeeNameLocal" value="Laos"> <a
								target="blank" style="font-size: 9pt; color: navy;" href="#"><small><i
									class="glyphicon glyphicon-plus"></i></small> New
								Address&nbsp;&nbsp;</a>
						</div>

					</div>
				</div>
			</fieldset>

			<fieldset>
				<legend style="font-size: 9pt; color: gray;">
					<small><span class="glyphicon glyphicon-triangle-right"></span></small>&nbsp;
					<a href="#contract_info" class="" data-toggle="collapse">CONTACT:</a>
				</legend>
				<div id="contract_info" class="collapse">
					<div class="form-group margin-bottom">
						<label class="control-label col-sm-2">Mobile phone:</label>
						<div class="col-sm-3">
							<input class="form-control input-sm" type="text" placeholder=""
								id="employeeName" name="employeeName" value="Donpalan">
						</div>
						<label class="control-label col-sm-2">Fixed Line Phone:</label>
						<div class="col-sm-3">
							<input class="form-control input-sm" type="text" placeholder=""
								id="employeeName" name="employeeName" value="Donpalan">
						</div>
					</div>
					<div class="form-group margin-bottom">
						<label class="control-label col-sm-2">Email1:</label>
						<div class="col-sm-3">
							<input class="form-control input-sm" type="text" placeholder=""
								id="employeeName" name="employeeName" value="Donpalan">
						</div>
						<label class="control-label col-sm-2">Email2:</label>
						<div class="col-sm-3">
							<input class="form-control input-sm" type="text" placeholder=""
								id="employeeName" name="employeeName" value="Donpalan">
						</div>
					</div>
					<div class="form-group margin-bottom">
						<label class="control-label col-sm-2">Relatives (For urgent
							cases):</label>
						<div class="col-sm-3">
							<input class="form-control input-sm" type="text" placeholder=""
								id="employeeName" name="employeeName" value="CHone"> <a
								target="blank" style="font-size: 9pt; color: navy;" href="#"><small><i
									class="glyphicon glyphicon-plus"></i></small> New
								Contract&nbsp;&nbsp;</a>
						</div>
						<label class="control-label col-sm-2">Telephone:</label>
						<div class="col-sm-3">
							<input class="form-control input-sm" type="text" placeholder=""
								id="employeeName" name="employeeName" value="123456">
						</div>
					</div>
				</div>
			</fieldset>

			<fieldset>
				<legend style="font-size: 9pt; color: gray;">
					<small><span class="glyphicon glyphicon-triangle-right"></span></small>&nbsp;
					<a href="#personal_id" class="" data-toggle="collapse">PERSONAL ID:</a>
				</legend>
				<div id="personal_id" class="collapse">
					<div class="form-group margin-bottom">
						<label class="control-label col-sm-2">Family Book No:</label>
						<div class="col-sm-3">
							<input class="form-control input-sm" type="text" placeholder=""
								id="employeeName" name="employeeName" value="12">
						</div>
					</div>
					<div class="form-group margin-bottom">
						<label class="control-label col-sm-2">Peronsal ID:</label>
						<div class="col-sm-3">
							<input class="form-control input-sm" type="text" placeholder=""
								id="employeeName" name="employeeName" value="12345">
						</div>
					</div>
					<div class="form-group margin-bottom">
						<label class="control-label col-sm-2">Issue Date:</label>
						<div class="col-sm-3">
							<input class="form-control input-sm" type="text" placeholder=""
								id="employeeName" name="employeeName" value="">
						</div>
						<label class="control-label col-sm-2">Expired Date:</label>
						<div class="col-sm-3">
							<input class="form-control input-sm" type="text" placeholder=""
								id="employeeName" name="employeeName" value=""> <input checked
								type="checkbox" name="isActive" value="1">&nbsp;Reminder one
							month before&nbsp;&nbsp;

						</div>
					</div>
					<hr>
					<div class="form-group margin-bottom">
						<label class="control-label col-sm-2">SS0 No.:</label>
						<div class="col-sm-3">
							<input class="form-control input-sm" type="text" placeholder=""
								id="employeeName" name="employeeName" value="12">
						</div>
						<label class="control-label col-sm-2">SSO registered on:</label>
						<div class="col-sm-3">
							<input class="form-control input-sm" type="text" placeholder=""
								id="employeeName" name="employeeName" value="12">
						</div>
					</div>

					<hr>
					<div class="form-group margin-bottom">
						<label class="control-label col-sm-2">Passpord No.:</label>
						<div class="col-sm-3">
							<input class="form-control input-sm" type="text" placeholder=""
								id="employeeName" name="employeeName" value="12">
						</div>
						<label class="control-label col-sm-2">Issue Place:</label>
						<div class="col-sm-3">
							<input class="form-control input-sm" type="text" placeholder=""
								id="employeeName" name="employeeName" value="12">
						</div>
					</div>
					<div class="form-group margin-bottom">
						<label class="control-label col-sm-2">Issue Date:</label>
						<div class="col-sm-3">
							<input class="form-control input-sm" type="text" placeholder=""
								id="employeeName" name="employeeName" value="">
						</div>
						<label class="control-label col-sm-2">Expired Date:</label>
						<div class="col-sm-3">
							<input class="form-control input-sm" type="text" placeholder=""
								id="employeeName" name="employeeName" value=""> <input checked
								type="checkbox" name="isActive" value="1">&nbsp;Reminder one
							month before&nbsp;&nbsp;

						</div>
					</div>


					<hr>
					<div class="form-group margin-bottom">
						<label class="control-label col-sm-2">Work Permit:</label>
						<div class="col-sm-3">
							<input class="form-control input-sm" type="text" placeholder=""
								id="employeeName" name="employeeName" value="12">

						</div>
						<label class="control-label col-sm-2">Issue Place:</label>
						<div class="col-sm-3">
							<input class="form-control input-sm" type="text" placeholder=""
								id="employeeName" name="employeeName" value="12">
						</div>
					</div>
					<div class="form-group margin-bottom">
						<label class="control-label col-sm-2">Issue Date:</label>
						<div class="col-sm-3">
							<input class="form-control input-sm" type="text" placeholder=""
								id="employeeName" name="employeeName" value="">
						</div>
						<label class="control-label col-sm-2">Expired Date:</label>
						<div class="col-sm-3">
							<input class="form-control input-sm" type="text" placeholder=""
								id="employeeName" name="employeeName" value=""> <input checked
								type="checkbox" name="isActive" value="1">&nbsp;Reminder one
							month before&nbsp;&nbsp;

						</div>
					</div>

				</div>
			</fieldset>

			<fieldset>
				<legend style="font-size: 9pt; color: gray;">
					<small><span class="glyphicon glyphicon-triangle-right"></span></small>&nbsp;
					<a href="#general_note" class="" data-toggle="collapse">REMARKS:</a>
				</legend>
				<div id="general_note" class="collapse">
					<div class="form-group margin-bottom">

						<label class="control-label col-sm-2">Remarks</label>
						<div class="col-sm-3">
							<textarea class="form-control input-sm" type="text" rows="4"
								placeholder="" name="remarks" style="font-size: 9pt;"><?php echo (!$entity == null)? $entity->getRemarks():"";?></textarea>
						</div>
					</div>

					<div class="form-group margin-bottom">
						<label class="control-label col-sm-2" for="inputTag"></label>
						<div class="col-sm-3">
							<a class="btn btn-default"
								href="<?php echo $this->baseUrl ?>/hr/employee/edit?token=<?php echo (!$entity == null)? $entity->getToken():"";?>&entity_id=<?php echo (!$entity == null)? $entity->getId():"";?>&checksum=<?php echo (!$entity == null)? $entity->getChecksum():"";?>"><small><i
									class="glyphicon glyphicon-pencil"></i></small>&nbsp;Edit</a>

						</div>
					</div>
				</div>
			</fieldset>

		</form>

	</div>
	<!-- GENERRAL END -->




	<!-- CV-->
	<div id="cv">
		<form id="cv_form" class="form-horizontal" action="" method="post"
			enctype="multipart/form-data">
			<fieldset>
				<legend style="font-size: 9pt; color: gray;">
					<small><span class="glyphicon glyphicon-triangle-right"></span></small>&nbsp;
					<a href="#language" class="" data-toggle="collapse">LANGUAGE:</a>
				</legend>
				<div id="language" class="collapse in">
					<div class="form-group margin-bottom">

						<label class="control-label col-sm-1"></label>
						<div class="col-sm-3">
							<input class="form-control input-sm" type="text"
								value="Laos, Thai, English, German" id="resigntDate" />
							<div style="color: navy; margin-bottom: 10pt;">
								<a target="blank" style="font-size: 9pt; color: navy;" href="#"><small><i
										class="glyphicon glyphicon-plus"></i></small> New
									Line&nbsp;&nbsp;</a>
							</div>
						</div>
					</div>

				</div>
			</fieldset>
			<fieldset>
				<legend style="font-size: 9pt; color: gray;">
					<small><span class="glyphicon glyphicon-triangle-right"></span></small>&nbsp;
					<a href="#skill" class="" data-toggle="collapse">SKILL:</a>
				</legend>
				<div id="skill" class="collapse in">
					<div class="form-group margin-bottom">

						<label class="control-label col-sm-1"></label>
						<div class="col-sm-3">
							<input class="form-control input-sm" type="text"
								value="sewing, cutting, PC" id="resigntDate" />
							<div style="color: navy; margin-bottom: 10pt;">
								<a target="blank" style="font-size: 9pt; color: navy;" href="#"><small><i
										class="glyphicon glyphicon-plus"></i></small> New
									Line&nbsp;&nbsp;</a>
							</div>
						</div>
					</div>

				</div>
			</fieldset>
			<fieldset>
				<legend style="font-size: 9pt; color: gray;">
					<small><span class="glyphicon glyphicon-triangle-right"></span></small>&nbsp;
					<a href="#education" class="" data-toggle="collapse">EDUCATION:</a>
				</legend>
				<div id="education" class="collapse in">
					<div class="form-group margin-bottom">
						<label class="control-label col-sm-1"></label>
						<div class="col-sm-9">
							<table style="font-size: 10pt;"
								class="table table-bordered table-hover">
								<thead>
									<tr>
										<td><b>#</b></td>
										<td><b>From Date</b></td>
										<td><b>To Date</b></td>
										<td><b>action</b></td>
									</tr>
								</thead>
								<tbody>
									<tr>
										<td>1</td>
										<td>01-05-2000</td>
										<td>31-05-2000</td>
										<td>University of Laos</td>
										<td>attach</td>

									</tr>
									<tr>
										<td>2</td>
										<td>01-05-2000</td>
										<td>31-05-2000</td>
										<td>University of vietnam</td>
										<td>attach</td>


									</tr>
								</tbody>
							</table>
							<div style="color: navy; margin-bottom: 10pt;">
								<a target="blank" style="font-size: 9pt; color: navy;" href="#"><small><i
										class="glyphicon glyphicon-plus"></i></small> New
									Line&nbsp;&nbsp;</a>
							</div>
						</div>
					</div>
			
			</fieldset>
			<fieldset>
				<legend style="font-size: 9pt; color: gray;">
					<small><span class="glyphicon glyphicon-triangle-right"></span></small>&nbsp;
					<a href="#experience" class="" data-toggle="collapse">EXPERIENCES:</a>
				</legend>
				<div id="experience" class="collapse in">
					<div class="form-group margin-bottom">
						<label class="control-label col-sm-1"></label>
						<div class="col-sm-9">
							<table style="font-size: 10pt;"
								class="table table-bordered table-hover">
								<thead>
									<tr>
										<td><b>#</b></td>
										<td><b>From Date</b></td>
										<td><b>To Date</b></td>
										<td><b>action</b></td>
									</tr>
								</thead>
								<tbody>
									<tr>
										<td>1</td>
										<td>01-05-2000</td>
										<td>31-05-2000</td>
										<td>Chief Account at ML</td>
										<td>attach</td>

									</tr>
									<tr>
										<td>2</td>
										<td>01-05-2000</td>
										<td>31-05-2000</td>
										<td>University of vietnam</td>
										<td>attach</td>


									</tr>
								</tbody>
							</table>
							<div style="color: navy; margin-bottom: 10pt;">
								<a target="blank" style="font-size: 9pt; color: navy;" href="#"><small><i
										class="glyphicon glyphicon-plus"></i></small> New
									Line&nbsp;&nbsp;</a>
							</div>
						</div>
					</div>
			
			</fieldset>
		</form>
	</div>
	<!-- EDU -->



</div>
<script>

$("#employee_show_form :input").attr("disabled", "disabled");
$( "input[id='startDate']").datepicker({ firstDay: 1, dateFormat: 'yy-mm-dd',closeText: 'X',changeMonth: true, changeYear: true});
$( "input[id='reStartDate']").datepicker({ firstDay: 1, dateFormat: 'yy-mm-dd',closeText: 'X',changeMonth: true, changeYear: true});

$( "input[id='contractValidFrom']").datepicker({ firstDay: 1, dateFormat: 'yy-mm-dd',closeText: 'X',changeMonth: true, changeYear: true});
$( "input[id='contractValidTo']").datepicker({ firstDay: 1, dateFormat: 'yy-mm-dd',closeText: 'X',changeMonth: true, changeYear: true});

</script>

