<h4><?php echo (!$entity == null)? "Employee: " . $entity->getEmployeeName():"";?></h4>

<div id="tabs" style="font-size: 9.5pt"> 
  <ul>
  <li ><a href="#general">Employee</a></li>
   <li ><a href="/hr/employee-attachment/get-pictures?token=<?php echo (!$entity == null)? $entity->getToken():"";?>&checksum=<?php echo (!$entity == null)? $entity->getChecksum():"";?>&target_id=<?php echo (!$entity == null)? $entity->getID():"";?>">Picture</a></li>
   <li ><a href="/hr/employee-attachment/list1?token=<?php echo (!$entity == null)? $entity->getToken():"";?>&checksum=<?php echo (!$entity == null)? $entity->getChecksum():"";?>&target_id=<?php echo (!$entity == null)? $entity->getID():"";?>">Attachment</a></li>
  </ul>

<div id="general"> 

<form id="employee_show_form" class="form-horizontal" action="" method="post" enctype="multipart/form-data">
<input type="hidden" name="redirectUrl" value="<?php echo $redirectUrl ?>" />

	<div class="form-group">
		<label class="control-label col-sm-2" >Employee Code</label>
		<div class="col-sm-3">
			<input class="form-control" type="text"  placeholder=""
				name="employeeCode" value="<?php echo (!$entity == null)? $entity->getEmployeeCode():"";?>">
		</div>		
	</div>
	
	<div class="form-group">
		<label class="control-label col-sm-2" >Employee Name</label>
		<div class="col-sm-3">
			<input class="form-control" type="text"  placeholder=""
				id = "employeeName" name="employeeName" value="<?php echo (!$entity == null)? $entity->getEmployeeName():"";?>">
		</div>
		
		<label class="control-label col-sm-2" >Employee Name Local:</label>
		<div class="col-sm-3">
			<input class="form-control" type="text"  placeholder=""
				id = "employeeName" name="employeeNameLocal" value="<?php echo (!$entity == null)? $entity->getEmployeeNameLocal():"";?>">
		</div>
	</div>
	

	<div class="form-group">
		<label class="control-label col-sm-2" >Birthday</label>
		<div class="col-sm-3">
		<input class="form-control" type="text" name="birthday" 
		value="<?php if(!$entity == null): echo ($entity->getBirthday() !== null)? date_format($entity->getBirthday(),"Y-m-d"):""; endif;?>" placeholder =" please select" id="birthday" />
		</div>
		
		<label class="control-label col-sm-2" for="inputTag">Gender</label>
		<div class="col-sm-3">
			<select class="form-control" name="gender">
				<option value="">Please select</option>
				<option <?php if(!$entity == null):	echo ($entity->getGender()=='M')?'selected="selected"':''; endif;?> value="M">Male</option>
				<option <?php if(!$entity == null):	echo ($entity->getGender()=='F')?'selected="selected"':''; endif;?> value="F">Female</option>
			</select>
		</div>
		
		
	</div>
	
	<div class="form-group">
		
		<label class="control-label col-sm-2" >Remarks</label>
		<div class="col-sm-3">
			<textarea  class="form-control" type="text" rows="4" placeholder=""
				name="remarks" style="font-size: 9pt;"><?php echo (!$entity == null)? $entity->getRemarks():"";?></textarea>
		</div>
	</div>
	
		<div class="form-group">
		<label class="control-label col-sm-2" for="inputTag"></label>
		<div class="col-sm-3">
 <a class="btn btn-default" href="<?php echo $this->baseUrl ?>/hr/employee/edit?token=<?php echo (!$entity == null)? $entity->getToken():"";?>&entity_id=<?php echo (!$entity == null)? $entity->getId():"";?>&checksum=<?php echo (!$entity == null)? $entity->getChecksum():"";?>"><small><i class="glyphicon glyphicon-pencil"></i></small>&nbsp;Edit</a>
 
  		</div>
	</div> 
	
</form>
</div>
</div>

<script>

$("#employee_show_form :input").attr("disabled", "disabled");

</script>

