
<?php
use Application\Application\Helper\ErrorMessage;
use Application\Domain\Company\AccountChart\GenericChart;
use Application\Form\AccountChart\ChartFormRender;
use Application\Form\Contracts\GenericForm;

/**
 *
 * @var GenericForm $form ;
 *
 * @var GenericChart $rootEntity ;
 */
$error_msg = ErrorMessage::showErrorMessage($errors);
$rootId = null;
if ($rootEntity !== null) {
    $rootId = $rootEntity->getId();
}

?>
<div id="tabs" style="font-size: 9.5pt">
   <ul>
      <li>
         <a href="#general">Create New Chart of Account</a>
      </li>
   </ul>
   <div id="general">
        <?php
        // ==================
        echo $error_msg;
        echo $form->renderForView($this, new ChartFormRender());
        ?>


  <a style="color: #0080ff;" href="javascript:;" onclick="$('#html1').jstree('open_all');">Expand all </a>
      &nbsp;|&nbsp;
      <a style="color: #0080ff;" href="javascript:;" onclick="$('#html1').jstree('close_all');">Collapse all </a>
      <div style="font-size: 10pt" id="html1" class="demo">
         <a style="color: #0080ff;" href="javascript:;" onclick="$('#html1').jstree('open_all');">Expand all </a>
         &nbsp;|&nbsp;
         <a style="color: #0080ff;" href="javascript:;" onclick="$('#html1').jstree('close_all');">Collapse all </a>
         <ul>
   <?php
echo $jsTree?>;
</ul>
      </div>
   </div>
</div>
<div class="modal" id="confirm_remove_node" role="dialog">
   <div class="modal-dialog modal-md">
      <div class="modal-content">
         <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal">&times;</button>
         </div>
         <div class="modal-body" id="b_modal_sm_body">
            <h5>#<?php

            echo $this->translate('Account will be removed!');
            ?></h5>
            <div class="alert alert-warning">
               <strong>[Info]</strong> <?php

            echo $this->translate('Remove can not be recalled!');
            ?>
               <!-- Journal Entry will be created. <br>- Warehouse Journal will be
               created.
                -->
            </div>
            <p><?php

            echo $this->translate('Do you want to continue?');
            ?></p>
         </div>
         <div class="modal-footer">
            <button onclick="doRemovingNode();" type="button" class="btn btn-primary btn-sm">YES</button>
            <button type="button" class="btn btn-default btn-sm" data-dismiss="modal">Cancel</button>
         </div>
      </div>
   </div>
</div>
<script>

<?php
echo sprintf("var rootId=%s;", $rootId);
echo sprintf("var redirectUrl = \"/application/account-chart/view?id=%s\"", $rootId);
?>;

$( "input[id='validFrom']").datepicker({ firstDay: 1, dateFormat: 'yy-mm-dd',closeText: 'X',changeMonth: true, changeYear: true});
$( "input[id='validTo']").datepicker({ firstDay: 1, dateFormat: 'yy-mm-dd',closeText: 'X',changeMonth: true, changeYear: true});

var node_to_remove = null;

function confirmRemoveNode() {
    $('#confirm_remove_node').modal();
 }

function doRemovingNode() {

    $('#confirm_remove_node').hide();

  //alert(data.node.parent +  data.node.id  +  data.node.text );
    $('#b_modal_no_header').modal();

    //alert(node_to_remove + rootId);

     $.post("/application/account-chart/remove-member", {
        rid : rootId,
        mid: node_to_remove

    }, function(data, status) {
       //alert(data);
       window.location = redirectUrl;
    });
}


//html demo
$('#html1').jstree({
   "core" : {
          // so that create works
          "check_callback" : true
        },
       "plugins" : [ "contextmenu","types"],

       "types" : {

	      "demo" : {
	        "icon" : "fa fa-book"
	      }
	    },

       "contextmenu":{
           "items": function($node) {
               var tree = $("#html1").jstree(true);
               return {

                      "Add Account": {
                          "separator_before": false,
                          "separator_after": false,
                          "label": "Add new account",
                          "title": "Add new account",
                          "icon": "fa fa-plus",
                          "action": function (obj) {
                           var redirectUrl = "/application/account-chart/add-member?rid=" +rootId+ "&pid="+ $node.id;
                           //alert(redirectUrl);
                           window.location = redirectUrl;
                         }
                      },

                      "Update Account": {
                          "separator_before": false,
                          "separator_after": false,
                          "label": "Update Account",
                          "title": "Update Account",
                          "icon": "fa fa-edit",
                          "separator_after": true,
                          "action": function (obj) {
                           var redirectUrl = "/application/account-chart/update-member?rid=" +rootId+ "&mid="+ $node.id
                           //alert(redirectUrl);
                           window.location = redirectUrl;
                         }
                      },


                     /*  'Move Account': {
                          "separator_before": false,
                          "separator_after": false,
                          "label": "Move Account",
                          "icon": "fa fa-bars",
                          "action": function (obj) {
                           var redirectUrl = "/application/account-chart/move?n="+$node.id;
                           window.location = redirectUrl;
                         }
                      }, */


                   /* "Create": {
                       "separator_before": false,
                       "separator_after": false,
                       "label": "Create New Deparment",
                       "action": function (obj) {
                        var ref = $.jstree.reference(obj.reference);
                        sel = ref.get_selected();
                       $node = tree.create_node($node);
                          tree.edit($node);
                       }
                   }, */

                   /* "Rename": {
                       "separator_before": false,
                       "separator_after": false,
                       "label": "Rename Account",
                       "icon": "fa fa-edit",

                       "action": function (obj) {
                           tree.edit($node);
                       }
                   }, */
                   "Remove": {
                       "separator_before": false,
                       "separator_after": false,
                       "label": "<span style=\"color:red\">Remove Account</span>",
                       "icon": "fa fa-remove",
                       "action": function (obj) {
                           tree.delete_node($node);
                       }
                   },



               };
           }
       }

});



// DELETE ===============
$('#html1').on('delete_node.jstree', function (e, data) {

     $('#confirm_remove_node').modal();
     //alert( data.node.id);
     node_to_remove = data.node.id;


});
// DELETE ===============


$("#html1").on("click", ".jstree-anchor", function(e) {
      var node = $("#html1").jstree(true).get_node($(this));

      var id = $("#html1").jstree(true).get_node($(this)).id;
      var cat_name = $("#html1").jstree(true).get_node($(this)).text;

      if (!node.state.disabled)
         {
      $("#node_selected").html('"' + cat_name + '" selected');
      $("#department_name").val(cat_name);
      $("#department_name_selected").val(id);

      $('#modal1 .close').click();
      $('#global-notice').show();
      $('#global-notice').html('"' + cat_name + '" selected');
      $('#global-notice').fadeOut(3000);
         }
});

</script>
