
<?php
use Application\Application\Helper\ErrorMessage;
use Application\Form\AccountChart\AccountFormRender;
use Application\Form\Contracts\GenericForm;

/**
 *
 * @var GenericForm $form ;
 *
 */
$error_msg = ErrorMessage::showErrorMessage($errors);
?>
<div id="tabs" style="font-size: 9.5pt">
   <ul>
      <li>
         <a href="#general">Create New Account</a>
      </li>
   </ul>
   <div id="general">

        <?php
        // ==================
        echo $error_msg;
        echo $form->renderForView($this, new AccountFormRender());
        ?>

   </div>
</div>
