
<div id="tabs" style="font-size: 9.5pt">
	<ul>
		<li><a href="#general"><?php
echo $this->translate('Account Chart');
?></li>
	</ul>

	<div id="general">
		<a class="btn btn-default btn-sm"
			href="<?php

echo $this->baseUrl?>/application/department/add"><small><i
				class="glyphicon glyphicon-plus"> </i></small>&nbsp;<?php

    echo $this->translate('Add Chart');
    ?></a>

		<hr>
		<div id="html" class="demo">

<?php

var_dump(get_class($chart));
?>
			<ul>

			</ul>
		</div>

	</div>
</div>

