    <?php /**@var \Application\Entity\NmtInventoryItem $a ; */ ?>

<div id="tabs" style="font-size: 9.5pt">

	<ul>
		<li><a href="#general">Contract /PO List:</a></li>
	</ul>
	<div id="general" style="padding: 10px 10px 1px 3px">



<?php
if ($total_records <= 0) :
    echo 'No record found!';
else :

    if (! is_null($paginator)) :
        echo 'Record ' . $paginator->getMinInPage() . ' to ' . $paginator->getMaxInPage() . ' | ' . $total_records . ' records found!';
    else :
        echo $total_records . ' records found!';
    endif;

    ?>

<table style="font-size: 9.3pt;"
			class="table table-bordered table-hover">
			<thead>
				<tr>
					<td><b>#</b></td>
					<td><b>Status</b></td>
					<td><b>Status</b></td>
				</tr>
			</thead>

			<tbody>
 
	 <?php

    $count = 0;
    foreach ($list as $l) :
        var_dump($l);
        $count ++;

        /**@var \Application\Entity\NmtInventoryItem $a ; */
        $a = $l[0];
        ?>
		
	<tr>
					<td>
				<?php echo $count;?>
			</td>
					<td><?php if($a!==null):echo get_class($a) .  $a->getId();endif;?></td>
					<td><?php echo $l['sn'];?></td>

				</tr>
	<?php endforeach; ?>
 </tbody>
		</table>

<?php endif;?>
