<form class="form-inline" action=""	method="get" enctype="multipart/form-data">
  <div class="form-group">
    	<input class="form-control" size="25" type="text" id ="search_term_<?php echo $context;?>" name = "query">
   </div>
  <div class="form-group">
     <button type="submit" class="btn btn-default" onclick="searchEntity('/bp/vendor-search/do1','<?php echo $context;?>');"><small><i class="glyphicon glyphicon-search"> </i></small> Search</button>
  </div>
  
</form>

<div>
<ul class="nav nav-pills">
		<li><a style="color: #0080ff;" href="/procurement/vendor/add"><i
				class="icon-plus"> </i>&nbsp;CREATE NEW VENDOR </a>
		
		<li><a style="color: #0080ff;" href="javascript:;"
			onclick="loadData1('/bp/vendor/list1','<?php echo $context;?>');"> <i class="icon-list"></i>&nbsp;ALL VENDORS
		</a>
		</ul>
</div>

<?php
echo '<span style = "font-size: 10pt;">';
echo $message;
echo '</span>';

if (! $hits == null) :
	?>
<table style = "font-size: 10pt;" class="table table-hover table-bordered">
	<thead>
		<tr style = "">
		    <td><b>#</b></td>
			<td><b>Select</b></td>
			<td><b>Vendor	</b></td>
			<td><b>Keywords</b></td>
			<td><b>Country</b></td>
			<td><b>Action</b></td>
		</tr>
		</tr>
	</thead>
	<tbody>

	 <?php
	
	$count = 0;
	foreach ( $hits as $hit ) :
		$count ++;
		// echo ($count % 2 == 1) ? "<tr>" : "<tr class=\"pure-table-odd\">";
		
		?>
	 <tr>
	
			<td> <?php echo $count;?></td>
	 		<td>		
<a href="javascript:;"
	onclick="selectId('<?php echo $this->escapeHtml($hit->vendor_id);?>','vendor_id','<?php echo $this->escapeJs($hit->vendor_name);?>','vendor_name');"><small><i class="glyphicon glyphicon-triangle-right"></i></small>&nbsp;Select
</a></td>
			<td><?php echo $this->escapeHtml($hit->vendor_name);?></td>
	 		<td><?php echo $this->escapeHtml($hit->keywords);?></td>
			<td><?php echo $this->escapeHtml($hit->country_name);?></td>
		
	<td>
	<a href="<?php echo $this->baseUrl ?>/bp/vendor/show?token=<?php echo $hit->token;?>&entity_id=<?php echo $hit->vendor_id;?>&checksum=<?php echo $hit->checksum;?>">Show</a>
	</td>	
		</tr>
<?php endforeach; ?>
</tbody>
</table>


<?php endif; ?>
