
<div id="tabs" style="font-size: 9.5pt">
   <ul>
      <li>
         <a href="#general"><?php
        echo $this->translate('Procure Reporting');
        ?></a>
      </li>
   </ul>
   <div id="general" style="font-size: 9pt">
      <h3 style="color: gray; font-weight: bold;">Master Data:</h3>
      <div class="row">
         <div class="col-sm-4"">
            <div class="well well-sm ">
               <a style="color: navy" href="/inventory/item-report/default">
                  <i class="fa fa-book" aria-hidden="true"></i>
                  Item Master Data
               </a>
            </div>
         </div>
         <div class="col-sm-4"">
            <div class="well well-sm ">
               <a style="color: navy" href="/inventory/item-report/default">
                  <i class="fa fa-book" aria-hidden="true"></i>
                  Item Serial No.
               </a>
            </div>
         </div>
      </div>
      <div class="row">
         <div class="col-sm-4"">
            <div class="well well-sm ">
               <a style="color: navy" href="/inventory/item-report/default">
                  <i class="fa fa-book" aria-hidden="true"></i>
                  Minimum Stock Balance
               </a>
            </div>
         </div>
         <div class="col-sm-4"">
            <div class="well well-sm ">
               <a style="color: navy" href="/inventory/item-report/default">
                  <i class="fa fa-book" aria-hidden="true"></i>
                  Item HS Code
               </a>
            </div>
         </div>
      </div>
      <h3 style="color: gray; font-weight: bold;">Stock Movement:</h3>
      <div class="row">
         <div class="col-sm-4"">
            <div class="well well-sm">
               <a style="color: navy" href="/inventory/trx-report/row-status">
                  <i class="fa fa-list" aria-hidden="true"></i>
                  Warehouse Journal
               </a>
            </div>
         </div>
         <div class="col-sm-4"">
            <div class="well well-sm">
               <a style="color: navy" href="/inventory/item-report/in-out-onhand">
                  <i class="fa fa-industry" aria-hidden="true"></i>
                  In-Out-Onhand Report
               </a>
            </div>
         </div>
      </div>
      <div class="row">
         <div class="col-sm-4"">
            <div class="well well-sm">
               <a style="color: navy" href="/inventory/trx-report/row-status">
                  <i class="fa fa-pie-chart" aria-hidden="true"></i>
                  Item Issue by Machine
               </a>
            </div>
         </div>
         <div class="col-sm-4"">
            <div class="well well-sm">
               <a style="color: navy" href="/inventory/trx-report/row-status">
                  <i class="fa fa-pie-chart" aria-hidden="true"></i>
                  Item Issue by Mechanic
               </a>
            </div>
         </div>
      </div>
      <div class="row">
         <div class="col-sm-4"">
            <div class="well well-sm">
               <a style="color: navy" href="/inventory/trx-report/row-status">
                  <i class="fa fa-pie-chart" aria-hidden="true"></i>
                  Return PO Transactions
               </a>
            </div>
         </div>
      </div>
      <div class="row">
         <div class="col-sm-4"">
            <div class="well well-sm">
               <a style="color: navy" href="/inventory/trx-report/row-status">
                  <i class="fa fa-pie-chart" aria-hidden="true"></i>
                  Recycling Transactions
               </a>
            </div>
         </div>
         <div class="col-sm-4"">
            <div class="well well-sm">
               <a style="color: navy" href="/inventory/trx-report/row-status">
                  <i class="fa fa-pie-chart" aria-hidden="true"></i>
                  Scrapp Transaction
               </a>
            </div>
         </div>
      </div>
   </div>
</div>