
<div id="tabs" style="font-size: 9.5pt">
   <ul>
      <li>
         <a href="#general"><?php
        echo $this->translate('Procure Reporting');
        ?></a>
      </li>
   </ul>
   <div id="general" style="font-size: 9pt">
      <h3 style="color: gray; font-weight: bold;">Purchase Request:</h3>
      <div class="row">
         <div class="col-sm-4"">
            <div class="well well-sm ">
               <a style="color: navy" href="/procure/pr-report/row-status">
                  <i class="fa fa-book" aria-hidden="true"></i>
                  PR Row Status
               </a>
            </div>
         </div>
          <div class="col-sm-4"">
            <div class="well well-sm ">
               <a style="color: navy" href="/procure/pr-report/header-status">
                  <i class="fa fa-book" aria-hidden="true"></i>
                  PR Status
               </a>
            </div>
         </div>

      </div>
      <h3 style="color: gray; font-weight: bold;">Purchse Order:</h3>
      <div class="row">
         <div class="col-sm-4"">
            <div class="well well-sm">
               <a style="color: navy" href="/procure/po-report/row-status">
                  <i class="fa fa-list" aria-hidden="true"></i>
                  PO Row Status
               </a>
            </div>
         </div>

          <div class="col-sm-4"">
            <div class="well well-sm ">
               <a style="color: navy" href="/procure/po-report/header-status">
                  <i class="fa fa-book" aria-hidden="true"></i>
                  PO Status
               </a>
            </div>
         </div>

      </div>
      <div class="row">
         <div class="col-sm-4"">
            <div class="well well-sm">
               <a style="color: navy" href="/procure/po-report/po-ap-report">
                  <i class="fa fa-pie-chart" aria-hidden="true"></i>
                  PO AP Row
               </a>
            </div>
         </div>


      </div>
      <h3 style="color: gray; font-weight: bold;">AP:</h3>
      <div class="row">
         <div class="col-sm-4"">
            <div class="well well-sm">
               <a style="color: navy" href="/procure/ap-report/row-status">
                  <i class="fa fa-pie-chart" aria-hidden="true"></i>
                  AP Row Status
               </a>
            </div>
         </div>

          <div class="col-sm-4"">
            <div class="well well-sm ">
               <a style="color: navy" href="/procure/ap-report/header-status">
                  <i class="fa fa-book" aria-hidden="true"></i>
                  AP Status
               </a>
            </div>
         </div>

      </div>
   </div>
</div>
</div>