<?php

/**
 * @var \Application\Entity\NmtInventoryItem $target ;
 * @var \Application\Entity\NmtInventoryTrx $entity ;
 */
if (count($errors) > 0) {
    echo '<div class="alert alert-danger" role="alert" style="font-size: 10.5pt">';

    echo '<ul>';
    foreach ($errors as $error) :
        echo '<li>' . $error . '</li>';
    endforeach
    ;
    echo '</ul>';
    echo '</div>';
}
?>


<div id="tabs" style="font-size: 9.5pt">
	<ul>
		<li><a href="#general">Item Issue</a></li>
	</ul>

	<div id="general" style="font-size: 9pt">

		<form id="gr_form" class="form-horizontal"
			action="<?php echo $this->baseUrl ?>/inventory/item-transaction/gi"
			method="post" enctype="multipart/form-data">
			<input type="hidden" name="redirectUrl"
				value="<?php echo $redirectUrl ?>" /> <input type="hidden"
				id="target_wh_id" name="target_wh_id"
				value="<?php if (!$entity == null): if (!$entity->getWh() == null):echo $entity->getWh()->getId();endif;endif;?>" />

			<input type="hidden" id="target_id" placeholder="" name="target_id"
				value="<?php if(!$target == null): echo ($target->getId()); endif;?>">
			<input type="hidden" id="token" placeholder="" name="token"
				value="<?php if(!$target == null): echo ($target->getToken()); endif;?>">

			<div class="form-group margin-bottom required">
				<label class="control-label col-sm-2">Item: </label>
				<div class="col-sm-6">
					<input disabled class="form-control input-sm" type="text"
						id="item_name" placeholder="Select Item if any" name="item_name"
						value="<?php if(!$target == null): echo ($target->getItemName()); endif;?>">

					<input
						<?php if(!$entity == null): echo ($entity->getIsDraft()=="1")?"checked":""; else: echo ""; endif;?>
						type="checkbox" name="isDraft" value="1">&nbsp;Draft&nbsp;&nbsp; <input
						<?php if(!$entity == null): echo ($entity->getIsActive()=="1")?"checked":""; else: echo "checked"; endif;?>
						type="checkbox" name="isActive" value="1">&nbsp;Active&nbsp;&nbsp;
				</div>


				<div id="item_detail">
					&nbsp;&nbsp;<a title="Item Detail" href="javascript:;"
						onclick="showSelectedItem();"><i style="color: navy"
						class="fa fa-info-circle fa-lg" aria-hidden="true"></i></a> <br>&nbsp;
				</div>




			</div>

			<fieldset>
				<legend style="font-size: 9pt; color: gray;">
					<small><span class="glyphicon glyphicon-triangle-right"></span></small>&nbsp;
					<a style="font-size: 9pt; color: gray;" href="#transaction"
						class="" data-toggle="collapse">TRANSACTION:</a>
				</legend>
				<div id="transaction" class="collapse in">

					<div class="form-group margin-bottom required">
						<label class="control-label col-sm-2" for="inputTag">Transaction
							Date:</label>
						<div class="col-sm-3">
							<input class="form-control input-sm" type="text" name="trx_date"
								placeholder=" please select" id="trx_date"
								value="<?php if(!$entity == null): echo ($entity->getTrxDate() !== null)? date_format($entity->getTrxDate(),"Y-m-d"):""; endif;?>" />
						</div>

						<label class="control-label col-sm-2" for="inputTag"><?php echo $this->translate("Source Warehouse");?>:</label>
						<div class="col-sm-3">
							<input class="form-control input-sm" readonly type="text"
								id="target_wh_name" placeholder="Please select!"
								name="target_wh"
								value="<?php if (!$entity == null): if (!$entity->getWh() == null):echo $entity->getWh()->getWhName();endif;endif;?>">
						</div>
						<a style="color: #0080ff;" href="javascript:;"
							onclick="showJqueryDialog('Source Warehouse','700','500','/inventory/warehouse/list1?target_id=target_wh_id&target_name=target_wh_name','j_loaded_data',true);">Select&nbsp;&nbsp;<i
							class="glyphicon glyphicon-folder-open"></i>
						</a>
					</div>
					<div class="form-group margin-bottom required">
						<label class="control-label col-sm-2" for="inputTag">Quantity:</label>
						<div class="col-sm-3">
							<input class="form-control input-sm" type="text" name="quantity"
								value="<?php echo (!$entity == null)? $entity->getQuantity():"";?>">
						</div>
					</div>

					<div class="form-group margin-bottom required">
						<label class="control-label col-sm-2">Issue for: </label>
						<div class="col-sm-3">
							<input disabled class="form-control input-sm" type="text"
								id="issue_for_name" placeholder="Select Item if any"
								name="issue_for_name"
								value="<?php if(!$entity== null): if($entity->getIssueFor()!==null):echo $entity->getIssueFor()->getItemName(); endif;endif;?>">
							<input type="hidden" id="issue_for_id" placeholder=""
								name="issue_for_id"
								value="<?php if(!$entity== null): if($entity->getIssueFor()!==null):echo $entity->getIssueFor()->getId(); endif;endif;?>">
						</div>


						<a style="color: #0080ff;" href="javascript:;"
							onclick="showJqueryDialog('Select Item','950','500', '/inventory/item-search/do1?target_id=issue_for_id&target_name=issue_for_name','j_loaded_data', true);">Select&nbsp;&nbsp;<i
							class="glyphicon glyphicon-folder-open"></i>
						</a>

					</div>

		

					<div class="form-group margin-bottom">

						<label class="control-label col-sm-2">Remarks:</label>
						<div class="col-sm-4">
							<textarea class="form-control input-sm" type="text" rows="4"
								placeholder="" name="remarks" style="font-size: 9pt;"><?php echo (!$entity == null)? $entity->getRemarks():"";?></textarea>
						</div>
					</div>



				</div>
				</fieldset>
				
				<br>
				<div class="form-group margin-bottom">
					<label class="control-label col-sm-2" for="inputTag"></label>
					<div class="col-sm-3">
						<a class="btn btn-primary btn-sm" style="color: white"
							onclick="confirmPost();" href="javascript:;"><i
							class="fa fa-floppy-o" aria-hidden="true"></i> &nbsp;<?php echo $this->translate('Post');?></a>
					</div>
				</div>
			

		</form>
	</div>
</div>


<!-- Modal -->
<div class="modal" id="confirm_modal_sm" role="dialog">
	<div class="modal-dialog modal-md">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal">&times;</button>
			</div>
			<div class="modal-body" id="b_modal_sm_body">
				<h5>Good Issue <?php echo (!$entity == null)? $entity->getSysNumber() . $this->translate(' will be posted!'):"";?></h5>

				<div class="alert alert-warning">
					<strong>[Info]</strong> <?php echo $this->translate('Document can\'t be changed anymore when submitted!');?>
					<!-- Journal Entry will be created. <br>- Warehouse Journal will be
					created.
					 -->
				</div>
				<p><?php echo $this->translate('Do you want to continue?');?></p>
			</div>
			<div class="modal-footer">
				<button onclick="doPosting();" type="button"
					class="btn btn-primary btn-sm">YES</button>
				<button type="button" class="btn btn-default btn-sm"
					data-dismiss="modal">Cancel</button>
			</div>
		</div>
	</div>
</div>



<script type="text/javascript">


function confirmPost() {
 	$('#confirm_modal_sm').modal();
}

function doPosting() {
	$('#confirm_modal_sm').modal('hide');
	submitForm('gr_form');
}



$('#vendor_item_unit').bind('change', function() {
	//alert($('#vendor_item_unit').val());
	$('#conversion_text').html($('#vendor_item_unit').val() + ' = ' + $('#conversion_factor').val() );
});

$('#conversion_factor').bind('change', function() {
	//alert($('#vendor_item_unit').val());
	$('#conversion_text').html($('#vendor_item_unit').val() + ' = ' + $('#conversion_factor').val() );
});
$( "input[id='trx_date']").datepicker({ firstDay: 1, dateFormat: 'yy-mm-dd',closeText: 'X',changeMonth: true, changeYear: true});


function showSelectedItem(){
	var url= '/inventory/item/show1?tab_idx=7&entity_id=<?php echo $target->getId();?>&token=<?php echo $target->getToken();?>';
   	showJqueryDialog('Item Detail','1350',$(window).height()-40, url,'j_loaded_data', true);
}

</script>