<div id="form_process_status" class="alert alert-danger" role="alert" style="font-size: 9.5pt; display:none"></div>

<div id="general" style="font-size: 9.5pt; padding: 0px;">

	<form id="gr_form" class="form-horizontal"
		action="<?php echo $this->baseUrl ?>/inventory/item-transaction/gr1"
		method="post" enctype="multipart/form-data">
		<input type="hidden" name="redirectUrl"
			value="<?php echo $redirectUrl ?>" /> <input type="hidden"
			id="target_wh_id" name="target_wh_id"
			value="<?php if (!$entity == null): if (!$entity->getWh() == null):echo $entity->getWh()->getId();endif;endif;?>" />

		<div class="form-group required">
			<div class="col-sm-3">
				<input type="hidden" id="token" placeholder="" name="token" value="">
				<input type="hidden" id="checksum" placeholder="" name="checksum" value="">
			</div>
		</div>

		<div class="form-group">
			<label class="control-label col-sm-2">
<?php

if (! $entity == null) :
    if ($entity->getPrRow() !== null) :
         if ($entity->getPrRow()->getPr() !== null) :
            echo $entity->getPrRow()->getPr()->getPrNumber().":";
        endif;
    endif;
endif;
    

?>
			</label>
			<div class="col-sm-3">
				<input disabled class="form-control" type="text" id="pr_item_name"
					placeholder="Select PR Item, if any" name="pr_row_name"
					value="<?php
    
    if (! $entity == null) :
        if ($entity->getPrRow() !== null) :
            if ($entity->getPrRow()->getItem() !== null) :
                echo $entity->getPrRow()
                    ->getItem()
                    ->getItemName();
	endif;
endif;
endif;           
    ?>">


			</div>
			<div class="col-sm-4">
				<input
					<?php if(!$entity == null): echo ($entity->getIsDraft()=="1")?"checked":""; else: echo ""; endif;?>
					type="checkbox" name="isDraft" value="1">&nbsp;Draft&nbsp;&nbsp; <input
					type="checkbox"
					<?php
    if (! $entity == null) :
        echo ($entity->getIsActive() == "1") ? "checked" : "";
    else :
        echo "checked";
    endif;
    ?>
					name="isActive" value="1">&nbsp;Active&nbsp;&nbsp; <input
					type="hidden" id="pr_row_id" placeholder="" name="pr_row_id"
					value="<?php
    
    if (! $entity == null) :
        if ($entity->getPrRow() !== null) :
            echo $entity->getPrRow()->getId();
endif;
endif;
        
    
    ?>">

			</div>
		</div>

		<fieldset>
			<legend style="font-size: 9pt; color: gray;">
				<small><span class="glyphicon glyphicon-triangle-right"></span></small>&nbsp;
				<a href="#transactionID" class="" data-toggle="collapse">TRANSACTION:</a>
			</legend>
			<div id="transactionID" class="collapse in">

				<div class="form-group required">
					<label class="control-label col-sm-2" for="inputTag">Transaction
						Date:</label>
					<div class="col-sm-3">
						<input class="form-control" type="text" name="trx_date"
							placeholder="please select" id="trx_date"
							value="
<?php

if (! $entity == null) :
    if ($entity->getTrxDate() !== null) :
        date_format($entity->getTrxDate(), "Y-m-d"); 
endif;
endif;
    

?>
" />
					</div>

					<label class="control-label col-sm-2" for="inputTag">Target
						Warehouse:</label>
					<div class="col-sm-3">
						<input class="form-control" readonly type="text"
							id="target_wh_name" placeholder="Please select!" name="target_wh"
							value="<?php if (!$entity == null): if (!$entity->getWh() == null):echo $entity->getWh()->getWhName();endif;endif;?>">
					</div>
				</div>


				<div class="form-group required">
					<label class="control-label col-sm-2" for="inputTag">Quantity:</label>
					<div class="col-sm-3">
						<input class="form-control" type="text" name="quantity"
							value="<?php echo (!$entity == null)? $entity->getQuantity():"";?>">
					</div>
				</div>
			</div>
		</fieldset>
		<fieldset>
			<legend style="font-size: 9pt; color: gray;">
				<small><span class="glyphicon glyphicon-triangle-right"></span></small>&nbsp;
				<a href="#purchasing_dataID" class="" data-toggle="collapse">PURCHASING
					DATA:</a>
			</legend>
			<div id="purchasing_dataID" class="collapse in">
				<div class="form-group">
					<label class="control-label col-sm-2">Vendor:</label>
					<div class="col-sm-3">
						<input class="form-control" type="text" id="vendor_name_1"
							placeholder="Enter term to search vendor" name="vendor_name"
							value="<?php if (!$entity == null): if (!$entity->getVendor() == null):echo $entity->getVendor()->getVendorName();endif;endif;?>">
			
						<input type="hidden" id="vendor_id" placeholder=""
							name="vendor_id"
							value="<?php if (!$entity == null): if (!$entity->getVendor() == null):echo $entity->getVendor()->getId();endif;endif;?>">
					</div>
					<div class="col-sm-3">
					
						<input
							<?php if(!$entity== null): echo ($entity->getIsPreferredVendor()=="1")?"checked":""; else: echo "checked"; endif;?> type="checkbox" name="isPreferredVendor" value="1">&nbsp;Is
						Preferred&nbsp;&nbsp;&nbsp;&nbsp;

					</div>
					<div class="col-sm-3">
					
					<a target="blank" style="font-size: 9pt;" href="/bp/vendor/list">Vendor List&nbsp;&nbsp;</a><small><i class="glyphicon glyphicon-new-window"></i></small>
					</div>
				</div>

				<div class="form-group">
					<label class="control-label col-sm-2">Vendor's Item Code</label>
					<div class="col-sm-3">
						<input class="form-control" type="text" placeholder=""
							name="vendorItemCode"
							value="<?php echo (!$entity == null)? $entity->getVendorItemCode():"";?>">
					</div>
				</div>

				<div class="form-group">
					<label class="control-label col-sm-2">Vendor's Item Unit</label>
					<div class="col-sm-3">
						<input class="form-control" type="text" placeholder=""
							id="vendor_item_unit" name="vendorItemUnit"
							value="<?php echo (!$entity == null)? $entity->getVendorItemUnit():"";?>">
					</div>

					<label class="control-label col-sm-2">Conversion Factor:</label>
					<div class="col-sm-3">
						<input class="form-control" type="text" placeholder=""
							id="conversion_factor" name="conversionFactor"
							value="<?php if(!$entity == null): if($entity->getConversionFactor()!==null): echo number_format($entity->getConversionFactor(), 2); endif;endif;?>">

					</div>
					<span style="font-size: 9.5pt" id="conversion_text"></span> <span><?php if (!$target == null): if (!$target->getStandardUom() == null):echo $target->getStandardUom()->getUomCode();endif;endif;?></span>
				</div>


				<div class="form-group">
					<label class="control-label col-sm-2">Unit Price</label>
					<div class="col-sm-3">
						<input class="form-control" type="text" placeholder=""
							name="vendorUnitPrice"
							value="<?php if(!$entity == null): if($entity->getVendorUnitPrice()!==null): echo number_format($entity->getVendorUnitPrice(), 2); endif;endif;?>">
					</div>

					<label class="control-label col-sm-2">Currency:</label>
					<div class="col-sm-3">
					<select name="currency_id" class="form-control">
								<option value="">Select Currency</option>
   	    							<?php
   	    							foreach ( $currency_list as $curr ) :
   	    							 echo '<option value="' . $curr->getId() . '">' . $curr->getCurrency() . '</option>';
									endforeach
									?>
   					</select>
   					</div>
				</div>

				<div class="form-group">
					<label class="control-label col-sm-2" for="inputTag">Lead Time:</label>
					<div class="col-sm-3">
						<input class="form-control" type="text" name="leadTime" value="">
					</div>
				</div>
			</div>
		</fieldset>

		<fieldset>
			<legend style="font-size: 9pt; color: gray;">
				<small><span class="glyphicon glyphicon-triangle-right"></span></small>&nbsp;
				<a href="#additional" class="" data-toggle="collapse">ADDITIONAL:</a>
			</legend>
			<div id="additional" class="collapse">


				<div class="form-group">

					<label class="control-label col-sm-2">Remarks:</label>
					<div class="col-sm-3">
						<textarea class="form-control" type="text" rows="4" placeholder=""
							name="remarks" style="font-size: 9pt;"><?php echo (!$entity == null)? $entity->getRemarks():"";?></textarea>
					</div>
				</div>



			</div>
		</fieldset>

		<div class="form-group">
			<label class="control-label col-sm-2" for="inputTag"></label>
			<div class="col-sm-3">
				<button onclick="submitAjaxForm('/inventory/item-transaction/gr1','gr_form');" type="submit" id="save"
					class="btn btn-default">
					<i class="glyphicon glyphicon-floppy-disk"> </i>&nbsp;Save
				</button>
			</div>
		</div>

	</form>
</div>


<script type="text/javascript">
    $('#vendor_item_unit').bind('change', function() {
    	//alert($('#vendor_item_unit').val());
    	$('#conversion_text').html($('#vendor_item_unit').val() + ' = ' + $('#conversion_factor').val() );
    });
    
    $('#conversion_factor').bind('change', function() {
    	//alert($('#vendor_item_unit').val());
    	$('#conversion_text').html($('#vendor_item_unit').val() + ' = ' + $('#conversion_factor').val() );
    });
    $( "input[id='trx_date']").datepicker({ firstDay: 1, dateFormat: 'yy-mm-dd',closeText: 'X',changeMonth: true, changeYear: true});

     $( "#vendor_name_1" ).autocomplete({
      source: "/bp/vendor-search/auto-complete",
      minLength: 3,
      select: function( event, ui ) {
    	  $( "#vendor_id" ).val(ui.item.id);
        //alert	( "Selected: " + ui.item.value + " aka " + ui.item.id );
    	  //alert($( "#vendor_id" ).val());

    	 	$('#global-notice').show();
    		$('#global-notice').html('"' + ui.item.value + '" selected');
    		$('#global-notice').fadeOut(5000);
    		//$("#jquery_dialog").dialog("close");
      }
      })
      .autocomplete( "instance" )._renderItem = function( ul, item ) {
      return $( "<li>" )
        .append( "<div style='padding-bottom: 5px; border-bottom: thin solid gray;'>" + item.value + "<br><span style='color:gray;font-size: 9pt;'>" + item.vendor_country + "<span></div>" )
        .appendTo( ul );
      };


     
    	      

 </script>