
<h3>Item Transaction</h3>
<ul id="menu">
	<li><a href="<?php echo $this->baseUrl ?>/inventory/item-transaction/gr">Good Receive</a></li>
	<li><a href="<?php echo $this->baseUrl ?>/inventory/gi/add">Good Issue</a></li>
	<li><a href="<?php echo $this->baseUrl ?>/inventory/item-transaction/transfer">Good Transfer</a></li>

	<li><a href="<?php echo $this->baseUrl ?>/inventory/item-transaction/list">Movement List</a></li>

</ul>


