
<div id="tabs" style="font-size: 10pt"> 
  <ul>
  <li ><a href="#general">Item Transaction:</a></li>
 	</ul>
   
 <div id="general">
 
<ul id="menu">
	<li><a href="<?php echo $this->baseUrl ?>/inventory/item-transaction/gr">Good Receive</a></li>
	<li><a href="<?php echo $this->baseUrl ?>/inventory/gi/add">Good Issue</a></li>
	<li><a href="<?php echo $this->baseUrl ?>/inventory/item-transaction/transfer">Good Transfer</a></li>

	<li><a href="<?php echo $this->baseUrl ?>/inventory/item-transaction/list">Movement List</a></li>

</ul>

</div>
</div>
