<div id="tabs" style="font-size: 9.5pt">
	<ul>
		<li><a href="#general">Transaction</a></li>
	</ul>

<div id="general">

 <div class="panel-group"  >
  <div class="panel panel-default">
    <div class="panel-heading">
      <h4 class="panel-title">
        <a data-toggle="collapse" href="#collapse1">
<small><span class="glyphicon glyphicon-filter"></span></small>
        Filter</a>
      </h4>
    </div>
    <div id="collapse1" class="panel-collapse collapse">
      <div class="panel-body" style="padding: 0px;">
  <div
					style="padding: 3px; font-size:10pt; background:url(/images/bg1.png); background-repeat: repeat-x; background-color: #FFFFFF;">
					    
 <form class="form-horizontal" action="<?php echo $this->baseUrl ?>/inventory/item-transaction/list" method="get" enctype="multipart/form-data">
	
	<div class="form-group">
		<label class="control-label col-sm-2" for="inputTag">Active Items</label>
		<div class="col-sm-3">
			<select class="form-control" name="is_active">
									<option
									<?php echo $is_active =='2'? "selected='selected'":"";?>
										value="2">All</option>
									<option
									<?php echo $is_active=='1'? "selected='selected'":"";?>
										value="1">Active</option>
									<option
									<?php echo $is_active=='-1'? "selected='selected'":"";?>
										value="-1">Inactive</option>
									</select>
		</div>
	</div>

	<div class="form-group">
		<label class="control-label col-sm-2" for="inputTag">Sort by</label>
		<div class="col-sm-3">
			<select class="form-control" name="sort_by">
									<option value="">None</option>
									<option
										<?php echo $sort_by=='itemName'? "selected='selected'":"";?>
										value="itemName">Item Name</option>
						
									<option <?php echo $sort_by=='vendorName'? "selected='selected'":"";?>
										value="vendorName">Vendor Name</option>
									<option <?php echo $sort_by=='trxDate'? "selected='selected'":"";?>
										value="trxDate">Transaction Date</option>
 			</select>
 			<input <?php if(!$sort==null): echo ($sort=='ASC')? "checked":""; else: echo "checked"; endif;?> type="radio" name="sort" value="ASC">&nbsp;ASC&nbsp;&nbsp;
 			<input <?php if(!$sort==null): echo ($sort=='DESC')? "checked":""; else: echo ""; endif;?> type="radio" name="sort" value="DESC">&nbsp;DESC&nbsp;&nbsp;
 							
		</div>
	</div>
	
	
	<div class="form-group">
		<label class="control-label col-sm-2" for="inputTag">Result per page</label>
		<div class="col-sm-3">
			<select class="form-control" name="perPage">
									<option value="">None</option>
									<option <?php echo $per_pape=='15'? "selected='selected'":"";?>
										value="15">15</option>

									<option <?php echo $per_pape=='20'? "selected='selected'":"";?>
										value="20">20</option>

									<option <?php echo $per_pape=='30'? "selected='selected'":"";?>
										value="30">30</option>

									<option <?php echo $per_pape=='50'? "selected='selected'":"";?>
										value="50">50</option>
									<option
										<?php echo $per_pape=='100'? "selected='selected'":"";?>
										value="100">100</option>
									<option
										<?php echo $per_pape=='200'? "selected='selected'":"";?>
										value="200">200</option>
								</select>
		</div>
	</div>
	
	<div class="form-group">
		<div class="col-sm-offset-2 col-sm-10">
			<button type="submit" class="btn btn-default">Show</button>
		</div>
	</div>     
	     
 </form>
 
     </div> 
      </div>
     </div>
  </div>
</div>
 

<?php

if ($total_records <= 0) {
	
	echo 'No record found!';
} else {
	
	if (! is_null ( $paginator )) {
		echo 'Record ' . $paginator->minInPage . ' to ' . $paginator->maxInPage . ' | ' . $total_records. ' records found!';
	} else {
		echo $total_records. ' records found!';
	}
	
	?>

<table style="font-size: 9.5pt;" class="table table-bordered table-hover">
	<thead>
		<tr>
			<td><b>#</b></td>
			<td><b>Date</b></td>
			
			<td><b>item</b></td>
			<td><b>Vendor</b></td>
			<td><b>Q/ty</b></td>
			<td><b>Price</b></td>
			<td><b>Currency</b></td>
			<td><b>Payment<br>Method</b></td>
			<td><b>Unit</b></td>	
			<td><b>Conversion</b></td>
			<td><b>A</b></td>
			<td><b></b></td>
			</tr>
	</thead>

	<tbody>
 
	 <?php
	
	$count = 0;
	foreach ( $list as $a ) :
		$count ++;
		/**@var \Application\Entity\NmtInventoryTrx $a ; */
		
		?>
	 <tr>
	  		<td><?php echo ($paginator===null)? $count:$paginator->minInPage -1+ $count;?></td>
	  		<td><?php if($a->getTrxDate()): echo (date_format($a->getTrxDate(),"d-m-Y")); endif;?> </td>
	  		
	  		<td><?php echo ($a->getItem()!==null )? $a->getItem()->getItemName():"N/A";?> </td>
			<td><?php echo $a->getVendor()->getVendorName();?>
			<?php if($a->getInvoiceRow()!==null): if($a->getInvoiceRow()->getInvoice()!==null): 
echo '<div><a target="_blank" style="font-size: 8.5pt; color:gray" href="/finance/v-invoice/add1?token='. 
			$a->getInvoiceRow()->getInvoice()->getToken().'&entity_id='.$a->getInvoiceRow()->getInvoice()->getId().'">'.$a->getInvoiceRow()->getInvoice()->getSapDoc().'</a>';
endif;
endif;?>			
			</td>
			<td><?php echo number_format( $this->escapeHtml($a->getQuantity()), 1);?></td>
			<td><?php echo number_format( $this->escapeHtml($a->getVendorUnitPrice()), 2);?></td>
			<td><?php if($a->getCurrency()!==null): echo $this->escapeHtml($a->getCurrency()->getCurrency()); endif;?></td>
			<td><?php echo ($a->getPmtMethod() !==null)? $this->escapeHtml($a->getPmtMethod()->getMethodCode()):"N/A";?></td>
			<td><?php echo $this->escapeHtml($a->getVendorItemUnit());?></td>
			<td><?php echo $this->escapeHtml($a->getConversionText());?></td>
			<td><?php echo ($a->getIsActive()=='1')?'<small><i class="glyphicon glyphicon-ok"></i></small>':'';?></td>
	
		 <td>
<a href="<?php echo $this->baseUrl ?>/inventory/item-purchase/show?token=<?php echo $a->getToken();?>&entity_id=<?php echo $a->getID();?>&checksum=<?php echo $a->getChecksum();?>">Show</a>
<a href="<?php echo $this->baseUrl ?>/inventory/item-purchase/edit?token=<?php echo $a->getToken();?>&entity_id=<?php echo $a->getID();?>&checksum=<?php echo $a->getChecksum();?>">Edit</a>
</td>
		
		</tr>
<?php endforeach; ?>

 </tbody>
</table>

<?php
	
	// ===============================
	if (! is_null ( $paginator )) :
		
		// change it only
	$base = $this->baseUrl . '/inventory/item-transaction/list?is_active='. $is_active.'&sort_by='.$sort_by.'&sort='.$sort;
		$_connector_symbol = '&';
		
		$last = $base . $_connector_symbol . 'page=' . $paginator->totalPages . '&perPage=' . $paginator->resultsPerPage;
		$first = $base . $_connector_symbol . 'page=1&perPage=' . $paginator->resultsPerPage;
		
		$p1 = ($paginator->page) - 1;
		$p2 = ($paginator->page) + 1;
		
		$prev = $base . $_connector_symbol . 'page=' . $p1 . '&perPage=' . $paginator->resultsPerPage;
		$next = $base . $_connector_symbol . 'page=' . $p2 . '&perPage=' . $paginator->resultsPerPage;
		
		echo '<ul class="pagination pagination-sm">';
		
		if ($paginator->page != 1 and $paginator->totalPages > 10) {
			echo '<li><a href="' . $first . '"> |< </a></li>';
			echo '<li><a href="' . $prev . '"> < </a></li>';
		}
		
		for($i = $paginator->minInPageSet; $i <= $paginator->maxInPageSet; $i ++) {
			
			$url = $base . $_connector_symbol . 'page=' . $i . '&perPage=' . $paginator->resultsPerPage;
			
			if ($i == $paginator->page) {
				echo '<li><a class="active" href="#">' . $i . '</a></li>';
			} else {
				echo '<li><a href="' . $url . '"> ' . $i . ' </a></li>';
			}
		}
		if ($paginator->page != $paginator->totalPages and $paginator->totalPages > 10) {
			echo '<li><a href="' . $next . '"> > </a></li>';
			echo '<li><a href="' . $last . '"> >| </a></li>';
		}
		echo '</ul>';
endif;
	
}
// ===============================
?>
</div></div>



