	<h1><?php echo $this->escapeHtml($sparepart->name);?></h1>
	
<?php echo $this->escapeHtml($sparepart->id);?>

<?php //var_dump($categories); ?>

<form action="<?php echo $this->baseUrl ?>/inventory/spareparts/add-category"	method="post" enctype="multipart/form-data" id="New Sparepart">
	
<input type="hidden" name="id" value="<?php echo (int) $sparepart->id; ?>" />
<table border="1" cellpadding="3">
<tr>
		<td><b></b></td>

		<td><b>Spare Part Category</b></td>
		
	</tr>	
	<?php foreach ($categories as $category) : ?>
 	
    <tr>
    		<td><input type="checkbox" name="category[]" value="<?php echo $this->escapeHtml($category['id2']);?>" class="checkbox"/></td>
    
		<td><?php echo $this->escapeHtml($category['level2']);?></td>
     	</tr>
<?php endforeach; ?>

<tr>
	<td></td> 
	<td><input type="submit" name="add" value="Add" />	</td>
</tr>
</table>
