<h4>Create New Spare-Part:</h4>
<?php echo $category!==null ?'Category: ' . ($category->name) :""?>
<hr>

<?php if (count($errors)>0)
{
echo '<div class="alert alert-error">';
	
	echo '<ul>';
	 foreach ($errors as $error) :
	 echo '<li>'.$error . '</li>';
	 
	 endforeach;
	 echo '</ul>';
	 echo '</div>';
} 
?>
	

 <form class="form-horizontal" action="<?php echo $this->baseUrl ?>/inventory/spareparts/add"	method="post" enctype="multipart/form-data" id="NewSP" >
 <input type="hidden" name="category_id" value="<?php echo $category!==null ? ($category->id) :""?>" />
 <input type="hidden" name="redirectUrl" value="<?php echo $redirectUrl ?>" />

 
      <div class="control-group">
        <label class="control-label" for="inputTag">Tag</label>
        <div class="controls">
          <input type="text" id="inputTag" placeholder="" name="tag" value="<?php echo $sparepart!==null ? ($sparepart->tag) :""?>">
        </div>
      </div>
      
      <div class="control-group">
        <label class="control-label" for="inputName">Name</label>
        <div class="controls">
          <input type="text" id="inputName" placeholder="" name="name" value="<?php echo $sparepart!==null ? ($sparepart->name) :""?>">
        </div>
      </div>
      
      <div class="control-group">
        <label class="control-label" for="inputNameLocal">Name</label>
        <div class="controls">
          <input type="text" id="inputNameLocal" placeholder="" name="name_local" value="<?php echo $sparepart!==null ? ($sparepart->name_local) :""?>">
        </div>
      </div>
      
      <div class="control-group">
        <label class="control-label" for="inputDescription">Description</label>
        <div class="controls">
          <textarea id="inputDescription" placeholder="" rows="3" name="description"><?php echo $sparepart!==null ? ($sparepart->description):""?></textarea>
        </div>
      </div>
      
       <div class="control-group">
        <label class="control-label" for="inputNameLocal">Code /Serial</label>
        <div class="controls">
          <input type="text" id="sparepart_code" placeholder="Code of supplier" name="code" value="<?php echo $sparepart!==null ? ($sparepart->code) :""?>"> 
          <a href="javascript:;" onclick="checkSparePartCode()" class="helper">check code</a>
        </div>
      </div>
      
       <div class="control-group">
        <label class="control-label" for="inputLocation">Location</label>
        <div class="controls">
          <input type="text" id="inputLocation" placeholder="" name="location" value="<?php echo $sparepart!==null ? ($sparepart->location) :""?>">
        </div>
      </div>
      
      <div class="control-group">
        <label class="control-label" for="inputLocation">Pictures	</label>
        <div class="controls">
          <input type="file" name="pictures[]" /><br>
   		<input type="file" name="pictures[]" /><br>
			<input type="file" name="pictures[]" /><br>

        </div>
      </div>
      
      <div class="control-group">
        <div class="controls">
             <button type="submit" class="btn"><i class="icon-plus">  </i> Create</button>
        </div>
      </div>
    </form>



<div id = "dialog" style="display: none;">Check code...</div>