<h3>Create New Spare-Part</h3>

<?php if (count($errors)>0){
	echo '<ul style="color:#FF0000">';
	 foreach ($errors as $error) :
	 echo '<li>'.$error . '</li>';	 
	 endforeach;
	 echo '</ul>';
	 ?>
	 <hr> 
<?php } ?>

<hr>
<form action="<?php echo $this->baseUrl ?>/inventory/spareparts/add"	method="post" enctype="multipart/form-data" id="NewAsset">
<input type="hidden" name="category_id" value="<?php echo (int) $category_id; ?>" />
<input type="hidden" name="redirectUrl" value="<?php echo $redirectUrl ?>" />


<table>

<tr>
	<td><label for="tag">Tag</label> </td>
	<td><input type="text"	name="tag" value="" /></td>
</tr>

<tr>
	<td><label for="category">Name</label> </td>
	<td><input type="text"	name="name" value="" /></td>
</tr>

<tr>
	<td><label for="category">Name Local (Laos)</label> </td>
	<td><input type="text"	name="name_local" value="" /></td>
</tr>
<tr>
	<td><label for="category">Description</label> 
	<td><textarea cols="60" name="description" id="description" style="background:#FFFFFF" rows="6"></textarea></td>
</tr>

<tr>
	<td><label for="code">Code /Serial</label> </td>
	<td><input type="text"	name="code" value="" id="sparepart_code"/> <a href="javascript:;" onclick="checkSparePartCode()" class="helper">check code</a></td>
</tr>

<tr>
	<td><label for="origin">Location</label></td>
	<td><input type="text"	name="location" value="" /></td>
</tr>

<tr>
	<td></td> 
	<td>	</td>
</tr>

</table>

<p>Pictures:</p>
<input type="file" name="pictures[]" /><br>
<input type="file" name="pictures[]" /><br>
<input type="file" name="pictures[]" /><br>

<hr>

<input type="submit" name="add" value="Create" />
</form>


<div id = "dialog" style="display: none;">Check code...</div>