 <div class="btn-group">
    <button type="button" class="btn btn-defaultdropdown-toggle" data-toggle="dropdown">
    Spare-Part Management <span class="caret"></span></button>
    <ul class="dropdown-menu" role="menu">
 				<li><a href="/inventory/spareparts/category">Spare-part category</a>
						</li>
						<li><a href="/inventory/spareparts/list">Show all spare-parts</a>
						</li>
						<li class="divider"></li>
 						<li><a href="/inventory/report/index">Reporting</a>
						</li>
			
    </ul>
  </div>
<hr>
	

    <form class="form-search" action="<?php echo $this->baseUrl ?>/inventory/search/sparepart"	method="get" enctype="multipart/form-data">
      <input type="text" name = "query" class="">
      <button type="submit" class="btn"><i class="icon-search">  </i>Search</button>
   </form>
 
 

<table class="pure-table pure-table-bordered">
<thead>
<tr>
		<td><b>Spare Part Category</b></td>
		<td><b>Action</b></td>
	</tr>
</thead>
<tbody>	
 
  <?php 
	 
	 $count = 0;
	 foreach ($assetCategories as $category) : 
	 	 $count++;
	 echo  ($count % 2 == 1) ? "<tr>" : "<tr class=\"pure-table-odd\">";
	 	 
	 ?>
 
		<td><?php echo $this->escapeHtml($category->l1);?> <span class="label label-info" title="<?php echo $this->escapeHtml($category->members);?> items"><?php echo $this->escapeHtml($category->members);?></span></td>
		<td>
         <a href="<?php echo $this->baseUrl ?>/inventory/spareparts/show-category?id=<?php echo $this->escapeHtml($category->id);?>">Detail</a>
         <a href="<?php echo $this->baseUrl ?>/inventory/admin/edit-sparepart-category?id=<?php echo $this->escapeHtml($category->id);?>">Edit</a>
         <a href="<?php echo $this->baseUrl ?>/inventory/admin/add-sparepart-category-member?id=<?php echo $this->escapeHtml($category->id);?>">Add-Member</a>
    	
     	</td>
	</tr>
<?php endforeach; ?>
</tbody>
</table>




