
<h4 >Spare-part category</h4>

	<a href="<?php echo $this->baseUrl ?>/inventory/admin/add-sparepart-category">Add spare part category</a>

	| <a href="<?php echo $this->baseUrl ?>/inventory/spareparts/list">Show all spare parts</a>
	| <a href="<?php echo $this->baseUrl ?>/inventory/spareparts/add">Add new
		spare part</a>

    <form class="form-search" action="<?php echo $this->baseUrl ?>/inventory/search/sparepart"	method="get" enctype="multipart/form-data">
      <input type="text" name = "query" class="">
      <button type="submit" class="btn"><i class="icon-search">  </i>Search</button>
   </form>
 
 

<table class="pure-table pure-table-bordered"">
<thead>
<tr>
		<td><b>Spare Part Category</b></td>
		<td><b>Action</b></td>
	</tr>
</thead>
<tbody>	
 
  <?php 
	 
	 $count = 0;
	 foreach ($assetCategories as $category) : 
	 	 $count++;
	 echo  ($count % 2 == 1) ? "<tr>" : "<tr class=\"pure-table-odd\">";
	 	 
	 ?>
 
		<td><?php echo $this->escapeHtml($category->l1);?> <span class="label label-info"><?php echo $this->escapeHtml($category->members);?></span></td>
		<td>
         <a href="<?php echo $this->baseUrl ?>/inventory/spareparts/show-category?id=<?php echo $this->escapeHtml($category->id);?>">Detail</a>
         <a href="<?php echo $this->baseUrl ?>/inventory/admin/add-sparepart-category-member?id=<?php echo $this->escapeHtml($category->id);?>">Add-Member</a>
    	
     	</td>
	</tr>
<?php endforeach; ?>
</tbody>
</table>




