	<a href="<?php echo $this->baseUrl ?>/inventory/admin/add-sparepart-category">Add spare part category</a>

	| <a href="<?php echo $this->baseUrl ?>/inventory/spareparts/list">Show all spare parts</a>
	| <a href="<?php echo $this->baseUrl ?>/inventory/spareparts/add">Add new
		spare part</a>


<table border="1" cellpadding="3">
<tr>
		<td><b>Spare Part Category</b></td>
		<td><b>No.Spare parts</b></td>
		
		<td><b>Action</b></td>
	</tr>	
 <?php foreach ($assetCategories as $category) : ?>
 
 	
    <tr>
		<td><?php echo $this->escapeHtml($category->l1);?></td>
		<td><?php echo $this->escapeHtml($category->members);?></td>
		<td>
         <a href="<?php echo $this->baseUrl ?>/inventory/admin/edit-sparepart-category?id=<?php echo $this->escapeHtml($category->id);?>">Edit</a>
         | <a href="<?php echo $this->baseUrl ?>/inventory/admin/delete-sparepart-category?id=<?php echo $this->escapeHtml($category->id);?>">Delete</a>
     	 | <a href="<?php echo $this->baseUrl ?>/inventory/spareparts/show-category?id=<?php echo $this->escapeHtml($category->id);?>">detail</a>
         | <a href="<?php echo $this->baseUrl ?>/inventory/admin/add-sparepart-category-member?id=<?php echo $this->escapeHtml($category->id);?>">Add member</a>
    	
     	</td>
	</tr>
<?php endforeach; ?>
</table>




