<h3>Spare Edit</h3>


<form action="<?php echo $this->baseUrl ?>/inventory/spareparts/edit"	method="post" enctype="multipart/form-data" id="NewAsset">
<input type="hidden" name="id" value="<?php echo (int) $sparepart->id; ?>" />

<table>

<tr>
	<td><label for="tag">Tag</label> </td>
	<td><input type="text"	name="tag" value="<?php echo  $sparepart->tag; ?>" /></td>
</tr>

<tr>
	<td><label for="category">Name</label> </td>
	<td><input type="text"	name="name" value="<?php echo  $sparepart->name; ?>" /></td>
</tr>

<tr>
	<td><label for="category">Name</label> </td>
	<td><input type="text"	name="name_local" value="<?php echo  $sparepart->name_local; ?>" /></td>
</tr>
<tr>
	<td><label for="category">Description</label> 
	<td><textarea cols="45" name="description" id="description" style="background:#FFFFFF" rows="3"><?php echo  $sparepart->description; ?></textarea></td>
</tr>

<tr>
	<td><label for="code">Code /Serial</label> </td>
	<td><input type="text"	name="code" value="<?php echo  $sparepart->code; ?>" /></td>
</tr>

<tr>
	<td><label for="origin">Location</label></td>
	<td><input type="text"	name="location" value="<?php echo  $sparepart->location; ?>" /></td>
</tr>

<tr>
	<td></td> 
	<td><input type="submit" name="add" value="update" />	</td>
</tr>

</table>

<p>Pictures:</p>
<input type="file" name="pictures[]" /><br>
<input type="file" name="pictures[]" /><br>
<input type="file" name="pictures[]" /><br>

</form>
