<script language="javascript">
			var id_array = [];
</script>

<h4>
	Receiving: <span class="label label-success"><?php echo $sp->tag; ?></span> <?php echo $sp->name; ?> </h4>

<hr>

<?php

if (count ( $errors ) > 0) {
	echo '<div class="alert alert-error">';
	
	echo '<ul>';
	foreach ( $errors as $error ) :
		echo '<li>' . $error . '</li>';
	endforeach
	;
	echo '</ul>';
	echo '</div>';
}
?>

<?php if (count($pending_pr_item)>0): 
$total_confirmed_balance=0
?>

<table class="table table-striped table-bordered">
	<thead>
		<tr>
			<td><b>#</b></td>
			<td><b>PR#</b></td>
			<td><b data-toggle="tooltip" title="Ordred Quantity">Requested <br>Quantity
			</b></td>
			<td><b data-toggle="tooltip" title="Balance">Balance</b></td>
			<td><b data-toggle="tooltip" title="Free">Free</b></td>
			<td><b>EDT</b></td>
			<td><b>Status</b></td>

			<td><b>Action</b></td>
		</tr>
	</thead>
	<tbody>	
	
  <?php
	
	$count = 0;
	foreach ( $pending_pr_item as $item ) :
		$count ++;
		// echo ($count % 2 == 1) ? "<tr>" : "<tr class=\"pure-table-odd\">";
		?>
		<tr>
			<td><?php echo ($paginator===null)? $count:$paginator->minInPage -1+ $count;?></td>
			<td><a href="/procurement/pr/show?pr_id=<?php echo $item->purchase_request_id;?>"
				target="_blank">PR#<?php echo $item->purchase_request_id;?></a></td>


			<td><span id="<?php echo $item->sparepart_id;?>_delivered_quantity"><?php echo $item->quantity;?></span></td>
			<td><?php echo $item->confirmed_balance;			
			$total_confirmed_balance= $total_confirmed_balance + $item->confirmed_balance;
			
			?></td>
			<td>-</td>
		
		<?php if($item->confirmed_balance == 0): ?>
			<td><?php echo date_format(date_create($item->EDT),"Y-m-d");?>
			<div>
					<span style="font-size: 7pt;" class="label label-success">Fulfilled</span>
				</div></td>
		<?php else: ?>		
			<td><span id="<?php echo $item->id;?>_EDT"><?php echo date_format(date_create($item->EDT),"Y-m-d");?></span>
				<div>
					<span
						style="color: gray; font-size: 8pt; font-style: italic; vertical-align: center"
						id="<?php echo $item->id;?>_timer"></span>
				</div></td>
		<?php endif; ?>	
<td>

				<div style="color: black;">
				Good Received by Procurement: <?php echo ($item->total_received_quantity>0)? '<b>'. $item->total_received_quantity.'</b>':$item->total_received_quantity;?><br>
				Notified to requester: <?php echo ($item->unconfirmed_quantity>0)? '<b>'. $item->unconfirmed_quantity.'</b>':$item->unconfirmed_quantity;?><br>
				</div>

			</td>
			<td>
			
			<?php if($item->unconfirmed_quantity>0):?>
			<a
				href="/procurement/do/get-notification?pr_item_id=<?php echo $item->id;?>"><i
					class="icon-check"> </i> Show Notification</a>
			<?php else: ?>	
				Processing
			<?php endif; ?>	
		</td>

			<script language="javascript">
				id_array.push(<?php echo $item->id;?>);
		</script>
		</tr>
	<?php endforeach; ?>
	
</tbody>
</table>
<?php 
echo '<b>Total Pending Quantity: ' .$total_confirmed_balance .'</b>';

else:?>

<div class="alert alert-warning">Please make Purchase Order!</div>
<?php endif;?>