<h4> Spare Part Issue: </h4>
<hr>

<?php if (count($errors)>0){
	echo '<ul style="color:#FF0000">';
	 foreach ($errors as $error) :
	 echo '<li>'.$error . '</li>';	 
	 endforeach;
	 echo '</ul>';
	 ?>
	 <hr>
 
<?php } ?>


<h5> Spare Part Name: <?php echo $sp->name; ?> </h5>




<?php if ($instock > 0){
	
	
?>

<form action="<?php echo $this->baseUrl ?>/inventory/spareparts/issue"
	method="post" enctype="multipart/form-data" id="New Sparepart">
	<input type="hidden" name="sparepart_id" value="<?php echo (int) $sp->id; ?>" />
	<input type="hidden" name="instock" value="<?php echo (int) $instock ?>" />
	<input type="hidden" name="asset_id" id="asset_id" value="" />
	
	<table>
			
		<tr>
			<td><label for="asset">Issue for Asset:</label></td>
		<td><input type="text" name="asset" value="" id="asset" /><a href="javascript:;" onclick="showDialog()" class="helper"> Select Asset</a>
		</td>
	
		</tr>
	
		<tr>
			<td><label for="movement_date">Issue date</label></td>
			<td><input type="text" name="movement_date" value="" id="movement_date" /></td>
		</tr>
		<tr>
			<td><label for="quantity">Quantity:</label></td>
			<td><input type="text" name="quantity" value="" /> (In stock: <?php echo (int) $instock . ' pcs.'; ?>)
			</td>
		</tr>

		<tr>
			<td><label for="requester">Requester: </label></td>
			<td><input type="text" name="requester" value="" /></td>
		</tr>

		<tr>
			<td><label for="reason">Reason: </label></td>
			<td><textarea cols="45" name="reason" id="reason"
					style="background: #FFFFFF" rows="3"></textarea></td>
		</tr>


		<tr>
			<td><label for="comment">Comment: </label></td>
			<td><textarea cols="45" name="comment" id="comment"
					style="background: #FFFFFF" rows="3"></textarea></td>
		</tr>

		<tr>
			<td></td>
			<td><input type="submit" name="receive" value="Issue" /></td>
		</tr>

	</table>
</form>

<div id = "dialog">No asset found...</div>


<?php }else {

	echo 'Please make order!';
	
	
}?>
	
 <?php if ($pictures->count()>0){ ?>

<h5> Spare part Picture:</h5>
<table border="1">

 <?php foreach ($pictures as $pic) : ?>
  	
    <tr>
		<td>
			<img alt="" src="/inventory/image/sparepart?id=<?php  echo $this->escapeHtml($pic->id);?>">
     	</td>
	</tr>
<?php endforeach; 
?>
</table>

<?php }?>