<h4>Issuing: <span class="label label-success"><?php echo $sp->tag; ?></span> <?php echo $sp->name; ?> </h4>
<hr>
<?php if (count($errors)>0)
{
echo '<div class="alert alert-error">';
	
	echo '<ul>';
	 foreach ($errors as $error) :
	 echo '<li>'.$error . '</li>';
	 
	 endforeach;
	 echo '</ul>';
	 echo '</div>';
} 
?>
	



<?php if ($instock + $total_confirmed_balance>0 ){
	
?>


 <form class="form-horizontal" action="<?php echo $this->baseUrl ?>/inventory/spareparts/issue"	method="post" enctype="multipart/form-data" id="NewSP" >
 	<input type="hidden" name="sparepart_id" value="<?php echo (int) $sp->id; ?>" />
	<input type="hidden" name="instock" value="<?php echo (int) $instock ?>" />
	<input type="hidden" name="asset_id" id="asset_id" value="<?php echo $movement!==null ? ($movement->asset_id) :""?>" />
	<input type="hidden" name="redirectUrl" value="<?php echo $redirectUrl ?>" />
	
	<div class="control-group">
        <label class="control-label" for="inputNameLocal">Movement Type: </label>
        <div class="controls">
        	<select name="movement_type">
      	    <?php foreach ($movement_types as $key =>$a) :
        		echo '<option value="'.$a . '">'. $a . '</option>';
	    		endforeach; 
			?>   		
   			</select>
	     </div>
      </div>
 	
 	 <div class="control-group">
        <label class="control-label" for="inputAsset">Issue for Asset:</label>
        <div class="controls">
<input readonly type="text" name="asset_name" id="asset_name" value="<?php echo $asset_name!==null ? $asset_name :""?>"/>
<a href="javascript:;" onclick="openAssetSearchDialog()" class="helper"> Select Asset <i class=" icon-folder-open"></i></a>        </div>
      </div>
 
      <div class="control-group">
         <div class="controls">
<input readonly type="text" name="asset" id="asset" value="<?php echo $movement!==null ? ($movement->asset_name) :""?>"/>
</div>
      </div>
      
      <div class="control-group">
        <label class="control-label" for="inputName">Issue date:</label>
        <div class="controls">
  			<input type="text" name="movement_date" placeholder =" please select" id="movement_date" value="<?php echo $movement!==null ? ($movement->movement_date) :""?>" />
         </div>
      </div>
      
      <div class="control-group">
        <label class="control-label" for="inputNameLocal">Quantity:</label>
        <div class="controls">
			<input type="text" name="quantity" value="<?php echo $movement!==null ? ($movement->quantity) :""?>" /> <span class="label label-info">
			In stock: <?php echo (int) $instock . ' Pcs' ; ?><?php echo $total_confirmed_balance>0?" - Pending Order: ".$total_confirmed_balance . "Pcs":"";?></span>        
		</div>
      </div>
      
       <div class="control-group">
        <label class="control-label" for="inputNameLocal">Requester:</label>
        <div class="controls">
			<input type="text" name="requester" value="<?php echo $movement!==null ? ($movement->requester) :""?>" />     
		</div>
      </div>
      
      <div class="control-group">
        <label class="control-label" for="inputDescription">Reason:</label>
        <div class="controls">
          <textarea class="form-control" id="inputDescription" placeholder="" rows="3" name="reason"><?php echo $movement!==null ? ($movement->reason) :""?></textarea>
        </div>
      </div>
      
      
      <div class="control-group">
        <div class="controls">
             <button type="submit" class="btn"><i class="icon-minus">  </i> Issue</button>
        </div>
      </div>
    </form>




<?php }else {

	echo 'Please make order!';
	
	
}?>

<hr>
<h5>    <a href="/inventory/spareparts/pictures?sparepart_id=<?php echo (int) $sp->id; ?>">Spare-part pictures</a></h5>

<?php if (count($pictures)>0): ?>
<div id="lightgallery">

 <?php foreach ($pictures as $pic) : ?>
  	
    <a href="/inventory/image/sparepart?id=<?php  echo $this->escapeHtml($pic->id);?>">
    <img class= "img-rounded" width="100" height="100" src="/inventory/image/sparepartthumbnail200?id=<?php  echo $this->escapeHtml($pic->id);?>"/>
    </a>
<?php endforeach; ?>
</div>

<?php endif;?>


<!-- Modal -->
<div id="myModal" class="modal hide" role="dialog">
	<div class="modal-dialog modal-lg" role="document">
		<div class="modal-header">
			<button type="button" class="close" data-dismiss="modal">&times;</button>
			<h5 class="modal-title">Mascot International (Laos) - Asset Search</h5>
		</div>
		<div class="modal-body">
			<span id="_status"></span>
			<form class="form-horizontal"
				action=""
				method="post" enctype="multipart/form-data" id="NewSP">
				<input type="hidden" name="redirectUrl"
					value="<?php echo $redirectUrl ?>" /> <input type="hidden"
					name="article_id" id="item_id" value="" />

				<div class="control-group">
					<label class="control-label" for="inputTag">Asset Search:</label>
					<div class="controls">
						<input type="text" id="asset_search_term1" placeholder="Please enter search term" name="name"
							value="">
					</div>
				</div>
				
				 <div class="control-group">
		        <div class="controls">
		             <button type="button" class="btn" onclick ="showDialog()"><i class="icon-search">  </i> Search...</button>
		        </div>
      			</div>
			</form>
		</div>
		
		<!-- 
		<div class="modal-footer">
			<button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
			<button onclick="addItemToCart('SPARE-PART');" type="button"
				class="btn btn-primary">Add To Cart</button>
		</div>
		 -->
	</div>
</div>	


<div id = "dialog" style="display: none;">

   <form style="padding-top:10pt" class="form-search" action="/inventory/search/sparepart"	method="get" enctype="multipart/form-data">
      <input type="text" id="asset_search_term" placeholder="" name="name">
      <button type="button" class="btn" onclick ="showDialog()"><i class="icon-search">  </i>Search</button>
   </form>
<hr>

<div id="search_result"></div>

</div>