<h3>Spare parts list</h3>

	<a href="<?php echo $this->baseUrl ?>/inventory/spareparts/category">Spare part category</a>
	| <a href="<?php echo $this->baseUrl ?>/inventory/spareparts/add">Add new
		spare part</a>
<hr>


<form action="<?php echo $this->baseUrl ?>/inventory/search/sparepart"	method="get" enctype="multipart/form-data">
<input type="text"	name="query" value="" /> <button type="submit" class="pure-button">Search</button>
</form>



<?php

if ($total_spareparts <= 0) {
	
	echo 'No spare part found!';
} else {

	if (! is_null ( $paginator )) {
		echo 'Result '. $paginator->minInPage. ' to '.$paginator->maxInPage. ' | ' .$total_spareparts . ' spare parts found!';
	}else{	
		echo $total_spareparts . ' spare parts found!';
	}
?>
<table class="pure-table pure-table-bordered">
<thead>
	<tr>
		<td><b>Tag</b></td>
		<td><b>Spare Part Name</b></td>
		<td><b>Code</b></td>
		<td><b>Location</b></td>
		<td><b>IN</b></td>
		<td><b>OUT</b></td>
		<td><b>In Stock</b></td>
		
		
		<td><b>Action</b></td>
	</tr>
</thead>

 <tbody>
 
	 <?php 
	 
	 $count = 0;
	 foreach ($spareparts as $a) : 
	 	 $count++;
	 echo  ($count % 2 == 1) ? "<tr>" : "<tr class=\"pure-table-odd\">";
	 	 
	 ?>
	 
  	
    
		<td><?php echo $this->escapeHtml($a['tag']);?></td>
		<td><?php echo $this->escapeHtml($a['name']);?></td>
		<td><?php echo $this->escapeHtml($a['code']);?></td>
		<td><?php echo $this->escapeHtml($a['location']);?></td>
		<td><?php echo $this->escapeHtml($a['totalINFLOW']);?></td>
		<td><?php echo $this->escapeHtml($a['totalOUTFLOW']);?></td>
		<td><?php echo $this->escapeHtml($a['totalINFLOW'])-$this->escapeHtml($a['totalOUTFLOW']);?></td>

		<td>
		<a
			href="<?php echo $this->baseUrl ?>/inventory/spareparts/edit?id=<?php echo $this->escapeHtml($a['id']);?>">Edit
		</a>
		| 
		<a
			href="<?php echo $this->baseUrl ?>/inventory/spareparts/issue?sparepart_id=<?php echo $this->escapeHtml($a['id']);?>">Issue
		</a>
		|
		<a
			href="<?php echo $this->baseUrl ?>/inventory/spareparts/receive?sparepart_id=<?php echo $this->escapeHtml($a['id']);?>">Receive
		</a>
		|
		<a
			href="<?php echo $this->baseUrl ?>/inventory/spareparts/add-category?id=<?php echo $this->escapeHtml($a['id']);?>">change category
		</a>
		|
		<a
			href="<?php echo $this->baseUrl ?>/inventory/spareparts/show?id=<?php echo $this->escapeHtml($a['id']);?>">
				Detail </a></td>
	</tr>
<?php endforeach; ?>

 </tbody>
</table>


<br>

<?php
	
	if (! is_null ( $paginator )) {
		
		$last = $this->baseUrl . '/inventory/spareparts/list' . '?page=' . $paginator->totalPages . '&perPage=' . $paginator->resultsPerPage;
		
		$first = $this->baseUrl . '/inventory/spareparts/list' . '?page=1&perPage=' . $paginator->resultsPerPage;
		
		
		for($i = $paginator->minInPageSet; $i <= $paginator->maxInPageSet; $i ++) {
			
			$url = $this->baseUrl . '/inventory/spareparts/list' . '?page=' . $i . '&perPage=' . $paginator->resultsPerPage;
			
			$last = $this->baseUrl . '/inventory/spareparts/list' . '?page=' . $paginator->totalPages . '&perPage=' . $paginator->resultsPerPage;
			
			?>

<?php
			
			if ($i == $paginator->page) {
				echo $i;
			} else {
				?>
<a href="<?php echo $url; ?>"><?php echo $i ?></a>

<?php
			}
		}
		?>
	
<a href="<?php echo $last; ?>"> Last</a>
<?php
	}
}
?>

