<h4>Spare parts list</h4>

	<a href="<?php echo $this->baseUrl ?>/inventory/spareparts/category">Spare part category</a>
	| <a href="<?php echo $this->baseUrl ?>/inventory/spareparts/add">Add new
		spare part</a>
<hr>


  <form class="form-search" action="<?php echo $this->baseUrl ?>/inventory/search/sparepart"	method="get" enctype="multipart/form-data">
      <input type="text" name = "query" class="">
      <button type="submit" class="btn"><i class="icon-search">  </i>Search</button>
   </form>
 


<?php

if ($total_spareparts <= 0) {
	
	echo 'No spare part found!';
} else {

	if (! is_null ( $paginator )) {
		echo 'Result '. $paginator->minInPage. ' to '.$paginator->maxInPage. ' | ' .$total_spareparts . ' spare parts found!';
	}else{	
		echo $total_spareparts . ' spare parts found!';
	}
	
?>




<table class="pure-table pure-table-bordered">
<thead>
	<tr>
		<td><b>Tag</b></td>
		<td><b>Spare Part Name</b></td>
		<td><b>Code</b></td>
		<td><b>Location</b></td>
	
		<td><b>Action</b></td>
	</tr>
</thead>

 <tbody>
 
	 <?php 
	 
	 $count = 0;
	 foreach ($spareparts as $a) : 
	 	 $count++;
	 	echo  ($count % 2 == 1) ? "<tr>" : "<tr class=\"pure-table-odd\">";
	 	$instock = $a['totalINFLOW']-$a['totalOUTFLOW'];
	 
	 	 
	 ?>
	 
  	
    
		<td><?php echo $this->escapeHtml($a['tag']);?></td>
		<td><?php echo $this->escapeHtml($a['name']);?> 
			<?php if($instock > 0){			
			echo '<span class="label label-info">'.$instock.'</span>';				
			
		}else{
			
			echo '<span class="label">'.$instock.'</span>';				
		}
		?>	 </td>
		<td><?php echo $this->escapeHtml($a['code']);?></td>
		<td><?php echo $this->escapeHtml($a['location']);?></td>

		<td>
		<a
			href="<?php echo $this->baseUrl ?>/inventory/spareparts/edit?id=<?php echo $this->escapeHtml($a['id']);?>">Edit
		</a>
		<a
			href="<?php echo $this->baseUrl ?>/inventory/spareparts/issue?sparepart_id=<?php echo $this->escapeHtml($a['id']);?>">Issue
		</a>
		<a
			href="<?php echo $this->baseUrl ?>/inventory/spareparts/receive?sparepart_id=<?php echo $this->escapeHtml($a['id']);?>">Receive
		</a>
		<a
			href="<?php echo $this->baseUrl ?>/inventory/spareparts/add-category?id=<?php echo $this->escapeHtml($a['id']);?>">change category
		</a>
		<a
			href="<?php echo $this->baseUrl ?>/inventory/spareparts/show?id=<?php echo $this->escapeHtml($a['id']);?>">
				Detail </a></td>
	</tr>
<?php endforeach; ?>

 </tbody>
</table>


<br>

<?php
	
	if (! is_null ( $paginator )) {
		
		//change it only
		$base=$this->baseUrl . '/inventory/spareparts/list';
		
		$last 	= $base . '?page=' . $paginator->totalPages . '&perPage=' . $paginator->resultsPerPage;		
		$first 	= $base . '?page=1&perPage=' . $paginator->resultsPerPage;
		
		$p1 = ($paginator->page)-1;
		$p2 = ($paginator->page)+1;
		
		$prev = $base . '?page=' . $p1 . '&perPage=' . $paginator->resultsPerPage;
		$next = $base . '?page=' . $p2 . '&perPage=' . $paginator->resultsPerPage;
		
		
		echo '<ul class="pagination">';
		
		if($paginator->page != 1){
			echo '<li><a href="'.  $first.'"> |< </a></li>';
			echo '<li><a href="'.  $prev .'"> < </a></li>';
		}
		
		for($i = $paginator->minInPageSet; $i <= $paginator->maxInPageSet; $i ++) {
			
			$url = $base. '?page=' . $i . '&perPage=' . $paginator->resultsPerPage;
		
			
			if ($i == $paginator->page) {
				echo   '<li><a class="active" href="#">'.$i.'</a></li>';
			} else {
				echo '<li><a href="'. $url. '"> '. $i. ' </a></li>';
			}
		}
		if($paginator->page != $paginator->totalPages){
			echo '<li><a href="'.  $next.'"> > </a></li>';
			echo '<li><a href="'.  $last .'"> >| </a></li>';
		}
		echo '</ul>';
	}
}
?>

