	<a href="<?php echo $this->baseUrl ?>/inventory/spareparts/category">Spare part category</a>
	| <a href="<?php echo $this->baseUrl ?>/inventory/spareparts/add">Add new
		spare part</a>
<hr>

<?php

if ($total_spareparts <= 0) {
	
	echo 'No spare part found!';
} else {

	if (! is_null ( $paginator )) {
		echo 'Result '. $paginator->getMinInPage(). ' to '.$paginator->getMaxInPage(). ' | ' .$total_spareparts . ' spare parts found!';
	}else{	
		echo $total_spareparts . ' spare parts found!';
	}
?>
<hr>
<table border="1"  cellpadding="3">
	<tr>
		<td><b>Tag</b></td>
		<td><b>Spare Part Name</b></td>
		<td><b>Code</b></td>
		<td><b>Location</b></td>
		<td><b>Action</b></td>
	</tr>
	 <?php foreach ($spareparts as $a) : ?>
  	
    <tr>
		<td><?php echo $this->escapeHtml($a['tag']);?></td>
		<td><?php echo $this->escapeHtml($a['name']);?></td>
		<td><?php echo $this->escapeHtml($a['code']);?></td>
		<td><?php echo $this->escapeHtml($a['location']);?></td>

		<td>
		<a
			href="<?php echo $this->baseUrl ?>/inventory/spareparts/edit?id=<?php echo $this->escapeHtml($a['id']);?>">Edit
		</a>
		| 
		<a
			href="<?php echo $this->baseUrl ?>/inventory/spareparts/issue?sparepart_id=<?php echo $this->escapeHtml($a['id']);?>">Issue
		</a>
		|
		<a
			href="<?php echo $this->baseUrl ?>/inventory/spareparts/receive?sparepart_id=<?php echo $this->escapeHtml($a['id']);?>">Receive
		</a>
		|
		<a
			href="<?php echo $this->baseUrl ?>/inventory/spareparts/add-category?id=<?php echo $this->escapeHtml($a['id']);?>">change category
		</a>
		|
		<a
			href="<?php echo $this->baseUrl ?>/inventory/spareparts/show?id=<?php echo $this->escapeHtml($a['id']);?>">
				Detail </a></td>
	</tr>
<?php endforeach; ?>
</table>

<br>

<?php
	
	if (! is_null ( $paginator )) {
		
		$last = $this->baseUrl . '/inventory/spareparts/list' . '?page=' . $paginator->getTotalPages() . '&perPage=' . $paginator->getResultsPerPage();;
		
		$first = $this->baseUrl . '/inventory/spareparts/list' . '?page=1&perPage=' . $paginator->getResultsPerPage();;
		
		
		for($i = $paginator->getMinInPageSet(); $i <= $paginator->getMaxInPageSet(); $i ++) {
			
			$url = $this->baseUrl . '/inventory/spareparts/list' . '?page=' . $i . '&perPage=' . $paginator->getResultsPerPage();;
			
			$last = $this->baseUrl . '/inventory/spareparts/list' . '?page=' . $paginator->getTotalPages() . '&perPage=' . $paginator->getResultsPerPage();;
			
			?>

<?php
			
			if ($i == $paginator->getPage()) {
				echo $i;
			} else {
				?>
<a href="<?php echo $url; ?>"><?php echo $i ?></a>

<?php
			}
		}
		?>
	
<a href="<?php echo $last; ?>"> Last</a>
<?php
	}
}
?>

