<h3>Stock Movement</h3>

<h4> <?php echo $this->escapeHtml($sparepart->name);?> </h4>

<hr>
<table border="1">
	<tr>
		<td><b>id</b></td>
		<td><b>Date of Movement</b></td>
		<td><b>Flow</b></td>
		<td><b>Quantity</b></td>
	</tr>
 <?php foreach ($movements as $a) : ?>
  	
    <tr>
		<td><?php echo $this->escapeHtml($a['id']);?></td>
		<td><?php echo $this->escapeHtml($a['movement_date']);?></td>
		<td><?php echo $this->escapeHtml($a['flow']);?></td>
		<td><?php echo $this->escapeHtml($a['quantity']);?></td>
	</tr>

<?php endforeach; ?>
</table>

