<?php include (ROOT.'\module\Inventory\view\inventory\sp_menu.php'); ?>


<h5>Category:  <?php echo $category->name ?></h5>


<ul class="nav nav-pills">
	<li><a
		href="<?php echo $this->baseUrl ?>/inventory/spareparts/add?category_id=<?php echo $category->id ?>"><i
			class="icon-plus"> </i> Add New Spare-part</a></li>
			<li><a
		href="<?php echo $this->baseUrl ?>/inventory/spareparts/show-category?id=<?php echo $category->id ?>"><i
			class="icon-list"> </i> Show category</a></li>
</ul>

 <div class="row">
  <div class="col-md-4">
    <a href="pulpitrock.jpg" class="thumbnail">
      <p>Pulpit Rock: A famous tourist attraction in Forsand, Ryfylke, Norway.</p>
      <img src="pulpitrock.jpg" alt="Pulpit Rock" style="width:150px;height:150px">
    </a>
  </div>
  <div class="col-md-4">
    <a href="moustiers-sainte-marie.jpg" class="thumbnail">
      <p>Moustiers-Sainte-Marie: Considered as one of the "most beautiful villages of France".</p>
      <img src="moustiers-sainte-marie.jpg" alt="Moustiers Sainte Marie" style="width:150px;height:150px">
    </a>
  </div>
  <div class="col-md-4">
    <a href="cinqueterre.jpg" class="thumbnail">
      <p>The Cinque Terre: A rugged portion of coast in the Liguria region of Italy.</p>
      <img src="cinqueterre.jpg" alt="Cinque Terre" style="width:150px;height:150px">
    </a>
  </div>
</div>

<?php

if ($total_spareparts <= 0) {
	
	echo 'No spare part found!';
} else {
	
	if (! is_null ( $paginator )) {
		echo '<h5>Result ' . $paginator->minInPage . ' to ' . $paginator->maxInPage . ' | ' . $total_spareparts . ' members found! </h5>';
		;
	} else {
		echo '<h5>' . $total_spareparts . ' spare parts found! </h5>';
	}
}
?>


 <?php
 /*
 $spareparts1=$spareparts; 
 foreach ($spareparts1 as $a1 ) : ?>
  	
  	<div id="caption<?php echo $this->escapeHtml($a1['id']);?>" style="display:none">
    	<h4><?php echo $this->escapeHtml($a1['tag']);?></h4><p><?php echo $this->escapeHtml($a1['name']);?></p>
	</div>				
	<?php
	endforeach
	;
	*/
$no_pics=0;
?>
<div class="demo-gallery">
<div id="lightgallery" class="justified-gallery">

 
 <?php foreach ( $spareparts as $a ) : ?>
  	
  		<?php
		if ($a->sp_pic_id !== null) :
			?>
		<a data-toggle="tooltip" data-sub-html="<h3><?php echo $this->escapeHtml($a['tag']);?></h3><h4><?php echo $this->escapeHtml($a['name']);?></h4>" class="jg-entry" href="/inventory/image/sparepart?id=<?php echo $a->sp_pic_id;?>">
	    	<img class="img-rounded" title="<?php echo $this->escapeHtml($a['tag']);?>: <?php echo $this->escapeHtml($a['name']);?>" src="/inventory/image/sparepartthumbnail200?id=<?php echo $a->sp_pic_id;?>">
		 </a>
		<?php else:
			$no_pics=$no_pics+1;
		
 		endif;
	endforeach
	;
	?>
</div>
</div>

<?php if ($no_pics>0)
{
echo '<div class="alert alert-error">';
	echo $no_pics . ' spare part has no picture!';
echo '</div>';
} 
?>



<?php include (ROOT.'\module\Inventory\view\inventory\sp_order_form.php'); ?>