<h3>Spare part for:  <?php echo $category->name ?></h3>

<P>
	<a href="<?php echo $this->baseUrl ?>/inventory/spareparts/add">Add new
		spare part</a>
</P>


<form action="<?php echo $this->baseUrl ?>/inventory/search/sparepart"	method="get" enctype="multipart/form-data" id="search">
<table>
	<tr><td><input type="text"	name="query" value="" /><td>
	<td><input type="submit" name="seach" value="search" /></td>
	</tr>
</table>
</form>

<?php

if ($total_spareparts <= 0) {
	
	echo 'No spare part found!';
} else {

	
	
		
	
	echo $total_spareparts . ' spare parts found!';
	if (! is_null ( $paginator )) {
?>
		
	<hr>
<?php	
	echo 'Result '. $paginator->minInPage. ' to '.$paginator->maxInPage;
	}
	?>

<table border="1"  cellpadding="3">
	<tr>
		<td><b>Tag</b></td>
		<td><b>Spare Part Name</b></td>
		<td><b>Code</b></td>
		<td><b>Location</b></td>
		<td><b>Action</b></td>
	</tr>
	 <?php foreach ($spareparts as $a) : ?>
  	
    <tr>
		<td><?php echo $this->escapeHtml($a['tag']);?></td>
		<td><?php echo $this->escapeHtml($a['name']);?></td>
		<td><?php echo $this->escapeHtml($a['code']);?></td>
		<td><?php echo $this->escapeHtml($a['location']);?></td>

		<td>
		<a
			href="<?php echo $this->baseUrl ?>/inventory/spareparts/edit?id=<?php echo $this->escapeHtml($a['id']);?>">Edit
		</a>
		| 
		<a
			href="<?php echo $this->baseUrl ?>/inventory/spareparts/issue?sparepart_id=<?php echo $this->escapeHtml($a['id']);?>">Issue
		</a>
		|
		<a
			href="<?php echo $this->baseUrl ?>/inventory/spareparts/receive?sparepart_id=<?php echo $this->escapeHtml($a['id']);?>">Receive
		</a>
		|
		<a
			href="<?php echo $this->baseUrl ?>/inventory/spareparts/show?id=<?php echo $this->escapeHtml($a['id']);?>">
				Detail </a></td>
	</tr>
<?php endforeach; ?>
</table>

<br>

<?php
	
	if (! is_null ( $paginator )) {
		
		$last = $this->baseUrl . '/inventory/spareparts/list' . '?page=' . $paginator->totalPages . '&perPage=' . $paginator->resultsPerPage;
		
		$first = $this->baseUrl . '/inventory/spareparts/list' . '?page=1&perPage=' . $paginator->resultsPerPage;
		
		
		for($i = $paginator->minInPageSet; $i <= $paginator->maxInPageSet; $i ++) {
			
			$url = $this->baseUrl . '/inventory/spareparts/list' . '?page=' . $i . '&perPage=' . $paginator->resultsPerPage;
			
			$last = $this->baseUrl . '/inventory/spareparts/list' . '?page=' . $paginator->totalPages . '&perPage=' . $paginator->resultsPerPage;
			
			?>

<?php
			
			if ($i == $paginator->page) {
				echo $i;
			} else {
				?>
<a href="<?php echo $url; ?>"><?php echo $i ?></a>

<?php
			}
		}
		?>
	
<a href="<?php echo $last; ?>"> Last</a>
<?php
	}
}
?>

