<h4>Stock Movement</h4>

  <div class="panel-group">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h5 class="panel-title">
          <a data-toggle="collapse" href="#collapse1">Filter</a>
        </h5>
      </div>
      <div id="collapse1" class="panel-collapse collapse <?php echo count($movements)>0?"":"in"?>">
        <div class="panel-body">
        
 <form class="form-horizontal" action="<?php echo $this->baseUrl ?>/inventory/spareparts/showmovement"	method="get" enctype="multipart/form-data" id="ReportForm" >
       <input type="hidden"  placeholder="click to select" name="sparepart_id" value="<?php echo $id?>">
       
      <div class="control-group">
        <label class="control-label" for="inputNameLocal">From Date</label>
        <div class="controls">
          <input type="text" id="start_date" placeholder="click to select" name="start_date" value="">
        </div>
       </div>
  
      <div class="control-group">
        <label class="control-label" for="inputNameLocal">To Date</label>
        <div class="controls">
          <input type="text" id="end_date" placeholder="click to select" name="end_date" value="">
        </div>
      </div>
  
      <div class="control-group">
        <label class="control-label" for="inputNameLocal">Flow</label>
        <div class="controls">
        	<select name="flow" >
        		<option value="ALL">All</option>
   	    		<option value="IN">IN</option>
   	    		<option value="OUT">OUT</option>
   	
   			</select>
	     </div>
      </div>
      
       <div class="control-group">
        <div class="controls">
             <button type="submit" class="btn"><i class="icon-search">  </i> show</button>
        </div>
      </div>
    </form>
        
        
        
        </div>
     </div>
    </div>
  </div>


 



<?php if(count($movements)>0){
	
		echo '<div class="alert alert-info">';
	
		echo '<ul>';
		echo '<li> <strong>' . $total_items . ' </strong> transaction(s) done from <strong>' .$fromDate . '</strong> To <strong>' .$toDate . '</strong></li>';
			echo '<li>Flow		: <strong>' .$flow . '</strong></li>';
	
		echo '</ul>';
		echo '</div>';
		
		if (! is_null ( $paginator )):
		echo '<h5>Result '. $paginator->getMinInPage(). ' to '.$paginator->getMaxInPage() . ' | ' .  $total_items . ' Items found!</h5>';
		else:
		echo '<h5>'. $total_items . ' Items found! </h5>';
		endif;
		
?>
<a href="<?php echo $this->baseUrl ?>/inventory/report/index?start_date=<?php echo $fromDate;?>&end_date=<?php echo $toDate;?>&flow=<?php echo $flow;?>&output=csv"><i class="icon-download-alt">  </i> Download (csv)</a> 
<hr>



<table class="table table-striped table-bordered">

<thead>
	<tr>
		<td><b>Date</b></td>
		<td><b>Tag	</b></td>
		<td><b>Flow</b></td>
		<td><b>Quantity</b></td>
		<td><b>Requester</b></td>
			<td><b>Reason</b></td>
		<td><b>Comment</b></td>
		<td><b>Asset Tag</b></td>	
			
	</tr>
</thead>
<tbody>

<?php 
	

	$count = 0;
	foreach ($movements as $a) :
	 	 $count++;
	// echo  ($count % 2 == 1) ? "<tr>" : "<tr class=\"pure-table-odd\">";
	 	 
	 ?>
	<tr>
		<td><?php echo date_format(date_create($a->movement_date),"Y-m-d");?></td>
		<td><?php echo $a->tag;?></td>
		<td><?php echo $a->flow;?></td>
		<td><?php echo $a->quantity;?></td>
		<td><?php echo $a->requester;?></td>

		<td><?php echo $a->reason;?></td>
		
		<td><?php echo $a->comment;?></td>
		<td><?php echo $a->asset_name;?></td>
			
	</tr>

<?php endforeach; ?>
</tbody>
</table>

<br>
<?php
	
if (! is_null ( $paginator )) {
		
	
	//change it only
	$base=$this->baseUrl . '/inventory/spareparts/showmovement?sparepart_id='.$id.
	
	$_connector_symbol = '&';

	$last 	= $base . $_connector_symbol.'page=' . $paginator->getTotalPages() . '&perPage=' . $paginator->getResultsPerPage();;
	$first 	= $base . $_connector_symbol.'page=1&perPage=' . $paginator->getResultsPerPage();;

	$p1 = ($paginator->getPage())-1;
	$p2 = ($paginator->getPage())+1;

	$prev = $base . $_connector_symbol.'page=' . $p1 . '&perPage=' . $paginator->getResultsPerPage();;
	$next = $base . $_connector_symbol.'page=' . $p2 . '&perPage=' . $paginator->getResultsPerPage();;


	echo '<ul class="pagination">';

	if($paginator->getPage() != 1 AND $paginator->getTotalPages() > 10){
		echo '<li><a href="'.  $first.'"> |< </a></li>';
		echo '<li><a href="'.  $prev .'"> < </a></li>';
	}

	for($i = $paginator->getMinInPageSet(); $i <= $paginator->getMaxInPageSet(); $i ++) {
			
		$url = $base. $_connector_symbol.'page=' . $i . '&perPage=' . $paginator->getResultsPerPage();;

			
		if ($i == $paginator->getPage()) {
			echo   '<li><a class="active" href="#">'.$i.'</a></li>';
		} else {
			echo '<li><a href="'. $url. '"> '. $i. ' </a></li>';
		}
	}
	if($paginator->getPage() != $paginator->getTotalPages() AND $paginator->getTotalPages() > 10){
		echo '<li><a href="'.  $next.'"> > </a></li>';
		echo '<li><a href="'.  $last .'"> >| </a></li>';
	}
	echo '</ul>';
}

?>



<?php }; ?>
