<?php include (ROOT.'\module\Inventory\view\inventory\sp_menu.php'); ?> 


<?php

if ($total_spareparts <= 0) {
	
	echo 'No spare part found!';
} else {
	
	if (! is_null ( $paginator )) {
		echo '<h5>Result ' . $paginator->getMinInPage() . ' to ' . $paginator->getMaxInPage() . ' | ' . $total_spareparts . ' members found! </h5>';
		;
	} else {
		echo '<h5>' . $total_spareparts . ' spare parts found! </h5>';
	}
	?>


<table class="table table-striped table-bordered">
	<thead>
		<tr>
			<td><b>PICTURE</b></td>
			<td><b>TAG</b></td>
			<td><b>SPARE-PART NAME</b></td>
			<td><b data-toggle="tooltip" title="Current Balance">Current <br> Balance</b></td>
			<td><b data-toggle="tooltip" title="Minimum Balance">Minimum <br> Balance</b></td>
			<td><b data-toggle="tooltip" title="Minimum Balance">Remaining<br>To Order</b></td>
			<td><b data-toggle="tooltip" title="Minimum Balance">Suggestion</b></td>
			<td><b>ACTION</b></td>
		</tr>
	</thead>
	<tbody>
	  <?php
	
	$count = 0;
	foreach ( $spareparts as $a ) :
		// $count++;
		// echo ($count % 2 == 1) ? "<tr>" : "<tr class=\"pure-table-odd\">";
		
		?>
	<tr>
			<td>
			<?php 
			if($a->sp_pic_id!==null):
			?>
			<a href="<?php echo $this->baseUrl ?>/inventory/spareparts/show?id=<?php echo $this->escapeHtml($a['id']);?>">
			<img class= "img-rounded" width="90" height="100" src="/inventory/image/sparepartthumbnail200?id=<?php echo $a->sp_pic_id;?>"/>
		</a>			
			<?php 
			else:
			?>
			<img class= "img-rounded" width="70" height="80" src="/images/no-pic.jpg"/>
				
			<?php 
			endif;
			?>
			
			</td>
			
			
			<td><?php echo $this->escapeHtml($a['tag']);?></td>
			<td>

				<div class="dropdown">
					<a style="" class="dropdown-toggle" type="button" data-toggle="dropdown"
						href="#"><span style="color:black;" id="<?php echo $this->escapeHtml($a['id']);?>_name"><b><?php echo $this->escapeHtml($a['name']);?></b></span>
						<span class="caret"></span></a>
					<ul class="dropdown-menu">
						<li><a
							href="<?php echo $this->baseUrl ?>/inventory/spareparts/edit?id=<?php echo $this->escapeHtml($a['id']);?>">Edit</a>
						</li>
						<li><a
							href="<?php echo $this->baseUrl ?>/inventory/spareparts/show?id=<?php echo $this->escapeHtml($a['id']);?>">Detail</a>
						</li>
 						<li class="divider"></li>
 						<li><a
							href="<?php echo $this->baseUrl ?>/inventory/spareparts/upload-picture1?id=<?php echo $this->escapeHtml($a['id']);?>">Upload Picture</a>
						</li>
 	
 							<li class="divider"></li>
 						<li><a
				href="<?php echo $this->baseUrl ?>/inventory/spareparts/showmovement?sparepart_id=<?php echo $this->escapeHtml($a['id']);?>">Stock movement</a>
						</li>
						<li><a
				href="<?php echo $this->baseUrl ?>/inventory/spareparts/set-min-balance?sparepart_id=<?php echo $this->escapeHtml($a['id']);?>">Set Minimum Balance</a>
						</li>
					</ul>
				</div>
				<div style="color: gray;">
					Code: <span id="<?php echo $this->escapeHtml($a['id']);?>_code"><?php echo $this->escapeHtml($a['code']);?></span><br>
					Location: <?php echo $this->escapeHtml($a['location']);?>
				<div style="color: gray;">
				Category:<a style="font-size 8pt;color: black;" href="<?php echo $this->baseUrl ?>/inventory/spareparts/show-category?id=<?php echo $this->escapeHtml($a['sparepart_cat_id']);?>" target="_blank"><?php echo $this->escapeHtml($a['cat_name']);?></a>
				</div>
				</div>

			</td>
			<td ><a href="<?php echo $this->baseUrl ?>/inventory/spareparts/showmovement?sparepart_id=<?php echo $this->escapeHtml($a['id']);?>">
			
			<span id="<?php echo $this->escapeHtml($a['id']);?>_current_balance"><?php echo $a->current_balance;?></span>
			
			
		</a></td>
			<td ><a href="<?php echo $this->baseUrl ?>/inventory/spareparts/set-min-balance?sparepart_id=<?php echo $this->escapeHtml($a['id']);?>">
			
			<span id="<?php echo $this->escapeHtml($a['id']);?>_min_balance"><?php echo $a->minimum_balance;?></span>
			
		</a></td>
<td ><?php echo $a->remaining_to_order;?>
		</td>
		<td >
		<?php
		
		if($a->remaining_to_order <=0):
			//echo '<div class="alert alert-danger" role="alert">Order now!</div>';
		echo '<span  class="label label-warning">Please order !</span>';
		else:
		
		endif;
		?>
		
		
		</td>

			<td><a href="#"
				onclick="openPRCart('<?php echo $this->escapeHtml($a['id'])?>');"><i
					class="icon-shopping-cart"></i>Order</a> <a
				href="<?php echo $this->baseUrl ?>/inventory/spareparts/issue?sparepart_id=<?php echo $this->escapeHtml($a['id']);?>">Issue
			</a> <a
				href="<?php echo $this->baseUrl ?>/inventory/spareparts/receive?sparepart_id=<?php echo $this->escapeHtml($a['id']);?>">Receive
			</a> 
			</td>
			</tr>
<?php endforeach; ?>
</tbody>
</table>

<br>

<?php
	
	if (! is_null ( $paginator )) {
		
		// change it only
		$base = $this->baseUrl . '/inventory/spareparts/suggest';
		
		$_connector_symbol = '?';
		
		$last = $base . $_connector_symbol . 'page=' . $paginator->getTotalPages() . '&perPage=' . $paginator->getResultsPerPage();;
		$first = $base . $_connector_symbol . 'page=1&perPage=' . $paginator->getResultsPerPage();;
		
		$p1 = ($paginator->getPage()) - 1;
		$p2 = ($paginator->getPage()) + 1;
		
		$prev = $base . $_connector_symbol . 'page=' . $p1 . '&perPage=' . $paginator->getResultsPerPage();;
		$next = $base . $_connector_symbol . 'page=' . $p2 . '&perPage=' . $paginator->getResultsPerPage();;
		
		echo '<ul class="pagination">';
		
		if ($paginator->getPage() != 1 and $paginator->getTotalPages() > 10) {
			echo '<li><a href="' . $first . '"> |< </a></li>';
			echo '<li><a href="' . $prev . '"> < </a></li>';
		}
		
		for($i = $paginator->getMinInPageSet(); $i <= $paginator->getMaxInPageSet(); $i ++) {
			
			$url = $base . $_connector_symbol . 'page=' . $i . '&perPage=' . $paginator->getResultsPerPage();;
			
			if ($i == $paginator->getPage()) {
				echo '<li><a class="active" href="#">' . $i . '</a></li>';
			} else {
				echo '<li><a href="' . $url . '"> ' . $i . ' </a></li>';
			}
		}
		if ($paginator->getPage() != $paginator->getTotalPages() and $paginator->getTotalPages() > 10) {
			echo '<li><a href="' . $next . '"> > </a></li>';
			echo '<li><a href="' . $last . '"> >| </a></li>';
		}
		echo '</ul>';
	}
}
?>



<?php include (ROOT.'\module\Inventory\view\inventory\sp_order_form.php'); ?>