 <div class="btn-group">
    <button type="button" class="btn btn-defaultdropdown-toggle" data-toggle="dropdown">
    Spare-Part Management <span class="caret"></span></button>
    <ul class="dropdown-menu" role="menu">
 				<li><a href="/inventory/spareparts/category">Spare-part category</a>
						</li>
						<li><a href="/inventory/spareparts/list">Show all spare-parts</a>
						</li>
						<li class="divider"></li>
 						<li><a href="/inventory/report/index">Reporting</a>
						</li>
			
    </ul>
  </div>
  
  
 
<hr>
 <form class="form-search" action="<?php echo $this->baseUrl ?>/inventory/search/sparepart"	method="get" enctype="multipart/form-data">
      <input type="text" name = "query" class="">
      <button type="submit" class="btn"><i class="icon-search">  </i>Search</button>
   </form>
<ul class="nav nav-pills">
	<li><a
		href="<?php echo $this->baseUrl ?>/inventory/spareparts/add">Add
			New Spare-part</a></li>
			
			<li><a href="<?php echo $this->baseUrl ?>/inventory/spareparts/list?output=csv"><i class="icon-download-alt">  </i> Download (csv)</a> 
</li>
</ul>



<?php

if ($total_spareparts <= 0) {
	
	echo 'No spare part found!';
} else {
	
	if (! is_null ( $paginator )) {
		echo '<h5>Result ' . $paginator->minInPage . ' to ' . $paginator->maxInPage . ' | ' . $total_spareparts . ' members found! </h5>';
		;
	} else {
		echo '<h5>' . $total_spareparts . ' spare parts found! </h5>';
	}
	?>


<table class="table table-striped table-bordered">
	<thead>
		<tr>
			<td><b>PICTURE</b></td>
			<td><b>TAG</b></td>
			<td><b>SPARE-PART NAME</b></td>
			<td><b data-toggle="tooltip" title="Current Balance">Current <br> Balance</b></td>
			<td><b data-toggle="tooltip" title="Minimum Balance">Minimum <br> Balance</b></td>
			<td><b data-toggle="tooltip" title="Minimum Balance">Remaining<br>To Order</b></td>
			<td><b data-toggle="tooltip" title="Minimum Balance">Suggestion</b></td>
			<td><b>ACTION</b></td>
		</tr>
	</thead>
	<tbody>
	  <?php
	
	$count = 0;
	foreach ( $spareparts as $a ) :
		// $count++;
		// echo ($count % 2 == 1) ? "<tr>" : "<tr class=\"pure-table-odd\">";
		
		?>
	<tr>
			<td>
			<?php 
			if($a->sp_pic_id!==null):
			?>
			<a href="<?php echo $this->baseUrl ?>/inventory/spareparts/show?id=<?php echo $this->escapeHtml($a['id']);?>">
			<img class= "img-rounded" width="90" height="100" src="/inventory/image/sparepartthumbnail200?id=<?php echo $a->sp_pic_id;?>"/>
		</a>			
			<?php 
			else:
			?>
			<img class= "img-rounded" width="70" height="80" src="/images/no-pic.jpg"/>
				
			<?php 
			endif;
			?>
			
			</td>
			
			
			<td><?php echo $this->escapeHtml($a['tag']);?></td>
			<td>

				<div class="dropdown">
					<a style="" class="dropdown-toggle" type="button" data-toggle="dropdown"
						href="#"><span style="color:black;" id="<?php echo $this->escapeHtml($a['id']);?>_name"><b><?php echo $this->escapeHtml($a['name']);?></b></span>
						<span class="caret"></span></a>
					<ul class="dropdown-menu">
						<li><a
							href="<?php echo $this->baseUrl ?>/inventory/spareparts/edit?id=<?php echo $this->escapeHtml($a['id']);?>">Edit</a>
						</li>
						<li><a
							href="<?php echo $this->baseUrl ?>/inventory/spareparts/show?id=<?php echo $this->escapeHtml($a['id']);?>">Detail</a>
						</li>
 						<li class="divider"></li>
 						<li><a
							href="<?php echo $this->baseUrl ?>/inventory/spareparts/upload-picture1?id=<?php echo $this->escapeHtml($a['id']);?>">Upload Picture</a>
						</li>
 	
 							<li class="divider"></li>
 						<li><a
				href="<?php echo $this->baseUrl ?>/inventory/spareparts/showmovement?sparepart_id=<?php echo $this->escapeHtml($a['id']);?>">Stock movement</a>
						</li>
						<li><a
				href="<?php echo $this->baseUrl ?>/inventory/spareparts/set-min-balance?sparepart_id=<?php echo $this->escapeHtml($a['id']);?>">Set Minimum Balance</a>
						</li>
					</ul>
				</div>
				<div style="color: gray;">
					Code: <span id="<?php echo $this->escapeHtml($a['id']);?>_code"><?php echo $this->escapeHtml($a['code']);?></span><br>
					Location: <?php echo $this->escapeHtml($a['location']);?>
				<div style="color: gray;">
				Category:<a style="font-size 8pt;color: black;" href="<?php echo $this->baseUrl ?>/inventory/spareparts/show-category?id=<?php echo $this->escapeHtml($a['sparepart_cat_id']);?>" target="_blank"><?php echo $this->escapeHtml($a['cat_name']);?></a>
				</div>
				</div>

			</td>
			
			<td ><a href="<?php echo $this->baseUrl ?>/inventory/spareparts/showmovement?sparepart_id=<?php echo $this->escapeHtml($a['id']);?>"><?php echo $a->current_balance;?>
		</a></td>
			<td ><a href="<?php echo $this->baseUrl ?>/inventory/spareparts/set-min-balance?sparepart_id=<?php echo $this->escapeHtml($a['id']);?>"><?php echo $a->minimum_balance;?>
		</a></td>
<td ><?php echo $a->remaining_to_order;?>
		</td>
		<td >
		<?php
		
		if($a->remaining_to_order <=0):
			//echo '<div class="alert alert-danger" role="alert">Order now!</div>';
		echo '<span  class="label label-warning">Please order !</span>';
		else:
		
		endif;
		?>
		
		
		</td>

			<td><a href="#"
				onclick="openPRCart('<?php echo $this->escapeHtml($a['id'])?>');"><i
					class="icon-shopping-cart"></i>Order</a> <a
				href="<?php echo $this->baseUrl ?>/inventory/spareparts/issue?sparepart_id=<?php echo $this->escapeHtml($a['id']);?>">Issue
			</a> <a
				href="<?php echo $this->baseUrl ?>/inventory/spareparts/receive?sparepart_id=<?php echo $this->escapeHtml($a['id']);?>">Receive
			</a> 
			</td>
			</tr>
<?php endforeach; ?>
</tbody>
</table>

<br>

<?php
	
	if (! is_null ( $paginator )) {
		
		// change it only
		$base = $this->baseUrl . '/inventory/spareparts/list';
		
		$_connector_symbol = '?';
		
		$last = $base . $_connector_symbol . 'page=' . $paginator->totalPages . '&perPage=' . $paginator->resultsPerPage;
		$first = $base . $_connector_symbol . 'page=1&perPage=' . $paginator->resultsPerPage;
		
		$p1 = ($paginator->page) - 1;
		$p2 = ($paginator->page) + 1;
		
		$prev = $base . $_connector_symbol . 'page=' . $p1 . '&perPage=' . $paginator->resultsPerPage;
		$next = $base . $_connector_symbol . 'page=' . $p2 . '&perPage=' . $paginator->resultsPerPage;
		
		echo '<ul class="pagination">';
		
		if ($paginator->page != 1 and $paginator->totalPages > 10) {
			echo '<li><a href="' . $first . '"> |< </a></li>';
			echo '<li><a href="' . $prev . '"> < </a></li>';
		}
		
		for($i = $paginator->minInPageSet; $i <= $paginator->maxInPageSet; $i ++) {
			
			$url = $base . $_connector_symbol . 'page=' . $i . '&perPage=' . $paginator->resultsPerPage;
			
			if ($i == $paginator->page) {
				echo '<li><a class="active" href="#">' . $i . '</a></li>';
			} else {
				echo '<li><a href="' . $url . '"> ' . $i . ' </a></li>';
			}
		}
		if ($paginator->page != $paginator->totalPages and $paginator->totalPages > 10) {
			echo '<li><a href="' . $next . '"> > </a></li>';
			echo '<li><a href="' . $last . '"> >| </a></li>';
		}
		echo '</ul>';
	}
}
?>


<!-- Modal -->
<div id="myModal" class="modal hide" role="dialog">
	<div class="modal-dialog">
		<div class="modal-header">
			<button type="button" class="close" data-dismiss="modal">&times;</button>
			<h5 class="modal-title">Mascot International (Laos)</h5>
		</div>
		<div class="modal-body">
			<span id="_status"></span>

			<form class="form-horizontal"
				action="<?php echo $this->baseUrl ?>/procurement/pr/select-item-2"
				method="post" enctype="multipart/form-data" id="NewSP">
				<input type="hidden" name="redirectUrl"
					value="<?php echo $redirectUrl ?>" /> <input type="hidden"
					name="article_id" id="item_id" value="" />

				<div class="control-group">
					<label class="control-label" for="inputNameLocal">Priority:</label>
					<div class="controls">
						<select name="priority" id="item_priority">
							<option value="Low">Low</option>
							<option value="Medium" selected>Medium</option>
							<option value="High">High</option>
							<option value="Urgent">Urgent</option>
						</select>
					</div>
				</div>

				<div class="control-group">
					<label class="control-label" for="inputTag">Name:</label>
					<div class="controls">
						<input type="text" id="item_name" placeholder="" name="name"
							value="article">
					</div>
				</div>
	
				<div class="control-group">
					<label class="control-label" for="inputTag">Code:</label>
					<div class="controls">
						<input type="text" id="item_code" placeholder="" name="code"
							value="">
					</div>
				</div>
				
				<div class="control-group">
					<label class="control-label" for="inputTag">Unit:</label>
					<div class="controls">
						<input type="text" id="item_unit" placeholder="" name="unit"
							value="">
					</div>
				</div>
				

				<div class="control-group">
					<label class="control-label" for="inputTag">Quantity:</label>
					<div class="controls">
						<input type="text" id="item_quantity" placeholder=""
							name="quantity" value="">
					</div>
				</div>

				<div class="control-group">
					<label class="control-label" for="inputNameLocal">Requested
						Delivery Date:</label>
					<div class="controls">
						<input type="text" id="end_date" placeholder="click to select"
							name="EDT" value="">
					</div>
				</div>

				<div class="control-group">
					<label class="control-label" for="inputDescription">Reason /Note:</label>
					<div class="controls">
						<textarea id="item_remarks" placeholder="" rows="2" cols="5"
							name="remarks"></textarea>
					</div>
				</div>
			</form>
		</div>

		<div class="modal-footer">
			<button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
			<button onclick="addItemToCart('SPARE-PART');" type="button"
				class="btn btn-primary">Add To Cart</button>
		</div>
	</div>
</div>

<!-- Modal -->
<div id="myModal1" class="modal hide" role="dialog">
	<div class="modal-dialog">
		<div class="modal-body">
			<p>Working on it........Please Wait!</p>
		</div>
	</div>
</div>