<h4><i class="icon-upload">  </i> Upload picture:</h4>

<?php if ($sparepart!==null)
{
echo '<div class="alert alert-info">';
	
	 echo '<ul>';
	 echo '<li>Sparepart Name	: <strong>' .$sparepart->name . '</strong></li>';
	 echo '<li>Sparepart Tag	: <strong>' .$sparepart->tag . '</strong></li>';
	 echo '<li>Code		: <strong>' .$sparepart->code . '</strong></li>';
	 
	 echo '</ul>';
	 echo '</div>';
} 
?>
	

 <form class="form-horizontal" id="sp_upload_pic_form" action="<?php echo $this->baseUrl ?>/inventory/spareparts/upload-picture"	method="post" enctype="multipart/form-data" id="NewSP" >
 <input type="hidden" name="redirectUrl" value="<?php echo $redirectUrl ?>" />
 <input type="hidden" name="id" value="<?php echo $sparepart!==null ? ($sparepart->id) :""?>"/>
      
      <div class="control-group">
        <label class="control-label" for="inputLocation">Pictures:</label>
        <div class="controls">
        <input type="file" name="pictures[]" /><br>
   		<input type="file" name="pictures[]" /><br>
		<input type="file" name="pictures[]" /><br>
		<input type="file" name="pictures[]" /><br>
   		<input type="file" name="pictures[]" /><br>
		<input type="file" name="pictures[]" /><br>

        </div>
      </div>
      
      <div class="control-group">
        <div class="controls">
             <button type="submit" class="btn"><i class="icon-upload">  </i> Upload</button>
        </div>
      </div>
    </form>


