
<div id="tabs" style="font-size: 9.5pt">
   <ul>
      <li>
         <a href="#general">search result</a>
      </li>
   </ul>
   <div id="general">
      <form class="form-inline" action="<?php
    echo $this->baseurl?>/procure/po-search/do" method="get" enctype="multipart/form-data">
         <div class="form-group" style="padding-left: 8px;">
            <input placeholder="<?php

            echo $this->translate("enter search term ...")?>" class="form-control" size="25" type="text" name="q">
         </div>
         <div class="form-group">
            <button type="submit" class="btn btn-default">
               <small>
                  <i class="glyphicon glyphicon-search"> </i>
               </small>
            </button>
         </div>
      </form>
      <hr>


<?php
echo '<span>';
echo $message;
echo '</span>';

if (! $hits == null) :

    ?>
<table style="font-size: 9.5pt;" class="table table-hover table-bordered">
         <thead>
            <tr>
               <td>
                  <b>#</b>
               </td>
               <td>
                  <b>doc id</b>
               </td>
               <td>
                  <b>#</b>
               </td>
               <td>
                  <b>vendor id</b>
               </td>
               <td>
                  <b>po#</b>
               </td>
               <td>
                  <b>po</b>
               </td>
               <td>
                  <b>item id</b>
               </td>
               <td>
                  <b>item sku</b>
               </td>
               <td>
                  <b>item</b>
               </td>
               <td>
                  <b>row name</b>
               </td>
               <td>
                  <b>code</b>
               </td>
               <td>
                  <b>quantity</b>
               </td>
               <td>
                  <b>
                     po
                     <br>
                     unit
                  </b>
               </td>
               <td>
                  <b>
                     conversion
                     <br>
                     factor
                  </b>
               </td>
               <td>
                  <b>action</b>
               </td>
            </tr>
         </thead>
         <tbody>

	 <?php

    $count = 0;
    foreach ($hits as $hit) :
        $count ++;
        ?>
	 <tr>
               <td> <?php

        echo $count;
        ?></td>
               <td>
                  <span id=""><?php

        echo $this->escapehtml($hit->id);
        ?></span>
               </td>
               <td>
                  <span id=""><?php

        echo round($hit->score * 100, 0) . '%';
        ?></span>
               </td>
               <td>
                  <span id=""><?php

        echo $this->escapehtml($hit->vendor_id);
        ?></span>
               </td>
               <td>
                  <span id=""><?php

        echo $this->escapehtml($hit->po_row_id);
        ?></span>
               </td>
               <td>
                  <a style="color: navy;" href="<?php

        echo $this->baseurl?>/procure/po/view?entity_token=<?php

        echo $hit->po_token;
        ?>&entity_id=<?php

        echo $hit->po_id;
        ?>">
               <?php

        echo $this->escapehtml($hit->po_number);
        ?></a>
               </td>
               <td>
                  <a style="color: navy;" href="<?php

        echo $this->baseurl?>/procure/po/show?token=<?php

        echo $hit->po_token;
        ?>&entity_id=<?php

        echo $hit->po_id;
        ?>">
					<?php

        echo $this->escapehtml($hit->po_number);
        ?></a>
               </td>
               <td>
                  <span id="">
                     <a style="color: navy;" target="_blank" href="<?php

        echo $this->baseurl?>/inventory/item/show?token=<?php

        echo $hit->item_token;
        ?>&entity_id=<?php

        echo $hit->item_id;
        ?></a>
                  </span>
               </td>
               <td>
                  <span id=""><?php

        echo $this->escapehtml($hit->item_sku_key);
        ?></span>
               </td>
               <td>
                  <span id=""><?php

        echo $this->escapehtml($hit->item_name);
        ?></span>
               </td>
               <td>
                  <span id=""><?php

        echo $this->escapehtml($hit->row_name);
        ?></span>
               </td>
               <td>
                  <span id=""></span>
               </td>
               <td>
                  <span id=""><?php

        echo $this->escapehtml($hit->row_quantity);
        ?></span>
               </td>
               <td>
                  <span id=""><?php

        echo $this->escapehtml($hit->row_unit);
        ?></span>
               </td>
               <td>
                  <span id=""><?php

        echo $this->escapehtml($hit->row_conversion_factor);
        ?></span>
               </td>
               <td>
                 
                
                
               </td>
            </tr>
<?php
    endforeach
    ;
    ?>
</tbody>
      </table>
<?php endif;

?>
</div>
</div>
