
<ul class="nav nav-pills">
	<li><a href="<?php echo $this->baseUrl ?>/pm/project/list">Project List</a></li>
</ul>

<form class="form-inline"
	action="<?php echo $this->baseUrl ?>/pm/project-search/do" method="get"
	enctype="multipart/form-data">
	<div class="form-group">
		<input class="form-control" size="28" type="text" name="q" class="">
	</div>
	<div class="form-group">
		<button type="submit" class="btn btn-default">
			<small><i class="glyphicon glyphicon-search"> </i></small> Search
		</button>
	</div>

</form>


<?php
echo '<hr>';
echo '<span>';
echo $message;
echo '</span>';

if (! $hits == null) :
	
	?>
<table style="font-size: 10pt;" class="table table-hover table-bordered">
	<thead>
		<tr>
			<td><b>#</b></td>
			<td><b>Project Name</b></td>
			<td><b>Keywords</b></td>
			<td><b>Action</b></td>
		</tr>
	</thead>
	<tbody>

	 <?php
	
	$count = 0;
	foreach ( $hits as $hit ) :
		$count ++;
		// echo ($count % 2 == 1) ? "<tr>" : "<tr class=\"pure-table-odd\">";
		
		?>
	 <tr>

			<td> <?php echo $count;?></td>
			<td><span id=""><?php echo $this->escapeHtml($hit->project_name);?></span></td>
			<td><span id=""><?php echo $this->escapeHtml($hit->keywords);?></span></td>
			<td>
<a href="<?php echo $this->baseUrl ?>/pm/project/show?token=<?php echo $hit->token;?>&entity_id=<?php echo $hit->project_id;?>&checksum=<?php echo $hit->checksum;?>">Show</a>
<a href="<?php echo $this->baseUrl ?>/pm/project/edit?token=<?php echo $hit->token;?>&entity_id=<?php echo $hit->project_id;?>&checksum=<?php echo $hit->checksum;?>">Edit</a>
			</td>
		</tr>
<?php endforeach; ?>
</tbody>
</table>


<?php endif; ?>
