
<?php /**@var \Application\Entity\FinVendorInvoice $target ;*/ ?>

<a class="btn btn-default"
	href="<?php echo $this->baseUrl ?>/finance/v-invoice-attachment/upload-pictures?token=<?php echo (!$target== null)? $target->getToken():"";?>&target_id=<?php echo (!$target== null)? $target->getID():"";?>"><small><i
		class="fa fa-upload" aria-hidden="true"></i>&nbsp;</small>&nbsp;Upload
	picture</a>

<hr>


<?php if( count($list)>0): ?>

<div id="picture" style="padding: 10pt">
	<div id="lightgallery">
		 <?php foreach ($list as $pic) : ?>
	    <a
			href="/finance/v-invoice-attachment/picture?id=<?php  echo $this->escapeHtml($pic->getId());?>&checksum=<?php  echo $this->escapeHtml($pic->getCheckSum());?>&token=<?php  echo $this->escapeHtml($pic->getToken());?>">
			<img class="img-rounded" width="150" height="150"
			src="/finance/v-invoice-attachment/thumbnail200?id=<?php  echo $this->escapeHtml($pic->getId());?>&checksum=<?php  echo $this->escapeHtml($pic->getCheckSum());?>&token=<?php  echo $this->escapeHtml($pic->getToken());?>" />
		</a>
	<?php endforeach; ?>
	 </div>
</div>

<?php else:?>
No record found!
<?php endif; ?>




<script>

$("#lightgallery").lightGallery({});

</script>