<h4>
	<a href="/hr/setting/index"><i class="fa fa-cog" aria-hidden="true"></i> <?php echo $this->translate('HR SETTING'); ?></a>
</h4>
<div id="tabs" style="font-size: 9.5pt">

	<ul>
		<li><a href="#general"><?php echo $this->translate('Minimum Wage Management'); ?></a></li>
	</ul>
	<div id="general" style="font-size: 9pt">

		<hr>
		<table style="font-size: 9pt;"
			class="table table-bordered table-hover">
			<thead>
				<tr>
					<td><b>#</b></td>
					<td><b><?php echo $this->translate('Minimum Wage'); ?></b></td>
					<td><b><?php echo $this->translate('Currency'); ?></b></td>
					<td><b><?php echo $this->translate('Effective from'); ?></b></td>
					<td><b><?php echo $this->translate('Effective to'); ?></b></td>
					<td><b><?php echo $this->translate('Status'); ?></b></td>
					<td><b><?php echo $this->translate('Action'); ?></b></td>
				</tr>
			</thead>

			<tbody>

				<tr>
					<td>0</td>
					<td>625.000</td>
					<td>LAK</td>
					<td>01/01/2013</td>
					<td>01/04/2015</td>
					<td><?php echo $this->translate('Inactive'); ?></td>
					<td><a style="color: navy" href="#"><?php echo $this->translate('Show'); ?></a></td>
				</tr>
				<tr>
					<td>1</b></td>
					<td>900.000</td>
					<td>LAK</td>
					<td>01/04/2015</td>
					<td></td>
					<td><?php echo $this->translate('Active'); ?></td>
					<td><a style="color: navy" href="#"><?php echo $this->translate('Show'); ?></a>
						| <a style="color: navy" href="#"><?php echo $this->translate('Update'); ?></a></b></td>
				</tr>
			</tbody>
			</tbody>
		</table>


	</div>
</div>
