<?php /**@var \Application\Entity\NmtProcureQo $target ;*/ ?>
<?php $attachment_url =  $this->baseUrl . '/procure/quote-attachment' ;?>

<a class="btn btn-default" href="<?php echo $attachment_url ?>/upload-pictures?token=<?php echo (!$target== null)? $target->getToken():"";?>&target_id=<?php echo (!$target== null)? $target->getID():"";?>"><small><i class="fa fa-upload" aria-hidden="true"></i>&nbsp;</small>&nbsp;Upload picture</a>
   
<hr>


<?php if( count($list)>0): ?>

<div id="picture" style="padding: 9.5pt">
	<div id="lightgallery1">
		 <?php foreach ($list as $pic) : ?>
	    <a href="<?php echo $attachment_url ?>/picture?id=<?php  echo $this->escapeHtml($pic->getId());?>&checksum=<?php  echo $this->escapeHtml($pic->getCheckSum());?>&token=<?php  echo $this->escapeHtml($pic->getToken());?>">
	    <img class= "img-rounded" width="150" height="150" src="<?php echo $attachment_url ?>/thumbnail200?id=<?php  echo $this->escapeHtml($pic->getId());?>&checksum=<?php  echo $this->escapeHtml($pic->getCheckSum());?>&token=<?php  echo $this->escapeHtml($pic->getToken());?>"/>
	    </a>
	<?php endforeach; ?>
	 </div>
</div>

<?php else:?>
No record found!
<?php endif; ?>




<script>

$("#lightgallery1").lightGallery({});

</script>