<?php echo $this->doctype(); ?>

<html lang="en">
<head>
<meta charset=" ISO 8859-1">
        <?php echo $this->headTitle('Mascot International (Lao) Sole co., Ltd')?>

        <?php echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0')?>
</head>

<body>
	
	<div class="container">
            <?php echo $this->content; ?>
            <hr>
		<footer>
			<p>Email: nmt@mascot.dk</p>
		</footer>
	</div>
	<!-- /container -->
        <?php echo $this->inlineScript()?>
    </body>

</html>
