<div id="tabs" style="font-size: 9.5pt">

	<ul>
		<li><a href="#general">DASHBOARD</a></li>
	</ul>
	<div id="general">


		<div class="row">
			<div class="col-sm-4" style="">

				
				<div class="panel panel-info">
					<div class="panel-heading"><strong>Recent Created Items</strong></div>
					<div class="panel-body" style="padding: 0px;">
						<div id="last_created_items_containter" style=""></div>
					</div>
				</div>

			
			</div>


			<div class="col-sm-4">
			<div class="panel panel-default">
					<div class="panel-heading"><strong>Most Order Items</strong></div>
					<div class="panel-body" style="padding: 0px;">
						<div id="most_order_items_containter" style=""></div>
					</div>
				</div>
				
			
				<div class="panel panel-warning">
					<div class="panel-heading">Recent Ordered Items</div>
					<div class="panel-body" style="padding: 0px;">
						<div id="last_created_items_containter" style=""></div>
					</div>
				</div>

			</div>
			<div class="col-sm-4">
				<div class="panel panel-success">
					<div class="panel-heading"><strong>Calendar</strong></div>
					<div class="panel-body" style="padding: 0px;">
						<div id="calendar_containter" style=""></div>
					</div>
				</div>
			</div>
		</div>


	</div>
</div>

<script>
	doPaginator('/inventory/dashboard/most-order-items','most_order_items_containter');
	doPaginator('/inventory/dashboard/last-created-items','last_created_items_containter');
	doPaginator('/calendar/index/month1','calendar_containter');
	
</script>