<div style="padding: 2px; font-size: 9.5pt;">

		<div class="row">
			<div class="col-sm-4" style="">
			
			<div class="panel panel-default">
					<div style="height: 28px;padding:5px" class="panel-heading"><strong>Random Item</strong></div>
					<div class="panel-body" style="padding: 2px;">
						<div id="random_item_containter" style="height: 230px;">
						</div>
					</div>
				</div>
			
			<div class="panel panel-info">
					<div  style="height: 28px;padding:5px" class="panel-heading"><strong>Most Valuable Items</strong></div>
					<div class="panel-body" style="padding: 2px;">
						<div id="most_value_items_container" style="">							
						</div>
					</div>
				</div>
				</div>


			<div class="col-sm-4">
			
			<div class="panel panel-default">
					<div style="height: 28px;padding:5px" class="panel-heading"><strong>Recent Created Items</strong></div>
					<div class="panel-body" style="padding: 2px;">
						<div id="last_created_items_containter" style=""></div>
					</div>
				</div>
			
			<div class="panel panel-default">
					<div style="height: 28px;padding:5px" class="panel-heading"><i class="fa fa-truck" aria-hidden="true"></i> 
					<strong><?php echo $this->translate('Recently received items');?></strong></div>
					<div class="panel-body" style="padding: 2px;">
						<div id="recent_received_items_containter" style=""></div>
					</div>
				</div>
			
				
			
				<div class="panel panel-warning">
					<div style="height: 28px;padding:5px" class="panel-heading"><i class="fa fa-shopping-cart" aria-hidden="true"></i>
					 <strong>Recent Ordered Items</strong></div>
					<div class="panel-body" style="padding:2px;">
						<div id="last_ordered_items_containter" style=""></div>
					</div>
				</div>

			</div>
			<div class="col-sm-4">
				<div class="panel panel-primary">
					<div style="height: 28px;padding:5px" class="panel-heading"><i class="fa fa-calendar" aria-hidden="true"></i> <strong>Calendar</strong></div>
					<div class="panel-body" style="padding:0px;">
						<div id="calendar_containter" style=""></div>
					</div>
				</div>
				
				<div class="panel panel-success">
					<div style="height: 28px;padding:5px" class="panel-heading"><i class="fa fa-shopping-cart" aria-hidden="true"></i>
					 <strong>Most Order Items</strong></div>
					<div class="panel-body" style="padding: 1px;">
						<div id="most_order_items_containter" style=""></div>
					</div>
				</div>
				
			</div>
		</div>



<script>
	doPaginator('/inventory/dashboard/random-item','random_item_containter');
	doPaginator('/inventory/dashboard/most-order-items','most_order_items_containter');
	doPaginator('/inventory/dashboard/last-created-items','last_created_items_containter');
	doPaginator('/calendar/index/month1','calendar_containter');
	doPaginator('/inventory/dashboard/last-ordered-items','last_ordered_items_containter');
	doPaginator('/inventory/dashboard/last-received-items','recent_received_items_containter');
	doPaginator('/inventory/dashboard/most-value-items','most_value_items_container');
	
		
</script>

</div>