<?php 
/** @var \Application\Entity\NmtInventoryItemPicture $entity ; */ 
?>

<div id="ramdom-item" style="height: 280; padding:2px;">
   <img class= "img-rounded" width="180" height="180" src="/inventory/item-picture/thumbnail200?token=<?php echo $entity->getToken();?>&entity_id=<?php  echo $entity->getId();?>&checksum=<?php echo $entity->getChecksum();?>"/>
<?php 
if ($entity->getItem() !== null) {
    if (strlen($entity->getItem()->getItemName()) < 35) {
        echo sprintf('<div><a target ="_blank" title="%s" href="%s" style="color:gray">%s // %s</a></div>',
            $entity->getItem()->getSysNumber() . '<br>' . $entity->getItem()->getItemName(),
            '/inventory/item/show?token='.$entity->getItem()->getToken().'&entity_id='.$entity->getItem()->getId(), 
            $entity->getItem()->getItemName(),
            $entity->getItem()->getItemSku());
    } else {
        
        echo sprintf('<div><a target ="_blank" title="%s" href="%s" style="color:gray">%s // %s</a></div>',
            $entity->getItem()->getSysNumber() . '<br>' . $entity->getItem()->getItemName(),
            '/inventory/item/show?token='.$entity->getItem()->getToken().'&entity_id='.$entity->getItem()->getId(),
            substr($entity->getItem()->getItemName(), 0, 35).'...',
            $entity->getItem()->getItemSku());
      }
}
?>
<a class="" style="color: navy" href="javascript:;" onclick="doPaginator('/inventory/dashboard/random-item','random_item_containter');">Next&nbsp;<i class="fa fa-caret-right" aria-hidden="true"></i></a>	

</div>