<?php                /** @var \Application\Entity\NmtInventoryItemPicture $entity ; */ ?>
<div id="ramdom-item" style="min-height: 280;">
	    <img class= "img-rounded" width="180" height="180" src="/inventory/item-picture/thumbnail200?token=<?php echo $entity->getToken();?>&entity_id=<?php  echo $entity->getId();?>&checksum=<?php echo $entity->getChecksum();?>"/>
<br><?php echo $entity->getItem()->getItemName();?>

</div>