<?php /**@var \Application\Entity\NmtProcureGr $entity ;*/?>
<?php /**@var \Application\Entity\NmtProcurePo $source ;*/?>

<?php
if (count ( $errors ) > 0) {
	echo '<div class="alert alert-danger" role="alert" style="font-size: 10.5pt">';
	
	echo '<ul>';
	foreach ( $errors as $error ) :
		echo '<li>' . $error . '</li>';
	endforeach
	;
	echo '</ul>';
	echo '</div>';
}
?>

<div id="tabs" style="font-size: 11pt">
	<ul>
		<li><a href="#general">Goods Receipt from Contract/PO: <?php if($source!==null): echo $source->getSysNumber(); endif;?></a></li>
	</ul>

	<div id="general" style="font-size: 9pt">
	<!-- Tab1 -->
	
  <div class="row">
  <!-- ROW -->
  
  <div class="col-xs-5 col-md-2" style="padding: 1px">
  <!-- C1 -->
  					<?php 
    					$current_step="STEP1";
    					include (ROOT.'/module/Procure/view/procure/gr-create-wizard.php');
  					?>
  					
  					<div class="alert alert-info" role="alert" style="padding:1px; font-size: 9pt">
					<ul style="font-size: 9pt">
						<li>Update GR date!</li>
					 	<li>Update quantity to be received!</li>
		                <li>Post the receipt!</li>
		      		</ul>	
					</div>
					
					<div class="alert alert-warning" role="alert" style="padding:1px; font-size: 9pt">
						Document can't be changed when posted!
					</div>
  <!-- C1 ends-->	
  </div>
  
  <div class="col-xs-12 col-sm-6 col-md-10" style="padding: 2px">
  <!-- C2 -->
  
  <?php if($entity !== null): ?>
  
		<form id="Create_Inv_Form" class="form-horizontal"
			action="/procure/gr/copy-from-po" method="post" enctype="multipart/form-data">
			<input type="hidden" name="redirectUrl" value="<?php echo $redirectUrl ?>" />
			<input type="hidden" name="source_id" value="<?php if($source!==null): echo $source->getId(); endif;?>" />
			<input type="hidden" name="source_token" value="<?php if($source!==null): echo $source->getToken(); endif;?>" />
				
				<fieldset>
				<legend style="font-size: 9.5pt; color: gray;">
					<small><span class="glyphicon glyphicon-triangle-right"></span></small>&nbsp;
					<a href="#invoice_header" class="" data-toggle="collapse">HEADER:</a>
				</legend>
				<div id="invoice_header" class="collapse in">
				
				<div class="form-group margin-bottom">
						<label class="control-label col-sm-2">Doc.No</label>
						<div class="col-sm-3">
							<input readonly="readonly" class="form-control input-sm" type="text" placeholder=""
								id="sysNumber" name="sysNumber" 
								value="<?php echo (!$entity == null)? $entity->getSysNumber():"";?>">
						</div>
						</div>
					<div class="form-group margin-bottom required">
					<label class="control-label col-sm-2">Current State:</label>
					<div class="col-sm-3">
					<select name="currentState" class="form-control input-sm">
							<option value="">Please Select</option>
							<option <?php if($entity->getCurrentState()=="draftInvoice"): echo "selected"; endif ?> value="draftInvoice">Draft Invoice</option>
							<option <?php if($entity->getCurrentState()=="finalInvoice"): echo "selected"; endif ?> value="finalInvoice">Final Invoice</option>
    				</select>
   					</div>
   					
   					<div class="col-sm-3">
							<input
								<?php if(!$entity== null): echo ($entity->getIsActive()=="1")?"checked":""; else: echo "checked"; endif;?>
								type="checkbox" name="isActive" value="1">&nbsp;Is Active&nbsp;&nbsp;&nbsp;&nbsp;

						</div>
   					
   					</div>

					<div class="form-group margin-bottom required">
						<label class="control-label col-sm-2 ">Vendor:</label>
						<div class="col-sm-3">
							<input readonly="readonly" class="form-control input-sm" type="text"
								id="vendor_name_1" placeholder="Enter term to search vendor"
								name="vendor_name"
								value="<?php if (!$source== null): if (!$source->getVendor() == null):echo $source->getVendor()->getVendorName();endif;endif;?>">

							<input type="hidden" id="vendor_id" placeholder=""
								name="vendor_id"
								value="<?php if (!$source == null): if (!$source->getVendor() == null):echo $source->getVendor()->getId();endif;endif;?>">
						</div>
					</div>
					
					<div class="form-group margin-bottom">
						<label class="control-label col-sm-2">Contract /PO:</label>
						<div class="col-sm-3">
							<input readonly="readonly" class="form-control input-sm" type="text" placeholder=""
								id="contractNo" name="contractNo" 
								value="<?php echo (!$source == null)? $source->getContractNo():"";?>">
						</div>
						<label class="control-label col-sm-2">Contract /PO Date:</label>
						<div class="col-sm-3">
							<input readonly="readonly" class="form-control input-sm" type="text" placeholder=""
								id="contractDate" name="contractDate" 
								value="<?php if(!$source == null): if ($source->getContractDate() !== null): echo date_format($source->getContractDate(),"Y-m-d"); endif; endif;?>">
						</div>
					</div>
					
					<div class="form-group margin-bottom required">
						<label class="control-label col-sm-2">Currency:</label>
    					<div class="col-sm-3">
    					
    					
    					<select disabled="disabled" name="currency_id" class="form-control input-sm">
								<option value="">Select Currency</option>
   	    							<?php
   	    							if($currency_list!== null):
       	    							foreach ( $currency_list as $curr ) :
       	    							if($source!==null):
       	    							     if($source->getCurrency()!==null):
       	    							         if($source->getCurrency()->getCurrency() == $curr->getCurrency()):
       	    							             echo '<option selected value="' . $curr->getId() . '">' . $curr->getCurrency() . '</option>';
   	    							             else:
   	    							                 echo '<option value="' . $curr->getId() . '">' . $curr->getCurrency() . '</option>';
       	    							         endif;
       	    							     else:
       	    							            echo '<option value="' . $curr->getId() . '">' . $curr->getCurrency() . '</option>';
       	    							     endif;
       	    							 else:
       	    							     echo '<option value="' . $curr->getId() . '">' . $curr->getCurrency() . '</option>';
       	    							 endif;
       									endforeach;
   	    							endif;
									?>
   					</select>
    					
    					
    			    <!-- 		
    					<input readonly="readonly" class="form-control input-sm" type="text" placeholder=""
    								id="currency_name" name="currency_name" 
    								value="<?php if($source->getCurrency()!==null): echo $source->getCurrency()->getCurrency(); endif;?>">
    					<input type="hidden" class="form-control input-sm" placeholder=""
    								id="currency_id" name="currency_id" 
    								value="<?php if($source->getCurrency()!==null): echo $source->getCurrency()->getId(); endif;?>">
    					
   					 -->
   					 	</div>
   			   					 
   					 <label class="control-label col-sm-2">Exchange Rate:</label>
						<div class="col-sm-3">
							<input class="form-control input-sm" type="text" placeholder=""
								id="exchangeRate" name="exchangeRate" 
								value="<?php echo (!$entity == null)? $entity->getExchangeRate():"";?>">
						</div>
   						 
   					</div>
					
					<div class="form-group margin-bottom required">

						<label class="control-label col-sm-2">Goods Receipt Date:</label>
						<div class="col-sm-3">
							<input class="form-control input-sm" type="text"
								id="grDate" name="grDate"
								value="<?php if(!$entity == null): if ($entity->getGrDate() !== null): echo date_format($entity->getGrDate(),"Y-m-d"); endif; endif;?>"
								placeholder=" please select" />
							</div>
						<label class="control-label col-sm-2" for="inputTag">Target Warehouse:</label>
					<div class="col-sm-3">
<input class="form-control input-sm" readonly type="text" id="target_wh_name" placeholder="Please select!" name="target_wh" value="<?php if (!$entity == null): if (!$entity->getWarehouse() == null):echo $entity->getWarehouse()->getWhName();endif;endif;?>">
<input type="hidden" id="target_wh_id" name="target_wh_id" value="<?php if (!$entity == null): if (!$entity->getWarehouse() == null):echo $entity->getWarehouse()->getId();endif;endif;?>" />
					</div>
				</div>
		
				<div class="form-group margin-bottom">
					<label class="control-label col-sm-2" >Description</label>
            		<div class="col-sm-8">
            			<input class="form-control input-sm" type="text"  placeholder=""
            				name="remarks" value="<?php 
            				if($source!==null): 
            				echo 'Goods Receipt from PO #'. $source->getSysNumber(); 
            				endif;
            				
            				?>">
            		</div>
				</div>
				</div>
					
				<hr>
				<div class="form-group margin-bottom">
						<label class="control-label col-sm-2" for="inputTag"></label>
						<div class="col-sm-3">
	   	<button onclick="submitForm('Create_Inv_Form');" class="btn btn-default btn-sm"><i class="glyphicon glyphicon-floppy-disk"> </i> Save & Next</button>
							<a tabindex="11" class="btn btn-default btn-sm"
								href="<?php echo $this->baseUrl ?>/finance/v-invoice/list"><small><i
									class="glyphicon glyphicon-remove"></i></small>&nbsp;Cancel</a>
	
						</div>
					</div>
			</fieldset>
		</form>
		  <?php endif; ?>
		 <!-- C2 ends-->
  </div>
  
  <!-- ROW -->
</div>	
		
		<!-- Tab1 -->
	</div>
</div>



<script>

$('#invoiceDate').bind('change', function() {
	$('#postingDate').val($('#invoiceDate').val());
	$('#grDate').val($('#invoiceDate').val());
});

$( "input[id='postingDate']").datepicker({ firstDay: 1, dateFormat: 'yy-mm-dd',closeText: 'X',changeMonth: true, changeYear: true});
$( "input[id='invoiceDate']").datepicker({ firstDay: 1, dateFormat: 'yy-mm-dd',closeText: 'X',changeMonth: true, changeYear: true});
$( "input[id='grDate']").datepicker({ firstDay: 1, dateFormat: 'yy-mm-dd',closeText: 'X',changeMonth: true, changeYear: true});

$( "#vendor_name_1" ).autocomplete({
    source: "/bp/vendor-search/auto-complete",
    minLength: 3,
    select: function( event, ui ) {
  	  $( "#vendor_id" ).val(ui.item.id);
      //alert	( "Selected: " + ui.item.value + " aka " + ui.item.id );
  	  //alert($( "#vendor_id" ).val());

  	 	$('#global-notice').show();
  		$('#global-notice').html('"' + ui.item.value + '" selected');
  		$('#global-notice').fadeOut(5000);
  		//$("#jquery_dialog").dialog("close");
    }
    })
    .autocomplete( "instance" )._renderItem = function( ul, item ) {
    return $( "<li>" )
      .append( "<div style='padding-bottom: 5px; border-bottom: thin solid gray;'><b>" + item.value + "</b><br><span style='color:gray;font-size: 9pt;'>" + item.vendor_country + "<span></div>" )
      .appendTo( ul );
    };

$( "#vendor_name_1" ).focus();
  
</script>

