<?php
use Application\Application\DTO\Uom\UomGroupDTO;
use Application\Application\Helper\ErrorMessage;
use Application\Application\Helper\OptionHelper;
use Application\Controller\Plugin\SharedCollectionPlugin;

/**
 *
 * @var UomGroupDTO $dto ;
 * @var SharedCollectionPlugin $sharedCollection ;
 */

$error_msg = ErrorMessage::showErrorMessage($errors);

$baseUom = null;
if ($dto != null) {
    $baseUom = $dto->getBaseUom();
}
$uomList = $sharedCollection->getUomCollection();
$uom_option = OptionHelper::createUoMOption($uomList, $baseUom);

?>
<div id="tabs" style="font-size: 9.5pt">
   <ul>
      <li>
         <a href="#general">Create New Uom</a>
      </li>
   </ul>
   <div id="general">

<?php
// ================================
echo $error_msg;
// ===============================
?>
      <form class="form-horizontal" action="<?php
    echo $form_action;
    ?>" method="post" enctype="multipart/form-data">
         <input type="hidden" name="redirectUrl" value="<?php

        echo $redirectUrl?>" />
         <input type="hidden" name="key" value="<?php

        echo $key;
        ?>" />
         <div class="form-group margin-bottom">
            <label class="control-label col-sm-2" for="inputTag">Group Name</label>
            <div class="col-sm-3">
               <input class="form-control input-sm" type="text" id="inputTag" placeholder="" name="groupName" value="<?php
            echo (! $dto == null) ? $dto->getGroupName() : "";
            ?>">
            </div>
         </div>
         <div class="form-group margin-bottom required">
            <label class="control-label col-sm-2"><?php

            echo $this->translate("Base Unit of Measurment");
            ?></label>
            <div class="col-sm-3">
               <select name="baseUom" id="baseUom_id" class="form-control input-sm">
                  <option value=""><?php

                echo $this->translate("Select Standard unit");
                ?></option>
   	              <?php
                echo $uom_option;
                ?>
   				</select>
            </div>
         </div>
         <div class="form-group margin-bottom">
            <label class="control-label col-sm-2" for="inputDescription">remarks</label>
            <div class="col-sm-3">
               <textarea class="form-control input-sm" id="inputDescription" placeholder="" rows="2" name="description"></textarea>
            </div>
         </div>
         <div class="form-group margin-bottom">
            <label class="control-label col-sm-2" for="inputTag">Conversion Factory</label>
            <div class="col-sm-3">
               <input class="form-control input-sm" type="text" id="inputTag" placeholder="" name="converstion_factor" value="">
            </div>
         </div>
         <div class="form-group margin-bottom">
            <label class="control-label col-sm-2" for="inputTag">Status</label>
            <div class="col-sm-3">
               <select class="form-control nput-sm" name="parent">
                  <option selected="selected" value="Activated">Activated</option>
                  <option value="Deactivated">Deactivated</option>
               </select>
            </div>
         </div>
         <div class="form-group margin-bottom">
            <div class="col-sm-offset-2 col-sm-10">
               <button type="submit" class="btn btn-default">Submit</button>
            </div>
         </div>
      </form>
   </div>
</div>
<div id="dialog" style="display: none;">Check code...</div>