 	
<?php
if ($total_resources <= 0) {

    echo 'No Resources found!';
} else {

    if (! is_null($paginator)) {
        echo 'records ' . $paginator->getMinInPage() . ' to ' . $paginator->getMaxInPage() . ' | ' . $total_resources . ' records found!';
    } else {
        echo $total_resources . ' records found!';
    }

    ?>

<form
	action="<?php echo $this->baseUrl ?>/application/role/grant-access"
	method="post" enctype="multipart/form-data" id="">

	<input type="hidden" name="role_id"
		value="<?php echo (int) $role_id; ?>" />

	<table style="font-size: 10pt"
		class="table table-bordered table-striped">
		<thead>
			<tr>
				<td><input type="checkbox" id="select_ALL" name="SelectAll"
					value="YES" /> <b>All</b></td>
				<td><b>Module</b></td>
				<td><b>Controller</b></td>
				<td><b>Action</b></td>
				<td><b>Resource</b></td>
				<td><b>Updated on</b></td>
				<td><b>Action</b></td>
			</tr>
		</thead>

		<tbody>
 
	 <?php

    $count = 0;
    foreach ($resources as $a) :
        $count ++;
        // echo ($count % 2 == 1) ? "<tr>" : "<tr class=\"pure-table-odd\">";
        // $instock = $a['totalINFLOW']-$a['totalOUTFLOW'];

        ?>
	 <tr>
				<td><input class="checkbox1" type="checkbox" name="resources[]"
					value="<?php echo $a->id;?>" class="checkbox" /></td>
				<td><?php echo $this->escapeHtml($a->module);?></td>
				<td><?php echo $this->escapeHtml($a->controller);?></td>
				<td><?php echo $this->escapeHtml($a->action);?></td>
				<td><?php echo $this->escapeHtml($a->resource);?></td>
				<td><?php echo date_format (date_create($a->created_on), "d/m/y h:m");?> </td>
				<td>-</td>
			</tr>
<?php endforeach; ?>

 </tbody>
	</table>
	<input class="btn btn-primary" type="submit" name="grant"
		value="Grant Access" /> <br>
    </form>
<?php

    // ===============================
    if (! is_null($paginator)) :

        // change it only
        $base = $this->baseUrl . '/application/role/grant-access?id=' . $role_id;
        $_connector_symbol = '&';

        $last = $base . $_connector_symbol . 'page=' . $paginator->getTotalPages() . '&perPage=' . $paginator->getResultsPerPage();;
        $first = $base . $_connector_symbol . 'page=1&perPage=' . $paginator->getResultsPerPage();;

        $p1 = ($paginator->getPage()) - 1;
        $p2 = ($paginator->getPage()) + 1;

        $prev = $base . $_connector_symbol . 'page=' . $p1 . '&perPage=' . $paginator->getResultsPerPage();;
        $next = $base . $_connector_symbol . 'page=' . $p2 . '&perPage=' . $paginator->getResultsPerPage();;

        echo '<ul class="pagination">';

        if ($paginator->getPage() != 1 and $paginator->getTotalPages() > 10) {
            echo '<li><a href="' . $first . '"> |< </a></li>';
            echo '<li><a href="' . $prev . '"> < </a></li>';
        }

        for ($i = $paginator->getMinInPageSet(); $i <= $paginator->getMaxInPageSet(); $i ++) {

            $url = $base . $_connector_symbol . 'page=' . $i . '&perPage=' . $paginator->getResultsPerPage();;

            if ($i == $paginator->getPage()) {
                echo '<li><a class="active" href="#">' . $i . '</a></li>';
            } else {
                echo '<li><a href="' . $url . '"> ' . $i . ' </a></li>';
            }
        }
        if ($paginator->getPage() != $paginator->getTotalPages() and $paginator->getTotalPages() > 10) {
            echo '<li><a href="' . $next . '"> > </a></li>';
            echo '<li><a href="' . $last . '"> >| </a></li>';
        }
        echo '</ul>';
endif;

}
//===============================
?>

