<h4>Create New Role:</h4>
<hr>

<?php
if (count ( $errors ) > 0) {
	echo '<div class="alert alert-error">';
	
	echo '<ul>';
	foreach ( $errors as $error ) :
		echo '<li>' . $error . '</li>';
	endforeach
	;
	echo '</ul>';
	echo '</div>';
}
?>


<form class="form-horizontal"
	action="<?php echo $this->baseUrl ?>/application/role/add"
	method="post" enctype="multipart/form-data" id="NewSP">
	<input type="hidden" name="redirectUrl"
		value="<?php echo $redirectUrl ?>" />


	<div class="form-group">
		<label class="control-label col-sm-2" for="inputTag">Name</label>
		<div class="col-sm-3">
			<input class="form-control" type="text" id="inputTag" placeholder=""
				name="role" value="<?php echo $role!==null ? ($role->role) :""?>">
		</div>
	</div>

	<div class="form-group">
		<label class="control-label col-sm-2" for="inputTag">Parent Role: </label>
		<div class="col-sm-3">
			<select name="parent_id" class="form-control">
				<option value="">-------</option>
        		<?php
										
										if (count ( $roles ) > 0) :
											foreach ( $roles as $role ) :
												echo '<option value =' . $role->id . '>' . $role->role . '</option>';
											endforeach
											;
					 endif;
										
										?>
	   	</select>
		</div>
	</div>

	<div class="form-group">
		<label class="control-label col-sm-2" for="inputDescription">remarks</label>
		<div class="col-sm-3">
			<textarea class="form-control" id="inputDescription" placeholder=""
				rows="2" name="remarks"><?php echo $role!==null ? ($role->remarks):""?></textarea>
		</div>
	</div>

	<div class="form-group">
		<label class="control-label col-sm-2" for="inputTag">Status</label>
		<div class="col-sm-3">
			<select class="form-control" name="parent">
				<option selected="selected" value="Activated">Activated</option>
				<option value="Deactivated">Deactivated</option>
			</select>
		</div>
	</div>

	<div class="form-group">        
      <div class="col-sm-offset-2 col-sm-10">
        <button type="submit" class="btn btn-default">Submit</button>
      </div>
    </div>
</form>



<div id="dialog" style="display: none;">Check code...</div>