<div id="tabs" style="font-size: 9.5pt">
	<ul>
		<li><a href="#general">ACL Role</a></li>
	</ul>

	<div id="general">

		<ul class="nav nav-pills">
			<li><a href="<?php

echo $this->baseUrl?>/application/role/list1">List1</a></li>
		</ul>
		<hr>

		<div id="html" class="demo">
			<ul>
	<?php

echo $jsTree?>;
</ul>
		</div>
	</div>
</div>

<script>
// html demo
	$('#html').jstree({
		"core" : {
		       // so that create works
		       "check_callback" : true
		     },
		    "plugins" : [ "contextmenu" ],

		    "contextmenu":{
		        "items": function($node) {
		            var tree = $("#html").jstree(true);
		            return {
		                "Create": {
		                    "separator_before": false,
		                    "separator_after": false,
		                    "label": "Create New Role",
		                    "action": function (obj) {
		                    	var ref = $.jstree.reference(obj.reference);
                                sel = ref.get_selected();
        	                    $node = tree.create_node($node);
			                    tree.edit($node);
		                    }
		                },
		                "Rename": {
		                    "separator_before": false,
		                    "separator_after": false,
		                    "label": "Rename Role",
		                    "action": function (obj) {
		                        tree.edit($node);
		                    }
		                },
		                "Remove": {
		                    "separator_before": false,
		                    "separator_after": false,
		                    "label": "Remove Role",
		                    "action": function (obj) {
		                        tree.delete_node($node);
		                    }
		                },
		                "Add Member": {
		                    "separator_before": false,
		                    "separator_after": false,
		                    "label": "Add Member",
		                    "action": function (obj) {
		                    	var redirectUrl = "/application/role/add-member?id="+$node.id;
		                    	window.location = redirectUrl;
		                   }
		                },
		                "Grant Access": {
		                    "separator_before": false,
		                    "separator_after": false,
		                    "label": "Grand Access",
		                    "action": function (obj) {
		                    	var redirectUrl = "/application/role/grant-access1?role="+$node.id;
		                    	window.location = redirectUrl;

		                   }
		                }
		            };
		        }
		    }

    });

	// When the jsTree is ready, add two more records.
	$('#html').on('create_node.jstree', function (e, data) {
		//alert(data.node.parent +  data.node.id);
	});

	$('#html').on('rename_node.jstree', function (e, data) {
		alert(data.node.parent +  data.node.id);
		createRole(data.node.parent,data.node.id,data.node.text);
    });

	$('#html').on('delete_node.jstree', function (e, data) {
		//alert(data.node.parent +  data.node.id);
		//createRole(data.node.parent,data.node.id,data.node.text);
    });
</script>

