<?php
echo '<div id="flash_messages" class="global-notice">';
echo $this->flashMessenger()->render();
echo '</div>';
?>

<h4>
	 <?php 
	 // target:EMPLOYEE
	 echo (!$target== null)? 'Employee: ' . $target->getEmployeeName():"";?>
</h4>

<?php
if (count ( $errors ) > 0) {
	echo '<div class="alert alert-danger" role="alert" style="font-size: 10.5pt">';
	
	echo '<ul>';
	foreach ( $errors as $error ) :
		echo '<li>' . $error . '</li>';
	endforeach
	;
	echo '</ul>';
	echo '</div>';
}
?>

<div id="tabs" style="font-size: 10pt"> 
  <ul>
  <li ><a href="#general">Picture Upload</a></li>
   </ul>

<div id="general"> 

<!-- TO UPDATE ACTION -->
<form id="sp_upload_pic_form" class="form-horizontal" action=""
	method="post" enctype="multipart/form-data">
	
	
	<div class="form-group">
		<label class="control-label col-sm-2" for="inputTag">Picture</label>
		<div class="col-sm-3">
			<input type="file" name="pictures[]" />
			<input type="file" name="pictures[]" />
			<input type="file" name="pictures[]" />
			<input type="file" name="pictures[]" />
			<input type="file" name="pictures[]" />
		</div>
	</div>
	
	
	
	<div class="form-group">
		<label class="control-label col-sm-2" for="inputTag"></label>
		<div class="col-sm-3">
			<button type="button"  onclick="uploadImages('/hr/employee-attachment/upload-pictures','<?php echo $target!==null ? $target->getId():""?>','<?php echo $redirectUrl ?>','<?php echo $target!==null ? $target->getChecksum():""?>','<?php echo $target!==null ? $target->getToken():""?>')" class="btn btn-primary"
				id="upload">
				<i class="glyphicon glyphicon-upload"> </i> Upload
			</button>
			<a class="btn btn-default" href="<?php echo $redirectUrl ?>"><i class="icon-back"> </i> << Back</a>
		</div>
	</div>
	
</form>
</div>
</div>



<!-- Modal -->
<div id="myModal" class="modal" role="dialog">
	<div class="modal-dialog">
	<div class="modal-content">
	
		<div class="modal-body">
			<p>Processing........Please Wait!</p>
		</div>
	</div>
	</div>
</div>

<!-- Modal -->
<div class="modal fade" id="modal1" role="dialog">
	<div class="modal-dialog modal-sm">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal">&times;</button>
				<h5 class="modal-title">Mascot International Laos</h5>
			</div>
			<div class="modal-body">
				<p>No picture selected!</p>
			</div>
			<div class="modal-footer">
				<button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
			</div>
		</div>
	</div>
</div>