<h4>Asset Counting:</h4>

<?php if ($counting!==null)
{
echo '<div class="alert alert-info">';
	
	 echo '<ul>';
	 echo '<li>Task Name	: <strong>' . $counting->name . '</strong></li>';
	 echo '<li>Start date	: <strong>' .$counting-> start_date . '</strong> - End date	: <strong>' .$counting->end_date . '</strong></li>';
	 echo '<li>Status	: <strong>' .$counting-> status . '</strong></li>';
	 echo '<li>Counted	: <strong>' .$total_counted . ' /' . $total_to_count  . '</strong></li>';
	 echo '</ul>';
	 echo '</div>';
} 
?>

<ul class="nav nav-pills">
	<li><a href="/application/pdf/asset-counting?id=<?php echo $counting->id ?>&category_id=<?php echo $counting->asset_cat_id ?>"  target="_blank"><i class="icon-print">  </i> Print PR(PDF)</a> </li>
	<li><a href="/inventory/count/print-asset-counting?id=<?php echo $counting->id ?>" target="_blank"><i class="icon-print">  </i> Print Preview(HTML)</a> </li>

 </ul>
		<h5>
		<a
			href="<?php echo $this->baseUrl ?>/inventory/count/select-location?id=<?php echo $counting->id?>"> COUNT NOW
		</a>
		</h5>

<table class="table table-striped table-bordered">
<thead>
	<tr>
		<td><b>N0.</b></td>
		<td><b>Picture</b></td>
		<td><b>ASSET TAG</b></td>
		<td><b>LOCATION</b></td>
		<td><b>COUNTED BY</b></td>
		<td><b>VERIFED BY</b></td>
		<td><b>ACKNOWLEDED BY</b></td>
		<td><b>COUNTED ON</b></td>
		<td><b>ACTION</b></td>
		
	</tr>
</thead>

 <tbody>
<?php	 
	 $count = 0;
	 foreach ($items as $a) : 
	 	 $count++;
	 	//echo  ($count % 2 == 1) ? "<tr>" : "<tr class=\"pure-table-odd\">";
	 	 
	 ?>
		<tr>
  		<td><b><?php echo $count;?></b></td>
  		
  			 	<td>
			<?php 
			if($a->asset_picture_id!=null):
			?>
			<a target="_blank" href="<?php echo $this->baseUrl ?>/inventory/asset/show?id=<?php echo $this->escapeHtml($a['id']);?>">
			<img class= "img-rounded" style="min-height:100px;height:100px;min-width:100px;width:100px;" src="/inventory/image/asset-thumbnail-200?id=<?php echo $a->asset_picture_id;?>"/>
			</a>
			<?php 
			else:
			?>
			<img class= "img-rounded" width="50" height="50" src="/images/no-pic.jpg"/>
				
			<?php 
			endif;
			?>
			
			</td>
  	
 		<td><?php echo $a['counted_on']!==null? '<span class="label label-success">'.$a['tag'].'</span>': '<b>'. $a['tag'].'</b>';?>
 				<div style="color: gray; font-size: 8pt;	">
 <?php	
 				$asset_name = $a->name;
 				if (strlen($asset_name) > 45) {

				    // truncate string
				    $stringCut = substr($asset_name, 0, 45);
				
				    // make sure it ends in a word so assassinate doesn't become ass...
				    $asset_name = substr($stringCut, 0, strrpos($stringCut, ' ')).'<a title="'. $a->name.'">... </a>'; 
				}
?>
 				
 				Name: <span id="<?php echo $this->escapeHtml($a->id);?>_name"><?php echo $asset_name ;?></span><br>
				Model: <span id="<?php echo $this->escapeHtml($a->id);?>_model"><?php echo $this->escapeHtml($a->model);?></span><br>
				Serial: <span id="<?php echo $this->escapeHtml($a->id);?>_serial"><?php echo $this->escapeHtml($a->serial);?></span>
				</div>
 		
 		</td>
		<td><?php echo $a['counted_location'];?></td>

		<td><?php echo $a['counted_by'];?></td>
		<td><?php echo $a['verified_by'];?></td>
		<td><?php echo $a['acknowledged_by'];?></td>
		<td><?php echo $a['counted_on'];?></td>
		<td>
		<a target="_blank"  href="<?php echo $this->baseUrl ?>/inventory/asset/show?id=<?php echo $this->escapeHtml($a['id']);?>">
		Detail </a></td>
	</tr>
<?php endforeach; ?>

 </tbody>
</table>
