
<div id="tabs" style="font-size: 10pt">

	<ul>
		<li><a href="#general"><?php echo $this->translate('Reporting'); ?></a></li>
	</ul>
	<div id="general" style="font-size: 10pt">
		<ul>
			<li><a href="/hr/reporting/daily"><?php echo $this->translate('Daily Reporting'); ?></a></li>
			<li><a href="/hr/reporting/month"><?php echo $this->translate('Monthly Reporting'); ?></a></li>
			<li><a href="/hr/reporting/quartly"><?php echo $this->translate('Quaterly Reporting'); ?></a></li>
			<li><a href="/hr/reporting/yearly"><?php echo $this->translate('Annual Reporting'); ?></a></li>

		</ul>

	</div>
</div>
