<h4>
	 <?php echo (!$item == null)? $item->getItemName():"";?>
</h4>

<?php
if (count ( $errors ) > 0) {
	echo '<div class="alert alert-danger" role="alert" style="font-size: 10.5pt">';
	
	echo '<ul>';
	foreach ( $errors as $error ) :
		echo '<li>' . $error . '</li>';
	endforeach
	;
	echo '</ul>';
	echo '</div>';
}
?>

<div id="tabs" style="font-size: 10pt"> 
  <ul>
  <li ><a href="#general">Attachment upload</a></li>
   </ul>

<div id="general"> 

<form id="attachment_upload_form" class="form-horizontal" action="/inventory/item-attachment/upload" method="post" enctype="multipart/form-data">
<input type="hidden" name="item_id" value="<?php echo (!$item == null)? $item->getId():"";?>" />
<input type="hidden" name="redirectUrl" value="<?php echo $redirectUrl ?>" />


	<div class="form-group">
		<label class="control-label col-sm-2" >Document Type</label>
		<div class="col-sm-3">
			<input class="form-control" type="text"  placeholder=""
				name="document_type" value="<?php echo (!$entity== null)? $entity->getDocumentType():"";?>">
	
		</div>
		<label class="control-label col-sm-1" for="inputTag"></label>
		<div class="col-sm-4">
					  	     <input <?php if(!$entity == null): echo ($entity->getIsActive()==="1")?"checked":""; else: echo "checked"; endif;?> type="checkbox" name="is_active" value="1">&nbsp;Active&nbsp;&nbsp;
		</div>		
	</div>
		
	<div class="form-group">
		<label class="control-label col-sm-2" for="inputTag">Attachment</label>
		<div class="col-sm-3">
			<input style=";" type="file" id= "attachments" name="attachments" />
		</div>		
	</div>
	
	<div class="form-group">
		<label class="control-label col-sm-2" >Vendor (optional)</label>
		<div class="col-sm-3">
			<input disabled class="form-control" type="text" id="vendor_name" placeholder="Select vendor, if any"
				name="vendor_name" value="<?php echo (!$vendor == null)? $vendor->getVendorName():"";?>">
			<input type="hidden" id="vendor_id" placeholder="" 
			name="vendor_id" value="<?php echo (!$vendor== null)? $vendor->getId():"";?>">	
		</div>
		

<a style="color: #0080ff;" href="javascript:;"
	onclick="showJqueryDialog('Select Vendor','750','450', '/bp/vendor/list1','j_loaded_data', true);">Select&nbsp;&nbsp;<i class="glyphicon glyphicon-folder-open"></i>
</a>

	</div>
	
	<div class="form-group">
		
	<label class="control-label col-sm-2" >Remarks</label>
		<div class="col-sm-3">
			<textarea  class="form-control" type="text" rows="4" placeholder=""
				name="remarks" style="font-size: 9pt;"><?php echo (!$entity == null)? $entity->getRemarks():"";?></textarea>
		</div>		
	</div>
	
	<div class="form-group">
		<label class="control-label col-sm-2" for="inputTag"></label>
		<div class="col-sm-3">
	   	<button type="submit" class="btn btn-default"><i class="glyphicon glyphicon-upload"> </i> Upload</button>
  		</div>
	</div> 
		
	
</form>
</div>
</div>

<script type="text/javascript">
$('#attachments').bind('change', function() {
	var file_size;
	file_size = this.files[0].size
	if (file_size > 2097152){
		//alert('This file size is too large : ' + file_size + "MB. Please select new file");
		
		$('#b_loaded_data').text('This file size is too large : ' + file_size + "MB. Please select new file");
		$('#modal1').modal();

		 $("#attachments").val("");
		 	
	}else{
		//alert('This file size is: ' + file_size + "MB, OKE");
		 //$('#save').removeAttr('disabled');
	}

});

</script>

<!-- Modal -->
<div class="modal" id="modal1" role="dialog">
	<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal">&times;</button>
				<span class="modal-title" id="modal_title" style="font-weight: bold;">Mascot International Laos</span>
			</div>
			<div class="modal-body">
				<div id="b_loaded_data">loading</div>
			</div>
			<div class="modal-footer">
				<span id="node_selected"></span>&nbsp;&nbsp;
				<button type="button" class="btn btn-default" data-dismiss="modal">Confirm</button>
			</div>
		</div>
	</div>
</div>




<div id="jquery_dialog" style="display: none; padding-top: 10pt">
	<div id="j_loaded_data"></div>
</div>



