<h4>Create Delivery - Step1:</h4>

<?php if (count($errors)>0)
{
echo '<div class="alert alert-error">';
	
	echo '<ul>';
	 foreach ($errors as $error) :
	 echo '<li>'.$error . '</li>';
	 
	 endforeach;
	 echo '</ul>';
	 echo '</div>';
} 
?>
	

<form class="form-horizontal" action="<?php echo $this->baseUrl ?>/procurement/delivery/create-step1"	method="post" enctype="multipart/form-data" id="NewSP" >
<input type="hidden" name="redirectUrl" value="<?php echo $redirectUrl ?>" />
 
      <div class="control-group">
        <label class="control-label" for="inputTag">Deliver Number:</label>
        <div class="controls">
          <input type="text" id="inputTag" placeholder="" name="dn_number" value="">
        </div>
      </div>
      
     <div class="control-group">
        <label class="control-label" for="inputDescription">Description</label>
        <div class="controls">
          <textarea id="inputDescription" placeholder="" rows="3" cols="5" name="description"></textarea>
        </div>
      </div>
       
       <div class="control-group">
        <div class="controls">
             <button type="submit" class="btn"><i class="icon-plus">  </i> Create</button>
        </div>
      </div>
    </form>



<div id = "dialog" style="display: none;">Check code...</div>
	
