<script language="javascript">
			var id_array = [];
</script>

        
 <?php 
echo '<div class="alert alert-info">';
	
	 echo '<ul>';
	 echo '<li>All Items View for Requester</li>';
	 echo '</ul>';
	 echo '</div>';

?>

 <form class="form-search" action="<?php echo $this->baseUrl ?>/procurement/"	method="get" enctype="multipart/form-data">
      <button type="submit" class="btn"><i class="icon-arrow-left">  </i> Back</button>
</form>
 
<!--  
<span class="label label-info"><?php echo count($dn_items) . ' PR - Items'?></span>

-->
<table class="pure-table pure-table-bordered"">
<thead>
<tr>	
		<td><b>Item</b></td>
		<td><b>PR </b></td>
		<td><b>Q'TY </b></td>
		<td><b>Priority</b></td>
		<td><b>Name</b></td>
		<td><b>Unit</b></td>
		<td><b>Quantity</b></td>
		<td><b>Delivered</b></td>
		<td><b>Balance</b></td>	
		<td><b>EDT</b></td>
		<td><b>Count Down</b></td>
		<td><b>Action</b></td>
		
		</tr>
</thead>
<tbody>	
 
  <?php 
	 
	 $count = 0;
	 foreach ($dn_items as $item) : 
	 	 $count++;
	 echo  ($count % 2 == 1) ? "<tr>" : "<tr class=\"pure-table-odd\">";
	 $to_delivery = $item->quantity - $item->delivered_quantity;
	 
	 ?>
		<td><?php echo $count;?></td>
		<td><?php echo $item->pr_number;?></td>
		<td><?php echo $item->delivered_quantity;?></td>
		
		<td><?php echo $item->priority=='Urgent'? '<span class="label label-warning" >'. $item->priority .'</span>':$item->priority;?></td> 	
		<td><?php echo $item->name;?></td>
		<td><?php echo $item->unit;?></td>
		<td><?php echo $item->quantity;?></td>
		<td><?php echo $item->delivered_quantity;?></td>
		<td><?php echo $to_delivery==0?'<span class="label label-success">0</span>':$to_delivery;?></td>
		<?php if($to_delivery == 0): ?>
				<td><?php echo date_format(date_create($item->EDT),"Y-m-d");?></td>
				<td><span class="label label-success">Fulfilled</span></td>
		<?php else: ?>
		
			<td><span id="<?php echo $item->id;?>_EDT"><?php echo date_format(date_create($item->EDT),"Y-m-d");?></span></td>
			<td><span id="<?php echo $item->id;?>_timer"></span></td>
		<?php endif; ?>
		<td>
		<a
href="<?php echo $this->baseUrl ?>/procurement/delivery/confirm?dn_item_id=<?php echo $item->dn_item_id;?>&
pr_item_id=<?php echo $item->pr_item_id;?>&
sparepart_id=<?php echo $item->sparepart_id;?>&
article_id=<?php echo $item->article_id;?>&
asset_id=<?php echo $item->asset_id;?>&
dn_id=<?php echo $item->delivery_id;?>">Confirm
		</a>
		</td>
		
		</tr>
		
		
		<script language="javascript">
			id_array.push(<?php echo $item->id;?>);
		</script>
	<?php endforeach; ?>

 			

</tbody>
</table>
	
