<script language="javascript">
			var id_array = [];
</script>


 <?php 
echo '<div class="alert alert-info">';
	
	 echo '<ul>';
	 echo '<li>All Items View for Procurement</li>';
	 echo '</ul>';
	 echo '</div>';
	 
	 $department_name = "All";
	 $status_name = $last_status;
	 
	 if ($status_name == ''):
		 $status_name = ' | PR status = All';
	 else:
	 	$status_name = ' | PR status = ' . $last_status;
	 endif;
	 
?>

<div class="panel-group">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h5 class="panel-title">
          <a data-toggle="collapse" href="#collapse1"><i class="icon-filter">  </i> FILTER</a>
        </h5>
      </div>
      <div id="collapse1" class="panel-collapse collapse <?php echo count($pr_items)>0?"":"in"?>">
        <div class="panel-body">
        
 <form class="form-horizontal" action="<?php echo $this->baseUrl ?>/procurement/delivery/item-to-deliver"	method="get" enctype="multipart/form-data" id="ReportForm" >
   
      <div class="control-group">
        <label class="control-label" for="inputNameLocal">PR by Department: </label>
        <div class="controls">
        	<select name="department_id" >
        		<option value="">All departments</option>
   	    	<?php foreach ($departments as $dept) :
        		if($dept->id === $department_id):
	        			$department_name = $dept->name;
	   					echo '<option selected="selected" value="' . $dept->id. '">' .  $dept->name. '</option>';
        		else:
        			echo '<option value="' . $dept->id. '">' .  $dept->name. '</option>';
        		endif;
			endforeach; 
   			?>
   	
   			</select>
	     </div>
      </div>
      
      <div class="control-group">
        <label class="control-label" for="inputNameLocal">PR by Status: </label>
        <div class="controls">
        	<select name="last_status" >
        		<option value="">All</option>
   	    		<option <?php echo $last_status=='Submitted'? "selected='selected'":"";?> value="Submitted">Submitted</option>
   	 	    	<option <?php echo $last_status=='Approved'? "selected='selected'":"";?> value="Approved">Approved</option>
  	 	    	<option <?php echo $last_status=='Fulfilled'? "selected='selected'":"";?> value="Fulfilled">Fulfilled</option>
  
   			</select>
	     </div>
      </div>
      
       <div class="control-group">
        <div class="controls">
             <button type="submit" class="btn"><i class="icon-search">  </i> show</button>
        </div>
      </div>
    </form>
        
        
        
        </div>
     </div>
    </div>
  </div>
 <hr>

  <form class="form-search" action="<?php echo $this->baseUrl ?>/procurement"	method="get" enctype="multipart/form-data">
      <button type="submit" class="btn"><i class="icon-arrow-left">  </i> Back</button>
</form>
        
<!--  
<span class="label label-info"><?php echo count($dn_items) . ' PR - Items'?></span>

-->
<?php if(count($pr_items) >0): 

	if (! is_null ( $paginator )):
		echo '<h5>Result '. $paginator->minInPage. ' to '.$paginator->maxInPage . ' | ' .  $total_items . ' Items found | Deparment = ' . $department_name . ''. $status_name. '</h5>';
	else:
		echo '<h5>'. $total_items . ' Items found | Deparment = ' . $department_name . ''. $status_name .'</h5>';
	endif;
?>	
<table class="pure-table pure-table-bordered">
<thead>
<tr>	
		<td><b>N0.</b></td>
		<td><b>PR Number</b></td>
		<td><b>PR Status</b></td>
		<td><b>Department </b></td>
		
		<td><b>Priority</b></td>
		<td><b>Name</b></td>
		<td><b>Unit</b></td>
		<td ><b data-toggle="tooltip" title = "Ordred Quantity">Q'ty</b></td>
		<td ><b data-toggle="tooltip" title = "Delivered Quantity">Del.</b></td>
		<td ><b data-toggle="tooltip" title = "Balance">Bal.</b></td>	
		<td><b>EDT</b></td>
		<td><b>Count Down</b></td>
	
		<td><b>Action</b></td>
		
		</tr>
</thead>
<tbody>	
 
  <?php 
	 
	 $count = 0;
	 foreach ($pr_items as $item) : 
	 	 $count++;
	 echo  ($count % 2 == 1) ? "<tr>" : "<tr class=\"pure-table-odd\">";
	 ?>
		<td><?php echo $count;?></td>
		<td><?php echo $item->pr_number;?></td>
		<td></td>
		
		<td><?php echo $item->pr_of_department;?></td>
		
		
		<td><?php echo $item->priority=='Urgent'? '<span class="label label-warning" >'. $item->priority .'</span>':$item->priority;?></td> 	
		<td><?php echo $item->name;?></td>
		<td><?php echo $item->unit;?></td>
		<td><?php echo $item->quantity;?></td>
		<td><?php echo $item->confirmed_delivered_quantity;?></td>
		<td><?php echo $item->confirmed_balance;?>
		
		</td>
				<td><span id="<?php echo $item->id;?>_EDT"><?php echo date_format(date_create($item->EDT),"Y-m-d");?></span></td>
			<td><span id="<?php echo $item->id;?>_timer"></span></td>
	
		<td><b><a href="<?php echo $this->baseUrl ?>/procurement/delivery/add-to-cart?pr_item_id=<?php echo $item->id;?>">Delivery</a></b></td>
		
		</tr>
		
		<script language="javascript">
			id_array.push(<?php echo $item->id;?>);
		</script>
	<?php endforeach; ?>

 			

</tbody>
</table><br>


<?php
	
if (! is_null ( $paginator )) {
		
	
	//change it only
	$base=$this->baseUrl . '/procurement/delivery/item-to-deliver?department_id='.$department_id;
	
	$_connector_symbol = '&';

	$last 	= $base . $_connector_symbol.'page=' . $paginator->totalPages . '&perPage=' . $paginator->resultsPerPage;
	$first 	= $base . $_connector_symbol.'page=1&perPage=' . $paginator->resultsPerPage;

	$p1 = ($paginator->page)-1;
	$p2 = ($paginator->page)+1;

	$prev = $base . $_connector_symbol.'page=' . $p1 . '&perPage=' . $paginator->resultsPerPage;
	$next = $base . $_connector_symbol.'page=' . $p2 . '&perPage=' . $paginator->resultsPerPage;


	echo '<ul class="pagination">';

	if($paginator->page != 1 AND $paginator->totalPages > 10){
		echo '<li><a href="'.  $first.'"> |< </a></li>';
		echo '<li><a href="'.  $prev .'"> < </a></li>';
	}

	for($i = $paginator->minInPageSet; $i <= $paginator->maxInPageSet; $i ++) {
			
		$url = $base. $_connector_symbol.'page=' . $i . '&perPage=' . $paginator->resultsPerPage;

			
		if ($i == $paginator->page) {
			echo   '<li><a class="active" href="#">'.$i.'</a></li>';
		} else {
			echo '<li><a href="'. $url. '"> '. $i. ' </a></li>';
		}
	}
	if($paginator->page != $paginator->totalPages AND $paginator->totalPages > 10){
		echo '<li><a href="'.  $next.'"> > </a></li>';
		echo '<li><a href="'.  $last .'"> >| </a></li>';
	}
	echo '</ul>';
}

?>




	
<?php else:
echo 'No Items found ...';

endif;
 ?>
 