
<script language="javascript">
			var id_array = [];
</script>

<!--  
<span class="label label-info"><?php echo count($pr_items) . ' PR - Items'?></span>

-->
<div class="control-group">
	<label class="control-label" for="inputTag">DN Number:</label>
	<div class="controls">
		<input type="text" id="dn_number" placeholder="" name="pr_number"
			value="">
	</div>
</div>


<div class="panel-group">
	<div class="panel panel-default">
		<div class="panel-heading">
			<h5 class="panel-title">
				<a data-toggle="collapse" href="#collapse1"><i class="icon-filter">
				</i> FILTER</a>
			</h5>
		</div>
		<div id="collapse1"
			class="panel-collapse collapse">
			<div class="panel-body">

				<form class="form-horizontal"
					action="<?php echo $this->baseUrl ?>/procurement/delivery/review-cart"
					method="get" enctype="multipart/form-data" id="ReportForm">
					<div class="control-group">
						<label class="control-label" for="inputNameLocal">PR by
							Department: </label>
						<div class="controls">
							<select name="department_id">
								<option value="">All departments</option>
   	    	<?php
									
									foreach ( $departments as $dept ) :
										if ($dept->id === $department_id) :
											$department_name = $dept->name;
											echo '<option selected="selected" value="' . $dept->id . '">' . $dept->name . '</option>';
										 else :
											echo '<option value="' . $dept->id . '">' . $dept->name . '</option>';
										endif;
									endforeach
									;
									?>
   	
   			</select>
						</div>
					</div>

					<div class="control-group">
						<label class="control-label" for="inputNameLocal">Vendor: </label>
						<div class="controls">
							<select name="vendor_id">
								<option value="-1">All</option>
								<?php
									
									foreach ( $vendors as $a ) :
										if ($a->vendor_id === $vendor_id) :
											$vendor_name = $a->vendor_name;
											echo '<option selected="selected" value="' . $a->vendor_id . '">' . $a->vendor_name . ' ('.$a->items_by_vendor.')</option>';
										else :
											echo '<option value="' . $a->vendor_id . '">' . $a->vendor_name . ' ('.$a->items_by_vendor.')</option>';
										endif;
									endforeach
									;
									?>

							</select>
						</div>
					</div>

					<div class="control-group">
						<div class="controls">
							<button type="submit" class="btn">
								<i class="icon-search"> </i> show
							</button>
						</div>
					</div>
				</form>



			</div>
		</div>
	</div>
</div>

<?php  	if (count($cart_items) >0): ?>
<table class="table table-striped table-bordered">
	<thead>
		<tr>
			<td><input type="checkbox" id="select_ALL" name="SelectAll"
				value="YES" /> <b>All</b></td>

		<td><b>Requester</b></td>
		<td><b>Name</b></td>
		<td ><b data-toggle="tooltip" title = "Ordered Quantity">Ordered <br> Quantity</b></td>
		<td><b data-toggle="tooltip" title="Balance">Balance</b></td>
		<td ><b data-toggle="tooltip" title = "Purchasing Quantity">Purchasing<br>Quantity</b></td>
		<td><b>Unit <br>Price</b></td>
		<td><b>Total</b></td>
			<td><b data-toggle="tooltip" title="Currency">Curr.</b></td>
	<td><b>Vendor</b></td>
		<td><b>Action</b></td>
		</tr>
	</thead>
	<tbody>	
 
  <?php
	
	$count = 0;
	foreach ( $cart_items as $item ) :
		$count ++;
		//echo ($count % 2 == 1) ? "<tr>" : "<tr class=\"pure-table-odd\">";
		
		?>
		<tr>
	 	<td><input class="checkbox1" type="checkbox" name="cart_items[]"
		value="<?php echo $item->id ;?>" /></td>

		<td><?php echo $item->pr_requester_name;?>
		
		<div style="color: gray; font-size: 8pt;">
			Dept.:<?php echo $item->pr_of_department;?><br>
			#<?php echo $item->auto_pr_number;?>
			</div>
		</td>
		<td><?php echo $item->name;?>
		
		
		
		</td>
		<td><?php echo $item->ordered_quantity;?></td>
		<td><?php echo $item->confirmed_balance;?></td>
		<td><?php echo $item->delivered_quantity;?></td>
		<td><?php echo $item->price;?></td>
		<td><?php echo ($item->price*$item->delivered_quantity);?></td>
		<td><?php echo $item->currency;?></td>
		
		
		<td>
		<a href="<?php echo $this->baseUrl ?>/procurement/vendor/show?id=<?php echo $item->vendor_id;?>" target="_blank"><?php echo $item->vendor_name;?></a>
<div style="color: gray; font-size: 8pt;">
			<?php echo $item->payment_method;?><br>
			</div>
</td>

		<td>
<a href="<?php echo $this->baseUrl ?>/procurement/pr/edit-cart-item?id=<?php echo $this->escapeHtml($item->id);?>">Edit</a>
<a href="#" onclick="deleteDNCartItemDialog('<?php echo $this->escapeHtml($item->id)?>');">Delete</a>
		
		</td>

<?php endforeach; ?>

 			

</tbody>
</table>
<hr>

<form class="form-search"
	action="<?php echo $this->baseUrl ?>/inventory" method="get"
	enctype="multipart/form-data">
	<button type="submit" class="btn">
		<i class="icon-arrow-left"> </i> Back
	</button>
	<button title="Submit PR to Procurment" class="btn btn-default"
		onclick="openConfirmation(1);" type="button">
		<i class="icon-ok"> </i> Notify 
	</button>
</form>
<?php else: echo 'please add items!'?>
<form class="form-search"
	action="<?php echo $this->baseUrl ?>/inventory" method="get"
	enctype="multipart/form-data">
	<button type="submit" class="btn">
		<i class="icon-arrow-left"> </i> Back
	</button>
</form>

<?php endif; ?>




<?php
	
	if (! is_null ( $paginator )) {
		
		// change it only
		$base = $this->baseUrl . '/procurement/delivery/review-cart?vendor_id='.$vendor_id;
		
		$_connector_symbol = '?';
		
		$last = $base . $_connector_symbol . 'page=' . $paginator->totalPages . '&perPage=' . $paginator->resultsPerPage;
		$first = $base . $_connector_symbol . 'page=1&perPage=' . $paginator->resultsPerPage;
		
		$p1 = ($paginator->page) - 1;
		$p2 = ($paginator->page) + 1;
		
		$prev = $base . $_connector_symbol . 'page=' . $p1 . '&perPage=' . $paginator->resultsPerPage;
		$next = $base . $_connector_symbol . 'page=' . $p2 . '&perPage=' . $paginator->resultsPerPage;
		
		echo '<ul class="pagination">';
		
		if ($paginator->page != 1 and $paginator->totalPages > 10) {
			echo '<li><a href="' . $first . '"> |< </a></li>';
			echo '<li><a href="' . $prev . '"> < </a></li>';
		}
		
		for($i = $paginator->minInPageSet; $i <= $paginator->maxInPageSet; $i ++) {
			
			$url = $base . $_connector_symbol . 'page=' . $i . '&perPage=' . $paginator->resultsPerPage;
			
			if ($i == $paginator->page) {
				echo '<li><a class="active" href="#">' . $i . '</a></li>';
			} else {
				echo '<li><a href="' . $url . '"> ' . $i . ' </a></li>';
			}
		}
		if ($paginator->page != $paginator->totalPages and $paginator->totalPages > 10) {
			echo '<li><a href="' . $next . '"> > </a></li>';
			echo '<li><a href="' . $last . '"> >| </a></li>';
		}
		echo '</ul>';
	}
	
	?>
	
	
	<!-- Modal -->
	<div id="myModal" class="modal hide" role="dialog">
	  <div class="modal-dialog">
	  	 <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h5 class="modal-title">Mascot International (Laos)</h5>
      </div>
	      <div class="modal-body">
	        <p>Do you want to Notify this delivery?</p>
	      </div>
	      
		  <div class="modal-footer">
	        <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
	        <button onclick="submitDNCartItems();" type="button" class="btn btn-primary">OK</button>
	      </div>
	   </div>
	</div>
	
	
	<!-- Modal -->
	<div id="myModal1" class="modal hide" role="dialog">
	  <div class="modal-dialog">
	      <div class="modal-body">
	        <span id="modad_body_text">Working on it........Please Wait!</span>
	      </div>
	   </div>
	</div>
	
	<div id="myModal2" class="modal hide" role="dialog">
	  <div class="modal-dialog">
	  	 <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h5 class="modal-title">Mascot International (Laos)</h5>
      </div>
	      <div class="modal-body">
	      	<span id="cart_item_to_delete"></span>
	        <p>Do you want to delete this Item?</p>
	      </div>
	      
		  <div class="modal-footer">
	        <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
	        <button onclick="deleteDNCartItem();" type="button" class="btn btn-primary">DELETE</button>
	      </div>
	   </div>
	</div>			
