
<div class="panel-group">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h5 class="panel-title">
          <a data-toggle="collapse" href="#collapse1"><?php echo $dn!==null ? '<h5>Deliver Note (DN): '. $dn->dn_number.'</h5>':"" ?></a>
        </h5>
      </div>
      <div id="collapse1" class="panel-collapse collapse">
        <div class="panel-body">
        
     <?php if ($dn!==null)
{
echo '<div class="alert alert-info">';
	
	 echo '<ul>';
	 echo '<li>Description	: <strong>' .$dn->description	 . '</strong></li>';
	 echo '</ul>';
	 echo '</div>';
} 
?>
        </div>
     </div>
    </div>
  </div>       

<h5>Adding Deliver Item:</h5>

<?php if (count($errors)>0)
{
echo '<div class="alert alert-error">';
	
	echo '<ul>';
	 foreach ($errors as $error) :
	 echo '<li>'.$error . '</li>';
	 
	 endforeach;
	 echo '</ul>';
	 echo '</div>';
} 
?>
	

<form class="form-horizontal" action="<?php echo $this->baseUrl ?>/procurement/delivery/select-from-list2"	method="post" enctype="multipart/form-data" id="NewSP" >
 <input type="hidden" name="redirectUrl" value="<?php echo $redirectUrl ?>" />
 <input type="hidden" name="delivery_id" value="<?php echo $dn->id ?>" />
  <input type="hidden" name="pr_item_id" value="<?php echo $pr_item->id ?>" />
 	
	
       <div class="control-group">
        <label class="control-label" for="inputTag">Delivered Quantity:</label>
        <div class="controls">
          <input type="text" id="inputTag" placeholder="" name="delivered_quantity" value="">
           <?php echo '<span class="label label-info">(To delivery: '.($pr_item['quantity'] - $pr_item['delivered_quantity']).')</span>' ?>
        </div>
      </div>    
   
      
       <div class="control-group">
        <label class="control-label" for="inputTag">Price:</label>
        <div class="controls">
          <input type="text" id="inputTag" placeholder="" name="price" value="">
        </div>
      </div>
      
       <div class="control-group">
        <label class="control-label" for="inputTag">Currecy:</label>
        <div class="controls">
          	<select name="curreny" id="curreny" >
        	
        		<option value="">---Please select---</option>
   				<option value="USD">USD</option>
   				<option selected="selected" value="LAK">LAK</option>
   				<option value="THB">THB</option>
   				
  		</select>
        </div>
      </div>
      
      
     
       <div class="control-group">
        <label class="control-label" for="inputDescription">Note:</label>
        <div class="controls">
          <textarea id="inputDescription" placeholder="" rows="2" cols="5" name="notes"></textarea>
        </div>
      </div>
       
       <div class="control-group">
        <div class="controls">
             <button type="submit" class="btn"><i class="icon-plus">  </i> Add</button>
        </div>
      </div>
    </form>



<div id = "dialog" style="display: none;">Check code...</div>
	



