<?php include (ROOT.'\module\Procurement\view\procurement\menu.php'); ?>

<script>
    $(function() {
	    $( "input[id='invoice_date']").datepicker({ firstDay: 1, dateFormat: 'yy-mm-dd',closeText: 'X'});
});
 </script>

<h5>Updating Good Receipt:</h5>

<?php

if (count ( $errors ) > 0) {
	echo '<div class="alert alert-error">';
	
	echo '<ul>';
	foreach ( $errors as $error ) :
		echo '<li>' . $error . '</li>';
	endforeach
	;
	echo '</ul>';
	echo '</div>';
}
?>


<form class="form-horizontal" 	action="<?php echo $this->baseUrl ?>/procurement/gr/edit-item"
	method="post" enctype="multipart/form-data" id="NewSP">
	<input type="hidden" name="redirectUrl"
		value="<?php echo $redirectUrl ?>" /><input
		type="hidden" name="pr_item_id" value="<?php echo $pr_item->id ?>" />		
	<input type="hidden" name="vendor_id" id="vendor_id" value="<?php echo $do_item->vendor_id ?>" />
	<input type="hidden" name="do_item_id" id="" value="<?php echo $do_item->id ?>" />

	<div class="control-group">
		<label class="control-label" for="inputNameLocal">Receipt Date:</label>
		<div class="controls">
			<input type="text" id="end_date" placeholder="click to select"
				name="receipt_date" value="<?php echo date_format(date_create($do_item->receipt_date),"Y-m-d");?>">
		</div>
	</div>
	
	<div class="control-group">
		<label class="control-label" for="inputTag">Vendor:</label>
		<div class="controls">
			<input readonly type="text" id="vendor" placeholder="" name="vendor"
				value="<?php echo $do_item->vendor_name ?>"> 
				<span style="color: gray;">PO: <?php echo $do_item->vendor_name?></span> |
				<a href="javascript:;" onclick="showVendorDialog();"
				class="helper"> Select Other Vendor <i class=" icon-folder-open"></i></a>
		</div>
				
		
	</div>
	
	
	<div class="control-group">
		<label class="control-label" for="inputNameLocal">Invoice Date:</label>
		<div class="controls">
			<input type="text" id="invoice_date" placeholder="click to select"
				name="invoice_date" value="<?php echo date_format(date_create($do_item->invoice_date),"Y-m-d");?>">
		</div>
	</div>
	
	<div class="control-group">
		<label class="control-label" for="inputTag">Invoice No.:</label>
		<div class="controls">
			<input type="text" placeholder="" name="invoice_no"
				value="<?php echo $do_item->invoice_no ?>">
		</div>
	</div>
	
	
	<div class="control-group">
		<label class="control-label" for="inputTag">Items:</label>
		<div class="controls">
			<input type="text" placeholder="" name="name"
				value="<?php echo $do_item->name ?>">
		</div>
	</div>
	<div class="control-group">
		<label class="control-label" for="inputTag">Item Code (if any):</label>
		<div class="controls">
			<input type="text" placeholder="" name="code"
				value="<?php echo $do_item->code ?>">
		</div>
	</div>

	<div class="control-group">
		<label class="control-label" for="inputTag">Item Unit:</label>
		<div class="controls">
			<input type="text" placeholder="" name="unit"
				value="<?php echo $do_item->unit ?>">
		</div>
	</div>

	<div class="control-group">
		<label class="control-label" for="inputTag">Received Quantity:</label>
		<div class="controls">
			<input type="text" id="inputTag" placeholder=""
				name="delivered_quantity" value="<?php echo $do_item->delivered_quantity; ?>">
				 <?php echo '<div style="color: gray;">To deliver: '. $pr_item->confirmed_balance.'. Total Received: '. $pr_item->total_received_quantity.'</div>'?>
     
        </div>
         
	</div>

	<div class="control-group">
		<label class="control-label" for="inputTag">Price:</label>
		<div class="controls">
			<input type="text" id="inputTag" placeholder="" name="price" value="<?php echo $do_item->price ?>">
			<span style="color: gray;">on PO: <?php echo $do_item->price?></span>
		</div>
	</div>

	<div class="control-group">
		<label class="control-label" for="inputTag">Currency:</label>
		<div class="controls">
			<select style="wight: 10px" name="curreny" id="curreny">

				<option selected="selected" value="">---Please select---</option>
				<option <?php echo $do_item->currency=='USD'? "selected='selected'":"";?> value="USD">USD</option>
				<option <?php echo $do_item->currency=='LAK'? "selected='selected'":"";?>value="LAK">LAK</option>
				<option <?php echo $do_item->currency=='THB'? "selected='selected'":"";?>value="THB">THB</option>

			</select>
			<span style="color: gray;">on PO: <?php echo $do_item->currency?></span>
		</div>
	</div>

	<div class="control-group">
		<label class="control-label" for="inputTag">Payment Method:</label>
		<div class="controls">
			<select name="payment_method" id="payment_method">

				<option selected="selected" value="">---Please select---</option>
				<option <?php echo $do_item->payment_method=='By Cash'? "selected='selected'":"";?> value="By Cash">By Cash</option>
				<option <?php echo $do_item->payment_method=='Bank Transfer'? "selected='selected'":"";?> value="Bank Transfer">Bank Transfer</option>
				<option <?php echo $do_item->payment_method=='Other'? "selected='selected'":"";?> value="Other">Other Method</option>
			</select>
			<span style="color: gray;">on PO: <?php echo $do_item->payment_method?></span>
		</div>
	</div>



	<div class="control-group">
		<label class="control-label" for="inputDescription">Remarks:</label>
		<div class="controls">
			<textarea id="inputDescription" placeholder="" rows="2" cols="5"
				name="remarks"><?php echo $do_item->remarks ?></textarea>
		</div>
	</div>

	<div class="control-group">
		<div class="controls">
			<button type="submit" class="btn"> Update
			</button>
		</div>
	</div>
</form>



<?php include (ROOT.'\module\Procurement\view\procurement\select_vendor.php'); ?>



