
<script language="javascript">
			var id_array = [];
</script>

<?php


if ($balance== 2 or $balance == null):
$balance_selected = "Balance = All";
endif;

if ($balance== 0 ):
$balance_selected = "Balance = 0 (Fulfilled Items)";
endif;

if ($balance== 1 ):
$balance_selected = "Balance >0 (Pending Items)";
endif;

if ($balance== -1 ):
$balance_selected = "Balance <0 (Some free items)";
endif;


if ($notified == "" or $notified == null):
	$notified_selected = "Notify status = all";
endif;


if ($notified == "1" ):
$notified_selected = "Notify status = YES";
endif;

if ($notified == "0"):
$notified_selected = "Notify status = NO";
endif;

?>


<h4> Received Items:</h4>
<div class="panel-group">
	<div class="panel panel-default">
		<div class="panel-heading">
			<h5 class="panel-title">
				<a data-toggle="collapse" href="#collapse1"><i class="icon-filter">
				</i> FILTER</a>
				
			</h5>
			<hr>
		</div>
		<div id="collapse1"
			class="panel-collapse collapse">
			<div class="panel-body">

				<form class="form-horizontal"
					action="<?php echo $this->baseUrl ?>/procurement/gr/list"
					method="get" enctype="multipart/form-data" id="ReportForm">
					<div class="control-group">
						<label class="control-label" for="inputNameLocal">PR by
							Department: </label>
						<div class="controls">
							<select name="department_id">
								<option value="">All departments</option>
   	    	<?php
									
									foreach ( $departments as $dept ) :
										if ($dept->id === $department_id) :
											$department_selected = "Department = ".  $dept->name;
										
											echo '<option selected="selected" value="' . $dept->id . '">' . $dept->name . '</option>';
										 else :
											echo '<option value="' . $dept->id . '">' . $dept->name . '</option>';
										endif;
									endforeach
									;
									?>
   	
   					</select>
						</div>
					</div>

					
					
					<div class="control-group">
						<label class="control-label" for="inputNameLocal">Balance: </label>
						<div class="controls">
							<select name="balance">
								<option value="2">All</option>
								<option <?php echo $balance=='0'? "selected='selected'":"";?>
									value="0">Balance=0 (Fulfilled Items)</option>
								<option <?php echo $balance=='1'? "selected='selected'":"";?>
									value="1">Balance>0 (Pending Items)</option>
								<option <?php echo $balance=='-1'? "selected='selected'":"";?>
									value="-1">Balance<0 (Some Free Items)</option>

							</select>
						</div>
					</div>
						<div class="control-group">
						<label class="control-label" for="inputTag">Notified:</label>
						<div class="controls">
							<select style="wight: 10px" name="notified" id="notified">
								<option selected="selected" value="">All</option>
								<option <?php echo $notified=='1'? "selected='selected'":"";?> value="1">YES</option>
								<option <?php echo $notified=='0'? "selected='selected'":"";?> value="0">NO</option>
							</select>
							</div>
					</div>
					
					<div class="control-group">
						<label class="control-label" for="inputNameLocal">Confirmed By Requester:</label>
						<div class="controls">
							<select name="notified_quantity">
								<option value="2">All</option>
								<option
									<?php echo $notified_quantity=='0'? "selected='selected'":"";?>
									value="0">YES</option>
								<option
									<?php echo $notified_quantity=='1'? "selected='selected'":"";?>
									value="1">NO</option>


							</select>
						</div>
					</div>
					
			
					<div class="control-group">
						<div class="controls">
							<button type="submit" class="btn">
								<i class="icon-search"> </i> show
							</button>
						</div>
					</div>
				</form>
				<hr>
			</div>
		</div>
	</div>
</div>

<?php if($notified==0 and $balance>0):?>

<div class="control-group">
	<label class="control-label" for="inputTag"><b>DN Number:</b></label>
	<div class="controls">
		<input type="text" id="dn_number" placeholder="" name="pr_number"
			value="">
	</div>
</div>
<?php endif;?>

<?php  	

	if (! is_null ( $paginator )) :
		echo '<h5>'. $paginator->minInPage . ' to ' . $paginator->maxInPage . ' of ' . $total_items . 
		' Item(s) found | <span class="label label-info">' . $balance_selected . ' | ' . 
		$notified_selected. ' | ' .
	 '<span></h5>';	
	 else :
	 echo '<h5>' . $total_items .
	 ' Item(s) found | <span class="label label-info">' . $balance_selected . ' | ' .
	 $notified_selected. ' | ' .
	 
	 '<span></h5>';		
	 endif;
	 ?>


<?php  	if (count($receipts) >0): ?>
<table class="table table-striped table-bordered">
	<thead>
		<tr>
			<td><input type="checkbox" id="select_ALL" name="SelectAll"
				value="YES" /> <b>All</b></td>

		<td><b>Requester</b></td>
		<td><b>Item Name</b></td>
		<td ><b data-toggle="tooltip" title = "Ordered Quantity">Ordered <br> Quantity</b></td>
		
		<td ><b data-toggle="tooltip" title = "Purchasing Quantity">Purchasing<br>Quantity</b></td>
		<td ><b data-toggle="tooltip" title = "Purchasing Quantity">Received<br>Quantity</b></td>
		<td ><b data-toggle="tooltip" title = "Purchasing Quantity">Notifed<br>Quantity</b></td>
		<td ><b data-toggle="tooltip" title = "Purchasing Quantity">Confirmed<br>Quantity</b></td>
		<td ><b data-toggle="tooltip" title = "Purchasing Quantity">Rejected<br>Quantity</b></td>
		<td><b data-toggle="tooltip" title="Balance">Balance</b></td>
	
		<td><b>Unit <br>Price</b></td>
		<td><b>Total</b></td>
			<td><b data-toggle="tooltip" title="Currency">Curr.</b></td>
	<td><b>Vendor</b></td>
		<td><b>Work Flow</b></td>
		</tr>
	</thead>
	<tbody>	
 
  <?php
	
	$count = 0;
	foreach ( $receipts as $item ) :
		$count ++;
		//echo ($count % 2 == 1) ? "<tr>" : "<tr class=\"pure-table-odd\">";
		
		?>
		<tr>
		
		
	 	<td>
	 	<?php if ($item->last_workflow_id ==null):?>
	 	<input class="checkbox1" type="checkbox" name="do_items[]"
		value="<?php echo $item->id ;?>" />
		<?php else: ?>
			Notified
		<?php endif; ?>
		
		</td>

		<td><?php echo $item->pr_requester_name;?>
		
		<div style="color: gray; font-size: 8pt;">
			Dept.:<?php echo $item->pr_of_department;?><br>
					<a style="color: black; font-size: 8pt;" href="<?php echo $this->baseUrl ?>/procurement/pr/process?pr_id=<?php echo $item->pr_id;?>"
				target="_blank">#<?php echo $item->auto_pr_number;?></a>
				</div>
		</td>
		<td><b><?php echo $item->name;?></b>
		
			
			
		</td>
		<td><?php echo $item->ordered_quantity;?></td>
		
		<td><?php echo $item->ordered_quantity;?></td>
		<td>
		<?php echo $item->delivered_quantity;?>
		</td>
		<td><?php echo $item->notified_quantity;?></td>
		<td><?php echo $item->confirmed_quantity;?></td>
		<td><?php echo $item->rejected_quantity;?></td>
		<td><?php echo $item->confirmed_balance;?></td>
		
		<td><?php echo $item->price;?></td>
		<td><?php echo ($item->price*$item->delivered_quantity);?></td>
		<td><?php echo $item->currency;?></td>
		
		<td>
		<a href="<?php echo $this->baseUrl ?>/procurement/vendor/show?id=<?php echo $item->vendor_id;?>" target="_blank"><?php echo $item->vendor_name;?></a>
<div style="color: gray; font-size: 8pt;">
			<?php echo $item->payment_method;?><br>
			</div>
</td>

		<td>
		<div style="color: gray; font-size: 8pt;">
				PR-Item: #<?php echo $item->pr_item_id;?><br>
				PO-Item: #<?php echo $item->po_item_id;?><br>
				<?php if($item->delivery_id>0):?>
				DO:<a style="color: black; font-size: 8pt;" href="<?php echo $this->baseUrl ?>/procurement/do/show?dn_id=<?php echo $item->delivery_id;?>" target="_blank">#<?php echo $item->delivery_id;?></a>
				<?php endif;?>
		</div>
		</td>

<?php endforeach; ?>

 			

</tbody>
</table>


<?php
	
	if (! is_null ( $paginator )) {
		
		// change it only
		$base = $this->baseUrl . '/procurement/gr/list';
		
		$_connector_symbol = '?';
		
		$last = $base . $_connector_symbol . 'page=' . $paginator->totalPages . '&perPage=' . $paginator->resultsPerPage;
		$first = $base . $_connector_symbol . 'page=1&perPage=' . $paginator->resultsPerPage;
		
		$p1 = ($paginator->page) - 1;
		$p2 = ($paginator->page) + 1;
		
		$prev = $base . $_connector_symbol . 'page=' . $p1 . '&perPage=' . $paginator->resultsPerPage;
		$next = $base . $_connector_symbol . 'page=' . $p2 . '&perPage=' . $paginator->resultsPerPage;
		
		echo '<ul class="pagination">';
		
		if ($paginator->page != 1 and $paginator->totalPages > 10) {
			echo '<li><a href="' . $first . '"> |< </a></li>';
			echo '<li><a href="' . $prev . '"> < </a></li>';
		}
		
		for($i = $paginator->minInPageSet; $i <= $paginator->maxInPageSet; $i ++) {
			
			$url = $base . $_connector_symbol . 'page=' . $i . '&perPage=' . $paginator->resultsPerPage;
			
			if ($i == $paginator->page) {
				echo '<li><a class="active" href="#">' . $i . '</a></li>';
			} else {
				echo '<li><a href="' . $url . '"> ' . $i . ' </a></li>';
			}
		}
		if ($paginator->page != $paginator->totalPages and $paginator->totalPages > 10) {
			echo '<li><a href="' . $next . '"> > </a></li>';
			echo '<li><a href="' . $last . '"> >| </a></li>';
		}
		echo '</ul>';
	}
	
	?>

<hr>

<form class="form-search"
	action="<?php echo $this->baseUrl ?>/inventory" method="get"
	enctype="multipart/form-data">
	<button type="submit" class="btn">
		<i class="icon-arrow-left"> </i> Back
	</button>
	
	
	<?php if($notified==0 and $balance>0):?>

	<button title="Submit PR to Procurment" class="btn btn-default"
			onclick="openDOConfirmation(1);" type="button">
			<i class="icon-ok"> </i> Notify 
		</button>
<?php endif;?>
	
</form>



	








<?php else: echo '<p> All goods receipt has been notified to requester! </p>'?>










<form class="form-search"
	action="<?php echo $this->baseUrl ?>/inventory" method="get"
	enctype="multipart/form-data">
	<button type="submit" class="btn">
		<i class="icon-arrow-left"> </i> Back
	</button>
</form>

<?php endif; ?>






	
	<!-- Modal -->
	<div id="myModal" class="modal hide" role="dialog">
	  <div class="modal-dialog">
	  	 <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h5 class="modal-title">Mascot International (Laos)</h5>
      </div>
	      <div class="modal-body">
	        <p>Do you want to Notify delivery <span id="submitted_id"></span>?</p>
	      </div>
	      
		  <div class="modal-footer">
	        <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
	        <button onclick="notifyDOItems();" type="button" class="btn btn-primary">OK</button>
	      </div>
	   </div>
	</div>
	
	
	<!-- Modal -->
	<div id="myModal1" class="modal hide" role="dialog">
	  <div class="modal-dialog">
	      <div class="modal-body">
	        <span id="modad_body_text">Working on it........Please Wait!</span>
	      </div>
	   </div>
	</div>
	
	<div id="myModal2" class="modal hide" role="dialog">
	  <div class="modal-dialog">
	  	 <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h5 class="modal-title">Mascot International (Laos)</h5>
      </div>
	      <div class="modal-body">
	      	<span id="cart_item_to_delete"></span>
	        <p>Do you want to delete this Item?</p>
	      </div>
	      
		  <div class="modal-footer">
	        <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
	        <button onclick="deleteDNCartItem();" type="button" class="btn btn-primary">DELETE</button>
	      </div>
	   </div>
	</div>			

	
		<div id="message_modal" class="modal hide" role="dialog">
	  <div class="modal-dialog">
	  		  	 <div class="modal-header">
        		<button type="button" class="close" data-dismiss="modal">&times;</button>
        <h5 class="modal-title">Mascot International (Laos)</h5>
      </div>
	  	
	      <div class="modal-body">
	        <span id="message_modal_content">Working on it........Please Wait!</span>
	      </div>
	       <div class="modal-footer">
	        <button type="button" class="btn btn-primary" data-dismiss="modal">OK</button>
	        </div>
	   </div>
	</div>
	