<?php /**@var \Application\Entity\NmtProcurePr $entity ;*/?>


<div id="wrapper" class="toggled">

	<!-- Sidebar -->
	<div id="sidebar-wrapper" style="font-size: 9.5pt;">
									<?php
        $current_step = "STEP1";
        include (ROOT . '/module/Procure/view/procure/pr-create-wizard.php');
        ?>


	</div>
	<!-- /#sidebar-wrapper -->

	<!-- Page Content -->
	<div id="page-content-wrapper"
		style="font-size: 9.5pt; padding: 0px; margin: 0px;">
		<div class="container-fluid" id="main_container"
			style="font-size: 9.5pt; padding: 1px; margin: 0px;";>
			<a style="font-size: 9pt; margin: 2px; padding: 3px;"
				href="#menu-toggle" class="btn btn-primary btn-sm" id="menu-toggle"><span
				title="Hide Menu"><i class="fa fa-chevron-left" aria-hidden="true"></i>
					Menu <span></a>


			<div id="tabs" style="font-size: 10pt">
				<ul>
					<li><a href="#general"><?php echo $this->translate("New Purchase Request");?>:</a></li>
				</ul>

				<div id="general" style="font-size: 9pt">
					<!-- Tab1 -->

	<?php
if (count ( $errors ) > 0) {
	echo '<div class="alert alert-danger alert-dismissible"" role="alert" style="font-size: 9.5pt"><a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>[ERROR]';
	
	echo '<ul>';
	foreach ( $errors as $error ) :
		echo '<li>' . $error . '</li>';
	endforeach
	;
	echo '</ul>';
	echo '</div>';
}
?>

			<form id="Create_PR_Form" class="form-horizontal" action="/procure/pr/add" method="post" enctype="multipart/form-data">
<input type="hidden" name="redirectUrl" value="<?php echo $redirectUrl ?>" />

	<div class="form-group margin-bottom">
		<label class="control-label col-sm-2" >PR Number:</label>
		<div class="col-sm-3">
			<input class="form-control input-sm" type="text"  placeholder=""
				name="prNumber" value="<?php echo (!$entity == null)? $entity->getPrNumber():"";?>">
		</div>
		
		<label class="control-label col-sm-1" for="inputTag"></label>
		<div class="col-sm-4">
<input <?php if(!$entity == null): echo ($entity->getIsActive()=="1")?"checked":""; else: echo "checked"; endif;?> type="checkbox" name="isActive" value="1">&nbsp;Active&nbsp;&nbsp;
<input <?php if(!$entity == null): echo ($entity->getIsDraft()=="1")?"checked":""; else: echo "checked"; endif;?> type="checkbox" name="isDraft" value="1">&nbsp;Draft&nbsp;&nbsp;

		</div>		
				
	</div>
	
	<div class="form-group margin-bottom">
		<label class="control-label col-sm-2" >PR Name:</label>
		<div class="col-sm-3">
			<input class="form-control input-sm" type="text"  placeholder=""
				id = "prName" name="prName" value="<?php echo (!$entity == null)? $entity->getPrName():"";?>">
		</div>
		
		<label class="control-label col-sm-2" >Keywords:</label>
		<div class="col-sm-3">
			<input class="form-control input-sm" type="text"  placeholder=""
				id = "keywords" name="keywords" value="<?php echo (!$entity == null)? $entity->getKeywords():"";?>">
		</div>
	</div>
	
	<div class="form-group margin-bottom">
		<label class="control-label col-sm-2" >Date:</label>
		<div class="col-sm-3">
<input class="form-control input-sm" type="text"  placeholder="" id = "submittedOn" name="submittedOn" 
value="<?php if(!$entity == null): if ($entity->getSubmittedOn() !== null): echo date_format($entity->getSubmittedOn(),"Y-m-d"); endif; endif;?>" placeholder =" please select"/>
		</div>
	</div>
	<div class="form-group margin-bottom">
		<label class="control-label col-sm-2" >Total Rows:</label>
		<div class="col-sm-3">
			<input class="form-control input-sm" type="text"  placeholder=""
				id = "totalRowManual" name="totalRowManual" value="<?php echo (!$entity == null)? $entity->getTotalRowManual():"";?>">
		</div>
		
	</div>
	
	
	<div class="form-group margin-bottom">
		<label class="control-label col-sm-2" >Department</label>
		<div class="col-sm-3">
<input disabled class="form-control input-sm" type="text" id="department_name" placeholder="Please select!" 
name="deparment_name" value="<?php if (!$entity== null):if($entity->getDepartment()!==null):echo $entity->getDepartment()->getNodeName(); endif;endif;?>">

<input type="hidden" class="form-control input-sm" type="text" id="department_name_selected" placeholder="Please select!" 
name="department_id" value="<?php if (!$entity== null):if($entity->getDepartment()!==null):echo $entity->getDepartment()->getNodeId(); endif;endif;?>">
			</div>
		
<a style="color: #0080ff;" href="javascript:;"
	onclick="showBootstrapDialog('Select Deparment','/application/department/list1','b_loaded_data');">Select&nbsp;&nbsp;<i class="glyphicon glyphicon-folder-open"></i>
</a>
    </div>
    
    <div class="form-group margin-bottom required">

							<label class="control-label col-sm-2"><?php echo $this->translate("Target Warehouse");?>:</label>
							<div class="col-sm-3">
								<select tabindex="9" name="wh_id" id="wh_id"
									class="form-control input-sm">
									<option value=""><?php echo $this->translate("Select Warehouse");?></option>
   	    							<?php
   	    	 if ($wh_list !== null) :
   	    	 foreach ($wh_list as $gl) :

                    /**@var \Application\Entity\NmtInventoryWarehouse $gl ; */

                    if ($entity !== null) :
                        if ($entity->getWarehouse() !== null) :
                        if ($entity->getWarehouse()->getId() == $gl->getId()) :
                            echo '<option selected value="' . $gl->getId() . '">' . $gl->getWhName() . '</option>';
                            else :
                            echo '<option value="' . $gl->getId() . '">' . $gl->getWhName() . '</option>';
                            endif;
                        else :
                        echo '<option value="' . $gl->getId() . '">' . $gl->getWhName() . '</option>';
                        endif;
                    else :
                    echo '<option value="' . $gl->getId() . '">' . $gl->getWhName()  . '</option>';
                    endif;
                endforeach
                ;
   	    							endif;

            ?>
   					</select>
							</div>	
							</div>
	
	<div class="form-group margin-bottom">
		<label class="control-label col-sm-2" >Remarks:</label>
		<div class="col-sm-3">
			<textarea  class="form-control input-sm" type="text" rows="4" placeholder=""
				name="remarks" style="font-size: 9pt;"><?php echo (!$entity == null)? $entity->getRemarks():"";?></textarea>
		</div>
	</div>
	
	<div class="form-group margin-bottom">
		<label class="control-label col-sm-2" for="inputTag"></label>
		<div class="col-sm-3">
	   	<button onclick="submitForm('Create_PR_Form');" class="btn btn-default btn-sm"><i class="glyphicon glyphicon-floppy-disk"> </i> Save</button>
  						<a class="btn btn-default btn-sm"
								href="<?php echo $redirectUrl; ?>"><small><i class="glyphicon glyphicon-remove"></i></small>&nbsp;Cancel</a>
		
  		</div>
	</div> 
		
	
</form>

				</div>

				<!-- end tab -->
			</div>
		</div>
	</div>
	<!-- /#page-content-wrapper -->

</div>
<!-- /#wrapper -->

<script>
$(function() {
   $( "input[id='submittedOn']").datepicker({ firstDay: 1, dateFormat: 'yy-mm-dd',closeText: 'X', changeMonth: true, changeYear: true});
});

</script>
