<div id="tabs" style="font-size: 9.5pt">

	<ul>
		<li><a href="#general">Purchase Requests</a></li>
	</ul>
<div id="general">

<div>
	<small><span class="glyphicon glyphicon-filter"></span></small>&nbsp;<a
		href="#transaction" class="" data-toggle="collapse">FILTER</a>
</div>
<div id="transaction" class="collapse">

	<div
		style="border: 1px; padding: 3px; font-size: 9pt; background: url(/images/bg1.png); background-repeat: repeat-x; background-color: #FFFFFF;">

		<form class="form-horizontal"
			action="<?php echo $this->baseUrl ?>/procure/pr/all<?php echo "/row_number=".$row_number?><?php echo $status!==null? "/status=".$status:"";?>" method="get"
			enctype="multipart/form-data">

			<div class="form-group margin-bottom">
				<label class="control-label col-sm-2" for="inputTag">PR Year</label>
				<div class="col-sm-3">
					<select name="pr_year"  class="form-control input-sm">
						<option value="0">All</option>
						<option <?php echo $pr_year=='2016'? "selected='selected'":"";?>
							value="2016">2016</option>
						<option <?php echo $pr_year=='2017'? "selected='selected'":"";?>
							value="2017">2017</option>
						<option <?php echo $pr_year=='2018'? "selected='selected'":"";?>
							value="2018">2018</option>
						<option <?php echo $pr_year=='2019'? "selected='selected'":"";?>
							value="2019">2019</option>
						<option <?php echo $pr_year=='2020'? "selected='selected'":"";?>
							value="2020">2020</option>
					</select>
				</div>
			</div>

			<div class="form-group margin-bottom">
				<label class="control-label col-sm-2" for="inputTag">PR Row Balance</label>
				<div class="col-sm-3">
					<select name="balance" class="form-control input-sm">
						<option value="2">All</option>
						<option <?php echo $balance=='0'? "selected='selected'":"";?>
							value="0">Balance=0 (Fulfilled PR)</option>
						<option <?php echo $balance=='1'? "selected='selected'":"";?>
							value="1">Balance>0 (Pending PR)</option>
					</select>
				</div>
			</div>

			<div class="form-group margin-bottom">
				<label class="control-label col-sm-2" for="inputTag">Active Items</label>
				<div class="col-sm-3">
					<select class="form-control input-sm" name="is_active">
						<option <?php echo $is_active =='2'? "selected='selected'":"";?>
							value="2">All</option>
						<option <?php echo $is_active=='1'? "selected='selected'":"";?>
							value="1">Active</option>
						<option <?php echo $is_active=='-1'? "selected='selected'":"";?>
							value="-1">Inactive</option>
					</select>
				</div>
			</div>
			
			<div class="form-group margin-bottom">
				<label class="control-label col-sm-2" for="inputTag">Sort by</label>
				<div class="col-sm-3">
					<select class="form-control input-sm" name="sort_by">
						<option value="">None</option>
						<option
							<?php echo $sort_by=='prNumber'? "selected='selected'":"";?>
							value="prNumber">Pr Number</option>
						<option
							<?php echo $sort_by=='submittedOn'? "selected='selected'":"";?>
							value="submittedOn">Submitted Date</option>	
						<option
							<?php echo $sort_by=='createdOn'? "selected='selected'":"";?>
							value="createdOn">Created Date</option>
						<option
							<?php echo $sort_by=='completion'? "selected='selected'":"";?>
							value="completion">Completion</option>
				
					</select> <input
						<?php if(!$sort==null): echo ($sort=='ASC')? "checked":""; else: echo "checked"; endif;?>
						type="radio" name="sort" value="ASC">&nbsp;ASC&nbsp;&nbsp; <input
						<?php if(!$sort==null): echo ($sort=='DESC')? "checked":""; else: echo ""; endif;?>
						type="radio" name="sort" value="DESC">&nbsp;DESC&nbsp;&nbsp;

				</div>
			</div>


			<div class="form-group margin-bottom">
				<label class="control-label col-sm-2" for="inputTag">Result per page</label>
				<div class="col-sm-3">
					<select class="form-control input-sm" name="perPage">
						<option value="">None</option>
						<option <?php echo $per_pape=='15'? "selected='selected'":"";?>
							value="15">15</option>

						<option <?php echo $per_pape=='20'? "selected='selected'":"";?>
							value="20">20</option>

						<option <?php echo $per_pape=='30'? "selected='selected'":"";?>
							value="30">30</option>

						<option <?php echo $per_pape=='50'? "selected='selected'":"";?>
							value="50">50</option>
						<option <?php echo $per_pape=='100'? "selected='selected'":"";?>
							value="100">100</option>
						<option <?php echo $per_pape=='200'? "selected='selected'":"";?>
							value="200">200</option>
					</select>
				</div>
			</div>

			<div class="form-group margin-bottom">
				<div class="col-sm-offset-2 col-sm-10">
					<button type="submit" class="btn btn-default">Show</button>
				</div>
			</div>

		</form>

	</div>
</div>


<div style="color: gray;font-size: 9pt;margin-top: 8px"><?php echo "Sorted by = ".$sort_by;?>. <?php echo "Sort = ".$sort ?></div>
<br>
<?php

if ($total_records <= 0) {
	
	echo 'No record found!';
} else {
	
	if (! is_null ( $paginator )) {
		echo 'Record ' . $paginator->minInPage . ' to ' . $paginator->maxInPage . ' | ' . $total_records . ' records found!';
	} else {
		echo $total_records . ' records found!';
	}
	
	?>




<table style="font-size: 10pt;" class="table table-bordered table-hover">
	<thead>
		<tr>
			<td><b>#</b></td>
			<td><b>PR Auto</b></td>
			<td><b>PR</b></td>
			<td><b>Date</b></td>
			<td><b>Total<br>Row</b></td>
			<td><b>Total<br>Added Row</b></td>
			<td><b>Completed<br>Row</b></td>
			<td><b>Pending<br>Row</b></td>
			<td><b>%</b></td>
			<td><b>Action</b></td>
		</tr>
	</thead>

	<tbody>
 
	 <?php
	
	$count = 0;
	foreach ( $list as $a ) :
		$count ++;
		?>
	<tr>
			<td><?php echo ($paginator===null)? $count:$paginator->minInPage -1+ $count;?></td>
			<td>
<a	style="color: gray;font-size: 9pt;" href="<?php echo $this->baseUrl ?>/procure/pr/show?token=<?php echo $a['pr_token'] ?>&entity_id=<?php echo $a['id'] ?>&checksum=<?php echo $a['pr_checksum'] ?>"><?php echo $a['pr_auto_number'] ?></a>
			</td>
	
			<td>
<a	href="<?php echo $this->baseUrl ?>/procure/pr/show?token=<?php echo $a['pr_token'] ?>&entity_id=<?php echo $a['id'] ?>&checksum=<?php echo $a['pr_checksum'] ?>"><?php echo $a['pr_number'] ?></a>
	</td>
			<td><?php echo $a['submitted_on'] ?></td>
			<td><?php echo $a['total_row_manual'] ?></td>
	
			<td><?php echo $a['total_row'] ?></td>
			<td><?php echo $a['row_completed'] ?></td>
			<td><?php echo $a['row_pending'] ?></td>
			<td><?php echo round($a['percentage_completed']*100,2)."%"?></td>
		

			<td><a
				href="<?php echo $this->baseUrl ?>/procure/pr/show?token=<?php echo $a['pr_token'] ?>&entity_id=<?php echo $a['id'] ?>&checksum=<?php echo $a['pr_checksum'] ?>">Show</a>
				<a
				href="<?php echo $this->baseUrl ?>/procure/pr/edit?token=<?php echo $a['pr_token'] ?>&entity_id=<?php echo $a['id'] ?>&checksum=<?php echo $a['pr_checksum'] ?>">Edit</a>
				<a href="javascript:;" onclick = "showJqueryDialog('<?php echo $a['pr_auto_number'].' - '. $a['pr_number'] ; ?>','1550',$(window).height()-50,'/procure/pr/show1?token=<?php echo $a['pr_token'] ?>&entity_id=<?php echo $a['id'] ?>&checksum=<?php echo $a['pr_checksum'] ?>','j_loaded_data',true);">Quick Show</a>
			</td>
		</tr>
<?php endforeach; ?>

 </tbody>
</table>

<?php
	
	// ===============================
	if (! is_null ( $paginator )) :
		
		// change it only
	$base = $this->baseUrl . '/procure/pr/all/row_number='.$row_number.'/status='.$status.'?is_active=' . $is_active . '&sort_by=' . $sort_by . '&sort=' . $sort. '&balance=' . $balance;
		$_connector_symbol = '&';
		
		$last = $base . $_connector_symbol . 'page=' . $paginator->totalPages . '&perPage=' . $paginator->resultsPerPage;
		$first = $base . $_connector_symbol . 'page=1&perPage=' . $paginator->resultsPerPage;
		
		$p1 = ($paginator->page) - 1;
		$p2 = ($paginator->page) + 1;
		
		$prev = $base . $_connector_symbol . 'page=' . $p1 . '&perPage=' . $paginator->resultsPerPage;
		$next = $base . $_connector_symbol . 'page=' . $p2 . '&perPage=' . $paginator->resultsPerPage;
		
		echo '<ul class="pagination pagination-sm">';
		
		if ($paginator->page != 1 and $paginator->totalPages > 10) {
			echo '<li><a href="' . $first . '"> |< </a></li>';
			echo '<li><a href="' . $prev . '"> < </a></li>';
		}
		
		for($i = $paginator->minInPageSet; $i <= $paginator->maxInPageSet; $i ++) {
			
			$url = $base . $_connector_symbol . 'page=' . $i . '&perPage=' . $paginator->resultsPerPage;
			
			if ($i == $paginator->page) {
				echo '<li><a class="active" href="#">' . $i . '</a></li>';
			} else {
				echo '<li><a href="' . $url . '"> ' . $i . ' </a></li>';
			}
		}
		if ($paginator->page != $paginator->totalPages and $paginator->totalPages > 10) {
			echo '<li><a href="' . $next . '"> > </a></li>';
			echo '<li><a href="' . $last . '"> >| </a></li>';
		}
		echo '</ul>';
endif;
	
}
// ===============================
?>
</div>
</div>

