<?php

/**
 *
 * @author Nguyen Mau Tri - ngmautri@gmail.com
 *         ===================================
 */
/**@var \Procure\Application\DTO\Pr\PrDTO $headerDTO ;*/
/**@var \Application\Controller\Plugin\NmtPlugin $nmtPlugin ;*/

/**
 *
 * @var GenericForm $form ;
 */

// ===========================================================
use Application\Application\Helper\ErrorMessage;
use Application\Form\Contracts\GenericForm;
use Procure\Form\PR\PRHeaderFormRender;

?>

<!-- /#wrapper -->
<div id="wrapper" class="toggled">
	<!-- Sidebar -->
	<div id="sidebar-wrapper" style="font-size: 9.5pt;">
	
		<?=$this->wizard;?>		
    
	</div>
	<!-- Sidebar -->

	<!-- Page Content -->
	<div id="page-content-wrapper"
		style="font-size: 9.5pt; padding: 0px; margin: 0px;">

		<!-- Content Container -->
		<div class="container-fluid" id="main_container"
			style="font-size: 9.5pt; padding: 1px; margin: 0px;";>
			<a style="font-size: 9pt; margin: 2px; padding: 3px;"
				href="#menu-toggle" class="btn btn-primary btn-sm" id="menu-toggle">
				<span title="Hide Menu"> <i class="fa fa-chevron-left"
					aria-hidden="true"></i> Menu <span>
			
			</a>
			<!-- TAB -->
			<div id="tabs" style="font-size: 10pt">
				<ul>
					<li><a href="#general">Create PR</a></li>
				</ul>
				<div id="general" style="font-size: 9pt">
				
<?php
echo ErrorMessage::showErrorMessage($errors);
echo $form->renderForView($this, new PRHeaderFormRender());
?>				
				</div>

			</div>
			<!-- TAB -->

		</div>
		<!-- Content Container -->

	</div>
	<!-- Page Content -->

</div>
<!-- /#wrapper -->
<script>
	$( "input[id='docDate']").datepicker({ firstDay: 1, dateFormat: 'yy-mm-dd',closeText: 'X',changeMonth: true, changeYear: true});
	$( "#prNumber" ).focus();
</script>