<?php

/**
 *
 * @author Nguyen Mau Tri - ngmautri@gmail.com
 *         ===================================
 */
/**@var \Procure\Application\DTO\Pr\PrDTO $headerDTO ;*/
/**@var \Application\Controller\Plugin\NmtPlugin $nmtPlugin ;*/

/**
 *
 * @var GenericForm $form ;
 */

// ===========================================================
use Application\Application\Helper\Form\FormHelper;
use Application\Form\Contracts\GenericForm;
$tabs = null;

if (! $headerDTO == null) {

    $picture_url = sprintf($this->baseUrl . "/procure/pr-attachment/get-pictures?target_id=%s&token=%s", $headerDTO->getId(), $headerDTO->getToken());
    $format = '/inventory/item-picture/list1?token=%s&target_id=%s';
    $url1 = sprintf($format, $headerDTO->getToken(), $headerDTO->getId());
    $picturesTab = sprintf('<a title="Picture" href="%s"><span class="glyphicon glyphicon-picture"></span>&nbsp;(%s)</a></li></a>', $picture_url, '');

    $format = '/inventory/item-attachment/list1?token=%s&target_id=%s';
    $url1 = sprintf($format, $headerDTO->getToken(), $headerDTO->getId());
    $attachment_url = sprintf($this->baseUrl . "/procure/pr-attachment/list1?target_id=%s&token=%s", $headerDTO->getId(), $headerDTO->getToken());
    $attachTab = sprintf('<a title="Serial" href="%s"><span class="glyphicon glyphicon-paperclip"></span>&nbsp;(%s)</a></li></a>', $attachment_url, '');

    $format = '/inventory/change-log/list1?object_token=%s&object_id=%s';
    $url1 = sprintf($format, $headerDTO->getToken(), $headerDTO->getId());
    $log_url = sprintf($this->baseUrl . "/application/message-store/list1?entity_id=%s&entity_token=%s", $headerDTO->getId(), $headerDTO->getToken());
    $logTab = sprintf('<a title="Change Log" href="%s"><span class="glyphicon glyphicon-list"></span>&nbsp;Log</a></li></a>', $log_url);

    $tabsList = [
        // $logisticTab,
        $picturesTab,
        $attachTab,
        $logTab
    ];

    $tabs = FormHelper::createTabs($tabsList);
}
?>

<!-- /#wrapper -->
<div id="wrapper" class="toggled">
	<!-- Sidebar -->
	<div id="sidebar-wrapper" style="font-size: 9.5pt;">
	
		<?=$this->sidebar_buttons;?>
		<?=$this->wizard;?>		
    
	</div>
	<!-- Sidebar -->

	<!-- Page Content -->
	<div id="page-content-wrapper"
		style="font-size: 9.5pt; padding: 0px; margin: 0px;">

		<!-- Content Container -->
		<div class="container-fluid" id="main_container"
			style="font-size: 9.5pt; padding: 1px; margin: 0px;";>
			<a style="font-size: 9pt; margin: 2px; padding: 3px;"
				href="#menu-toggle" class="btn btn-primary btn-sm" id="menu-toggle">
				<span title="Hide Menu"> <i class="fa fa-chevron-left"
					aria-hidden="true"></i> Menu <span>
			
			</a>
			<!-- TAB -->
			<div id="tabs" style="font-size: 10pt">
				<ul>
					<li><a href="#general">Create PR</a></li>
	<?php
echo $tabs;
?>
				</ul>
				<div id="general" style="font-size: 9pt">				
<?=$this->header_form;?>			
				</div>

			</div>
			<!-- TAB -->

		</div>
		<!-- Content Container -->

	</div>
	<!-- Page Content -->

</div>
<!-- /#wrapper -->
<script>
	$( "input[id='docDate']").datepicker({ firstDay: 1, dateFormat: 'yy-mm-dd',closeText: 'X',changeMonth: true, changeYear: true});
	$( "input[id='submittedOn']").datepicker({ firstDay: 1, dateFormat: 'yy-mm-dd',closeText: 'X',changeMonth: true, changeYear: true});
	$( "#prNumber" ).focus();
</script>