<?php
use Procure\Application\Helper\ErrorMessage;
use Procure\Application\Helper\OptionList;
use Procure\Domain\Shared\Constants;

/**
 *
 * @author Nguyen Mau Tri - ngmautri@gmail.com
 *         ===================================
 */
/**@var \Procure\Application\DTO\Pr\PrDTO $headerDTO ;*/
/**@var \Application\Controller\Plugin\NmtPlugin $nmtPlugin ;*/

$docStatus = null;
$wh_id = null;
$pmtTermId = null;
$currencyId = null;
$incotermId = null;
$departmentId = null;
$tabsList = null;

if (! $headerDTO == null) {
    $log_url = sprintf($this->baseUrl . "/application/message-store/list1?entity_id=%s&entity_token=%s", $headerDTO->getId(), $headerDTO->getToken());
    $review_url = sprintf($this->baseUrl . "/procure/pr/view?entity_id=%s&entity_token=%s", $headerDTO->getId(), $headerDTO->getToken());
    $wh_id = $headerDTO->getWarehouse();
    $pmtTermId = $headerDTO->getPmtTerm();
    $currencyId = $headerDTO->getDocCurrency();
    $incotermId = $headerDTO->getIncoterm();
    $departmentId = $headerDTO->getDepartment();

    $picture_url = sprintf($this->baseUrl . "/procure/pr-attachment/get-pictures?target_id=%s&token=%s", $headerDTO->getId(), $headerDTO->getToken());
    $format = '/inventory/item-picture/list1?token=%s&target_id=%s';
    $url1 = sprintf($format, $headerDTO->getToken(), $headerDTO->getId());
    $picturesTab = sprintf('<a title="Picture" href="%s"><span class="glyphicon glyphicon-picture"></span>&nbsp;(%s)</a></li></a>', $picture_url, '');

    $format = '/inventory/item-attachment/list1?token=%s&target_id=%s';
    $url1 = sprintf($format, $headerDTO->getToken(), $headerDTO->getId());
    $attachment_url = sprintf($this->baseUrl . "/procure/pr-attachment/list1?target_id=%s&token=%s", $headerDTO->getId(), $headerDTO->getToken());
    $attachTab = sprintf('<a title="Serial" href="%s"><span class="glyphicon glyphicon-paperclip"></span>&nbsp;(%s)</a></li></a>', $attachment_url, '');

    $format = '/inventory/change-log/list1?object_token=%s&object_id=%s';
    $url1 = sprintf($format, $headerDTO->getToken(), $headerDTO->getId());
    $log_url = sprintf($this->baseUrl . "/application/message-store/list1?entity_id=%s&entity_token=%s", $headerDTO->getId(), $headerDTO->getToken());
    $logTab = sprintf('<a title="Change Log" href="%s"><span class="glyphicon glyphicon-list"></span>&nbsp;Log</a></li></a>', $log_url);

    $tabsList = [
        // $logisticTab,
        $picturesTab,
        $attachTab,
        $logTab
    ];
}

$wh_option = OptionList::createWarehouseOption($nmtPlugin->warehouseList(), $wh_id);
$paymentTerm_option = OptionList::createPmtTermOption($nmtPlugin->getPaymentTerms(), $pmtTermId);
$incoterm_option = OptionList::createIncotermOption($nmtPlugin->incotermList(), $incotermId);
$currency_option = OptionList::createCurrencyOption($nmtPlugin->currencyList(), $currencyId);
$department_option = OptionList::createDepartmentOption($nmtPlugin->departmentList(), $departmentId);
$error_msg = ErrorMessage::showErrorMessage($errors);

$tabs = \Application\Application\Helper\FormHelper::createTabs($tabsList);

// ===========================================================
?>
<div id="wrapper" class="toggled">
   <!-- Sidebar -->
   <div id="sidebar-wrapper" style="font-size: 9.5pt;">
					<?php
    $current_step = "STEP1";
    include (ROOT . '/module/Procure/view/procure/pr-create-wizard.php');
    ?>


	</div>
   <!-- /#sidebar-wrapper -->
   <!-- Page Content -->
   <div id="page-content-wrapper" style="font-size: 9.5pt; padding: 0px; margin: 0px;">
      <div class="container-fluid" id="main_container" style="font-size: 9.5pt; padding: 1px; margin: 0px;";>
         <a style="font-size: 9pt; margin: 2px; padding: 3px;" href="#menu-toggle" class="btn btn-primary btn-sm" id="menu-toggle">
            <span title="Hide Menu">
               <i class="fa fa-chevron-left" aria-hidden="true"></i>
               Menu
               <span>

         </a>
         <div id="tabs" style="font-size: 10pt">
            <ul>
               <li>
                  <a href="#general"><?php
                echo $form_title;
                ?>:</a>
               </li>
                   <?php
                echo $tabs;
                ?>
            </ul>
            <div id="general" style="font-size: 9pt">
               <!-- Tab1 -->

<?php
// ==================
echo $error_msg;
// ==================
include (ROOT . '/module/Procure/view/procure/pr/_header.php');
?>



            </div>
            <!-- end tab -->
         </div>
      </div>
   </div>
   <!-- /#page-content-wrapper -->
</div>
<!-- /#wrapper -->
<script>

$( "input[id='submittedOn']").datepicker({ firstDay: 1, dateFormat: 'yy-mm-dd',closeText: 'X',changeMonth: true, changeYear: true});
$( "#docNumber" ).focus();

<?php
if ($docStatus == \Application\Model\Constants::DOC_STATUS_POSTED) :
    ?>
$("#Creating_Form :input").attr("disabled", "disabled");
$("#remarks").attr("disabled", false);
$("#entity_id").attr("disabled", false);
$("#entity_token").attr("disabled", false);
$("#submit").attr("disabled", false);
<?php
endif;

?>

</script>