<?php
use Procure\Application\Helper\ErrorMessage;
use Procure\Application\Helper\OptionList;

/**
 *
 * @author Nguyen Mau Tri - ngmautri@gmail.com
 *         ===========================================
 */

/**@var \Procure\Application\DTO\Pr\PrDTO $rootDto ;*/
/**@var \Procure\Application\DTO\Pr\PrRowDTO $dto ;*/
/**@var \Application\Controller\Plugin\NmtPlugin $nmtPlugin ;*/

// var_dump($rootDto);

// echo memory_get_usage();
$message_url = null;
$review_url = null;
$rowNumber = null;
$doc_wh_id = null;
$today = new DateTime();
$default_edt = $today->modify("7 days")->format("Y-m-d");

// var_dump($rootDto);
if ($rootDto !== null) {
    $target_id = $rootDto->getId();
    $target_token = $rootDto->getToken();

    $message_url = sprintf($this->baseUrl . "/application/message-store/list1?entity_token=%s&entity_id=%s", $target_token, $target_id);
    $review_url = sprintf($this->baseUrl . "/procure/pr/view?entity_id=%s&entity_token=%s", $target_id, $target_token);
    // $add_url = sprintf($this->baseUrl . "/procure/po/add-row?target_id=%s&token=%s", $target_id, $target_token);
    $rowNumber = $rootDto->getTotalRows() + 1;
    $doc_wh_id = $rootDto->getWarehouse();
}

$wh_id = null;
$gl_account = null;
$cost_center = null;
if ($dto !== null) {
    $rowNumber = $dto->getRowNumber();
    $wh_id = $dto->getWarehouse();
    $gl_account = $dto->getGlAccount();
    $cost_center = $dto->getCostCenter();

    if ($dto->getEdt() !== null) {
        $default_edt = $dto->getEdt();
    }
}

if ($wh_id == null) {
    $wh_id = $doc_wh_id;
}

$wh_option = OptionList::createWarehouseOption($nmtPlugin->warehouseList(), $wh_id);
$gl_option = OptionList::createGLAccountOption($nmtPlugin->glAccountList(), $gl_account);
$cost_center_option = OptionList::createCostCenterOption($nmtPlugin->costCenterList(), $cost_center);

$error_msg = ErrorMessage::showErrorMessage($errors);

// echo memory_get_usage();
// =====================================================
?>
<div id="wrapper" class="toggled">
   <!-- Sidebar -->
   <div id="sidebar-wrapper" style="font-size: 9.5pt;">

    	<?php
    $current_step = "STEP2";
    include (ROOT . '/module/Procure/view/procure/pr-create-wizard.php');
    ?>

      					<hr>
      <span style="color: gray; margin: 2pt 2pt 2pt 8pt"><?php

    echo $this->translate('Summary:');
    ?></span>
      <div class="alert alert-info" role="alert" style="padding: 2px; margin: 2pt 2pt 2pt 8pt; font-size: 9.2pt">
         <ul style="font-size: 9pt; margin: 0; padding-left: 15pt">
            <li>
               <b><?php

            if (! $rootDto == null) :
                echo $rootDto->getSysNumber(); endif;

            ?></b>
            </li>
            <li>-----</li>
            <li>Total rows:<?php

            if (! $rootDto == null) :
                echo $rootDto->getTotalRows(); endif;

            ?></li>
            <li>Status:<?php

            if (! $rootDto == null) :
                echo $rootDto->getTransactionStatus(); endif;

            ?> </li>
            <li>-----</li>
            <li>Created by: <?php

            if (! $rootDto == null) :
                echo $rootDto->getCreatedByName(); endif;

            ?></li>
         </ul>
      </div>
   </div>
   <!-- /#sidebar-wrapper -->
   <!-- Page Content -->
   <div id="page-content-wrapper" style="font-size: 9.5pt; padding: 0px; margin: 0px;">
      <div class="container-fluid" id="main_container" style="font-size: 9.5pt; padding: 1px; margin: 0px;";>
         <a style="font-size: 9pt; margin: 2px; padding: 3px;" href="#menu-toggle" class="btn btn-primary btn-sm" id="menu-toggle">
            <span title="Hide Menu">
               <i class="fa fa-chevron-left" aria-hidden="true"></i>
               Menu
               <span>
         
         </a>
         <div id="tabs" style="font-size: 10pt">
            <ul>
               <li>
                  <a href="#general"><?php

                echo $form_title;
                ?></a>
               </li>

<?php
if ($action == \Application\Model\Constants::FORM_ACTION_EDIT) :
    ?>
 	 	<li>
                  <a href=""<?php

    echo $message_url;
    ?>">
                     <span class="glyphicon glyphicon-list"></span>
                     &nbsp;Log
                  </a>
               </li>
<?php endif;

?>
				</ul>
            <div id="general" style="font-size: 9pt">
               <!-- Tab1 -->

<?php
// ================================
echo $error_msg;
// ===============================
?>

					<form id="New_Invoice_Row" class="form-horizontal" action="<?php

    echo $form_action;
    ?>" method="post" enctype="multipart/form-data">
                  <input type="hidden" name="redirectUrl" value="<?php

                echo $redirectUrl?>" />
                  <input type="hidden" id="target_id" name="target_id" value="<?php

                echo $target_id;
                ?>" />
                  <input type="hidden" id="target_token" name="target_token" value="<?php

                echo $target_token;
                ?>" />
                  <input type="hidden" name="version" value="<?php

                echo $version;
                ?>" />
                  <input type="hidden" id="entity_id" name="entity_id" value="<?php

                echo $entity_id;
                ?>" />
                  <input type="hidden" id="entity_token" name="entity_token" value="<?php

                echo $entity_token;
                ?>" />
                  <div class="form-group margin-bottom">
                     <label class="control-label col-sm-2">Row Number: </label>
                     <div class="col-sm-1">
                        <input tabindex="0" class="form-control input-sm" type="text" id="rowNumber" name="rowNumber" value="<?php

                        echo $rowNumber;
                        ?>">
                     </div>
                     <div class="col-sm-2">
                        <input
                           <?php

                        if (! $dto == null) :
                            echo ($dto->getIsActive() == "1") ? "checked" : "";
                        else :
                            echo "checked";
                        endif;
                        ?>
                           type="checkbox" name="isActive" value="1">
                        &nbsp;Is Active&nbsp;&nbsp;&nbsp;&nbsp;
                     </div>
                  </div>
                  <div class="form-group margin-bottom  required">
                     <label class="control-label col-sm-2">Item: </label>
                     <div class="col-sm-3">
                        <input tabindex="2" class="form-control" type="text" id="item_name" placeholder="Enter keyword to search item..." name="itemName"
                           value="<?php

                        if (! $dto == null) :
                            echo $dto->getItemName();endif;

                        ?>">
                        <input type="hidden" id="item_id" placeholder="" name="item" value="<?php

                        if (! $dto == null) :
                            echo $dto->getItem(); endif;

                        ?>">
                        <div id="item_url" style="display: none;"></div>
                     </div>
                     <div class="col-sm-1" style="margin: 0px">
                        <span title="<?php

                        echo $this->translate("Item Detail");
                        ?>" id="item_detail" style="display: none;">
                           &nbsp;&nbsp;
                           <a style="color: #0080ff;" href="javascript:;" onclick="showSelectedItem();">
                              <i style="color: navy" class="fa fa-info-circle fa-lg" aria-hidden="true"></i>
                           </a>
                           <br>
                        </span>
                     </div>
                     <div class="col-sm-1" style="margin: 0px">
                        <a style="color: #0080ff;" href="javascript:;" onclick="showJqueryDialog('Select Item','1350',$(window).height()-50, '/inventory/item-search/do1?target_id=item_id&target_name=item_name','j_loaded_data', true);">
                           Select&nbsp;&nbsp;
                           <i class="glyphicon glyphicon-folder-open"></i>
                        </a>
                     </div>
                     <div class="col-sm-1">
                        <a target="_blank" style="font-size: 9pt;" href="/inventory/item/list">Item List&nbsp;&nbsp;</a>
                        <small>
                           <i class="glyphicon glyphicon-new-window"></i>
                        </small>
                     </div>
                  </div>
                  <div class="form-group margin-bottom">
                     <label class="control-label col-sm-2" for="inputTag">Vendor Item Name:</label>
                     <div class="col-sm-3">
                        <input tabindex="3" class="form-control input-sm" type="text" id="vendorItemName" name="vendorItemName" value="<?php

                        echo (! $dto == null) ? $dto->getVendorItemName() : "";
                        ?>">
                     </div>
                     <label class="control-label col-sm-2" for="inputTag">Vendor Item Code:</label>
                     <div class="col-sm-3">
                        <input tabindex="3" class="form-control input-sm" type="text" id="vendor_item_code" name="vendorItemCode" value="<?php

                        echo (! $dto == null) ? $dto->getVendorItemCode() : "";
                        ?>">
                     </div>
                  </div>
                  <hr style="margin: 5pt 1pt 5pt 1pt;">
                  <div class="form-group margin-bottom required">
                     <label class="control-label col-sm-2" for="inputTag">Quantity:</label>
                     <div class="col-sm-3">
                        <input tabindex="4" class="form-control input-sm" type="text" id="quantity" name="docQuantity" value="<?php

                        echo (! $dto == null) ? $dto->getDocQuantity() : "";
                        ?>">
                     </div>
                     <div class="col-sm-3">
                        <div style="color: graytext; padding-bottom: 5px;" id="purchase_uom_convert_factor"></div>
                     </div>
                  </div>
                  <div class="form-group margin-bottom required">
                     <label class="control-label col-sm-2" for="inputTag">Unit:</label>
                     <div class="col-sm-3">
                        <input tabindex="5" class="form-control input-sm" type="text" name="docUnit" id="rowUnit" value="<?php

                        echo (! $dto == null) ? $dto->getDocUnit() : "each";
                        ?>">
                     </div>
                     <label class="control-label col-sm-2" for="inputTag">Converstion Factor:</label>
                     <div class="col-sm-1">
                        <input tabindex="6" class="form-control input-sm" type="text" name="conversionFactor" value="<?php

                        echo (! $dto == null) ? $dto->getConversionFactor() : "1";
                        ?>">
                     </div>
                     <div class="col-sm-3">
                        <span style="color: graytext; padding-bottom: 5px; margin: 0 0 0 10pt; font-size: 8.5pt" id="">Converstion to order unit (see PR).</span>
                     </div>
                  </div>
                  <hr style="margin: 5pt 1pt 5pt 1pt;">
                  <div class="form-group margin-bottom required">
                     <label class="control-label col-sm-2 required">Expected Date:</label>
                     <div class="col-sm-3">
                        <input class="form-control input-sm" type="text" id="edt" name="edt" value="<?php
                        echo $default_edt;
                        ?>" placeholder=" please select" />
                     </div>
                  </div>
                  <div class="form-group margin-bottom required">
                     <label class="control-label col-sm-2"><?php
                    echo $this->translate("Target Warehouse");
                    ?>:</label>
                     <div class="col-sm-3">
                        <select tabindex="9" name="warehouse" id="target_wh_id" class="form-control input-sm">
                           <option value=""><?php
                        echo $this->translate("...");
                        ?></option>
<?php
// ================
echo $wh_option;
// ================
?>
                                        </select>
                     </div>
                  </div>
                  <hr style="margin: 5pt 1pt 5pt 1pt;">
                  <div class="form-group margin-bottom">
                     <label class="control-label col-sm-2">Remark:</label>
                     <div class="col-sm-3">
                        <input tabindex="11" class="form-control input-sm" type="text" placeholder="" name="remarks" value="<?php

                        echo (! $dto == null) ? $dto->getRemarks() : "";
                        ?>">
                     </div>
                  </div>
                  <div class="form-group margin-bottom">
                     <label class="control-label col-sm-2">Description:</label>
                     <div class="col-sm-4">
                        <textarea class="form-control input-sm" type="text" rows="6" placeholder="" name="descriptionText" style="font-size: 9pt;"><?php

                        echo (! $dto == null) ? $dto->getDescriptionText() : "";
                        ?></textarea>
                     </div>
                  </div>
                  <hr style="margin: 5pt 1pt 5pt 1pt">
                  <div class="form-group margin-bottom" style="margin-top: 10pt">
                     <label class="control-label col-sm-2" for="inputTag"></label>
                     <div class="col-sm-3">
                        <a tabindex="11" class="btn btn-default btn-sm" onclick="submitForm('New_Invoice_Row');" href="javascript:;">
                           <small>
                              <i class="glyphicon glyphicon-floppy-disk"></i>
                           </small>&nbsp;<?php

                        echo $this->translate("Save");
                        ?></a>
                        <a tabindex="12" class="btn btn-default btn-sm" href="<?php

                        echo $review_url;
                        ?>">
                           <small>
                              <i class="glyphicon glyphicon-remove"></i>
                           </small>&nbsp;<?php

                        echo $this->translate("Cancel");
                        ?></a>
                     </div>
                     <div class="col-sm-3"></div>
                  </div>
               </form>
            </div>
            <!-- end tab -->
         </div>
      </div>
   </div>
   <!-- /#page-content-wrapper -->
</div>
<!-- /#wrapper -->
<script type="text/javascript">

$( "input[id='edt']").datepicker({ firstDay: 1, dateFormat: 'yy-mm-dd',closeText: 'X',changeMonth: true, changeYear: true});
$( "#item_name" ).focus();





        // if select item, then delete all pr item
        $( "#item_name" ).autocomplete({
            source: "/inventory/item-search/auto-complete",
            minLength: 2,
            select: function( event, ui ) {

              // set pr row empty
              $( "#item_id" ).val(ui.item.id);

              $('#item_url').text('/inventory/item/show1?tab_idx=7&entity_id='+ui.item.id+'&token='+ui.item.token);


          	 	$('#global-notice').show();
          		$('#global-notice').html('"' + ui.item.value + '" selected');
          		$('#global-notice').fadeOut(5000);
          		//$("#jquery_dialog").dialog("close");

           	  	$('#item_detail').show();
            	$( "#quantity" ).focus();

            }

          })
          .autocomplete( "instance" )._renderItem = function( ul, item ) {
        	  var serial_no = "";
        	  if(item.item_serial!=""){
        		  serial_no = " : " + item.item_serial;
        	  }

        	  var img = '<img class="img-rounded" width="60" height="60" src="'+item.item_thumbnail+'"/>';
                  

             return $( "<li>" )
               .append( "<div style='padding-bottom: 5px; border-bottom: thin solid gray;'><table><tr><td>"+img+"</td><td><span style='padding-left:5px; font-size: 9.5pt;font-weight: bold;'>" + item.value + "</span><br><span style='padding-left:5px; color:gray;font-size: 9pt;'>" + item.item_sku + serial_no +"<span></td></tr></table></div>" )
               .appendTo( ul );
           };
      
         $( function() {
             $( "#vendor_name" ).autocomplete({
              source: "/bp/vendor-search/auto-complete",
              minLength: 3,
              select: function( event, ui ) {
            	  $( "#vendor_id" ).val(ui.item.id);
                //alert	( "Selected: " + ui.item.value + " aka " + ui.item.id );
            	  //alert($( "#vendor_id" ).val());

            	 	$('#global-notice').show();
            		$('#global-notice').html('"' + ui.item.value + '" selected');
            		$('#global-notice').fadeOut(5000);
            		//$("#jquery_dialog").dialog("close");
              }
              })
              .autocomplete( "instance" )._renderItem = function( ul, item ) {
              return $( "<li>" )
                .append( "<div style='padding-bottom: 5px; border-bottom: thin solid gray;'>" + item.value + "<br><span style='color:gray;font-size: 9pt;'>" + item.vendor_country + "<span></div>" )
                .appendTo( ul );
            };
              ;
         } );

        function showSelectedItem(){
    		var url= $('#item_url').text();
    	   	showJqueryDialog('Item Detail','1450',$(window).height()-40, url,'j_loaded_data', true);
    	}

        function showSelectedPrRow(){
    		var url= $('#pr_row_url').text();
    	   	showJqueryDialog('PR Row Detail','1450',$(window).height()-40, url,'j_loaded_data', true);
    	}

        <?php
        if ($dto !== null) :
            ?>
        		  $("#item_id" ).val(<?php

            echo $dto->getItem();
            ?>);
        	      $('#item_url').text('/inventory/item/show1?tab_idx=0&entity_id=<?php

            echo $dto->getItem();
            ?>&token=<?php

            echo $dto->getItemToken();
            ?>');
        		  $('#item_detail').show();
        		  $("#pr_row_id" ).val(<?php

            echo $dto->getPrRow();
            ?>);
          	      $('#pr_row_url').text('/procure/pr-row/show1?tab_idx=0&entity_id=<?php

            echo $dto->getPrRow();
            ?>');
          	      $('#pr_row_detail').show();
        <?php
       	 endif
        ?>
        
        
        
  
    function selectItem(id, token,target, name, target_name, context = null){
    	var target_id = '#' + target;
    	$(target_id).val(id);

        var target_name_id = '#' + target_name;
    	$(target_name_id).val(name);
    	$('#modal1.close').click();
    	$('#global-notice').show();
    	$('#global-notice').html('"' + name + '" selected');
    	$('#global-notice').fadeOut(5000);
    	$("#jquery_dialog").dialog("close");


        $("#item_id" ).val(id);
    	  	$('#item_url').text('/inventory/item/show1?tab_idx=9&entity_id='+id+'&token='+token);

    		$('#item_detail').show();
    		$("#quantity").focus();

    	var url = '/inventory/item/get-item?id='+id;
    		$('#rowUnit').val("Loading...");
    		$('#purchase_uom_convert_text').text("Loading...");

    	$.get(url, {   	}, function(data, status) {
        		//alert(data.purchase_uom_code);
        		$('#rowUnit').val(data.purchase_uom_code);
        		$('#standard_uom_id').text(data.uom_code);
        		$('#conversionFactor').val(data.purchase_uom_convert_factor);
                $('#purchase_uom_convert_text').text($( "#rowUnit" ).val() + " = " +  $('#conversionFactor').val() + " " + $( "#standard_uom_id" ).text());

       	});
    }


     </script>