<?php
use Application\Application\Helper\OptionHelper;
use Procure\Application\Helper\ErrorMessage;
use Procure\Application\Helper\FormHelper;
use Procure\Application\Helper\OptionList;

/**
 *
 * @author Nguyen Mau Tri - ngmautri@gmail.com
 *         ===========================================
 */

/**@var \Procure\Application\DTO\Pr\PrDTO $headerDTO ;*/
/**@var \Procure\Application\DTO\Pr\PrRowDTO $dto ;*/
/**@var \Application\Controller\Plugin\NmtPlugin $nmtPlugin ;*/

// var_dump($headerDTO);

// echo memory_get_usage();
$message_url = null;
$review_url = null;
$rowNumber = null;
$doc_wh_id = null;
$today = new DateTime();
$default_edt = $today->modify("10 days")->format("Y-m-d");
$transactionStatus = "";
$progress_div = '';
$alert = "info";
$tabsList = null;
$docUomName = null;

// var_dump($headerDTO);
if ($headerDTO != null) {

    if ($headerDTO->getTotalRows() > 0) {
        $completion = $headerDTO->getCompletedRows() / $headerDTO->getTotalRows();
    } else {
        $completion = 0;
    }

    $progress_div = FormHelper::createProgressDiv($completion, 'completed.');

    $transactionStatus = sprintf('<span style="color:red;">%s</span>', $headerDTO->getTransactionStatus());

    if ($headerDTO->getTransactionStatus() == "completed") {
        $transactionStatus = sprintf('<span style="color:green;">%s</span>', $headerDTO->getTransactionStatus());
        $alert = "success";
    }

    if ($headerDTO->getTransactionStatus() == "completed") {
        $transactionStatus = sprintf('<span style="color:green;">%s</span>', $headerDTO->getTransactionStatus());
        $alert = "success";
    }

    $target_id = $headerDTO->getId();
    $target_token = $headerDTO->getToken();

    $message_url = sprintf($this->baseUrl . "/application/message-store/list1?entity_token=%s&entity_id=%s", $target_token, $target_id);
    $review_url = sprintf($this->baseUrl . "/procure/pr/view?entity_id=%s&entity_token=%s", $target_id, $target_token);
    // $add_url = sprintf($this->baseUrl . "/procure/po/add-row?target_id=%s&token=%s", $target_id, $target_token);
    $rowNumber = $headerDTO->getTotalRows() + 1;
    $doc_wh_id = $headerDTO->getWarehouse();

    $picture_url = sprintf($this->baseUrl . "/procure/pr-attachment/get-pictures?target_id=%s&token=%s", $headerDTO->getId(), $headerDTO->getToken());
    $format = '/inventory/item-picture/list1?token=%s&target_id=%s';
    $url1 = sprintf($format, $headerDTO->getToken(), $headerDTO->getId());
    $picturesTab = sprintf('<a title="Picture" href="%s"><span class="glyphicon glyphicon-picture"></span>&nbsp;(%s)</a></li></a>', $picture_url, '');

    $format = '/inventory/item-attachment/list1?token=%s&target_id=%s';
    $url1 = sprintf($format, $headerDTO->getToken(), $headerDTO->getId());
    $attachment_url = sprintf($this->baseUrl . "/procure/pr-attachment/list1?target_id=%s&token=%s", $headerDTO->getId(), $headerDTO->getToken());
    $attachTab = sprintf('<a title="Serial" href="%s"><span class="glyphicon glyphicon-paperclip"></span>&nbsp;(%s)</a></li></a>', $attachment_url, '');

    $format = '/inventory/change-log/list1?object_token=%s&object_id=%s';
    $url1 = sprintf($format, $headerDTO->getToken(), $headerDTO->getId());
    $log_url = sprintf($this->baseUrl . "/application/message-store/list1?entity_id=%s&entity_token=%s", $headerDTO->getId(), $headerDTO->getToken());
    $logTab = sprintf('<a title="Change Log" href="%s"><span class="glyphicon glyphicon-list"></span>&nbsp;Log</a></li></a>', $log_url);

    $tabsList = [
        // $logisticTab,
        $picturesTab,
        $attachTab,
        $logTab
    ];
}

$tabs = \Application\Application\Helper\FormHelper::createTabs($tabsList);

$wh_id = null;
$gl_account = null;
$cost_center = null;
if ($dto !== null) {
    $rowNumber = $dto->getRowNumber();
    $wh_id = $dto->getWarehouse();
    $gl_account = $dto->getGlAccount();
    $cost_center = $dto->getCostCenter();

    if ($dto->getEdt() !== null) {
        $default_edt = $dto->getEdt();
    }

    $docUomName = $dto->getDocUnit();
}

if ($wh_id == null) {
    $wh_id = $doc_wh_id;
}

$wh_option = OptionList::createWarehouseOption($nmtPlugin->warehouseList(), $wh_id);
$gl_option = OptionList::createGLAccountOption($nmtPlugin->glAccountList(), $gl_account);
$cost_center_option = OptionList::createCostCenterOption($nmtPlugin->costCenterList(), $cost_center);
$uomList = $sharedCollection->getUomCollection();
$uom_option = OptionHelper::createUomNameOption($uomList, $docUomName);

$error_msg = ErrorMessage::showErrorMessage($errors);

// echo memory_get_usage();
// =====================================================
?>
<div id="wrapper" class="toggled">
   <!-- Sidebar -->
   <div id="sidebar-wrapper" style="font-size: 9.5pt; padding-left: 20px;">

   <?php

// include (ROOT . '/module/Procure/view/procure/pr_summary.php');
?>

      <form class="form-inline" action="" method="get" onsubmit="return toSubmit();" enctype="multipart/form-data">
         <div class="form-group" style="padding-left: 0px;">
            <input placeholder="Search term ..." id="search_term_id" class="form-control" size="10" type="text" name="q" onkeypress="return runScript(event)">
         </div>
         <div class="form-group">
            <button style="font-size: 9pt" ; class="btn btn-default" onclick="doSearch();">
               <small>
                  <i class="glyphicon glyphicon-search"> </i>
               </small>
            </button>
         </div>
      </form>
      <div id="search_result_id"></div>
   </div>
   <!-- /#sidebar-wrapper -->
   <!-- Page Content -->
   <div id="page-content-wrapper" style="font-size: 9.5pt; padding: 0px; margin: 0px;">
      <div class="container-fluid" id="main_container" style="font-size: 9.5pt; padding: 1px; margin: 0px;";>
         <a style="font-size: 9pt; margin: 2px; padding: 3px;" href="#menu-toggle" class="btn btn-primary btn-sm" id="menu-toggle">
            <span title="Hide Menu">
               <i class="fa fa-chevron-left" aria-hidden="true"></i>
               Menu
               <span>

         </a>
         <div id="tabs" style="font-size: 10pt">
            <ul>
               <li>
                  <a href="#general"><?php

                echo $form_title;
                ?></a>
               </li>
<?php
echo $tabs;
?>
				</ul>
            <div id="general" style="font-size: 9pt">
               <!-- Tab1 -->

<?php
// ================================
echo $error_msg;
// ===============================
?>

  <div class="row">
                  <div class="col-sm-10" style="">
                     <form id="New_Invoice_Row" class="form-horizontal" action="<?php

                    echo $form_action;
                    ?>" method="post" enctype="multipart/form-data">
                        <input type="hidden" name="redirectUrl" value="<?php

                        echo $redirectUrl?>" />
                        <input type="hidden" id="target_id" name="target_id" value="<?php

                        echo $target_id;
                        ?>" />
                        <input type="hidden" id="target_token" name="target_token" value="<?php

                        echo $target_token;
                        ?>" />
                        <input type="hidden" name="docRevisionNo" value="<?php

                        echo $docRevisionNo;
                        ?>" />
                        <input type="hidden" id="entity_id" name="entity_id" value="<?php

                        echo $entity_id;
                        ?>" />
                        <input type="hidden" id="entity_token" name="entity_token" value="<?php

                        echo $entity_token;
                        ?>" />
                        <div class="form-group margin-bottom">
                           <label class="control-label col-sm-2">Row Number: </label>
                           <div class="col-sm-1">
                              <input tabindex="0" class="form-control input-sm" type="text" id="rowNumber" name="rowNumber" value="<?php

                            echo $rowNumber;
                            ?>">
                           </div>
                           <div class="col-sm-2">
                              <input
                                 <?php

                                if (! $dto == null) :
                                    echo ($dto->getIsActive() == "1") ? "checked" : "";
                                else :
                                    echo "checked";
                                endif;
                                ?>
                                 type="checkbox" name="isActive" value="1">
                              &nbsp;Is Active&nbsp;&nbsp;&nbsp;&nbsp;
                           </div>
                        </div>
                        <div class="form-group margin-bottom  required">
                           <label class="control-label col-sm-2">Item: </label>
                           <div class="col-sm-3">
                              <input tabindex="2" class="form-control" type="text" id="item_name" placeholder="Enter keyword to search item..." name="itemName"
                                 value="<?php

                                if (! $dto == null) :
                                    echo $dto->getItemName();endif;

                                ?>">
                              <input type="hidden" id="item" placeholder="" name="item" value="<?php

                            if (! $dto == null) :
                                echo $dto->getItem(); endif;

                            ?>">
                              <div id="item_url" style="display: none;"></div>
                           </div>
                           <div class="col-sm-1" style="margin: 0px">
                              <span title="<?php

                            echo $this->translate("Item Detail");
                            ?>" id="item_detail" style="display: none;">
                                 &nbsp;&nbsp;
                                 <a style="color: #0080ff;" href="javascript:;" onclick="showSelectedItem();">
                                    <i style="color: navy" class="fa fa-info-circle fa-lg" aria-hidden="true"></i>
                                 </a>
                                 <br>
                              </span>
                           </div>
                           <div class="col-sm-1" style="margin: 0px">
                              <a style="color: #0080ff;" href="javascript:;" onclick="showJqueryDialog('Select Item','1350',$(window).height()-50, '/inventory/item-search/do1?target_id=item_id&target_name=item_name','j_loaded_data', true);">
                                 Select&nbsp;&nbsp;
                                 <i class="glyphicon glyphicon-folder-open"></i>
                              </a>
                           </div>
                           <div class="col-sm-1">
                              <a target="_blank" style="font-size: 9pt;" href="/inventory/item/list">Item List&nbsp;&nbsp;</a>
                              <small>
                                 <i class="glyphicon glyphicon-new-window"></i>
                              </small>
                           </div>
                        </div>
                        <div class="form-group margin-bottom">
                           <label class="control-label col-sm-2" for="inputTag">Vendor Item Name:</label>
                           <div class="col-sm-3">
                              <input tabindex="3" class="form-control input-sm" type="text" id="vendorItemName" name="vendorItemName" value="<?php

                            echo (! $dto == null) ? $dto->getVendorItemName() : "";
                            ?>">
                           </div>
                           <label class="control-label col-sm-2" for="inputTag">Vendor Item Code:</label>
                           <div class="col-sm-3">
                              <input tabindex="3" class="form-control input-sm" type="text" id="vendor_item_code" name="vendorItemCode" value="<?php

                            echo (! $dto == null) ? $dto->getVendorItemCode() : "";
                            ?>">
                           </div>
                        </div>
                        <hr style="margin: 5pt 1pt 5pt 1pt;">
                        <div class="form-group margin-bottom required">
                           <label class="control-label col-sm-2" for="inputTag">Quantity:</label>
                           <div class="col-sm-3">
                              <input tabindex="4" class="form-control input-sm" type="text" id="quantity" name="docQuantity" value="<?php

                            echo (! $dto == null) ? $dto->getDocQuantity() : "";
                            ?>">
                           </div>
                           <div class="col-sm-3">
                              <div style="color: graytext; padding-bottom: 5px;" id="purchase_uom_convert_factor"></div>
                           </div>
                        </div>
                        <div class="form-group margin-bottom required">
                             <label class="control-label col-sm-2"><?php

                            echo $this->translate("Document Unit");
                            ?></label>
                     <div class="col-sm-3">
                        <select tabindex="5" name="docUnit" id="docUnit" class="form-control input-sm">
                           <option     value=""><?php

                        echo $this->translate("Select doc unit");
                        ?></option>
                    <?php
                    echo $uom_option;
                    ?>
               </select>
                     </div>
                           <label class="control-label col-sm-2" for="inputTag">Converstion Factor:</label>
                           <div class="col-sm-1">
                              <input tabindex="6" class="form-control input-sm" type="text" name="standardConvertFactor" value="<?php

                            echo (! $dto == null) ? $dto->getStandardConvertFactor() : "1";
                            ?>">
                           </div>
                           <div class="col-sm-3">
                              <span style="color: graytext; padding-bottom: 5px; margin: 0 0 0 10pt; font-size: 8.5pt" id="">Converstion to order unit (see PR).</span>
                           </div>
                        </div>
                        <hr style="margin: 5pt 1pt 5pt 1pt;">
                        <div class="form-group margin-bottom required">
                           <label class="control-label col-sm-2 required">Expected Date:</label>
                           <div class="col-sm-3">
                              <input class="form-control input-sm" type="text" id="edt" name="edt" value="<?php
                            echo $default_edt;
                            ?>" placeholder=" please select" />
                           </div>
                        </div>
                        <div class="form-group margin-bottom required">
                           <label class="control-label col-sm-2"><?php
                        echo $this->translate("Target Warehouse");
                        ?>:</label>
                           <div class="col-sm-3">
                              <select tabindex="9" name="warehouse" id="target_wh_id" class="form-control input-sm">
                                 <option value=""><?php
                                echo $this->translate("...");
                                ?></option>
<?php
// ================
echo $wh_option;
// ================
?>
                                        </select>
                           </div>
                        </div>
                        <hr style="margin: 5pt 1pt 5pt 1pt;">
                        <div class="form-group margin-bottom">
                           <label class="control-label col-sm-2">Remark:</label>
                           <div class="col-sm-3">
                              <input tabindex="11" class="form-control input-sm" type="text" placeholder="" name="remarks" value="<?php

                            echo (! $dto == null) ? $dto->getRemarks() : "";
                            ?>">
                           </div>
                        </div>
                        <div class="form-group margin-bottom">
                           <label class="control-label col-sm-2">Description:</label>
                           <div class="col-sm-4">
                              <textarea class="form-control input-sm" type="text" rows="6" placeholder="" name="descriptionText" style="font-size: 9pt;"><?php

                            echo (! $dto == null) ? $dto->getDescriptionText() : "";
                            ?></textarea>
                           </div>
                        </div>
                        <hr style="margin: 5pt 1pt 5pt 1pt">
                        <div class="form-group margin-bottom" style="margin-top: 10pt">
                           <label class="control-label col-sm-2" for="inputTag"></label>
                           <div class="col-sm-3">
                              <a tabindex="11" class="btn btn-default btn-sm" onclick="submitForm('New_Invoice_Row');" href="javascript:;">
                                 <small>
                                    <i class="glyphicon glyphicon-floppy-disk"></i>
                                 </small>&nbsp;<?php

                                echo $this->translate("Save");
                                ?></a>
                              <a tabindex="12" class="btn btn-default btn-sm" href="<?php

                            echo $review_url;
                            ?>">
                                 <small>
                                    <i class="glyphicon glyphicon-remove"></i>
                                 </small>&nbsp;<?php

                                echo $this->translate("Cancel");
                                ?></a>
                           </div>
                           <div class="col-sm-3"></div>
                        </div>
                     </form>
                     <!-- COL 1 -->
                  </div>
                  <!-- COL 2 -->
                  <div class="col-sm-2" style="background-color: white;">
                     <div id="item_img"></div>
                  </div>
                  <!-- ROW -->
               </div>
               <!-- end tab -->
            </div>
         </div>
      </div>
      <!-- /#page-content-wrapper -->
   </div>
   <!-- /#wrapper -->
   <script type="text/javascript">

$( "input[id='edt']").datepicker({ firstDay: 1, dateFormat: 'yy-mm-dd',closeText: 'X',changeMonth: true, changeYear: true});
$( "#item_name" ).focus();

    function doSearch(){
        var q =      $('#search_term_id').val();
        var url = '/inventory/item-search/do3?q=' + q;
        doSearching(url,'search_result_id');
    }

    function runScript(e) {
	    //See notes about 'which' and 'key'
	    if (e.keyCode == 13) {
		    doSearch();

	    }
	}

    function toSubmit(){
	      return false;
	   }

</script>

     <?php
    include (ROOT . '/module/Inventory/view/inventory/item_auto_complete.php');
    ?>