<?php /**@var \Application\Entity\NmtProcurePr $entity ;*/?>


<?php
if (count ( $errors ) > 0) {
	echo '<div class="alert alert-danger" role="alert" style="font-size: 10.5pt">';
	
	echo '<ul>';
	foreach ( $errors as $error ) :
	echo '<li>' . $error . '</li>';
	endforeach
	;
	echo '</ul>';
	echo '</div>';
}
?>

<div>
<h4><a href="/procure/pr/show?token=<?php if(!$entity == null):echo $entity->getToken(); endif;?>&entity_id=<?php if(!$entity == null):echo $entity->getId(); endif;?>"><?php echo (!$entity == null)?$entity->getPrNumber():"";?></a>
<span style="color: gray; font-size: 10pt"><?php echo (!$entity == null)? " // PR #" . $entity->getPrAutoNumber() :"";?></span></h4>
</div>

<div id="tabs" style="font-size: 9.5pt"> 
  <ul>
  <li ><a href="#general">Edit Purchase Request</a></li>
   </ul>

<div id="general" style="font-size: 9pt"> 

<!-- UPDATE -->
<form id="Edit_PR_Form" class="form-horizontal" action="/procure/pr/edit" method="post" enctype="multipart/form-data">
<input type="hidden" name="redirectUrl" value="<?php echo $redirectUrl ?>" />
<input type="hidden" name="entity_id" value="<?php echo (!$entity== null)? $entity->getId():"";?>" />
<input type="hidden" name="token" value="<?php echo (!$entity== null)? $entity->getToken():"";?>" />
<input type="hidden" name="n" value="<?php echo $n;?>" />

	<div class="form-group margin-bottom required">
		<label class="control-label col-sm-2" ><?php echo $this->translate('PR#'); ?>:</label>
		<div class="col-sm-3">
		<input disabled class="form-control input-sm" type="text" value="<?php if(!$entity == null): echo $entity->getPrAutoNumber(); endif;?>"/></div>
		<div class="col-sm-4">
		<?php echo (!$entity == null)? '<span style="color:gray;font-size: 9pt">Revision #'. $entity->getRevisionNo().';</span>':'';?>
		<?php if (!$entity == null): if($entity->getLastChangeOn()!==null): echo '<span style="color:gray;font-size: 9pt"> Last Revision: '. $entity->getLastChangeOn()->format('d-m-Y h:i:s').'</span>'; endif; endif;?>
		
	  </div>
			
	</div>


	<div class="form-group margin-bottom">
		<label class="control-label col-sm-2" >PR Number:</label>
		<div class="col-sm-3">
			<input class="form-control input-sm" type="text"  placeholder=""
				name="prNumber" value="<?php echo (!$entity == null)? $entity->getPrNumber():"";?>">
		</div>
		<div class="col-sm-4">
<input <?php if(!$entity == null): echo ($entity->getIsActive()=="1")?"checked":""; else: echo "checked"; endif;?> type="checkbox" name="isActive" value="1">&nbsp;Active&nbsp;&nbsp;
<input <?php if(!$entity == null): echo ($entity->getIsDraft()=="1")?"checked":""; else: echo "checked"; endif;?> type="checkbox" name="isDraft" value="1">&nbsp;Draft&nbsp;&nbsp;

		</div>		
				
	</div>
	
	<div class="form-group margin-bottom">
		<label class="control-label col-sm-2" >PR Name:</label>
		<div class="col-sm-3">
			<input class="form-control input-sm" type="text"  placeholder=""
				id = "prName" name="prName" value="<?php echo (!$entity == null)? $entity->getPrName():"";?>">
		</div>
		
		<label class="control-label col-sm-2" >Keywords:</label>
		<div class="col-sm-3">
			<input class="form-control input-sm" type="text"  placeholder=""
				id = "keywords" name="keywords" value="<?php echo (!$entity == null)? $entity->getKeywords():"";?>">
		</div>
	</div>
	
		<div class="form-group margin-bottom">
		<label class="control-label col-sm-2" >Date:</label>
		<div class="col-sm-3">
<input class="form-control input-sm" type="text"  placeholder="" id = "submittedOn" name="submittedOn" 
value="<?php if(!$entity == null): if ($entity->getSubmittedOn() !== null): echo date_format($entity->getSubmittedOn(),"Y-m-d"); endif; endif;?>" placeholder =" please select"/>
		</div>
	</div>
	
	<div class="form-group margin-bottom margin-bottom">
		<label class="control-label col-sm-2" >Total Rows:</label>
		<div class="col-sm-3">
			<input class="form-control input-sm" type="text"  placeholder=""
				id = "totalRowManual" name="totalRowManual" value="<?php echo (!$entity == null)? $entity->getTotalRowManual():"";?>">
		</div>
		
	</div>
	
	
	<div class="form-group margin-bottom">
		<label class="control-label col-sm-2" >Department</label>
		<div class="col-sm-3">
<input disabled class="form-control input-sm" type="text" id="department_name" placeholder="Please select!" 
name="deparment_name" value="<?php if (!$entity== null):if($entity->getDepartment()!==null):echo $entity->getDepartment()->getNodeName(); endif;endif;?>">

<input type="hidden" class="form-control input-sm" type="text" id="department_name_selected" placeholder="Please select!" 
name="department_id" value="<?php if (!$entity== null):if($entity->getDepartment()!==null):echo $entity->getDepartment()->getNodeId(); endif;endif;?>">
			</div>
		
<a style="color: #0080ff;" href="javascript:;"
	onclick="showBootstrapDialog('Select Deparment','/application/department/list1','b_loaded_data');">Select&nbsp;&nbsp;<i class="glyphicon glyphicon-folder-open"></i>
</a>
    </div>	
	
	<div class="form-group margin-bottom">
		<label class="control-label col-sm-2" >Remarks:</label>
		<div class="col-sm-3">
			<textarea  class="form-control input-sm" type="text" rows="4" placeholder=""
				name="remarks" style="font-size: 9pt;"><?php echo (!$entity == null)? $entity->getRemarks():"";?></textarea>
		</div>
	</div>
	
	<div class="form-group margin-bottom">
		<label class="control-label col-sm-2" for="inputTag"></label>
		<div class="col-sm-3">
	   	<button onclick="submitForm('Edit_PR_Form');" class="btn btn-default"><i class="glyphicon glyphicon-floppy-disk"> </i> Save</button>
  		</div>
	</div> 
		
	
</form>
</div>
</div>

<script>
$(function() {
   $( "input[id='submittedOn']").datepicker({ firstDay: 1, dateFormat: 'yy-mm-dd',closeText: 'X', changeMonth: true, changeYear: true});
});
</script>
