<?php
use Application\Application\Helper\ErrorMessage;
use Procure\Form\PR\PRHeaderFormRender;

/**
 *
 * @author Nguyen Mau Tri - ngmautri@gmail.com
 *         ===================================
 */
?>

<div
	style="border: 1px; padding: 3px; font-size: 9pt; background: url(/images/bg1.png); background-repeat: repeat-x; background-color: #FFFFFF;">
         
    <?php
    echo ErrorMessage::showErrorMessage($errors);
    echo $form->renderForView($this, new PRHeaderFormRender());
    ?>
</div>