<?php
use Procure\Domain\PurchaseRequest\PRDoc;

/**
 *
 * @author Nguyen Mau Tri - ngmautri@gmail.com
 *         ===================================
 *        
 *        
 * @var PRDoc $rootEntity ;
 *      ==============================
 */
//

$addRow = '<a style="color: gray" class="list-group-item" href="#">' . $this->translate('2. PR Line') . '</a>';

if ($rootEntity != null) {

    $f = 'add-row?target_id=%s&target_token=%s';
    $t = sprintf($f, $rootEntity->getId(), $rootEntity->getToken());

    $f = '<a style="color: gray" class="list-group-item" href="%s">' . $this->translate('2. PR Line') . '</a>';
    $addRow = sprintf($f, $t);
}
?>



<span style="color: gray; margin: 10pt 10pt 10pt 10pt">
       <?php
    echo $this->translate('Steps:');
    ?></span>

<div style="font-size: 9pt; margin: 5pt 2pt 5pt 5pt">

	<div class="list-group">
	<?php
if ($current_step == "STEP1") :
    ?>
		<a class="list-group-item active" href="#">1. <?php

    echo $this->translate('PR Header');
    ?>&nbsp;&nbsp;&nbsp;<i class="fa fa-chevron-right"
			aria-hidden="true"></i>
		</a>
	<?php

else :
    ?>
		<a style="color: gray" class="list-group-item" href="#">1. <?php

    echo $this->translate('PR Header');
    ?></a>
	<?php

endif;
?>
	
	<?php

if ($current_step == "STEP2") :
    ?>
		<a class="list-group-item active" href="#">2. <?php

    echo $this->translate('PR Line');
    ?>&nbsp;&nbsp;&nbsp;<i class="fa fa-chevron-right"
			aria-hidden="true"></i>
		</a>
	<?php

else :
    echo $addRow;

endif;
?>
	
	<?php

if ($current_step == "STEP3") :
    ?>
		<a class="list-group-item active" class="list-group-item"
			href="<?php

    echo $this->baseUrl?>/procure/pr/review?token=<?php

    echo (! $target == null) ? $target->getToken() : "";
    ?>&entity_id=<?php

    echo (! $target == null) ? $target->getId() : "";
    ?>">3. <?php

    echo $this->translate('Review & Submit');
    ?>&nbsp;&nbsp;&nbsp;</a>
	<?php

else :
    ?>
		<a style="color: gray" class="list-group-item" href="#">3. <?php

    echo $this->translate('Review & Submit');
    ?></a>
	<?php

endif;
?>
	
</div>
</div>
