<?php
use Procure\Application\Helper\ErrorMessage;
use Procure\Application\Helper\FormHelper;
use Procure\Application\Helper\OptionList;
use Procure\Application\Helper\Toolbar;
use Procure\Application\Service\Output\Contract\SaveAsSupportedType;
use Procure\Domain\Shared\Constants;
use Procure\Domain\Shared\ProcureDocStatus;

/**
 *
 * @author Nguyen Mau Tri - ngmautri@gmail.com
 *         ===================================
 */
/**@var \Procure\Application\DTO\Pr\PrDTO $headerDTO ;*/
/**@var \Procure\Application\DTO\Pr\PrRowDTO $dto ;*/
/**@var \Application\Controller\Plugin\NmtPlugin $nmtPlugin ;*/

// var_dump($headerDTO);
// echo memory_get_usage();

$add_row_url = null;
$picture_url = null;
$attachment_url = null;
$status_url = null;
$log_url = null;
$view_url = null;

$hoverMode = "row";

$isViewing = false;

if ($action == Constants::FORM_ACTION_SHOW) {
    $isViewing = true;
}

$canPost = true;

$transactionStatus = "";
$alert = "info";

$wh_id = null;
$pmtTermId = null;
$currencyId = null;
$incotermId = null;
$progress_div = '';

if (! $headerDTO == null) {

    if ($headerDTO->getTotalRows() > 0) {
        $completion = $headerDTO->getCompletedRows() / $headerDTO->getTotalRows();
    } else {
        $completion = 0;
    }

    $progress_div = FormHelper::createProgressDiv($completion, 'completed.');

    $transactionStatus = sprintf('<span style="color:red;">%s</span>', $headerDTO->getTransactionStatus());

    if ($headerDTO->getTransactionStatus() == "completed") {
        $transactionStatus = sprintf('<span style="color:green;">%s</span>', $headerDTO->getTransactionStatus());
        $alert = "success";
    }

    $picture_url = sprintf($this->baseUrl . "/procure/pr-attachment/get-pictures?target_id=%s&token=%s", $headerDTO->getId(), $headerDTO->getToken());
    $attachment_url = sprintf($this->baseUrl . "/procure/pr-attachment/list1?target_id=%s&token=%s", $headerDTO->getId(), $headerDTO->getToken());
    $status_url = sprintf($this->baseUrl . "/procure/pr/status?entity_id=%s&token=%s", $headerDTO->getId(), $headerDTO->getToken());
    $review_url = sprintf($this->baseUrl . "/procure/pr/review?entity_id=%s&entity_token=%s", $headerDTO->getId(), $headerDTO->getToken());
    $view_url = sprintf($this->baseUrl . "/procure/pr/view?entity_id=%s&entity_token=%s", $headerDTO->getId(), $headerDTO->getToken());

    $log_url = sprintf($this->baseUrl . "/application/message-store/list1?entity_id=%s&entity_token=%s", $headerDTO->getId(), $headerDTO->getToken());
    $update_header_url = sprintf($this->baseUrl . "/procure/pr/update?entity_id=%s&entity_token=%s", $headerDTO->getId(), $headerDTO->getToken());

    $add_row_url = sprintf($this->baseUrl . "/procure/pr/add-row?target_id=%s&target_token=%s", $headerDTO->getId(), $headerDTO->getToken());

    $save_as_pdf = sprintf($this->baseUrl . "/procure/pr/print?file_type=%s&entity_id=%s&entity_token=%s", SaveAsSupportedType::OUTPUT_IN_PDF, $headerDTO->getId(), $headerDTO->getToken());
    $save_as_excel = sprintf($this->baseUrl . "/procure/pr/save-as?file_type=%s&entity_id=%s&entity_token=%s", SaveAsSupportedType::OUTPUT_IN_EXCEL, $headerDTO->getId(), $headerDTO->getToken());
    $save_as_openoffice = sprintf($this->baseUrl . "/procure/pr/save-as?file_type=%s&entity_id=%s&entity_token=%s", SaveAsSupportedType::OUTPUT_IN_OPEN_OFFICE, $headerDTO->getId(), $headerDTO->getToken());

    if ($headerDTO->getDocStatus() == Constants::DOC_STATUS_DRAFT && $action == Constants::FORM_ACTION_REVIEW) :
        $hoverMode = "cell";
        $canPost = true;
    endif;

    switch ($headerDTO->getDocStatus()) {
        case ProcureDocStatus::DOC_STATUS_DRAFT:
            $isDraft = true;
            $canPost = true;
            break;
        case ProcureDocStatus::DOC_STATUS_POSTED:
            $isPosted = true;
            break;
    }

    $wh_id = $headerDTO->getWarehouse();
    $pmtTermId = $headerDTO->getPmtTerm();
    $currencyId = $headerDTO->getDocCurrency();
    $incotermId = $headerDTO->getIncoterm();
}

$wh_option = OptionList::createWarehouseOption($nmtPlugin->warehouseList(), $wh_id);
$paymentTerm_option = OptionList::createPmtTermOption($nmtPlugin->getPaymentTerms(), $pmtTermId);
$incoterm_option = OptionList::createIncotermOption($nmtPlugin->incotermList(), $incotermId);
$currency_option = OptionList::createCurrencyOption($nmtPlugin->currencyList(), $currencyId);
$error_msg = ErrorMessage::showErrorMessage($errors);

// ============================
?>
<div id="wrapper" class="toggled">
   <!-- Sidebar -->
   <div id="sidebar-wrapper" style="font-size: 9.5pt;">

<?php
if ($action == Constants::FORM_ACTION_REVIEW) :
    $current_step = "STEP3";
    include (ROOT . '/module/Procure/view/procure/pr-create-wizard.php');
endif;

?>

  		<hr>
      <h5>PURCHASE REQUEST:</h5>
      <span style="color: gray; margin: 2pt 2pt 2pt 8pt">
       <?php

    echo $this->translate('Summary:');
    ?></span>
      <div class="alert alert-<?php

    echo $alert;
    ?>" role="alert" style="padding: 2px; margin: 2pt 2pt 2pt 8pt; font-size: 9.2pt">
         <ul style="font-size: 9pt; margin: 0; padding-left: 15pt">
            <li>
               <b><?php

            if (! $headerDTO == null) :
                echo sprintf("PR #%s (Version #%s)", $headerDTO->getSysNumber(), $headerDTO->getRevisionNo()); endif;

            ?></b>
               <span style="color: black;">
                  <br><?php
                echo ($headerDTO !== null) ? $headerDTO->getDocNumber() : "";
                ?></span>
            </li>
            <li>-----</li>
            <li>Status: <?php

            if (! $headerDTO == null) :
                echo $headerDTO->getDocStatus(); endif;

            ?> </li>
            <li>Total rows: <?php

            echo ($headerDTO->totalRows);
            ?></li>
            <li>Status: <?php

            echo $transactionStatus;
            ?> </li>
            <li>-----</li>
            <li>Created by: <?php

            echo $headerDTO->getCreatedByName();
            echo $progress_div?></li>
         </ul>
      </div>

	<?php
if ($action == Constants::FORM_ACTION_REVIEW) :
    ?>
		<div class="alert alert-warning" role="alert" style="padding: 5px 2px 2px 5px; margin: 5pt 2pt 2pt 8pt; font-size: 9.2pt; color: graytext;">
         <i class="fa fa-info-circle" aria-hidden="true"></i>&nbsp;
			<?php

    echo $this->translate('Please post when PO /Contract is signed. Document can\'t be changed anymore when posted! <br> ');
    ?>
		</div>
	<?php endif;

?>


 <div class="container_dropzone">
         <input style="display: none;" type="file" name="pictures[]" id="file">
         <!-- Drag and Drop container-->
         <div class="upload-area" id="uploadfile">
            <h4>
               <i class="fa fa-cloud-upload fa-2x" aria-hidden="true"></i>
               <br>
               <br>
               Drag and Drop file here
            </h4>
         </div>
         <div id="selected_file"></div>
         <a id="uploadBtn" class="btn btn-default btn-sm" style="color: black; margin-top: 4pt; margin-left: 10pt; display: none;" href="javascript:;" onclick="doUploading();">
            <i class="fa fa-upload" aria-hidden="true">&nbsp;&nbsp;Upload</i>
         </a>
      </div>
   </div>
   <!-- /#sidebar-wrapper -->
   <!-- Page Content -->
   <div id="page-content-wrapper" style="font-size: 9.5pt; padding: 0px; margin: 0px;">
      <div class="container-fluid" id="main_container" style="font-size: 9.5pt; padding: 1px; margin: 0px;";>
         <a style="font-size: 9pt; margin: 2px; padding: 3px;" href="#menu-toggle" class="btn btn-primary btn-sm" id="menu-toggle">
            <span title="Hide Menu">
               <i class="fa fa-chevron-left" aria-hidden="true"></i>
               Menu
               <span>
         
         </a>
         <!-- end tab -->
         <div id="tabs" style="font-size: 9.5pt">
            <ul>
               <li>
                  <a href="#general">
                     <small>
                        <i class="fa fa-calculator" aria-hidden="true"></i>
                     </small>&nbsp;<?php

                    echo $form_title;
                    ?></a>
               </li>
               <li>
                  <a href="<?php

                echo $picture_url;
                ?>">
                     <span class="glyphicon glyphicon-picture"></span>
                     </span>
                     &nbsp;Picture
                  </a>
               </li>
               <li>
                  <a href="<?php

                echo $attachment_url;
                ?>">
                     <small>
                        <span class="glyphicon glyphicon-paperclip"></span>
                     </small>
                     &nbsp;Attachment
                  </a>
               </li>
               <li>
                  <a href="<?php

                echo $log_url;
                ?>">
                     <span class="glyphicon glyphicon-list"></span>
                     &nbsp;Log
                  </a>
               </li>
            </ul>
            <div id="general" style="font-size: 9pt; padding: 10px 10px 1px 5px">
               <!-- Tab1 -->


<?php
// ================================
echo $error_msg;
// ===============================
?>

<?php
if ($action == Constants::FORM_ACTION_REVERSE) :
    ?>
    <form id="REVERSAL_FORM" class="form-horizontal" action="<?php

    echo $form_action;
    ?>" method="post" enctype="multipart/form-data">
                  <input type="hidden" name="entity_id" value="<?php

    echo (! $headerDTO == null) ? $headerDTO->getId() : "";
    ?>" />
                  <input type="hidden" name="entity_token" value="<?php
    echo (! $headerDTO == null) ? $headerDTO->getToken() : "";
    ?>" />
                  <input type="hidden" name="version" value="<?php
    echo $version;
    ?>" />
                  <fieldset>
                     <legend style="font-size: 9.5pt; color: gray;">
                        <small>
                           <span class="glyphicon glyphicon-triangle-right"></span>
                        </small>
                        &nbsp;
                        <a href="#reserval_header" class="" data-toggle="collapse"><?php
    echo $this->translate("Reserval Header");
    ?>:</a>
                     </legend>
                     <div id="reserval_header" class="collapse in">
                        <div class="form-group margin-bottom required">
                           <label class="control-label col-sm-2 required"><?php

    echo $this->translate("Reversal Date");
    ?> :</label>
                           <div class="col-sm-3">
                              <input class="form-control input-sm" type="text" id="reversalDate" name="reversalDate" value="" placeholder=" please select" />
                           </div>
                        </div>
                        <div class="form-group margin-bottom">
                           <label class="control-label col-sm-2">Description</label>
                           <div class="col-sm-8">
                              <input class="form-control input-sm" type="text" placeholder="" name="reversalReason" value="<?php

    echo (! $headerDTO == null) ? '[Reversal] ' . $headerDTO->getRemarks() : "";
    ?>">
                           </div>
                        </div>
                        <div class="form-group margin-bottom">
                           <label class="control-label col-sm-2" for="inputTag"></label>
                           <div class="col-sm-3">
                              <a class="btn btn-primary btn-sm" style="color: white" onclick="confirmReserval();" href="javascript:;">
                                 <i class="fa fa-floppy-o" aria-hidden="true"></i> &nbsp;<?php

    echo $this->translate('Post');
    ?></a>
                              <a tabindex="11" class="btn btn-default btn-sm" href="<?php
    echo $view_url;
    ?>">
                                 <small>
                                    <i class="glyphicon glyphicon-remove"></i>
                                 </small>
                                 &nbsp;Cancel
                              </a>
                           </div>
                           <div class="col-sm-3"></div>
                        </div>
                     </div>
                  </fieldset>
               </form>
               <hr style="margin: 20pt 1pt 5pt 1pt;">
<?php endif;

?>


<!-- ================ TOOL BAR ======================-->
               <div style="position: relative; float: right;">
           <?php
        echo Toolbar::showToolbarPR($headerDTO, $action, $this);
        ?>
               </div>
               <!-- ================== TOOL BAR ===================-->
               <FORM id="HEADER_FORM" class="form-horizontal" action="<?php
            echo $form_action;
            ?>" method="post" enctype="multipart/form-data">
                  <input type="hidden" name="redirectUrl" value="<?php
                echo $redirectUrl?>" />
                  <input type="hidden" id="entity_id" name="entity_id" value="<?php
                echo $entity_id;
                ?>" />
                  <input type="hidden" id="entity_token" name="entity_token" value="<?php
                echo $entity_token;
                ?>" />
                  <input type="hidden" name="version" value="<?php
                echo $version;
                ?>" />
                  <fieldset>
                     <legend style="font-size: 9.5pt; color: gray;">
                        <small>
                           <span class="glyphicon glyphicon-triangle-right"></span>
                        </small>
                        &nbsp;
                        <a href="#invoice_header" class="" data-toggle="collapse">HEADER (<?php
                        echo "Version " . $version;
                        ?>):</a>
                     </legend>
                     <!-- HEADER  -->
                     <div id="invoice_header" class="collapse">
                        <div class="form-group margin-bottom required">
                           <label class="control-label col-sm-2">PR number:</label>
                           <div class="col-sm-3">
                              <input class="form-control input-sm" type="text" placeholder="" id="submittedOn" name="submittedOn" value="<?php
                            echo (! $headerDTO == null) ? $headerDTO->getPrName() : "";
                            ?>">
                           </div>
                        </div>
                        <div class="form-group margin-bottom required">
                           <label class="control-label col-sm-2 required">PR Date:</label>
                           <div class="col-sm-3">
                              <input class="form-control input-sm" type="text" id="docDate" name="docDate" value="<?php
                            if (! $headerDTO == null) :
                                echo $headerDTO->getSubmittedOn(); endif;

                            ?>"
                                 placeholder=" please select" />
                           </div>
                        </div>
                        <div class="form-group margin-bottom">
                           <label class="control-label col-sm-2">Keywords.:</label>
                           <div class="col-sm-3">
                              <input class="form-control input-sm" type="text" placeholder="" id="" keywords"" name="keywords" value="<?php
                            echo (! $headerDTO == null) ? $headerDTO->getKeywords() : "";
                            ?>">
                           </div>
                        </div>
                        <div class="form-group margin-bottom required">
                           <label class="control-label col-sm-2"><?php
                        echo $this->translate("Target Warehouse");
                        ?>:</label>
                           <div class="col-sm-3">
                              <select tabindex="9" name="warehouse" id="target_wh_id" class="form-control input-sm">
                                 <option value=""><?php
                                echo $this->translate("...");
                                ?></option>
<?php
// ================
echo $wh_option;
// ================
?>
                                        </select>
                           </div>
                        </div>
                        <div class="form-group margin-bottom required">
                           <label class="control-label col-sm-2"><?php
                        echo $this->translate("Payment Term");
                        ?>:</label>
                           <div class="col-sm-3">
                              <select name="department" class="form-control input-sm">
                                 <option value=""><?php
                                echo $this->translate("---");
                                ?></option>
 <?php
// ================
echo $department_option;
// ================
?>>
                     </select>
                           </div>
                        </div>
                        <div class="form-group margin-bottom">
                           <label class="control-label col-sm-2">Description</label>
                           <div class="col-sm-8">
                              <input class="form-control input-sm" type="text" id="remarks" placeholder="" name="remarks" value="<?php
                            echo (! $headerDTO == null) ? $headerDTO->getRemarks() : "";
                            ?>">
                           </div>
                        </div>
                        <div class="form-group margin-bottom">
                           <label class="control-label col-sm-2"></label>
                           <div class="col-sm-8">
                              <a title="<?php

                            echo $this->translate('Update document hearder');
                            ?>" class="btn btn-default btn-sm" style="color: navy; font-weight: bold;"
                                 href="<?php

                                echo $update_header_url;
                                ?>">
                                 <i class="fa fa-pencil-square-o" aria-hidden="true"></i>&nbsp;<?php

                                echo $this->translate('Edit');
                                ?></a>
                              <hr>
                           </div>
                        </div>
                     </div>
                     <!-- HEADER END -->
                  </fieldset>
               </form>
               <!-- ROW -->
               <form action="">
                  <fieldset>
                     <legend style="font-size: 9pt; color: gray;">
                        <small>
                           <span class="glyphicon glyphicon-triangle-right"></span>
                        </small>
                        &nbsp;
                        <a href="#rows" class="" data-toggle="collapse">ROWS:</a>
                     </legend>
                     <div id="rows" class="collapse in">
                        <div style="font-size: 9pt">
                           <div class="dropdown">
                              <button style="font-size: 9.5pt; margin-bottom: 2pt; padding: 3pt 5pt 3pt 5pt;" title="" class="btn btn-default dropdown-toggle btn-sm" type="button" id="dropdownMenu1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
                                 <i class="fa fa-download" aria-hidden="true"></i>
                                 &nbsp;&nbsp;
                                 <span class="caret"></span>
                              </button>
                              <a style="font-size: 9.5pt; margin-bottom: 2pt; padding: 3pt 5pt 3pt 5pt;" title="<?php

                            echo $this->translate("Refresh");
                            ?>" class="btn btn-default btn-sm" href="javascript:;" onclick="refreshGird();">
                                 &nbsp;
                                 <i class="fa fa-refresh" aria-hidden="true"></i>
                                 &nbsp;
                              </a>
                              <a <?php

                            echo $this->translate("Full Screen");
                            ?> style="font-size: 9.5pt; margin-bottom: 2pt; padding: 3pt 5pt 3pt 5pt;" class="btn btn-default btn-sm" href="javascript:;"
                                 onclick="showJqueryDialog('Contract /PO: <?php

                                echo $headerDTO->getSysNumber() . ' - ' . $headerDTO->getContractNo();
                                ?>','1850',$(window).height()-50,'/procure/po/add2?token=<?php

                                echo $headerDTO->getToken()?>&entity_id=<?php

                                echo $headerDTO->getId()?>','j_loaded_data',true);">
                                 <i class="fa fa-window-maximize" aria-hidden="true"></i>
                              </a>
                              &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                              <span>
                                 <strong>PO#: <?php

                                echo (! $headerDTO == null) ? $headerDTO->getSysNumber() : "";
                                ?> // </strong>
                              </span>
                              <span class="" style="padding: 3px; margin-bottom: 2px; font-size: 10pt; color: gray">
						Net amount: <?php

    echo number_format($headerDTO->getNetAmount(), 2) . " " . $headerDTO->getCurrencyIso3();
    ?>
                        &nbsp;|&nbsp;Tax amount: <?php

                        echo number_format($headerDTO->getTaxAmount(), 2);
                        ?>
                        &nbsp;|&nbsp;Gross amount: <?php

                        echo "<b>" . number_format($headerDTO->getGrossAmount(), 2) . "</b> " . $headerDTO->getCurrencyIso3();
                        ?>
                        &nbsp;|&nbsp;Total rows:<?php

                        echo ($headerDTO->getTotalActiveRows());
                        ?>
					</span>
                              <ul style="font-size: 9pt;" class="dropdown-menu" aria-labelledby="dropdownMenu1">
                                 <li>
                                    <a target="_blank" class="" href="<?php

                                    echo $save_as_pdf;
                                    ?>">
                                       <i class="fa fa-file-pdf-o fa-lg" aria-hidden="true"></i>&nbsp;Pdf (*.pdf) default
                                    </a>
                                 </li>
                                    <li class="divider"></li>
                             
                                 <li class="dropdown-submenu">
                                    <a class="test" tabindex="-1" href="#">
                                    <i class="fa fa-file-pdf-o fa-lg" aria-hidden="true"></i>&nbsp;Pdf (*.pdf) Detail&nbsp; &nbsp; &nbsp; &nbsp; 
                                       <i class="fa fa-caret-right" aria-hidden="true"></i>
                                    </a>
                                    <ul style="font-size: 9pt;" class="dropdown-menu">
                                       <li>
                                          <a tabindex="-1" href="#"><i class="fa fa-file-pdf-o fa-lg" aria-hidden="true"></i> Details with price <i class="fa fa-lock" aria-hidden="true"></i></a>
                                       </li>
                                          <li class="divider"></li>
                            
                                       <li>
                                           <a tabindex="-1" href="#"><i class="fa fa-file-pdf-o fa-lg" aria-hidden="true"></i> Details with picture</a>
                                      </li>
                                    </ul>
                                 </li>
                                 <li class="divider"></li>
                                 <li>
                                    <a class="" href="<?php

                                    echo $save_as_excel;
                                    ?>">
                                       <i class="fa fa-file-excel-o fa-lg" aria-hidden="true"></i>
                                       &nbsp;Excel (*.xlxs)
                                    </a>
                                 </li>
                                 <li class="divider"></li>
                                 <li>
                                    <a class="" href="<?php

                                    echo $save_as_openoffice;
                                    ?>">
                                       <i class="fa fa-file-excel-o fa-lg" aria-hidden="true"></i>
                                       &nbsp;Open Office (*.ods)
                                    </a>
                                 </li>
                              </ul>
                           </div>
                        </div>
                        <div id="pr_row_gird" style="font-size: 8pt;"></div>
                  
                  </fieldset>
               </form>
            </div>
            <!-- end tab -->
         </div>
      </div>
   </div>
</div>
<!-- /#page-content-wrapper -->
</div>
<!-- /#wrapper -->
<!-- Modal -->
<div class="modal" id="confirm_modal_sm" role="dialog">
   <div class="modal-dialog modal-md">
      <div class="modal-content">
         <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal">&times;</button>
         </div>
         <div class="modal-body" id="b_modal_sm_body">
            <h5>#<?php

            echo $this->translate('PO will be posted!');
            ?></h5>
            <div class="alert alert-warning">
               <strong>[Info]</strong> <?php

            echo $this->translate('Document can\'t be changed anymore when posted!');
            ?>
					<!-- Journal Entry will be created. <br>- Warehouse Journal will be
					created.
					 -->
            </div>
            <p><?php

            echo $this->translate('Do you want to continue?');
            ?></p>
         </div>
         <div class="modal-footer">
            <button onclick="doPosting();" type="button" class="btn btn-primary btn-sm">YES</button>
            <button type="button" class="btn btn-default btn-sm" data-dismiss="modal">Cancel</button>
         </div>
      </div>
   </div>
</div>
<!-- RESERVAL MODAL -->
<div class="modal" id="reversal_confirm_modal_sm" role="dialog">
   <div class="modal-dialog modal-md">
      <div class="modal-content">
         <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal">&times;</button>
         </div>
         <div class="modal-body" id="b_modal_sm_body">
            <h5>#<?php

            echo $this->translate('Invoice will be reversed!');
            ?></h5>
            <div class="alert alert-warning">
               <strong>[Info]</strong> <?php

            echo $this->translate('Document can\'t be changed anymore when posted!');
            ?>
					<!-- Journal Entry will be created. <br>- Warehouse Journal will be
					created.
					 -->
            </div>
            <p><?php

            echo $this->translate('Do you want to continue?');
            ?></p>
         </div>
         <div class="modal-footer">
            <button onclick="doReserval();" type="button" class="btn btn-primary btn-sm">YES</button>
            <button type="button" class="btn btn-default btn-sm" data-dismiss="modal">Cancel</button>
         </div>
      </div>
   </div>
</div>
<!-- Modal -->
<div class="modal" id="update_header_confirm_modal_sm" role="dialog">
   <div class="modal-dialog modal-md">
      <div class="modal-content">
         <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal">&times;</button>
         </div>
         <div class="modal-body" id="b_modal_sm_body">
            <h5>#<?php

            echo $this->translate('Document header amendment will be posted!');
            ?></h5>
            <div class="alert alert-warning">
               <strong>[Info]</strong> <?php

            echo $this->translate('Document can\'t be changed anymore when posted!');
            ?>
				</div>
            <p><?php

            echo $this->translate('Do you want to continue?');
            ?></p>
         </div>
         <div class="modal-footer">
            <button onclick="doPostAmendment();" type="button" class="btn btn-primary btn-sm">YES</button>
            <button type="button" class="btn btn-default btn-sm" data-dismiss="modal">Cancel</button>
         </div>
      </div>
   </div>
</div>
<script>

var data = <?php

echo json_encode($rowOutput);
?>

$( "input[id='contractDate']").datepicker({ firstDay: 1, dateFormat: 'yy-mm-dd',closeText: 'X',changeMonth: true, changeYear: true});
$( "input[id='reversalDate']").datepicker({ firstDay: 1, dateFormat: 'yy-mm-dd',closeText: 'X',changeMonth: true, changeYear: true});

<?php

if (! $canPost) :
    ?>
$("#HEADER_FORM :input").attr("disabled", "disabled");
<?php endif;

?>

function confirmPost() {
 	$('#confirm_modal_sm').modal();
}

function doPosting() {
   $('#confirm_modal_sm').modal('hide');
   $('#b_modal_no_header').modal();
   submitForm('HEADER_FORM');

   
}

function doPosting1() {
	$('#confirm_modal_sm').modal('hide');
	$('#b_modal_no_header').modal();

	//submitForm('Posting_Form');

	var url="/procure/ap/review";
	var entity_id="<?php
echo (! $headerDTO == null) ? $headerDTO->getId() : "";
?>";
	var entity_token="<?php

echo (! $headerDTO == null) ? $headerDTO->getToken() : "";
?>";
	var version="<?php
echo $version;
?>";

	$.post(url, {
		entity_id 	: entity_id,
		entity_token: entity_token,
		version: version,
	}, function(data, status, dataType) {
		//alert(data);
        window.location.href= data;
   	});
}

function confirmReserval() {
    
 	$('#reversal_confirm_modal_sm').modal();
}

function doReserval() {
    $('#reversal_confirm_modal_sm').modal('hide');    
    submitForm("REVERSAL_FORM");
}


function doAmendment() {
	$('#amendment_confirm_modal_sm').modal('hide');
	$('#b_modal_no_header').modal();

	var url="/procure/po/enable-amendment";
	var entity_id="<?php

echo (! $headerDTO == null) ? $headerDTO->getId() : "";
?>";
	var entity_token="<?php

echo (! $headerDTO == null) ? $headerDTO->getToken() : "";
?>";
	var version="<?php

echo $version;
?>";

	$.post(url, {
		entity_id 	: entity_id,
		entity_token: entity_token,
		version: version,
	}, function(data, status, dataType) {
	//	alert(data);
        window.location.href= data;
   	});
}


function confirmPostAmendment() {
 	$('#post_amendment_confirm_modal_sm').modal();
}

function doPostAmendment() {
	$('#post_amendment_confirm_modal_sm').modal('hide');
	$('#b_modal_no_header').modal();

	var url="/procure/po/review-amendment";
	var entity_id="<?php

echo (! $headerDTO == null) ? $headerDTO->getId() : "";
?>";
	var entity_token="<?php

echo (! $headerDTO == null) ? $headerDTO->getToken() : "";
?>";
	var version="<?php

echo $version;
?>";
	$.post(url, {
		entity_id 	: entity_id,
		entity_token: entity_token,
		version: version,
	}, function(data, status, dataType) {
        window.location.href= data;
   	});
}


$( "#pr_item_name" ).autocomplete({
    source: "/procure/pr-search/auto-complete",
    minLength: 3,
    select: function( event, ui ) {
  	  $( "#pr_row_id" ).val(ui.item.pr_row_id);

     alert	( ui.item.pr_row_id );
  	  //alert($( "#vendor_id" ).val());

  	 	$('#global-notice').show();
  		$('#global-notice').html('"' + ui.item.item_name + '" selected');
  		$('#global-notice').fadeOut(5000);
  		//$("#jquery_dialog").dialog("close");
    }
    })
    .autocomplete( "instance" )._renderItem = function( ul, item ) {
    return $( "<li>" )
      .append( "<div style='padding-bottom: 5px; border-bottom: thin solid gray;color:gray;font-size: 9.5pt;'>" + item.pr_number + "<br><span style='color:black;font-size: 9.5pt;'>" + item.item_sku_key  +  " | " + item.item_name + " | Q'ty: " + item.row_quantity + "<span></div>" )
      .appendTo( ul );
    };

    $( "#item_name" ).autocomplete({
        source: "/inventory/item-search/auto-complete",
        minLength: 2,
        select: function( event, ui ) {
      	  $( "#item_id" ).val(ui.item.id);

      	 	$('#global-notice').show();
      		$('#global-notice').html('"' + ui.item.value + '" selected');
      		$('#global-notice').fadeOut(5000);
      		//$("#jquery_dialog").dialog("close");
        }

      })
      .autocomplete( "instance" )._renderItem = function( ul, item ) {
   	  var serial_no = "";
   	  if(item.item_serial!=""){
   		  serial_no = " : " + item.item_serial;
   	  }

         return $( "<li>" )
           .append( "<div style='padding-bottom: 5px; border-bottom: thin solid gray;'><span style='font-size: 9.5pt;font-weight: bold;'>" + item.value + "</span><br><span style='color:gray;font-size: 9pt;'>" + item.item_sku + serial_no +"<span></div>" )
           .appendTo( ul );
       };



//$( "input[id='invoiceDate']").datepicker({ firstDay: 1, dateFormat: 'yy-mm-dd',closeText: 'X',changeMonth: true, changeYear: true});

$( "#vendor_name_1" ).autocomplete({
    source: "/bp/vendor-search/auto-complete",
    minLength: 3,
    select: function( event, ui ) {
  	  $( "#vendor_id" ).val(ui.item.id);
      //alert	( "Selected: " + ui.item.value + " aka " + ui.item.id );
  	  //alert($( "#vendor_id" ).val());

  	 	$('#global-notice').show();
  		$('#global-notice').html('"' + ui.item.value + '" selected');
  		$('#global-notice').fadeOut(5000);
  		//$("#jquery_dialog").dialog("close");
    }
    })
    .autocomplete( "instance" )._renderItem = function( ul, item ) {
    return $( "<li>" )
      .append( "<div style='padding-bottom: 5px; border-bottom: thin solid gray;'>" + item.value + "<br><span style='color:gray;font-size: 9pt;'>" + item.vendor_country + "<span></div>" )
      .appendTo( ul );
    };

	//$("#Create_PR_Form :input").attr("disabled", "disabled");


	    var autoCompleteEditor = function (ui) {
        var $inp = ui.$cell.find("input");
        var rowData = ui.rowData;

        //initialize the editor
        $inp.autocomplete({
        	source: "/bp/vendor-search/auto-complete",
            minLength: 3,
            select: function( event, ui ) {
          	  //$( "#vendor_id" ).val(ui.item.id);
              //alert	( "Selected: " + ui.item.value + " aka " + ui.item.id );
          	  //alert($( "#vendor_id" ).val());
          	  //alert(ui.item.id);
          	  rowData.vendor_id = ui.item.id;

          	 	$('#global-notice').show();
          		$('#global-notice').html('"' + ui.item.value + '" selected');
          		$('#global-notice').fadeOut(5000);
          		//$("#jquery_dialog").dialog("close");
            }
            })
            .autocomplete( "instance" )._renderItem = function( ul, item ) {
            return $( "<li>" )
              .append( "<div style='padding-bottom: 5px; border-bottom: thin solid gray;'>" + item.value + "<br><span style='color:gray;font-size: 9pt;'>" + item.vendor_country + "<span></div>" )
              .appendTo( ul );
          };
    }


    //var container_height = $('#main_container').height();
    //alert(container_height);



	var obj = { width: "auto", height: $(window).height()-300, showTitle : false,
			resizable:true,
			//draggable:true,
			sortable: true,
			freezeCols:1,
			hoverMode: '<?php

echo $hoverMode;
?>',
		   	pageModel: { type: "local", rPP: 100, strRpp: "{0}" },
		  	editModel: {
                allowInvalid: true,
                saveKey: $.ui.keyCode.ENTER
            },
            editor: {
                select: true
            },
		 columnBorders: true,

				  	  toolbar: {
	                    items: [
                        { type: 'button', icon: 'ui-icon-plus', label: 'Add New Row', listeners: 
                            [
                                { "click": function (evt, ui) {
                                    var $grid = $(this).closest('.pq-grid');
                                    redirectUrl="<?php

                                    echo $add_row_url;
                                    ?>";
                                    window.location.href= redirectUrl;
                                    }
                                  }
                              ]
                              }
                           ]
                       },


        change: function (evt, ui) {

            if (ui.source == 'commit' || ui.source == 'rollback') {
                return;
            }
            console.log(ui);
            var $grid = $(this),
                grid = $grid.pqGrid('getInstance').grid;
            var rowList = ui.rowList,
                addList = [],
                recIndx = grid.option('dataModel').recIndx,
                deleteList = [],
                updateList = [];

            for (var i = 0; i < rowList.length; i++) {
                var obj = rowList[i],
                    rowIndx = obj.rowIndx,
                    newRow = obj.newRow,
                    type = obj.type,
                    rowData = obj.rowData;
                 if (type == 'add') {
                    var valid = grid.isValid({ rowData: newRow, allowInvalid: true }).valid;
                    if (valid) {
                        addList.push(newRow);
                    }
                }
                else if (type == 'update') {
                    var valid = grid.isValid({ rowData: rowData, allowInvalid: true }).valid;
                    if (valid) {
                        if (rowData[recIndx] == null) {
                            addList.push(rowData);
                        }
                        //else if (grid.isDirty({rowData: rowData})) {
                        else {
                            updateList.push(rowData);
                      		//alert(rowData[recIndx]  + "remarks: " + rowData.item_name);

                        }
                    }
                }
              }

              if (addList.length || updateList.length || deleteList.length) {
				var sent_list = JSON.stringify({
                    updateList: updateList,
                    addList: addList,
                    deleteList: deleteList
                });
                //alert(sent_list);

                  $.ajax({
                      url: '/procure/po/update-row',
                      data: {
                          sent_list: sent_list
                      },
                      dataType: "json",
                      type: "POST",
                      async: true,
                      beforeSend: function (jqXHR, settings) {
                          //$(".saving", $grid).show();


                          //$("#global-notice").text("Updating...").show();
                          //alert(updateList[0].item_name  +  updateList[0].row_id);
                      },
                      success: function (changes) {
                          //commit the changes.

                      	  if(changes.status == <?php

                        echo Constants::AJAX_FAILED;
                        ?>){
                      		$("#global-notice").text(changes.message).show();
                      	  }else{
                      		$("#global-notice").text("[OK] Updated...").show();
                      	  }
            		      //alert('it is ok');
                          /* grid.commit({ type: 'add', rows: changes.addList });
                          grid.commit({ type: 'update', rows: changes.updateList });
                          grid.commit({ type: 'delete', rows: changes.deleteList }); */
                      },
                      complete: function () {
                          //$(".saving", $grid).hide();
                          $("#global-notice").delay(2200).fadeOut(500);
                     	  refreshGird();
                      }
                  });
              }
            //alert(updateList.length);

        },

	};

    obj.dataModel = {
            data: data,
            location: "local",
            sorting: "local",
            sortDir: "down"
    };

    obj.colModel = [

             { title: "", editable: false, minWidth: 55, sortable: false,
           render: function (ui) {
               //return "<button type='button' class='edit_btn' ><small><i style='font-style: normal;' class=''>Edit&nbsp;</i></small></button><button type='button' class='receive_btn'><span class='glyphicon glyphicon-plus'>&nbsp;</span><button type='button' class='receive_inline_btn'><span class='glyphicon glyphicon-plus'>&nbsp;</span></button>";
        		return '<button type="button" class="edit_btn">Edit </button>';
           }
       },


       <?php
    // $rowDTO->convertedStandardQuantity; ?>

       { title: "FA Remarks", dataType: "string", dataIndx: "faRemarks", align: 'left',minWidth: 150,editable: true},
   	   { title: "Ref", dataType: "integer", dataIndx: "rowIdentifer", width:85,editable: false},
            { title: "Status", dataType: "string", dataIndx: "transactionStatus", align: 'left',minWidth: 150,editable: true},

   	       { title: "#", dataType: "integer", dataIndx: "rowNumber", width:10,editable: true },
  		{ title: "SKU", dataType: "string", dataIndx: "itemSKU", width:50,editable: false },
       { title: "Item", dataType: "string", dataIndx: "itemName", width:220,editable: false },
       { title: "Vendor Item Name", dataType: "string", dataIndx: "vendorItemName", width:180,editable: false },
       { title: "Code", dataType: "string", dataIndx: "vendorItemCode", width:100,editable: false },

      	<?php

    if ($headerDTO->getDocStatus() == Constants::DOC_STATUS_DRAFT && $action == Constants::FORM_ACTION_REVIEW) :
        ?>
        { title: "Doc Qty", dataType: "decimal", dataIndx: "docQuantity", width: 70,align: 'right',editable: true},
        <?php

    else :
        ?>
        { title: "Doc Qty", dataType: "decimal", dataIndx: "docQuantity", width: 70,align: 'right',editable: false},
        	<?php

    endif;
    ?>
       { title: "Unit", dataType: "string", dataIndx: "rowUnit", width: 50,align: 'right',editable: false},
  
        { title: "Received", dataType: "decimal", dataIndx: "postedGrQuantity", align: 'right',width:70,editable: false },
       { title: "Received Stock", dataType: "decimal", dataIndx: "postedStockQrQuantity", align: 'right',width:70,editable: false },
       { title: "Billed qty", dataType: "decimal", dataIndx: "postedApQuantity", align: 'right',width:70,editable: false },
       { title: "Standard Qty", dataType: "integer", dataIndx: "convertedStandardQuantity", width: 70,align: 'right',editable: false},
       { title: "Standard Unit", dataType: "integer", dataIndx: "convertedStandardUnitPrice", width: 70,align: 'right',editable: false},

       { title: "Target WH", dataType: "string", dataIndx: "warehouseCode", width:50,editable: false },
	    { title: "Remarks", dataType: "string", dataIndx: "remarks", align: 'left',minWidth: 150,editable: false},
      { title: "PR", dataType: "string", dataIndx: "lastApVendor", width:120,editable: false },
      { title: "PR", dataType: "string", dataIndx: "edt", width:120,editable: false },
           
      ];

    var $grid = $("#pr_row_gird").pqGrid(obj);


    $grid.on('pqgridrefresh pqgridrefreshrow', function () {
        //debugger;
        var $grid = $(this);

        $grid.find("button.edit_btn").button({})
        .unbind("click")
        .bind("click", function (evt) {

            var $tr = $(this).closest("tr"),
            rowIndx = $grid.pqGrid("getRowIndx", { $tr: $tr }).rowIndx;

            rowData = $grid.pqGrid("getRowData", { rowIndx: rowIndx }),
            recIndx = $grid.pqGrid("option", "dataModel.recIndx");

            redirectUrl="/procure/pr/update-row?entity_token="+rowData['token']+"&entity_id="+rowData['id']+"&target_id="+rowData['docId']+"&target_token="+rowData['docToken'];
          	//alert(redirectUrl);
			window.location.href = redirectUrl;
          	//window.open(redirectUrl,'_blank');
        });

     });

	// important for datamodel: local.
    $( "#pr_row_gird" ).pqGrid( "refreshDataAndView" );

    function refreshGird(){
    	$( "#pr_row_gird" ).pqGrid( "refreshDataAndView" )
    }


    //==================


    var dataArray = [];
    var maxFiles = 2;


    // Drag enter
    $('.upload-area').on('dragenter', function (e) {
        e.stopPropagation();
        e.preventDefault();
        $("h4").addClass('cat_drag_over');
            
        //$("h4").text("Drop");
    });

    // Drag enter
    $('.upload-area').on('dragleave', function (e) {
        e.stopPropagation();
        e.preventDefault();
        $("h4").removeClass('cat_drag_over');
            
        //$("h4").text("Drop");
    });

    // Drag over
    $('.upload-area').on('dragover', function (e) {
        e.stopPropagation();
        e.preventDefault();
        $("h4").addClass('cat_drag_over');
        //$("h4").text("Drop");
    });

    // Drop
    $('.upload-area').on('drop', function (e) {
        e.stopPropagation();
        e.preventDefault();

        //$("h4").text("Uploaded");
        $("h4").removeClass('cat_drag_over');
        

        var file = e.originalEvent.dataTransfer.files;
        var fd = new FormData();

        fd.append('attachments', file[0]);         
        fd.append('target_id', <?php
        echo (! $headerDTO == null) ? $headerDTO->getId() : "";
        ?>);
        fd.append('token', '<?php
        echo (! $headerDTO == null) ? $headerDTO->getToken() : "";
        ?>');
        fd.append('redirectUrl',null);
        fd.append('documentSubject','na');
        fd.append('validTo','');
        fd.append('validFrom','');
        fd.append('isActive',1);
        fd.append('markedForDeletion',0);
        fd.append('filePassword','');
        fd.append('visibility',1);
        fd.append('remarks','');

        $('#file')[0] = file[0];
        //alert(file[0].size + file[0].type);

        dataArray.push(file[0]);

        if(dataArray.length>maxFiles){
     	   alert("Max file " +  maxFiles);
     	   return;
        }

        if(dataArray.length == 0){
     	   return;
        }
        
        var i;
        var selected_file="";
        
        selected_file= "<ul>";
        for (i = 0; i < dataArray.length; i++) {
     	   selected_file = selected_file + "<li>"+ dataArray[i].name +"; "+dataArray[i].size + "</li>";
        } 

        selected_file= selected_file+"</ul>";

        $('#selected_file').html(selected_file);
        $('#uploadBtn').show();
           
        //uploadData(fd);
    });

    // Open file selector on div click
    $("#uploadfile").click(function(){
        $("#file").click();
    });

    // file selected
    $("#file").change(function(){
        var fd = new FormData();

        var files = $('#file')[0].files[0];

        fd.append('attachments',files);
        fd.append('target_id', <?php

        echo (! $headerDTO == null) ? $headerDTO->getId() : "";
        ?>);
        fd.append('checksum','na');
        fd.append('token', '<?php

        echo (! $headerDTO == null) ? $headerDTO->getToken() : "";
        ?>');       
        fd.append('subject','na');
        fd.append('entity_id','na');
        fd.append('entity_token','na');
  

        //uploadData(fd);
    });


 //Sending AJAX request and upload file
 function uploadData(formdata){
 	
    $.ajax({
        url: '/procure/pr-attachment/upload1',
        type: 'POST',
        data: formdata,
        contentType: false,
        processData: false,
        dataType: 'json',       
        success: function( jqXHR, textStatus ){
     	   //alert("ok");
            //alert(response);
     	   location.reload();
        },
    }).fail(function(  jqXHR, textStatus ) {
 	    
 		
 		 alert('false');

 		   });
 }

 //Sending AJAX request and upload file
 function doUploading(){

 	 if(dataArray.length == 0){
 		alert("No File");
 	  	return;
 	 }    

 	 $("#b_modal_no_header").modal(); 

 	 //alert(dataArray.length);
 	 
     var fd = new FormData();
     fd.append('attachments',dataArray[0]);
     fd.append('target_id', <?php

    echo (! $headerDTO == null) ? $headerDTO->getId() : "";
    ?>);
     fd.append('checksum','na');
     fd.append('token', '<?php

    echo (! $headerDTO == null) ? $headerDTO->getToken() : "";
    ?>');       
     fd.append('documentSubject','na');
     fd.append('entity_id','na');
     fd.append('entity_token','na');
     fd.append('validFrom','');
     fd.append('validTo','');
     fd.append('redirectUrl',null);
     fd.append('isActive',1);
     fd.append('remarks','');
     fd.append('markedForDeletion',0);
     fd.append('visibility',1);
     fd.append('filePassword','');
         
             
    $.ajax({
        url: '/procure/pr-attachment/upload1',
        type: 'POST',
        data: fd,
        contentType: false,
        processData: false,
        dataType: 'json',       
        success: function( jqXHR, textStatus ){
     	   //alert("ok");
            //alert(response);
     	   location.reload();
        },
    }).fail(function(  jqXHR, textStatus ) {
 	    
 		
 		 alert(jqXHR.responseText  + textStatus);

 		   });
 }

 //Added thumbnail
 function addThumbnail(data){
    $("#uploadfile h1").remove(); 
    var len = $("#uploadfile div.thumbnail").length;

    var num = Number(len);
    num = num + 1;

    var name = data.name;
    var size = convertSize(data.size);
    var src = data.src;

    // Creating an thumbnail
    $("#uploadfile").append('<div id="thumbnail_'+num+'" class="thumbnail"></div>');
    $("#thumbnail_"+num).append('<img src="'+src+'" width="100%" height="78%">');
    $("#thumbnail_"+num).append('<span class="size">'+size+'<span>');

 }

 //Bytes conversion
 function convertSize(size) {
    var sizes = ['Bytes', 'KB', 'MB', 'GB', 'TB'];
    if (size == 0) return '0 Byte';
    var i = parseInt(Math.floor(Math.log(size) / Math.log(1024)));
    return Math.round(size / Math.pow(1024, i), 2) + ' ' + sizes[i];
 }
         

    
</script>
