<?php
use Application\Application\Helper\Form\FormHelper;
use Application\Application\Helper\Form\Bootstrap3\CollapseHelper;
use Application\Domain\Util\Collection\Render\AbstractCollectionRender;
use Procure\Form\PR\PRRowCollectionFilterForm;
use Procure\Form\PR\PRRowCollectionFilterFormRender;

/**
 *
 * @author Nguyen Mau Tri - ngmautri@gmail.com
 *         ===================================
 *        
 * @var AbstractCollectionRender $collectionRender ;
 * @var PRRowCollectionFilterForm $form ;
 */
// ===========================================================
?>

<script>
<?php
$format = "var previous_url = '%s'";
echo sprintf($format, $collectionRender->getUrl());
?>
</script>



<div id="pr_row_div">


          <?php

        $showTitle = '<span style="font-size:8pt"><i class="fa fa-chevron-down" aria-hidden="true"></i> Filter</span>';
        $hideTitle = '<span <span style="font-size:8pt"><i class="fa fa-chevron-up" aria-hidden="true"></i> Filter</span>';
        $collapseId = 'test_id';
        $content = $form->renderForView($this, new PRRowCollectionFilterFormRender());

        $filterBtn = CollapseHelper::drawBasisCollapse($showTitle, $hideTitle, $collapseId, $content);

        if ($collectionRender != null) :

            $currentToolBar = $collectionRender->printToolBar();
            $toolbar = FormHelper::preAppendToCurrentToolbar($currentToolBar, $filterBtn);
            $collectionRender->setToolbar($toolbar);

            echo $collectionRender->printToolBar() . FormHelper::drawLine();
            echo $collectionRender->execute();
            echo $collectionRender->printAjaxPaginator();
        else :
            echo FormHelper::echoMessage("Nothing found !");
        endif;
        ?>

    <!-- PARAM QUERY -->
    <?=$this->row_gird;?>
    <!-- PARAM QUERY -->

    <!-- REMOVE MODAL -->
    <?=$this->remove_modal;?>
    <!-- REMOVE MODAL -->

</div>
