

<h4><?php echo (!$entity == null)? 'PR: ' . $entity->getPrName():"";?></h4>

<div id="tabs" style="font-size: 9.5pt">
	<ul>
		<li><a href="#general">Purchase Request</a></li>
		<li><a
			href="/procure/pr-attachment/get-pictures?token=<?php echo (!$entity == null)? $entity->getToken():"";?>&checksum=<?php echo (!$entity == null)? $entity->getChecksum():"";?>&target_id=<?php echo (!$entity == null)? $entity->getID():"";?>">Picture</a></li>
		<li><a
			href="/procure/pr-attachment/list1?token=<?php echo (!$entity == null)? $entity->getToken():"";?>&checksum=<?php echo (!$entity == null)? $entity->getChecksum():"";?>&target_id=<?php echo (!$entity == null)? $entity->getID():"";?>">Attachment</a></li>

	</ul>

	<div id="general">

		<form id="Create_PR_Form" class="form-horizontal"
			action="/procure/pr/add" method="post" enctype="multipart/form-data">
			<input type="hidden" name="redirectUrl"
				value="<?php echo $redirectUrl ?>" />


			<fieldset>
				<legend style="font-size: 10pt; color: gray;">
					<small><span class="glyphicon glyphicon-triangle-right"></span></small>&nbsp;
					<a href="#pr_header" class="" data-toggle="collapse">PR HEADER:</a>
				</legend>
				<div id="pr_header" class="collapse">

					<div class="form-group">
						<label class="control-label col-sm-2">PR Number:</label>
						<div class="col-sm-3">
							<input class="form-control" type="text" placeholder=""
								name="prNumber"
								value="<?php echo (!$entity == null)? $entity->getPrNumber():"";?>">
						</div>

						<label class="control-label col-sm-1" for="inputTag"></label>
						<div class="col-sm-4">
							<input
								<?php if(!$entity == null): echo ($entity->getIsActive()=="1")?"checked":""; else: echo "checked"; endif;?>
								type="checkbox" name="isActive" value="1">&nbsp;Active&nbsp;&nbsp;
							<input
								<?php if(!$entity == null): echo ($entity->getIsDraft()== "1")?"checked":""; else: echo "checked"; endif;?>
								type="checkbox" name="isDraft" value="1">&nbsp;Draft&nbsp;&nbsp;

						</div>

					</div>

					<div class="form-group">
						<label class="control-label col-sm-2">PR Name:</label>
						<div class="col-sm-3">
							<input class="form-control" type="text" placeholder=""
								id="prName" name="prName"
								value="<?php echo (!$entity == null)? $entity->getPrName():"";?>">
						</div>

						<label class="control-label col-sm-2">Keywords:</label>
						<div class="col-sm-3">
							<input class="form-control" type="text" placeholder=""
								id="keywords" name="keywords"
								value="<?php echo (!$entity == null)? $entity->getKeywords():"";?>">
						</div>
					</div>

					<div class="form-group">
						<label class="control-label col-sm-2">Department</label>
						<div class="col-sm-3">
							<input disabled class="form-control" type="text"
								id="department_name" placeholder="Please select!"
								name="deparment_name"
								value="<?php if (!$entity== null):if($entity->getDepartment()!==null):echo $entity->getDepartment()->getNodeName(); endif;endif;?>">

							<input type="hidden" class="form-control" type="text"
								id="department_name_selected" placeholder="Please select!"
								name="department_id"
								value="<?php if (!$entity== null):if($entity->getDepartment()!==null):echo $entity->getDepartment()->getNodeId(); endif;endif;?>">
						</div>

						<a style="color: #0080ff;" href="javascript:;"
							onclick="showBootstrapDialog('Select Deparment','/application/department/list1','b_loaded_data');">Select&nbsp;&nbsp;<i
							class="glyphicon glyphicon-folder-open"></i>
						</a>
					</div>

					<div class="form-group">
						<label class="control-label col-sm-2">Remarks:</label>
						<div class="col-sm-3">
							<textarea class="form-control" type="text" rows="4"
								placeholder="" name="remarks" style="font-size: 9pt;"><?php echo (!$entity == null)? $entity->getRemarks():"";?></textarea>
						</div>
					</div>

					<div class="form-group">
						<label class="control-label col-sm-2" for="inputTag"></label>
						<div class="col-sm-3">
							<a class="btn btn-default"
								href="<?php echo $this->baseUrl ?>/procure/pr/edit?token=<?php echo (!$entity == null)? $entity->getToken():"";?>&entity_id=<?php echo (!$entity == null)? $entity->getId():"";?>&checksum=<?php echo (!$entity == null)? $entity->getChecksum():"";?>"><small><i
									class="glyphicon glyphicon-pencil"></i></small>&nbsp;Edit</a>

						</div>
					</div>

				</div>
			</fieldset>
		</form>

		<fieldset>
			<legend style="font-size: 10pt; color: gray;">
				<small><span class="glyphicon glyphicon-triangle-right"></span></small>&nbsp;
				<a href="#transaction" class="" data-toggle="collapse">PR ROWS:</a>
			</legend>
			<div id="transaction" class="collapse in">

				<div id="pr_rows"></div>

				<div id="pr_row_gird" style="margin: 1px;"></div>
		
		</fieldset>
	</div>


</div>



<script>
	//loadPrRow('<?php echo $this->baseUrl . '/procure/pr-row/row?target_id='. $entity->getId().'&token='.$entity->getToken().'&checksum='.$entity->getChecksum()?>');
	$("#Create_PR_Form :input").attr("disabled", "disabled");


	 //to check whether any row is currently being edited.
    function isEditing($grid) {
        var rows = $grid.pqGrid("getRowsByClass", { cls: 'pq-row-edit' });
        if (rows.length > 0) {
            //focus on editor if any 
            $grid.find(".pq-editor-focus").focus();
            return true;
        }
        return false;
    }

     
	  //called by add button in toolbar.
    function addRow($grid) {
    	 if (isEditing($grid)) {
    	        return false;
    	    }
    	  
    	//append empty row in the first row.                            
        var rowData = { Item: "", Quantity: 0, Received: 0, Balance: 0}; //empty row template
        $grid.pqGrid("addRow", { rowIndxPage: 0, rowData: rowData });

        var $tr = $grid.pqGrid("getRow", { rowIndxPage: 0 });
        if ($tr) {
            //simulate click on edit button.
            $tr.find("button.edit_btn").click();
        }
    }
    
	var obj = { width: "100%", height: 350, title: "ParamQuery Grid Example",
			//resizable:true,
			//draggable:true,
			sortable: true,
			 hoverMode: 'cell',
			 columnBorders: true,
			 /*  toolbar: {
	                items: [
	                    { type: 'button', icon: 'ui-icon-plus', label: 'Add New Row', listeners: [
	                        { "click": function (evt, ui) {
	                            var $grid = $(this).closest('.pq-grid');
	                            addRow($grid);
	                            //debugger;
	                        }
	                        }
	                    ]
	                    }
	                ]
	            },  */
	};

    obj.colModel = [
        { title: "Item", dataType: "string", dataIndx: "item_name", width: 380 },
        { title: "Quantity", dataType: "integer", dataIndx: "quantity", width: 80,align: 'right'},
        { title: "Received", dataType: "integer", dataIndx: "total_received", width:82, align: 'right'},
        { title: "Balance", dataType: "integer", dataIndx: "confirmed_balance", width: 80,align: 'right'},
        
        { title: "", editable: false, minWidth: 200, sortable: false,
            render: function (ui) {
                return "<button type='button' class='receive_btn'>Receive</button> <button type='button' class='received_btn'>Received</button>";
	           }
        }
   ];

    obj.dataModel = {
    		  dataType: "JSON",
              location: "remote",
              recIndx: "row_id",
              url: "/procure/pr-row/gird?token=<?php echo (!$entity == null)? $entity->getToken():"";?>&target_id=<?php echo (!$entity == null)? $entity->getId():"";?>&checksum=<?php echo (!$entity == null)? $entity->getChecksum():"";?>",
              getData: function (response) {
           	    return { data: response.data };
             }
    };
    
    var $grid = $("#pr_row_gird").pqGrid(obj);

    $grid.on('pqgridrefresh pqgridrefreshrow', function () {
        //debugger;
        var $grid = $(this);

        //receive button
        $grid.find("button.receive_btn").button({})
        .unbind("click")
        .bind("click", function (evt) {

            var $tr = $(this).closest("tr"),
            rowIndx = $grid.pqGrid("getRowIndx", { $tr: $tr }).rowIndx;

            rowData = $grid.pqGrid("getRowData", { rowIndx: rowIndx }),
            recIndx = $grid.pqGrid("option", "dataModel.recIndx");
    
            redirectUrl="/inventory/item-transaction/gr?token="+rowData['row_token']+"&pr_row_id="+rowData['row_id']+"&checksum="+rowData['row_checksum'];
          	//alert(rowData['item_name']);

          	window.open(redirectUrl,'_blank');
        });

        //receive button
        $grid.find("button.received_btn").button({})
        .unbind("click")
        .bind("click", function (evt) {

            var $tr = $(this).closest("tr"),
            rowIndx = $grid.pqGrid("getRowIndx", { $tr: $tr }).rowIndx;

            rowData = $grid.pqGrid("getRowData", { rowIndx: rowIndx }),
            recIndx = $grid.pqGrid("option", "dataModel.recIndx");
    
            redirectUrl="/inventory/item-transaction/gr?token="+rowData['row_token']+"&pr_row_id="+rowData['row_id']+"&checksum="+rowData['row_checksum'];
          	//alert(rowData['item_name']);

          	//window.open(redirectUrl,'_blank');
          	showJqueryDialog('Receiving of Item:',980,550, '/inventory/item-transaction/pr-row?pr_row_id='+ rowData['row_id'],'j_loaded_data', true)
        });
    });        

</script>

