<h4><?php echo (!$entity == null)? 'PR: ' . $entity->getPrName():"";?></h4>

<div id="tabs" style="font-size: 9.5pt"> 
  <ul>
  <li ><a href="#general">Purchase Request</a></li>
    <li ><a href="/procure/pr-row/list1?token=<?php echo (!$entity == null)? $entity->getToken():"";?>&checksum=<?php echo (!$entity == null)? $entity->getChecksum():"";?>&target_id=<?php echo (!$entity == null)? $entity->getID():"";?>">PR Rows</a></li>
   <li ><a href="/procure/pr-attachment/get-pictures?token=<?php echo (!$entity == null)? $entity->getToken():"";?>&checksum=<?php echo (!$entity == null)? $entity->getChecksum():"";?>&target_id=<?php echo (!$entity == null)? $entity->getID():"";?>">Picture</a></li>
   <li ><a href="/procure/pr-attachment/list1?token=<?php echo (!$entity == null)? $entity->getToken():"";?>&checksum=<?php echo (!$entity == null)? $entity->getChecksum():"";?>&target_id=<?php echo (!$entity == null)? $entity->getID():"";?>">Attachment</a></li>
  
   </ul>

<div id="general"> 

<form id="Create_PR_Form" class="form-horizontal" action="/procure/pr/add" method="post" enctype="multipart/form-data">
<input type="hidden" name="redirectUrl" value="<?php echo $redirectUrl ?>" />

	<div class="form-group">
		<label class="control-label col-sm-2" >PR Number:</label>
		<div class="col-sm-3">
			<input class="form-control" type="text"  placeholder=""
				name="prNumber" value="<?php echo (!$entity == null)? $entity->getPrNumber():"";?>">
		</div>
		
		<label class="control-label col-sm-1" for="inputTag"></label>
		<div class="col-sm-4">
<input <?php if(!$entity == null): echo ($entity->getIsActive()=="1")?"checked":""; else: echo "checked"; endif;?> type="checkbox" name="isActive" value="1">&nbsp;Active&nbsp;&nbsp;
<input <?php if(!$entity == null): echo ($entity->getIsDraft()== "1")?"checked":""; else: echo "checked"; endif;?> type="checkbox" name="isDraft" value="1">&nbsp;Draft&nbsp;&nbsp;

		</div>		
				
	</div>
	
	<div class="form-group">
		<label class="control-label col-sm-2" >PR Name:</label>
		<div class="col-sm-3">
			<input class="form-control" type="text"  placeholder=""
				id = "prName" name="prName" value="<?php echo (!$entity == null)? $entity->getPrName():"";?>">
		</div>
		
		<label class="control-label col-sm-2" >Keywords:</label>
		<div class="col-sm-3">
			<input class="form-control" type="text"  placeholder=""
				id = "keywords" name="keywords" value="<?php echo (!$entity == null)? $entity->getKeywords():"";?>">
		</div>
	</div>
	
	<div class="form-group">
		<label class="control-label col-sm-2" >Department</label>
		<div class="col-sm-3">
<input disabled class="form-control" type="text" id="department_name" placeholder="Please select!" 
name="deparment_name" value="<?php if (!$entity== null):if($entity->getDepartment()!==null):echo $entity->getDepartment()->getNodeName(); endif;endif;?>">

<input type="hidden" class="form-control" type="text" id="department_name_selected" placeholder="Please select!" 
name="department_id" value="<?php if (!$entity== null):if($entity->getDepartment()!==null):echo $entity->getDepartment()->getNodeId(); endif;endif;?>">
			</div>
		
<a style="color: #0080ff;" href="javascript:;"
	onclick="showBootstrapDialog('Select Deparment','/application/department/list1','b_loaded_data');">Select&nbsp;&nbsp;<i class="glyphicon glyphicon-folder-open"></i>
</a>
    </div>	
	
	<div class="form-group">
		<label class="control-label col-sm-2" >Remarks:</label>
		<div class="col-sm-3">
			<textarea  class="form-control" type="text" rows="4" placeholder=""
				name="remarks" style="font-size: 9pt;"><?php echo (!$entity == null)? $entity->getRemarks():"";?></textarea>
		</div>
	</div>
	
	<div class="form-group">
		<label class="control-label col-sm-2" for="inputTag"></label>
		<div class="col-sm-3">
 <a class="btn btn-default" href="<?php echo $this->baseUrl ?>/procure/pr/edit?token=<?php echo (!$entity == null)? $entity->getToken():"";?>&entity_id=<?php echo (!$entity == null)? $entity->getId():"";?>&checksum=<?php echo (!$entity == null)? $entity->getChecksum():"";?>"><small><i class="glyphicon glyphicon-pencil"></i></small>&nbsp;Edit</a>
 
  		</div>
	</div> 
		
	
</form>
</div>
</div>

<script>
$("#Create_PR_Form :input").attr("disabled", "disabled");
</script>

