 <?php

/**
 *
 * @author Nguyen Mau Tri - ngmautri@gmail.com
 *         ===================================
 *        
 */
// ===========================================================
?>
<a style="font-size: 9pt; margin: 10pt 2pt 20pt 20pt"
    class="btn btn-default btn-sm" href="/procure/pr-report/header-status"> <small> <i
    class="fa fa-chevron-left" aria-hidden="true"></i>
    </small>&nbsp;&nbsp;&nbsp;&nbsp;<?php
    echo $this->translate("PR List");
    ?></a>   
<hr>
