<?php
use Application\Application\Helper\Form\FormHelper;
use Inventory\Form\ItemSerial\ItemSerialFilterForm;
use Procure\Application\Helper\Toolbar;
use Procure\Domain\PurchaseRequest\PRDoc;

/**
 *
 * @author Nguyen Mau Tri - ngmautri@gmail.com
 *         ===================================
 *        
 * @var PRDoc $rootEntity ;
 * @var ItemSerialFilterForm $form ;
 */
// ===========================================================

$tabs = null;

if (! $headerDTO == null) {

    $picture_url = sprintf($this->baseUrl . "/procure/pr-attachment/get-pictures?target_id=%s&token=%s", $headerDTO->getId(), $headerDTO->getToken());
    $format = '/inventory/item-picture/list1?token=%s&target_id=%s';
    $url1 = sprintf($format, $headerDTO->getToken(), $headerDTO->getId());
    $picturesTab = sprintf('<a title="Picture" href="%s"><span class="glyphicon glyphicon-picture"></span>&nbsp;(%s)</a></li></a>', $picture_url, '');

    $format = '/inventory/item-attachment/list1?token=%s&target_id=%s';
    $url1 = sprintf($format, $headerDTO->getToken(), $headerDTO->getId());
    $attachment_url = sprintf($this->baseUrl . "/procure/pr-attachment/list1?target_id=%s&token=%s", $headerDTO->getId(), $headerDTO->getToken());
    $attachTab = sprintf('<a title="Serial" href="%s"><span class="glyphicon glyphicon-paperclip"></span>&nbsp;(%s)</a></li></a>', $attachment_url, '');

    $format = '/inventory/change-log/list1?object_token=%s&object_id=%s';
    $url1 = sprintf($format, $headerDTO->getToken(), $headerDTO->getId());
    $log_url = sprintf($this->baseUrl . "/application/message-store/list1?entity_id=%s&entity_token=%s", $headerDTO->getId(), $headerDTO->getToken());
    $logTab = sprintf('<a title="Change Log" href="%s"><span class="glyphicon glyphicon-list"></span>&nbsp;Log</a></li></a>', $log_url);

    $tabsList = [
        // $logisticTab,
        $picturesTab,
        $attachTab,
        $logTab
    ];

    $tabs = FormHelper::createTabs($tabsList);
}
?>

<div id="wrapper" class="toggled">

	<!-- Sidebar -->
	<div id="sidebar-wrapper" style="font-size: 9.5pt;">
		
		<?=$this->sidebar_buttons;?>
		<?=$this->wizard;?>
		
		<div id="doc_summary"><?=$this->summary;?> </div>
		
		
		<!-- Sidebar -->
	</div>

	<!-- Page Content -->
	<div id="page-content-wrapper"
		style="font-size: 9.5pt; padding: 0px; margin: 0px;">

		<!-- /#page-container -->
		<div class="container-fluid" id="main_container"
			style="font-size: 9.5pt; padding: 1px; margin: 0px;";>
			<a style="font-size: 9pt; margin: 2px; padding: 3px;"
				href="#menu-toggle" class="btn btn-primary btn-sm" id="menu-toggle">
				<span title="Hide Menu"> <i class="fa fa-chevron-left"
					aria-hidden="true"></i> Menu <span>
						</a>


			<div id="tabs" style="font-size: 9.5pt">
				<ul>
					<li><a href="#general">VIEW</a></li>
						<?php
    echo $tabs;
    ?>
				</ul>

				<div id="general" style="font-size: 9pt; padding: 10px 6px 1px 5px">

					<!-- ======== TOOL BAR ======= -->
					<div style="position: relative; float: right;">
    <?php
    echo Toolbar::showToolbarPR($rootEntity->makeSnapshot(), $action, $this);
    ?>
					<!-- ======== TOOL BAR ======= -->
					 </div>
					<hr>					<a href="#doc_header" class="" data-toggle="collapse">HEADER</a>
					<div id="doc_header" class="collapse in">
						<div id="header">
								<?=$this->header_form;?>
									
						</div>
					</div>

					<div id="row_containter"></div>

				</div>
			</div>

			<!-- /#page-container -->
		</div>

		<!-- Page Content -->
	</div>

	<!-- /#wrapper -->
</div>



<script>
<?php
$format = "var row_url = '/procure/pr/row-content?entity_id=%s&entity_token=%s'";
echo sprintf($format, $rootEntity->getId(), $rootEntity->getToken());
?>
</script>

<script>
	doPaginatorV1(row_url,'row_containter');
</script>

<!-- Confirm Posting -->
<?=$this->confirm_posting;?>
<!-- Confirm Posting -->


<script>
function confirmPost() {
 	$('#confirm_posting_modal_sm').modal();
}

function doPosting() {
   $('#confirm_posting_modal_sm').modal('hide');
   $('#b_modal_no_header').modal();
   submitForm('pr_create_form');
}
</script>
	
	