<?php
use Inventory\Application\DTO\Association\AssociationDTO;
use Procure\Application\Helper\ErrorMessage;
use Procure\Application\Helper\OptionList;

/**
 *
 * @author Nguyen Mau Tri - ngmautri@gmail.com
 *         ===========================================
 */
/**@var AssociationDTO $dto ;*/
/**@var \Application\Controller\Plugin\NmtPlugin $nmtPlugin ;*/

// var_dump($rootDto);

// echo memory_get_usage();
$message_url = null;
$associtation = null;

if ($dto !== null) {
    $associtation = $dto->getAssociation();
}

$associtation_option = OptionList::createAssociationOption($nmtPlugin->associationList(), $associtation);
$error_msg = ErrorMessage::showErrorMessage($errors);

// echo memory_get_usage();
// =====================================================
?>
<div id="tabs" style="font-size: 10pt">
   <ul>
      <li>
         <a href="#general"><?php

        echo $form_title;
        ?></a>
      </li>

<?php
if ($action == \Application\Model\Constants::FORM_ACTION_EDIT) :
    ?>
 	 	<li>
         <a href=""<?php

    echo $message_url;
    ?>">
            <span class="glyphicon glyphicon-list"></span>
            &nbsp;Log
         </a>
      </li>
<?php endif;

?>
				</ul>
   <div id="general" style="font-size: 9pt">
      <!-- Tab1 -->

<?php
// ================================
echo $error_msg;
// ===============================
?>
            <form id="New_Invoice_Row" class="form-horizontal" action="<?php

            echo $form_action;
            ?>" method="post" enctype="multipart/form-data">
         <input type="hidden" name="redirectUrl" value="<?php

        echo $redirectUrl?>" />
         <input type="hidden" name="version" value="<?php

        echo $version;
        ?>" />
         <input type="hidden" id="entity_id" name="entity_id" value="<?php

        echo $entity_id;
        ?>" />
         <input type="hidden" id="entity_token" name="entity_token" value="<?php
        echo $entity_token;
        ?>" />
         <div class="form-group margin-bottom  required">
            <label class="control-label col-sm-2">Main Item: </label>
            <div class="col-sm-3">
               <input tabindex="2" class="form-control" type="text" id="item_name" placeholder="Enter keyword to search item..." name="itemName" value="<?php

            if (! $dto == null) :
                echo $dto->getItemName();endif;

            ?>">
               <input type="hidden" id="item_id" placeholder="" name="mainItem" value="<?php

            if (! $dto == null) :
                echo $dto->getMainItem(); endif;

            ?>">
               <div id="item_url" style="display: none;"></div>
            </div>
            <div class="col-sm-1" style="margin: 0px">
               <span title="<?php

            echo $this->translate("Item Detail");
            ?>" id="item_detail" style="display: none;">
                  &nbsp;&nbsp;
                  <a style="color: #0080ff;" href="javascript:;" onclick="showSelectedItem();">
                     <i style="color: navy" class="fa fa-info-circle fa-lg" aria-hidden="true"></i>
                  </a>
                  <br>
               </span>
            </div>
            <div class="col-sm-1" style="margin: 0px">
               <a style="color: #0080ff;" href="javascript:;" onclick="showJqueryDialog('Select Item','1350',$(window).height()-50, '/inventory/item-search/do1?target_id=item_id&target_name=item_name','j_loaded_data', true);">
                  Select&nbsp;&nbsp;
                  <i class="glyphicon glyphicon-folder-open"></i>
               </a>
            </div>
            <div class="col-sm-1">
               <a target="_blank" style="font-size: 9pt;" href="/inventory/item/list">Item List&nbsp;&nbsp;</a>
               <small>
                  <i class="glyphicon glyphicon-new-window"></i>
               </small>
            </div>
         </div>
         <div class="form-group margin-bottom required">
            <label class="control-label col-sm-2"><?php
            echo $this->translate("Association");
            ?>:</label>
            <div class="col-sm-3">
               <select tabindex="9" name="association" id="association" class="form-control input-sm">
                  <option value=""><?php
                echo $this->translate("Select Association");
                ?></option>
<?php
// ================
echo $associtation_option;
// ================
?>
                                        </select>
            </div>
         </div>
         <hr style="margin: 5pt 1pt 5pt 1pt">
         <div class="form-group margin-bottom  required">
            <label class="control-label col-sm-2">Related Item: </label>
            <div class="col-sm-3">
               <input tabindex="2" class="form-control" type="text" id="related_item_name" placeholder="Enter keyword to search item..." name="relatedItemName"
                  value="<?php

                if (! $dto == null) :
                    echo $dto->getRelatedItem();endif;

                ?>">
               <input type="hidden" id="related_item_id" placeholder="" name="relatedItem" value="<?php

            if (! $dto == null) :
                echo $dto->getRelatedItem(); endif;

            ?>">
               <div id="related_item_url" style="display: none;"></div>
            </div>
            <div class="col-sm-1" style="margin: 0px">
               <span title="<?php

            echo $this->translate("Item Detail");
            ?>" id="related_item_detail" style="display: none;">
                  &nbsp;&nbsp;
                  <a style="color: #0080ff;" href="javascript:;" onclick="showSelectedRelatedItem();">
                     <i style="color: navy" class="fa fa-info-circle fa-lg" aria-hidden="true"></i>
                  </a>
                  <br>
               </span>
            </div>
            <div class="col-sm-1" style="margin: 0px">
               <a style="color: #0080ff;" href="javascript:;" onclick="showJqueryDialog('Select Item','1350',$(window).height()-50, '/inventory/item-search/do1?target_id=item_id&target_name=item_name','j_loaded_data', true);">
                  Select&nbsp;&nbsp;
                  <i class="glyphicon glyphicon-folder-open"></i>
               </a>
            </div>
            <div class="col-sm-1">
               <a target="_blank" style="font-size: 9pt;" href="/inventory/item/list">Item List&nbsp;&nbsp;</a>
               <small>
                  <i class="glyphicon glyphicon-new-window"></i>
               </small>
            </div>
         </div>
         <div class="form-group margin-bottom" style="margin-top: 10pt">
            <label class="control-label col-sm-2" for="inputTag"></label>
            <div class="col-sm-3">
               <a tabindex="11" class="btn btn-default btn-sm" onclick="submitForm('New_Invoice_Row');" href="javascript:;">
                  <small>
                     <i class="glyphicon glyphicon-floppy-disk"></i>
                  </small>&nbsp;<?php

                echo $this->translate("Save");
                ?></a>
               <a tabindex="12" class="btn btn-default btn-sm" href="<?php

            echo $review_url;
            ?>">
                  <small>
                     <i class="glyphicon glyphicon-remove"></i>
                  </small>&nbsp;<?php

                echo $this->translate("Cancel");
                ?></a>
            </div>
            <div class="col-sm-3"></div>
         </div>
      </form>
      <!-- COL 1 -->
   </div>
   <script type="text/javascript">

          // if select item, then delete all pr item
          
          $( "#item_name" ).autocomplete({
              source: "/inventory/item-search/auto-complete",
              minLength: 2,
              select: function( event, ui ) {

                // set pr row empty
                $( "#item_id" ).val(ui.item.id);

                $('#item_url').text('/inventory/item/show1?tab_idx=7&entity_id='+ui.item.id+'&token='+ui.item.token);
         	 	 $('#global-notice').show();
            	 $('#global-notice').html('"' + ui.item.value + '" selected');
            	 $('#global-notice').fadeOut(5000);
         	  	 $('#item_detail').show();
             }
            })
            .autocomplete( "instance" )._renderItem = function( ul, item ) {
          	  var serial_no = "";
          	  if(item.item_serial!=""){
          		  serial_no = " : " + item.item_serial;
          	  }
          	  var img = '<img class="img-rounded" width="60" height="60" src="'+item.item_thumbnail+'"/>';
              return $( "<li>" )
                 .append( "<div style='padding-bottom: 5px; border-bottom: thin solid gray;'><table><tr><td>"+img+"</td><td><span style='padding-left:5px; font-size: 9.5pt;font-weight: bold;'>" + item.value + "</span><br><span style='padding-left:5px; color:gray;font-size: 9pt;'>" + item.item_sku + serial_no +"<span></td></tr></table></div>" )
                 .appendTo( ul );
         };

             
         // if select item, then delete all pr item
          $( "#related_item_name" ).autocomplete({
              source: "/inventory/item-search/auto-complete",
              minLength: 2,
              select: function( event, ui ) {

                // set pr row empty
                $( "#related_item_id" ).val(ui.item.id);
                $('#related_item_url').text('/inventory/item/show1?tab_idx=7&entity_id='+ui.item.id+'&token='+ui.item.token);
                $('#global-notice').show();
                $('#global-notice').html('"' + ui.item.value + '" selected');
                $('#global-notice').fadeOut(5000);
               //$("#jquery_dialog").dialog("close");
                $('#related_item_detail').show();
          }

        })
        .autocomplete( "instance" )._renderItem = function( ul, item ) {
              var serial_no = "";
              if(item.item_serial!=""){
                 serial_no = " : " + item.item_serial;
              }

              var img = '<img class="img-rounded" width="60" height="60" src="'+item.item_thumbnail+'"/>';
                    

               return $( "<li>" )
                 .append( "<div style='padding-bottom: 5px; border-bottom: thin solid gray;'><table><tr><td>"+img+"</td><td><span style='padding-left:5px; font-size: 9.5pt;font-weight: bold;'>" + item.value + "</span><br><span style='padding-left:5px; color:gray;font-size: 9pt;'>" + item.item_sku + serial_no +"<span></td></tr></table></div>" )
                 .appendTo( ul );
             };

    	

        function showSelectedItem(){
    		var url= $('#item_url').text();
    	   	showJqueryDialog('Item Detail','1450',$(window).height()-40, url,'j_loaded_data', true);
    	}

        function showSelectedRelatedItem(){
		var url= $('#related_item_url').text();
	   	showJqueryDialog('Item Detail','1450',$(window).height()-40, url,'j_loaded_data', true);
	}
      
        <?php
        if ($dto !== null) :
            ?>
        		  $("#item_id" ).val(<?php

            echo $dto->getItem();
            ?>);
        	      $('#item_url').text('/inventory/item/show1?tab_idx=0&entity_id=<?php

            echo $dto->getItem();
            ?>&token=<?php

            echo $dto->getItemToken();
            ?>');
        		  $('#item_detail').show();
        		  $("#pr_row_id" ).val(<?php

            echo $dto->getPrRow();
            ?>);
          	      $('#pr_row_url').text('/procure/pr-row/show1?tab_idx=0&entity_id=<?php

            echo $dto->getPrRow();
            ?>');
          	      $('#pr_row_detail').show();
        <?php
       	 endif
        ?>
        
        
        
       
      function selectItem(id, token,target, name, target_name, context = null){
    	var target_id = '#' + target;
    	$(target_id).val(id);

        var target_name_id = '#' + target_name;
    	$(target_name_id).val(name);
    	$('#modal1.close').click();
    	$('#global-notice').show();
    	$('#global-notice').html('"' + name + '" selected');
    	$('#global-notice').fadeOut(5000);
    	$("#jquery_dialog").dialog("close");


        $("#item_id" ).val(id);
    	  	$('#item_url').text('/inventory/item/show1?tab_idx=9&entity_id='+id+'&token='+token);

    		$('#item_detail').show();
    		$("#quantity").focus();

    	var url = '/inventory/item/get-item?id='+id;
    		$('#rowUnit').val("Loading...");
    		$('#purchase_uom_convert_text').text("Loading...");

    	$.get(url, {   	}, function(data, status) {
        		//alert(data.purchase_uom_code);
        		$('#rowUnit').val(data.purchase_uom_code);
        		$('#standard_uom_id').text(data.uom_code);
        		$('#conversionFactor').val(data.purchase_uom_convert_factor);
                $('#purchase_uom_convert_text').text($( "#rowUnit" ).val() + " = " +  $('#conversionFactor').val() + " " + $( "#standard_uom_id" ).text());

       	});
    }


     </script>