<?php
/**
 *
 * @author Nguyen Mau Tri - ngmautri@gmail.com
 *         ===================================
 */

// echo $total_records;
use Procure\Application\Helper\FormHelper;

$message_log_div = "message_log_div";
$table_body = "";
$count = 0;
$n = 0;
$base = sprintf($this->baseUrl . "/application/message-store/list1?entity_id=%s&entity_token=%s", $entity_id, $entity_token);

$result_msg = "No record found!";

if (count($list) > 0) {

    $result_msg = sprintf("%s records found!", $total_records);

    if ($paginator !== null) {
        $result_msg = sprintf("Recored %s to %s | %s records found!", $paginator->minInPage, $paginator->maxInPage, $total_records);
    }

    foreach ($list as $item) {

        $n ++;

        if ($paginator !== null) {
            $count = $paginator->minInPage - 1 + $n;
        } else {
            $count = $n;
        }

        /**
         *
         * @var \Application\Entity\NmtInventoryAssociationItem $item ;
         */
        $table_body = $table_body . "<tr>";
        $table_body = $table_body . sprintf("<td>%s</td>", $count);
        $table_body = $table_body . sprintf("<td>%s</td>", $item->getAssociation()->getAssociationName());

        $table_body = $table_body . "</tr>";
    }
}
?>
<div id="<?php
echo $message_log_div;
?>">

	<?php

echo $result_msg;
?>
	<table id="mytable26" style="font-size: 9.5pt; color: graytext; font-family: Courier, monospace;" class="table table-bordered table-striped table-hover">
      <thead>
         <tr>
            <td>
               <b><?php

            echo $this->translate("#");
            ?></b>
            </td>
            <td>
               <b><?php

            echo $this->translate("Ver.");
            ?></b>
            </td>
            <td>
               <b><?php

            echo $this->translate("Rev.");
            ?></b>
            </td>
            <td>
               <b><?php

            echo $this->translate("Event Name");
            ?></b>
            </td>
            <td style="width: 160px">
               <b><?php

            echo $this->translate("Date");
            ?></b>
            </td>
            <td>
               <b><?php

            echo $this->translate("Change Log");
            ?></b>
            </td>
            <td>
               <b><?php

            echo $this->translate("By");
            ?></b>
            </td>
         </tr>
      </thead>
      <tbody>
		<?php

echo $table_body;
?>
		</tbody>
   </table>

<?php

// ===============================
echo FormHelper::createPaginatorAjax($base, $paginator, "&", $message_log_div);
// ===============================
?>

</div>
