<?php 
$item_name ='';

if($article!=null):
$item_name = $item_name . "Purchasing Data for item: " . $article->name; 
endif;

if($sp!=null):
$item_name = $item_name . "Purchasing Data for item: " . $sp->name;
endif;
?>

<h4> <?php echo $item_name;?></h4>
<hr>

<?php

if (count ( $errors ) > 0) {
	echo '<div class="alert alert-error">';
	
	echo '<ul>';
	foreach ( $errors as $error ) :
		echo '<li>' . $error . '</li>';
	endforeach
	;
	echo '</ul>';
	echo '</div>';
}
?>

<form class="form-horizontal" 	action="<?php echo $this->baseUrl ?>/inventory/purchasing/add"
	method="post" enctype="multipart/form-data" id="NewSP">
	<input type="hidden" name="redirectUrl" value="<?php echo $redirectUrl ?>" />
	<input type="hidden" name="id" value="<?php echo $id ?>" />
	<input type="hidden" name="type" value="<?php echo $type ?>" />
	
	<input type="hidden" name="vendor_id" id="vendor_id" value="<?php echo $submitted_purchasing !=null ? $submitted_purchasing->vendor_id : ""?>" />
	
	<div class="control-group">
		<label class="control-label" for="inputTag">Vendor:</label>
		<div class="controls">
			<input readonly type="text" id="vendor" placeholder="" name="vendor"
				value="<?php echo $vendor_name; ?>"> 
		
		<a href="javascript:;" onclick="showVendorDialog();"
				class="helper"> Select Vendor <i class=" icon-folder-open"></i></a>

	
		</div>
	</div>
	
	<div class="control-group">
		<label class="control-label" for="inputTag">Default Vendor:</label>
		<div class="controls">
			<select style="wight: 10px" name="is_preferred" id="is_preferred">
			
					<?php if($submitted_purchasing!=null):?>
					<option <?php echo $submitted_purchasing->is_preferred=='1'? "selected='selected'":"";?> value="1">YES</option>
					<option <?php echo $submitted_purchasing->is_preferred=='0'? "selected='selected'":"";?> value="0">NO</option>
					<?php else:?>
					<option value="1">YES</option>
					<option  selected=selected value="0">NO</option>
					<?php endif;?>
			</select>
			
			</div>
	</div>
	<div class="control-group">
		<label class="control-label" for="inputTag">Vendor Item Unit:</label>
		<div class="controls">
			<input type="text" placeholder="" name="vendor_unit"
				value="<?php echo $submitted_purchasing !=null ? $submitted_purchasing->vendor_unit : ""?>">
		</div>
	</div>
	<div class="control-group">
		<label class="control-label" for="inputTag">Unit Price:</label>
		<div class="controls">
			<input  type="text" id="vendor_unit_price" placeholder="" name="vendor_unit_price" value="<?php echo $submitted_purchasing !=null ? $submitted_purchasing->vendor_unit_price : ""?>">
			</div>
	</div>

	<div class="control-group">
		<label class="control-label" for="inputTag">Currency:</label>
		<div class="controls">
			<select style="wight: 10px" name="currency" id="currency">
				<option value="">---Please select---</option>
					
					<?php if($submitted_purchasing!=null):?>
					<option <?php echo $submitted_purchasing->currency=='USD'? "selected='selected'":"";?> value="USD">USD</option>
					<option <?php echo $submitted_purchasing->currency=='LAK'? "selected='selected'":"";?> value="LAK">LAK</option>
					<option <?php echo $submitted_purchasing->currency=='THB'? "selected='selected'":"";?> value="THB">THB</option>
					<?php else:?>
					<option value="USD">USD</option>
					<option value="LAK">LAK</option>
					<option value="THB">THB</option>
					<?php endif;?>
			</select>
			
			</div>
	</div>
	
	<div class="control-group">
		<label class="control-label" for="inputTag">Vendor Item Code:</label>
		<div class="controls">
			<input type="text" placeholder="" name="vendor_article_code"
				value="<?php echo $submitted_purchasing !=null ? $submitted_purchasing->vendor_article_code : ""?>">
		</div>
	</div>

	

	<div class="control-group">
		<div class="controls">
			<button type="submit" class="btn">
				<i class="icon-plus"> </i> Add
			</button>
		</div>
	</div>
</form>

<?php include (ROOT.'\module\Procurement\view\procurement\select_vendor.php'); ?>