
<?php /**@var \Application\Entity\NmtHrPosition $entity ; */ ?>
<h4>
	<a href="/hr/setting/index"><i class="fa fa-cog" aria-hidden="true"></i> <?php echo $this->translate('HR SETTING'); ?></a>
</h4>

<?php
if (count($errors) > 0) {
    echo '<div class="alert alert-danger" role="alert" style="font-size: 10.5pt">';

    echo '<ul>';
    foreach ($errors as $error) :
        echo '<li>' . $error . '</li>';
    endforeach
    ;
    echo '</ul>';
    echo '</div>';
}
?>

<div id="tabs" style="font-size: 9.5pt">
	<ul>
		<li><a href="#general"><?php echo $this->translate('New Postion'); ?></a></li>
	</ul>

	<div id="general">

		<form id="create_employee_form" class="form-horizontal"
			action="/hr/position/edit" method="post"
			enctype="multipart/form-data">
			<input type="hidden" name="redirectUrl"
				value="<?php echo $redirectUrl ?>" /> <input type="hidden"
				name="entity_id"
				value="<?php echo (!$entity== null)? $entity->getId():"";?>" /> <input
				type="hidden" name="token"
				value="<?php echo (!$entity== null)? $entity->getToken():"";?>" />


			<div class="form-group margin-bottom required">
				<label class="control-label col-sm-2"><?php echo $this->translate('Postion Code'); ?>:</label>
				<div class="col-sm-3">
					<input class="form-control input-sm" type="text"
						name="positionCode"
						value="<?php if(!$entity == null): echo $entity->getPositionCode(); endif;?>"
						placeholder="<?php echo $this->translate('please enter position code'); ?>"
						id="" />
				</div>

				<div class="col-sm-4">
					<input
						<?php if(!$entity == null): echo ($entity->getIsActive()=="1")?"checked":""; else: echo "checked"; endif;?>
						type="checkbox" name="isActive" value="1">&nbsp;<?php echo $this->translate('Active'); ?>&nbsp;&nbsp;
		</div>
			</div>

			<div class="form-group margin-bottom required">
				<label class="control-label col-sm-2"><?php echo $this->translate('Postion Name'); ?>:</label>
				<div class="col-sm-3">
					<input class="form-control input-sm" type="text"
						name="positionName"
						value="<?php if(!$entity == null): echo $entity->getPositionName(); endif;?>"
						placeholder="<?php echo $this->translate('please enter position name'); ?>"
						id="" />
				</div>
			</div>

			<div class="form-group margin-bottom required">
				<label class="control-label col-sm-2"><?php echo $this->translate('Cost Center'); ?></label>
				<div class="col-sm-3">
					<input class="form-control input-sm" type="text" name="costCenter"
						value="<?php if(!$entity == null): echo $entity->getCostCenter(); endif;?>"
						placeholder="" />
				</div>
			</div>

			<div class="form-group margin-bottom">
				<label class="control-label col-sm-2"><?php echo $this->translate('Vadid From'); ?>:</label>
				<div class="col-sm-3">
					<input class="form-control input-sm" type="text" placeholder=""
						name="validFrom" id="validFrom"
						value="<?php echo (!$entity == null)? $entity->getValidFrom():"";?>">
				</div>
			</div>
			<div class="form-group margin-bottom">
				<label class="control-label col-sm-2"><?php echo $this->translate('Vadid To'); ?>:</label>
				<div class="col-sm-3">
					<input class="form-control input-sm" type="text" placeholder=""
						name="validTo" id="validTo"
						value="<?php echo (!$entity == null)? $entity->getValidTo():"";?>">
				</div>
			</div>
			<div class="form-group margin-bottom">
				<label class="control-label col-sm-2"><?php echo $this->translate('Description'); ?>:</label>
				<div class="col-sm-8">
					<input class="form-control input-sm" type="text" placeholder=""
						name="description"
						value="<?php echo (!$entity == null)? $entity->getDescription():"";?>">
				</div>
			</div>
			<hr>


			<div class="form-group margin-bottom">
				<label class="control-label col-sm-2" for="inputTag"></label>
				<div class="col-sm-3">
					<a tabindex="10" class="btn btn-default btn-sm"
						onclick="submitForm('create_employee_form');" href="javascript:;"><small><i
							class="glyphicon glyphicon-floppy-disk"></i></small>&nbsp;<?php echo $this->translate('Save'); ?></a>
					<a tabindex="11" class="btn btn-default btn-sm"
						href="<?php echo $this->baseUrl ?>/hr/position/list"><small><i
							class=""></i></small>&nbsp;<?php echo $this->translate('Cancel'); ?></a>
				</div>
			</div>


		</form>
	</div>
</div>


<script>
$(function() {
   $( "input[id='validFrom']").datepicker({ firstDay: 1, dateFormat: 'yy-mm-dd',closeText: 'X', changeMonth: true, changeYear: true});
   $( "input[id='validTo']").datepicker({ firstDay: 1, dateFormat: 'yy-mm-dd',closeText: 'X', changeMonth: true, changeYear: true});
});

</script>


