<h4>
	<a href="/hr/setting/index"><i class="fa fa-cog" aria-hidden="true"></i> <?php echo $this->translate('HR SETTING'); ?></a>
</h4>
<div id="tabs" style="font-size: 9.5pt">

	<ul>
		<li><a href="#general"><?php echo $this->translate('Postion'); ?></a></li>
	</ul>
	<div id="general" style="font-size: 9pt">
		<a class="btn btn-default btn-sm"
			href="<?php echo $this->baseUrl ?>/hr/position/add"><small><i
				class="glyphicon glyphicon-plus"> </i></small>&nbsp;<?php echo $this->translate('New Postion'); ?></a>
		<hr>


<?php

if ($total_records <= 0) {

    echo 'No record found!';
} else {

    if (! is_null($paginator)) {
        echo 'Record ' . $paginator->minInPage . ' to ' . $paginator->maxInPage . ' | ' . $total_records . ' records found!';
    } else {
        echo $total_records . ' ' . $this->translate('records');
    }

    ?>

<table style="font-size: 10pt;" class="table table-bordered table-hover">
			<thead>
				<tr>
					<td><b>#</b></td>
					<td><b><?php echo $this->translate('Postion name'); ?></a></b></td>
					<td><b><?php echo $this->translate('Cost Center'); ?></a></b></td>
					<td><b><?php echo $this->translate('Vadid From'); ?></a></b></td>
					<td><b><?php echo $this->translate('Vadid To'); ?></a></b></td>
					<td><b><?php echo $this->translate('Created Date'); ?></a></b></td>
					<td><b><?php echo $this->translate('Action'); ?></a></b></td>
				</tr>
			</thead>

			<tbody>
 
	 <?php

    $count = 0;
    foreach ($list as $a) :
        $count ++;
        /**@var \Application\Entity\NmtHrPosition $a ; */
        ?>
	 <tr>
					<td><?php echo ($paginator===null)? $count:$paginator->minInPage -1+ $count;?></td>
					<td><?php echo $this->escapeHtml($a->getPositionName());?></td>
					<td><?php echo $this->escapeHtml($a->getCostCenter());?></td>
					<td><?php echo ($a->getValidFrom()!==null )? date_format ( $a->getValidFrom(), "d-m-y"):"";?> </td>
					<td><?php echo ($a->getValidTo()!==null )? date_format ( $a->getValidTo(), "d-m-y"):"";?> </td>
					<td><?php echo ($a->getCreatedOn()!==null )? date_format ( $a->getCreatedOn(), "d-m-y"):"";?> </td>
					<td><a
						href="<?php echo $this->baseUrl ?>/hr/position/show?token=<?php echo $this->escapeHtml($a->getToken());?>&entity_id=<?php echo $this->escapeHtml($a->getID());?>"><?php echo $this->translate('Show'); ?></a>
						<a
						href="<?php echo $this->baseUrl ?>/hr/position/edit?token=<?php echo $this->escapeHtml($a->getToken());?>&entity_id=<?php echo $this->escapeHtml($a->getID());?>"><?php echo $this->translate('Edit'); ?></a>
					</td>

				</tr>
<?php endforeach; ?>

 </tbody>
		</table>

<?php

    // ===============================
    if (! is_null($paginator)) :

        // change it only
        $base = $this->baseUrl . '/hr/position/list';
        $_connector_symbol = '?';

        $last = $base . $_connector_symbol . 'page=' . $paginator->totalPages . '&perPage=' . $paginator->resultsPerPage;
        $first = $base . $_connector_symbol . 'page=1&perPage=' . $paginator->resultsPerPage;

        $p1 = ($paginator->page) - 1;
        $p2 = ($paginator->page) + 1;

        $prev = $base . $_connector_symbol . 'page=' . $p1 . '&perPage=' . $paginator->resultsPerPage;
        $next = $base . $_connector_symbol . 'page=' . $p2 . '&perPage=' . $paginator->resultsPerPage;

        echo '<ul class="pagination pagination-sm">';

        if ($paginator->page != 1 and $paginator->totalPages > 10) {
            echo '<li><a href="' . $first . '"> |< </a></li>';
            echo '<li><a href="' . $prev . '"> < </a></li>';
        }

        for ($i = $paginator->minInPageSet; $i <= $paginator->maxInPageSet; $i ++) {

            $url = $base . $_connector_symbol . 'page=' . $i . '&perPage=' . $paginator->resultsPerPage;

            if ($i == $paginator->page) {
                echo '<li><a class="active" href="#">' . $i . '</a></li>';
            } else {
                echo '<li><a href="' . $url . '"> ' . $i . ' </a></li>';
            }
        }
        if ($paginator->page != $paginator->totalPages and $paginator->totalPages > 10) {
            echo '<li><a href="' . $next . '"> > </a></li>';
            echo '<li><a href="' . $last . '"> >| </a></li>';
        }
        echo '</ul>';
endif;
	
}
// ===============================
?>
</div>
</div>