
<?php
if ($total_records <= 0) {
	echo 'No record found!';
} else {

?>

<table style="font-size: 10pt;" class="table table-bordered table-hover">
	<thead>
		<tr>
			<td><b>#</b></td>
			<td><b>Item Name</b></td>
			<td><b>Unit</td>
			<td><b>Quantity</b></td>
			<td><b>Unit<br>Price</b></td>
			<td><b>Action</b></td>
		</tr>
	</thead>

	<tbody>
 
	 <?php
	
	$count = 0;
	foreach ( $list as $a ) :
	
	    /**@var \Application\Entity\FinVendorInvoiceRow $a ; */
		$count ++;
		?>
	<tr>
			<td><?php echo ($paginator===null)? $count:$paginator->getMinInPage() -1+ $count;?></td>
			<td><?php echo $a->getItem()->getItemName(); ?></td>
			<td><?php echo $a->getUnit(); ?></td>
			<td><?php echo $a->getQuantity(); ?></td>
			<td><?php echo $a->getUnitPrice(); ?></td>
			<td><?php echo $a->getGrossAmount(); ?></td>
			<td></td>			
		</tr>
<?php endforeach; ?>

 </tbody>
</table>

<?php }?>