<div class="container">
    
<div class="col-xs-12 col-md-12">
<h3><span class="label label-danger">403 - Access Denied</span></h3>

<hr>
<p>You are not allowed to access this page!</p>

<ul style="color: graytext; font-style: italic;">
<li>Resource is protected.</li>
<li>insufficient authority.</li>
</ul>

<div style="color: graytext;">Please go back and contract administator for support.</div>


<?php if ($isAjax == false):?>
<hr>
<button class="btn btn-default" onclick="window.history.back();"><i class="glyphicon glyphicon-arrow-left">  </i> Go Back</button>
<?php endif;?>
</div>
</div>