<div><h1>USER LIST</h1></div>
<h2> <?php echo $this->massage; ?></h2>

<?php
$form->setAttribute('action', $this->url('user', array('action' => 'add')));
$form->prepare();


echo $this->form()->openTag($form);
echo $this->formHidden($form->get('firstname'));
echo $this->formRow($form->get('lastname'));
echo $this->formRow($form->get('email'));
echo $this->formSubmit($form->get('submit'));
echo $this->form()->closeTag();


echo $this->formCollection($form);

?>



<table border="1">
 <?php foreach ($users as $user) : ?>
    <tr>
        <td><?php echo $this->escapeHtml($user->id);?></td>
        <td><?php echo $this->escapeHtml($user->firstname);?></td>
        <td><?php echo $this->escapeHtml($user->lastname);?></td>
        <td><?php echo $this->escapeHtml($user->email);?></td>
    </tr>
<?php endforeach; ?>
</table>


