<div class="container">
    
<div class="col-xs-12 col-md-12">
<h3><span class="label label-warning">404 - Not Found</span></h3>

<hr>
<p>Requested resource can not be found!</p>

<ul style="color: graytext; font-style: italic;">
<li>Resource have been deleted or removed.</li>
<li>Or the URL is probraly modified manually.</li>
</ul>


<?php if ($isAjax == false):?>
<hr>
<button class="btn btn-default" onclick="window.history.back();"><i class="glyphicon glyphicon-arrow-left">  </i> Go Back</button>
<?php endif;?>
</div>
</div>