
<div id="tabs" style="font-size: 9.5pt">

	<ul>
		<li><a href="#general"><?php echo $this->translate("Exchange Rate");?></a></li>
	</ul>
	<div id="general">

		<a class="btn btn-default btn-sm"
			href="<?php echo $this->baseUrl ?>/finance/fx/add"><small><i
				class="glyphicon glyphicon-plus"> </i></small>&nbsp;<?php echo $this->translate("Add new Fx");?></a>
		<hr>

		<div>
			<small><span class="glyphicon glyphicon-filter"></span></small>&nbsp;<a
				href="#list_filter" class="" data-toggle="collapse">FILTER</a>
		</div>
		<div id="list_filter" class="collapse">

			<div
				style="border: 1px; padding: 3px; font-size: 9pt; background: url(/images/bg1.png); background-repeat: repeat-x; background-color: #FFFFFF;">


			</div>
		</div>

		<br>



<?php
if ($total_records <= 0) :
    echo 'No record found!';
else :

    if (! is_null($paginator)) :
        echo 'Record ' . $paginator->getMinInPage() . ' to ' . $paginator->getMaxInPage() . ' | ' . $total_records . ' records found!';
    else :
        echo $total_records . ' records found!';
    endif;

    ?>

<table style="font-size: 9.5pt;"
			class="table table-bordered table-hover">
			<thead>
				<tr>
					<td><b>#</b></td>
					<td><b>Date</b></td>
					<td><b>Source</b></td>
					<td><b>Target</b></td>
					<td><b>Rate</b></td>
					<td><b>Action</b></td>
				</tr>
			</thead>

			<tbody>
 
	 <?php

    $count = 0;
    foreach ($list as $l) :
        $count ++;

        /**@var \Application\Entity\FinReRow $a ; */
        $a = $l;
        ?>
		
	<tr>
					<td><?php echo $count;?></td>
					<td><?php echo date_format($a->getFxDate(),"d-m-Y");?></td>
					<td><?php echo $a->getSourceCurrency()->getCurrency();?></td>
					<td><?php echo $a->getTargetCurrency()->getCurrency()?></td>
					<td><?php echo number_format($a->getFxRate(),4)?></td>
					<td><a style="color: blue;"
						href="<?php echo $this->baseUrl ?>/finance/fx/show?token=<?php echo $a->getToken(); ?>&entity_id=<?php echo $a->getId(); ?>"><?php echo $this->translate('show'); ?></a>

						<a style="color: blue;"
						href="<?php echo $this->baseUrl ?>/finance/fx/edit?token=<?php echo $a->getToken(); ?>&entity_id=<?php echo $a->getId(); ?>"><?php echo $this->translate('Edit'); ?></a>
					</td>
	<?php endforeach; ?>
 
			
			</tbody>
		</table>


<?php
    // ===============================
    if (! is_null($paginator)) :

        // change it only
        $base = $this->baseUrl . '/finance/fx/list';
        $_connector_symbol = '?';

        $last = $base . $_connector_symbol . 'page=' . $paginator->getTotalPages() . '&perPage=' . $paginator->getResultsPerPage();;
        $first = $base . $_connector_symbol . 'page=1&perPage=' . $paginator->getResultsPerPage();;

        $p1 = ($paginator->getPage()) - 1;
        $p2 = ($paginator->getPage()) + 1;

        $prev = $base . $_connector_symbol . 'page=' . $p1 . '&perPage=' . $paginator->getResultsPerPage();;
        $next = $base . $_connector_symbol . 'page=' . $p2 . '&perPage=' . $paginator->getResultsPerPage();;

        echo '<ul class="pagination pagination-sm">';

        if ($paginator->getPage() != 1 and $paginator->getTotalPages() > 10) {
            echo '<li><a href="' . $first . '"> |< </a></li>';
            echo '<li><a href="' . $prev . '"> < </a></li>';
        }

        for ($i = $paginator->getMinInPageSet(); $i <= $paginator->getMaxInPageSet(); $i ++) {

            $url = $base . $_connector_symbol . 'page=' . $i . '&perPage=' . $paginator->getResultsPerPage();;

            if ($i == $paginator->getPage()) {
                echo '<li><a class="active" href="#">' . $i . '</a></li>';
            } else {
                echo '<li><a href="' . $url . '"> ' . $i . ' </a></li>';
            }
        }
        if ($paginator->getPage() != $paginator->getTotalPages() and $paginator->getTotalPages() > 10) {
            echo '<li><a href="' . $next . '"> > </a></li>';
            echo '<li><a href="' . $last . '"> >| </a></li>';
        }
		echo '</ul>';
endif;
// ===============================
?>

</div>
<?php endif; ?>
</div>
<?php

