
<div id="tabs" style="font-size: 9.5pt">

	<ul>
		<li><a href="#general"><?php echo $this->translate('Social Security Management'); ?></a></li>
	</ul>
	<div id="general" style="font-size: 9pt">

		<hr>
		<table style="font-size: 9pt;"
			class="table table-bordered table-hover">
			<thead>
				<tr>
					<td><b>#</b></td>
					<td><b><?php echo $this->translate('SSO Employee Rate'); ?></b></td>
					<td><b><?php echo $this->translate('SSO Employeer Rate'); ?></b></td>
					<td><b><?php echo $this->translate('Maximum Contribution'); ?></b></td>
					<td><b><?php echo $this->translate('Effective from'); ?></b></td>
					<td><b><?php echo $this->translate('Effective to'); ?></b></td>
					<td><b><?php echo $this->translate('Status'); ?></b></td>
					<td><b><?php echo $this->translate('Action'); ?></b></td>
				</tr>
			</thead>

			<tbody>

				<tr>
					<td>1</td>
					<td>5,5%</td>
					<td>5%</td>
					<td>2.000.000</td>
					<td>01/01/2013</td>
					<td>01/04/2015</td>
					<td><?php echo $this->translate('Inactive'); ?></td>
					<td><a style="color: navy" href="#"><?php echo $this->translate('Show'); ?></a></td>
				</tr>
				<tr>
					<td>1</td>
					<td>5,5%</td>
					<td>6%</td>
					<td>4.500.000</td>
					<td>01/04/2015</td>
					<td></td>
					<td><?php echo $this->translate('Active'); ?></td>
					<td><a style="color: navy" href="#"><?php echo $this->translate('Show'); ?></a>
						| <a style="color: navy" href="#"><?php echo $this->translate('Update'); ?></a></b></td>

				</tr>
			</tbody>
			</tbody>
		</table>


	</div>
</div>
