<?php
/**
 *
 * @author Nguyen Mau Tri - ngmautri@gmail.com
 *         ===================================
 */
use Application\Application\Helper\ErrorMessage;
use Application\Application\Helper\OptionList;
use Application\Controller\Plugin\SharedCollectionPlugin;
use Application\Domain\Shared\Constants;

/**
 *
 * @var \Inventory\Application\DTO\Item\ItemDTO $dto ;
 * @var \Application\Controller\Plugin\NmtPlugin $nmtPlugin ;
 * @var SharedCollectionPlugin $sharedCollection ;
 */
$tab_active = 0;
if (isset($tab_idx)) {
    $tab_active = $tab_idx;
}

$groupUOM = null;
$standardUOM = null;
$stockUOM = null;
$purchaseUOM = null;
$salesUOM = null;
$itemGroup = null;
$itemTypeId = null;
$monitorMethod = null;
$dropDown = null;
$tabs = null;
$img = null;
$view_url = null;

$isModelFormat = '<input type="hidden" name="isModel" value="0">';
$isModelFormat = $isModelFormat . '<input %s type="checkbox" name="isModel" value="1">&nbsp;Model&nbsp;';
$isModel = sprintf($isModelFormat, "");

$isActiveFormat = '<input type="hidden" name="isModel" isActive="0">';
$isActiveFormat = $isActiveFormat . '<input %s type="checkbox" name="isActive" value="1">&nbsp;Active&nbsp;';
$isActive = sprintf($isActiveFormat, "");

$isPurchaseFormat = '<input type="hidden" name="isPurchased" isActive="0">';
$isPurchaseFormat = $isPurchaseFormat . '<input %s type="checkbox" name="isPurchased" value="1">&nbsp;Purchased&nbsp;';
$isPurchased = sprintf($isPurchaseFormat, "");

$entityFormInput = '';
$submitItemFormInput = '';
$submitLogisticFormInput = '';

if ($action == Constants::FORM_ACTION_EDIT) {
    $view_url = sprintf($this->baseUrl . "/inventory/item/view?entity_id=%s&entity_token=%s", $entity_id, $entity_token);

    $format = '<input type="hidden" name="redirectUrl" value="%s">';
    $entityFormInput = $entityFormInput . sprintf($format, $redirectUrl);

    $format = '<input type="hidden" id="entity_id" name="entity_id" value="%s">';
    $entityFormInput = $entityFormInput . sprintf($format, $entity_id);

    $format = '<input type="hidden" id="entity_token" name="entity_token" value="%s">';
    $entityFormInput = $entityFormInput . sprintf($format, $entity_token);

    $format = '<input type="hidden" id="version" name="version" value="%s">';
    $entityFormInput = $entityFormInput . sprintf($format, $version);

    $format = '<div class="form-group margin-bottom"><div class="col-sm-offset-2 col-sm-10">
<button onclick="submitForm(\'%s\');" class="btn btn-default">
<i class="glyphicon glyphicon-floppy-disk"> </i>&nbsp;Save</button>
<a class="btn btn-default btn-sm" href="%s"><small><i class="glyphicon glyphicon-remove"></i></small>&nbsp;%s</a>
</div></div>';
    $submitItemFormInput = $entityFormInput . sprintf($format, 'create_item_form', $view_url, $this->translate("Cancel"));

    $format = '<div class="form-group margin-bottom"><div class="col-sm-offset-2 col-sm-10">
<button onclick="submitForm(\'%s\');" class="btn btn-default">
<i class="glyphicon glyphicon-floppy-disk"> </i>&nbsp;Save</button>
<a class="btn btn-default btn-sm" href="%s"><small><i class="glyphicon glyphicon-remove"></i></small>&nbsp;%s</a>
</div></div>';
    $submitLogisticFormInput = $submitLogisticFormInput . sprintf($format, 'logistic_data_frm', $view_url, $this->translate("Cancel"));
}

if ($action != Constants::FORM_ACTION_SHOW) {

    $format = '<div class="form-group margin-bottom"><div class="col-sm-offset-2 col-sm-10">
<button onclick="submitForm(\'%s\');" class="btn btn-default">
<i class="glyphicon glyphicon-floppy-disk"> </i>&nbsp;Save</button>
<a class="btn btn-default btn-sm" href="%s"><small><i class="glyphicon glyphicon-remove"></i></small>&nbsp;%s</a>
</div></div>';
    $submitItemFormInput = $entityFormInput . sprintf($format, 'create_item_form', $view_url, $this->translate("Cancel"));
}

$hsCodeSearchUrl = '';
$q = '';
if (! $dto == null) {

    $q = $dto->hsCode;
    if (strlen($dto->hsCode) > 6) {
        $q = substr($dto->hsCode, 0, 6) . "*";
    }

    $format = '/inventory/hs-code/search?q=%s';
    $hsCodeSearchUrl = sprintf($format, $q);

    if ($dto->getIsModel() == "1") {
        $isModel = sprintf($isModelFormat, 'checked');
    }

    if ($dto->getIsActive() == "1") {
        $isActive = sprintf($isActiveFormat, 'checked');
    }

    if ($dto->getIsPurchased() == "1") {
        $isPurchased = sprintf($isPurchaseFormat, 'checked');
    }

    $groupUOM = $dto->getUomGroup();
    $standardUOM = $dto->getStandardUom();
    $stockUOM = $dto->getStockUom();
    $purchaseUOM = $dto->getPurchaseUom();
    $salesUOM = $dto->getSalesUom();
    $itemGroup = $dto->getItemGroup();
    $itemTypeId = $dto->getItemTypeId();
    $monitorMethod = $dto->getMonitoredBy();

    $format = '<a href="/inventory/item/update?entity_token=%s&entity_id=%s"><small><i class="glyphicon glyphicon-pencil"></i></small>&nbsp;Edit</a>';
    $editUrl = sprintf($format, $dto->getToken(), $dto->getId());

    $format = '<a href="/inventory/item/upload-picture?token=%s&target_id=%s"><small><i class="fa fa-upload"></i></small>&nbsp;Upload Picture</a>';
    $pictureUrl = sprintf($format, $dto->getToken(), $dto->getId());

    $format = '<a href="/inventory/item-attachment/upload?token=%s&target_id=%s"><small><i class="fa fa-upload"></i></small>&nbsp;Upload Attachment</a>';
    $attachmentUrl = sprintf($format, $dto->getToken(), $dto->getId());

    $dropDownList = [
        $editUrl,
        'divider',
        $pictureUrl,
        $attachmentUrl
    ];

    $dropDown = \Application\Application\Helper\FormHelper::createDropDownBtn($dropDownList);

    if ($action == Constants::FORM_ACTION_SHOW) {

        $format = '/procure/price-comparison/price-of-item?token=%s&item_id=%s';
        $url1 = sprintf($format, $dto->getToken(), $dto->getId());

        $pricesTab = sprintf('<a title="Price Comparison" href="%s"><i class="fa fa-bar-chart" aria-hidden="true"></i></a>', $url1);

        $format = '/inventory/item-picture/list1?token=%s&target_id=%s';
        $url1 = sprintf($format, $dto->getToken(), $dto->getId());
        $picturesTab = sprintf('<a title="Picture" href="%s"><span class="glyphicon glyphicon-picture"></span>&nbsp;(%s)</a></li></a>', $url1, $dto->getPictureList()->count());

        $format = '/inventory/item-serial/list1?token=%s&target_id=%s';
        $url1 = sprintf($format, $dto->getToken(), $dto->getId());
        $serialNoTab = sprintf('<a title="Serial" href="%s"><span class=""></span>Serial No.(%s)</a></li></a>', $url1, $dto->getSerialNoList()->count());

        $format = '/inventory/item-attachment/list1?token=%s&target_id=%s';
        $url1 = sprintf($format, $dto->getToken(), $dto->getId());
        $attachTab = sprintf('<a title="Serial" href="%s"><span class="glyphicon glyphicon-paperclip"></span>&nbsp;(%s)</a></li></a>', $url1, $dto->getAttachmentList()->count());

        $format = '/procure/pr-row/pr-of-item?token=%s&item_id=%s';
        $url1 = sprintf($format, $dto->getToken(), $dto->getId());
        $prTab = sprintf('<a title="Purchase Request" href="%s">PR&nbsp;(%s)</a></li></a>', $url1, $dto->getPrList()->count());

        $format = '/procure/quote-row/qo-of-item?token=%s&item_id=%s';
        $url1 = sprintf($format, $dto->getToken(), $dto->getId());
        $qoTab = sprintf('<a title="Quotation" href="%s">QO&nbsp;(%s)</a></li></a>', $url1, $dto->getQoList()->count());

        $format = '/procure/po-row/po-of-item?token=%s&item_id=%s';
        $url1 = sprintf($format, $dto->getToken(), $dto->getId());
        $poTab = sprintf('<a title="Purchase Order" href="%s">PO&nbsp;(%s)</a></li></a>', $url1, $dto->getPoList()->count());

        $format = '/finance/v-invoice-row/ap-of-item?token=%s&item_id=%s';
        $url1 = sprintf($format, $dto->getToken(), $dto->getId());
        $apTab = sprintf('<a title="AP Invoice" href="%s">AP&nbsp;(%s)</a></li></a>', $url1, $dto->getApList()->count());

        $format = '/inventory/change-log/list1?object_token=%s&object_id=%s';
        $url1 = sprintf($format, $dto->getToken(), $dto->getId());
        $logTab = sprintf('<a title="Change Log" href="%s"><span class="glyphicon glyphicon-list"></span>&nbsp;Log</a></li></a>', $url1);

        $format = '/inventory/stock/summary?token=%s&target_id=%s';
        $url1 = sprintf($format, $dto->getToken(), $dto->getId());
        $stockTab = sprintf('<a title="Serial" href="%s"><i class="fa fa-industry" aria-hidden="true"></i>&nbsp;Stock</a>', $url1);

        $format = '/inventory/association-item/list?token=%s&entity_id=%s';
        $url1 = sprintf($format, $dto->getToken(), $dto->getId());
        $associationTab = sprintf('<a title="Association" href="%s"><i class="fa fa-chain" aria-hidden="true"></i>&nbsp;Association (%s)</a>', $url1, $dto->getAssociationList()->count());

        $format = '/finance/v-invoice-row/ap-of-item?token=%s&item_id=%s';
        $url1 = sprintf($format, $dto->getToken(), $dto->getId());
        $logisticTab = sprintf('<a title="Logistic" href="%s"><i class="fa fa-truck" aria-hidden="true"></i>&nbsp;Logistic %s</a>', $url1, "");

        $format = '/inventory/trx-report/issue-for-trx?itemId=%s';
        $url1 = sprintf($format, $dto->getId());
        $repairTab = sprintf('<a title="Repair Cost Overview" href="%s"><i class="fa fa-wrench" aria-hidden="true"></i>&nbsp;Repair Cost %s</a>', $url1, "");

        $format = '/inventory/item-variant/list?target_token=%s&target_id=%s';
        $url1 = sprintf($format, $dto->getToken(), $dto->getId());
        $variantTab = sprintf('<a title="Serial" href="%s"><i class="fa fa-list" aria-hidden="true"></i>&nbsp;Variant</a>', $url1);

        $tabsList = [
            // $logisticTab,
            $variantTab,
            $stockTab,
            $repairTab,
            $pricesTab,
            $picturesTab,
            $attachTab,
            $serialNoTab,
            $prTab,
            $qoTab,
            $poTab,
            $apTab,
            $logTab,
            $associationTab
        ];

        $tabs = \Application\Application\Helper\FormHelper::createTabs($tabsList);
    }

    $url = $nmtPlugin->getItemPic($dto->getId());
    if ($url == null) {
        $url = '/images/no-pic1.jpg';
    }
    $format = '<img style="cursor: pointer;" title="click for more detail!" onclick="$(\' // tabs\').tabs({ active: 1});" class="img-rounded" width="150" height="150" src="%s" />';
    $img = sprintf($format, $url);
}

$uomList = $nmtPlugin->uomList();
$item_group_list = $nmtPlugin->itemGroupList();
$uomGroupList = $sharedCollection->getUomGroupCollection();

$uom_group_option = OptionList::createUoMGroupOption($uomGroupList, $groupUOM);

$uom_option = OptionList::createUoMOption($uomList, $standardUOM);
$stock_uom_option = OptionList::createUoMOption($uomList, $stockUOM);
$purchase_uom_option = OptionList::createUoMOption($uomList, $purchaseUOM);
$sales_uom_option = OptionList::createUoMOption($uomList, $salesUOM);
$item_group_option = OptionList::createItemGroupOption($item_group_list, $itemGroup);
$item_type_option = OptionList::createItemTypeOption($itemTypeId);
$item_monitor_option = OptionList::createItemMonitorOption($monitorMethod);

$error_msg = ErrorMessage::showErrorMessage($errors);

// ================================
?>
<div style="position: relative; float: right;">
   <img alt="" height="" src="/inventory/item/barcode?barcode=<?php

echo (! $dto == null) ? $dto->getAssetLabel() : "";
?>">
</div>
<div>
   <table style="">
      <tr style="padding: 1pt 2pt 2pt 10pt;">
         <td style="width: 50pt;">&nbsp;</td>
         <td>
            <div style="position: relative; float: right; padding: 1pt 2pt 2pt 5pt">
            <?php
            echo $img;
            ?>
            </div>
         </td>
         <td style="padding: 1pt 2pt 2pt 10pt;">
            <h3 style="padding: 2pt 2pt 2pt 1pt;"><?php

            echo (! $dto == null) ? $dto->getItemName() : "";
            ?></h3>
            <span style="color: gray; font-size: 9.5pt"><?php

            echo (! $dto == null) ? "Item No.: " . $dto->getSysNumber() : "";
            ?></span>
            <span style="color: gray; font-size: 9.5pt"><?php

            echo (! $dto == null) ? "SKU: " . $dto->getItemSku() : "";
            ?></span>
            <div style="color: gray; padding-top: 5pt; font-size: 8pt"><?php

            if (! $dto == null) :
                echo ($dto->getCreatedOn()); endif;

            ?></div>
            <div style="color: gray; padding-top: 2pt; font-size: 8pt"><?php

            if (! $dto == null) :
                echo 'Revision# ' . $dto->getRevisionNo() . ' - Last Change: ' . $dto->getLastChangeOn(); endif;

            ?></div>
            <div style="color: gray; padding-top: 2pt; font-size: 8pt"><?php
            if (! $dto == null) :
                echo $dto->getOnHandQty(); endif;

            ?></div>
            <?php
            echo $dropDown;
            ?>
            </td>


      <tr>

   </table>
</div>
<div style="font-size: 9pt" id="<?php

echo $tab_id;
?>">
   <ul>
      <li>
         <a href="#general"><?php
        echo $form_title;
        ?></a>
      </li>
      <li>
         <a href="#logistic">
            <i class="fa fa-truck" aria-hidden="true"></i>
            &nbsp;Logistic
         </a>
      </li>

      <?php
    echo $tabs;
    ?>

   </ul>
   <div id="logistic">
   <?php
echo $error_msg;
?>

      <form id="logistic_data_frm" class="form-horizontal" action="/inventory/item/update-logistic" method="post">

        <?php
        echo $entityFormInput;
        ?>
         <div class="form-group margin-bottom required">
            <label class="control-label col-sm-2">HS Code</label>
            <div class="col-sm-3">
               <input class="form-control input-sm" type="text" placeholder="" name="hsCode" value="<?php
            echo (! $dto1 == null) ? $dto->hsCode : "";
            ?>">
            </div>
            <a class="btn btn-default btn-sm" target="blank" style="font-size: 9pt;" href="<?php
            echo $hsCodeSearchUrl;
            ?>">
               HS Code Search&nbsp;
               <i class="fa fa-search" aria-hidden="true"></i>
            </a>
         </div>
         <div class="form-group margin-bottom required">
            <label class="control-label col-sm-2">HS Code Description: </label>
            <div class="col-sm-3">
               <textarea class="form-control input-sm" type="text" rows="5" placeholder="" name="hsCodeDescription" style="font-size: 9pt;"><?php

            echo (! $dto1 == null) ? $dto->hsCodeDescription : "";
            ?></textarea>
            </div>
         </div>
         <hr style="margin: 5pt 1pt 5pt 1pt;">
         <div class="form-group margin-bottom required">
            <label class="control-label col-sm-2">Standard Weight (kg):</label>
            <div class="col-sm-3">
               <input class="form-control input-sm" type="text" placeholder="" name="standardWeightInKg" value="<?php
            echo (! $dto1 == null) ? $dto->standardWeightInKg : "";
            ?>">
            </div>
         </div>
         <div class="form-group margin-bottom required">
            <label class="control-label col-sm-2">Standard Volumn (m3):</label>
            <div class="col-sm-3">
               <input class="form-control input-sm" type="text" placeholder="" name="standardVolumnInM3" value="<?php
            echo (! $dto1 == null) ? $dto->standardVolumnInM3 : "";
            ?>">
            </div>
         </div>
          <?php
        echo $submitLogisticFormInput;
        ?>
      </form>
   </div>
   <div id="general">

<?php
echo $error_msg;
?>

		<form id="create_item_form" class="form-horizontal" action="<?php

echo $form_action;
?>" method="post" enctype="multipart/form-data">

  <?php
echo $entityFormInput;
?>


			<div class="form-group margin-bottom required">
            <label class="control-label col-sm-2">Item Type</label>
            <div class="col-sm-3">
               <select class="form-control input-sm" name="itemTypeId">
                 <?php
                echo $item_type_option;
                ?>
               </select>
            </div>
         </div>
         <hr style="margin: 5pt 1pt 5pt 1pt;">
         <div class="form-group margin-bottom required">
            <label class="control-label col-sm-2">Item ID</label>
            <div class="col-sm-3">
               <input class="form-control input-sm" type="text" placeholder="" name="itemSku" value="<?php

            echo (! $dto == null) ? $dto->itemSku : "xx";
            ?>">
               <input class="form-control input-sm" type="text" placeholder="optional sku" name="itemSku1" value="<?php

            echo (! $dto == null) ? $dto->itemSku1 : "xx";
            ?>">
               <input class="form-control input-sm" type="text" placeholder="optional sku" name="itemSku2" value="<?php

            echo (! $dto == null) ? $dto->itemSku2 : "xx";
            ?>">
            </div>
            <div class="col-sm-4">
               <?php
            echo $isActive . '&nbsp;&nbsp;' . $isModel . '&nbsp;&nbsp;' . $isPurchased;
            ?>

            </div>
            <div class="col-sm-3">
               <img alt="" height="" src="/inventory/item/barcode?barcode=<?php

            echo (! $dto == null) ? $dto->getSysNumber() : "";
            ?>">
            </div>
         </div>
         <hr style="margin: 5pt 1pt 5pt 1pt;">
         <div class="form-group margin-bottom required">
            <label class="control-label col-sm-2">Item Name</label>
            <div class="col-sm-3">
               <input class="form-control input-sm" type="text" placeholder="" name="itemName" value="<?php

            echo (! $dto == null) ? $dto->itemName : "";
            ?>">
            </div>
         </div>
         <div class="form-group margin-bottom required">
            <label class="control-label col-sm-2">Item Foreign Name1</label>
            <div class="col-sm-3">
               <input class="form-control input-sm" type="text" placeholder="" name="itemNameForeign" value="<?php

            echo (! $dto == null) ? $dto->itemNameForeign : "";
            ?>">
            </div>
            <label class="control-label col-sm-2">Item Foreign Name2</label>
            <div class="col-sm-3">
               <input class="form-control input-sm" type="text" placeholder="" name="itemName1" value="<?php

            echo (! $dto == null) ? $dto->itemName1 : "";
            ?>">
            </div>
         </div>
         <div class="form-group margin-bottom">
            <label class="control-label col-sm-2">Item Description</label>
            <div class="col-sm-8">
               <input class="form-control input-sm" type="text" placeholder="" name="itemDescription" value="<?php

            echo (! $dto == null) ? $dto->itemDescription : "";
            ?>">
            </div>
         </div>
         <div class="form-group margin-bottom">
            <label class="control-label col-sm-2">Keyworks</label>
            <div class="col-sm-3">
               <input class="form-control input-sm" type="text" placeholder="" name="keywords" value="<?php

            echo (! $dto == null) ? $dto->keywords : "";
            ?>">
            </div>
         </div>
         <div class="form-group margin-bottom">
            <label class="control-label col-sm-2">Inventory No.</label>
            <div class="col-sm-3">
               <input class="form-control input-sm" type="text" placeholder="" name="assetLabel" value="<?php

            echo (! $dto == null) ? $dto->assetLabel : "";
            ?>">
            </div>
            <label class="control-label col-sm-2">Barcode</label>
            <div class="col-sm-3">
               <input class="form-control input-sm" type="text" placeholder="" name="barcode" value="<?php

            echo (! $dto == null) ? $dto->barcode : "";
            ?>">
            </div>
         </div>
         <hr style="margin: 5pt 1pt 5pt 1pt">

         <div class="form-group margin-bottom required">
            <label class="control-label col-sm-2"><?php

            echo $this->translate("Standard Unit");
            ?></label>
            <div class="col-sm-3">
               <select name="standardUom" id="standardUom_id" class="form-control input-sm chosen-select">
                  <option value=""><?php

                echo $this->translate("Select Standard unit");
                ?></option>
   	              <?php
                echo $uom_option;
                ?>
   				</select>
            </div>
         </div>
         <div class="form-group margin-bottom required">
            <label class="control-label col-sm-2"><?php

            echo $this->translate("Inventory Unit");
            ?>:</label>
            <div class="col-sm-3">
               <select name="stockUom" id="stockUom_id" class="form-control input-sm chosen-select">
                  <option value=""><?php

                echo $this->translate("Select inventory unit");
                ?></option>
   	    		<?php
        echo $stock_uom_option;
        ?>
   					</select>
            </div>
            <label class="control-label col-sm-2"><?php

            echo $this->translate("Conversion Factor");
            ?></label>
            <div class="col-sm-1">
               <input class="form-control input-sm" type="text" placeholder="" name="stockUomConvertFactor" id="stock_uom_convert_factor_id" value="<?php

            echo (! $dto == null) ? $dto->stockUomConvertFactor : "";
            ?>">
            </div>
            <div class="col-sm-3">
               <span style="color: graytext;" id="stock_uom_convert_text"></span>
            </div>
         </div>
         <div class="form-group margin-bottom required">
            <label class="control-label col-sm-2"><?php

            echo $this->translate("Purchase Unit");
            ?>:</label>
            <div class="col-sm-3">
               <select name="purchaseUom" id="purchaseUom_id" class="form-control input-sm chosen-select">
                  <option value=""><?php

                echo $this->translate("Select purchase unit");
                ?></option>
                <?php
                echo $purchase_uom_option;
                ?>

   					</select>
            </div>
            <label class="control-label col-sm-2"><?php

            echo $this->translate("Conversion Factor");
            ?></label>
            <div class="col-sm-1">
               <input class="form-control input-sm" type="text" placeholder="" name="purchaseUomConvertFactor" id="purchase_uom_convert_factor_id" value="<?php

            echo (! $dto == null) ? $dto->purchaseUomConvertFactor : "";
            ?>">
            </div>
            <div class="col-sm-3">
               <span style="color: graytext;" id="purchase_uom_convert_text"></span>
            </div>
         </div>
         <div class="form-group margin-bottom required">
            <label class="control-label col-sm-2"><?php

            echo $this->translate("Sales Unit");
            ?>:</label>
            <div class="col-sm-3">
               <select name="salesUom" id="salesUom_id" class="form-control input-sm chosen-select">
                  <option value="">
                   <?php
                echo $sales_uom_option;
                ?>


               </select>
            </div>
            <label class="control-label col-sm-2"><?php

            echo $this->translate("Conversion Factor");
            ?></label>
            <div class="col-sm-1">
               <input class="form-control input-sm" type="text" placeholder="" name="salesUomConvertFactor" id="sales_uom_convert_factor_id" value="<?php

            echo (! $dto == null) ? $dto->salesUomConvertFactor : "";
            ?>">
            </div>
            <div class="col-sm-3">
               <span style="color: graytext;" id="sales_uom_convert_text"></span>
            </div>
         </div>
         <hr style="margin: 5pt 1pt 5pt 1pt;">


          <div class="form-group margin-bottom required">
            <label class="control-label col-sm-2">

            <?php

            echo $this->translate("Uom Group");
            ?>:</label>
            <div class="col-sm-3">
               <select name="uomGroup" class="form-control input-sm chosen-select">
                  <option value=""><?php

                echo $this->translate("Select Uom Group");
                ?></option>
                              <?php
                            echo $uom_group_option?>

                  </select>
            </div>
         </div>


         <div class="form-group margin-bottom required">
            <label class="control-label col-sm-2">

            <?php

            echo $this->translate("Item Group");
            ?>:</label>
            <div class="col-sm-3">
               <select name="itemGroup" class="form-control input-sm chosen-select">
                  <option value=""><?php

                echo $this->translate("Select Group");
                ?></option>
   	    							<?php
            echo $item_group_option?>

   					</select>
            </div>
         </div>
         <div class="form-group margin-bottom required">
            <label class="control-label col-sm-2">Monitored by:</label>
            <div class="col-sm-3">
               <select class="form-control input-sm chosen-select" name="monitoredBy">
                  <option value="">NONE</option>
                  <?php
                echo $item_monitor_option;
                ?>
               </select>
            </div>
         </div>
         <div class="form-group margin-bottom">
            <label class="control-label col-sm-2">Location</label>
            <div class="col-sm-3">
               <input class="form-control input-sm" type="text" placeholder="" name="location" value="<?php

            echo (! $dto == null) ? $dto->location : "";
            ?>">
            </div>
         </div>
         <hr style="margin: 5pt 1pt 5pt 1pt">
         <div class="form-group margin-bottom">
            <label class="control-label col-sm-2">Manufacturer</label>
            <div class="col-sm-3">
               <input class="form-control input-sm" type="text" placeholder="" name="manufacturer" value="<?php

            echo (! $dto == null) ? $dto->manufacturer : "";
            ?>">
            </div>
            <label class="control-label col-sm-2">Manufacturer Model</label>
            <div class="col-sm-3">
               <input class="form-control input-sm" type="text" placeholder="" name="manufacturerModel" value="<?php

            echo (! $dto == null) ? $dto->manufacturerModel : "";
            ?>">
            </div>
         </div>
         <div class="form-group margin-bottom">
            <label class="control-label col-sm-2">Manufacturer's Item Code</label>
            <div class="col-sm-3">
               <input class="form-control input-sm" type="text" placeholder="" name="manufacturerCode" value="<?php

            echo (! $dto == null) ? $dto->manufacturerCode : "";
            ?>">
            </div>
            <label class="control-label col-sm-2">Manufacturer Serial</label>
            <div class="col-sm-3">
               <input class="form-control input-sm" type="text" placeholder="" name="manufacturerSerial" value="<?php

            echo (! $dto == null) ? $dto->manufacturerSerial : "";
            ?>">
            </div>
         </div>
         <div class="form-group margin-bottom">
            <label class="control-label col-sm-2">Lead time</label>
            <div class="col-sm-3">
               <input class="form-control input-sm" type="text" placeholder="" name="leadTime" value="<?php

            echo (! $dto == null) ? $dto->leadTime : "";
            ?>">
               <input name="localAvailabiliy" <?php

            if (! $dto == null) :
                echo ($dto->localAvailabiliy == "1") ? "checked" : "";
            else :
                echo "checked";
            endif;
            ?> type="checkbox" value="1">
               &nbsp;Local Availability
            </div>
            <label class="control-label col-sm-2">Remarks</label>
            <div class="col-sm-3">
               <textarea class="form-control input-sm" type="text" rows="5" placeholder="" name="remarks" style="font-size: 9pt;"><?php

            echo (! $dto == null) ? $dto->remarks : "";
            ?></textarea>
            </div>
         </div>
         <hr style="margin: 5pt 1pt 5pt 1pt">

         <?php
        echo $submitItemFormInput;

        ?>
      </form>
   </div>
</div>
<script type="text/javascript">


$("#<?php
echo $tab_id;
?>").tabs(
   {active: <?php
echo $tab_active;
?>},
   { beforeLoad:function(e,ui){
      $( ui.panel ).html('<p>Loading...</p>');
   },
});


<?php
if ($action == Constants::FORM_ACTION_SHOW) :
    ?>
$("#create_item_form :input").attr("disabled", "disabled");
$("#logistic_data_frm :input").attr("disabled", "disabled");
<?php endif;

?>

	$('#purchase_uom_convert_text').text($( "#purchase_uom_id option:selected" ).text() + " = " +  $('#purchase_uom_convert_factor_id').val() + " " + $( "#standardUom_id option:selected" ).text());
	$('#sales_uom_convert_text').text($( "#salesUom_id option:selected" ).text() + " = " +  $('#sales_uom_convert_factor_id').val() + " " + $( "#standardUom_id option:selected" ).text());
   	$('#stock_uom_convert_text').text($( "#stockUuom_id option:selected" ).text() + " = " +  $('#stock_uom_convert_factor_id').val() + " " + $( "#standardUom_id option:selected" ).text());


	$('#standardUom_id').change(function() {
	   	$('#purchase_uom_convert_text').text($( "#purchase_uom_id option:selected" ).text() + " = " +  $('#purchase_uom_convert_factor_id').val() + " " + $( "#standardUom_id option:selected" ).text());
	   	$('#sales_uom_convert_text').text($( "#salesUom_id option:selected" ).text() + " = " +  $('#sales_uom_convert_factor_id').val() + " " + $( "#standardUom_id option:selected" ).text());
	});

    $('#purchase_uom_convert_factor_id').bind('change', function() {
    	$('#purchase_uom_convert_text').text($( "#purchaseUom_id option:selected" ).text() + " = " +  $('#purchase_uom_convert_factor_id').val() + " " + $( "#standardUom_id option:selected" ).text());

    });

    $('#purchaseUom_id').change(function() {
    	$('#purchase_uom_convert_text').text($( "#purchaseUom_id option:selected" ).text() + " = " +  $('#purchase_uom_convert_factor_id').val() + " " + $( "#standardUom_id option:selected" ).text());
   	});

    $('#salesUom_id').change(function() {
     	$('#sales_uom_convert_text').text($( "#salesUom_id option:selected" ).text() + " = " +  $('#sales_uom_convert_factor_id').val() + " " + $( "#standardUom_id option:selected" ).text());
    });

    $('#sales_uom_convert_factor_id').bind('change', function() {
    	$('#sales_uom_convert_text').text($( "#salesUom_id option:selected" ).text() + " = " +  $('#sales_uom_convert_factor_id').val() + " " + $( "#standardUom_id option:selected" ).text());

    });

    $('#stockUom_id').change(function() {
       	$('#stock_uom_convert_text').text($( "#stockUom_id option:selected" ).text() + " = " +  $('#stock_uom_convert_factor_id').val() + " " + $( "#standardUom_id option:selected" ).text());
    });

    $('#stock_uom_convert_factor_id').bind('change', function() {
    	$('#stock_uom_convert_text').text($( "#stockUom_id option:selected" ).text() + " = " +  $('#stock_uom_convert_factor_id').val() + " " + $( "#standardUom_id option:selected" ).text());

    });

</script>
