<?php /**@var \Application\Entity\NmtInventoryItem $entity ;*/?>




<div id="tabs" style="font-size: 9pt">
	<ul>
		<li><a href="#general">New Item</a></li>
	</ul>

	<div id="general">
	
		<?php
if (count($errors) > 0) {
    echo '<div class="alert alert-danger alert-dismissible" role="alert" style="font-size: 9.5pt"> <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>[ERROR]';

    echo '<ul>';
    foreach ($errors as $error) :
        echo '<li>' . $error . '</li>';
    endforeach
    ;
    echo '</ul>';
    echo '</div>';
}
?>

		<form id="create_item_form" class="form-horizontal"
			action="<?php echo $this->baseUrl ?>/inventory/item/edit"
			method="post" enctype="multipart/form-data">
			<input type="hidden" name="redirectUrl"
				value="<?php echo $redirectUrl ?>" />
				
				<input type="hidden" name="redirectUrl" value="<?php echo $redirectUrl ?>" />
<input type="hidden" name="entity_id" value="<?php echo (!$entity== null)? $entity->getId():"";?>" />
<input type="hidden" name="token" value="<?php echo (!$entity== null)? $entity->getToken():"";?>" />
				<input type="hidden" name="n" value="<?php echo $n;?>" />
				
				<div class="form-group margin-bottom">
		<label class="control-label col-sm-2" ><?php echo $this->translate('Item#'); ?>:</label>
		<div class="col-sm-3">
		<input disabled class="form-control input-sm" type="text" value="<?php if(!$entity == null): echo $entity->getSysNumber(); endif;?>"/></div>
		<div class="col-sm-4">
		<?php echo (!$entity == null)? '<span style="color:gray;font-size: 9pt">Revision #'. $entity->getRevisionNo().';</span>':'';?>
		<?php if (!$entity == null): if($entity->getLastChangeOn()!==null): echo '<span style="color:gray;font-size: 9pt"> Last Revision: '. $entity->getLastChangeOn()->format('d-m-Y h:i:s').'</span>'; endif; endif;?>
		
	  </div>
			
	</div>

			<div class="form-group margin-bottom required">
				<label class="control-label col-sm-2">Item ID</label>
				<div class="col-sm-3">
					<input class="form-control input-sm" type="text" placeholder=""
						name="itemSku"
						value="<?php echo (!$entity == null)? $entity->getItemSku():"xx";?>">
					<input class="form-control input-sm" type="text"
						placeholder="optional sku" name="itemSku1"
						value="<?php echo (!$entity == null)? $entity->getItemSku1():"";?>">

				</div>
				<div class="col-sm-4">
					<input
						<?php if(!$entity == null): echo ($entity->getIsActive()=="1")?"checked":""; else: echo "checked"; endif;?>
						type="checkbox" name="isActive" value="1">&nbsp;Active&nbsp;&nbsp;
					<input
						<?php if(!$entity == null): echo ($entity->getIsStocked()=="1")?"checked":""; else: echo "checked"; endif;?>
						type="checkbox" name="isStocked" value="1">&nbsp;Stocked
					&nbsp;&nbsp; <input
						<?php if(!$entity == null): echo ($entity->getIsPurchased()=="1")?"checked":""; else: echo "checked"; endif;?>
						type="checkbox" name="isPurchased" value="1">&nbsp;Purchased
					&nbsp;&nbsp;<br> <input
						<?php if(!$entity == null): echo ($entity->getIsSaleItem()=="1")?"checked":""; else: echo ""; endif;?>
						type="checkbox" name="isSaleItem" value="1">&nbsp;For Sale
					&nbsp;&nbsp; <input
						<?php if(!$entity == null): echo ($entity->getIsFixedAsset()=="1")?"checked":""; else: echo ""; endif;?>
						type="checkbox" name="isFixedAsset" value="1">&nbsp;Fixed Asset <input
						<?php if(!$entity == null): echo ($entity->getIsSparepart()=="1")?"checked":""; else: echo ""; endif;?>
						type="checkbox" name="isSparePart" value="1">&nbsp;Spare Part

				</div>

				<div class="col-sm-3">
					<img alt="" height=""
						src="/inventory/item/barcode?barcode=22011979">
				</div>
			</div>
			<hr style="margin: 5pt 1pt 5pt 1pt;">

			<div class="form-group margin-bottom required">
				<label class="control-label col-sm-2">Item Name</label>
				<div class="col-sm-3">
					<input class="form-control input-sm" type="text" placeholder=""
						name="itemName"
						value="<?php echo (!$entity == null)? $entity->getItemName():"";?>">
				</div>

				<label class="control-label col-sm-2">Item Foreign Name</label>
				<div class="col-sm-3">
					<input class="form-control input-sm" type="text" placeholder=""
						name="itemNameForeign"
						value="<?php echo (!$entity == null)? $entity->getItemNameForeign():"";?>">
				</div>
			</div>
			<div class="form-group margin-bottom">
				<label class="control-label col-sm-2">Item Description</label>
				<div class="col-sm-8">
					<input class="form-control input-sm" type="text" placeholder=""
						name="itemDescription"
						value="<?php echo (!$entity == null)? $entity->getItemDescription():"";?>">
				</div>
			</div>

			<div class="form-group margin-bottom">
				<label class="control-label col-sm-2">Keyworks</label>
				<div class="col-sm-3">
					<input class="form-control input-sm" type="text" placeholder=""
						name="keywords"
						value="<?php echo (!$entity == null)? $entity->getKeywords():"";?>">
				</div>
			</div>


			<div class="form-group margin-bottom">

				<label class="control-label col-sm-2">Inventory No.</label>
				<div class="col-sm-3">
					<input class="form-control input-sm" type="text" placeholder=""
						name="assetLabel"
						value="<?php echo (!$entity == null)? $entity->getAssetLabel():"";?>">
				</div>

				<label class="control-label col-sm-2">Barcode</label>
				<div class="col-sm-3">
					<input class="form-control input-sm" type="text" placeholder=""
						name="barcode"
						value="<?php echo (!$entity == null)? $entity->getBarcode():"";?>">

				</div>

			</div>
			<hr style="margin: 5pt 1pt 5pt 1pt">
			<div class="form-group margin-bottom required">
				<label class="control-label col-sm-2"><?php echo $this->translate("Standard Unit");?></label>
				<div class="col-sm-3">

					<select name="uom_id" id="uom_id" class="form-control input-sm">
						<option value=""><?php echo $this->translate("Select standard unit");?></option>
   	    	<?php
        if ($uom_list !== null) :
            foreach ($uom_list as $uom) :

                /**@var \Application\Entity\NmtApplicationUom $uom ; */
                $selected = '';
                if ($entity !== null) :
                    if ($entity->getStandardUom() !== null) :
                        if ($entity->getStandardUom()->getId() == $uom->getId()) :
                            $selected = 'selected';
                            endif;
                         endif;
                    endif;



                echo sprintf('<option %s value="%s">%s </option>', $selected, ucwords($uom->getId()), ucwords($uom->getUomCode()));
            endforeach
            ;
   	    	endif;

        ?>
   					</select>

				</div>
			</div>

<div class="form-group margin-bottom required">
				<label class="control-label col-sm-2"><?php echo $this->translate("Inventory Unit");?>:</label>
				<div class="col-sm-3">

					<select name="stock_uom_id" id="stock_uom_id"
						class="form-control input-sm">
						<option value=""><?php echo $this->translate("Select inventory unit");?></option>
   	    							<?php
            if ($uom_list !== null) :
                foreach ($uom_list as $uom) :

                    /**@var \Application\Entity\NmtApplicationUom $uom ; */
                    $selected = '';
                    if ($entity !== null) :
                        if ($entity->getStockUom() !== null) :
                        if ($entity->getStockUom()->getId() == $uom->getId()) :
                                $selected = 'selected';
   	    							endif;
   	    							endif;
   	    							endif;



                    echo sprintf('<option %s value="%s">%s </option>', $selected, ucwords($uom->getId()), ucwords($uom->getUomCode()));
                endforeach
                ;
   	    							endif;

            ?>
   					</select>
   					</div>
   					
   						<label class="control-label col-sm-2"><?php echo $this->translate("Conversion Factor");?></label>
				<div class="col-sm-1">
					<input class="form-control input-sm" type="text" placeholder=""
						name="stockUomConvertFactor"
						id="stock_uom_convert_factor_id"
						value="<?php echo (!$entity == null)? $entity->getStockUomConvertFactor():"";?>">
				</div>
				
				<div class="col-sm-3">
					<span style="color: graytext;" id="stock_uom_convert_text"></span>
				</div>

				</div>

			<div class="form-group margin-bottom required">
				<label class="control-label col-sm-2"><?php echo $this->translate("Purchase Unit");?>:</label>
				<div class="col-sm-3">

					<select name="purchase_uom_id" id="purchase_uom_id"
						class="form-control input-sm">
						<option value=""><?php echo $this->translate("Select purchase unit");?></option>
   	    							<?php
            if ($uom_list !== null) :
                foreach ($uom_list as $uom) :

                    /**@var \Application\Entity\NmtApplicationUom $uom ; */
                    $selected = '';
                    if ($entity !== null) :
                        if ($entity->getPurchaseUom() !== null) :
                            if ($entity->getPurchaseUom()->getId() == $uom->getId()) :
                                $selected = 'selected';
   	    							endif;
   	    							endif;
   	    							endif;



                    echo sprintf('<option %s value="%s">%s </option>', $selected, ucwords($uom->getId()), ucwords($uom->getUomCode()));
                endforeach
                ;
   	    							endif;

            ?>
   					</select>

				</div>


				<label class="control-label col-sm-2"><?php echo $this->translate("Conversion Factor");?></label>
				<div class="col-sm-1">
					<input class="form-control input-sm" type="text" placeholder=""
						name="purchaseUomConvertFactor"
						id="purchase_uom_convert_factor_id"
						value="<?php echo (!$entity == null)? $entity->getPurchaseUomConvertFactor():"";?>">
				</div>

				<div class="col-sm-3">
					<span style="color: graytext;" id="purchase_uom_convert_text"></span>
				</div>
			</div>

			<div class="form-group margin-bottom required">
				<label class="control-label col-sm-2"><?php echo $this->translate("Sales Unit");?>:</label>
				<div class="col-sm-3">

					<select name="sales_uom_id" id="sales_uom_id"
						class="form-control input-sm">
						<option value=""><?php echo $this->translate("Select Sales Unit");?></option>
   	    							<?php
            if ($uom_list !== null) :
                foreach ($uom_list as $uom) :

                    /**@var \Application\Entity\NmtApplicationUom $uom ; */
                    $selected = '';
                    if ($entity !== null) :
                        if ($entity->getSalesUom() !== null) :
                            if ($entity->getSalesUom()->getId() == $uom->getId()) :
                                $selected = 'selected';
   	    							endif;
   	    							endif;
   	    							endif;



                    echo sprintf('<option %s value="%s">%s </option>', $selected, ucwords($uom->getId()), ucwords($uom->getUomCode()));
                endforeach
                ;
   	    							endif;

            ?>
   					</select>

				</div>


				<label class="control-label col-sm-2"><?php echo $this->translate("Conversion Factor");?></label>
				<div class="col-sm-1">
					<input class="form-control input-sm" type="text" placeholder=""
						name="salesUomConvertFactor" id="sales_uom_convert_factor_id"
						value="<?php echo (!$entity == null)? $entity->getSalesUomConvertFactor():"";?>">


				</div>
				<div class="col-sm-3">
					<span style="color: graytext;" id="sales_uom_convert_text"></span>
				</div>
			</div>

			<hr style="margin: 5pt 1pt 5pt 1pt;">
			<div class="form-group margin-bottom required">
				<label class="control-label col-sm-2">Item Type</label>
				<div class="col-sm-3">
					<select class="form-control input-sm" name="itemType">
						<option
							<?php if(!$entity == null): echo ($entity->getItemType()=="ITEM")?"selected":""; endif;?>
							value="ITEM">Item</option>
						<option
							<?php if(!$entity == null): echo ($entity->getItemType()=="SERVICE")?"selected":""; endif;?>
							value="SERVICE">Service</option>
						<option
							<?php if(!$entity == null): echo ($entity->getItemType()=="SOFTWARE")?"selected":""; endif;?>
							value="SOFTWARE">Software</option>
					</select>
				</div>

				<label class="control-label col-sm-2"><?php echo $this->translate("Item Group");?>:</label>
				<div class="col-sm-3">
					<select name="item_group_id" class="form-control input-sm">
						<option value=""><?php echo $this->translate("Select Group");?></option>
   	    							<?php
            if ($item_group_list !== null) :
                foreach ($item_group_list as $gl) :

                    /**@var \Application\Entity\NmtInventoryItemGroup $gl ; */

                    if ($entity !== null) :
                        if ($entity->getItemGroup() !== null) :
                            if ($entity->getItemGroup()->getId() == $gl->getId()) :
                                echo '<option selected value="' . $gl->getId() . '">' . $gl->getGroupName() . '</option>';
                            else :
                                echo '<option value="' . $gl->getId() . '">' . $gl->getGroupName() . '</option>';
                            endif;
                        else :
                            echo '<option value="' . $gl->getId() . '">' . $gl->getGroupName() . '</option>';
                        endif;
                    else :
                        echo '<option value="' . $gl->getId() . '">' . $gl->getGroupName() . '</option>';
                    endif;
                endforeach
                ;
   	    							endif;

            ?>
   					</select>
				</div>
			</div>

			<div class="form-group margin-bottom required">
				<label class="control-label col-sm-2">Monitored by:</label>
				<div class="col-sm-3">
					<select class="form-control input-sm" name="monitoredBy">
						<option value="">NONE</option>
						<option
							<?php if(!$entity == null): echo ($entity->getMonitoredBy()=="SN")?"selected":""; endif;?>
							value="SN">Serial Number</option>
						<option
							<?php if(!$entity == null): echo ($entity->getMonitoredBy()=="B")?"selected":""; endif;?>
							value="B">Batch Number</option>
					</select>
				</div>
			</div>

			<div class="form-group margin-bottom">
				<label class="control-label col-sm-2">Item Category</label>
				<div class="col-sm-3">

					<input disabled class="form-control input-sm" type="text"
						id="item_category_name" placeholder="Please select item category"
						name="country_code_2"
						value="<?php if($category !== null):echo $category->getNodeName();endif;?>">
					<input type="hidden" class="form-control input-sm"
						id="item_category_name_selected" name="item_category_id"
						value="<?php if($category!== null):echo $category->getNodeId();endif;?>">
				</div>

				<a style="color: #0080ff;" href="javascript:;"
					onclick="showBootstrapDialog('Select Item Category','/application/item-category/list1','b_loaded_data');">Select&nbsp;&nbsp;<i
					class="glyphicon glyphicon-folder-open"></i>
				</a>
			</div>

			<div class="form-group margin-bottom">
				<label class="control-label col-sm-2">Department</label>
				<div class="col-sm-3">

					<input disabled class="form-control input-sm" type="text"
						id="department_name" placeholder="Please select!"
						name="deparment_name"
						value="<?php if($department !== null):echo $department->getNodeName();endif;?>">
					<input type="hidden" class="form-control input-sm" type="text"
						id="department_name_selected"
						placeholder="Please select standard unit" name="department_id"
						value="<?php if($department!== null):echo $department->getNodeId();endif;?>">

				</div>

				<a style="color: #0080ff;" href="javascript:;"
					onclick="showBootstrapDialog('Select Deparment','/application/department/list1','b_loaded_data');">Select&nbsp;&nbsp;<i
					class="glyphicon glyphicon-folder-open"></i>
				</a>

			</div>

			<div class="form-group margin-bottom">
				<label class="control-label col-sm-2">Location</label>
				<div class="col-sm-3">
					<input class="form-control input-sm" type="text" placeholder=""
						name="location"
						value="<?php echo (!$entity == null)? $entity->getLocation():"";?>">
				</div>
			</div>
			<hr style="margin: 5pt 1pt 5pt 1pt">

			<div class="form-group margin-bottom">
				<label class="control-label col-sm-2">Manufacturer</label>
				<div class="col-sm-3">
					<input class="form-control input-sm" type="text" placeholder=""
						name="manufacturer"
						value="<?php echo (!$entity == null)? $entity->getManufacturer():"";?>">
				</div>
				<label class="control-label col-sm-2">Manufacturer Model</label>
				<div class="col-sm-3">
					<input class="form-control input-sm" type="text" placeholder=""
						name="manufacturerModel"
						value="<?php echo (!$entity == null)? $entity->getManufacturerModel():"";?>">
				</div>
			</div>

			<div class="form-group margin-bottom">
				<label class="control-label col-sm-2">Manufacturer's Item Code</label>
				<div class="col-sm-3">
					<input class="form-control input-sm" type="text" placeholder=""
						name="manufacturerCode"
						value="<?php echo (!$entity == null)? $entity->getManufacturerCode():"";?>">
				</div>


				<label class="control-label col-sm-2">Manufacturer Serial</label>
				<div class="col-sm-3">
					<input class="form-control input-sm" type="text" placeholder=""
						name="manufacturerSerial"
						value="<?php echo (!$entity == null)? $entity->getManufacturerSerial():"";?>">
				</div>
			</div>

			<div class="form-group margin-bottom">
				<label class="control-label col-sm-2">Lead time</label>
				<div class="col-sm-3">
					<input class="form-control input-sm" type="text" placeholder=""
						name="leadTime"
						value="<?php echo (!$entity == null)? $entity->getLeadTime():"";?>">

					<input name="localAvailabiliy"
						<?php if(!$entity == null): echo ($entity->getLocalAvailabiliy()=="1")?"checked":""; else: echo ""; endif;?>
						type="checkbox" value="1">&nbsp;Local Availability

				</div>

				<label class="control-label col-sm-2">Remarks</label>
				<div class="col-sm-3">
					<textarea class="form-control input-sm" type="text" rows="5"
						placeholder="" name="remarksText" style="font-size: 9pt;"><?php echo (!$entity == null)? $entity->getRemarksText():"";?></textarea>
				</div>
			</div>
			<hr style="margin: 5pt 1pt 5pt 1pt">

			<div class="form-group margin-bottom">
				<div class="col-sm-offset-2 col-sm-10">
					<button onclick="submitForm('create_item_form');"
						class="btn btn-default">
						<i class="glyphicon glyphicon-floppy-disk"> </i>&nbsp;Save
					</button>
				</div>
			</div>

		</form>
	</div>
</div>


<script type="text/javascript">

$('#purchase_uom_convert_text').text($( "#purchase_uom_id option:selected" ).text() + " = " +  $('#purchase_uom_convert_factor_id').val() + " " + $( "#uom_id option:selected" ).text());
$('#sales_uom_convert_text').text($( "#sales_uom_id option:selected" ).text() + " = " +  $('#sales_uom_convert_factor_id').val() + " " + $( "#uom_id option:selected" ).text());
	$('#stock_uom_convert_text').text($( "#stock_uom_id option:selected" ).text() + " = " +  $('#stock_uom_convert_factor_id').val() + " " + $( "#uom_id option:selected" ).text());


$('#uom_id').change(function() {
   	$('#purchase_uom_convert_text').text($( "#purchase_uom_id option:selected" ).text() + " = " +  $('#purchase_uom_convert_factor_id').val() + " " + $( "#uom_id option:selected" ).text());
   	$('#sales_uom_convert_text').text($( "#sales_uom_id option:selected" ).text() + " = " +  $('#sales_uom_convert_factor_id').val() + " " + $( "#uom_id option:selected" ).text());
});

$('#purchase_uom_convert_factor_id').bind('change', function() {
	$('#purchase_uom_convert_text').text($( "#purchase_uom_id option:selected" ).text() + " = " +  $('#purchase_uom_convert_factor_id').val() + " " + $( "#uom_id option:selected" ).text());

});

$('#purchase_uom_id').change(function() {
	$('#purchase_uom_convert_text').text($( "#purchase_uom_id option:selected" ).text() + " = " +  $('#purchase_uom_convert_factor_id').val() + " " + $( "#uom_id option:selected" ).text());
	});

$('#sales_uom_id').change(function() {
 	$('#sales_uom_convert_text').text($( "#sales_uom_id option:selected" ).text() + " = " +  $('#sales_uom_convert_factor_id').val() + " " + $( "#uom_id option:selected" ).text());
});

$('#sales_uom_convert_factor_id').bind('change', function() {
	$('#sales_uom_convert_text').text($( "#sales_uom_id option:selected" ).text() + " = " +  $('#sales_uom_convert_factor_id').val() + " " + $( "#uom_id option:selected" ).text());

});

$('#stock_uom_id').change(function() {
   	$('#stock_uom_convert_text').text($( "#stock_uom_id option:selected" ).text() + " = " +  $('#stock_uom_convert_factor_id').val() + " " + $( "#uom_id option:selected" ).text());
});

$('#stock_uom_convert_factor_id').bind('change', function() {
	$('#stock_uom_convert_text').text($( "#stock_uom_id option:selected" ).text() + " = " +  $('#stock_uom_convert_factor_id').val() + " " + $( "#uom_id option:selected" ).text());

});

</script>


