<?php
use Inventory\Domain\Item\ItemType;

$nid = \Application\Model\Constants::INVENTORY_HASH_ID;

/**
 *
 * @var \Application\Controller\Plugin\NmtPlugin $nmtPlugin ;
 */
?>


<div id="tabs" style="font-size: 9.5pt">

	<ul>
		<li><a href="#general">Items</a></li>
	</ul>
	<div id="general">
		<div class="panel-group">
			<div class="panel panel-default">
				<div class="panel-heading">
					<h4 class="panel-title">
						<a data-toggle="collapse" href="#collapse1"> <small><span
								class="glyphicon glyphicon-filter"></span></small> Filter
						</a>
					</h4>
				</div>
				<div id="collapse1" class="panel-collapse collapse">
					<div class="panel-body" style="padding: 0px;">
						<div
							style="padding: 3px; font-size: 9.5pt; background: url(/images/bg1.png); background-repeat: repeat-x; background-color: #FFFFFF;">

							<form class="form-horizontal"
								action="<?php echo $this->baseUrl ?>/inventory/item/list2"
								method="get" enctype="multipart/form-data">

								<div class="form-group margin-bottom">
									<label class="control-label col-sm-2" for="inputTag">Item Type</label>
									<div class="col-sm-3">
										<select class="form-control input-sm" name="item_type">
											<option value="All">All</option>
											<option
												<?php echo $item_type=='ITEM'? "selected='selected'":"";?>
												value="ITEM">Item</option>
											<option
												<?php echo $item_type=='SERVICE'? "selected='selected'":"";?>
												value="SERVICE">Service</option>
											<option
												<?php echo $item_type=='SOFTWARE'? "selected='selected'":"";?>
												value="SOFTWARE">Software</option>
										</select>
									</div>
									<div class="col-sm-4"></div>
								</div>

								<div class="form-group margin-bottom">
									<label class="control-label col-sm-2" for="inputTag">Active
										Items</label>
									<div class="col-sm-3">
										<select class="form-control input-sm" name="is_active">
											<option
												<?php echo $is_active ==''? "selected='selected'":"";?>
												value="2">All</option>
											<option
												<?php echo $is_active=='1'? "selected='selected'":"";?>
												value="1">Active</option>
											<option
												<?php echo $is_active=='-1'? "selected='selected'":"";?>
												value="-1">Inactive</option>
										</select>
									</div>
								</div>

								<div class="form-group margin-bottom">
									<label class="control-label col-sm-2" for="inputTag">Fixed
										Asset</label>
									<div class="col-sm-3">
										<select class="form-control input-sm" name="is_fixed_asset">
											<option
												<?php echo $is_fixed_asset==''? "selected='selected'":"";?>
												value="">All</option>
											<option
												<?php echo $is_fixed_asset=='1'? "selected='selected'":"";?>
												value="1">Fixed Asset</option>
											<option
												<?php echo $is_fixed_asset=='-1'? "selected='selected'":"";?>
												value="-1">None Fixed Asset</option>
										</select>
									</div>
								</div>

								<div class="form-group margin-bottom">
									<label class="control-label col-sm-2" for="inputTag">Sort by</label>
									<div class="col-sm-3">
										<select class="form-control input-sm" name="sort_by">
											<option value="">None</option>
											<option
												<?php echo $sort_by=='itemName'? "selected='selected'":"";?>
												value="itemName">Item Name</option>

											<option
												<?php echo $sort_by=='createdOn'? "selected='selected'":"";?>
												value="createdOn">Created Date</option>
										</select> <input
											<?php if(!$sort==null): echo ($sort=='ASC')? "checked":""; else: echo "checked"; endif;?>
											type="radio" name="sort" value="ASC">&nbsp;ASC&nbsp;&nbsp; <input
											<?php if(!$sort==null): echo ($sort=='DESC')? "checked":""; else: echo ""; endif;?>
											type="radio" name="sort" value="DESC">&nbsp;DESC&nbsp;&nbsp;

									</div>
								</div>

								<div class="form-group margin-bottom">
									<label class="control-label col-sm-2" for="inputTag">Layout</label>
									<div class="col-sm-3">
										<select class="form-control input-sm" name="layout">
											<option value="">None</option>
											<option
												<?php echo $layout=='list'? "selected='selected'":"";?>
												value="list">List</option>

											<option
												<?php echo $layout=='grid'? "selected='selected'":"";?>
												value="grid">grid</option>
										</select>

									</div>
								</div>


								<div class="form-group margin-bottom">
									<label class="control-label col-sm-2" for="inputTag">Result per
										page</label>
									<div class="col-sm-3">
										<select class="form-control input-sm" name="perPage">
											<option value="">None</option>
											<option
												<?php echo $per_pape=='20'? "selected='selected'":"";?>
												value="20">20</option>

											<option
												<?php echo $per_pape=='25'? "selected='selected'":"";?>
												value="25">25</option>

											<option
												<?php echo $per_pape=='30'? "selected='selected'":"";?>
												value="30">30</option>

											<option
												<?php echo $per_pape=='50'? "selected='selected'":"";?>
												value="50">50</option>
											<option
												<?php echo $per_pape=='100'? "selected='selected'":"";?>
												value="100">100</option>
											<option
												<?php echo $per_pape=='200'? "selected='selected'":"";?>
												value="200">200</option>
										</select>
									</div>
								</div>

								<div class="form-group margin-bottom">
									<div class="col-sm-offset-2 col-sm-10">
										<button type="submit" class="btn btn-default">Show</button>
									</div>
								</div>

							</form>

						</div>
					</div>
				</div>
			</div>
		</div>



<?php

if ($total_records <= 0) {

    echo 'No record found!';
} else {

    if (! is_null($paginator)) {
        echo 'Record ' . $paginator->minInPage . ' to ' . $paginator->maxInPage . ' | ' . $total_records . ' records found!';
    } else {
        echo $total_records . ' records found!';
    }

    $url = sprintf($this->baseUrl . '/inventory/item/list2?layout=list&is_active=%s&item_type=%s&sort_by=%s&sort=%s&is_fixed_asset=%s&perPage=%s&page=%s', $is_active, $item_type, $sort_by, $sort, $is_fixed_asset, $per_pape, $page);

    ?>


	&nbsp;&nbsp;&nbsp;<a class="btn btn-default btn-sm"
			style="color: black; padding: 1pt 5pt 2pt 5pt;" title="List View"
			href="<?php echo $url;?>"> <i class="fa fa-list" aria-hidden="true"></i></a>

		<hr style="margin: 5pt 1pt 5pt 1pt;">
		<div class="container-fluid">

 <?php

    $lineBreak = 4;
    $count = 0;

    foreach ($list as $a) :

        $url = $nmtPlugin->getItemPic($a['id']);

        if ($count == 0 || $count % $lineBreak == 0) {
            echo '<div class="row" style="height-min:130px; border:1px;">';
        }

        ?>
		    <div class="col-xs-6 col-md-3	">


				<table style="">
					<tr style="padding: 1pt 2pt 10pt 1pt;">
						<td>


							<div style="position: relative; float: right;">
								<!-- <span class="badge badge-primary"><?php echo ($paginator===null)? $count:$paginator->minInPage -1+ $count+1;?></span> -->

								<!--  <img id="item_<?php echo $this->escapeHtml($a['id']);?>"
									style="cursor: pointer;" title="click for more detail!"
									onclick="" class="img-rounded" width="120" height="120"
									src="/inventory/item/get-picture1?&item_id=<?php echo $a['id'];?>" />-->


								<a target="_blank" style="color: black;"
									href="<?php echo $this->baseUrl ?>/inventory/item/show?token=<?php echo $a['token'] ;?>&entity_id=<?php echo $a['id'];?>&checksum=<?php echo $a['checksum'];?>">
									<img id="item_<?php echo $this->escapeHtml($a['id']);?>"
									style="cursor: pointer;" title="click for more detail!"
									onclick="" class="img-rounded" width="140" height="140"
									src="<?php echo $url; ?>" />
								</a>


	
							</div>
						</td>

						<td style="padding: 1pt 1pt 1pt 10pt;"><span
							style="padding: 1pt 1pt 1pt 2pt; font-weight: bold;"> <a
								target="_blank" style="color: black;"
								href="<?php echo $this->baseUrl ?>/inventory/item/show?token=<?php echo $a['token'] ;?>&entity_id=<?php echo $a['id'];?>&checksum=<?php echo $a['checksum'];?>">
						<?php echo ucwords(substr($this->escapeHtml($a['item_name']),0,100));?></a>	
							<?php if($a['item_type']=="SERVICE"):?>			
							<span style="font-size: 8pt;" class="badge">S</span>
							<?php endif; ?>
							
								<?php if($a['is_fixed_asset']=="1"):?>			
							<span style="font-size: 6pt;" class="badge">A</span>
							<?php endif; ?>
							
								</span> <span
							style="padding: 1pt 1pt 1pt 1pt; color: graytext; font-size: 8pt;">
								<br><?php echo $this->escapeHtml(($a['item_sku']));?>
						
			<br><?php echo $this->escapeHtml($a['sys_number']);?>
				<br><?php echo $this->escapeHtml($a['serial_number']);?>
						<br><?php echo substr($this->escapeHtml($a['manufacturer_model']),0,30);?>
						
						<div style="margin: 2px; font-size: 9pt">

									<div class="dropdown">
										<button
											style="color: black; padding: 2pt 2pt 2pt 2pt; color: navy; font-size: 8.5pt"
											class="btn btn-default dropdown-toggle btn-sm" type="button"
											id="dropdownMenu1" data-toggle="dropdown"
											aria-haspopup="true" aria-expanded="true">
											<i class="fa fa-bars" aria-hidden="true"></i>&nbsp;Action&nbsp;<span
												class="caret"></span>
										</button>
										<ul class="dropdown-menu" aria-labelledby="dropdownMenu1">
											<li><a href="javascript:;"
												onclick="showJqueryDialog('<?php echo $a['item_name'].' - '. $a['item_sku'] ; ?>','1550',$(window).height()-50,'/inventory/item/show1?token=<?php echo $a['token'] ?>&entity_id=<?php echo $a['id'] ?>&checksum=<?php echo $a['checksum'] ?>','j_loaded_data',true);"><i
													class="fa fa-eye" aria-hidden="true"></i>&nbsp;Quick Show</a>

												<a
												href="<?php echo $this->baseUrl ?>/inventory/item/update?token=<?php echo $a['token'] ;?>&entity_id=<?php echo $a['id'];?>"><small><i
														class="glyphicon glyphicon-pencil"></i></small>&nbsp;Edit</a></li>
											<li role="separator" class="divider"></li>
											<li><a
												href="<?php echo $this->baseUrl ?>/inventory/item/clone?<?php echo $a['token'] ;?>&entity_id=<?php echo $a['id'];?>&checksum=<?php echo $a['checksum'];?>">
													<small><i class="fa fa-plus" aria-hidden="true"></i>&nbsp;</small>&nbsp;Clone
											</a></li>

											<li><a
												href="<?php echo $this->baseUrl ?>/inventory/item/upload-picture?token=<?php echo $a['token'] ;?>&target_id=<?php echo $a['id'];?>&checksum=<?php echo $a['checksum'];?>">
													<small><i class="fa fa-upload" aria-hidden="true"></i>&nbsp;</small>&nbsp;Upload
													Picture
											</a></li>
											<li><a
												href="<?php echo $this->baseUrl ?>/inventory/item-attachment/upload?token=<?php echo $a['token'] ;?>&target_id=<?php echo $a['id'];?>&checksum=<?php echo $a['checksum'];?>"><small><i
														class="glyphicon glyphicon-plus"></i></small>&nbsp;New
													Attachment</a></li>
										</ul>
									</div>
						
	
		<?php ?>
	
					<tr>
				
				</table>


			</div>

		<?php
        $count ++;

        if ($count % $lineBreak == 0) {

            echo '</div><hr style="margin: 5pt 1pt 5pt 1pt;">';
        }
        ?>
        
    	
<?php endforeach; ?>
</div>





<?php

    // ===============================
    if (! is_null($paginator)) :

        // change it only
        $base = $this->baseUrl . '/inventory/item/list2?is_active=' . $is_active . '&layout=' . $layout . '&item_type=' . $item_type . '&sort_by=' . $sort_by . '&sort=' . $sort . '&is_fixed_asset=' . $is_fixed_asset;
        $_connector_symbol = '&';

        $last = $base . $_connector_symbol . 'page=' . $paginator->totalPages . '&perPage=' . $paginator->resultsPerPage;
        $first = $base . $_connector_symbol . 'page=1&perPage=' . $paginator->resultsPerPage;

        $p1 = ($paginator->page) - 1;
        $p2 = ($paginator->page) + 1;

        $prev = $base . $_connector_symbol . 'page=' . $p1 . '&perPage=' . $paginator->resultsPerPage;
        $next = $base . $_connector_symbol . 'page=' . $p2 . '&perPage=' . $paginator->resultsPerPage;

        echo '<ul class="pagination pagination-sm">';

        if ($paginator->page != 1 and $paginator->totalPages > 10) {
            echo '<li><a href="' . $first . '"> |< </a></li>';
            echo '<li><a href="' . $prev . '"> < </a></li>';
        }

        for ($i = $paginator->minInPageSet; $i <= $paginator->maxInPageSet; $i ++) {

            $url = $base . $_connector_symbol . 'page=' . $i . '&perPage=' . $paginator->resultsPerPage;

            if ($i == $paginator->page) {
                echo '<li><a class="active" href="#">' . $i . '</a></li>';
            } else {
                echo '<li><a href="' . $url . '"> ' . $i . ' </a></li>';
            }
        }
        if ($paginator->page != $paginator->totalPages and $paginator->totalPages > 10) {
            echo '<li><a href="' . $next . '"> > </a></li>';
            echo '<li><a href="' . $last . '"> >| </a></li>';
        }
        echo '</ul>';
endif;

}
// ===============================
?>

</div>
</div>


