<?php /**@var \Application\Entity\NmtInventoryItem $entity ;*/?>

<div style="position: relative; float: right;">
	<img alt="" height=""
		src="/inventory/item/barcode?barcode=<?php echo (!$entity == null)? $entity->getAssetLabel():"";?>">
</div>

<div>
<table style="">
<tr style="padding: 1pt 2pt 2pt 10pt;">
<td style="width:10pt;"><td>
<td><div style="position: relative; float: right;">
			<img style="cursor: pointer;" title="click for more detail!"
				onclick="$('#tabs').tabs({ active: 1});" class="img-rounded"
				width="150" height="150"
				src="/inventory/item/get-picture?&item_id=<?php echo (!$entity == null)? $entity->getId():"";?>" />
		</div></td>
	<td style="padding: 1pt 2pt 2pt 10pt;">
	<h3 style="padding: 2pt 2pt 2pt 1pt;"><?php echo (!$entity == null)?$entity->getItemName():"";?></h3>
	<span style="color: gray; font-size: 9.5pt"><?php echo (!$entity == null)? "Item No.: " . $entity->getSysNumber() :"";?></span>
	
	<div style="color: gray; padding-top: 5pt; font-size: 8pt"><?php if(!$entity == null): echo ($entity->getCreatedOn() !== null)?'Created date: ' . date_format($entity->getCreatedOn(),"Y/m/d H:i:s"):""; endif;?></div>
	<div style="color: gray; padding-top: 2pt; font-size: 8pt"><?php if(!$entity == null): echo  ($entity->getLastChangeOn() !== null)?'Revision# '. $entity->getRevisionNo(). ' - Last Change: ' . date_format($entity->getLastChangeOn(),"Y/m/d H:i:s"):""; endif;?></div>
	
	<div style="margin: 2px; font-size: 9pt">

	<div class="dropdown">
		<button class="btn btn-default dropdown-toggle btn-sm" type="button"
			id="dropdownMenu1" data-toggle="dropdown" aria-haspopup="true"
			aria-expanded="true">
			<i class="fa fa-bars" aria-hidden="true"></i>&nbsp;&nbsp;Actions&nbsp;<span
				class="caret"></span>
		</button>
		<ul class="dropdown-menu" aria-labelledby="dropdownMenu1">
			<li><a
				href="<?php echo $this->baseUrl ?>/inventory/item/edit?token=<?php echo (!$entity == null)? $entity->getToken():"";?>&entity_id=<?php echo (!$entity == null)? $entity->getId():"";?>&checksum=<?php echo (!$entity == null)? $entity->getChecksum():"";?>"><small><i
						class="glyphicon glyphicon-pencil"></i></small>&nbsp;Edit</a></li>
			<li role="separator" class="divider"></li>
		<li><a
				href="<?php echo $this->baseUrl ?>/inventory/item/clone?token=<?php echo (!$entity == null)? $entity->getToken():"";?>&target_id=<?php echo (!$entity == null)? $entity->getId():"";?>&checksum=<?php echo (!$entity == null)? $entity->getChecksum():"";?>">
					<small><i class="fa fa-plus" aria-hidden="true"></i>&nbsp;</small>&nbsp;Clone</a></li>
	
			<li><a
				href="<?php echo $this->baseUrl ?>/inventory/item/upload-picture?token=<?php echo (!$entity == null)? $entity->getToken():"";?>&target_id=<?php echo (!$entity == null)? $entity->getId():"";?>&checksum=<?php echo (!$entity == null)? $entity->getChecksum():"";?>">
					<small><i class="fa fa-upload" aria-hidden="true"></i>&nbsp;</small>&nbsp;Upload
					Picture
			</a></li>
			<li><a
				href="<?php echo $this->baseUrl ?>/inventory/item-attachment/upload?token=<?php echo (!$entity == null)? $entity->getToken():"";?>&target_id=<?php echo (!$entity == null)? $entity->getId():"";?>&checksum=<?php echo (!$entity == null)? $entity->getChecksum():"";?>"><small><i
						class="glyphicon glyphicon-plus"></i></small>&nbsp;New Attachment</a></li>
		</ul>
	</div>

</div>
	

</td>
<tr>

</table>
</div>


<div id="tabs1" style="font-size: 9pt">
	<ul>
		<li><a href="#general">Item</a></li>
		
		  <li><a title="<?php echo $this->translate("Price Comparison");?>"
		href="<?php echo $this->baseUrl ?>/procure/price-comparison/price-of-item?token=<?php echo (!$entity == null)? $entity->getToken():"";?>&item_id=<?php echo (!$entity == null)? $entity->getId():"";?>">
			<i class="fa fa-bar-chart" aria-hidden="true"></i></a></li>

		
		
		<li><a title="<?php echo $this->translate("Picture");?>"
			href="<?php echo $this->baseUrl ?>/inventory/item-picture/list1?token=<?php echo (!$entity == null)? $entity->getToken():"";?>&target_id=<?php echo (!$entity == null)? $entity->getId():"";?>&checksum=<?php echo (!$entity == null)? $entity->getChecksum():"";?>"><span
				class="glyphicon glyphicon-picture"></span>&nbsp;(<?php echo $total_picture;?>)&nbsp;</a></li>
		<li><a
			href="<?php echo $this->baseUrl ?>/inventory/item-purchase/list1?token=<?php echo (!$entity == null)? $entity->getToken():"";?>&target_id=<?php echo (!$entity == null)? $entity->getId():"";?>&checksum=<?php echo (!$entity == null)? $entity->getChecksum():"";?>">Purchasing</a></li>
		<li><a
			href="<?php echo $this->baseUrl ?>/inventory/stock/summary?token=<?php echo (!$entity == null)? $entity->getToken():"";?>&target_id=<?php echo (!$entity == null)? $entity->getId():"";?>&checksum=<?php echo (!$entity == null)? $entity->getChecksum():"";?>">Stock</a></li>
		
		<?php if(!$entity!==null):?>		
		<?php if($entity->getMonitoredBy()==\Application\Model\Constants::ITEM_WITH_SERIAL_NO OR $entity->getIsFixedAsset()==1):?>
				<li><a
			href="<?php echo $this->baseUrl ?>/inventory/item-serial/list1?token=<?php echo (!$entity == null)? $entity->getToken():"";?>&target_id=<?php echo (!$entity == null)? $entity->getId():"";?>&checksum=<?php echo (!$entity == null)? $entity->getChecksum():"";?>">Serial</a></li>
			
		<?php endif;?>
		<?php endif;?>
		
		<li><a title="<?php echo $this->translate("Attachments");?>"
			href="<?php echo $this->baseUrl ?>/inventory/item-attachment/list1?token=<?php echo (!$entity == null)? $entity->getToken():"";?>&target_id=<?php echo (!$entity == null)? $entity->getId():"";?>&checksum=<?php echo (!$entity == null)? $entity->getChecksum():"";?>"><span
				class="glyphicon glyphicon-paperclip"></span>&nbsp;(<?php echo $total_attachment;?>)&nbsp;</a></li>
		<li><a href="#accounting">&nbsp;Accounting</a></li>

		<li><a
			href="<?php echo $this->baseUrl ?>/inventory/item-assignment/list1?token=<?php echo (!$entity == null)? $entity->getToken():"";?>&target_id=<?php echo (!$entity == null)? $entity->getId():"";?>&checksum=<?php echo (!$entity == null)? $entity->getChecksum():"";?>">Assignment</a></li>

	
		<li><a title="<?php echo $this->translate("Purchase Request");?>"
			href="<?php echo $this->baseUrl ?>/procure/pr-row/pr-of-item?token=<?php echo (!$entity == null)? $entity->getToken():"";?>&item_id=<?php echo (!$entity == null)? $entity->getId():"";?>">PR (<?php echo $total_pr_row;?>)</a></li>

		<li><a title="<?php echo $this->translate("Quotation");?>"
			href="<?php echo $this->baseUrl ?>/procure/quote-row/qo-of-item?token=<?php echo (!$entity == null)? $entity->getToken():"";?>&item_id=<?php echo (!$entity == null)? $entity->getId():"";?>">QO (<?php echo $total_qo_row;?>)</a></li>

		<li><a title="<?php echo $this->translate("Purchase Order");?>"
			href="<?php echo $this->baseUrl ?>/procure/po-row/po-of-item?token=<?php echo (!$entity == null)? $entity->getToken():"";?>&item_id=<?php echo (!$entity == null)? $entity->getId():"";?>">PO (<?php echo $total_po_row;?>)</a></li>
		<li><a title="<?php echo $this->translate("AP Invoice");?>"
			href="<?php echo $this->baseUrl ?>/finance/v-invoice-row/ap-of-item?token=<?php echo (!$entity == null)? $entity->getToken():"";?>&item_id=<?php echo (!$entity == null)? $entity->getId():"";?>">A/P (<?php echo $total_ap_row;?>)</a></li>
		<li><a title="<?php echo $this->translate("Change Logs");?>"
			href="<?php echo $this->baseUrl ?>/inventory/change-log/list1?object_token=<?php echo (!$entity == null)? $entity->getToken():"";?>&object_id=<?php echo (!$entity == null)? $entity->getId():"";?>&class_name=<?php echo (!$entity == null)? get_class($entity):"";?>"><span
				class="glyphicon glyphicon-list"></span>&nbsp;Log</a></li>

	<li><a title="<?php echo $this->translate("Item Attributes");?>"	href="#attribute"><span
				class="glyphicon glyphicon-list"></span>&nbsp;<?php echo $this->translate("Attributes");?> </a></li>

	</ul>
	<div id="accounting" style="font-size: 9pt">
		- G/L Account <br> - Inventory UoM <br> - Min Quantity <br> - Max
		Quantity <br>


	</div>
		<div id="attribute" style="font-size: 9pt">
	Items can have serveral attributes such as size, color, material, etc.
	Comming soon.

	</div>


	<div id="general">
	
			<form id="create_item_form" class="form-horizontal"
			action="<?php echo $this->baseUrl ?>/inventory/item/add"
			method="post" enctype="multipart/form-data">
			<input type="hidden" name="redirectUrl"
				value="<?php echo $redirectUrl ?>" />

			<div class="form-group margin-bottom required">
				<label class="control-label col-sm-2">Item ID</label>
				<div class="col-sm-3">
					<input class="form-control input-sm" type="text" placeholder=""
						name="itemSku"
						value="<?php echo (!$entity == null)? $entity->getItemSku():"xx";?>">
					<input class="form-control input-sm" type="text"
						placeholder="optional sku" name="itemSku1"
						value="<?php echo (!$entity == null)? $entity->getItemSku1():"";?>">

				</div>
				<div class="col-sm-4">
					<input
						<?php if(!$entity == null): echo ($entity->getIsActive()=="1")?"checked":""; else: echo "checked"; endif;?>
						type="checkbox" name="isActive" value="1">&nbsp;Active&nbsp;&nbsp;
					<input
						<?php if(!$entity == null): echo ($entity->getIsStocked()=="1")?"checked":""; else: echo "checked"; endif;?>
						type="checkbox" name="isStocked" value="1">&nbsp;Stocked
					&nbsp;&nbsp; <input
						<?php if(!$entity == null): echo ($entity->getIsPurchased()=="1")?"checked":""; else: echo "checked"; endif;?>
						type="checkbox" name="isPurchased" value="1">&nbsp;Purchased
					&nbsp;&nbsp;<br> <input
						<?php if(!$entity == null): echo ($entity->getIsSaleItem()=="1")?"checked":""; else: echo ""; endif;?>
						type="checkbox" name="isSaleItem" value="1">&nbsp;For Sale
					&nbsp;&nbsp; <input
						<?php if(!$entity == null): echo ($entity->getIsFixedAsset()=="1")?"checked":""; else: echo ""; endif;?>
						type="checkbox" name="isFixedAsset" value="1">&nbsp;Fixed Asset <input
						<?php if(!$entity == null): echo ($entity->getIsSparepart()=="1")?"checked":""; else: echo ""; endif;?>
						type="checkbox" name="isSparePart" value="1">&nbsp;Spare Part

				</div>

			</div>
			<hr style="margin: 5pt 1pt 5pt 1pt;">

			<div class="form-group margin-bottom required">
				<label class="control-label col-sm-2">Item Name</label>
				<div class="col-sm-3">
					<input class="form-control input-sm" type="text" placeholder=""
						name="itemName"
						value="<?php echo (!$entity == null)? $entity->getItemName():"";?>">
				</div>

				<label class="control-label col-sm-2">Item Foreign Name</label>
				<div class="col-sm-3">
					<input class="form-control input-sm" type="text" placeholder=""
						name="itemNameForeign"
						value="<?php echo (!$entity == null)? $entity->getItemNameForeign():"";?>">
				</div>
			</div>
			<div class="form-group margin-bottom">
				<label class="control-label col-sm-2">Item Description</label>
				<div class="col-sm-8">
					<input class="form-control input-sm" type="text" placeholder=""
						name="itemDescription"
						value="<?php echo (!$entity == null)? $entity->getItemDescription():"";?>">
				</div>
			</div>

			<div class="form-group margin-bottom">
				<label class="control-label col-sm-2">Keyworks</label>
				<div class="col-sm-3">
					<input class="form-control input-sm" type="text" placeholder=""
						name="keywords"
						value="<?php echo (!$entity == null)? $entity->getKeywords():"";?>">
				</div>
			</div>


			<div class="form-group margin-bottom">

				<label class="control-label col-sm-2">Inventory No.</label>
				<div class="col-sm-3">
					<input class="form-control input-sm" type="text" placeholder=""
						name="assetLabel"
						value="<?php echo (!$entity == null)? $entity->getAssetLabel():"";?>">
				</div>

				<label class="control-label col-sm-2">Barcode</label>
				<div class="col-sm-3">
					<input class="form-control input-sm" type="text" placeholder=""
						name="barcode"
						value="<?php echo (!$entity == null)? $entity->getBarcode():"";?>">

				</div>

			</div>
			<hr style="margin: 5pt 1pt 5pt 1pt">
			<div class="form-group margin-bottom required">
				<label class="control-label col-sm-2"><?php echo $this->translate("Standard Unit");?></label>
				<div class="col-sm-3">

					<select name="uom_id" id="uom_id" class="form-control input-sm">
						<option value=""><?php echo $this->translate("Select standard unit");?></option>
   	    	<?php
            if ($uom_list !== null) :
                foreach ($uom_list as $uom) :

                    /**@var \Application\Entity\NmtApplicationUom $uom ; */
                    $selected = '';
                    if ($entity !== null) :
                        if ($entity->getStandardUom() !== null) :
                            if ($entity->getStandardUom()->getId() == $uom->getId()) :
                                $selected = 'selected';
                            endif;
                         endif;
                    endif;
                    echo sprintf('<option %s value="%s">%s </option>', $selected, ucwords($uom->getId()), ucwords($uom->getUomCode()));
                endforeach;
   	    	endif;

            ?>
   					</select>

				</div>
			</div>
			
			<div class="form-group margin-bottom required">
				<label class="control-label col-sm-2"><?php echo $this->translate("Inventory Unit");?>:</label>
				<div class="col-sm-3">

					<select name="stock_uom_id" id="stock_uom_id"
						class="form-control input-sm">
						<option value=""><?php echo $this->translate("Select inventory unit");?></option>
   	    							<?php
            if ($uom_list !== null) :
                foreach ($uom_list as $uom) :

                    /**@var \Application\Entity\NmtApplicationUom $uom ; */
                    $selected = '';
                    if ($entity !== null) :
                        if ($entity->getStockUom() !== null) :
                        if ($entity->getStockUom()->getId() == $uom->getId()) :
                                $selected = 'selected';
   	    							endif;
   	    							endif;
   	    							endif;



                    echo sprintf('<option %s value="%s">%s </option>', $selected, ucwords($uom->getId()), ucwords($uom->getUomCode()));
                endforeach
                ;
   	    							endif;

            ?>
   					</select>
   					</div>
   					
   						<label class="control-label col-sm-2"><?php echo $this->translate("Conversion Factor");?></label>
				<div class="col-sm-1">
					<input class="form-control input-sm" type="text" placeholder=""
						name="stockUomConvertFactor"
						id="stock_uom_convert_factor_id"
						value="<?php echo (!$entity == null)? $entity->getStockUomConvertFactor():"";?>">
				</div>
				
				<div class="col-sm-3">
					<span style="color: graytext;" id="stock_uom_convert_text"></span>
				</div>

				</div>

			<div class="form-group margin-bottom required">
				<label class="control-label col-sm-2"><?php echo $this->translate("Purchase Unit");?>:</label>
				<div class="col-sm-3">

					<select name="purchase_uom_id" id="purchase_uom_id"
						class="form-control input-sm">
						<option value=""><?php echo $this->translate("Select purchase unit");?></option>
   	    							<?php
   	    							if ($uom_list !== null) :
   	    							foreach ($uom_list as $uom) :
   	    							
   	    							/**@var \Application\Entity\NmtApplicationUom $uom ; */
   	    							$selected = '';
   	    							if ($entity !== null) :
   	    							if ($entity->getPurchaseUom() !== null) :
   	    							if ($entity->getPurchaseUom()->getId() == $uom->getId()) :
   	    							$selected = 'selected';
   	    							endif;
   	    							endif;
   	    							endif;
   	    							echo sprintf('<option %s value="%s">%s </option>', $selected, ucwords($uom->getId()), ucwords($uom->getUomCode()));
   	    							endforeach;
   	    							endif;

            ?>
   					</select>

				</div>


				<label class="control-label col-sm-2"><?php echo $this->translate("Conversion Factor");?></label>
				<div class="col-sm-1">
					<input class="form-control input-sm" type="text" placeholder=""
						name="purchaseUomConvertFactor"
						id="purchase_uom_convert_factor_id"
						value="<?php echo (!$entity == null)? $entity->getPurchaseUomConvertFactor():"";?>">
				</div>

				<div class="col-sm-3">
					<span style="color: graytext;" id="purchase_uom_convert_text"></span>
				</div>
			</div>

			<div class="form-group margin-bottom required">
				<label class="control-label col-sm-2"><?php echo $this->translate("Sales Unit");?>:</label>
				<div class="col-sm-3">

					<select name="sales_uom_id" id="sales_uom_id"
						class="form-control input-sm">
						<option value=""><?php echo $this->translate("Select Sales Unit");?></option>
   	    							<?php
   	    							if ($uom_list !== null) :
   	    							foreach ($uom_list as $uom) :
   	    							
   	    							/**@var \Application\Entity\NmtApplicationUom $uom ; */
   	    							$selected = '';
   	    							if ($entity !== null) :
   	    							if ($entity->getSalesUom() !== null) :
   	    							if ($entity->getSalesUom()->getId() == $uom->getId()) :
   	    							$selected = 'selected';
   	    							endif;
   	    							endif;
   	    							endif;
   	    							echo sprintf('<option %s value="%s">%s </option>', $selected, ucwords($uom->getId()), ucwords($uom->getUomCode()));
   	    							endforeach;
   	    							endif;

            ?>
   					</select>

				</div>


				<label class="control-label col-sm-2"><?php echo $this->translate("Conversion Factor");?></label>
				<div class="col-sm-1">
					<input class="form-control input-sm" type="text" placeholder=""
						name="salesUomConvertFactor"
						id="sales_uom_convert_factor_id"
						value="<?php echo (!$entity == null)? $entity->getSalesUomConvertFactor():"";?>">


				</div>
				<div class="col-sm-3">
					<span style="color: graytext;" id="sales_uom_convert_text"></span>
				</div>
			</div>

			<hr style="margin: 5pt 1pt 5pt 1pt;">
			<div class="form-group margin-bottom required">
				<label class="control-label col-sm-2">Item Type</label>
				<div class="col-sm-3">
					<select class="form-control input-sm" name="itemType">
						<option
							<?php if(!$entity == null): echo ($entity->getItemType()=="ITEM")?"selected":""; endif;?>
							value="ITEM">Item</option>
						<option
							<?php if(!$entity == null): echo ($entity->getItemType()=="SERVICE")?"selected":""; endif;?>
							value="SERVICE">Service</option>
						<option
							<?php if(!$entity == null): echo ($entity->getItemType()=="SOFTWARE")?"selected":""; endif;?>
							value="SOFTWARE">Software</option>
					</select>
				</div>

				<label class="control-label col-sm-2"><?php echo $this->translate("Item Group");?>:</label>
				<div class="col-sm-3">
					<select name="item_group_id" class="form-control input-sm">
						<option value=""><?php echo $this->translate("Select Group");?></option>
   	    							<?php
            if ($item_group_list !== null) :
                foreach ($item_group_list as $gl) :

                    /**@var \Application\Entity\NmtInventoryItemGroup $gl ; */

                    if ($entity !== null) :
                        if ($entity->getItemGroup() !== null) :
                            if ($entity->getItemGroup()->getId() == $gl->getId()) :
                                echo '<option selected value="' . $gl->getId() . '">' . $gl->getGroupName() . '</option>';
                            else :
                                echo '<option value="' . $gl->getId() . '">' . $gl->getGroupName() . '</option>';
                            endif;
                        else :
                            echo '<option value="' . $gl->getId() . '">' . $gl->getGroupName() . '</option>';
                        endif;
                    else :
                        echo '<option value="' . $gl->getId() . '">' . $gl->getGroupName() . '</option>';
                    endif;
                endforeach
                ;
   	    							endif;

            ?>
   					</select>
				</div>
			</div>

			<div class="form-group margin-bottom required">
				<label class="control-label col-sm-2">Monitored by:</label>
				<div class="col-sm-3">
					<select class="form-control input-sm" name="monitoredBy">
						<option value="">NONE</option>
						<option
							<?php if(!$entity == null): echo ($entity->getMonitoredBy()=="SN")?"selected":""; endif;?>
							value="SN">Serial Number</option>
						<option
							<?php if(!$entity == null): echo ($entity->getMonitoredBy()=="B")?"selected":""; endif;?>
							value="B">Batch Number</option>
					</select>
				</div>
			</div>

			<div class="form-group margin-bottom">
				<label class="control-label col-sm-2">Item Category</label>
				<div class="col-sm-3">

					<input disabled class="form-control input-sm" type="text"
						id="item_category_name" placeholder="Please select item category"
						name="country_code_2"
						value="<?php if($category !== null):echo $category->getNodeName();endif;?>">
					<input type="hidden" class="form-control input-sm"
						id="item_category_name_selected" name="item_category_id"
						value="<?php if($category!== null):echo $category->getNodeId();endif;?>">
				</div>

				<a style="color: #0080ff;" href="javascript:;"
					onclick="showBootstrapDialog('Select Item Category','/application/item-category/list1','b_loaded_data');">Select&nbsp;&nbsp;<i
					class="glyphicon glyphicon-folder-open"></i>
				</a>
			</div>

			<div class="form-group margin-bottom">
				<label class="control-label col-sm-2">Department</label>
				<div class="col-sm-3">

					<input disabled class="form-control input-sm" type="text"
						id="department_name" placeholder="Please select!"
						name="deparment_name"
						value="<?php if($department !== null):echo $department->getNodeName();endif;?>">
					<input type="hidden" class="form-control input-sm" type="text"
						id="department_name_selected"
						placeholder="Please select standard unit" name="department_id"
						value="<?php if($department!== null):echo $department->getNodeId();endif;?>">

				</div>

				<a style="color: #0080ff;" href="javascript:;"
					onclick="showBootstrapDialog('Select Deparment','/application/department/list1','b_loaded_data');">Select&nbsp;&nbsp;<i
					class="glyphicon glyphicon-folder-open"></i>
				</a>

			</div>

			<div class="form-group margin-bottom">
				<label class="control-label col-sm-2">Location</label>
				<div class="col-sm-3">
					<input class="form-control input-sm" type="text" placeholder=""
						name="location"
						value="<?php echo (!$entity == null)? $entity->getLocation():"";?>">
				</div>
			</div>
			<hr style="margin: 5pt 1pt 5pt 1pt">

			<div class="form-group margin-bottom">
				<label class="control-label col-sm-2">Manufacturer</label>
				<div class="col-sm-3">
					<input class="form-control input-sm" type="text" placeholder=""
						name="manufacturer"
						value="<?php echo (!$entity == null)? $entity->getManufacturer():"";?>">
				</div>
				<label class="control-label col-sm-2">Manufacturer Model</label>
				<div class="col-sm-3">
					<input class="form-control input-sm" type="text" placeholder=""
						name="manufacturerModel"
						value="<?php echo (!$entity == null)? $entity->getManufacturerModel():"";?>">
				</div>
			</div>

			<div class="form-group margin-bottom">
				<label class="control-label col-sm-2">Manufacturer's Item Code</label>
				<div class="col-sm-3">
					<input class="form-control input-sm" type="text" placeholder=""
						name="manufacturerCode"
						value="<?php echo (!$entity == null)? $entity->getManufacturerCode():"";?>">
				</div>


				<label class="control-label col-sm-2">Manufacturer Serial</label>
				<div class="col-sm-3">
					<input class="form-control input-sm" type="text" placeholder=""
						name="manufacturerSerial"
						value="<?php echo (!$entity == null)? $entity->getManufacturerSerial():"";?>">
				</div>
			</div>

			<div class="form-group margin-bottom">
				<label class="control-label col-sm-2">Lead time</label>
				<div class="col-sm-3">
					<input class="form-control input-sm" type="text" placeholder=""
						name="leadTime"
						value="<?php echo (!$entity == null)? $entity->getLeadTime():"";?>">

					<input name="localAvailabiliy"
						<?php if(!$entity == null): echo ($entity->getLocalAvailabiliy()=="1")?"checked":""; else: echo ""; endif;?>
						type="checkbox" value="1">&nbsp;Local Availability
		<div style="color: gray; padding-top: 10pt; font-size: 8pt"><?php if(!$entity == null): echo ($entity->getCreatedOn() !== null)?'Created date: ' . date_format($entity->getCreatedOn(),"Y/m/d H:i:s"):""; endif;?></div>
					<div style="color: gray; padding-top: 2pt; font-size: 8pt"><?php if(!$entity == null): echo  ($entity->getLastChangeOn() !== null)?'Revision# '. $entity->getRevisionNo(). ' - Last Change: ' . date_format($entity->getLastChangeOn(),"Y/m/d H:i:s"):""; endif;?></div>

				</div>

				<label class="control-label col-sm-2">Remarks</label>
				<div class="col-sm-3">
					<textarea class="form-control input-sm" type="text" rows="5"
						placeholder="" name="remarksText" style="font-size: 9pt;"><?php echo (!$entity == null)? $entity->getRemarksText():"";?></textarea>
				</div>
			</div>
			<hr style="margin: 5pt 1pt 5pt 1pt">

		</form>
	</div>
</div>




<script type="text/javascript">
$("#create_item_form :input").attr("disabled", "disabled");

	$('#purchase_uom_convert_text').text($( "#purchase_uom_id option:selected" ).text() + " = " +  $('#purchase_uom_convert_factor_id').val() + " " + $( "#uom_id option:selected" ).text());
   	$('#sales_uom_convert_text').text($( "#sales_uom_id option:selected" ).text() + " = " +  $('#sales_uom_convert_factor_id').val() + " " + $( "#uom_id option:selected" ).text());
	$('#stock_uom_convert_text').text($( "#stock_uom_id option:selected" ).text() + " = " +  $('#stock_uom_convert_factor_id').val() + " " + $( "#uom_id option:selected" ).text());

   	$( "#tabs1" ).tabs({
   		beforeLoad:function(e,ui){
   			$( ui.panel ).html('<p>Loading...</p>');       
   		    },
   		   
   	});

   	$( "#tabs3" ).tabs({
   		beforeLoad:function(e,ui){
   			$( ui.panel ).html('<p>Loading...</p>');       
   		    },
   		   
   	});
   	$( "#tabs1" ).tabs( "option", "active", <?php echo $tab_idx; ?> );
   	$( "#tabs3" ).tabs( "option", "active", 0 );
</script>


