<h4>
	<i class="icon-upload"> </i> Upload picture:
</h4>

<?php
if ($item !== null) {
	echo '<div class="alert alert-info">';
	
	echo '<ul>';
	echo '<li>Company Name	: <strong>' . $item->getItemName() . $item->getId().'</strong></li>';
	
	echo '</ul>';
	echo '</div>';
}
?>


<!--  <div class="alert alert-warning">
    <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
    <strong>Info!</strong> This alert box could indicate a neutral informative change or action.
  </div>
  -->

<form id="sp_upload_pic_form" class="form-horizontal" action=""
	method="post" enctype="multipart/form-data">
	
	
	<div class="form-group">
		<label class="control-label col-sm-2" for="inputTag">Picture</label>
		<div class="col-sm-3">
			<input type="file" name="pictures[]" />
			<input type="file" name="pictures[]" />
			<input type="file" name="pictures[]" />
			<input type="file" name="pictures[]" />
			<input type="file" name="pictures[]" />
		</div>
	</div>
	
	
	
	<div class="form-group">
		<label class="control-label col-sm-2" for="inputTag"></label>
		<div class="col-sm-3">
			<button type="button"  onclick="uploadImages('/inventory/item/upload-picture','<?php echo $item!==null ? $item->getId():""?>','<?php echo $redirectUrl ?>')" class="btn btn-primary"
				id="upload">
				<i class="glyphicon glyphicon-upload"> </i> Upload
			</button>
			<a class="btn btn-default" href="<?php echo $redirectUrl ?>"><i class="icon-back"> </i> << Back</a>
		</div>
	</div>
</form>


<!-- Modal -->
<div id="myModal" class="modal" role="dialog">
	<div class="modal-dialog">
	<div class="modal-content">
	
		<div class="modal-body">
			<p>Processing........Please Wait!</p>
		</div>
	</div>
	</div>
</div>

<!-- Modal -->
<div class="modal fade" id="modal1" role="dialog">
	<div class="modal-dialog modal-sm">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal">&times;</button>
				<h5 class="modal-title">Mascot International Laos</h5>
			</div>
			<div class="modal-body">
				<p>No picture selected!</p>
			</div>
			<div class="modal-footer">
				<button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
			</div>
		</div>
	</div>
</div>