<?php /**@var \Application\Entity\FinVendorInvoice $entity ;*/?>


<div id="wrapper" class="toggled">

	<!-- Sidebar -->
	<div id="sidebar-wrapper" style="font-size: 9.5pt;">
					<?php
    $current_step = "STEP1";
    include (ROOT . '/module/Inventory/view/inventory/gi-create-wizard.php');
    ?>


	</div>
	<!-- /#sidebar-wrapper -->

	<!-- Page Content -->
	<div id="page-content-wrapper"
		style="font-size: 9.5pt; padding: 0px; margin: 0px;">
		<div class="container-fluid" id="main_container"
			style="font-size: 9.5pt; padding: 1px; margin: 0px;";>
			<a style="font-size: 9pt; margin: 2px; padding: 3px;"
				href="#menu-toggle" class="btn btn-primary btn-sm" id="menu-toggle"><span
				title="Hide Menu"><i class="fa fa-chevron-left" aria-hidden="true"></i>
					Menu <span></a>


			<div id="tabs" style="font-size: 10pt">
				<ul>
					<li><a href="#general">New A/P Invoice:</a></li>
				</ul>

				<div id="general" style="font-size: 9pt">
					<!-- Tab1 -->
	
	
	<?php
if (count($errors) > 0) {
    echo '<div class="alert alert-danger alert-dismissible"" role="alert" style="font-size: 9.5pt"><a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>[ERROR]';

    echo '<ul>';
    foreach ($errors as $error) :
        echo '<li>' . $error . '</li>';
    endforeach
    ;
    echo '</ul>';
    echo '</div>';
}
?>
<form id="Create_Inv_Form" class="form-horizontal"
						action="/inventory/gi/add" method="post"
						enctype="multipart/form-data">
						<input type="hidden" name="redirectUrl"
							value="<?php echo $redirectUrl ?>" />
						<fieldset>
							<legend style="font-size: 9.5pt; color: gray;">
								<small><span class="glyphicon glyphicon-triangle-right"></span></small>&nbsp;
								<a href="#invoice_header" class="" data-toggle="collapse">HEADER:</a>
							</legend>

							<div class="form-group margin-bottom required">

								<label class="control-label col-sm-2">Movement Type:</label>
								<div class="col-sm-3">
									<select name="movementType" class="form-control input-sm">
										<option value="">Select Movement</option>
   	    							<?php
            if ($issueType !== null) :
                foreach ($issueType as $k => $v) :
                    if ($entity !== null) :
                        if ($entity->getMovementType() == $k) :
                            echo '<option selected value="' . $k . '">' . $k . ' - ' . $this->translate($v['type_name']) . '</option>';
                        else :
                            echo '<option value="' . $k . '">' . $k . ' - ' . $this->translate($v['type_name']) . '</option>';
                        endif;
                    else :
                        echo '<option value="' . $k . '">' . $k . ' - ' . $this->translate($v['type_name']) . '</option>';
                    endif;
                endforeach
                ;
   	    							endif;

            ?>
   					</select>
								</div>

								<div class="col-sm-3">
									<input
										<?php if(!$entity== null): echo ($entity->getIsActive()=="1")?"checked":""; else: echo "checked"; endif;?>
										type="checkbox" name="isActive" value="1">&nbsp;Is
									Active&nbsp;&nbsp;&nbsp;&nbsp;

								</div>
							</div>


							<div class="form-group margin-bottom required">

								<label class="control-label col-sm-2">Movement Date:</label>
								<div class="col-sm-3">
									<input class="form-control input-sm" type="text"
										id="movementDate" name="movementDate"
										value="<?php if(!$entity == null): if ($entity->getMovementDate() !== null): echo date_format($entity->getMovementDate(),"Y-m-d"); endif; endif;?>"
										placeholder=" please select" />
								</div>
								<label class="control-label col-sm-2" for="inputTag"><?php echo $this->translate("Source Warehouse");?>:</label>
								<div class="col-sm-3">
									<input class="form-control input-sm" readonly type="text"
										id="target_wh_name" placeholder="Please select!"
										name="target_wh"
										value="<?php if (!$entity == null): if (!$entity->getWarehouse() == null):echo $entity->getWarehouse()->getWhName();endif;endif;?>">
									<input type="hidden" id="target_wh_id" name="target_wh_id"
										value="<?php if (!$entity == null): if (!$entity->getWarehouse() == null):echo $entity->getWarehouse()->getId();endif;endif;?>" />
								</div>
							</div>


							<div class="form-group margin-bottom">
								<label class="control-label col-sm-2">Description</label>
								<div class="col-sm-8">
									<input class="form-control input-sm" type="text" placeholder=""
										name="remarks"
										value="<?php echo (!$entity == null)? $entity->getRemarks():"";?>">
								</div>
							</div>


							<hr>
							<div class="form-group margin-bottom">
								<label class="control-label col-sm-2" for="inputTag"></label>
								<div class="col-sm-3">
									<button onclick="submitForm('Create_Inv_Form');"
										class="btn btn-default btn-sm">
										<i class="glyphicon glyphicon-floppy-disk"> </i> Save
									</button>
									<a class="btn btn-default btn-sm"
										href="<?php echo $redirectUrl; ?>"><small><i
											class="glyphicon glyphicon-remove"></i></small>&nbsp;Cancel</a>

								</div>
							</div>
						</fieldset>
					</form>



					<!-- end tab -->
				</div>
			</div>
		</div>
		<!-- /#page-content-wrapper -->

	</div>
	<!-- /#wrapper -->

	<script>

$('#invoiceDate').bind('change', function() {
	$('#postingDate').val($('#invoiceDate').val());
	$('#grDate').val($('#invoiceDate').val());
});

$( "input[id='movementDate']").datepicker({ firstDay: 1, dateFormat: 'yy-mm-dd',closeText: 'X',changeMonth: true, changeYear: true});


$( "#vendor_name_1" ).autocomplete({
    source: "/bp/vendor-search/auto-complete",
    minLength: 3,
    select: function( event, ui ) {
  	  $( "#vendor_id" ).val(ui.item.id);
      //alert	( "Selected: " + ui.item.value + " aka " + ui.item.id );
  	  //alert($( "#vendor_id" ).val());

  	 	$('#global-notice').show();
  		$('#global-notice').html('"' + ui.item.value + '" selected');
  		$('#global-notice').fadeOut(5000);
  		//$("#jquery_dialog").dialog("close");
    }
    })
    .autocomplete( "instance" )._renderItem = function( ul, item ) {
    return $( "<li>" )
      .append( "<div style='padding-bottom: 5px; border-bottom: thin solid gray;'><b>" + item.value + "</b><br><span style='color:gray;font-size: 9pt;'>" + item.vendor_country + "<span></div>" )
      .appendTo( ul );
    };

$( "#vendor_name_1" ).focus();
  
</script>