<?php
use Application\Application\Helper\ErrorMessage;
use Application\Application\Helper\OptionList;
use Application\Domain\Shared\Constants;
use Inventory\Application\DTO\Transaction\TrxDTO;

/**
 *
 * @var TrxDTO $headerDTO ;
 * @var \Application\Controller\Plugin\NmtPlugin $nmtPlugin ;
 *
 */

$entityFormInput = '';
$targetFormInput = '';
$view_url = sprintf($this->baseUrl . "/inventory/gi/create");

$format = '<div class="form-group margin-bottom"><div class="col-sm-offset-2 col-sm-10">
<button onclick="submitForm(\'%s\');" class="btn btn-default">
<i class="glyphicon glyphicon-floppy-disk"> </i>&nbsp;Save</button>
<a class="btn btn-default btn-sm" href="%s"><small><i class="glyphicon glyphicon-remove"></i></small>&nbsp;%s</a>
</div></div>';

$submitFormInput = $entityFormInput . sprintf($format, 'create_item_form', $view_url, $this->translate("Cancel"));

if ($action == Constants::FORM_ACTION_EDIT) {

    $view_url = sprintf($this->baseUrl . "/inventory/gi/view?entity_id=%s&entity_token=%s", $entity_id, $entity_token);

    $format = '<input type="hidden" name="redirectUrl" value="%s">';
    $entityFormInput = $entityFormInput . sprintf($format, $redirectUrl);

    $format = '<input type="hidden" id="entity_id" name="entity_id" value="%s">';
    $entityFormInput = $entityFormInput . sprintf($format, $entity_id);

    $format = '<input type="hidden" id="entity_token" name="entity_token" value="%s">';
    $entityFormInput = $entityFormInput . sprintf($format, $entity_token);

    $format = '<input type="hidden" id="version" name="version" value="%s">';
    $entityFormInput = $entityFormInput . sprintf($format, $version);
}

if ($action == Constants::FORM_ACTION_WH_GI_FOR_PO) {

    $view_url = sprintf($this->baseUrl . "/inventory/gi/view?entity_id=%s&entity_token=%s", $target_id, $target_token);

    $format = '<input type="hidden" name="redirectUrl" value="%s">';
    $targetFormInput = $targetFormInput . sprintf($format, $redirectUrl);

    $format = '<input type="hidden" id="target_id" name="target_id" value="%s">';
    $targetFormInput = $targetFormInput . sprintf($format, $target_id);

    $format = '<input type="hidden" id="target_token" name="target_token" value="%s">';
    $targetFormInput = $targetFormInput . sprintf($format, $target_token);
}

$wh_id = null;
$currencyId = $localCurrencyId;
$trxType = null;

if ($headerDTO != null) {
    $wh_id = $headerDTO->getWarehouse();
    if ($headerDTO->getDocCurrency() != null) {
        $currencyId = $headerDTO->getDocCurrency();
    }

    $trxType = $headerDTO->getMovementType();
}

$wh_option = OptionList::createWarehouseOption($nmtPlugin->warehouseList(), $wh_id);
$currency_option = OptionList::createCurrencyOption($nmtPlugin->currencyList(), $currencyId);

$trx_option = OptionList::createGoodsIssueOption($this, $currencyId);

$error_msg = ErrorMessage::showErrorMessage($errors);

// ===============================
?>
<div id="wrapper" class="toggled">
   <!-- Sidebar -->
   <div id="sidebar-wrapper" style="font-size: 9.5pt;">
					<?php
    $current_step = "STEP1";
    include (ROOT . '/module/Inventory/view/inventory/gi-create-wizard.php');
    ?>


	</div>
   <!-- /#sidebar-wrapper -->
   <!-- Page Content -->
   <div id="page-content-wrapper" style="font-size: 9.5pt; padding: 0px; margin: 0px;">
      <div class="container-fluid" id="main_container" style="font-size: 9.5pt; padding: 1px; margin: 0px;";>
         <a style="font-size: 9pt; margin: 2px; padding: 3px;" href="#menu-toggle" class="btn btn-primary btn-sm" id="menu-toggle">
            <span title="Hide Menu">
               <i class="fa fa-chevron-left" aria-hidden="true"></i>
               Menu
               <span>

         </a>
         <div id="tabs" style="font-size: 10pt">
            <ul>
               <li>
                  <a href="#general"><?php

                echo $form_title;
                ?></a>
               </li>
            </ul>
            <div id="general" style="font-size: 9pt">
               <!-- Tab1 -->
<?php
echo $error_msg;
?>
<form id="Trx_Header_Form" class="form-horizontal" action="<?php
echo $form_action;
?>" method="post" enctype="multipart/form-data">

<?php
echo $entityFormInput;
echo $targetFormInput;
?>

                  <fieldset>
                     <legend style="font-size: 9.5pt; color: gray;">
                        <small>
                           <span class="glyphicon glyphicon-triangle-right"></span>
                        </small>
                        &nbsp;
                        <a href="#invoice_header" class="" data-toggle="collapse">HEADER: (Rev.#<?php
                        echo $version;
                        ?>)</a>
                     </legend>
                     <div class="form-group margin-bottom required">
                        <label class="control-label col-sm-2">Movement Type:</label>
                        <div class="col-sm-3">
                           <select name="movementType" class="form-control input-sm chosen-select">

                              <option value="">Select Movement</option>
                           <?php
                        echo $trx_option;
                        ?>

   					</select>
                        </div>
                        <div class="col-sm-3">
                           <input
                              <?php

                            if (! $headerDTO == null) :
                                echo ($headerDTO->getIsActive() == "1") ? "checked" : "";
                            else :
                                echo "checked";
                            endif;
                            ?>
                              type="checkbox" name="isActive" value="1">
                           &nbsp;Is Active&nbsp;&nbsp;&nbsp;&nbsp;
                        </div>
                     </div>
                     <div class="form-group margin-bottom required">
                        <label class="control-label col-sm-2">Movement Date:</label>
                        <div class="col-sm-3">
                           <input class="form-control input-sm" type="text" id="movementDate" name="movementDate" value="<?php

                        if (! $headerDTO == null) :
                            echo $headerDTO->getMovementDate(); endif;

                        ?>"
                              placeholder=" please select" />
                        </div>
                        <label class="control-label col-sm-2"><?php

                        echo $this->translate("Source Warehouse");
                        ?></label>
                        <div class="col-sm-3">
                           <select name="warehouse" id="standardUom_id" class="form-control input-sm chosen-select">
                              <option value=""><?php

                            echo $this->translate("Select Warehouse");
                            ?></option>
   	    	<?php
        echo $wh_option;
        ?>
   					</select>
                        </div>
                     </div>
                     <div class="form-group margin-bottom required">
                        <label class="control-label col-sm-2">Currency:</label>
                        <div class="col-sm-3">
                           <select name="docCurrency" class="form-control input-sm chosen-select">
                              <option value="">Select Currency</option>
 <?php
// ================
echo $currency_option;
// ================
?>                                  </select>
                        </div>
                        <label class="control-label col-sm-2">Exchange Rate:</label>
                        <div class="col-sm-3">
                           <input class="form-control input-sm" type="text" placeholder="" id="exchangeRate" name="exchangeRate" value="<?php
                        echo (! $headerDTO == null) ? $headerDTO->getExchangeRate() : "";
                        ?>">
                        </div>
                     </div>
                     <div class="form-group margin-bottom">
                        <label class="control-label col-sm-2">Description</label>
                        <div class="col-sm-8">
                           <input class="form-control input-sm" type="text" placeholder="" name="remarks" value="<?php

                        echo (! $headerDTO == null) ? $headerDTO->getRemarks() : "";
                        ?>">
                        </div>
                     </div>
                     <hr>
                     <div class="form-group margin-bottom">
                        <label class="control-label col-sm-2" for="inputTag"></label>
                        <div class="col-sm-3">
                         <?php
                        echo $submitFormInput;
                        ?>
                        </div>
                     </div>
                  </fieldset>
               </form>
               <!-- end tab -->
            </div>
         </div>
      </div>
      <!-- /#page-content-wrapper -->
   </div>
   <!-- /#wrapper -->
   <script>

$('#invoiceDate').bind('change', function() {
	$('#postingDate').val($('#invoiceDate').val());
	$('#grDate').val($('#invoiceDate').val());
});

$( "input[id='movementDate']").datepicker({ firstDay: 1, dateFormat: 'yy-mm-dd',closeText: 'X',changeMonth: true, changeYear: true});


$( "#vendor_name_1" ).autocomplete({
    source: "/bp/vendor-search/auto-complete",
    minLength: 3,
    select: function( event, ui ) {
  	  $( "#vendor_id" ).val(ui.item.id);
      //alert	( "Selected: " + ui.item.value + " aka " + ui.item.id );
  	  //alert($( "#vendor_id" ).val());

  	 	$('#global-notice').show();
  		$('#global-notice').html('"' + ui.item.value + '" selected');
  		$('#global-notice').fadeOut(5000);
  		//$("#jquery_dialog").dialog("close");
    }
    })
    .autocomplete( "instance" )._renderItem = function( ul, item ) {
    return $( "<li>" )
      .append( "<div style='padding-bottom: 5px; border-bottom: thin solid gray;'><b>" + item.value + "</b><br><span style='color:gray;font-size: 9pt;'>" + item.vendor_country + "<span></div>" )
      .appendTo( ul );
    };

$( "#vendor_name_1" ).focus();

</script>