<?php
use application\application\helper\errormessage;
use application\application\helper\optionhelper;
use application\application\helper\optionlist;
use inventory\application\dto\transaction\trxdto;
use inventory\application\dto\transaction\trxrowdto;

/**
 *
 * @author nguyen mau tri - ngmautri@gmail.com
 *         ===========================================
 *
 * @var trxdto $headerdto ;
 * @var trxrowdto $dto ;
 * @var \application\controller\plugin\nmtplugin $nmtplugin ;
 */

// var_dump($headerdto);

$base_url = sprintf($this->baseurl . "/inventory/gi/");
$view_url = null;
$review_url = null;
$rownumber = null;
$alert = "info";
$transactiontypearray = [];
$docuomname = null;

$format = '<div class="form-group margin-bottom"><div class="col-sm-offset-2 col-sm-10">
<button onclick="submitform(\'%s\');" class="btn btn-default">
<i class="glyphicon glyphicon-floppy-disk"> </i>&nbsp;save</button>
<a class="btn btn-default btn-sm" href="%s"><small><i class="glyphicon glyphicon-remove"></i></small>&nbsp;%s</a>
</div></div>';

$hiddenforminput = '';

$format = '<input type="hidden" name="redirecturl" value="%s">';
$hiddenforminput = $hiddenforminput . sprintf($format, $redirecturl);

$format = '<input type="hidden" id="target_id" name="target_id" value="%s">';
$hiddenforminput = $hiddenforminput . sprintf($format, $target_id);

$format = '<input type="hidden" id="target_token" name="target_token" value="%s">';
$hiddenforminput = $hiddenforminput . sprintf($format, $target_token);

$format = '<input type="hidden" id="entity_id" name="entity_id" value="%s">';
$hiddenforminput = $hiddenforminput . sprintf($format, $entity_id);

$format = '<input type="hidden" id="entity_token" name="entity_token" value="%s">';
$hiddenforminput = $hiddenforminput . sprintf($format, $entity_token);

$format = '<input type="hidden" id="version" name="docrevisionno" value="%s">';
$hiddenforminput = $hiddenforminput . sprintf($format, $docrevisionno);

// var_dump($headerdto);
if ($headerdto !== null) {
    $headerdto_id = $headerdto->getid();
    $headerdto_token = $headerdto->gettoken();
    $transactiontypearray = $transactiontype[$headerdto->getmovementtype()];

    $message_url = sprintf($this->baseurl . "/application/message-store/list1?entity_token=%s&entity_id=%s", $headerdto_token, $headerdto_id);
    $review_url = sprintf($base_url . "review?entity_id=%s&entity_token=%s", $headerdto_id, $headerdto_token);
    $add_url = sprintf($base_url . "add-row?target_id=%s&token=%s", $headerdto_id, $headerdto_token);
    $view_url = sprintf($base_url . "view?entity_id=%s&entity_token=%s", $headerdto_id, $headerdto_token);

    $rownumber = $headerdto->gettotalrows() + 1;
    $docuomname = $dto->getdocunit();
}

$cost_center = null;

$item_view_url = null;
$item_view_javascript = null;
if ($dto !== null) {
    $rownumber = $dto->getrownumber();
    $cost_center = $dto->getcostcenter();
    $format = '/inventory/item/show1?tab_idx=0&entity_id=%s&token=%s';
    $item_view_url = sprintf($format, $dto->getitem(), $dto->getitemtoken());

    $format = ' $("#item_name" ).val("%s");' . "\n";
    $format = $format . ' $("#item_url" ).text("%s");' . "\n";
    $format = $format . ' $("#item_detail").show()' . "\n";
    $item_view_javascript = sprintf($format, $dto->itemname, $item_view_url);
}

$cost_center_option = optionlist::createcostcenteroption($nmtplugin->costcenterlist(), $cost_center);
$error_msg = errormessage::showerrormessage($errors);

$uomlist = $sharedcollection->getuomcollection();
$uom_option = optionhelper::createuomnameoption($uomlist, $docuomname);

$current_step = "step2";

// =====================================================

?>
<div id="wrapper" class="toggled">
   <!-- sidebar -->
   <div id="sidebar-wrapper" style="font-size: 9.5pt;">
					<?php
    $current_step = "step2";
    include (root . '/module/inventory/view/inventory/gi-create-wizard.php');
    include (root . '/module/inventory/view/inventory/trx_summary.php');

    ?>
   </div>
   <!-- /#sidebar-wrapper -->
   <!-- page content -->
   <div id="page-content-wrapper" style="font-size: 9.5pt; padding: 0px; margin: 0px;">
      <div class="container-fluid" id="main_container" style="font-size: 9.5pt; padding: 1px; margin: 0px;";>
         <a style="font-size: 9pt; margin: 2px; padding: 3px;" href="#menu-toggle" class="btn btn-primary btn-sm" id="menu-toggle">
            <span title="hide menu">
               <i class="fa fa-chevron-left" aria-hidden="true"></i>
               menu
               <span>

         </a>
         <div id="tabs" style="font-size: 10pt">
            <ul>
               <li>
                  <a href="#general">
                     <small>
                        <i class="glyphicon glyphicon-plus"> </i>
                        </i>
                     </small>&nbsp;<?php
                    echo $form_title;
                    ?></a>
               </li>
               <li>
                  <a href="">
                     <small>
                        <i class="glyphicon glyphicon-list"> </i>
                        </i>
                     </small>
                     &nbsp;current rows
                  </a>
               </li>
               <li>
                  <a title="<?php
                echo $this->translate("change logs");
                ?>" href="">
                     <span class="glyphicon glyphicon-list"></span>
                     &nbsp;log
                  </a>
               </li>
            </ul>
            <div id="general" style="font-size: 9pt">
               <!-- tab1 -->

						<?php
    echo $error_msg;
    ?>

					<!-- for all case: -->
               <form id="new_trx_row" class="form-horizontal" action="<?php
            echo $form_action;
            ?>" method="post" enctype="multipart/form-data">
              <?php
            echo $hiddenforminput;
            ?>

			<!-- for all case: -->
                  <div id="new_row" class="collapse in">
                     <div class="form-group margin-bottom">
                        <label class="control-label col-sm-2"></label>
                        <div class="col-sm-3">
                           <input
                              <?php

                            if (! $dto == null) :
                                echo ($dto->getisactive() == "1") ? "checked" : "";
                            else :
                                echo "checked";
                            endif;
                            ?>
                              type="checkbox" name="isactive" value="1">
                           &nbsp;is active&nbsp;&nbsp;&nbsp;&nbsp;
                        </div>
                     </div>
                     <div class="form-group margin-bottom  required">
                        <label class="control-label col-sm-2">issue for item: </label>
                        <div class="col-sm-3">
                           <input tabindex="2" class="form-control" type="text" id="issueforname" placeholder="enter keyword to search item..." name="issueforname"
                              value="<?php

                            if (! $dto == null) :
                                echo $dto->getissuefor();endif;

                            ?>">
                           <input type="hidden" id="issuefor" placeholder="" name="issuefor" value="<?php
                        if (! $dto == null) :
                            echo $dto->getissuefor();
                        endif;

                        ?>">
                           <div id="issue_for_url" style="display: none;"></div>
                        </div>
                        <div class="col-sm-1" style="margin: 0px">
                           <span title="<?php

                        echo $this->translate("item detail");
                        ?>" id="issue_for_detail" style="display: none;">
                              &nbsp;&nbsp;
                              <a style="color: #0080ff;" href="javascript:;" onclick="showselectedissueforitem();">
                                 <i style="color: navy" class="fa fa-info-circle fa-lg" aria-hidden="true"></i>
                              </a>
                              <br>
                           </span>
                        </div>
                        <div class="col-sm-2" style="margin: 0px">
                           <a style="color: #0080ff;" href="javascript:;" onclick="showjquerydialog('select item','1350',$(window).height()-50, '/inventory/item-search/do1?target_id=item_id&target_name=item_name','j_loaded_data', true);">
                              select&nbsp;&nbsp;
                              <i class="glyphicon glyphicon-folder-open"></i>
                           </a>
                        </div>
                        <div class="col-sm-3">
                           <a target="_blank" style="font-size: 9pt;" href="/inventory/item/list">item list&nbsp;&nbsp;</a>
                           <small>
                              <i class="glyphicon glyphicon-new-window"></i>
                           </small>
                        </div>
                     </div>
                     <div class="form-group margin-bottom required">
                        <label class="control-label col-sm-2" for="inputtag">quantity:</label>
                        <div class="col-sm-3">
                           <input tabindex="3" class="form-control input-sm" type="text" id="docquantity" name="docquantity" value="<?php

                        echo (! $dto == null) ? $dto->getdocquantity() : "";
                        ?>">
                        </div>
                        <label class="control-label col-sm-2" for="inputtag">convert factor:</label>
                        <div class="col-sm-3">
                           <input tabindex="4" class="form-control input-sm" type="text" id="conversionfactor" name="conversionfactor" value="<?php

                        echo (! $dto == null) ? $dto->getconversionfactor() : "1";
                        ?>">
                        </div>
                     </div>


 <hr style="margin: 5pt 1pt 5pt 1pt;">
                     <div class="form-group margin-bottom required">
                        <label class="control-label col-sm-2"><?php

                        echo $this->translate("document unit");
                        ?></label>
                        <div class="col-sm-3">
                           <select tabindex="6" name="docunit" id="docunit" class="form-control input-sm">
                              <option value=""><?php

                            echo $this->translate("select doc unit");
                            ?></option>
                    <?php
                    echo $uom_option;
                    ?>
               </select>
                        </div>
                        <label class="control-label col-sm-2" for="inputtag">converstion factor:</label>
                        <div class="col-sm-1">
                           <input tabindex="7" class="form-control input-sm" type="text" name="standardconvertfactor" id="standardconvertfactor" value="<?php

                        echo (! $dto == null) ? $dto->getstandardconvertfactor() : "1";
                        ?>">
                        </div>
                        <div class="col-sm-3">
                           <span style="color: graytext; padding-bottom: 5px; margin: 0 0 0 10pt; font-size: 8.5pt" id="">converstion to item standard unit.</span>
                        </div>
                     </div>


                     <div class="form-group margin-bottom  required">
                        <label class="control-label col-sm-2">item: </label>
                        <div class="col-sm-3">
                           <input tabindex="5" class="form-control" type="text" id="item_name" placeholder="enter keyword to search item..." name="item_name"
                              value="<?php

                            if (! $dto == null) :
                                echo $dto->getitemname();endif;

                            ?>">
                           <input type="hidden" id="item" placeholder="" name="item" value="<?php
                        if (! $dto == null) :
                            echo $dto->getitem();
                        endif;

                        ?>">
                           <div id="item_url" style="display: none;"></div>
                        </div>
                        <div class="col-sm-1" style="margin: 0px">
                           <span title="<?php

                        echo $this->translate("item detail");
                        ?>" id="item_detail" style="display: none;">
                              &nbsp;&nbsp;
                              <a style="color: #0080ff;" href="javascript:;" onclick="showselecteditem();">
                                 <i style="color: navy" class="fa fa-info-circle fa-lg" aria-hidden="true"></i>
                              </a>
                              <br>
                           </span>
                        </div>
                        <div class="col-sm-2" style="margin: 0px">
                           <a style="color: #0080ff;" href="javascript:;" onclick="showjquerydialog('select item','1350',$(window).height()-50, '/inventory/item-search/do1?target_id=item_id&target_name=item_name','j_loaded_data', true);">
                              select&nbsp;&nbsp;
                              <i class="glyphicon glyphicon-folder-open"></i>
                           </a>
                        </div>
                        <div class="col-sm-3">
                           <a target="_blank" style="font-size: 9pt;" href="/inventory/item/list">item list&nbsp;&nbsp;</a>
                           <small>
                              <i class="glyphicon glyphicon-new-window"></i>
                           </small>
                        </div>
                     </div>
                     <div class="form-group margin-bottom required">
                        <label class="control-label col-sm-2" for="inputtag"><?php

                        echo $this->translate("cost center");
                        ?>:</label>
                        <div class="col-sm-3">
                           <select name="costcenter" class="form-control input-sm">
                              <option value=""><?php

                            echo $this->translate("select cost center");
                            ?></option>
   	    							<?php
            echo $cost_center_option;
            ?>
   					</select>
                        </div>
                     </div>
                     <div class="form-group margin-bottom">
                        <label class="control-label col-sm-2">remark:</label>
                        <div class="col-sm-8">
                           <input tabindex="9" class="form-control input-sm" type="text" placeholder="" name="remarks" value="<?php

                        echo (! $dto == null) ? $dto->getremarks() : "";
                        ?>">
                        </div>
                     </div>
                     <div class="form-group margin-bottom">
                        <label class="control-label col-sm-2" for="inputtag"></label>
                        <div class="col-sm-3">
                           <a tabindex="10" class="btn btn-default btn-sm" onclick="submitform('new_trx_row');" href="javascript:;">
                              <small>
                                 <i class="glyphicon glyphicon-floppy-disk"></i>
                              </small>
                              &nbsp;save
                           </a>
                           <a tabindex="11" class="btn btn-default btn-sm" href="<?php
                        echo $review_url;
                        ?>">
                              <small>
                                 <i class="glyphicon glyphicon-remove"></i>
                              </small>
                              &nbsp;cancel
                           </a>
                        </div>
                     </div>
                  </div>
               </form>
               <!-- end tab -->
            </div>
         </div>
      </div>
      <!-- /#page-content-wrapper -->
   </div>
   <!-- /#wrapper -->
   <script type="text/javascript">
 	$( "#issueforname" ).focus();

    $('#quantity').bind('change', function() {
         });

  </script>

 <?php
include (root . '/module/inventory/view/inventory/item_auto_complete_1.php');
include (root . '/module/inventory/view/inventory/item_auto_complete.php');
?>