<h4>
	 <?php echo (!$item == null)? $item->getItemName():"";?>
</h4>

<?php
if (count ( $errors ) > 0) {
	echo '<div class="alert alert-danger" role="alert" style="font-size: 10.5pt">';
	
	echo '<ul>';
	foreach ( $errors as $error ) :
		echo '<li>' . $error . '</li>';
	endforeach
	;
	echo '</ul>';
	echo '</div>';
}
?>

<div id="tabs" style="font-size: 9.5pt"> 
  <ul>
  <li ><a href="#general">Purchasing Data</a></li>
   </ul>

<div id="general"> 

<form id="" class="form-horizontal" action="/inventory/item-purchase/add" method="post" enctype="multipart/form-data">
<input type="hidden" name="item_id" value="<?php echo (!$item == null)? $item->getId():"";?>" />
<input type="hidden" name="new_entity_id" value="<?php echo $new_entity_id;?>" />
<input type="hidden" name="redirectUrl" value="<?php echo $redirectUrl ?>" />

	<div class="form-group">
		<label class="control-label col-sm-2" >Vendor:</label>
		<div class="col-sm-3">
			<input disabled class="form-control" type="text" id="vendor_name" placeholder="Select vendor"
				name="vendor_name" value="<?php echo (!$vendor == null)? $vendor->getVendorName():"";?>">
			<input type="hidden" id="vendor_id" placeholder="" 
			name="vendor_id" value="<?php echo (!$vendor== null)? $vendor->getId():"";?>">
				 <input <?php if(!$entity== null): echo ($entity->getIsPreferredVendor()=="1")?"checked":""; else: echo "checked"; endif;?> type="checkbox" name="is_preferred_vendor" value="1">&nbsp;Is Preferred&nbsp;&nbsp;
		  	     <input <?php if(!$entity == null): echo ($entity->getIsActive()==="1")?"checked":""; else: echo "checked"; endif;?> type="checkbox" name="is_active" value="1">&nbsp;Active&nbsp;&nbsp;
		
		</div>
		

<a style="color: #0080ff;" href="javascript:;"
	onclick="showJqueryDialog('Select Vendor','750','450', '/bp/vendor/list1','j_loaded_data', true);">Select&nbsp;&nbsp;<i class="glyphicon glyphicon-folder-open"></i>
</a>

	</div>
	
	

	<div class="form-group">
		<label class="control-label col-sm-2" >Vendor's Item Code</label>
		<div class="col-sm-3">
			<input class="form-control" type="text"  placeholder=""
				name="vendor_item_code" value="<?php echo (!$entity == null)? $entity->getVendorItemCode():"";?>">
		</div>		
	</div>
	
	<div class="form-group">
		<label class="control-label col-sm-2" >Vendor's Item Unit</label>
		<div class="col-sm-3">
			<input class="form-control" type="text"  placeholder=""
				id = "vendor_item_unit" name="vendor_item_unit" value="<?php echo (!$entity == null)? $entity->getVendorItemUnit():"";?>">
		</div>
		
		<label class="control-label col-sm-2" >Conversion Factor:</label>
		<div class="col-sm-3">
			<input class="form-control" type="text"  placeholder=""
				id="conversion_factor" name="conversion_factor" value="<?php echo (!$entity == null)? $entity->getConversionFactor():"";?>">
		</div>
		<span style="font-size: 9.5pt" id="conversion_text"></span> <span><?php echo (!$item == null)? $item->getStandardUom()->getUomCode():"";?></span>			
	</div>
	

	<div class="form-group">
		<label class="control-label col-sm-2" >Unit Price</label>
		<div class="col-sm-3">
			<input class="form-control" type="text"  placeholder=""
				name="vendor_unit_price" value="<?php echo (!$entity == null)? $entity->getVendorUnitPrice():"";?>">
		</div>
		
		<label class="control-label col-sm-2" >Currency:</label>
		<div class="col-sm-3">
			<input disabled class="form-control" type="text" id="currency_name" placeholder="Select Currency"
				name="currency_name" value="<?php echo (!$currency== null)? $currency->getCurrency():"";?>">
			<input type="hidden" id="currency_id" placeholder="" 
			name="currency_id" value="<?php echo (!$currency== null)? $currency->getId():"";?>">
		</div>
		

<a style="color: #0080ff;" href="javascript:;"
	onclick="showJqueryDialog('Select Currency','500','450', '/application/currency/select','j_loaded_data', true);">Select&nbsp;&nbsp;<i class="glyphicon glyphicon-folder-open"></i>
</a>		
	</div>
	
	<div class="form-group">
		<label class="control-label col-sm-2" >Valid From:</label>
		<div class="col-sm-3">
			<input class="form-control" type="text" name="price_valid_from" 
			value="<?php if(!$entity == null): echo ($entity->getPriceValidFrom() !== null)? date_format($entity->getPriceValidFrom(),"Y-m-d"):""; endif;?>" placeholder =" please select" id="valid_from" />
		</div>
		
		<label class="control-label col-sm-2" >Valid To:</label>
		<div class="col-sm-3">
			<input class="form-control" type="text" name="price_valid_to" 
			value="<?php if(!$entity == null): echo ($entity->getPriceValidTo() !== null)? date_format($entity->getPriceValidTo(),"Y-m-d"):""; endif;?>" placeholder =" please select" id="valid_to" />
		</div>		
	</div>
	
	
	
	<div class="form-group">
		<label class="control-label col-sm-2" >Payment Method</label>
		<div class="col-sm-3">
			<input disabled class="form-control" type="text" id="pmt_method_name" placeholder="Select Payment Method"
				name="pmt_method_name" value="<?php echo (!$pmt_method== null)? $pmt_method->getMethodCode():"";?>">
			<input type="hidden" id="pmt_method_id" placeholder="" 
			name="pmt_method_id" value="<?php echo (!$pmt_method== null)? $pmt_method->getId():"";?>">
		</div>
		

<a style="color: #0080ff;" href="javascript:;"
	onclick="showJqueryDialog('Select Payment Method','500','450', '/application/pmt-method/select','j_loaded_data', true);">Select&nbsp;&nbsp;<i class="glyphicon glyphicon-folder-open"></i>
</a>		
	</div>
	
	<div class="form-group">
		<label class="control-label col-sm-2" >Lead time</label>
		<div class="col-sm-3">
			<input  class="form-control" type="text" placeholder=""
				name="lead_time" value="<?php echo (!$entity == null)? $entity->getLeadTime():"";?>">
		
		</div>
		
	</div>
	
	<div class="form-group">
		
		<label class="control-label col-sm-2" >Remarks</label>
		<div class="col-sm-3">
			<textarea  class="form-control" type="text" rows="4" placeholder=""
				name="remarks" style="font-size: 9pt;"><?php echo (!$entity == null)? $entity->getRemarks():"";?></textarea>
		</div>
		<label class="control-label col-sm-2" for="inputTag">Attachment</label>
		<div class="col-sm-3">
			<input style=";" type="file" id = "attachments" name="attachments" />
		</div>		
	</div>
	
	<div class="form-group">
		<label class="control-label col-sm-2" for="inputTag"></label>
		<div class="col-sm-3">
	   	<button type="submit" id = "save" class="btn btn-default"><i class="glyphicon glyphicon-save"> </i> Save</button>
  		</div>
	</div> 
		
	
</form>
</div>
</div>

<script>

$('#attachments').bind('change', function() {
	var file_size;
	file_size = this.files[0].size
	if (file_size > 2097152){
		alert('This file size is too large : ' + file_size + "MB. Please select new file");

		 $("#attachments").val("");
		 	
	}else{
		//alert('This file size is: ' + file_size + "MB, OKE");
		 //$('#save').removeAttr('disabled');
	}

});

$('#vendor_item_unit').bind('change', function() {
	//alert($('#vendor_item_unit').val());
	$('#conversion_text').html($('#vendor_item_unit').val() + ' = ' + $('#conversion_factor').val() );
});

$('#conversion_factor').bind('change', function() {
	//alert($('#vendor_item_unit').val());
	$('#conversion_text').html($('#vendor_item_unit').val() + ' = ' + $('#conversion_factor').val() );
});

$(function() {
   $( "input[id='valid_from']").datepicker({ firstDay: 1, dateFormat: 'yy-mm-dd',closeText: 'X'});
    $( "input[id='valid_to']").datepicker({ firstDay: 1, dateFormat: 'yy-mm-dd',closeText: 'X'});
});

</script>


<!-- Modal -->
<div class="modal" id="modal1" role="dialog">
	<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal">&times;</button>
				<span class="modal-title" id="modal_title" style="font-weight: bold;">Mascot International Laos</span>
			</div>
			<div class="modal-body">
				<div id="b_loaded_data">loading</div>
			</div>
			<div class="modal-footer">
				<span id="node_selected">No thing selected</span>&nbsp;&nbsp;
				<button type="button" class="btn btn-default" data-dismiss="modal">Confirm</button>
			</div>
		</div>
	</div>
</div>


<div id="jquery_dialog" style="display: none; padding-top: 10pt">
	<div id="j_loaded_data"></div>
</div>



