
<div id="tabs" style="font-size: 9.5pt">

	<ul>
		<li><a href="#general"><?php echo $this->translate('Inventory Setting'); ?></a></li>
	</ul>
<div id="general" style="font-size: 9pt">
	
	
<div class="row">
  <div class="col-xs-6 col-md-3">
  <div class="list-group" style="">
  	<a class="list-group-item" href="/inventory/opening-balance/list"><?php echo $this->translate('Opening Balance'); ?></a>
  	<a class="list-group-item" href="/inventory/item-group/list"><?php echo $this->translate('Item Group'); ?></a>
  	<a class="list-group-item" href="/inventory/serial-number/list"><?php echo $this->translate('Serial Number'); ?></a>
  	<a class="list-group-item" href="/inventory/batch-number/list"><?php echo $this->translate('Batch Number'); ?></a>
  	<a class="list-group-item" href="/inventory/warehouse/list"><?php echo $this->translate('Warehouse'); ?></a>

	</div>
 </div>

  <div class="col-xs-12 col-sm-6 col-md-9" style=""><h3><?php echo $this->translate('Inventory Setting'); ?></h3></div>
</div>
	
	
	
</div>
</div>