
<div id="tabs" style="font-size: 9.5pt">

	<ul>
		<li><a href="#general"><?php echo $this->translate('Inventory Setting'); ?></a></li>
	</ul>
<div id="general" style="font-size: 9pt">
	
	
<div class="row">
  <div class="col-xs-6 col-md-3">
  <div class="list-group" style="">
  	<a class="list-group-item" href="/inventory/opening-balance/list"><?php echo $this->translate('Opening Balance'); ?></a>
  	<a class="list-group-item" href="/hr/leave-reason/list"><?php echo $this->translate('Accounting'); ?></a>
	<a class="list-group-item" href="/hr/minimum-wage/index"><?php echo $this->translate('Minimum Wage'); ?></a>
	<a class="list-group-item" href="/hr/sso/index"><?php echo $this->translate('Social Security (SSO)'); ?></a>
	</div>
  </div>

  <div class="col-xs-12 col-sm-6 col-md-9" style=""><h3><?php echo $this->translate('Inventory Setting'); ?></h3></div>
</div>
	
	
	
</div>
</div>