<?php
namespace Inventory\Domain\Transaction\GI;

use Application\Application\Event\DefaultParameter;
use Application\Domain\Shared\Command\CommandOptions;
use Inventory\Domain\Contracts\AutoGeneratedDocInterface;
use Inventory\Domain\Event\Transaction\GI\WhGiPosted;
use Inventory\Domain\Service\SharedService;
use Inventory\Domain\Transaction\AbstractGoodsIssue;
use Inventory\Domain\Transaction\Contracts\GoodsReceiptInterface;
use Inventory\Domain\Transaction\Contracts\TrxFlow;
use Inventory\Domain\Transaction\Contracts\TrxType;
use Inventory\Domain\Transaction\Validator\ValidatorFactory;
use Procure\Domain\GoodsReceipt\GRRow;
use Procure\Domain\GoodsReceipt\GenericGR;
use Procure\Domain\Shared\ProcureDocStatus;
use Webmozart\Assert\Assert;

/**
 *
 * @author Nguyen Mau Tri - ngmautri@gmail.com
 *
 */
class GIFromPurchasingReversal extends AbstractGoodsIssue implements GoodsReceiptInterface, AutoGeneratedDocInterface
{

    /**
     *
     * {@inheritdoc}
     * @see \Inventory\Domain\Transaction\GenericTrx::specify()
     */
    public function specify()
    {
        $this->movementType = TrxType::GI_FOR_PURCHASING_REVERSAL;
        $this->movementFlow = TrxFlow::WH_TRANSACTION_OUT;
    }

    /**
     *
     * @param GenericGR $sourceObj
     * @param CommandOptions $options
     * @param SharedService $sharedService
     * @throws \InvalidArgumentException
     * @throws \RuntimeException
     * @return \Inventory\Domain\Transaction\GI\GIFromPurchasingReversal
     */
    public static function postCopyFromProcureGRReversal(GenericGR $sourceObj, CommandOptions $options, SharedService $sharedService)
    {
        Assert::isInstanceOf($sourceObj, GenericGR::class, sprintf("GRDoc Entity is required %s"));
        Assert::eq($sourceObj->getDocStatus(), ProcureDocStatus::REVERSED, sprintf("PO GR is not reversed %s", $sourceObj->getId()));

        $rows = $sourceObj->getDocRows();
        Assert::notNull($rows, "GRDoc Entity is empty!");

        Assert::notNull($options, "Options not founds");
        Assert::notNull($sharedService, "Shared service not founds");

        /**
         *
         * @var GIFromPurchasingReversal $instance
         */
        $instance = new self();
        $instance = $sourceObj->convertTo($instance);

        // overwrite.
        $instance->specify(); // important.
        $instance->setMovementDate($sourceObj->getPostingDate());

        $createdBy = $options->getUserId();
        $instance->setBaseDocId($sourceObj->getId());
        $instance->setBaseDocType($sourceObj->getDocType());

        $instance->initDoc($options);
        $instance->markAsPosted($createdBy, $sourceObj->getPostingDate());
        $instance->setRemarks($instance->getRemarks() . \sprintf('[Auto.] Ref.%s', $sourceObj->getSysNumber()));

        foreach ($rows as $r) {

            /**
             *
             * @var GRRow $r ;
             */

            if (! $r->getIsInventoryItem()) {
                continue;
            }

            $grRow = GIFromPurchasingReversalRow::createFromPurchaseGrRowReversal($instance, $r, $options);
            $grRow->markRowAsPosted($instance, $options);

            // caculate COGS
            $valuattionSrv = $sharedService->getValuationService()->getFifoService();
            $cogs = $valuattionSrv->calculateCOGS($instance, $grRow);
            $grRow->setCalculatedCost($cogs);

            $instance->addRow($grRow);
        }

        $validationService = ValidatorFactory::create($instance->getMovementType(), $sharedService);
        $instance->validate($validationService);

        if ($instance->hasErrors()) {
            throw new \RuntimeException($instance->getErrorMessage());
        }

        $instance->clearEvents();

        $rep = $sharedService->getPostingService()->getCmdRepository();
        $snapshot = $rep->post($instance, true);

        $target = $instance;
        $defaultParams = new DefaultParameter();
        $defaultParams->setTargetId($snapshot->getId());
        $defaultParams->setTargetToken($snapshot->getToken());
        $defaultParams->setTargetDocVersion($snapshot->getDocVersion());
        $defaultParams->setTargetRrevisionNo($snapshot->getRevisionNo());
        $defaultParams->setTriggeredBy($options->getTriggeredBy());
        $defaultParams->setUserId($options->getUserId());
        $params = null;

        $event = new WhGiPosted($target, $defaultParams, $params);

        $instance->addEvent($event);
        $instance->updateIdentityFrom($snapshot);

        return $instance;
    }
}