<?php

/**@var \Application\Entity\NmtInventoryOpeningBalance $target ;
 @var \Application\Entity\NmtInventoryOpeningBalanceRow $entity ; */
?>


<div id="wrapper" class="toggled">

	<!-- Sidebar -->
	<div id="sidebar-wrapper" style="font-size: 9.5pt;">
					<?php
    $current_step = "STEP2";
    include (ROOT . '/module/Inventory/view/inventory/ob-create-wizard.php');
    ?>


	</div>
	<!-- /#sidebar-wrapper -->

	<!-- Page Content -->
	<div id="page-content-wrapper"
		style="font-size: 9.5pt; padding: 0px; margin: 0px;">
		<div class="container-fluid" id="main_container"
			style="font-size: 9.5pt; padding: 1px; margin: 0px;";>
			<a style="font-size: 9pt; margin: 2px; padding: 3px;"
				href="#menu-toggle" class="btn btn-primary btn-sm" id="menu-toggle"><span
				title="Hide Menu"><i class="fa fa-chevron-left" aria-hidden="true"></i>
					Menu <span></a>


			<div id="tabs" style="font-size: 10pt">
				<ul>
					<li><a href="#general">New Open Balance:</a></li>
				</ul>

				<div id="general" style="font-size: 9pt">
					<!-- Tab1 -->
	
	
	<?php
if (count($errors) > 0) {
    echo '<div class="alert alert-danger alert-dismissible"" role="alert" style="font-size: 9.5pt"><a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>[ERROR]';

    echo '<ul>';
    foreach ($errors as $error) :
        echo '<li>' . $error . '</li>';
    endforeach
    ;
    echo '</ul>';
    echo '</div>';
}
?>
<form id="New_Invoice_Row" class="form-horizontal"
						action="<?php echo $this->baseUrl ?>/inventory/opening-balance-row/add"
						method="post" enctype="multipart/form-data">
						<input type="hidden" name="redirectUrl"
							value="<?php echo $redirectUrl ?>" /> <input type="hidden"
							id="target_id" name="target_id"
							value="<?php if (!$target == null): echo $target->getId();endif;?>" />
						<input type="hidden" id="token" name="token"
							value="<?php if (!$target == null): echo $target->getToken();endif;?>" />


						<fieldset>
							<legend style="font-size: 9pt; color: gray;">
								<small><span class="glyphicon glyphicon-triangle-right"></span></small>&nbsp;
								<a style="font-size: 9pt; color: gray;" href="#new_row" class=""
									data-toggle="collapse">NEW ROW:</a>
							</legend>
							<div id="new_row" class="collapse in">
								<div class="form-group margin-bottom">
									<label class="control-label col-sm-2"></label>
									<div class="col-sm-3">
										<input
											<?php if(!$entity== null): echo ($entity->getIsActive()=="1")?"checked":""; else: echo "checked"; endif;?>
											type="checkbox" name="isActive" value="1">&nbsp;Is
										Active&nbsp;&nbsp;&nbsp;&nbsp;
									</div>
								</div>
								<div class="form-group margin-bottom  required">
									<label class="control-label col-sm-2">Item: </label>
									<div class="col-sm-3">
										<input tabindex="2" class="form-control" type="text"
											id="item_name" placeholder="Enter keyword to search item..."
											name="item_name"
											value="<?php if (!$entity== null): if($entity->getItem()!==null): echo $entity->getItem()->getItemName(); endif;endif;?>">


										<input type="hidden" id="item_id" placeholder=""
											name="item_id"
											value="<?php if (!$entity== null): if($entity->getItem()!==null): echo $entity->getItem()->getID(); endif;endif;?>">

									</div>

									<div id="item_url" style="display: none;"></div>

									<div class="col-sm-2">
										<a style="color: #0080ff;" href="javascript:;"
											onclick="showJqueryDialog('Select Item','1280',$(window).height()-80, '/inventory/item-search/do1?target_id=item_id&target_name=item_name','j_loaded_data', true);">Select&nbsp;&nbsp;<i
											class="glyphicon glyphicon-folder-open"></i>
										</a>


									</div>

									<div class="col-sm-2">
										<a target="_blank" style="font-size: 9pt;"
											href="/inventory/item/list">Item List&nbsp;&nbsp;</a><small><i
											class="glyphicon glyphicon-new-window"></i></small>
									</div>

									<div id="item_detail">
										&nbsp;&nbsp;<a title="Item Detail" href="javascript:;"
											onclick="showSelectedItem();"><i style="color: navy"
											class="fa fa-info-circle fa-lg" aria-hidden="true"></i></a> <br>&nbsp;
									</div>
								</div>
								<div class="form-group margin-bottom required">
									<label class="control-label col-sm-2" for="inputTag">Quantity:</label>
									<div class="col-sm-3">
										<input tabindex="6" class="form-control input-sm" type="text"
											id="quantity" name="quantity"
											value="<?php echo (!$entity == null)? $entity->getQuantity():"";?>">
									</div>
								</div>

								<div class="form-group margin-bottom required">
									<label class="control-label col-sm-2" for="inputTag">Unit
										Price:</label>
									<div class="col-sm-3">
										<input tabindex="6" class="form-control input-sm" type="text"
											id="unitPrice" name="unitPrice"
											value="<?php echo (!$entity == null)? $entity->getUnitPrice():"";?>">
									</div>

									<label class="control-label col-sm-2" for="inputTag">Total
										Value:</label>
									<div class="col-sm-3">
										<input tabindex="6" class="form-control input-sm" type="text"
											id="totalValue" name="totalValue"
											value="<?php echo (!$entity == null)? $entity->getNetAmount():"";?>">
									</div>
								</div>

								<div class="form-group margin-bottom">
									<label class="control-label col-sm-2">Remark:</label>
									<div class="col-sm-8">
										<input tabindex="9" class="form-control input-sm" type="text"
											placeholder="" name="remarks"
											value="<?php echo (!$entity == null)? $entity->getRemarks():"";?>">
									</div>
								</div>

								<div class="form-group margin-bottom">
									<label class="control-label col-sm-2" for="inputTag"></label>
									<div class="col-sm-3">
										<a tabindex="10" class="btn btn-default btn-sm"
											onclick="submitForm('New_Invoice_Row');" href="javascript:;"><small><i
												class="glyphicon glyphicon-floppy-disk"></i></small>&nbsp;Save</a>
										<a tabindex="11" class="btn btn-default btn-sm"
											href="<?php echo $this->baseUrl ?>/inventory/opening-balance/list"><small><i
												class="glyphicon glyphicon-remove"></i></small>&nbsp;Cancel</a>

									</div>
								</div>

							</div>
						</fieldset>
					</form>



					<!-- end tab -->
				</div>
			</div>
		</div>
		<!-- /#page-content-wrapper -->

	</div>
	<!-- /#wrapper -->

	<script type="text/javascript">

    $( "#item_name" ).autocomplete({
        source: "/inventory/item-search/auto-complete",
        minLength: 2,
        select: function( event, ui ) {
      	  $( "#item_id" ).val(ui.item.id);

      	   $('#item_url').text('/inventory/item/show1?tab_idx=7&entity_id='+ui.item.id+'&token='+ui.item.token);
            //alert('/inventory/item/show1?tab_idx=7&entity_id='+ui.item.id+'&token='+ui.item.token);
        
      	 	$('#global-notice').show();
      		$('#global-notice').html('"' + ui.item.value + '" selected');
      		$('#global-notice').fadeOut(5000);
      		//$("#jquery_dialog").dialog("close");
        }
       
      })
      .autocomplete( "instance" )._renderItem = function( ul, item ) {
    	  var serial_no = "";
    	  if(item.item_serial!=""){
    		  serial_no = " : " + item.item_serial;
    	  }
    	   
         return $( "<li>" )
           .append( "<div style='padding-bottom: 5px; border-bottom: thin solid gray;'><span style='font-size: 9.5pt;font-weight: bold;'>" + item.value + "</span><br><span style='color:gray;font-size: 9pt;'>" + item.item_sku + serial_no +"<span></div>" )
           .appendTo( ul );
       };

    $('#quantity').bind('change', function() {
         });

     function showSelectedItem(){
    	//var url= '/inventory/item/show1?tab_idx=7&entity_id=<?php echo $target->getId();?>&token=<?php echo $target->getToken();?>';
		var url= $('#item_url').text(); 
		alert(url);
    	
       	showJqueryDialog('Item Detail','1350',$(window).height()-40, url,'j_loaded_data', true);
    }

 </script>