<?php
if (count($rows) == 0) :
    ?>
<h5>no thing found!</h5>
<?php

else :
    ?>
<h4 style="color: graytext;"><?php

    echo $this->translate("Quotation");
    ?>:</h4>
<table style="font-size: 9pt;" class="table table-bordered table-hover">
   <thead>
      <tr>
         <td>
            <b>#</b>
         </td>
         <td>
            <b>QO No.</b>
         </td>
         <td>
            <b>Vendor</b>
         </td>
         <td>
            <b>QO Date</b>
         </td>
         <td>
            <b><?php

    echo $this->translate("Item Name");
    ?></b>
         </td>
         <td>
            <b>Unit</b>
         </td>
         <td>
            <b>Q'ty</b>
         </td>
         <td>
            <b>UP Price</b>
         </td>
         <td>
            <b>Total</b>
         </td>
         <td>
            <b>Currency</b>
         </td>
         <td>
            <b>EX</b>
         </td>
         <td>
            <b>local UP</b>
         </td>
         <td>
            <b>Local Total</b>
         </td>
         <td>
            <b>Status</b>
         </td>
         <td>
            <b>Action</b>
         </td>
      </tr>
   </thead>
   <tbody>
 
	 <?php

    $count = 0;
    // $total_ordered = 0;
    // $total_received = 0;
    // $total_balance = 0;
    foreach ($rows as $r) :
        $count ++;
        /**@var \Application\Entity\NmtProcureQoRow $a ;*/
        $a = $r[0];

        ?>
	 <tr>
         <td><?php

        echo $count;
        ?></td>
         <td>
            <a href="/procure/qr/view?entity_id=<?php

        echo $a->getQo()->getId();
        ?>&entity_token=<?php

        echo $a->getQo()->getToken();
        ?>" target="_blank"><?php

        echo $this->escapeHtml($a->getQo()
            ->getSysNumber());
        ?></a>
         </td>
         <td><?php

        if (! $a->getQo() == null) :
            if ($a->getQo()->getVendor() !== null) :
                echo $a->getQo()
                    ->getVendor()
                    ->getVendorName();endif;endif;


        ?> </td>
         <td><?php

        if (! $a->getQo()->getContractDate() == null) :
            echo date_format($a->getQo()->getContractDate(), "d/m/y");endif;

        ?> </td>
         <td><?php

        echo $a->getVendorItemCode();
        ?></td>
         <td><?php

        echo $a->getItem()
            ->getStandardUom()
            ->getUomCode();
        ?></td>
         <td><?php

        echo $a->getQuantity();
        ?></td>
         <td><?php

        echo number_format($a->getUnitPrice(), 2);
        ?></td>
         <td><?php

        echo number_format($a->getUnitPrice() * $a->getQuantity(), 2);
        ?></td>
         <td><?php

        echo $a->getQo()
            ->getCurrency()
            ->getCurrency();
        ?></td>
         <td><?php

        echo number_format($a->getQo()->getExchangeRate(), 2);
        ?></td>
         <td><?php

        echo number_format($a->getQo()->getExchangeRate() * $a->getUnitPrice(), 2);
        ?></td>
         <td><?php

        echo number_format($a->getQo()->getExchangeRate() * $a->getUnitPrice() * $a->getQuantity(), 2);
        ?></td>
         <td></td>
         <td></td>
      </tr>
<?php
    endforeach
    ;
    ?>

 </tbody>
</table>
<script type="text/javascript">
</script>
<?php

endif;
?>
	
