<h4>Create New Department:</h4>
<hr>

<?php if (count($errors)>0)
{
echo '<div class="alert alert-error">';
	
	echo '<ul>';
	 foreach ($errors as $error) :
	 echo '<li>'.$error . '</li>';
	 
	 endforeach;
	 echo '</ul>';
	 echo '</div>';
} 
?>
	

 <form class="form-horizontal" action="<?php echo $this->baseUrl ?>/application/department/add"	method="post" enctype="multipart/form-data" id="NewSP" >
  <input type="hidden" name="redirectUrl" value="<?php echo $redirectUrl ?>" />
      <div class="control-group">
        <label class="control-label" for="inputTag">Name</label>
        <div class="controls">
          <input type="text" id="inputTag" placeholder="" name="name" value="<?php echo $department!==null ? ($department->name) :""?>">
        </div>
      </div>
       <div class="control-group">
        <label class="control-label" for="inputTag">Short Name</label>
        <div class="controls">
          <input type="text" id="inputTag" placeholder="" name="short-name" value="<?php echo $department!==null ? ($department->short_name) :""?>">
        </div>
      </div>
      <div class="control-group">
        <label class="control-label" for="inputDescription">Description</label>
        <div class="controls">
          <textarea id="inputDescription" placeholder="" rows="2" name="description"><?php echo $department!==null ? ($department->description):""?></textarea>
        </div>
      </div>
      
      
      
      <div class="control-group">
        <label class="control-label" for="inputTag">Status</label>
        <div class="controls">
        	<select name="status" >
        		<option selected = "selected" value="Activated">Activated</option>
        		<option value="Deactivated">Deactivated</option>
     			</select>
       </div>
      </div>
      
      
      <div class="control-group">
        <div class="controls">
             <button type="submit" class="btn"><i class="icon-plus">  </i> Create</button>
        </div>
      </div>
    </form>



<div id = "dialog" style="display: none;">Check code...</div>