<?php
use Application\Application\Helper\OptionList;

$depmartment_option = OptionList::createDeptOption($departmentForOption, "");
?>
<div id="tabs" style="font-size: 9.5pt">
   <ul>
      <li>
         <a href="#general"><?php

        echo $this->translate('Department');
        ?>















      </li>
   </ul>
   <div id="general">
      <a class="btn btn-default btn-sm" href="<?php

    echo $this->baseUrl?>/application/department/create">
         <small>
            <i class="glyphicon glyphicon-plus"> </i>
         </small>&nbsp;<?php

        echo $this->translate('Add Department');
        ?></a>
      <!--
   <ul class="nav nav-pills">
   <li><a style="color: #0080ff;" href="<?php

echo $this->baseUrl?>/application/department/create"><i class="glyphicon glyphicon-plus"> </i><?php

echo $this->translate('Add Department');
?></a></li>
   <li><a style="color: #0080ff;" href="javascript:;"
   onclick="showBootstrapDialog('Country List','/application/department/list1','loaded_data');"> <i class="glyphicon glyphicon-list">  </i> Test Ajax List
</a>

</ul>
 -->
      <hr>
      <div style="font-size: 10pt" id="html02" class="demo">
         <h5>Department in dropdown view</h5>
         <select tabindex="9" name="department" id="deparment_id" class="chosen-select">
<?php
// ================
echo $depmartment_option;
// ================
?>
       </select>
      </div>
      <hr>
      <h5>Department in tree view</h5>
      <div style="font-size: 10pt" id="html1" class="demo">
         <ul>
	<?php

echo $jsTree?>;
</ul>
      </div>
      <hr>
      <hr>
      <h5>Department in orgigramm</h5>
      <div style="font-size: 10pt" class="tree">
         <ul>
   <?php
echo $departmentForOrnigramm;
?>;

      </ul>
      </div>

      <hr>
      <!--  -->
      <div>
         <div class="tree">
            <ul>
               <li>
                  <a href="#">
                     Nguyen Mau Tri
                     <br />
                     Nico Simanjuntak
                     <br />
                     Technician
                  </a>
                  <ul>
                     <li>
                        <a href="#">
                           IT Support
                           <br />
                           Nico Simanjuntak
                           <br />
                           Technician
                        </a>
                     </li>
                     <li>
                        <a href="#">
                           IT Support
                           <br />
                           Nico Simanjuntak
                           <br />
                           Technician
                        </a>
                     </li>
                     <li>
                        <a href="#">
                           IT Support
                           <br />
                           Nico Simanjuntak
                           <br />
                           Technician
                        </a>
                     </li>
                  </ul>
               </li>
            </ul>
         </div>
      </div>
   </div>
</div>
<div class="modal" id="confirm_remove_node" role="dialog">
   <div class="modal-dialog modal-md">
      <div class="modal-content">
         <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal">&times;</button>
         </div>
         <div class="modal-body" id="b_modal_sm_body">
            <h5>#<?php

            echo $this->translate('Department will be removed!');
            ?></h5>
            <div class="alert alert-warning">
               <strong>[Info]</strong> <?php

            echo $this->translate('Remove can not be recalled!');
            ?>
               <!-- Journal Entry will be created. <br>- Warehouse Journal will be
               created.
                -->
            </div>
            <p><?php

            echo $this->translate('Do you want to continue?');
            ?></p>
         </div>
         <div class="modal-footer">
            <button onclick="doRemovingNode();" type="button" class="btn btn-primary btn-sm">YES</button>
            <button type="button" class="btn btn-default btn-sm" data-dismiss="modal">Cancel</button>
         </div>
      </div>
   </div>
</div>
<script>

var node_name_to_remove = null;

function confirmRemoveNode() {
    $('#confirm_remove_node').modal();
 }

function doRemovingNode() {

    $('#confirm_remove_node').hide();

  //alert(data.node.parent +  data.node.id  +  data.node.text );
    $('#b_modal_no_header').modal();

    var redirectUrl = "/application/department/list2";

    $.post("/application/department/remove", {
        node_name : node_name_to_remove,

    }, function(data, status) {
       //alert(data);
       window.location = redirectUrl;
    });
}


// html demo
	$('#html1').jstree({
		"core" : {
		       // so that create works
		       "check_callback" : true
		     },
		    "plugins" : [ "contextmenu" ],

		    "contextmenu":{
		        "items": function($node) {
		            var tree = $("#html1").jstree(true);
		            return {

		        	 "Add New Deparment": {
			                    "separator_before": false,
			                    "separator_after": false,
			                    "label": "Add New Deparment",
			                    "action": function (obj) {
			                    	var redirectUrl = "/application/department/create?p="+$node.id;
			                    	window.location = redirectUrl;
			                   }
			                },


			                'Move Deparment': {
			                    "separator_before": false,
			                    "separator_after": false,
			                    "label": "Move Deparment",
			                    "action": function (obj) {
			                    	var redirectUrl = "/application/department/move?n="+$node.id;
			                    	window.location = redirectUrl;
			                   }
			                },


		                /* "Create": {
		                    "separator_before": false,
		                    "separator_after": false,
		                    "label": "Create New Deparment",
		                    "action": function (obj) {
		                    	var ref = $.jstree.reference(obj.reference);
                                sel = ref.get_selected();
        	                    $node = tree.create_node($node);
			                    tree.edit($node);
		                    }
		                }, */

		                "Rename": {
		                    "separator_before": false,
		                    "separator_after": false,
		                    "label": "Rename Deparment",
		                    "action": function (obj) {
		                        tree.edit($node);
		                    }
		                },
		                "Remove": {
		                    "separator_before": false,
		                    "separator_after": false,
		                    "label": "Remove Deparment",
		                    "action": function (obj) {
		                        tree.delete_node($node);
		                    }
		                },



		            };
		        }
		    }

    });

	// When the jsTree is ready, add two more records.
	$('#html1').on('create_node.jstree', function (e, data) {
		alert(data.node.parent +  data.node.id);
	});

   // RENAME
	$('#html1').on('rename_node.jstree', function (e, data) {
         //alert(data.node.parent +  data.node.id  +  data.node.text );
           $('#b_modal_no_header').modal();

           var redirectUrl = "/application/department/list2";

           $.post("/application/department/rename", {
               node_name : data.node.id,
               new_name : data.node.text,
           }, function(data, status) {
              //alert(data);
              window.location = redirectUrl;
           });

    });
	// RENAME ===============


    // DELETE ===============
    $('#html1').on('delete_node.jstree', function (e, data) {

	     $('#confirm_remove_node').modal();

	     node_name_to_remove = data.node.id;


    });
   // DELETE ===============


	$("#html1").on("click", ".jstree-anchor", function(e) {
		   var node = $("#html1").jstree(true).get_node($(this));

		   var id = $("#html1").jstree(true).get_node($(this)).id;
		   var cat_name = $("#html1").jstree(true).get_node($(this)).text;

		   if (!node.state.disabled)
   		   {
		   $("#node_selected").html('"' + cat_name + '" selected');
		   $("#department_name").val(cat_name);
		   $("#department_name_selected").val(id);

			$('#modal1 .close').click();
			$('#global-notice').show();
			$('#global-notice').html('"' + cat_name + '" selected');
			$('#global-notice').fadeOut(3000);
   		   }
	});

</script>
