<?php
use Application\Application\Helper\ErrorMessage;
use Application\Application\Helper\OptionList;

$error_msg = ErrorMessage::showErrorMessage($errors);
$depmartment_option = OptionList::createDeptOption($departmentForOption, "");

?>
<div id="tabs" style="font-size: 9.5pt">
   <ul>
      <li>
         <a href="#general">Create New Department</a>
      </li>
   </ul>
   <div id="general">

   <?php
// ==================
echo $error_msg;
// ==================
?>


		<form class="form-horizontal" action="<?php

echo $form_action;
?>" method="post" enctype="multipart/form-data">
                  <div class="form-group margin-bottom">
            <label class="control-label col-sm-2" for="inputTag">Department Name</label>
            <div class="col-sm-3">
               <input class="form-control input-sm" type="text" id="inputTag" placeholder="" name="departmentName" value="">
            </div>
         </div>
         <div class="form-group margin-bottom">
            <label class="control-label col-sm-2 input-sm" for="inputTag">Parent Deparment: </label>
            <div class="col-sm-3">
               <select name="parentName" id="parent_id" class="chosen-select">
<?php
// ================
echo $depmartment_option;
// ================
?>
       </select>
            </div>
         </div>
         <div class="form-group margin-bottom">
            <label class="control-label col-sm-2" for="inputDescription">remarks</label>
            <div class="col-sm-3">
               <textarea class="form-control input-sm" id="inputDescription" placeholder="" rows="2" name="remarks"></textarea>
            </div>
         </div>
         <div class="form-group margin-bottom">
            <label class="control-label col-sm-2" for="inputTag">Status</label>
            <div class="col-sm-3">
               <select class="form-control input-sm chosen-select" name="parent">
                  <option selected="selected" value="Activated">Activated</option>
                  <option value="Deactivated">Deactivated</option>
               </select>
            </div>
         </div>
         <div class="form-group">
            <div class="col-sm-offset-2 col-sm-10">
               <button type="submit" class="btn btn-default">Submit</button>
            </div>
         </div>
      </form>
   </div>
</div>
