<?php
use Application\Application\Helper\ErrorMessage;
use Application\Application\Service\Department\Tree\DepartmentNode;
use Application\Form\Contracts\GenericForm;
use Application\Form\Deparment\DepartmentFormRender;

/**
 *
 * @var GenericForm $form ;
 * @var DepartmentNode $departmentNode ;
 */
$error_msg = ErrorMessage::showErrorMessage($errors);
?>
<div id="tabs" style="font-size: 9.5pt">
   <ul>
      <li>
         <a href="#general">Create New Department</a>
      </li>
   </ul>
   <div id="general">

        <?php
        // ==================
        echo $error_msg;
        echo $form->renderForView($this, new DepartmentFormRender());
        ?>

   </div>
</div>
