<div id="tabs" style="font-size: 9.5pt"> 
  <ul>
  <li ><a href="#picture_manager">Picture Management</a></li>
  
  </ul>
 
 
 <div id="picture_manager">


<?php if( count($brokenFile)>0): ?>


<table style="font-size: 10pt;" class="table table-bordered table-hover">
	<thead>
		<tr>
			<td><b>#</b></td>
			<td><b>Item</b></td>
			<td><b>Action</b></td>
		</tr>
	</thead>

	<tbody>
		


	<?php 
	$n=1;
	foreach ($brokenFile as $pic) : ?>
	
	<?php /** @var Application\Entity\NmtApplicationAttachment $pic ;*/?>
	
	<tr>
	<td><?php echo $n++;?> </td>
	<td><?php echo $pic->getId(); ?></td>
	
	<td>
	</td>
	</tr>
	<?php endforeach; ?>

	

	</tbody>
	
</table>
</div>
 </div> 
<?php else:?>
No record found!
<?php endif; ?>


