<h3>Settings</h3>

<ul style="font-size: 10pt" id="menu">
	<li><a href="<?php echo $this->baseUrl ?>/application/country">Country</a></li>
	<li><a href="<?php echo $this->baseUrl ?>/application/currency">Currency</a></li>
	<li><a href="<?php echo $this->baseUrl ?>/application/uom">Units or Measurements</a></li>
	<li><a href="<?php echo $this->baseUrl ?>/application/pmt-method">Payment Method</a></li>
	<li><a href="#">------</a></li>

	<li><a href="<?php echo $this->baseUrl ?>/application/company">Company</a></li>
	<li><a href="<?php echo $this->baseUrl ?>/application/department">Department</a></li>
	
	<li><a href="#">------</a></li>
	
	<li><a href="<?php echo $this->baseUrl ?>/application/acl">ACL</a></li>
	<li><a href="#">------</a></li>
	<li><a href="<?php echo $this->baseUrl ?>/application/item-category">Item Category</a></li>
	<li><a href="<?php echo $this->baseUrl ?>/inventory/search">Item Search Index</a></li>
	
	<li><a href="#">------</a></li>
	<li><a href="<?php echo $this->baseUrl ?>/application/pdf/test">Test PDF</a></li>
	<li><a href="<?php echo $this->baseUrl ?>/application/excel/test">Test Excel</a></li>
	
	<li><a href="#">------</a></li>
	<li><a href="<?php echo $this->baseUrl ?>/application/search/index">Search Indexes Manager</a></li>
		<li><a href="#">------</a></li>
	
	<li><a href="<?php echo $this->baseUrl ?>/calendar">Calendar</a></li>
	<li><a href="<?php echo $this->baseUrl ?>/workflow/wf/list">List Workflow</a></li>
	<li><a href="#">------</a></li>
	<li><a href="<?php echo $this->baseUrl ?>/application/index/info" target="blank">System info</a></li>
	
</ul>


