<h3>Welcome</h3>

<hr>
<ul id="menu">
	<li><a href="<?php echo $this->baseUrl ?>/application/country">Country Manager</a></li>
	<li><a href="<?php echo $this->baseUrl ?>/application/currency">Currency Manager</a></li>
	<li><a href="<?php echo $this->baseUrl ?>/application/uom">Units or Measurements</a></li>
	<li><a href="<?php echo $this->baseUrl ?>/application/pmt-method">Payment Method</a></li>
	<li><a href="#">------</a></li>

	<li><a href="<?php echo $this->baseUrl ?>/application/company">Company Manager</a></li>
	<li><a href="<?php echo $this->baseUrl ?>/application/department">Department Manager</a></li>
	
	<li><a href="#">------</a></li>
	
	<li><a href="<?php echo $this->baseUrl ?>/application/acl">ACL</a></li>
	<li><a href="#">------</a></li>
	<li><a href="<?php echo $this->baseUrl ?>/application/item-category">Item Category</a></li>
	<li><a href="#">------</a></li>
	<li><a href="<?php echo $this->baseUrl ?>/application/pdf/test">Test PDF</a></li>
	<li><a href="<?php echo $this->baseUrl ?>/application/excel/test">Test Excel</a></li>
	
	<li><a href="#">------</a></li>
	<li><a href="<?php echo $this->baseUrl ?>/application/search/index">Search Indexes Manager</a></li>
		<li><a href="#">------</a></li>
	
	<li><a href="<?php echo $this->baseUrl ?>/calendar">Calendar</a></li>
	<li><a href="<?php echo $this->baseUrl ?>/workflow/wf/list">List Workflow</a></li>
</ul>


