<?php

/** @var \Application\Entity\NmtInventoryItem $target ;
 @var \Application\Entity\NmtInventoryItemPicture $entity ;  
 
 */
?>

<div>
	<h4>
		<a style="color: navy;"
			href="<?php echo $this->baseUrl ?>/inventory/item/show?token=<?php echo (!$target == null)?$target->getToken():"";?>&entity_id=<?php echo (!$target == null)?$target->getId():"";?>&checksum=<?php echo (!$target == null)?$target->getChecksum():"";?>"><?php echo (!$target == null)?$target->getItemName():"";?></a>

		<span style="color: gray; font-size: 9.5pt"><?php echo (!$target == null)? " (Item No.: " . $target->getSysNumber().")" :"";?></span>
	</h4>
	</h4>
</div>






<?php
if (count($errors) > 0) {
    echo '<div class="alert alert-danger" role="alert" style="font-size: 10.5pt">';
    
    echo '<ul>';
    foreach ($errors as $error) :
        echo '<li>' . $error . '</li>';
    endforeach
    ;
    echo '</ul>';
    echo '</div>';
}
?>

<div id="tabs" style="font-size: 9.5pt">
	<ul>
		<li><a href="#picture_manager">Edit Picture:</a></li>
	</ul>


	<div id="picture_manager">
	
		<img class= "img-rounded" width="180" height="180" src="/inventory/item-picture/thumbnail200?token=<?php if($entity!==null): echo $entity->getToken();endif;?>&entity_id=<?php if($entity!==null): echo $entity->getId();endif;?>&checksum=<?php if($entity!==null): echo $entity->getChecksum();endif;?>"/>
		<span style="color: gray"> <?php echo "Uploaded on". date_format ( $entity->getCreatedOn(), "d/m/y");?> </span>
		<hr>

		<!--UPDATE -->
		<form id="edit_form" class="form-horizontal"
			action="/inventory/item-picture/edit" method="post"
			enctype="multipart/form-data">
			<input type="hidden" name="entity_id"
				value="<?php echo (!$entity== null)? $entity->getId():"";?>" /> <input
				type="hidden" name="token"
				value="<?php echo (!$entity== null)? $entity->getToken():"";?>" /> <input
				type="hidden" name="redirectUrl" value="<?php echo $redirectUrl ?>" />

			<div class="form-group margin-bottom">
				<label class="control-label col-sm-2">Caption:</label>
				<div class="col-sm-3">
					<input class="form-control input-sm" type="text" placeholder=""
						name="documentSubject"
						value="<?php echo (!$entity== null)? $entity->getDocumentSubject():"";?>">

				</div>
				<div class="col-sm-2">
					<input
						<?php if(!$entity == null): echo ($entity->getIsActive()=="1")?"checked":""; else: echo "checked"; endif;?>
						type="checkbox" name="isActive" value="1">&nbsp;Active&nbsp;&nbsp;
						<br>
								<input
						<?php if(!$entity == null): echo ($entity->getMarkedForDeletion()=="1")?"checked":""; else: echo "checked"; endif;?>
						type="checkbox" name="markedForDeletion" value="1">&nbsp;Mark for deletion&nbsp;&nbsp;
						<br><input
						<?php if(!$entity == null): echo ($entity->getVisibility()=="1")?"checked":""; else: echo "checked"; endif;?>
						type="checkbox" name="visibility" value="1">&nbsp;Visiblity&nbsp;&nbsp;
										<br><input
						<?php if(!$entity == null): echo ($entity->getIsDefault()=="1")?"checked":""; else: echo "checked"; endif;?>
						type="checkbox" name="isDefault" value="1">&nbsp;Default&nbsp;&nbsp;
				</div>
			</div>

			<div class="form-group margin-bottom">
				<label class="control-label col-sm-2">Remarks:</label>
				<div class="col-sm-8">
					<input tabindex="9" class="form-control input-sm" type="text"
						placeholder="" name="remarks"
						value="<?php echo (!$entity == null)? $entity->getRemarks():"";?>">
				</div>
			</div>


			<div class="form-group">
				<label class="control-label col-sm-2" for="inputTag"></label>
				<div class="col-sm-3">
					<a class="btn btn-default btn-sm" style="" href="javascript:;"
						onClick="submitForm('edit_form')"><small><i class="glyphicon glyphicon-floppy-disk"> </i></small>&nbsp;Save
					</a> <a class="btn btn-default btn-sm" href="<?php echo $redirectUrl ?>"><i
						class="icon-back"> </i> << Back</a>


				</div>
			</div>


		</form>
	</div>
</div>

