<?php
if ($total_records <= 0) {

    echo 'No Resources found!';
} else {

    if (! is_null($paginator)) {
        echo 'Result ' . $paginator->minInPage . ' to ' . $paginator->maxInPage . ' | ' . $total_records . ' Resources found!';
    } else {
        echo $total_records . ' record found!';
    }

    ?>

<table style="font-size: 10pt" class="table table-bordered table-hover">
	<thead>
		<tr>
			<td><b>Select</b></td>
			<td><b>Unit Code </b></td>
			<td><b>Unit of Measurement</b></td>
		</tr>
	</thead>

	<tbody>
 
	 <?php

    $count = 0;
    foreach ($list as $a) :
        $count ++;
        ?>
	 <tr>
			<td><a href="javascript:;"
				onclick="selectId('<?php echo $this->escapeHtml($a->getId());?>','standard_uom_id','<?php echo $this->escapeHtml($a->getUomCode());?>','standard_uom_name');"><small><i
						class="glyphicon glyphicon-triangle-right"></i></small>&nbsp;Select
			</a></td>
			<td><?php echo $this->escapeHtml($a->getUomCode());?></td>
			<td><?php echo $this->escapeHtml($a->getUomName());?></td>
		</tr>
<?php endforeach; ?>

 </tbody>
</table>

<?php

    // ===============================
    if (! is_null($paginator)) :

        // change it only
        $base = $this->baseUrl . '/application/uom/list';
        $_connector_symbol = '?';

        $last = $base . $_connector_symbol . 'page=' . $paginator->totalPages . '&perPage=' . $paginator->resultsPerPage;
        $first = $base . $_connector_symbol . 'page=1&perPage=' . $paginator->resultsPerPage;

        $p1 = ($paginator->page) - 1;
        $p2 = ($paginator->page) + 1;

        $prev = $base . $_connector_symbol . 'page=' . $p1 . '&perPage=' . $paginator->resultsPerPage;
        $next = $base . $_connector_symbol . 'page=' . $p2 . '&perPage=' . $paginator->resultsPerPage;

        echo '<ul class="pagination pagination-sm">';

        if ($paginator->page != 1 and $paginator->totalPages > 10) {
            echo '<li><a href="' . $first . '"> |< </a></li>';
            echo '<li><a href="' . $prev . '"> < </a></li>';
        }

        for ($i = $paginator->minInPageSet; $i <= $paginator->maxInPageSet; $i ++) {

            $url = $base . $_connector_symbol . 'page=' . $i . '&perPage=' . $paginator->resultsPerPage;

            if ($i == $paginator->page) {
                echo '<li><a class="active" href="#">' . $i . '</a></li>';
            } else {
                echo '<li><a href="' . $url . '"> ' . $i . ' </a></li>';
            }
        }
        if ($paginator->page != $paginator->totalPages and $paginator->totalPages > 10) {
            echo '<li><a href="' . $next . '"> > </a></li>';
            echo '<li><a href="' . $last . '"> >| </a></li>';
        }
        echo '</ul>';
endif;

}
// ===============================
?>


