<?php
/**
 *
 * @author Nguyen Mau Tri - ngmautri@gmail.com
 *         ===================================
 */

// echo $total_records;
use Application\Entity\NmtApplicationUom;
use Procure\Application\Helper\FormHelper;

$message_log_div = "message_log_div";
$table_body = "";
$count = 0;
$n = 0;
$base = $this->baseUrl . "/application/uom/list";

$result_msg = "No record found!";

if (count($list) > 0) {

    $result_msg = sprintf("%s records found!", $total_records);

    if ($paginator !== null) {
        $result_msg = sprintf("Recored %s to %s | %s records found!", $paginator->getMinInPage(), $paginator->getMaxInPage(), $total_records);
    }

    foreach ($list as $item) {

        $n ++;

        if ($paginator !== null) {
            $count = $paginator->getMinInPage() - 1 + $n;
        } else {
            $count = $n;
        }

        /**
         *
         * @var NmtApplicationUom $item ;
         */
        $format = '<a href="/application/uom/update?key=%s">edit</a>';
        $actionUrl = sprintf($format, $item->getUomName());

        $table_body = $table_body . "<tr>";
        $table_body = $table_body . sprintf("<td>%s</td>", $count);
        $table_body = $table_body . sprintf("<td>%s</td>", $item->getUomName());
        $table_body = $table_body . sprintf("<td>%s</td>", $item->getUomCode());
        $table_body = $table_body . sprintf("<td>%s</td>", $item->getSymbol());
        $table_body = $table_body . sprintf("<td>%s</td>", $item->getStatus());
        $table_body = $table_body . sprintf("<td>%s</td>", $actionUrl);
        $table_body = $table_body . "</tr>";
    }
}
?>
<hr>
<ul class="nav nav-pills">
   <li>
      <a style="color: #0080ff;" href="<?php
    echo $this->baseUrl?>/application/uom/add">Add New UoM</a>
   </li>
   <li>
      <a style="color: #0080ff;" href="<?php

    echo $this->baseUrl?>/application/uom/create">Add UoM</a>
   </li>
   <li>
      <a style="color: #0080ff;" href="javascript:;" onclick="showBootstrapDialog('UOM List','/application/uom/list1','loaded_data');">
         <i class="icon-list"> </i>
         Test Ajax List
      </a>
   </li>
</ul>

<table id="mytable26" style="font-size: 9.5pt; color: graytext; font-family: Courier, monospace;" class="table table-bordered table-striped table-hover">
   <thead>
      <tr>
         <td>
            <b>Unit of Measurement</b>
         </td>
         <td>
            <b>Unit Code </b>
         </td>
         <td>
            <b>Description</b>
         </td>
         <td>
            <b>Symbol</b>
         </td>
         <td>
            <b>Status</b>
         </td>
         <td>
            <b>Action</b>
         </td>
      </tr>
   </thead>
   <tbody>
         <?php

        echo $table_body;
        ?>
   </tbody>
</table>
<?php

// ===============================
echo FormHelper::createPaginatorAjax($base, $paginator, "&", $message_log_div);
// ===============================
?>