
<?php
use Application\Application\Helper\ErrorMessage;
use Application\Domain\Company\AccountChart\GenericChart;
use Application\Form\Brand\BrandFormRender;
use Application\Form\Contracts\GenericForm;

/**
 *
 * @var GenericForm $form ;
 *
 * @var GenericChart $rootEntity ;
 */
$error_msg = ErrorMessage::showErrorMessage($errors);
$rootId = null;
if ($rootEntity !== null) {
    $rootId = $rootEntity->getId();
}

?>
<div id="tabs" style="font-size: 9.5pt">
   <ul>
      <li>
         <a href="#general">Create New Brand</a>
      </li>
   </ul>
   <div id="general">

   <?php
// ==================
echo $error_msg;
echo $form->renderForView($this, new BrandFormRender());

?>

<div class="container-fluid">
         <div class="row">
            <div class="col-md-6">
               <div id="gird_div" style="margin: 1px; font-size: 9pt"></div>
            </div>
            <div class="col-md-6"></div>
         </div>
      </div>
      <!-- General -->
   </div>
   <!-- Tab -->
   <div class="modal" id="confirm_remove_node" role="dialog">
      <div class="modal-dialog modal-md">
         <div class="modal-content">
            <div class="modal-header">
               <button type="button" class="close" data-dismiss="modal">&times;</button>
            </div>
            <div class="modal-body" id="b_modal_sm_body">
               <h5>#<?php

            echo $this->translate('Account will be removed!');
            ?></h5>
               <div class="alert alert-warning">
                  <strong>[Info]</strong> <?php

                echo $this->translate('Remove can not be recalled!');
                ?>
               <!-- Journal Entry will be created. <br>- Warehouse Journal will be
               created.
                -->
               </div>
               <p><?php

            echo $this->translate('Do you want to continue?');
            ?></p>
            </div>
            <div class="modal-footer">
               <button onclick="doRemovingNode();" type="button" class="btn btn-primary btn-sm">YES</button>
               <button type="button" class="btn btn-default btn-sm" data-dismiss="modal">Cancel</button>
            </div>
         </div>
      </div>
   </div>
   <script>

