
<div id="tabs" style="font-size: 9.5pt">

	<ul>
		<li><a href="#general"><?php echo $this->translate('HR SETTING'); ?></a></li>
	</ul>
	<div id="general" style="font-size: 9pt">


		<div class="row">
			<div class="col-xs-6 col-md-3">
				<div class="list-group" style="">
					<a class="list-group-item" href="/hr/position/list"><?php echo $this->translate('Position'); ?></a>
					<a class="list-group-item" href="/hr/leave-reason/list"><?php echo $this->translate('Leave Reason'); ?></a>
					<a class="list-group-item" href="/hr/minimum-wage/index"><?php echo $this->translate('Minimum Wage'); ?></a>
					<a class="list-group-item" href="/hr/sso/index"><?php echo $this->translate('Social Security (SSO)'); ?></a>
					<a class="list-group-item" href="/hr/income-setup/index"><?php echo $this->translate('Income Setup'); ?></a>
					<a class="list-group-item" href="/hr/income-decorator/index"><?php echo $this->translate('Income Calculation Method'); ?></a>
					<a class="list-group-item" href="/hr/sso/index"><?php echo $this->translate('Default Allowances Setup'); ?></a>
					<a class="list-group-item" href="/hr/sso/index"><?php echo $this->translate('Default Deduction Setup'); ?></a>
				</div>
			</div>

			<div class="col-xs-12 col-sm-6 col-md-9" style="">
				<h3><?php echo $this->translate('HR SETTING'); ?></h3>
			</div>
		</div>



	</div>
</div>
