<script language="javascript">
			var id_array = [];
</script>
<h4>Deliver Notification:</h4>

 <form class="form-search" action="<?php echo $this->baseUrl ?>/procurement/"	method="get" enctype="multipart/form-data">
      <button type="submit" class="btn"><i class="icon-arrow-left">  </i> Back</button>
</form>
<?php if (count($dn_items)>0):?>
<table class="table table-striped table-bordered">
<thead>
<tr>	
		<td><b>No.</b></td>
		<td><b>PR </b></td>
			<td><b>Item Name</b></td>
		<td><b>Item <br> Unit</b></td>
		<td><b>Ordered <br>Quantity</b></td>
		<td><b>Notified <br>Quantity</b></td>
		<td><b>Balance</b></td>	
		<td><b>EDT</b></td>
		<td><b>Action</b></td>
		
		</tr>
</thead>
<tbody>	
 
  <?php 
	 
	 $count = 0;
	 foreach ($dn_items as $item) : 
	 	 $count++;
	 //echo  ($count % 2 == 1) ? "<tr>" : "<tr class=\"pure-table-odd\">";
	 ?>
	 <tr>
		<td><?php echo $count;?></td>
		<td><?php echo $item->pr_number;?>
		
		<div style="color: gray; font-size: 8pt;">
				<a style="color: black; font-size: 8pt;" href="<?php echo $this->baseUrl ?>/procurement/pr/show?pr_id=<?php echo $item->pr_id;?>"
				target="_blank">#<?php echo $item->auto_pr_number;?></a>
		</div>
		</td>
		<td><span id="<?php echo $item->id;?>_item_name"><?php echo $item->pr_item_name;?></span></td>
		<td><?php echo $item->pr_item_unit;?></td>
		<td><?php echo $item->ordered_quantity;?></td>
		<td><span id="<?php echo $this->escapeHtml($item->id);?>_delivered_quantity"><?php echo $item->delivered_quantity;?></span></td>
		<td><?php echo $item->confirmed_balance;?></td>
		
		<?php if($item->confirmed_balance == 0): ?>
				<td><?php echo date_format(date_create($item->EDT),"Y-m-d");?></td>
				<td><span class="label label-success">Fulfilled</span></td>
		<?php else: ?>
		
			<td>
			<span id="<?php echo $item->id;?>_EDT">
			<?php echo date_format(date_create($item->EDT),"Y-m-d");?></span>
			<div>
					<span style="color: gray; font-size: 8pt; font-style: italic;"
						id="<?php echo $item->id;?>_timer"></span>
			</div>
			
			</td>
		<?php endif; ?>
		<td>
		<a href="#" onclick="openDeliveryConfirmation('<?php echo $item->id;?>','<?php echo $this->baseUrl ?>/procurement/do/confirm-do?dn_item_id=<?php echo $item->id;?>&pr_item_id=<?php echo $item->pr_item_id;?>&sparepart_id=<?php echo $item->sparepart_id;?>&article_id=<?php echo $item->article_id;?>&asset_id=<?php echo $item->asset_id;?>&dn_id=<?php echo $item->delivery_id;?>');">CONFIRM</a>
		
		</td>
		

		
		
		<script language="javascript">
			id_array.push(<?php echo $item->id;?>);
		</script>
	<?php endforeach; ?>

 			</tr>		

</tbody>
</table>
	
<?php else:


	echo '<div class="alert alert-info">';
	echo 'No Notifications!';
	echo '</div>';


endif;?>	

<!-- Modal -->
	<div id="myModal" class="modal hide" role="dialog">
	  <div class="modal-dialog">
	  	 <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h5 class="modal-title">Delivery Confirmation:</h5>
      </div>
	      <div class="modal-body">
	  <div>
	  <span id="_status"></span>
	  <span id="_uri"></span>
	  </div>

<form class="form-horizontal" action=""	method="post" enctype="multipart/form-data" id="NewSP" >
<input type="hidden" name="article_id" id ="item_id" value="" />
	 <div class="control-group">
        <label class="control-label" for="inputTag">Item Name:</label>
        <div class="controls">
          <input readonly type="text" id="item_name" placeholder="" name="item_name" value="">
        </div>
      </div>
 	
	  <div class="control-group">
        <label class="control-label" for="inputTag">Delivered Quantity:</label>
        <div class="controls">
          <input readonly type="text" id="delivered_quantity" placeholder="" name="delivered_quantity" value="">
        </div>
      </div>
      
      <div class="control-group">
        <label class="control-label" for="inputTag">Confirmed Quantity:</label>
        <div class="controls">
          <input type="text" id="confirmed_quantity" placeholder="" name="name" value="article">
        </div>
      </div>
      
       <div class="control-group">
        <label class="control-label" for="inputTag">Rejected Quantity:</label>
        <div class="controls">
          <input readonly type="text" id="rejected_quantity" placeholder="" name="quantity" value="">
        </div>
      </div>
      
       
       <div class="control-group">
        <label class="control-label" for="inputDescription">Reason /Remarks:</label>
        <div class="controls">
          <textarea id="confirmation_remarks" placeholder="" rows="2" cols="5" name=""></textarea>
        </div>
      </div>
    </form>
	   </div>
	      
		  <div class="modal-footer">
	        <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
	        <button onclick="doConfirmDelivery();" type="button" class="btn btn-primary">SEND</button>
	      </div>
	   </div>
	</div>
	
	<!-- Modal -->
	<div id="myModal1" class="modal hide" role="dialog">
	  <div class="modal-dialog">
	      <div class="modal-body">
	        <p>Working on it........Please Wait!</p>
	      </div>
	   </div>
	</div>			
