<h4>Delivery:</h4>

<?php echo $total_items . ' Delivers found'?>
<table class="table table-striped table-bordered">
<thead>
<tr>	
		<td><b>No.</b></td>
		<td><b>Name</b></td>
		<td><b>Description</b></td>
		<td><b>Status</b></td>
		<td><b>Updated on</b></td>
		<td><b>Action</b></td>
	</tr>
</thead>
<tbody>	
 
  <?php 
	 
	 $count = 0;
	 foreach ($deliveries as $item) : 
	 	 $count++;
	 //echo  ($count % 2 == 1) ? "<tr>" : "<tr class=\"pure-table-odd\">";
	 ?>
	 <tr>
 		<td><?php echo ($paginator===null)? $count:$paginator->minInPage -1+ $count;?></td>
		<td><?php echo $item->dn_number;?> <span class="label label-info"><?php echo $item->total_items;?></span></td> 	
		<td><?php echo $item->description;?></td>
		<td><?php echo $item->last_status;?></td>
		<td><?php echo date_format(date_create($item->last_status_on),"Y-m-d");?></td>
		
		<td>
		<?php if ($item->last_status==null):?> 
		<a
			href="<?php echo $this->baseUrl ?>/procurement/delivery/create-step2?dn_id=<?php echo $item->id;?>">Edit
		</a>
		
		<?php else: ?>
		<a
			href="<?php echo $this->baseUrl ?>/procurement/do/show?dn_id=<?php echo $item->id;?>">Show
		</a>
		
		
		<?php endif;?>
	</td>
<?php endforeach; ?>
</tbody>
</table>


<?php
	
	if (! is_null ( $paginator )) {
		
		// change it only
		$base = $this->baseUrl . '/procurement/do/list';
		
		$_connector_symbol = '?';
		
		$last = $base . $_connector_symbol . 'page=' . $paginator->totalPages . '&perPage=' . $paginator->resultsPerPage;
		$first = $base . $_connector_symbol . 'page=1&perPage=' . $paginator->resultsPerPage;
		
		$p1 = ($paginator->page) - 1;
		$p2 = ($paginator->page) + 1;
		
		$prev = $base . $_connector_symbol . 'page=' . $p1 . '&perPage=' . $paginator->resultsPerPage;
		$next = $base . $_connector_symbol . 'page=' . $p2 . '&perPage=' . $paginator->resultsPerPage;
		
		echo '<ul class="pagination">';
		
		if ($paginator->page != 1 and $paginator->totalPages > 10) {
			echo '<li><a href="' . $first . '"> |< </a></li>';
			echo '<li><a href="' . $prev . '"> < </a></li>';
		}
		
		for($i = $paginator->minInPageSet; $i <= $paginator->maxInPageSet; $i ++) {
			
			$url = $base . $_connector_symbol . 'page=' . $i . '&perPage=' . $paginator->resultsPerPage;
			
			if ($i == $paginator->page) {
				echo '<li><a class="active" href="#">' . $i . '</a></li>';
			} else {
				echo '<li><a href="' . $url . '"> ' . $i . ' </a></li>';
			}
		}
		if ($paginator->page != $paginator->totalPages and $paginator->totalPages > 10) {
			echo '<li><a href="' . $next . '"> > </a></li>';
			echo '<li><a href="' . $last . '"> >| </a></li>';
		}
		echo '</ul>';
	}
	
	?>