<?php include (ROOT.'\module\Procurement\view\procurement\menu.php'); ?>
<script language="javascript">
			var id_array = [];
</script>

<div class="panel-group">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h5 class="panel-title">
          <a data-toggle="collapse" href="#collapse1"><?php echo $dn!==null ? '<h5>Deliver Note (DN): '. $dn->dn_number.'</h5>':"" ?></a>
        </h5>
      </div>
      <div id="collapse1" class="panel-collapse collapse in">
        <div class="panel-body">
        
     <?php if ($dn!==null)
{
echo '<div class="alert alert-info">';
	
	 echo '<ul>';
	 if($dn->dn_last_status == null):
	 	echo '<li>Status	: <strong> Started</strong></li>';
	 else:
		 echo '<li>Status	: <strong>' .$dn->dn_last_status	 . '</strong></li>';	 
	 endif;
	 echo '<li>Total Items	: <strong>' .$dn->totalItems	 . '</strong></li>';
	 
	 
		 
	 echo '</ul>';
	 echo '</div>';
} 
?>
        </div>
     </div>
    </div>
  </div>        

<?php if($dn->dn_last_status == null):?>
 <div class="dropdown">
    <button class="btn btn-default dropdown-toggle" type="button" id="menu1" data-toggle="dropdown">Add delivery Items
    <span class="caret"></span></button>
    <ul class="dropdown-menu" role="menu" aria-labelledby="menu1">
      <li role="presentation"><a role="menuitem" tabindex="-1" href="<?php echo $this->baseUrl ?>/procurement/delivery/select-from-list1?dn_id=<?php echo $dn->id?>"><i class="icon-plus">  </i> Select item from PR list</a></li>
      </ul>
       <button type="button" onclick="completeNotifyDNConfirm('<?php echo $dn->id?>');" class="btn"> Complete & Notify Requester <i class="icon-bullhorn"> </i></button>
 
  </div>
 <?php endif;?>
<p> 
<a href="/application/pdf/dn?id=<?php echo $dn->id ?>"  target="_blank"><i class="icon-print">  </i> Print (PDF)</a>    	
</p>
<table class="table table-striped table-bordered">
<thead>
	<tr>	
		<td><b>No.</b></td>
		<td><b>Requester</b></td>
		<td><b>Name</b></td>
		<td ><b data-toggle="tooltip" title = "Ordered Quantity">Q'ty</b></td>
		<td ><b data-toggle="tooltip" title = "Delivered Quantity">Del.</b></td>
		<td><b>Unit Price</b></td>
		<td><b>Total</b></td>
		<td><b>Currency</b></td>
		
		</tr>
</thead>
<tbody>	
 
  <?php 
	 
	 $count = 0;
	 foreach ($dn_items as $item) : 
	 	 $count++;
	 //echo  ($count % 2 == 1) ? "<tr>" : "<tr class=\"pure-table-odd\">";
	 ?>
	  <tr>
 		<td><?php echo $count;?></td>
		<td><?php echo $item->firstname . ' ' . $item->lastname ;?>
			<div style="color: gray; font-size: 8pt;">
			<a style="color: black; font-size: 8pt;" href="<?php echo $this->baseUrl ?>/procurement/pr/show?pr_id=<?php echo $item->purchase_request_id;?>"
				target="_blank">#<?php echo $item->auto_pr_number;?></a>
			</div>
		
		</td>
	 	<td><?php echo $item->name;?>
		 	<div style="color: gray;">
				Code: <?php echo $this->escapeHtml($item->code);?><br>
			</div>
	 	</td>
	 	<td><?php echo $item->quantity;?></td>
		<td><?php echo $item->delivered_quantity;?></td>
		<td><?php echo $item->price;?></td>
		<td><?php echo ($item->price*$item->delivered_quantity);?></td>
		<td><?php echo $item->currency;?></td>
		
		<script language="javascript">
			id_array.push(<?php echo $item->id;?>);
		</script>
<?php endforeach; ?>
</tr>
</tbody>
</table>

	<!-- Modal -->
	<div id="myModal" class="modal hide" role="dialog">
	  <div class="modal-dialog">
	  	 <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h5 class="modal-title">Mascot International (Laos)</h5>
      </div>
	      <div class="modal-body">
	        <p>Do you want to complete this deliver  and notify the requester?</p>
	      </div>
	      
		  <div class="modal-footer">
	        <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
	        <button onclick="completeNotifyDN('<?php echo $dn->id?>');" type="button" class="btn btn-primary">OK</button>
	      </div>
	   </div>
	</div>	
	
	<!-- Modal -->
	<div id="myModal1" class="modal hide" role="dialog">
	  <div class="modal-dialog">
	      <div class="modal-body">
	        <p>Sending data........Please Wait!</p>
	      </div>
	   </div>
	</div>	
		
	
	
	
