<ul>
	<li><a href="#general">Valuation method: FIFO</a></li>
	<li><a href="#general">Minimum in Stock</a></li>
	<li><a href="#general">Maximum in stock</a></li>
</ul>


<div id="tabs3" style="font-size: 9.5pt;color: graytext ; margin: 2pt 2pt 0pt 2pt">
	<ul>
		<li><a href="#onhand">On-Hand</a></li>
		<li><a
			href="<?php echo $this->baseUrl ?>/inventory/stock/returned-item?token=<?php echo (!$target == null)? $target->getToken():"";?>&target_id=<?php echo (!$target == null)? $target->getId():"";?>&checksum=<?php echo (!$target == null)? $target->getChecksum():"";?>"><?php echo $this->translate("Exchanged");?></a></li>
		<li><a
			href="<?php echo $this->baseUrl ?>/inventory/stock/disposed-item?token=<?php echo (!$target == null)? $target->getToken():"";?>&target_id=<?php echo (!$target == null)? $target->getId():"";?>&checksum=<?php echo (!$target == null)? $target->getChecksum():"";?>"><?php echo $this->translate("Disposal");?></a></li>
		<li><a
			href="<?php echo $this->baseUrl ?>/inventory/item-transaction/list1?token=<?php echo (!$target == null)? $target->getToken():"";?>&target_id=<?php echo (!$target == null)? $target->getId():"";?>&checksum=<?php echo (!$target == null)? $target->getChecksum():"";?>"><?php echo $this->translate("All");?></a></li>

	</ul>

	<div id="onhand" style="font-size: 9.5pt; padding: 2pt 10pt 10pt 2pt"">

<?php

if ($total_records <= 0) :

    echo 'No record found!';
else :

    if (! is_null($paginator)) {
        echo 'Record ' . $paginator->minInPage . ' to ' . $paginator->maxInPage . ' | ' . $total_records . ' records found!';
    } else {
        echo $total_records . ' records found!';
    }

    ?>

<table style="font-size: 9pt;" class="table table-bordered table-hover">
			<thead>
				<tr>
					<td><b>#</b></td>
					<td><b><?php echo $this->translate("Warehouse");?></b></td>
					<td><b><?php echo $this->translate("Posting Date");?></b></td>			
					<td><b><?php echo $this->translate("Posted Qty");?></b></td>
					<td><b><?php echo $this->translate("On-hand Qty");?></b></td>
					<td><b><?php echo $this->translate("Unit Price");?></b></td>
					<td><b><?php echo $this->translate("Stock Value");?></b></td>
					<td><b><?php echo $this->translate("Remark");?></b></td>
					<td><b><?php echo $this->translate("Action");?></b></td>
		
				</tr>
			</thead>

			<tbody>
 
	 <?php

    $count = 0;
    foreach ($list as $a) :

        /**@var \Application\Entity\NmtInventoryFifoLayer $a ; */
        $count ++;
        ?>
	 <tr>
					<td><?php echo ($paginator===null)? $count:$paginator->minInPage -1+ $count;?></td>
					<td>@todo</td>
					<td>	<?php echo date_format($a->getPostingDate(),"m-d-Y");?></td>
			
					<td>	<?php echo $a->getQuantity();?></td>
					<td>	<?php echo $a->getOnhandQuantity();?></td>
					<td>	<?php echo $a->getDocUnitPrice();?></td>
					<td>	<?php echo $a->getOnhandQuantity()*$a->getDocUnitPrice()*$a->getExchangeRate();?></td>

					<td>
			<?php echo $a->getRemarks();?>
			</td>
			<td>
			see Good Issue
			</td>
				</tr>
<?php endforeach; ?>

 </tbody>
		</table>

<?php endif; ?>

	</div>


</div>




<script type="text/javascript">
$("#create_item_form :input").attr("disabled", "disabled");
$( "#tabs3" ).tabs({
	beforeLoad:function(e,ui){
		$( ui.panel ).html('<p>Loading...</p>');       
	    },
	   
});
$( "#tabs3" ).tabs( "option", "active", 0 );
</script>
