
<?php
if (count($errors) > 0) {
    echo '<div class="alert alert-danger" role="alert" style="font-size: 10.5pt">';

    echo '<ul>';
    foreach ($errors as $error) :
        echo '<li>' . $error . '</li>';
    endforeach
    ;
    echo '</ul>';
    echo '</div>';
}
?>

<div id="tabs" style="font-size: 9.5pt">
	<ul>
		<li><a href="#general">Attachment upload</a></li>
	</ul>

	<div id="general" style="font-size: 9pt; padding-top: 0px"> 

<?php /**@var \Application\Entity\FinVendorInvoice $target ;*/ ?>

<h5 style="color: gray">
	 <?php echo (!$target== null)? 'Contract: ' . $target->getContractNo()."<br>":"";?>
	 <?php echo (!$target== null)? 'Invoice: ' . $target->getInvoiceNo():"";?>
</h5>

		<hr>

		<!-- TO UPDATE ACTION -->
		<form id="attachment_upload_form" class="form-horizontal"
			action="/hr/fingerscan/import" method="post"
			enctype="multipart/form-data">
			<input type="hidden" name="target_id"
				value="<?php echo (!$target == null)? $target->getId():"";?>" /> <input
				type="hidden" name="token"
				value="<?php echo (!$target== null)? $target->getToken():"";?>" /> <input
				type="hidden" name="redirectUrl" value="<?php echo $redirectUrl ?>" />



			<div class="form-group margin-bottom">
				<label class="control-label col-sm-2" for="inputTag">File:</label>
				<div class="col-sm-3">
					<input style="" type="file" id="uploaded_file" name="uploaded_file" />
				</div>
			</div>

			<hr>
			<div class="form-group margin-bottom">
				<label class="control-label col-sm-2" for="inputTag"></label>
				<div class="col-sm-3">
					<button type="submit" class="btn btn-default btn-sm">
						<i class="glyphicon glyphicon-upload"> </i> Upload
					</button>
				</div>
			</div>


		</form>
	</div>
</div>

<script type="text/javascript">
$('#attachments').bind('change', function() {
	var file_size;
	file_size = this.files[0].size
	if (file_size > 10485760){
		//alert('This file size is too large : ' + file_size + "MB. Please select new file");
		
		$('#b_loaded_data').text('This file size is too large : ' + file_size + "MB. Please select new file");
		$('#modal1').modal();

		 $("#attachments").val("");
		 	
	}else{
		//alert('This file size is: ' + file_size + "MB, OKE");
		 //$('#save').removeAttr('disabled');
	}

});

$( "input[id='valid_from']").datepicker({ firstDay: 1, dateFormat: 'yy-mm-dd',closeText: 'X',changeMonth: true, changeYear: true});
$( "input[id='valid_to']").datepicker({ firstDay: 1, dateFormat: 'yy-mm-dd',closeText: 'X',changeMonth: true, changeYear: true});


</script>

